### ISSUE TITLE
Generar script para la clasificación de las poblaciones (Grado de aislamiento de la población) #FOMIX

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#10]
**Objetivo:** Clasificar las poblaciones de acuerdo a las siguientes reglas: 

**Insumos:** 
@CorinaCantero  favor de colocar la capa de poblaciones, carreteras y el pdf  en la siguiente ruta 

Ruta: SIG\desarrollo\sig_fomix\procesamiento\clasificacion_poblaciones\insumos

**Comment by CorinaCantero** [comment]
@ofegarcia En este issue puedes encontrar lo referente a los mapas donde se clasifica la población, se hicieron basados en el documento "grado_dispersion_poblacional.pdf"

La carpeta con toda la información está ubicada en: FOMIX\fmx_insumos\fmx_estadisticas

**Comment by vichdzgeo** [comment]
# Grado de aislamiento de la población

La intensidad de la marginación en los asentamientos rurales tiende a aumentar
conforme éstos se encuentran alejados de las localidades de mayor tamaño y de las vías
de comunicación2. Para evaluar la conectividad según la condición de ubicación de las
localidades rurales, CONAPO ha definido cuatro categorías:

| categoria | definición |
| ---- | -----|
| a | cercanas a ciudades, ubicadas a **5** kilómetros o menos de una localidad de **15,000** o más habitantes |
| b         | cercanas a centros de población mixtos o en transición, localizadas a **2.5** kilómetros o menos de una localidad de **2,500**  a **14,999** habitantes |
| c         | cercanas a carreteras, situadas a **3** kilómetros o menos de un camino transitable durante todo el año                                                |
| d         | aísladas, categoría asginada la resto de las localidades rurales, alejadas de centros de población de mayor tamaño y de vías de comunicación           |

## Insumos


### Localidades


Contiene localidades tanto urbanas como rurales de Yucatán y hasta 3 kilométros
de distancía de los límites del estado. incluyendo algunas localidades de Quntana Roo y Campeche

ruta:SIG/desarrollo/sig_fomix/procesamiento/clasificacion_poblaciones/insumos/yucatan_loc_urb_rur_utm_v2.shp


### Carreteras

Contiene tramos carreteros y caminos que son transitables durante todo el año de Yucatán y hasta 3 kilómetros
de distancia de los límites del estado. Incliyedo algunos tramos de QuintanaRoo y Campeche

ruta: SIG/desarrollo/sig_fomix/procesamiento/clasificacion_poblaciones/insumos/red_carretera_final.shp


## Procedimiento


- Se crea el script  **grado_aislamiento_yuc.py** ubicado en la ruta: SIG\desarrollo\sig_fomix\procesamiento\clasificacion_poblaciones\
el cual clasifica las localidades deacuerdo a las cuatro categorías definidas por la CONAPO,
basadas en la distancía y tamaño de población.

la salida del script **grado_aislamiento_yuc.py** es un csv con dos columnas:

id =  el id correspondiente a la localidad 
clase_loc = la categoria (a,b,c o d)

posteriormente se une el csv para agregar el campo clase_loc a la capa de localidades y se guarda
en 
ruta: SIG/desarrollo/sig_fomix/procesamiento/clasificacion_poblaciones/salida/yucatan_loc_clasificacion_v2.shp

- Se crea el script **poblacion_d.py** el cual calula la variable de grado de aislamiento de la población (VGA)

VGA = pa/pt

VGA: Variable de Grado de Aislamiento de la población.
Pa: Población en condición de aislamiento en el municipio. (población de las localidades en categoria d)
Pt: Población total del mismo municipio.

la salida del script  **poblacion_d.py** es un csv que contiene:

CVE_MUN = Clave municipal 
pob_total = Población total del municipio
pop_d = Población total de las localidades en la categoria **d (aisladas)**
VGA = Variable de grado de Aislamiento de la población, 
El indicador se construye en una escala que va del 0 al 1, en donde el cero representa la
ausencia de personas en condiciones de aislamiento y el uno representa la totalidad de
habitantes del municipio en este tipo de condiciones


## Producto


1. la salida del script **grado_aislamiento_yuc.py** es un csv con dos columnas:

id =  el id correspondiente a la localidad 
clase_loc = la categoria (a,b,c o d)

posteriormente se une el csv para agregar el campo clase_loc a la capa de localidades y se guarda
en 
ruta: SIG/desarrollo/sig_fomix/procesamiento/clasificacion_poblaciones/salida/yucatan_loc_clasificacion_v2.shp




2. la salida del script  **poblacion_d.py** es un csv que contiene:

CVE_MUN = Clave municipal 
pob_total = Población total del municipio
pop_d = Población total de las localidades en la categoria **d (aisladas)**
VGA = Variable de grado de Aislamiento de la población, 


El indicador se construye en una escala que va del 0 al 1, en donde el cero representa la
ausencia de personas en condiciones de aislamiento y el uno representa la totalidad de
habitantes del municipio en este tipo de condiciones 
ruta: SIG/desarrollo/sig_fomix/procesamiento/clasificacion_poblaciones/salida/mun_vga.csv

## Bibliografía


ÍNDICE DE DISPERSIÓN POBLACIONAL PARA CHIAPAS
NOTA METODOLÓGICA, Dirección de Geografía, Estadística e Información
Subsecretaría de Planeación, Presupuesto y Egresos, Secretaría de Hacienda - Diciembre de 2010
