### ISSUE TITLE
Preparar página del curso de OE 

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#100]
Con base en contenido del curso viejo.

**Comment by dpedroza74** [comment]
Considero que lo prioritario es habilitar lo más pronto posible el de los representantes sectoriales en el comité
La cuestión es que no sirve el adobe flashplayer, pero hay una extensión que bajas a la compu que se llama ruffle nightly con el que se pueden ver 
https://proyectos.cuaed.unam.mx/educacion_continua/ordenamiento_ecologico/

Yo puse en esta carpeta de dropbox los videos que yo bajé como backup para que no perdiéramos el contenido, pero que no tienen la calidad para subirlos así
/ENTREGAS/curso_oe/video_curso_comite

**Comment by Nayita** [comment]
Se cierra este issue y se migra al repositorio de planeación colaborativa, issue #1107
