### ISSUE TITLE
Diseñar página de bitácora ambiental POETY# FOMIX

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/fomix#101]
### AVISO

Acuerdos de la reunión del 20 de agosto con @dpedroza74 

1. Las secciones que se estarán modificando son las secciones del submenú: @vichdzgeo 

  - Comité de Ordenamiento Ecológico

  - Participación pública

  - Estudio técnico

  - Programa de Ordenamiento Ecológico

  - Monitoreo y evaluación

2. Daniela hará una tabla con los diferentes tipos de archivos descargables para que @nadiaruiz ponga los nombres de los archivos

3. @nadiaruiz terminará el manual de edición en markdown y dará capacitación al respecto

4. Se presentó a @dpedroza74 el borrador de estructura de archivos que se estará utilizando para la formación de la página de la bitácora. @dpedroza74 descargó en instaló el programa (Atom) con el que hará los documentos en markdown

5. La forma de operar para la generación o actualización de información para la página web será la siguiente: @dpedroza74 generará o hará las actualizaciones de los archivos en markdown, avisará a @nadiaruiz vía issue de los cambios para que se suban. @nadiaruiz notificará vía issue de las actualizaciones subidas para que los diseñadores actualicen la página web

6. Pendiente reunión entre @vichdzgeo @dpedroza74 @nadiaruiz para ver funcionamiento del repositorio y estructura de archivos

**Comment by Nayita** [comment]
@Nayita 
Subí propuesta de estructura de documentos estructura_bitacora_poety
en dropbox FOMIX/fmx_estudio_tecnico/bitacora_ambiental

**Comment by Nayita** [comment]
@dpedroza74
 Listo el manual para edición de Markdown. Ruta:\FOMIX\fmx_estudio_tecnico\bitacora_ambiental
Archivo: manual_markdown.md

**Comment by Nayita** [comment]
### AVISO

Issue de trabajo interno

**Comment by Nayita** [comment]
@dpedroza74 

Listos los archivos en pdf en la siguiente ruta:
\FOMIX\fmx_estudio_tecnico\bitacora_ambiental\repositorio\sgc_poety\textos_md\recursos\pdf

**Comment by Nayita** [comment]
### AVISO

Listos los nombres de los archivos descargables.
Ruta:FOMIX\fmx_estudio_tecnico\bitacora_ambiental

**Comment by dpedroza74** [comment]
@Nayita 
Ya subí el material de la primera sesión del Órgano Ejecutivo para que por favor la subas a la página de www.poety-yucatan
FOMIX/fmx_estudio_tecnico/bitacora_ambiental/pdf/comite/1a_sesion_oe_poety
y se informe a los de DASS en GITLab

**Comment by Nayita** [comment]
@dpedroza74 
Se agregó el botón de presentación y orden del día. Sólo se tenía para la lista de asistencia y el acta en la página de www.poety-yucatan.

**Importante** que se coloquen los pdf en el repositorio de GitHub para que se puedan trasladar al repositorio de GitLab. Ruta: 
\FOMIX\fmx_estudio_tecnico\bitacora_ambiental\repositorio\sgc_poety\textos_md\recursos\pdf
Por esta ocasión, ya se copiaron los archivos a esta carpeta.

**Comment by dpedroza74** [comment]
@Nayita 
Subí a la carpeta FOMIX/fmx_estudio_tecnico/bitacora_ambiental/repositorio/sgc_poety/textos_md
un nuevo markdown **programa_oe.md** para que por favor le informes a Víctor de DASS se incluya como el texto explicativo en la sección "Programa de Ordenamiento Ecológico" en el menú de la bitácora del POETY

programa_oe.md

**Comment by Nayita** [comment]
@dpedroza74 

Archivo subido al repositorio de GitLab y hecha la notificación a DASS.

**Importante** considerar que todo archivo que se coloca en la carpeta de repositorio está listo para ser subido en el GitHub Desktop. Valdría la pena poner los archivos que DASS  directamente toma del Dropbox en una carpeta diferente, para evitar confusiones.

**Comment by paola-gp** [comment]
@Nayita 

- [x] Migrar directorio **ugas** de **https://gitlab.com/lancis-apc/sgc_poety/-/tree/master** a: **https://gitlab.com/lancis-apc/sgc_poety/-/tree/insumos**

**Comment by dpedroza74** [comment]
@Nayita 

- [x] Favor de quitar de la página inicial de yucatan-poety.com el texto de comité:

Comité de Ordenamiento Ecológico
El ordenamiento ecológico debe llevarse a cabo a través de un proceso de planeación colaborativa. El mecanismo principal para consolidar esta colaboración es el Comité de Ordenamiento Ecológico, instancia responsable de dar seguimiento al proceso y fortalecer su carácter participativo y transparente. El Comité se conforma con representantes de las dependencias gubernamentales y de los sectores que desarrollan actividades en el estado de Yucatán.

El Comité de Ordenamiento Ecológico tiene como objetivo:
(1)    verificar que el proceso de ordenamiento ecológico cumpla con lo estipulado en el marco legal;
(2)    facilitar la inclusión de los intereses y las necesidades sectoriales en el proceso;
(3)    establecer los mecanismos de diálogo y concertación necesarios para que el programa de ordenamiento ecológico sea legítimo y esté dirigido a enfrentar de manera efectiva los conflictos ambientales;
(4)    facilitar la coordinación entre las dependencias gubernamentales para asegurar que exista congruencia entre los planes, programas y acciones sectoriales que se aplican en el territorio;
(5)    dar seguimiento al estudio técnico que sustentará el programa de ordenamiento ecológico; y 
(6)    verificar que los avances del proceso se publiquen en la Bitácora Ambiental para mantener la transparencia y la rendición de cuentas.
Si desea más información sobre el Comité de Ordenamiento Ecológico lo invitamos a que revise la sección de Bitácora ambiental.
Si desea conocer los avances de la actualización del POETY le invitamos a que revise la sección de Estudio técnico.

- [x] Favor de incluir en la sección de Comité como texto introductorio lo que contiene el documento  **comite_poety** que está en la carpeta 
FOMIX\fmx_estudio_tecnico\bitacora_ambiental\word

- [x] incluir en el calendario la instalación del Órgano Técnico el día de hoy

**Comment by dpedroza74** [comment]
@Nayita  

No recuerdo si ahora que Esmeralda concluyó la nueva página del curso de OE se hizo el cambio en la página www. yucatan-poety-com de la liga al curso:
http://lancisapc.wixsite.com/cursooers

**Comment by Nayita** [comment]
@dpedroza74 
Se quitó la liga anterior. Pongo la nueva liga.

**Comment by Nayita** [comment]
### AVISO

El párrafo y la liga quedó insertado en la sección de Participación pública de la página web.

**Comment by paola-gp** [comment]
@Nayita 
### Observaciones al 9-dic-21

- [x] Hacer una copia respaldo de la última esta versión de la página para mantener control de versiones
- [x] No encuentro la liga al curso de ordenamiento en participación como se informó en el comentario previo anterior
- [x] Quitar en la sección de calendario lo de la ubicación a los talleres presenciales de pronóstico 
- [x] Eliminar el registro de los talleres de pronóstico 
- [x] Agregar documentos enviados por la SDS relacionados con la instalación del órgano técnico, preguntar sobre insumos a @dpedroza74 
- [x] Poner en el siguiente orden la sección de participación: (1) Análisis de aptitud, (2) talleres de pronóstico y (3) recepción de información y el resto en orden alfabético hasta abajo (sin lo de registro que ya es mucho)
- [x] En la página de recepción de información. Agrega una quinta viñeta que diga Geometría y topología completas

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
