### ISSUE TITLE
Preparar presentación para el órgano técnico #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#102]
**Carpeta de trabajo:** FOMIX\fmx_comite\sesiones_comite\presentaciones\introduccion

**Comment by Nayita** [comment]
### AVISO

Ruta de las figuras del curso:
CAPACITACION\cursos_no_formales\curso_oe\figuras

**Comment by Nayita** [comment]
### AVISO

Ruta de las figuras para la presentación:

FOMIX/fmx_comite/sesiones_comite/presentaciones/agosto_21/insumos

**Comment by Nayita** [comment]
@paola-gp 

Favor de revisar las figuras del curso para correcciones. Ruta: CAPACITACION\cursos_no_formales\curso_oe\figuras

Carpetas: 
- Proceso
- Marco legal
- Estudio técnico (en la figura: fi_mapa_aptitud.png, al usar la herramienta de 3D para voltear los mapas le pone una base gris a pesar de la transparencia, y si se le quita la base gris pone una blanca. Lo checo contigo para revisar de qué otra forma se puede hacer)
- Conceptos teóricos
- Comité

**Comment by paola-gp** [comment]
@dpedroza74 
en /FOMIX/fmx_comite/sesiones_comite/organo_tecnico/pr_fomix_organo_tecnico_9_nov_21.pptx 
está la última versión de la presentación para la sesión del órgano técnico del 9 de noviembre.

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
