### ISSUE TITLE
Generar procedimiento para análisis de grupos: Insumo para la generación de UGAS

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#103]
# Actividades:

### Procedimiento 1: 
- [x] Ajustar código de interval judgment para correr con las nuevas entradas @iaga
- [x] Correr los nuevos resultados y revisar las salidas @TatianaMerino 
- [x] Analizar las salidas @TatianaMerino @iaga 

### Procedimiento 2: 
- [x] Realizar markdown con histogramas, correlaciones, pruebas paramétricas y no paramétricas, etc. para analizar un grupo @TatianaMerino 
- [x] Crear un markdown con parámetros, generalizar el script y correr con todos los grupos @iaga 

## Otras actividades:
- [x] Documentar los insumos e indicar issue asociado @vichdzgeo 
- [x] Documentar el procedimiento final @TatianaMerino, @iaga 
- [x] https://github.com/lancis-apc/fomix/issues/105 @iaga @TatianaMerino

**Comment by iaga** [comment]
@vichdzgeo Indicar la sintaxis de la entrada dummy para el código

**Comment by vichdzgeo** [comment]
## Datos de prueba 

Base de datos en csv por pixel para el grupo 6, 


grupo | res_con | res_por_av
-- | -- | --
valor de grupo | residual de conservación para el grupo 6 | residual de porcino avícola para el grupo 6




</body>

</html>


@TatianaMerino @iaga 


[bd_grupo_6_res_con_porcino.zip](https://github.com/lancis-apc/fomix/files/7238283/bd_grupo_6_res_con_porcino.zip)

[bd_univar_residual_conservacion_n_100m.csv](https://github.com/lancis-apc/fomix/files/7238321/bd_univar_residual_conservacion_n_100m.csv)


[bd_univar_residual_porcino_avicola_n_100m.csv](https://github.com/lancis-apc/fomix/files/7238322/bd_univar_residual_porcino_avicola_n_100m.csv)

**Comment by TatianaMerino** [comment]
# Procedimiento 2: Análisis estadístico de grupos de aptitud 

Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos

**(a) Análisis de actividades por grupo** 
(e.g., comparación de aptitud de 13 actividades para el grupo "1")

**(b) Análisis de grupos por actividad** 
(e.g., comparación de aptitud en 13 grupos para la actividad "agricultura")

## a) Análisis de actividades para cada grupo
### Insumos
Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos\insumos\grupos
por @vichdzgeo 

Cada archivo csv contiene los datos de un grupo de aptitud. Las columnas son las actividades en el grupo. Los valores son la aptitud de cada pixel. 

### Código
Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos

Archivo: estadistico_grupos.Rmd

Procedimiento: grafica los histogramas de cada actividad, compara por pares las actividades (histograma y gráfica de cajas) y calcula la prueba no paramétrica Kolmogorov-Smirnov y la prueba paramétrica t de cada comparación. 

### Salidas
El archivo generar_markdowns.Rmd, por @iaga, permite generar html de cada grupo, los cuales se encuentran en: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos\salidas\html

## (b) Análisis de grupos para cada actividad
### Insumos
Generación de bases de datos a partir de los insumos del análisis **(a)**
Archivo: generar_insumos_actividades.Rmd
Salida: archivos csv en \analisis_ugas\analisis_grupos\insumos\actividades

Cada archivo csv contiene los datos de una actividad. Las columnas son los grupos de aptitud elegidos. Los valores son la aptitud de cada pixel. 

### Código
Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos

Archivo: estadistico_actividades.Rmd

Procedimiento: grafica los histogramas de cada grupo, compara por pares los grupos (histograma y gráfica de cajas) y calcula la prueba no paramétrica Kolmogorov-Smirnov y la prueba paramétrica t de cada comparación. 

### Salidas
pendientes por generar en TEMERARIA 

- [ ] html de cada actividad en: \propuesta\analisis_ugas\analisis_grupos\salidas

**Comment by TatianaMerino** [comment]
## AVISO

El código para las gráficas (histogramas individuales y grupales, correlaciones y boxplot) está en 
Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos

Archivo: **graficas_grupos.Rmd**

@iaga

**Comment by iaga** [comment]
# Revisión de últimos escenarios

Nombre del escenario | Versión de mapa de grupos | Descripción
-- | -- | --
e06 | grupos_v4 |  Incluye 13 sectores (sin pesca ni acuacultura) y **excluye ANP** federales y estatales. **10 sectores con OWA mínimo.** Turismo de naturaleza, turismo de sol y playa, urbano  con aptitud original. 
e07 | grupos_v1 | Incluye ANP Federales y Estatales. Mapa de aptitud de conservación sin incluir el ANP como aprovechamiento actual (tal cual sale de la plataforma)
**e07_b** | grupos_v4 | Incluye ANP Federales y Estatales. Mapa de aptitud de conservación sin incluir el ANP como aprovechamiento actual (tal cual sale de la plataforma) y el mapa de aptitud de urbano representado unicamente con la función de valor de crecimiento orgánico, reescalado.
e08 | grupos_v1 | Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 12 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. **1 sector con OWA mínimo: Bovino**
e09 | grupos_V1 | Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 11 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. **2 sectores con OWA mínimo: Bovino, Porcino avícola**
e10 |grupos_v1| Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 12 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. **1 sector con OWA mínimo: Forestal**
e11 |grupos_v1| Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 12 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. **1 sector con OWA mínimo: Porcino avícola**

**Comment by vichdzgeo** [comment]
## Aviso

Lista  la síntesis de grupos y los residuales del escenario e07_b

ruta:FOMIX\fmx_estudio_tecnico\propuesta\analisis_grupos

bd_grupos_v4_e07_b_6dic.xlsx

@iaga @TatianaMerino

**Comment by iaga** [comment]
# Análisis de los cortes para el escenario e07_b

Ruta:
\FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos\sintesis_grupos\sintesis_grupos_e07_v4.html

**Comment by iaga** [comment]
## Importante

Se dejó únicamente la versión final en la carpeta de FOMIX. Se realizó un respaldo con todas las versiones en CARPETAS_TRABAJO/igrave/FOMIX
