### ISSUE TITLE
Generación de indicadores por UGA para sistema #FOMIX #ET #Propuesta

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#104]
- **Extensión  (km²):**
- **Selva (%):** Uso de suelo y vegetación modificada en la costa con la capa de manglares, para el estado de Yucatán, serie VI (2014) - LANCIS 
- **Manglar (%):** Uso de suelo y vegetación modificada en la costa con la capa de manglares, para el estado de Yucatán, serie VI (2014) - LANCIS
- **Urbano (%):** Uso de suelo y vegetación modificada en la costa con la capa de manglares, para el estado de Yucatán, serie VI (2014) - LANCIS
_SIG\desarrollo\sig_fomix\procesamiento\areas_conservacion\procesamiento\inegi\series_corregidas\cobertura_usv_svi_16cats_costa_manglar.shp_
- **Número de humedales terrestres**: Humedales terrestres
- **Humedales terrestres (%)**: Humedales terrestres
- **Densidad de humedales terrestres**: Humedales terrestres
_SIG\desarrollo\sig_fomix\entregables\humedales\humedales_terrestres.shp_
- **Humedales costeros (%)**:  _SIG\desarrollo\sig_fomix\entregables\humedales\humedales_costeros.shp_
- **Calidad de parche de cobertura forestal (%):** _SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega\areas_conservar\ind_usv_serie6_progresiva_1_7.tif_
- **Número de parches de cobertura forestal prioritarios:**
_SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega\areas_conservar\evolucion_parches_s1_a_s1_coberturas_fid_s1.shp_ 
- **Riqueza de especies melíferas (%)**: _SIG\desarrollo\sig_fomix\insumos\agricultura\seduma\region_apicola\apicola_apiarios\riqueza_melifera.tif_
- **Biomasa árbórea (%):**
_SIG\desarrollo\sig_fomix\insumos\ambiente\mapa_biomasa_
- **Áreas prioritarias para la conservación (%):**
_SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega\areas_conservar\integracion_appcr_14jul_fuera_anps.shp_
_SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega\areas_conservar\integracion_appcr_14jul_dentro_anps.shp_
- **Áreas prioritarias para la restauración   (%):**
_SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega\areas_conservar\appcr_parches.shp_
-  **Índice de recarga al acuífero:** _SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega\insumos\recarga_promedio_batllori.shp_
- **Índice de vulnerabilidad del acuífero:**
SIG\desarrollo\sig_fomix\insumos\agua\dr_batllori\vuln_unidades_planeacion\INTERSECCION_VULNERABILIDAD_UNIDAD DE PLAN.shp_ **RASTERIZAR Y PROCESAR CAPA**
- **Susceptibilidad por inestabilidad de laderas (%):** CENAPRED 2020 (3 capas medio, alto y muy alto)
_SIG\desarrollo\sig_fomix\insumos\geocientifica\cenapred\inestabilidad_laderas_
- **Susceptibilidad a hundimientos (%):** [ATLAS PELIGROS por fenómenos naturales YUCATAN 2013](http://www.atlasnacionalderiesgos.gob.mx/AtlasEstatales/?&NOM_ENT=Yucat%C3%A1n&CVE_ENT=31) _SIG\desarrollo\sig_fomix\insumos\geocientifica\sgm\atlas_riesgos_portal_cenapred\hundimientos_
-  **Vulnerabilidad por incendios forestales (%)**: Mapa de áreas prioritarias de manejo del fuego del estado de Yucatán CONAFOR 2021. _SIG\desarrollo\sig_fomix\insumos\amc\conafor\manejo_fuego\manejo_fuego.shp_
- **Vulnerabilidad por inundaciones (%):** [(a) ATLAS PELIGROS por fenómenos naturales YUCATAN](http://www.atlasnacionalderiesgos.gob.mx/AtlasEstatales/?&NOM_ENT=Yucat%C3%A1n&CVE_ENT=31) 2013 o sustituto (b) **Indice de peligro por inundación, CENAPRED 2016** 
(a)_SIG\desarrollo\sig_fomix\insumos\amc\sgm\inundaciones_
(b)_SIG\desarrollo\sig_fomix\procesamiento\indice_riesgo\insumos\riesgo_inundaciones_yuc\indice_peligro_inundacion_cenapred_2016.shp_
-  **Riesgo por ciclones tropicales (%):** Grado de riesgo por ciclones tropicales hasta el 2015, [CENAPRED 2017](http://www.atlasnacionalderiesgos.gob.mx/portal/fenomenos/)
_SIG\desarrollo\sig_fomix\insumos\amc\cenapred\riesgo_ciclon_trop\riesgo_ciclontro_wgs84.shp_
- **Vulnerabilidad por cambio climático (%):** Vulnerabilidad de asentamientos humanos a inundaciones - [Atlas Nacional de Vulnerabilidad al cambio climático INECC 2018](https://atlasvulnerabilidad.inecc.gob.mx/page/index.html#zoom=8&lat=20.8405&lon=-88.6254&layers=1) 
_SIG\desarrollo\sig_fomix\entregables\sub_natural\vul_max_
- **Vulnerabilidad costera (%):**  ¿Papiit?

**Comment by CorinaCantero** [comment]
### AVISO
@vichdzgeo 

Favor de convertir las siguientes capas de kmz a shp:

- [ ] - SIG\desarrollo\sig_fomix\insumos\geocientifica\cenapred\inestabilidad_laderas
**No se pudieron procesar las capas porque no están en un formato adecuado- se solicitarán a la SDS** 
![image](https://user-images.githubusercontent.com/44783182/135174732-23f95bab-d663-433d-afe8-f998a97d4a33.png)

- [x] - SIG\desarrollo\sig_fomix\insumos\geocientifica\sgm\atlas_riesgos_portal_cenapred\hundimientos
- [x] - SIG\desarrollo\sig_fomix\insumos\amc\sgm\inundaciones
Se crea capa raster ya que la geometría presenta problemas topológicos: sgm_a_inundaciones_utm16n_yuc.tif
capa vectorial: a_inundaciones_utm16n_yuc.shp

**Comment by CorinaCantero** [comment]
### INSUMOS
- LANCIS (2021) 'Uso de suelo y vegetación, serie VI (2014) corregido en la costa con la capa de manglares, para el estado de Yucatán', escala: 1:250,000 . Laboratorio Nacional de Ciencias de la Sostenibilidad, Instituto de Ecología UNAM. Ciudad de México, México
- LANCIS (2021). 'Humedales terrestres' Escala: sin dato .Laboratorio Nacional de Ciencias de la Sostenibilidad, Instituto de Ecología UNAM. Ciudad de México, México.
- LANCIS (2021). 'Humedales costeros' Escala: sin dato.Laboratorio Nacional de Ciencias de la Sostenibilidad, Instituto de Ecología UNAM. Ciudad de México, México.
- LANCIS (2021). 'Calidad de parches serie VI (2014).' Escala: 1:250,000 .Laboratorio Nacional de Ciencias de la Sostenibilidad, Instituto de Ecología UNAM. Ciudad de México, México.
- LANCIS (2021). 'Parches importantes' Escala: 1:250,000 .Laboratorio Nacional de Ciencias de la Sostenibilidad, Instituto de Ecología UNAM. Ciudad de México, México.
- SEDUMA (2005). 'Riqueza melífera'. Sin escala. Secretaría de Desarrollo Urbano y Medio Ambiente.
- Hernández-Stefanoni, J. (2021). 'Biomasa aérea'. Escala: sin dato. Centro de Investigación Científica de Yucatán (CICY)
- LANCIS (2021). 'Áreas prioritarias para la protección, preservación y conservación fuera de las Áreas Naturales Protegidas' Escala: 1:250,000 .Laboratorio Nacional de Ciencias de la Sostenibilidad, Instituto de Ecología UNAM. Ciudad de México, México.
- LANCIS (2021). 'Áreas prioritarias para la protección, preservación y conservación dentro de las Áreas Naturales Protegidas' Escala: 1:250,000 .Laboratorio Nacional de Ciencias de la Sostenibilidad, Instituto de Ecología UNAM. Ciudad de México, México.
- Batllori-Sampedro, E., y Canto-Mendiburu, S. (sin año) 'Recarga promedio 2004-2008'. Escala: sin dato
- Batllori-Sampedro, E. y Canto-Mendiburu, S. (2021). 'Vulnerabilidad intrínseca del acuífero en el Estado de Yucatán'. Escala: sin dato. 
- CENAPRED (2020) 'Mapa Nacional de Susceptibilidad por Inestabilidad de Laderas.' Escala: sin dato. Centro Nacional de Prevención de Desastres. Proveedor de la información: Portal del Atlas Nacional de Riesgos CENAPRED http://www.atlasnacionalderiesgos.gob.mx/portal/fenomenos/ 
- SGM (2013) 'Mapa de susceptibilidad a hundimiento del terreno en el estado de Yucatán.' Escala: sin dato. Servicio Geológico Mexicano. Proveedor de la información: Portal del Atlas Estatal de Riesgos del estado de Yucatán CENAPRED http://www.atlasnacionalderiesgos.gob.mx/AtlasEstatales/?&NOM_ENT=Yucat%C3%A1n&CVE_ENT=31
- CONAFOR (2021) 'Mapa de Áreas Prioritarias de Manejo de Fuego'. Escala: 1:250,000. México. Comisión Nacional Forestal
- SGM (2013) 'Mapa de susceptibilidad del terreno a inundaciones pluviales.' Escala: sin dato. Servicio Geológico Mexicano. Proveedor de la información: Portal del Atlas Estatal de Riesgos del estado de Yucatán CENAPRED http://www.atlasnacionalderiesgos.gob.mx/AtlasEstatales/?&NOM_ENT=Yucat%C3%A1n&CVE_ENT=31
- CENAPRED (2016) 'Índice de peligro por inundación.' Escala: sin dato. Centro Nacional de Prevención de Desastres. Proveedor de la información: Portal del Atlas Nacional de Riesgos CENAPRED http://www.atlasnacionalderiesgos.gob.mx/portal/fenomenos/ 
- CENAPRED (2017) 'Grado de riesgo por Ciclones tropicales hasta el 2015.' Escala: sin dato. Centro Nacional de Prevención de Desastres. Proveedor de la información: Portal del Atlas Nacional de Riesgos CENAPRED http://www.atlasnacionalderiesgos.gob.mx/portal/fenomenos/ 
- INECC-SEMARNAT (2018) 'Vulnerabilidad de los asentamientos humanos por inundaciones.' Escala: sin dato. Proveedor de la información: Portal del 'Atlas Nacional de Vulnerabilidad al Cambio Climático' https://atlasvulnerabilidad.inecc.gob.mx/

**Comment by paola-gp** [comment]
@iaga @TatianaMerino @dpedroza74 

### Las fichas de UGA llevarán la siguiente información (PARTE 1):


#### 1. Tabla de síntesis (bd_indicadores_basicos)

| Indicador                                             | Valor | Indicador                                                                        | Valor    |
|-------------------------------------------------------|-------|----------------------------------------------------------------------------------|----------|
| Extensión (km²):                                      | 104.1 | Áreas prioritarias para la conservación (%):                                     | 49       |
| Selva (%):                                            | 64    | Áreas prioritarias para la restauración (%):                                     | 35       |
| Manglar (%):                                          | 0     | Índice de recarga al acuífero:                                                   | Muy alto |
| Urbano (%):                                           | 1     | Índice de vulnerabilidad del acuífero:                                           | Alto     |
| Número de humedales terrestres:                       | 258   | Susceptibilidad por inestabilidad de laderas (%):                                | 12       |
| Humedales terrestres (%):                             | 12    | Susceptibilidad a hundimientos (%):                                              | 0        |
| Densidad de humedales terrestres:                     | 23    | Susceptibilidad a incendios forestales (%):                                      | 14       |
| Humedales costeros (%):                               | 0     | Peligro por inundaciones (%)                                                     | 15       |
| Calidad de parche de cobertura forestal (%):          | 52    | Riesgo por ciclones tropicales (%):                                              | 26       |
| Número de parches de cobertura forestal prioritarios: | 3     | Vulnerabilidad costera (%):                                                      | 0        |
| Riqueza de especies melíferas (%):                    | 41    | Vulnerabilidad de asentamientos humanos a inundaciones por cambio climático (%): | 14       |
| Biomasa árbórea (%):                                  | 59    | Indice extra:                                                                    | x        |
| Índice extra:                                         | x     | Índice extra:                                                                    | x        |

#### 2. Lista de sectores prioritarios (del análisis de optimización de actividades)


| id_grupo | lista_id_sector_prio |
|----------|----------------------|
| 1        | 1,4,6,8              |
| 2        | 3,6,8,9,11           |
| 3        | 5,7                  |
| 4        | 10,1                 |
| 5        | 4,6,8,13             |
| 6        | 7,11,16              |
| 7        | 4,7,15               |
| 8        | 4,6,8,13,16          |
| 9        | 5,7,8                |
| 10       | 1,2,3,4,5            |
| 11       | 6,7,8,9,10           |
| 12       | 1,2,3,4,5            |
| 13       | 1,3,5,6,13,14        |
| 14       | 3,4,5                |
| 15       | 5,6                  |
| 16       | 4,6,7,8              |
| 17       | 1                    |
| 18       | 3,5                  |
| 19       | 6,8,10               |
| 20       | 7,14,15,16           |

#### La tabla anterior se alimenta en la estructura de la base de datos:
| id_sector | sector_nombre              |
|-----------|----------------------------|
| 1         | Acuacultura de agua dulce  |
| 2         | Acuacultura salobre        |
| 3         | Agricultura tecnificada    |
| 4         | Apicultura                 |
| 5         | Conservación               |
| 6         | Energía                    |
| 7         | Forestal                   |
| 8         | Industrial                 |
| 9         | Milpa maya                 |
| 10        | Minería                    |
| 11        | Pecuario bovino            |
| 12        | Pecuario porcino y avícola |
| 13        | Pesca                      |
| 14        | Turismo de naturaleza      |
| 15        | Turismo de sol y playa     |
| 16        | Urbano                     |

#### 5. La tabla de conflictos ambientales
| Conflictos ambientales          |           |                                              |                  |            |
|---------------------------------|-----------|----------------------------------------------|------------------|------------|
| Supuesto                        | Prioridad | Sectores en conlficto                        | Superficie (km²) | Severidad  |
| Aptitud sectorial               | 1         | Conservación afecta Pecuario bovino          | 81.2             | Muy alta   |
|                                 | 2         | Agricultura tecnificada afecta Milpa maya    | 104.5            | Muy alta   |
|                                 | 3         | Agricultura tecnificada afecta Apicultura    | 115.24           | Muy alta   |
| Minimizar riesgo a la inversión | 1         | Conservación afecta Pecuario bovino          | 42.35            | Alta       |
|                                 | 2         | Agricultura tecnificada afecta Apicultura    | 14.27            | Muy alta   |
|                                 | 3         | Pecuario porcino y avícola afecta Apicultura | 73.24            | Muy alta   |
| Maximizar áreas de conservación | 1         | Conservación afecta Pecuario porcino         | 24.12            | Alta       |
|                                 | 2         | Pecuario porcino y avícola afecta Apicultura | 13.85            | Moderada   |
|                                 | 3         | Agricultura tecnificada afecta Milpa maya    | 15.82            | Moderada   |

#### Esta tabla se alimenta de la tabla de conflictos en el siguiente formato (es un ejemplo inventado):
| Acuacultura de agua dulce  | Acuacultura salobre | Agricultura tecnificada | Apicultura | Conservación | Energía | Forestal | Industrial | Milpa maya | Minería | Pecuario bovino | Pecuario porcino y avícola | Pesca | Turismo de naturaleza | Turismo de sol y playa | Urbano |   |
|----------------------------|---------------------|-------------------------|------------|--------------|---------|----------|------------|------------|---------|-----------------|----------------------------|-------|-----------------------|------------------------|--------|---|
| Acuacultura de agua dulce  | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Acuacultura salobre        | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Agricultura tecnificada    | 0                   | 0                       | 0          | 1            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 1 |
| Apicultura                 | 0                   | 0                       | 0          | 0            | 0       | 1        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Conservación               | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 1                      | 0      | 0 |
| Energía                    | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Forestal                   | 0                   | 1                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Industrial                 | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Milpa maya                 | 0                   | 0                       | 0          | 1            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Minería                    | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 1       | 0               | 0                          | 0     | 0                     | 0                      | 1      | 0 |
| Pecuario bovino            | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Pecuario porcino y avícola | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Pesca                      | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Turismo de naturaleza      | 0                   | 1                       | 0          | 0            | 0       | 0        | 1          | 0          | 0       | 1               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Turismo de sol y playa     | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |
| Urbano                     | 0                   | 0                       | 0          | 0            | 0       | 0        | 0          | 0          | 0       | 0               | 0                          | 0     | 0                     | 0                      | 0      | 0 |

### continuará...

**Comment by vichdzgeo** [comment]
## Base de datos de indicadores por UGA



### Ultima versión de indicadores por UGA 

total de UGAS: 175

[bd_ugas_yucatan_anp_indicadores_12feb.xlsx](https://github.com/lancis-apc/fomix/files/8056471/bd_ugas_yucatan_anp_indicadores_12feb.xlsx)

@paola-gp 


```
#OBSOLETO
### UGAs con zonificación dentro de ANPs

Total de UGAs: 193

archivo: [bd_ugas_yucatan_indicadores.xlsx](https://github.com/lancis-apc/fomix/files/8034499/bd_ugas_yucatan_indicadores.xlsx)


### UGAs, sin zonificación dentro de ANPs
Total de UGAs: 177

[bd_ugas_yucatan_anp_indicadores.xlsx](https://github.com/lancis-apc/fomix/files/8045121/bd_ugas_yucatan_anp_indicadores.xlsx)

```

@TatianaMerino   @dpedroza74

**Comment by vichdzgeo** [comment]
### Generar proyectos de indicadores en SIGnature

Las unidades de los indicadores se encuentran en hectáreas

#### Proyectos

Cuenta: fomix

[Indicadores por UGA](http://pruebas.sigplanning.com.mx/signature/mapviewer/83/)

[Indicadores por municipio](http://pruebas.sigplanning.com.mx/signature/mapviewer/84/)

@paola-gp

**Comment by vichdzgeo** [comment]
## Diccionario de datos

última versión del diccionario de datos de indicadores.

ruta: FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\excel\diccionario_datos_25_abril_22.xlsx

@paola-gp @dpedroza74

**Comment by vichdzgeo** [comment]
## Figuras

ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\indicadores\figuras

ruta del proyecto: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\ugas\indicadores\indicadores_ugas_figuras.qgs

en espera de retroalimentación y comentarios para mejora de figuras @paola-gp 


![insumos_humedales_terrestres](https://user-images.githubusercontent.com/38017509/165840891-6c6270b5-97c5-47ac-9a0d-31cdea50c4cb.png)
![integridad_ecologica](https://user-images.githubusercontent.com/38017509/165840900-53263e21-9c95-459f-8e6e-a7b759687626.png)
![inundaciones_pluviales](https://user-images.githubusercontent.com/38017509/165840905-31fb6b8e-7afb-42dc-897e-1d489282ad0c.png)
![ramsar](https://user-images.githubusercontent.com/38017509/165840910-f17e0175-19f2-4982-b0a3-46d3a0614d03.png)
![recarga_acuifero](https://user-images.githubusercontent.com/38017509/165840912-7597c014-9ef8-4aed-a2d6-176168bc0a32.png)
![riqueza_especies](https://user-images.githubusercontent.com/38017509/165840916-c9791c1f-35d2-4e77-adde-6868125a697f.png)
![sus_incendios](https://user-images.githubusercontent.com/38017509/165840920-512cbb33-47d7-4fe3-9507-2803ea7bcbbd.png)
![susceptibilidad_hundimientos](https://user-images.githubusercontent.com/38017509/165840926-ff10e6e2-98f1-487f-b8fa-c2491c13347e.png)
![susceptibilidad_laderas](https://user-images.githubusercontent.com/38017509/165840929-16f1da07-e538-4cfe-942b-dbed220612d0.png)
![vulnerabilidad_acuifero](https://user-images.githubusercontent.com/38017509/165840934-a3639749-bcd6-416d-b8e1-a03d95438a52.png)

![insumos_humedales_costeros](https://user-images.githubusercontent.com/38017509/165840888-25d08182-1a45-4f21-af54-6ff233a5368e.png)

![humedal_costero](https://user-images.githubusercontent.com/38017509/165840880-a689c012-f337-4fb6-bc1f-1c34d72fc8e8.png)
 
![humedal_terrestre](https://user-images.githubusercontent.com/38017509/165840884-b98ecf4a-9828-4744-84a4-4b1c9f3b348b.png)

![anp](https://user-images.githubusercontent.com/38017509/165840849-fac9bdc9-9c2f-4f63-a430-418425cc01d7.png)
![asentamiento_humano](https://user-images.githubusercontent.com/38017509/165840858-1fb203ac-cbe4-4937-aef4-ed432257ed87.png)
![biomasa](https://user-images.githubusercontent.com/38017509/165840866-dbd8fd81-b817-475f-9f4c-6784756dffb2.png)
![cobertura_selva_manglar](https://user-images.githubusercontent.com/38017509/165840871-dd4c6b7d-e5da-49ca-8de9-e7b7f62419ad.png)
