### ISSUE TITLE
Generar script en R para la ubicación de Actividades en UGAS: Optimización

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#105]
## Objetivo:
Generar script en R para el problema de asignación, a partir del archivo en Excel **solver_conflictos.xlsx**, utilizando el paquete **lpSolve**.

## Insumos:
- Matriz con los residuales para cada grupo @vichdzgeo 
- Matriz de conflictos (no ponderada) https://github.com/lancis-apc/fomix/issues/85 @iaga
- Restricciones @TatianaMerino @iaga 

## Restricciones:
Se consideran tres restricciones:
- Restricción 1. Suma de las filas igual a 2
- Restricción 2. Suma de columnas mayor o igual que 1
- Restricción 3. Suma de cada par de conflictos, para todas las UGAS menor o igual que 1

## Otros parámetros:
- Maximizar 
- Problema binario

**Importante:** El número de actividades consideradas en los grupos debe ser igual al número de actividades en la matriz de residuales. Es necesario seleccionar en el código los sectores que quedan fuera del análisis.

**Comment by iaga** [comment]
## Carpeta de trabajo con los archivos de prueba
\CARPETAS_TRABAJO\igrave\avance_personal\optimizacion\asignacion_ugas\v1

### Insumos
- **matriz_ady_conflictos_yuc.csv**. La matriz no ponderada de conflictos (versión del 20 de septiembre), para todos los conflictos.
- **matriz_ady_conflictos_yuc_un_conflicto.csv**. Matriz con un conflicto.
- **matriz_ady_conflictos_yuc_dos_conflictos.csv**. Matriz con dos conflictos.
- **residuales.csv**. Archivo con los residuales que se usan en el ejemplo de Excel **solver_conflictos.xlsx**
- **restricciones3.csv** Matriz con los elementos de las restricciones para filas y columnas
- **restricciones4.csv** Matriz con los elementos de las restricciones para filas y columnas y ejemplo de dos restricciones en UGAS
- **bd_residuales_grupos_v10.csv** Archivo con los grupos en formato CSV

### Scripts
- **ugas.Rmd**. Contiene el ejemplo que viene el paquete **lpSolve** para la función **assign.cost** y la prueba con las restricciones para filas y columnas
- **ugas_v2.Rmd** Prueba para uno/dos conflictos
- **asignacion_ugas.Rmd** Versión final con las tres restricciones
- **asignacion_ugas_laplacian.Rmd** Versión de prueba con la tercera restricción definida a partir de la matriz Laplaciana. No se encontró la solución.

**Comment by iaga** [comment]
## Versión 1
Utiliza el paquete lpSolve para la asignación, dado cualquier número de UGAS y grupos, para las tres restricciones.

### Ruta
\FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\asignacion_ugas\v1

### Insumos

- **matriz_ady_conflictos_yuc.csv** La matriz no ponderada de conflictos (versión del 20 de septiembre), para todos los conflictos.
- **bd_residuales_grupos_v10.csv** Archivo con los grupos en formato CSV

### Script
- **asignacion_ugas.Rmd** Versión con las tres restricciones

**Comment by iaga** [comment]
## Actividades:

- Generalizar para correr distintos escenarios
- Generar htmls
- Incluir gráfica de residuales

@Nayita me puedes apoyar ubicando el script de residuales que hizo Luis en R?

**Comment by iaga** [comment]
## Versión 2
Utiliza el paquete lpSolve para la asignación, dado cualquier número de UGAS y grupos, para las tres restricciones.

### Ruta
\FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\asignacion_ugas\v2

### Insumos

- **matriz_conflictos_20sep21_sin_acuas_pesca.csv** La matriz no ponderada de conflictos (versión del 20 de septiembre, ultima actualización 29 sep), sin acuaculturas ni pesca.
- **bd_grupos_v6_e07_b_residuales.csv** Archivo con los grupos en formato CSV

### Script
- **asignacion_grupos.Rmd** Versión con las tres restricciones

### Salida
- **grupos_asignados.csv** Matriz con la asignación de grupos

**Comment by iaga** [comment]
## Versión 4: sin pesca ni acuaculturas (03 de febrero)
Utiliza el paquete lpSolve para la asignación, dado cualquier número de UGAS y grupos, para las tres restricciones.

### Observaciones

- Ya que no existe solución al problema de optimización con la matriz de conflictos final (versión no ponderada del 20 de septiembre, sin pesca ni acuaculturas), se exploraron los conflictos con intensidades mayores a 0.125 y 0.25. Finalmente, se usa la versión no ponderada de conflictos con intensidad mayor a 0.125 (**matriz_conflictos_yuc_bajo.csv**)
- A partir del insumo entregado por @vichdzgeo (**bd_residuales_ugas_yucatan.csv**) se divide el insumo entre las que no son ANP (**bd_residuales_ugas_yucatan_no_anp.csv**) y las que sí lo son (**bd_residuales_ugas_yucatan_si_anp.csv**).

### Ruta
\FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\asignacion_ugas\v4

### Insumos

- **matriz_conflictos_20sep21_sin_acuas_pesca.csv** La matriz no ponderada de conflictos (versión del 20 de septiembre, ultima actualización 29 sep), sin acuaculturas ni pesca, completa.
- **matriz_conflictos_yuc_mod_alto.csv** La matriz no ponderada de conflictos para los conflictos con intensidad mayor a 0.25
- **matriz_conflictos_yuc_bajo.csv** La matriz no ponderada de conflictos para los conflictos con intensidad mayor a 0.125
- **bd_residuales_ugas_yucatan.csv** Archivo con todas las UGAS en formato CSV
- **bd_residuales_ugas_yucatan_si_anp.csv** Archivo con las UGAS que no son ANP en formato CSV
- **bd_residuales_ugas_yucatan_no_anp.csv**Archivo con las UGAS que son ANP en formato CSV

### Scripts
- **Restricciones:** suma filas (<=4), suma columnas (>=1), conflictos (<=1)
- **asignacion_ugas_bajo_si_anp.Rmd** Versión con las tres restricciones, para las ANP
- **asignacion_ugas_bajo_no_anp.Rmd** Versión con las tres restricciones, para las que no son ANP

### Salida
- **ugas_yucatan_si_anp.csv** Matriz con la asignación de ugas para las ANP
- **ugas_yucatan_no_anp.csv** Matriz con la asignación de ugas para las no ANP
- **bd_ugas_yucatan_actividades.csv** Matriz con la asignación de actividades para todas las ugas

**Comment by iaga** [comment]
## Versión 5: se incluye pesca y acuaculturas
Utiliza el paquete lpSolve para la asignación, dado cualquier número de UGAS y grupos, para las tres restricciones.

### Observaciones

- Ya que no existe solución al problema de optimización con la matriz de conflictos final (versión no ponderada del 20 de septiembre, sin pesca ni acuaculturas), se exploraron los conflictos con intensidades mayores a 0.125 y 0.25. Finalmente, se usa la versión no ponderada de conflictos con intensidad mayor a 0.125 (**matriz_conflictos_yuc_bajo.csv**)
- Insumo **bd_residuales_ugas_yucatan_anp.xlsx**
- **ESTA VERSIÓN SE DESCARTA PORQUE EL MAPA DE APTITUD PESQUERA INCLUÍA PRÁCTICAMENTE A TODO EL ESTADO, se repite el análisis con restricciones (ver Versión 6)**

![imagen(2)](https://user-images.githubusercontent.com/41757755/153890447-6401293f-9320-42cc-b371-f6c42c739fc7.png)

### Ruta
\FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\asignacion_ugas\v5

### Insumos

- **matriz_conflictos_20sep21.csv** La matriz no ponderada de conflictos (versión del 20 de septiembre, ultima actualización 29 sep), completa.
- **matriz_conflictos_yuc_bajo.csv** La matriz no ponderada de conflictos para los conflictos con intensidad mayor a 0.125
- **bd_residuales_ugas_yucatan.csv** Archivo con todas las UGAS en formato CSV

### Scripts
- **Restricciones:** suma filas (<=4), suma columnas (>=1), conflictos (<=1)
- **asignacion_ugas_bajo_anp.Rmd** Versión con las tres restricciones, para las ANP


### Salida
- **ugas_yucatan_anp.csv** Matriz con la asignación de ugas

**Comment by iaga** [comment]
## Versión 6: se incluye pesca y acuaculturas RESTRINGIDAS
Utiliza el paquete lpSolve para la asignación, dado cualquier número de UGAS y grupos, para las tres restricciones.

- Mapa de aptitud restrictivo (most) de Acuacultura dulce
- Mapa de aptitud restrictivo (most) de Acuacultura salobre
- Mapa de aptitud restrictivo (most) de Pesca con datos únicamente en la zona ocupada por las UGAs del POETCY y valores  >= 0.6
- Acuaculturas solo con valores >= a 0.8
Insumo: **bd_residuales_ugas_yucatan_sin_acua_pesca_most_v5.xlsx**

(Ver comentarios https://github.com/lancis-apc/fomix/issues/96#issuecomment-1036453690 y https://github.com/lancis-apc/fomix/issues/96#issuecomment-1036618017)

### Observaciones

- Ya que no existe solución al problema de optimización con la matriz de conflictos final (versión no ponderada del 20 de septiembre, sin pesca ni acuaculturas), se exploraron los conflictos con intensidades mayores a 0.125 y 0.25. Finalmente, se usa la versión no ponderada de conflictos con intensidad mayor a 0.125 (**matriz_conflictos_yuc_bajo.csv**)


### Ruta
\FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\asignacion_ugas\v6

### Insumos

- **matriz_conflictos_completa.csv** La matriz no ponderada de conflictos (versión del 20 de septiembre, ultima actualización 29 sep), completa.
- **matriz_conflictos_yuc_bajo.csv** La matriz no ponderada de conflictos para los conflictos con intensidad mayor a 0.125
- **bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most_v5** Archivo con los residuales para todas las UGAS en formato CSV

### Scripts
- **Restricciones:** suma filas (<=4), suma columnas (>=1), conflictos (<=1)
- **asignacion_ugas_bajo.rmd** Versión con las tres restricciones, para las ANP


### Salida
- **ugas_yucatan_anp_sin_acu_pesca_most_v5.csv** Matriz con la asignación de ugas
- **ugas_pesca_acuaculturas.csv** Archivo que contiene únicamente la asignación de pescas y acuaculturas

### Importante
- El archivo con la asignación de pesca y acuaculturas (ugas_pesca_acuaculturas.csv) se utilizó por dpedroza para la asignación final de las actividades. Las asignación final es una combinación de la salida de la versión 4 (bd_ugas_yucatan_actividades.csv) y esta versión (bd_ugas_yucatan_actividades.csv)

**Comment by iaga** [comment]
@vichdzgeo favor de confirmar si existe algún otro cambio (distinto a los reportados en el issue https://github.com/lancis-apc/fomix/issues/96 en el banco de datos utilizado para la optimización: bd_residuales_ugas_yucatan_sin_acua_pesca_most_v5.xlsx)

- Mapa de aptitud restrictivo (most) de Acuacultura dulce
- Mapa de aptitud restrictivo (most) de Acuacultura salobre
- Mapa de aptitud restrictivo (most) de Pesca con datos únicamente en la zona ocupada por las UGAs del POETCY y valores  >= 0.6
- Acuaculturas solo con valores >= a 0.8

**Comment by vichdzgeo** [comment]
@iaga modifique tu comentario con los cambios realizados para esa corrida. por lo tanto quedan confirmados.

**Comment by iaga** [comment]
## Importante

Se dejaron únicamente las versiones finales en la carpeta de FOMIX. Se hizo un respaldo con todas las versiones en la ruta
\CARPETAS_TRABAJO\igrave\FOMIX\asignacion_ugas

**Comment by vichdzgeo** [comment]
## Actualización

## Generales



- mapa de agricultura restrictivo con zonas de aprovechamiento actual (unidades,distritos y cobertura de agricultura de riego y temporal USV VI LANCIS) 
- Exclusión de localidades en mapas de (agricultura, conservación, acuacultura dulce, acuacultura salobre, porcino)

### Residuales v1
insumos :mapas_aptitud_e07_b_con_acu_pesca_most_agri_most_ze_7marzo2022_v1.csv

- Exclusión en zonas con valores mayores o iguales a 0.25  de vulnerabilidad el acuífero 

[bd_residuales_ugas_yucatan_anp_7marzo2022_v1_025.xlsx](https://github.com/lancis-apc/fomix/files/8201216/bd_residuales_ugas_yucatan_anp_7marzo2022_v1_025.xlsx)

### Residuales v2

insumos : mapas_aptitud_e07_b_con_acu_pesca_most_agri_most_ze_7marzo2022_v2.csv

- Exclusión en zonas con valores mayores o iguales a 0.5  de vulnerabilidad el acuífero 

[bd_residuales_ugas_yucatan_anp_7marzo2022_v2_050.xlsx](https://github.com/lancis-apc/fomix/files/8201224/bd_residuales_ugas_yucatan_anp_7marzo2022_v2_050.xlsx)

@TatianaMerino

**Comment by TatianaMerino** [comment]
## Optimización de asignación de sectores a regular por UGA
07/03/2022

Insumos: 

- **matriz_conflictos_yuc_bajo.csv** La matriz no ponderada de conflictos para los conflictos con intensidad mayor a 0.125
- bd_residuales_ugas_yucatan_anp_7marzo2022_v1_025.xlsx
- bd_residuales_ugas_yucatan_anp_7marzo2022_v1_050.xlsx

Salidas:
[ugas_yucatan_anp_7marzo2022_v1_025.csv](https://github.com/lancis-apc/fomix/files/8201321/ugas_yucatan_anp_7marzo2022_v1_025.csv)
[ugas_yucatan_anp_7marzo2022_v2_050.csv](https://github.com/lancis-apc/fomix/files/8201323/ugas_yucatan_anp_7marzo2022_v2_050.csv)

@vichdzgeo

**Comment by vichdzgeo** [comment]
## Actualización 
 9 de marzo 2022

valores de -999 en residuales de pesca y porcino, donde los promedios tuviesen cero

**Promedios**
[bd_promedios_ugas_yucatan_anp_025_porcino_pesca_999_v1.xlsx](https://github.com/lancis-apc/fomix/files/8218190/bd_promedios_ugas_yucatan_anp_025_porcino_pesca_999_v1.xlsx)

**Residuales**
[bd_residuales_ugas_yucatan_anp_7marzo2022_v1_025_por_pes_999.xlsx](https://github.com/lancis-apc/fomix/files/8218191/bd_residuales_ugas_yucatan_anp_7marzo2022_v1_025_por_pes_999.xlsx)

**Resultados** @TatianaMerino 
[ugas_yucatan_anp_7marzo2022_v1_025_por_pes_999.csv](https://github.com/lancis-apc/fomix/files/8225654/ugas_yucatan_anp_7marzo2022_v1_025_por_pes_999.csv)

**Comment by vichdzgeo** [comment]
Actualización

10 de marzo 2022


valores de -999 en residuales de pesca,, tur sol y playa y porcino, donde los promedios tuviesen cero

Promedios

[bd_promedios_poety_uga_11feb22_10marzo2022_v1_025.xlsx](https://github.com/lancis-apc/fomix/files/8225900/bd_promedios_poety_uga_11feb22_10marzo2022_v1_025.xlsx)

Residuales
[bd_residuales_poety_uga_11feb22_10marzo2022_v1_025.xlsx](https://github.com/lancis-apc/fomix/files/8225901/bd_residuales_poety_uga_11feb22_10marzo2022_v1_025.xlsx)
@TatianaMerino

**Comment by vichdzgeo** [comment]
## Actualización

10 de marzo
valores de -999 en residuales de pesca,, tur sol y playa y porcino, donde los promedios tuviesen cero

Promedios
[bd_promedios_poety_uga_11feb22_10marzo2022_v2_025.xlsx](https://github.com/lancis-apc/fomix/files/8226370/bd_promedios_poety_uga_11feb22_10marzo2022_v2_025.xlsx)

Residuales

[bd_residuales_poety_uga_11feb22_10marzo2022_v2_025.xlsx](https://github.com/lancis-apc/fomix/files/8226371/bd_residuales_poety_uga_11feb22_10marzo2022_v2_025.xlsx)

@TatianaMerino 

**Resultados**
Con restricción de filas <= 5. Nota: con = 5 no hay solución
[uga_11feb22_10marzo2022_v2_025.csv](https://github.com/lancis-apc/fomix/files/8226778/uga_11feb22_10marzo2022_v2_025.csv)

**Script**
asignacion_ugas_bajo_anp_025_999.Rmd

**Comment by vichdzgeo** [comment]
## Actualización

se aplica restriccion de vulnerabilidad del acuifero 0.5 a los sectores de porcino y agricultura

Promedios 
[bd_promedios_poety_uga_11feb22_10marzo2022_v3_050.xlsx](https://github.com/lancis-apc/fomix/files/8226978/bd_promedios_poety_uga_11feb22_10marzo2022_v3_050.xlsx)

Residuales con todos los sectores

[bd_residuales_poety_uga_11feb22_10marzo2022_v3_050.xlsx](https://github.com/lancis-apc/fomix/files/8226980/bd_residuales_poety_uga_11feb22_10marzo2022_v3_050.xlsx)

Residuales sin acuaculturas 

[bd_residuales_poety_uga_11feb22_10marzo2022_v3_050_sin_acu.xlsx](https://github.com/lancis-apc/fomix/files/8226981/bd_residuales_poety_uga_11feb22_10marzo2022_v3_050_sin_acu.xlsx)

@TatianaMerino 

**Script**
asignacion_ugas_bajo_anp_050_sin_acua.Rmd

**Resultados**
Residuales: se utilizaron sin acuacultura
Restricciones: matriz_conflictos_yuc_bajo_sin_acua.csv

[uga_11feb22_10marzo2022_v3_050_sin_acu.csv](https://github.com/lancis-apc/fomix/files/8227070/uga_11feb22_10marzo2022_v3_050_sin_acu.csv)

**Comment by vichdzgeo** [comment]
## Actualización

Se agrega restriccion de vulnerabilidad del acuífero al mapa de mineria.

### Promedios
[bd_promedios_poety_uga_11feb22_10marzo2022_v4_050.xlsx](https://github.com/lancis-apc/fomix/files/8227892/bd_promedios_poety_uga_11feb22_10marzo2022_v4_050.xlsx)
### Residuales
[bd_residuales_poety_uga_11feb22_10marzo2022_v4_050.xlsx](https://github.com/lancis-apc/fomix/files/8227895/bd_residuales_poety_uga_11feb22_10marzo2022_v4_050.xlsx)

### Residuales sin acuícolas
[bd_residuales_poety_uga_11feb22_10marzo2022_v4_050_sin_acu.xlsx](https://github.com/lancis-apc/fomix/files/8227896/bd_residuales_poety_uga_11feb22_10marzo2022_v4_050_sin_acu.xlsx)

@TatianaMerino 

## Optimización

### Script

**asignacion_ugas_bajo_anp_050_sin_acua_min.Rmd** : corrida del modelo después de restringir minería por vulnerabilidad del acuífero; categorías mayores a 0.5 para esa restricción, porcícola y agricultura; con conflictos mayores a 0.125 

### Insumos

- **matriz_conflictos_yuc_bajo_sin_acua.csv** La matriz no ponderada de conflictos para los conflictos con intensidad mayor a 0.125 sin considerar acuacultura salobre y acuacultura dulce
- **bd_residuales_poety_uga_11feb22_10marzo2022_v4_050_sin_acu.xlsx**

### Resultados

[uga_11feb22_10marzo2022_v4_050_sin_acu.csv](https://github.com/lancis-apc/fomix/files/8227927/uga_11feb22_10marzo2022_v4_050_sin_acu.csv)

**Comment by vichdzgeo** [comment]
## Actualización 

Renumeración de UGAS

### Promedios

[bd_promedios_poety_uga_11mar22_10marzo2022_v4_050.xlsx](https://github.com/lancis-apc/fomix/files/8235545/bd_promedios_poety_uga_11mar22_10marzo2022_v4_050.xlsx)

### Residuales

[bd_residuales_poety_uga_11mar22_10marzo2022_v4_050.xlsx](https://github.com/lancis-apc/fomix/files/8235546/bd_residuales_poety_uga_11mar22_10marzo2022_v4_050.xlsx)

### Residuales sin acuacultura dulce y salobre
[bd_residuales_poety_uga_11mar22_10marzo2022_v4_050_sin_acu.xlsx](https://github.com/lancis-apc/fomix/files/8235547/bd_residuales_poety_uga_11mar22_10marzo2022_v4_050_sin_acu.xlsx)

### Residuales sin acuacultura dulce y salobre sin ANP

[bd_residuales_poety_uga_11mar22_10marzo2022_v4_050_sin_acu_sin_anp.xlsx](https://github.com/lancis-apc/fomix/files/8248900/bd_residuales_poety_uga_11mar22_10marzo2022_v4_050_sin_acu_sin_anp.xlsx)


@TatianaMerino

**Comment by vichdzgeo** [comment]
## Bases de datos

Áreas prioritarias por UGA

[bd_areas_poety_uga_11mar22_tp_appcr_marzo2022_v2.xlsx](https://github.com/lancis-apc/fomix/files/8236327/bd_areas_poety_uga_11mar22_tp_appcr_marzo2022_v2.xlsx)

![fig_prueba_cob_anp](https://user-images.githubusercontent.com/38017509/157985093-564c8ff2-9fe1-402a-aa85-e8517aa80c2a.png)


### Indicadores por UGA 
[bd_ugas_indicadores_11mar.xlsx](https://github.com/lancis-apc/fomix/files/8236440/bd_ugas_indicadores_11mar.xlsx)


@TatianaMerino

**Comment by TatianaMerino** [comment]
## Actualización de resultados de optimización 
Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\asignacion_ugas\v6\salidas

Se modificaron los ID de las UGAs 1-5
[uga_11feb22_10marzo2022_v4_050_sin_acu_v2.csv](https://github.com/lancis-apc/fomix/files/8236334/uga_11feb22_10marzo2022_v4_050_sin_acu_v2.csv)

El archivo **optimizacion_uga_10mar22.xlsx** genera la lista de sectores a partir de los resultados de la matriz

**Comment by TatianaMerino** [comment]
## Actualización optimización 14/mar/22

Se corrió la v4_050 con los residuales calculados sin ANP. 

**Insumos:** 

- RESIDUALES: bd_residuales_poety_uga_11mar22_10marzo2022_v4_050_sin_acu_sin_anp.xlsx
- SCRIPT: asignacion_ugas_bajo_anp_050_sin_acua_min_sinanp.Rmd
- CONFLICTOS: matriz_conflictos_yuc_bajo_sin_acua.csv

**Resultados:** 

[uga_11feb22_10marzo2022_v4_050_sin_acu_sin_anp.csv](https://github.com/lancis-apc/fomix/files/8256707/uga_11feb22_10marzo2022_v4_050_sin_acu_sin_anp.csv)

El documento **optimizacion_uga_10mar22_sin_anp.xlsx** tiene la lista de sectores resultado del modelo de optimización y la lista de los sectores que no fueron seleccionados pero que tienen residuales positivos. Esta segunda lista corresponde a los conflictos principales para las fichas @dpedroza74

**Comment by vichdzgeo** [comment]
## Actualización de indicadores

[bd_ugas_indicadores_15mar.xlsx](https://github.com/lancis-apc/fomix/files/8277763/bd_ugas_indicadores_15mar.xlsx)

@TatianaMerino

**Comment by TatianaMerino** [comment]
## Actualización en #84 

> ## Bases de datos
> Áreas prioritarias por UGA
> 
> [bd_areas_poety_uga_11mar22_tp_appcr_marzo2022_v2.xlsx](https://github.com/lancis-apc/fomix/files/8236327/bd_areas_poety_uga_11mar22_tp_appcr_marzo2022_v2.xlsx)
> 
> ![fig_prueba_cob_anp](https://user-images.githubusercontent.com/38017509/157985093-564c8ff2-9fe1-402a-aa85-e8517aa80c2a.png)
> 
> ### Indicadores por UGA
> [bd_ugas_indicadores_11mar.xlsx](https://github.com/lancis-apc/fomix/files/8236440/bd_ugas_indicadores_11mar.xlsx)
> 
> @TatianaMerino

**Comment by TatianaMerino** [comment]
## Actualización de matriz de sectores prioritarios
@vichdzgeo 
Se agregó la UGA 158 como sector conservación

Archivo final para la plataforma: **uga_11feb22_10marzo2022_v4_050_sin_acu_sin_anp_informe.csv**

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
