### ISSUE TITLE
Diseñar sección Monitoreo bitácora

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#106]
@iaga @TatianaMerino 
En la carpeta FOMIX\fmx_diseno_sistema\monitoreo\bd
subimos algunas bases de datos que queremos usar para diseñar gráficos y tablas que se puedan incluir en la sección de monitoreo de la bitácora ambiental en la que se dará seguimiento a los indicadores del POETY. 
Luis nos comentó ayer que estas bases servirán también para tener algunas series históricas para el pronóstico. Algunas de las bd están a nivel estado y otras a nivel municipal y tienen diferentes años de cobertura. Pero él dijo que les diría qué hacer.
En la carpeta de la info municipal puse un excel con el listado y sugerencia de las variables a usar

**Comment by TatianaMerino** [comment]
## Actividades a considerar
@iaga 

- [ ] Descripción estadística 
- [ ] Análisis de correlaciones
- [ ] Análisis de series de tiempo
