### ISSUE TITLE
Integrar informe de talleres del pronóstico de urbano e industrial #FOMIX

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#107]
Ubicación de insumos y resultados: 
fmx_estudio_tecnico/pronostico/talleres

**Comment by TatianaMerino** [comment]
**AVISO**

Carpetas : 
-  diagramas: contiene los diagramas como png o pdf y una carpeta "vensim" donde se ubican los modelos en formato mdl. Nombre: (sector).mdl
- ksim: donde se ubicarán los archivos en formato xlsx que contien la simulasión dinámica KSIM. Nombres: "ksim_(sector).xlsx"
- pagina_web

Nota: en cada carpeta hay una subcarpeta llamada auxiliares, donde se colocarán las versiones no actualizadas de los archivos correspondientes. 

_Nombres de archivos y equivalencias:_

sector|nombre
--|--|
Urbano e industrial | urbano
Agricultura | agricultura
Porcino y avícola | por_avi
Ganadería | bovino
Energía | energia
Turismo  (sol y playa) | turismo
Cambio climático | clima

**Comment by TatianaMerino** [comment]
## Insumos antes del taller
Archivos: 
- urbano_v9.mdl 
- ksim_urbano.xlsx
-  fi_urbano_v9_2.png

![fi_urbano_v9_2](https://user-images.githubusercontent.com/57197109/136855192-48eb69dc-0848-4dc7-a35e-3e9a827b663e.png)

Variable|Definición|Unidades
--|--|--|
Zonas urbanas e industriales | Superficie de zonas urbanas e industriales | Hectáreas
Población| | Número de habitantes
Vulnerabilidad del acuífero | Superficie de acuífero vulnerable | Hectáreas
Residuos sólidos y líquidos|  Residuos sólidos y aguas residuales | Toneladas y m3
Consumo de agua| Consumo promedio de agua por habitante | Litros/habitante 
Calidad de agua| Índice | Adimensional
Humedales costeros| Superficie de humedales costeros| Hectáreas
Humedales terrestres| Superficie de cenotes, dolinas, aguadas, etc. | Hectáreas
Zonas agropecuarias| Superficie de granjas agropecuarias | Hectáreas
Bancos de materiales pétreos| Superficie de bancos de materiales | Hectáreas
Cobertura forestal| Superficie con cobertura forestal| Hectáreas
Parques eólicos y solares| Proyectos de energía limpia eólica y solar | Hectáreas 
Producción pesquera| Producción general de pesca| Toneladas 
Vulnerabilidad ante eventos hidro-meteorológicos| Zonas propensas a inundación| Hectáreas 
Acuífero| Flujo de recarga| Hectómetros cúbicos
Calidad de hábitat de flora y fauna| Superficie con buen estado de conservación | Hectáreas

**Comment by TatianaMerino** [comment]
## Escala de intensidad de interacciones

Abreviatura| Expresión| Valor numérico
--|--|--|
MF | Muy fuerte| 9
F | Fuerte | 7
M | Moderado | 5
B | Bajo | 3
MB | Muy bajo | 1

**Comment by dpedroza74** [comment]
En la carpeta FOMIX\fmx_estudio_tecnico\pronostico\talleres\factores_transf puse carpetas para todos los talleres 

Para cada taller puse una carpeta **notas** donde subiré los chats de zoom y podemos subir nuestras notas y una de **info_recibida** para ir subiendo ahí la información que envíen sobre el tema. Para el taller de hoy subí un artículo que nos refirieron por el chat
En la carpeta de cada taller voy a ir subiendo la lista de registro/asistencia 

En la carpeta FOMIX\fmx_estudio_tecnico\pronostico\imagenes voy a ir subiendo capturas de pantalla y videos de los talleres

**Comment by ofegarcia** [comment]
Se agregó versión escrita del taller en la carpeta fmx_estudio_tecnico\pronostico\talleres\factores_transf\urbano_industria\notas

Archivo: resultados_urb_ind_12oct21

**Comment by TatianaMerino** [comment]
## Resultados del taller

### Diagrama del taller con intensidades
Archivos:
- urbano_taller_v2.mdl
- fi_urbano_taller_v2.png

![resultados_taller](https://user-images.githubusercontent.com/57197109/137237466-4e7eb803-c5ec-4a64-9c49-abf99de4d18f.png)


### Diagrama para informe
Archivos:
- urbano_informe.mdl
- fi_urbano_informe.png

![fi_urbano_informe](https://user-images.githubusercontent.com/57197109/137970697-268f13c0-3dc4-4b77-9a19-e89ba0d272b5.png)


Variable|Definición|Unidades
--|--|--|
Factores de crecimiento| Fraudes, falta de reservas territoriales, incumplimiento de programas de ordenamiento, precio de la tierra y conectividad |
Zonas urbanas e industriales | Superficie de zonas urbanas e industriales | Hectáreas
Población | Número de habitantes | Número de habitantes
Vulnerabilidad del acuífero | Superficie de acuífero vulnerable | Hectáreas
Residuos sólidos y líquidos|  Residuos sólidos y aguas residuales | Toneladas y metros cúbicos
Consumo de agua| Consumo promedio de agua por habitante | Litros/habitante 
Acuífero: calidad del agua| Índice | Adimensional
Humedales costeros y terrestres| Superficie de humedales, cenotes, dolinas, aguadas, etc.| Hectáreas
Zonas agropecuarias| Superficie de granjas agropecuarias | Hectáreas
Bancos de materiales pétreos| Superficie de bancos de materiales | Hectáreas
Cobertura forestal| Superficie con cobertura forestal| Hectáreas
Generación y distribución de energía| Proyectos de energía limpia eólica y solar | Hectáreas 
Producción pesquera| Producción general de pesca| Toneladas 
Vulnerabilidad ante eventos hidrometeorológicos| Zonas propensas a inundación| Hectáreas 
Acuífero: disponibilidad de agua| Disponibilidad de agua en el acuífero| Hectómetros cúbicos
Hábitat de flora y fauna| Superficie con buen estado de conservación | Hectáreas 
Calidad del aire | Índice o promedio de emisiones de contaminantes atmosféricos | Adimensional o partes por millón

**Comment by TatianaMerino** [comment]
## **AVISO**

El video de la reunión para subir a la plataforma es **vi_urbano_industrial_12oct21.mp4**
Ruta: \fmx_estudio_tecnico\pronostico\imagenes\urbano_industria

@ofegarcia @dpedroza74  favor de revisar

**Comment by Nayita** [comment]
@dpedroza74 

Ruta para poner las figuras:

\FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\urbano_indus

**Comment by dpedroza74** [comment]
@Nayita 
Ya subí la imagen del diagrama. La lista de asistencia en pdf está en la carpeta

FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\urb e ind
Mañana subo las tablas porque falta que Luis revise unas cosas

**Comment by dpedroza74** [comment]
@Nayita 

La introducción es general por lo que tiene que ir en la página de inicio de los talleres. Al final de la introducción poner el hipervínculo a la presentación **pres_talleres_pron_oct21_pag_web** que subí a 
FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web

### Introducción

A partir de la información recabada en el análisis de conflictos, el equipo técnico del Laboratorio Nacional de Ciencias de la Sostenibilidad, UNAM generó diagramas que representan los principales factores de transformación del territorio y sus efectos sobre los factores ambientales y las actividades sectoriales. 
Para la programación de talleres se consideraron aquellos factores de transformación del territorio que tienen un efecto más significativo en términos sus impactos sobre el ambiente y otros sectores.
Los participantes en los talleres revisaron las variables y las relaciones causales de los diagramas de flujo y, en su caso, los complementaron. Asimismo, avanzaron en la evaluación de las intensidades de las interacciones entre las variables, utilizando una escala lingüística. 
En este reporte se muestran:
1.	Los diagramas que incorporan las observaciones de los participantes en cada taller
2.	Una tabla con la definición de las variables 
3.	Una tabla que explica las interacciones entre variables, la dirección del efecto y la intensidad de la interacción 
Se identifica como una interacción positiva, si el cambio en una variable conduce al cambio en la otra en el mismo sentido. Es decir, el aumento de la variable causante ocasiona el aumento de la variable que recibe el efecto, o si la disminución de la variable causante ocasiona la disminución de la variable que recibe el efecto. 
Se identifica como una interacción negativa, si el cambio en una variable conduce al cambio en la otra en el mismo sentido. Es decir, el aumento de la variable causante ocasiona la disminución de la variable que recibe el efecto, o si la disminución de la variable causante ocasiona el aumento de la variable que recibe el efecto. 
La intensidad de la interacción se evalúa con las siguientes variables lingüísticas: Muy fuerte (MF), Fuerte (F), Moderada (M), Baja (B), Muy baja (MB), Baja (B). Las interacciones que no alcanzaron a ser evaluadas durante en taller se reportan como NE.

**Comment by dpedroza74** [comment]
@Nayita el diagrama ponerle el título
Diagrama que representa los efectos del crecimiento urbano e industrial

**Comment by TatianaMerino** [comment]
@Nayita 

**Variables del diagrama que representa los efectos del crecimiento urbano e industrial**

Variable | Definición | Unidades
-- | -- | --
Acuífero: calidad del agua | Índice | Adimensional
Acuífero: disponibilidad de agua | Disponibilidad Media Anual de Agua Subterránea | Hectómetros cúbicos
Bancos de   materiales pétreos | Superficie de bancos de materiales | Hectáreas
Calidad del aire | Índice | Adimensional
Cobertura forestal | Superficie con cobertura forestal | Hectáreas
Consumo de agua | Consumo de agua   para uso de servicios, urbano público, industrial y doméstico; Consumo promedio de agua por habitante | Metros cúbicos; Litros/habitante
Generación y distribución de energía | Superficie de instalaciones de energía eólica, solar y termoeléctricas | Hectáreas
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación natural | Hectáreas
Humedales terrestres y costeros | Superficie de humedales costeros, cenotes, dolinas, aguadas, etc. | Hectáreas
Población | Habitantes   en zonas urbanas | Número de   habitantes
Producción pesquera | Producción pesquera en el estado | Toneladas
Residuos sólidos y líquidos | Residuos sólidos y aguas residuales | Toneladas y metros   cúbicos
Vulnerabilidad ante eventos hidrometeorológicos | Zonas vulnerables a inundación | Hectáreas
Vulnerabilidad   del acuífero | Superficie de acuífero con vulnerabilidad alta a la contaminación | Hectáreas
Zonas agropecuarias | Superficie con uso agropecuario | Hectáreas
Zonas urbanas e industriales | Superficie de zonas urbanas e industriales | Hectáreas


**Interacciones del diagrama que representa los efectos del crecimiento urbano e industrial**

Variable causante | Variable afectada | Efecto | Dirección | Intensidad
-- | -- | -- | -- | --
Zonas urbanas e industriales | Cobertura forestal | Si aumentan las zonas urbanas e industriales    la cobertura forestal disminuye y se fragmenta | - | MF, F
Cobertura forestal | Hábitat de flora y fauna | Si aumenta la cobertura forestal, el hábitat de    flora y fauna aumenta | + | NE
Cobertura forestal | Acuífero: disponibilidad de agua | Si aumenta la cobertura forestal, las zonas de recarga del acuífero aumentan | + | NE
Cobertura forestal | Vulnerabilidad ante eventos hidrometeorológicos | Si aumenta la cobertura vegetal, la vulnerabilidad ante eventos de hidrometeorológicos disminuye por la retención del flujo    hidráulico | - | NE
Zonas urbanas e industriales | Humedales    terrestres y costeros | Si aumentan las zonas urbanas e industriales, la superficie manglares y otros humedales disminuye por relleno o alteración del flujo hidrodinámico | - | NE
Humedales costeros y terrestres | Vulnerabilidad ante eventos hidrometeorológicos | Si aumentan los humedales costeros y terrestres, la vulnerabilidad ante    eventos de hidrometeorológicos disminuye | - | NE
Zonas urbanas e industriales | Vulnerabilidad ante eventos hidrometeorológicos | Si aumentan las zonas urbanas e industriales, la vulnerabilidad ante inundaciones aumenta por    el establecimiento de superficies impermeables. | + | NE
Vulnerabilidad ante eventos hidrometeorológicos | Zonas urbanas e industriales | Si aumenta la vulnerabilidad ante eventos hidrometeorológicos, las zonas aptas para el desarrollo urbano e    industrial disminuyen | - | NE
Zonas urbanas e industriales | Zonas agropecuarias | Si aumentan las zonas urbanas e industriales, la superficie con uso agropecuario disminuyen | - | F, M
Zonas urbanas e industriales | Bancos de materiales pétreos | Si aumentan las zonas urbanas e industriales, los bancos de materiales aumentan para abastecer la demanda para la construcción de infraestructura urbana y vivienda | + | MF, F
Bancos de materiales pétreos | Cobertura forestal | Si aumentan los bancos de materiales, la cobertura forestal disminuye y se fragmenta | - | NE
Bancos de materiales pétreos | Zonas agropecuarias | Si aumentan los bancos de materiales, la    superficie con uso agropecuario disminuye | - | NE
Bancos de materiales pétreos | Vulnerabilidad del acuífero | Si aumentan los bancos de materiales, la    vulnerabilidad intrínseca y específica del acuífero aumenta por alteración    del suelo y las actividades mineras | + | NE
Zonas urbanas e industriales | Generación y distribución de energía | Si aumentan las zonas urbanas e industriales, la demanda de energía para uso domiciliario, de servicios e industrial aumenta | + | NE
Zonas urbanas e industriales | Población | Si aumentan las zonas urbanas e industriales, el    número de habitantes atraídos por la oferta de desarrollos inmobiliarios y    de empleo aumenta | + | NE
Población | Residuos sólidos y líquidos | Si aumenta la población, la generación de residuos sólidos y líquidos aumenta | + | NE
Residuos    sólidos y líquidos | Vulnerabilidad del acuífero | Si aumentan los residuos sólidos y líquidos, la vulnerabilidad específica de contaminación del acuífero aumenta | + | NE
Vulnerabilidad del acuífero | Acuífero: calidad del agua | Si aumenta la vulnerabilidad específica de contaminación del acuífero, la  calidad del agua disminuye | - | NE
Acuífero: calidad del agua | Zonas urbanas e industriales | Si aumenta la disponibilidad de agua de buena calidad las zonas aptas para el desarrollo urbano e industrial aumentan | + | NE
Población | Consumo de agua | Si aumenta la población, la demanda de agua para usos domiciliario y de servicios e industrial aumenta | + | NE
Consumo de agua | Acuífero: disponibilidad de agua | Si aumenta el consumo de agua para usos domiciliario y de servicios e industrial, la disponibilidad de agua del acuífero disminuye| - | NE
Acuífero: disponibilidad de agua | Acuífero: calidad del agua | Si aumenta la disponibilidad de    agua del acuífero la calidad de agua del acuífero aumenta por dilución | + | NE
Acuífero: disponibilidad de agua | Humedales terrestres y costeros | Si aumenta la disponibilidad de agua del acuífero, el flujo de agua a los humedales aumenta | + | NE
Acuífero: calidad del agua | Humedales terrestres y costeros | Si aumenta la disponibilidad de    agua del acuífero, la calidad de agua que fluye a los humedales aumenta | + | NE
Humedales terrestres y costeros | Hábitat de flora y fauna | Si aumenta la extensión y la calidad de agua de los humedales, el hábitat de flora y fauna aumenta | + | NE
Hábitat de flora y fauna | Producción pesquera | Si aumenta el hábitat de flora y fauna, las especies de interés pesquero aumentan | + | NE
Zonas urbanas e industriales | Calidad del aire | Si aumentan las zonas urbanas e industriales, la    calidad del aire disminuye por la emisión de contaminantes de fuentes fijas y móviles | - | NE

**Comment by Nayita** [comment]
### AVISO

Listo el informe.

- [x] @vichdzgeo  favor de publicar

**Comment by dpedroza74** [comment]
@Nayita 
Ha hice el cambio en la definición de calidad del aire en la tabla Variables del diagrama que representa los efectos del crecimiento urbano e industrial en el comentario de Tatiana.

**Comment by dpedroza74** [comment]
@Nayita 
Vi con Luis el html y no se ve bien la tabla de interacciones, puedes ponerla como imagen, para ver cómo se ve. Puse la imagen fi_tabla_interacc_urbano  en 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\urbano_indus

**Comment by Nayita** [comment]
@dpedroza74 

Lista las correcciones solicitadas. Favor de revisar el html para poder publicar en la ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\build\html
Archivo: urbano_indus_pronos

**Comment by ofegarcia** [comment]
@dpedroza74
Lista la tabla de justificación de evaluación de la intensidad de las interacciones y las notas del taller.
Ruta: fmx_estudio_tecnico\pronostico\talleres\resultados\agricola\notas
Archivos: evaluac_intensidad_urb_ind_12oct21
urb_ind_notas:12oct21

**Comment by dpedroza74** [comment]
@Nayita 

Puedes incluir en el reporte de la página después de la imagen de 
**Interacciones del diagrama que representa los efectos del crecimiento urbano e industrial**
esta tabla

**Justificación de la evaluación de intensidad de las interacciones**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Variable   causante | Variable afectada | Intensidad | Argumentación
-- | -- | -- | --
Zonas   urbanas e industriales | Cobertura forestal | MF, F | Muy fuerte en el corredor   de  Mérida a Progreso y Dzilam donde se   ha lotificado y se han autorizado cambios de uso de suelo en terrenos con   cobertura forestal. Ya está urbanizado hasta la playa Chuburná.     El efecto de la urbanización sobre terrenos con cobertura vegetal es mayor,   en comparación con zonas donde se establecen bancos de materiales y   actividades agropecuarias, ya que cuando éstas últimas se abandonan la   vegetación puede recuperarse.
Zonas   urbanas e industriales | Zonas agropecuarias | F, M | Depende de la zona.      Fuerte en la zona poniente, donde es mayor el crecimiento de zonas urbanas   hacia las zonas agropecuarias.     Moderado en otras zonas, donde el crecimiento de zonas urbanas es más   intenso hacia terrenos con cobertura forestal.
Zonas   urbanas e industriales | Bancos de materiales pétreos | MF, F | Las zonas urbanas e industriales   requieren materiales para la construcción de vivienda, edificios,   infraestructura urbana y vías de comunicación.





</body>

</html>

**Comment by Nayita** [comment]
### AVISO

Lista la actualización

- [ ] @vichdzgeo Favor de publicar

**Comment by dpedroza74** [comment]
@Nayita

Favor de sustituir en la página la lista de asistencia con la que ya incluye los talleres de noviembre que está en la carpeta \FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\urb e ind

**Comment by Nayita** [comment]
### AVISO

Lista la sustitución.

@vichdzgeo favor de publicar

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
