### ISSUE TITLE
Integrar informe de talleres del pronóstico de agricultura #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#108]
Ruta de trabajo: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos

**Comment by TatianaMerino** [comment]
## Insumos antes del taller
- agricultura_v4.mdl
- ksim_agricultura

- fi_agricultura_v4.png
![fi_agricultura_v4](https://user-images.githubusercontent.com/57197109/137232493-be2c64d4-1828-44ab-9f6e-3f2445fddc2b.png)

Variable | Definición | Unidades
--|--|--|
Inversión |Programas de fomento gubernamentales o por recursos de los productores | Pesos
Zonas de agricultura tecnificada | Superficies con uso de agricultura tecnificada de temporal y de riego | Hectáreas
Cobertura de especies melíferas | Superficie de distribución de especies melíferas | Hectáreas
Producción apícola | Producción de miel | Toneladas
Uso de agroquímicos | Superficie fertilizada | Hectáreas
Vulnerabilidad del acuífero | Superficie vulnerable | Hectáreas
Calidad de agua | Índice | Adimensional
Consumo de agua | Volumen de agua para consumo agrícola | Litros o metros cúbicos
Acuífero | Disponibilidad de agua | Hectómetros cúbicos
Cobertura forestal | Vegetación forestal: selvas y pastizales naturales | Hectáreas
Zonas de milpa | Superficie con uso de milpa (zonas ocupadas o zonas de aptitud para ser ocupadas) | Hectáreas
Zonas de producción forestal | Superficie de zonas de aprovechamiento forestal (ya ocupadas) o zonas de aptitud para producción forestal (por ocupar) | Hectáreas
Calidad de hábitat de flora y fauna | Superficie con buen estado de conservación | Hectáreas

**Comment by TatianaMerino** [comment]
# Insumos generados en el taller 

Archivos: 
- agricultura_taller.mdl
- fi_agricultura_taller

![fi_agricultura_taller](https://user-images.githubusercontent.com/57197109/137389243-bcf77f41-432a-4405-8127-6900b3597632.png)

Nota: en la consulta de las intensidades, los expertos mencionaron la diferenciación entre zonas del estado para algunas interacciones. Dichas diferenciaciones se observan entre paréntesis, donde o= Oriente, s= Sur, n= Norte, c= Centro, *Motul

### Diagrama para informe
- agricultura_informe.mdl
- fi_agricultura_informe.png


![fi_agricultura_informe](https://user-images.githubusercontent.com/57197109/137971121-f8d64922-2484-49a0-9b04-6257d3e9b214.png)


Variable | Definición | Unidades
--|--|--|
Inversión |Programas de fomento gubernamentales o por recursos de los productores | Pesos
Zonas de agricultura tecnificada | Superficies con uso de agricultura tecnificada de temporal y de riego | Hectáreas
Cobertura de especies melíferas | Superficie de distribución de especies melíferas | Hectáreas
Producción apícola | Producción de miel | Toneladas
Uso de agroquímicos | Superficie fertilizada | Hectáreas
Vulnerabilidad del acuífero | Superficie de acuífero vulnerable | Hectáreas
Acuífero: calidad del agua | Índice | Adimensional
Consumo de agua | Volumen de agua para consumo agrícola | Litros o metros cúbicos
Acuífero: disponibilidad de agua | Disponibilidad de agua | Hectómetros cúbicos
Cobertura forestal | Vegetación forestal: selvas y pastizales naturales | Hectáreas
Zonas de milpa | Superficie con uso de milpa (zonas ocupadas o zonas de aptitud para ser ocupadas) | Hectáreas
Zonas de producción forestal | Superficie de zonas de aprovechamiento forestal (ya ocupadas) o zonas de aptitud para producción forestal (por ocupar) | Hectáreas
Hábitat de flora y fauna | Superficie con buen estado de conservación | Hectáreas
Humedales terrestres y costeros | Superficie de humedales costeros, cenotes, dolinas, aguadas, etc. | Hectáreas

**Comment by TatianaMerino** [comment]
## AVISO

Listo el video del taller para subir a la plataforma: **vi_agricultura_14oct21.mp4**
Ruta: FOMIX\fmx_estudio_tecnico\pronostico\imagenes\agricola

**Comment by dpedroza74** [comment]
@Nayita 
Ya subí la imagen del diagrama en 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\agricola

La lista de asistencia en pdf está en la carpeta
FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\agri

Mañana subo las tablas porque falta que Luis revise unas cosas

**Comment by TatianaMerino** [comment]
@Nayita 

**Variables del diagrama que representa los efectos del crecimiento agrícola**
Variable | Definición | Unidades
-- | -- | --
Acuífero: calidad del agua | Índice | Adimensional
Acuífero: disponibilidad de agua | Disponibilidad Media Anual de Agua Subterránea | Hectómetros cúbicos
Cobertura de especies melíferas | Superficie de distribución de especies melíferas | Hectáreas
Cobertura   forestal | Superficie con cobertura forestal | Hectáreas
Consumo de agua | Volumen de agua para consumo agrícola | Hectómetros cúbicos
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación natural | Hectáreas
Humedales terrestres y costeros | Superficie de humedales costeros, cenotes, dolinas, aguadas, etc. | Hectáreas
Inversión | Programas de fomento gubernamentales o inversión de los productores | Pesos
Producción apícola | Producción de miel | Toneladas
Uso de agroquímicos | Superficie cultivada con aplicación de fertilizantes | Hectáreas
Vulnerabilidad del acuífero | Superficie de acuífero con vulnerabilidad alta a la contaminación | Hectáreas
Zonas de agricultura tecnificada | Superficies con uso de agricultura tecnificada de temporal y de riego | Hectáreas
Zonas de milpa | Zonas de milpa maya | Hectáreas
Zonas de producción forestal | Zonas de aprovechamiento forestal | Hectáreas

**Interacciones del diagrama que representa los efectos del crecimiento agrícola**

Variable causante | Variable afectada | Efecto | Dirección | Intensidad
-- | -- | -- | -- | --
Zonas de agricultura tecnificada | Zonas de milpa | Si las zonas de agricultura tecnificada aumentan, las zonas de milpa disminuyen | - | M, MB
Zonas de milpa | Cobertura forestal | Si las zonas de milpa aumentan, la cobertura forestal disminuye y se fragmenta | - | NE
Zonas de agricultura tecnificada | Cobertura forestal | Si las zonas agrícolas aumentan, la cobertura forestal disminuye y se fragmenta | - | B (centro y oriente)    F(sur)
Cobertura forestal | Hábitat de flora y fauna | Si la cobertura forestal aumenta,  el    hábitat de flora y fauna aumenta | + | NE
Cobertura forestal | Acuífero: disponibilidad de agua | Si la cobertura forestal aumenta, las zonas de recarga del acuífero aumentan | + | NE
Zonas de agricultura tecnificada | Cobertura de especies melíferas | Si las zonas agrícolas aumentan, la cobertura de especies melíferas disminuye | - | F, M
Cobertura de especies melíferas | Producción apícola | Si la cobertura de especies melíferas aumenta,  la producción de miel aumenta | + | NE
Zonas de agricultura tecnificada | Uso de agroquímicos | Si aumentan las zonas de agricultura tecnificada ,    el uso de agroquímicos aumenta | + | MF, F
Uso de agroquímicos | Producción apícola | Si el uso de agroquímicos aumenta, la producción de miel disminuye por la muerte de abejas y la contaminación de la miel | - | F
Producción apícola | Zonas de agricultura tecnificada | Si aumenta la presión social por los efectos en la apicultura de los cultivos de transgénicos, las zonas de agricultura tecnificada pueden disminuir | - | NE
Uso de agroquímicos | Vulnerabilidad del acuífero | Si aumenta el uso de agroquímicos, la    vulnerabilidad específica de contaminación del acuífero aumenta | + | F (norte y oriente)    M(sur)
Vulnerabilidad del acuífero | Acuífero: calidad de agua | Si aumenta la vulnerabilidad específica de contaminación del acuífero, la calidad    del agua disminuye | - | MF, F
Acuífero: calidad de agua | Zonas de agricultura tecnificada | Si aumenta la calidad del agua, las zonas aptas para la agricultura tecnificada aumentan | + | NE
Zonas de agricultura tecnificada | Consumo de agua | Si aumentan las zonas de agricultura tecnificada, la demanda de agua para riego aumenta | + | NE
Consumo de agua | Acuífero: disponibilidad de agua | Si aumenta el consumo de agua, la disponibilidad de agua en el acuífero disminuye | - | MF, F (sur, Motul)
Acuífero: disponibilidad de agua | Acuífero: calidad de agua | Si aumenta la disponibilidad de    agua del acuífero la calidad de agua del acuífero aumenta por dilución | + | NE
Acuífero: disponibilidad de agua | Humedales terrestres y costeros | Si aumenta la disponibilidad de agua del acuífero, el flujo de agua a los humedales aumenta | + | NE
Acuífero: calidad de agua | Humedales terrestres y costeros | Si aumenta la disponibilidad de    agua del acuífero, la calidad de agua que fluye a los humedales aumenta | + | NE
Humedales terrestres y costeros | Hábitat de flora y fauna | Si aumenta la extensión y la calidad de agua de los humedales, el hábitat de flora y fauna aumenta | + | NE

**Comment by Nayita** [comment]
### AVISO

Listo el informe.

- [x] @vichdzgeo favor de publicar

**Comment by dpedroza74** [comment]
@Nayita
Vi con Luis el html y no se ve bien la tabla de interacciones, puedes ponerla como imagen, para ver si se ve mejora, por favor? Puse la imagen fi_tabla_interacc_agri en la carpeta
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\agricola

**Comment by Nayita** [comment]
Lista las correcciones solicitadas. Favor de revisar el html para poder publicar en la ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\build\html
Archivo: agricultura_pronos

**Comment by ofegarcia** [comment]
@dpedroza74
Lista la tabla de justificación de evaluación de la intensidad de las interacciones y las notas del taller.
Ruta: fmx_estudio_tecnico\pronostico\talleres\resultados\agricola\notas
Archivos: evaluac_intensidad_agric_14oct21
agric_notas:14oct21

**Comment by dpedroza74** [comment]
@Nayita 

Favor de incluir en el informe de la página después de la imagen 
**Interacciones del diagrama que representa los efectos del crecimiento agrícola**
la siguiente tabla

**Justificación de la evaluación de intensidad de las interacciones**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Variable   causante | Variable afectada | Intensidad | Argumentación
-- | -- | -- | --
Zonas de   agricultura tecnificada | Zonas de milpa | M, MB | El cambio en la milpa es por   razones económicas, porque la mano de obra se está ocupando en otros   sectores.     Terrenos que tenían milpa se están convirtiendo en agricultura tecnificada,   pero es muy baja.      Mucha milpa se desarrolla en selva caducifolia.
Zonas de   agricultura tecnificada | Cobertura forestal | B (centro y oriente), F(sur) | En centro y oriente la ganadería   es el factor que más ha disminuido la cobertura.     Las zonas agrícolas están creciendo hacia el sur.
Zonas   de agricultura tecnificada | Cobertura de especies melíferas | F, M | Fuerte en el sur del estado   donde la agricultura ha tenido un alto impacto sobre lo forestal por   desmontes para cultivos.      Hay tres especies importantes: tajonal, dzizilché y jabín.     La milpa tradicional sí deja claros de descanso para que crezca dzizilché.        Moderada porque se crean cinturones de estas especies.
Zonas de   agricultura tecnificada | Uso de agroquímicos | MF, F | Muy fuerte porque es agricultura   intensiva con alto uso de agroquímicos.          Fuerte porque solo 12 % de la superficie sembrada usa fertilizantes   químicos.      Fuerte porque los agroquímicos son caros y eso limita su uso.
Uso de   agroquímicos | Producción apícola | F | Los agroquímicos afectan a las   plantas melíferas, matan a las abejas y se acumula en la miel.
Uso de   agroquímicos | Vulnerabilidad del acuífero | F (norte y oriente),     M (sur) | Depende de la zona.      Fuerte en Dzilam Bravo, Dzilam González y zona norte, donde el manto   freático es somero.          Moderado en el cono sur, donde el manto freático es más profundo.
Vulnerabilidad   del acuífero | Acuífero: calidad de agua | MF, F | Muy Fuerte por el sistema   kárstico, y de acuerdo con resultados del Dr. Polanco que señalan   contaminación por glifosato en el manto acuífero. También CINVESTAV ha   reportado contaminación en todos los cenotes de Yucatán.          Fuerte porque el agua que se aprovecha no se toma de la capa superficial   que está contaminada, sino de la parte media. Por tanto, a veces no se   registra la contaminación.
Consumo   de agua | Acuífero: disponibilidad de agua | MF; F (sur, Motul) | Muy fuerte porque según los   datos de la CONAGUA la agricultura consume mucha agua.     Fuerte porque la superficie donde aún puede crecer la agricultura es   limitada.     La zona centro es henequenera (Motul). La agricultura puede crecer en zona   sur, y el acuífero está profundo por lo que podría ser moderado el consumo.        El consumo de agua es diferente, dependiendo del cultivo.



</body>

</html>

**Comment by Nayita** [comment]
### AVISO

Lista la actualización

- [ ] @vichdzgeo Favor de publicar

**Comment by dpedroza74** [comment]
@Nayita

Favor de sustituir en la página la lista de asistencia con la que ya incluye los talleres de noviembre que está en la carpeta \FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\agri

**Comment by Nayita** [comment]
### AVISO

Lista la sustitución.

- [x] @vichdzgeo favor de publicar
