### ISSUE TITLE
Integrar informe de talleres del pronóstico de porcino-avícola #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#109]
Ruta: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos

## Insumos previos al taller

Archivos del diagrama de flujo:
- por_avi_v5.mdl
- fi_por_avi_v5.png

![fi_por_avi_v5](https://user-images.githubusercontent.com/57197109/137555956-03fe0cef-0771-453c-be5f-9f482bec9db0.png)

Variable | Definición | Unidades
--|--|--|
Inversión | Programas de fomento gubernamentales o por recursos de los productores | Pesos o hectáreas que reciben apoyo
Granjas porcícolas y avícolas | Número de animales y/o número de granjas | Número de animales y/o número de granjas
Vulnerabilidad del acuífero | Superficie de acuífero vulnerable | Hectáreas
Residuos sólidos y líquidos|  Residuos sólidos y aguas residuales | Toneladas y metros cúbicos
Consumo de agua | Consumo promedio de agua por granja | Metros cúbicos por año 
Calidad de agua| Índice | Adimensional
Humedales costeros y terrestres| Superficie de humedales, cenotes, dolinas, aguadas, etc.| Hectáreas
Cobertura forestal| Superficie con cobertura forestal| Hectáreas
Acuífero| Disponibilidad de agua en el acuífero| Hectómetros cúbicos
Hábitat de flora y fauna| Superficie con buen estado de conservación | Hectáreas 
Calidad del aire | Índice o promedio de emisiones de contaminantes atmosféricos | Adimensional o partes por millón

**Comment by TatianaMerino** [comment]
## Diagrama del taller

![fi_por_avi_taller](https://user-images.githubusercontent.com/57197109/137974868-aa284077-5a38-42a2-8b1d-055972495738.png)

## Para informe

Archivos: 
- por_avi_informe.mdl
- fi_por_avi_informe.png

![fi_por_avi_informe](https://user-images.githubusercontent.com/57197109/137974999-db001de4-1366-4078-a110-1ed60cd93b7d.png)

Nota: falta una conexión al diagrama de agricultra con residuos, quedó pendiente de discutirse en el equipo. 

Variable | Definición | Unidades
--|--|--|
Inversión | Programas de fomento gubernamentales o por recursos de los productores | Pesos 
Tren Maya | Proyecto Tren Maya | Pesos
Granjas porcícolas y avícolas | Número de animales y/o número de granjas | Número de animales y/o número de granjas
Vulnerabilidad del acuífero | Superficie de acuífero vulnerable | Hectáreas
Residuos sólidos y líquidos |  Excretas y aguas residuales | Toneladas y metros cúbicos
Consumo de agua | Consumo promedio de agua por granja | Metros cúbicos por año 
Acuífero: calidad del agua | Índice | Adimensional
Humedales costeros y terrestres | Superficie de humedales, cenotes, dolinas, aguadas, etc. | Hectáreas
Cobertura forestal | Superficie con cobertura forestal | Hectáreas
Acuífero: disponibilidad de agua | Disponibilidad de agua en el acuífero | Hectómetros cúbicos
Hábitat de flora y fauna | Superficie con buen estado de conservación | Hectáreas 
Calidad del aire | Índice o promedio de emisiones de contaminantes atmosféricos | Adimensional o partes por millón

**Comment by Nayita** [comment]
@dpedroza74 

Ruta para poner figuras: 
\FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\porcino_avi

**Comment by dpedroza74** [comment]
@Nayita 
Favor de publicar en la página los resultados del taller
Ya subí a la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\porcino_avi
las imágenes de

- Diagrama que representa los efectos del crecimiento de la ganadería porcícola y avícola
- Interacciones del diagrama que representa los efectos del crecimiento de la ganadería porcícola y avícola

La lista de asistencia en pdf está en la carpeta FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\por y avi

**Comment by TatianaMerino** [comment]
## Variables del diagrama que representan los efectos del crecimiento de la ganadería porcícola y avícola

Variable | Definición | Unidades
-- | -- | --
Acuífero: calidad del agua | Índice | Adimensional
Acuífero: diponibilidad de agua | Disponibilidad Media Anual de Agua Subterránea | Hectómetros cúbicos
Calidad del aire | Promedio de emisiones de contaminantes atmosféricos | Partes por millón
Cobertura forestal | Superficie con cobertura forestal | Hectáreas
Consumo de agua | Consumo promedio de agua por granja | Metros cúbicos por año
Granjas porcícolas y avícolas | Número de animales y/o número de granjas | Cabezas y granjas
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación   natural | Hectáreas
Humedales costeros y   terrestres | Superficie de humedales, cenotes, dolinas, aguadas, etc | Hectáreas
Inversión | Programas de fomento gubernamentales o inversión de los productores | Pesos
Residuos sólidos y líquidos | Excretas y aguas residuales | Toneladas y metros cúbicos
Tren Maya | Proyecto Tren Maya |  
Vulnerabilidad del acuífero | Superficie de acuífero con vulnerabilidad alta a la contaminación | Hectáreas

@Nayita

**Comment by Nayita** [comment]
### AVISO

Listo el informe.

- [x] @vichdzgeo Favor de publicar

**Comment by ofegarcia** [comment]
@dpedroza74
Lista la tabla de justificación de evaluación de la intensidad de las interacciones y las notas del taller.
Ruta: fmx_estudio_tecnico\pronostico\talleres\resultados\porcino_avicola\notas
Archivos: evaluac_intensidad_porc_avi_19oct21
por_notas:19oct21

**Comment by dpedroza74** [comment]
@Nayita 

- [x] Favor de sustituir la imagen **Interacciones del diagrama que representa los efectos del crecimiento de la ganadería porcícola y avícola**
 por la que actualmente está en la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\porcino_avi

- [x] Incluir abajo de esta imagen la siguiente tabla 
**Justificación de la evaluación de intensidad de las interacciones**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Variable   causante | Variable afectada | Intensidad | Argumentación
-- | -- | -- | --
Tren Maya | Granjas porcícolas y avícolas | MF (en Umán y Hunucmá) | Habrá afectaciones del tren maya   que van a afectar las granjas de algunos miembros de la Asociación de   Avicultores del Sureste, que están en Umán y Hunucmá.            No hay afectaciones para las granjas porcícolas.
Granjas   porcícolas y avícolas | Cobertura forestal | MF | Las granjas porcícolas no han   crecido en 2020 y 2021. Sin embargo, la intensidad es muy fuerte porque las   granjas siempre crecen sobre zonas forestales.      La mayoría de las granjas porcícolas de Yucatán tienen entre 30 y 40 años y   están en predios de 2 a 5 ha.     Los predios de las granjas nuevas son de 100 ha mínimo  y la infraestructura ocupa entre 10 y 30 ha   (10 ha en promedio).           El tamaño de la granja avícola dependiendo de los recursos del dueño pueden   ser de entre 2 y 5 ha, pero hay algunas de    500 – 600 ha. En general, del total del predio de la granja, el 70% se   deja para conservación y 30% para el establecimiento de la   infraestructura.     Las granjas  del sur son muy grandes   porque allí se manejan especies reproductoras y progenitoras que deben estar   alejadas y protegidas por aspectos sanitarios.     Las granjas avícolas están aumentando su producción en 1% anual, mejorando   la genética de los animales y haciendo más eficientes los procesos.
Granjas   porcícolas y avícolas | Consumo de agua | M (avícola), MF (porcícola) | En las granjas avícolas consumen   250 ml/ave/día.     Las granjas porcícolas nuevas tienen tecnología para hacer más eficiente el   uso del agua y descarga cero, por lo que su consumo de agua es de entre 15 y   20 l/cerdo/día.     Las granjas porcícolas viejas (aprox. 400 granjas que generan 20%   pro-ducción del estado) tienen consumos de entre 30 y 50 l/cerdo/día.
Granjas   porcícolas y avícolas | Residuos sólidos y líquidos | M (avícola), MF (porcícola) | Las granjas avícolas generan   pocos residuos porque generan de 25-30 g de residuos/ave/día. Les dan 110 g   de alimento al día (soya, sorgo, canola y aceites vegetales). Las excretas se   separan, se procesan y se hacen composta para los viveros de sembrando vida.   Generan agua residual sólo en los baños del personal.          Las granjas porcícolas producen más residuos.     Entre 7 y 9 kg excretas/100 kg (UPA) (Novelo, et al. 2009)*.     Carlos Ramayo proporcionará datos de la producción de residuos.
Residuos   sólidos y líquidos | Vulnerabilidad del acuífero | M (avícola), MF (porcícola) | La vulnerabilidad específica del   acuí-fero por contaminación de residuos de las granjas porcícolas es muy   fuerte, especialmente en la zona norte y del anillo de cenotes.     Por la cantidad de residuos que se generan en las granjas avícolas el   efecto sobre la vulnerabilidad es moderado.
Residuos   sólidos y líquidos | Calidad del aire | F | Las granjas porcícolas nuevas   tienen registro de emisión de metano y biodigestores.           En las granjas avícolas los olores se han minimizado con el uso de   bacterias y aireadores. Usan harinas a base de Yuca que inhibe el olor y baja   el amoniaco 150-200 kg por tonelada de alimento.
*Novelo,   R. M., Borges, E. C., Borges, E. V., Pérez, O. B., Peraza, V. C., Canul, R.   P., & Vivas, P. G. (2009). Estimación del potencial contaminante de las   granjas porcinas y avícolas del estado de Yucatán. Inge-niería, 13(2), 13-21.



</body>

</html>

**Comment by Nayita** [comment]
### AVISO

Listas las correcciones

- [ ] @vichdzgeo Favor de publicar

**Comment by dpedroza74** [comment]
@Nayita

Favor de sustituir en la página la lista de asistencia con la que ya incluye los talleres de noviembre que está en la carpeta FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\por y avi

**Comment by Nayita** [comment]
### AVISO

Lista la sustitución.

- [x] @vichdzgeo favor de publicar
