### ISSUE TITLE
Generar análisis de activos de información de la SDS Yucatán, Etapa 1 #FOMIX

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#11]
**La ruta donde estará alojado el reporte e insumos es FOMIX\fmx_diagnostico_institucional\activos_informacion**

@paola-gp  @Nayita @CorinaCantero @vichdzgeo @dpedroza74

**Comment by paola-gp** [comment]
### Compromisos en términos de referencia y propuesta alojados en /fomix/....

**Comment by ofegarcia** [comment]
## Análisis de información de activos 

1. Revisar requerimientos establecidos en la propuesta para el análisis de activos y del plan de seguridad
2. Identificar activos de información y clasificarlos
3. Evaluar activos de información con técnica multicriterio
4. Evaluar el cumplimiento de disposiciones legales y normativas por parte de la SDS
5. Analizar cómo integrar el plan de seguridad 
6. Elaborar reporte de análisis de activos para integrar al diagnóstico institucional

### Requerimientos de términos de referencia para análisis de activos y plan de seguridad
Objetivo específico 1
Elaborar un diagnóstico de recursos y capacidades disponibles para la gestión del ordenamiento ecológico del territorio y de los instrumentos de política de desarrollo sostenible en el estado de Yucatán
a) Meta asociada 1.1.3 
Análisis de activos de información que incluirá el inventario de activos, considerando la propiedad, la clasificación de la información, los procedimientos de manejo de activos, los mecanismos de custodia, los usuarios y la integridad, la confidencialidad y la disponibilidad de bases de datos. El resultado será una matriz de inventario y valoración de activos de información.
Realizar el inventario de activos de información del POETY considerando los lineamientos de la legislación en materia de transparencia y acceso a la información pública, y las mejores prácticas y documentos de uso libre de las normas ISO IEC 27005 – 2009 y gestión de activos ISO 27001:2013.
Los activos se clasificarán en términos de confidencialidad, integridad y disponibilidad. Para cada activo se especificará la información básica, nivel de clasificación, ubicación, propiedad y custodia, usuarios y derechos de acceso. 
b) Productos comprometidos asociados al objetivo 1
1.1.1	Diagnóstico para la gestión del ordenamiento ecológico del territorio.
c) Especificación de productos comprometidos:
Etapa 1
1.1.1 Diagnóstico para la gestión del ordenamiento ecológico del territorio. Documento que identificará recursos y capacidades disponibles para la gestión en materia de ordenamiento ecológico en el estado de Yucatán. Dicho diagnóstico incluirá: 
a) un análisis de la disponibilidad de equipamiento, infraestructura y presupuesto para el manejo de información, la implementación de mecanismos gobernanza y la elaboración de estudios técnicos.
b) una evaluación de las competencias técnicas e institucionales de los diferentes actores sociales para participar en procesos de gobernanza colaborativa.

Objetivo específico 5.
Diseñar un plan de seguridad, mantenimiento y soporte técnico que garantice el correcto funcionamiento del sistema de gestión en el largo plazo.
Involucrará tres actividades:
1.	análisis del contexto jurídico y normativo de las obligaciones legales de la SEDUMA, con base en los productos del diagnóstico y la estrategia (objetivos específicos 1 y 2). 
2.	análisis del contexto normativo para proponer e implementar protocolos y manuales de protección de datos personales, gestión de activos de información (entrega, recepción, manejo y organización), mantenimiento y soporte técnico.
3.	análisis árbol de decisión de fallas/contingencias para generar los protocolos.
a) Metas asociadas
5.3.1 Programa de seguridad de activos de información.
Se contará con el programa de seguridad de activos de información conforme a la norma ISO 27001 por 12 meses. La gestión de la Seguridad de la Información se debe realizar mediante un proceso sistémico, documentado y conocido por toda la empresa. El programa consistirá en preservar la confidencialidad (que la información no esté a disposición de individuos o entidades no autorizadas), integridad (que la información y su procesamiento se mantenga en forma completa y exacta) y disponibilidad ((que el acceso y la utilización de la información y procedimientos de análisis se fácil y expedito) del sistema de gestión del POETY. 
5.3.2 Programa de mantenimiento del sistema de gestión.
Se contará con un programa de mantenimiento del sistema de gestión por 12 meses, a partir de la instalación del sistema en SEDUMA. Las actividades de este programa incluirán actualizaciones de las plataformas computacionales, la integración de nuevos programas, módulos y parches. Ya que el sistema estará basado en web y la nube, las actualizaciones serán automatizadas y con mínimo disturbio para los usuarios y beneficiarios.
5.3.3 Programa de soporte técnico del sistema de gestión.
Se elaborará un programa de soporte técnico del sistema de gestión por 12 meses, que se implementará a partir del tercer año del proyecto con la instalación del sistema en SEDUMA. El soporte técnico consistirá en la guía experta tanto en los aspectos técnicos de computación como en los teórico-metodológicos sobre de la operación del sistema y la bitácora ambiental, la formulación de políticas públicas transversales y la gestión procesos de gobernanza colaborativa en el contexto del POETY. 

b) Productos comprometidos asociados al objetivo 5
5.3.1 Plan de seguridad, mantenimiento y soporte técnico del Sistema

c) Especificación productos comprometidos:
4.2.1 Sistema desarrollado e implementado. - Infraestructura tecnológica de software y hardware del sistema de gestión para el ordenamiento ecológico del territorio del estado de Yucatán, desarrollada e implementada de acuerdo con las especificaciones del proyecto correspondiente (producto esperado 4.1.1).
Productos Comprometidos:
4.3.1 Puesta en marcha del Sistema - Documentos probatorios de las siguientes actividades: a) La capacitación para el personal de la Secretaría de Desarrollo Urbano y Medio Ambiente del Gobierno del Estado Yucatán (SEDUMA) que operará el Sistema. b) La realización de pruebas de funcionamiento del Sistema. c) La implementación de una estrategia de difusión y divulgación del Sistema, así como de sus beneficios en el corto y mediano plazos, dirigido a los actores involucrados en la gestión del ordenamiento ecológico del territorio del estado de Yucatán.
5.3.1 Plan de seguridad, mantenimiento y soporte técnico del Sistema - Documento con el plan que garantizará el correcto funcionamiento del Sistema en el largo plazo y estrategia de acompañamiento posterior a la ejecución del proyecto, en la que LANCIS brindará soporte técnico al SEDUMA, al menos durante los primeros seis meses de operación del Sistema.


### Obligaciones legales de la SDS en materia de transparencia


#### Ley de Transparencia y Acceso a la Información Pública   del Estado de Yucatán
--
Artículo 40. Mejores prácticas.    La SDS podrá desarrollar o adoptar, esquemas de mejores   prácticas para: I. Elevar el nivel del cumplimiento de las disposiciones   previstas en esta ley; II. Armonizar el acceso a la información por sectores;   III. Facilitar el ejercicio del derecho de acceso a la información de las   personas y IV. Procurar la accesibilidad de la información.
Artículo 42. Medios idóneos    La información publicada por la SDS se difundirá en los   medios y formatos que más convenga al público al que va dirigida.
Artículo 43. Generación de conocimiento público útil.   La información publicada debe permitir la generación de   conocimiento público útil para disminuir asimetrías de la información,   mejorar los accesos a trámites y servicios, optimizar la toma de decisiones   de autoridades o ciudadanos y debe tener un objeto claro enfocado en las   necesidades de sectores de la sociedad determinado o determinable.
Artículo 44. Transparencia focalizada.   La información pública focalizada se establece sobre   prácticas específicas con el fin de hacer posible la evaluación oportuna,   comparativa, sobre servicios, proyectos o políticas que establezcan o   ejecuten los sujetos obligados, sobre un tema específico o relevante, que   permita unificar criterios y generar información general y significativa de   forma sistematizada y ordenada.
Artículo 47. Obligaciones en materia de gobierno abierto.      I. Establecer políticas internas para conducirse de forma   transparente.    II. Generar las condiciones que permitan que permee la   participación de ciudadanos y grupos de interés.    III. Crear mecanismos para rendir cuentas de sus   acciones.    IV. Promover la eficacia tanto en la organización de su   trabajo como en su propio desempeño.
Artículo 48. Competencias específicas en materia de   gobierno abierto   b) Propiciar mecanismos de acceso público a las sesiones   de los órganos colegiados administrativos, siempre que su propia naturaleza   lo permita.    c) Procurar la utilización de lenguaje sencillo en sus   resoluciones.    d) Implementar plataformas electrónicas y otras   herramientas que permita la interacción de la sociedad frente a la actuación   jurisdiccional.    e) Instituir un grupo de trabajo con la sociedad que   posibilite la interacción permanente, la detección de áreas de oportunidad y   el establecimiento de políticas de apertura institucional. En este caso se   emitirán los lineamientos que establezcan la forma y términos de   implementación del trabajo conjunto con la sociedad.
Artículo 50. Obligaciones de los sujetos obligados. La   SDS tiene las obligaciones establecidas en el artículo 24 de la Ley general.
Artículo 52. Obligación de documentar    La SDS debe documentar todo acto que derive del ejercicio   de sus facultades, competencias o funciones.
Artículo 64. Características de la información.   La información que se ponga a disposición de los   particulares debe ser accesible, actualizada, completa, comprensible,   confiable, congruente, integral, oportuna, veraz y verificable, y cumplir con   los lineamientos técnicos que, para su publicación, emita el sistema nacional   para garantizar su homogeneidad y estandarización. En la generación,   publicación y entrega de la información, los sujetos obligados utilizarán un   lenguaje sencillo y con perspectiva de género, y promoverán su accesibilidad   en formatos abiertos que permitan su interoperabilidad y reutilización
Artículo 65. Ajustes razonables y medidas de inclusión   social    La SDS promoverá la implementación de ajustes razonables   y de medidas de inclusión social, a través de acuerdos con instituciones   públicas para llevar a cabo la transcripción en braille, la traducción en   lengua maya o la generación de cualquier formato que permita garantizar a las   personas el derecho humano de acceso a la información…, siempre que se   requieran en un caso particular y no le impongan una carga desproporcionada
Artículo 66. Publicación de la información en internet   La información sujeta a las obligaciones de transparencia   será publicada de manera clara, estructurada y entendible, a través del sitio   web de los sujetos obligados y de la plataforma nacional, de conformidad con   los lineamientos generales que expida el sistema nacional y demás   normatividad aplicable. La página de inicio de los sitios web de los sujetos   obligados tendrán un vínculo de acceso directo al sitio donde se encuentra la   información obligatoria, que debe tener un buscador.
Artículo 67. Actualización de la información.   La información relativa a las obligaciones de   transparencia deberá actualizarse, por lo menos, cada tres meses, salvo que   la ley general o la normatividad aplicable establezcan un plazo diverso. La   información a que se refiere este artículo deberá indicar el sujeto obligado   encargado de generarla y la fecha de su última actualización, y permanecer   disponible y accesible a los particulares el tiempo que determine el sistema   nacional.
Artículo 69. Consulta y difusión de la información. La   SDS, a través de su unidad de transparencia, pondrá a disposición de las   personas interesadas equipos de cómputo con acceso a internet, que les   permitan consultar la información o utilizar el sistema de solicitudes de   acceso a la información. Con independencia de lo dispuesto en el párrafo   anterior, la SDS debe utilizar medios alternativos de difusión de la   información cuando resulten de más fácil acceso y comprensión.
Artículo 71. Datos personales.   La SDS es responsable de los datos personales en su   posesión y en relación con estos deberán sujetarse a lo dispuesto en los   artículos 68 de la Ley general.
Artículo 72. Información obligatoria de los sujetos   obligados. La SDS debe publicar en su sitio web y mantener actualizada, sin   necesidad de que medie solicitud alguna, la información común establecida en   el artículo 70 de la Ley general.    Además, se debe poner a disposición del público y   actualizar la prevista en el artículo 71.
Artículo 79. Acceso a la información    Cualquier persona podrá ejercer su derecho de acceso a la   información, sin que acredite interés alguno o justifique su utilización,   mediante la presentación de la solicitud respectiva, a través del   procedimiento establecido en el título séptimo de la ley general….


#### Ley General de Transparencia y Acceso a la Información   Pública (DOF, 2015)
--
Artículo 24. Obligaciones de la SDS como sujeto obligado:   IV. Constituir y mantener actualizados sus sistemas de archivo y gestión   documental, conforme a la normatividad aplicable; V. Promover la generación,   documentación y publicación y de la información en Formatos Abiertos y   Accesibles; XI. Publicar y mantener actualizada la información relativa a las   obligaciones de transparencia; XII. Difundir proactivamente información de   interés público; |  
Artículo 70. La SDS debe poner a disposición del público   y mantener actualizada, en medios electrónicos por lo menos la información de   los temas, documentos y políticas siguientes:    I. El marco normativo aplicable a la SDS, que incluya   leyes, códigos, reglamentos, decretos de creación, manuales administrativos,   reglas de operación, criterios, políticas, entre otros;    II. Su estructura orgánica completa que permita vincular   la estructura, las atribuciones y responsabilidades de cada servidor público...;   III. Las facultades de cada Área;   IV. Las metas y objetivos de las Áreas de conformidad con   sus programas operativos;    V. Los indicadores relacionados con temas de interés   público o trascendencia social que, conforme a sus funciones, deban   establecer;    VI. Los indicadores que permitan rendir cuenta de sus   objetivos y resultados;    VII. El directorio de todos los Servidores Públicos,    XX. Los trámites, requisitos y formatos que ofrecen;    XXI. La información financiera sobre el presupuesto   asignado, así como los informes del ejercicio trimestral del gasto, en   términos de la Ley General de Contabilidad Gubernamental y demás normatividad   aplicable;    XXIII. Los montos   destinados a gastos relativos a comunicación social y publicidad oficial   desglosada por tipo de medio, proveedores, número de contrato y concepto o   campaña; |

**Comment by ofegarcia** [comment]
@dpedroza74 
Daniela, te incluyo nuevamente para que tengas la información de activos de información que envié ayer.

**Comment by Nayita** [comment]
### Aviso
Se ha escrito al correo de NYCE para saber el estatus del trámite de compra de las Normas. 
Respondieron que enviáramos el pago a la siguiente liga y ya se genero el aviso de recibido.


![recorte](https://user-images.githubusercontent.com/25210323/73776108-c8ca2900-474c-11ea-915f-bf725eff4528.PNG)

En espera del envío de las normas.

**Comment by Nayita** [comment]
### Aviso

Las normas ya se encuentran en la siguiente ruta para su consulta: /FOMIX/fmx_diag_insti/activos_informacion

Los archivos son los siguientes: NMX-1-27001-NYCE-2015.pdf y NMX-1-27005-NYCE-2011.pdf

**Comment by ofegarcia** [comment]
Se colocaron en la carpeta de fomix/activos_informacion:
- procedimientos que elaboramos sobre los trámites en los que emplean el POETY (word)
- manual de organización de la dirección de planeación y cambio climático, proporcionado por la SDS
- cuestionarios respondidos por funcionarios (excel)
-  imagen del organigrama

La liga de la SDS:   sds.yucatan.gob.mx/directorio-funcionarios/index.php

**Comment by Nayita** [comment]
### Aviso

@ofegarcia la propuesta de cuestionario general y la propuesta de estrategia para el diagnóstico está en la siguiente ruta: FOMIX/fmx_diag_insti/activos_informacion
Archivos:
propuesta_bd_diagnostico.xlsx
propuesta_estrategia_diagnostico.docx

### Actividades

- [ ] Hacer un glosario de los rubros del bd

- [ ] Relacionar los rubros con las ISO

- [ ] Aclarar los puntos de la propuesta de estrategia

- [ ] Hacer síntesis de de ambas Normas

- [ ] Programar una reunión para aclarar dudas y acotar alcances del diagnóstico

**Comment by Nayita** [comment]
### SÍNTESIS DE LAS NORMAS ISO 27001-2015 E ISO 27005-2011

**ISO 27001-2015**

**ISO 27005-2011**


definciión de documentos e información documentada

**Comment by ofegarcia** [comment]
### Aviso
Se actualizó el archivo propuesta_bd_diagnostico, el cual ya está prellenado de acuerdo con la información que tenemos

**Comment by Nayita** [comment]
### Acuerdos de la reunión del día 17 de febrero de 2020

- Se juntarán los glosarios tanto del banco de datos como el de términos de referencia. El glosario es para uso interno.
El glosario final estará en la siguiente ruta: )\FOMIX\fmx_diag_insti\activos_informacion
Archivo: glosario_bd_activos_gral
@ofegarcia favor de completar el glosario con los artículos de la Ley de Transparencia que definen los tipos de clasificación de la información

- Se imprimirán los procedimientos a doble carta y con base en ellos se harán las entrevistas y se llenará el banco de datos (propuesta_db_diagnostico.xlsx)

- Daniela definirá la fecha de entrevistas a personal de la SDS.

**Comment by Nayita** [comment]
### Aviso

- Listo el glosario final. Está en la ruta indicada en los acuerdos de la reunión del 17/02/2020

- Listo el banco de datos final en la siguiente ruta: FOMIX\fmx_diag_insti\activos_informacion

Archivo: propuesta_bd_diagnostico.xlsx

**Comment by ofegarcia** [comment]
Se incluyeron los artículos de la  LEY GENERAL DE TRANSPARENCIA Y ACCESO A
LA INFORMACIÓN PÚBLICA que definen clasificación, información reservada e
información confidencial

**Comment by ofegarcia** [comment]
Se **actualizó el archivo propuesta_bd_diagnostico**:
Se agregó la columna B para especificar la correspondencia de los documentos mencionados en la tabla, con los elementos numerados en los diagramas de flujo.

Nota: Se **modificó el archivo de procedimiento_eia_fua** para especificar la intervención del Comité de cambio de uso de suelo y del Dpto de Geoestadística, porque solo se mencionaba que se aplicaba el procedimiento de opiniones semarnat.
