### ISSUE TITLE
Integrar informe de talleres del pronóstico de bovino #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#110]
Ruta: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos

## Insumos para el taller
Archivos: 
- bovino_v3.mdl
- fi_bovino_v3.png
- ksim_bovino.xlsx

![fi_bovino_v3](https://user-images.githubusercontent.com/57197109/138148589-538a1ecd-6409-4e0e-b150-abd8b215951d.png)

Variable | Definición | Unidades
--|--|--|
Inversión |Programas de fomento gubernamentales o por recursos de los productores | Pesos
Zonas de ganadería de bovinos | Número de cabezas de ganado | Número de animales
Producción apícola | Producción de miel | Toneladas
Uso de agroquímicos | Superficie fertilizada | Hectáreas
Vulnerabilidad del acuífero | Superficie de acuífero vulnerable | Hectáreas
Acuífero: calidad del agua | Índice | Adimensional
Consumo de agua | Volumen de agua para consumo ganadero | Litros o metros cúbicos
Acuífero: disponibilidad de agua | Disponibilidad de agua | Hectómetros cúbicos
Cobertura forestal | Vegetación forestal: selvas y pastizales naturales | Hectáreas
Producción de forrajes | Zonas de pastizal inducido y agricultura tecnificada para producción de granos: maíz forrajero y alfalfa | Hectáreas
Hábitat de flora y fauna | Superficie con buen estado de conservación | Hectáreas

**Comment by TatianaMerino** [comment]
## Insumos generados en el taller

Archivos: 
- bovino_taller.mld
- fi_bovino_taller.png
- ksim_bovino.xlsx

![fi_bovino_taller](https://user-images.githubusercontent.com/57197109/138350208-7e7423f3-b9b5-4abc-8ff4-e74004ada042.png)

## Insumos para informe
Archivos: 

- bovino_informe.mld
- fi_bovino_informe.png

![fi_bovino_informe](https://user-images.githubusercontent.com/57197109/138498308-e2ca383c-5a04-40e5-a7a2-c6b41a103d9c.png)


Variable | Definición | Unidades
--|--|--|
Acuífero: calidad   del agua | Índice | Adimensional
Acuífero: disponibilidad de agua | Disponibilidad Media Anual de Agua Subterránea | Hectómetros cúbicos
Calidad del aire | Promedio de emisiones de contaminantes atmosféricos | Partes por millón
Cobertura forestal | Superficie con cobertura forestal | Hectáreas
Consumo de agua | Consumo promedio de agua para consumo ganadero | Litros o metros cúbicos
Fertilidad del suelo | Suelo apto para la producción de biomasa | Hectáreas
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación natural | Hectáreas
Inversión | Programas de fomento gubernamentales o inversión de los productores | Pesos
Producción apícola | Producción de miel | Toneladas
Producción de forrajes | Zonas de pastizal inducido y agricultura tecnificada para producción de   granos | Hectáreas
Residuos sólidos y líquidos | Excretas y aguas residuales | Toneladas y metros cúbicos
Uso de agroquímicos | Superficie cultivada con aplicación de fertilizantes | Hectáreas
Vulnerabilidad del acuífero | Superficie de acuífero con vulnerabilidad alta a la   contaminación | Hectáreas
Zonas de ganadería de bovinos | Número de cabezas de ganado | Número de animales

**Comment by TatianaMerino** [comment]
## AVISO

Listo el video del taller para subir a la plataforma: **vi_bovino_21oct2021.mp4**

**Comment by dpedroza74** [comment]
@Nayita 
Favor de publicar en la página los resultados del taller
Ya subí a la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\bovino
las imágenes de

- Diagrama que representa los efectos del crecimiento de la ganadería de bovinos 
- Interacciones del diagrama que representa los efectos del crecimiento de la ganadería de bovinos

La lista de asistencia en pdf está en la carpeta C:\Dropbox FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\bov

**Comment by TatianaMerino** [comment]
## Variables del diagrama que representan los efectos del crecimiento de la ganadería de bovinos

Variable | Definición | Unidades
-- | -- | --
Acuífero: calidad del agua | Índice | Adimensional
Acuífero: disponibilidad de agua | Disponibilidad Media Anual de Agua Subterránea | Hectómetros cúbicos
Calidad del aire | Índice | Adimensional
Cobertura forestal | Superficie con cobertura forestal | Hectáreas
Consumo de agua | Consumo promedio de agua para consumo ganadero | Litros o metros cúbicos
Fertilidad del suelo | Suelo apto para la producción de biomasa | Hectáreas
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación   natural | Hectáreas
Inversión | Programas de fomento gubernamentales o inversión de los productores | Pesos
Producción apícola | Producción de miel | Toneladas
Producción de forrajes | Zonas de pastizal inducido y agricultura tecnificada para producción de   granos | Hectáreas
Residuos sólidos y líquidos | Excretas y aguas residuales | Toneladas y metros cúbicos
Uso de agroquímicos | Superficie cultivada con aplicación de fertilizantes | Hectáreas
Vulnerabilidad del acuífero | Superficie de acuífero con vulnerabilidad alta a la   contaminación | Hectáreas
Zonas de ganadería de bovinos | Número de cabezas de ganado | Número de animales

@Nayita

**Comment by Nayita** [comment]
### AVISO

Listo el informe.

- [x] @vichdzgeo  Favor de publicar

**Comment by ofegarcia** [comment]
@dpedroza74 
Lista la tabla de justificación de evaluación de la intensidad de las interacciones.
Ruta: fmx_estudio_tecnico\pronostico\talleres\resultados\bovino\notas
Archivo: evaluac_intensidad_bov_21oct21

**Comment by dpedroza74** [comment]
@Nayita 

- [x]  Favor de sustituir la imagen de **Interacciones del diagrama que representa los efectos del crecimiento de la ganadería de bovinos** por la que actualmente está en la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\bovino
- [x] Incluir debajo de esa imagen la siguiente tabla

**Justificación de la evaluación de intensidad de las interacciones**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Variable   causante | Variable afectada | Intensidad | Argumentación
-- | -- | -- | --
Zonas de   ganadería de bovinos | Cobertura forestal | MB | La ganadería de bovinos está   focalizada en zona oriente y la mayoría es semi intensiva. Los ranchos tienen   un tamaño de entre 40 y 200 ha.     No se espera un crecimiento en cuanto a ocupar más áreas, sino que el   crecimiento en la producción está enfocado en aumentar el número de animales   y hacer mejoras en el manejo para incrementar la producción por animal. Se   requieren cambios en el manejo para tener mayor eficiencia en términos de   relación producción animal/superficie (kg carne/ha).     Se está adoptando cambios en el manejo como el pastoreo rotativo.     Actualmente se tienen de 2 a 3 cabezas/ha, pero con manejo se puede llegar   a tener de 5 a 8 cabezas/ha.     Hay pocos casos de ganado intensivo.    En Motul y Progreso sí tienen aprovechamiento intensivo y producen   forraje para ganado estabulado.      En el sur hay sistema silvopastoril pero, por sus limitaciones, puede ser   abandonado y cambiado por semi intensivo.
Zonas de   ganadería de bovinos | Fertilidad del suelo | F | La pérdida en la fertilidad de   suelo es mayor en libre pastoreo. Con una carga animal alta, hay mayor   compactación del suelo y erosión.      Cuando se hace un manejo en el que se ponen cercos eléctricos para que los   animales pasten en un sitio, se fomenta una alta carga de defoliación del   pasto y las excretas sirven como materia orgánica para fertilizar el suelo.
Zonas   de ganadería de bovinos | Producción de forrajes | NE | El 90% de los ranchos produce su   forraje. Se utilizan pastos introducidos (estrella, guinea, jaragua) que   tienen periodo de floración más lento y por lo mismo tienen mayor calidad   alimenticia. Actualmente son monocultivos de gramíneas.     Hay una tendencia actual a la producción de forrajes de corte, no   necesariamente son todos de pastoreo.    La eficiencia de la planta dependerá de su contenido de nutrientes con   mayor materia seca por tonelada.     Hay nuevos forrajes que enraizan más profundo. Generan mayor degradación de   suelo más profundo, pero tienen mayor rendimiento 600 a 800 gr de ganancia de   peso/d, con árboles sube hasta 1 kg/d.     El alimento debe ponerse al alcance de los animales reduciendo el gasto   energético que reduce la productividad. Ello lleva a la necesidad de manejar   pastos de corte en áreas concentradas.
Producción   de forrajes | Consumo de agua | F | La producción de forraje depende   de tecnificación del riego. Al concentrar el agua en forrajes, consumes los   litros que se pierden de evapotranspiración.     Existen técnicas para minimizar el consumo: manejo silvopastoril,   reforestar, disminuir impactos por sequía, mejorar la producción y   aprovechamiento de forraje por unidad de ha, balancear la nutrición de los   animales.
Zonas   de ganadería de bovinos | Residuos sólidos y líquidos | F (manejo intensivo y establos   lecheros)     B (manejo extensivo) | Un animal de 400 kg come 40kg de   alimento y genera 4kg de excretas/día.      Fuerte en la ganadería intensiva y en establos lecheros, porque requieren   tener manejo de las excretas.           Bajo en sistemas de pastoreo extensivo y semi intensivo, porque se deja en   la pradera y no se concentra. No hay manejo de estiércol.
Residuos   sólidos y líquidos | Calidad del aire | F (manejo intensivo y establos   lecheros)     B (manejo extensivo) | Fuerte en manejo intensivo y   establos leche-ros. La parte de ordeña tiene problema de olores por la   concentración de estiércol.     Bajo en libre pastoreo.
Zonas   de ganadería de bovinos | Consumo de agua | F (manejo intensivo y establos   lecheros)     M (manejo extensivo) | Fuerte para sistemas de manejo   intensivo y los establos lecheros que consumen agua en la limpieza y   operación del establo, la producción de forraje y el consumo del animal para   la producción de leche (15 li-tros/cabeza).          Moderado para sistemas de manejo extensivo en ranchos de becerros y engorda   (5 litros/cabeza).     La reforestación de los potreros es muy importante para reducir el estrés   por calor de los animales y reducir la necesidad de agua.          Se pueden hacer mejoras para hacer más eficiente el uso del agua, como   establecer horarios y sistemas de riego que disminuyan la evaporación.
Consumo   de agua | Acuífero: calidad de agua | B | Efecto en la calidad del agua se   da específicamente en la zona costera (40 km tierra adentro de la línea de   costa). Ya se registró intrusión salina en el oriente.      En zonas más alejadas de la costa, si hay un exceso de extracción, se puede   mezclar el agua salina con el agua dulce.      Por ahora el efecto es bajo pero, a medida que aumente la extracción del   agua, se puede agravar.
Consumo de   agua | Acuífero: disponibilidad de agua | M, F (con riego) | Moderada actualmente, pero puede   ser fuerte si se establecen sistemas de riego para la producción de forraje y   por los efectos del cambio climático (cambios en el patrón de precipitación).



</body>

</html>

**Comment by Nayita** [comment]
### AVISO

Listas las correcciones solicitadas.

- [x] @vichdzgeo Favor de publicar

**Comment by dpedroza74** [comment]
@Nayita

Favor de sustituir en la página la lista de asistencia con la que ya incluye los talleres de noviembre que está en la carpeta \FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\bov

**Comment by Nayita** [comment]
### AVISO

Lista la sustitución.

- [x] @vichdzgeo favor de publicar
