### ISSUE TITLE
Integrar informe de talleres del pronóstico de energía #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#111]
Ruta: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos

## Insumos previos al taller
Archivos: 
- energia_v1.mdl
- fi_energia_v1.png
- ksim_energia.xlsx

![fi_energia_v1](https://user-images.githubusercontent.com/57197109/138506806-33fe3147-8d68-4ab6-9b7e-3048d4b9fa82.png)

**Comment by TatianaMerino** [comment]
## Insumos generados en el taller
Archivos: 
- fi_energia_taller
- energia_taller.mdl
- ksim_energia.xlsx

![fi_energia_taller](https://user-images.githubusercontent.com/57197109/138950064-857fd774-e9f5-4074-ad8a-bb795ccb1546.png)

## Insumos para informe

![fi_energia_informe](https://user-images.githubusercontent.com/57197109/139322175-162962ba-5eab-468c-bff9-7c869db2d01f.png)

Archivos: 
- fi_energia_informe.png
- energia_informe.mdl
@dpedroza74 las definniciones están en el excel **definiciones_energia.xlsx**

**Comment by TatianaMerino** [comment]
## AVISO

Listo el video del taller para subir a la página: **vi_energia_26oct21.mp4**

**Comment by dpedroza74** [comment]
@Nayita 
Favor de subir en la página los productos del taller. En la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\energia 
están las imágenes de
- Diagrama que representa los efectos del crecimiento del sector energético
- Interacciones del diagrama que representa los efectos del crecimiento del sector energético

La lista de asistencia está en
FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\ener

**Comment by TatianaMerino** [comment]
@Nayita 

**Variables del diagrama que representa los efectos del crecimiento del sector energético** 

Variable | Definición | Unidades
-- | -- | --
Acuífero: calidad del agua | Índice | Adimensional
Acuífero: disponibilidad de agua | Disponibilidad Media Anual de Agua Subterránea | Hectómetros cúbicos
Aguas residuales | Aguas residuales | Metros cúbicos
Calidad del aire | Índice | Adimensional
Cobertura forestal | Superficie con cobertura forestal | Hectáreas
Consumo de agua | Consumo promedio de agua por planta | Metros cúbicos por año
Ductos de distribución de combustibles | Gasoductos | Kilómetros
Generación y distribución de energía | Superficie de instalaciones de energía eólica, solar y termoeléctricas | Hectáreas
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación natural | Hectáreas
Población aves y murciélagos | Número de aves y murciélagos | Número de animales
Termoeléctricas | Superficie de plantas termoeléctricas | Hectáreas
Vulnerabilidad del acuífero | Superficie de acuífero con vulnerabilidad alta a la contaminación | Hectáreas
Zonas agrícolas | Superficie de zonas de uso agrícola | Hectáreas
Zonas agropecuarias | Superficie de zonas con uso agropecuario | Hectáreas
Zonas energía eólica | Superficie con proyectos de energía eólica | Hectáreas
Zonas energía solar | Superficie con proyectos de energía solar | Hectáreas
Zonas pecuarias | Superficie de zonas de uso pecuario bovino, pecuario porcino y avícola | Hectáreas
Zonas turismo de sol y playa | Superficie de zonas de uso turístico de sol y playa | Hectáreas
Zonas urbanas e industriales | Superficie de zonas urbanas e industriales | Hectáreas

**Comment by Nayita** [comment]
### AVISO

Listo el informe.

- [ ] @vichdzgeo Favor de publicar

**Comment by ofegarcia** [comment]
Lista la tabla de justificación de evaluación de la intensidad de las interacciones.
Ruta: fmx_estudio_tecnico\pronostico\talleres\resultados\energia\notas
Archivo: evaluac_intensidad_ene_26oct21

**Comment by dpedroza74** [comment]
@Nayita 

Favor de incluir debajo de la imagen de 
**Interacciones del diagrama que representa los efectos del crecimiento del sector energético**

la siguiente tabla
**Justificación de la evaluación de intensidad de las interacciones**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Variable   causante | Variable afectada | Intensidad | Argumentación
-- | -- | -- | --
Zonas   energía solar | Cobertura forestal | MF, F | En proyectos fotovoltaicos se   hace el cambio de uso de suelo para instalaciones (caminos, subestación,   celdas solares, líneas de transmisión) en el 80% del terreno.      Se ha generado deforestación de selva baja y mediana. En Muna se   deforestaron aprox. 500 ha de selva y en Valladolid 200 ha, pero está   suspendido.          Referencia de la diferencia de intensidad de cambio de cobertura de   proyectos eólicos y solares:     • Para generar 90 mega watts en proyecto eólico se requieren 900 ha y se   usan 27ha (3% del terreno) para las instalaciones.     • Para generar 90 mega watts en proyecto fotovoltaico se requieren 2 ha/MW   por lo que se requiere un terreno de 180 ha de las cuales se utilizan 144 ha   (80% del terreno) para las instalaciones.
Zonas   energía eólica | Cobertura forestal | B, M | Bajo por la superficie que se   utiliza.     Los parques eólicos requieren terrenos grandes de cientos de hectáreas,   pero únicamente se hace el cambio de uso de suelo para instalaciones   (caminos, subestación, cimentación de aerogeneradores, turbinas, líneas de   transmisión) en el 3-5% del terreno y en el resto se pueden seguir haciendo   las actividades.     Hay parques que se ubican en zonas de cultivo, arrendadas.      Las líneas de distribución de energía eléc-trica generalmente se ponen en   zonas urbana y en zonas rurales se usa el derecho de vía de la SCT. No se   instalan sobre áreas forestales, por eso no se consideran como generadores de   cambio de uso de suelo. Se hacen zanjas y los ingenieros forestales hacen   medidas de mitigación.          Moderado porque estos proyectos generan más fragmentación, aumentando el   número de parches de vegetación.
Termoeléctrica | Cobertura forestal | B | El tamaño de los terrenos de las   instalaciones termoeléctricas es menor y gene-ralmente ocupan el 100% de la   superficie. Se desmonta totalmente el predio y de los caminos también. Dejan   franja con vegetación para amortiguar el ruido. También se considera el   cambio de cobertura de los pozos para la extracción de agua fuera del   terreno.     Las termoeléctricas generan gran cantidad de energía en superficie pequeña.   Mérida III genera 480 megas en 9 ha.
Ductos de   distribución de combustibles | Cobertura forestal | B | No se tiene planeado aumentar   gasoducto en el mediano plazo, ya que el proyecto Cuxtal II hacia Q. Roo está   suspendido. Sólo se plantea la distribución (“la última milla”).
Zonas   energía solar | Zonas agropecuarias | B | Los proyectos de energía   fotovoltaica que ya están operando se han realizado en áreas ya afectadas.        En Peto se instaló el parque solar Justicia Social en terrenos con uso   agropecuario.     En Progreso se instaló el proyecto San Ignacio en un terreno que era banco   de materiales (Isla Cervera) en la terminal remota del puerto.
Zonas   energía eólica | Zonas agropecuarias | B | Bajo porque sólo se ocupa un   pequeño porcentaje del terreno total y en el resto no se limitan, ni se   interfieren las actividades.
Zonas   energía eólica | Población de aves y murciélagos | NE | En general, no hay información   pública sobre la afectación en Yucatán. El estado es paso de muchas aves   migratorias y hábitat de aves endémicas.      Hay documento del banco mundial para Oaxaca.      Las empresas están obligadas a hacer estudios, previo a la instalación del   proyecto.      APER realiza estudio regional sobre el impacto de proyectos renovables en   el estado, pero aún no se concluye.
Termoeléctricas | Aguas residuales | M | Se devuelven al subsuelo   15-20l/seg., pero el volumen es importante.     El agua se inyecta a 38-39 °C y lleva nitrógeno y metales.
Termoeléctricas | Consumo de agua | F , B | Se utiliza agua para la   generación y para el sistema de enfriamiento.      Fuerte si el sistema de enfriamiento es por torres de enfriamiento, donde   se utilizan 100l/seg de los cuales la mayoría se evapora y se devuelven al   subsuelo 15-20l/seg.          Bajo si el sistema de enfriamiento son aerocondensadores, en las calderas   de reposición se utilizan 3-5l/seg y tienen ciclo cerrado.



</body>

</html>

**Comment by Nayita** [comment]
### AVISO

Listas las correcciones solicitadas.

- [ ] @vichdzgeo Favor de publicar

**Comment by dpedroza74** [comment]
@Nayita 
Favor de sustituir en la página la lista de asistencia con la que ya incluye los talleres de noviembre que está en la carpeta \FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\ener

**Comment by Nayita** [comment]
### AVISO

Lista la sustitución.

- [x] @vichdzgeo favor de publicar
