### ISSUE TITLE
Integrar informe de talleres del pronóstico de turismo sol y playa #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#112]
\FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos

## Insumos para taller
- turismo_taller.mdl
- fi_turismo_v3

![fi_turismo_v3](https://user-images.githubusercontent.com/57197109/139145043-65eaf917-04cd-46a1-ad6a-b83181fc15ee.png)

**Comment by TatianaMerino** [comment]
## Insumos generados en el taller
fi_turismo_taller.png
![fi_turismo_taller](https://user-images.githubusercontent.com/57197109/139316497-34a51200-8123-4dc3-975d-2fde2f35bd7a.png)

## Isumos para informe
- turismo_informe.mdl
- fi_turismo_informe.png
- definiciones_turismo.xlsx @dpedroza74 

![fi_turismo_informe](https://user-images.githubusercontent.com/57197109/139345819-c8828488-8997-4ed1-9982-70ccbffbe183.png)

**Comment by dpedroza74** [comment]
@Nayita 
Favor de subir productos del taller a la página con el siguiente material

En la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\turismo
están las imágenes de 

- Diagrama que representa los efectos del crecimiento del turismo de sol y playa
- Interacciones del diagrama que representa los efectos del crecimiento del turismo de sol y playa

La lista de asistencia está en la carpeta
FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\tur

**Comment by TatianaMerino** [comment]
@Nayita 

**Variables del diagrama que representa los efectos del crecimiento del turismo de sol y playa**

Variable | Definición | Unidades
-- | -- | --
Acceso público a playas | Libre acceso y tránsito por las playas y la zona federal marítimo   terrestre |  
Acuífero: calidad del agua | Índice | Adimensional
Acuífero: disponibilidad de agua | Disponibilidad Media Anual de Agua Subterránea | Hectómetros cúbicos
Áreas Naturales Protegidas | Zonas establecidas como Áreas Naturales Protegidas | Hectáreas
Áreas para desarrollo de acuacultura y   pesca | Superficie de zonas con uso acuícola o pesquero | Hectáreas
Bancos de materiales pétreos | Superficie de bancos de materiales | Hectáreas
Cobertura forestal | Superficie con cobertura forestal | Hectáreas
Consumo de agua | Consumo promedio de agua por instalaciones hoteleras | Metros cúbicos por año
Generación y distribución de energía | Superficie de instalaciones de energía eólica, solar y termoeléctricas | Hectáreas
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación natural | Hectáreas
Humedales costeros | Superficie de humedales costeros | Hectáreas
Inversión | Programas de fomento gubernamentales o inversión privada | Pesos
Residuos sólidos y líquidos | Residuos sólidos y aguas residuales | Toneladas y metros cúbicos
Sistema playa-duna | Superficie de dunas costeras | Hectáreas
Vulnerabilidad ante eventos   hidrometeorológicos | Índice | Adimensional
Vulnerabilidad del acuífero | Superficie de acuífero con vulnerabilidad alta a la contaminación | Hectáreas
Zonas turismo sol y playa | Superficie con uso turístico de sol y playa y pesca recreativa | Hectáreas
Zonas urbanas | Superficie de zonas urbanas | Hectáreas

**Comment by TatianaMerino** [comment]
## AVISO

Ya está el video del taller de turismo para subirse a la página: **vi_turismo_28oct21.mp4**

**Comment by Nayita** [comment]
### AVISO

Listo el informe.

- [ ] @vichdzgeo Favor de publicar

**Comment by ofegarcia** [comment]
@dpedroza74 
Lista la tabla de justificación de evaluación de la intensidad de las interacciones.
Ruta: fmx_estudio_tecnico\pronostico\talleres\resultados\turismo_sol\notas
Archivo: evaluac_intensidad_tur_syp_28oct21

**Comment by dpedroza74** [comment]
@Nayita 

Favor de incluir en el reporte de la página después de la imagen de 
**Interacciones del diagrama que representa los efectos del crecimiento del turismo de sol y playa** la siguiente tabla

**Justificación de la evaluación de intensidad de las interacciones**

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Variable   causante | Variable afectada | Intensidad | Argumentación
-- | -- | -- | --
Zonas   turismo sol y playa | Cobertura forestal | F | Incluye hoteles, casas de   segunda residencia, desarrollos inmobiliarios asociados con turismo, club de   playa, infraestructura para turismo náutico (marinas).
Zonas   turismo sol y playa | Humedales costeros | F | Hay fuerte impacto de   infraestructura turística sobre humedales por cambios en cobertura de   manglar, rellenos de humedales, cortes y cambios de flujo hidrológico (en   particular caminos, que no dejan pasos de agua para mantener la conecti-vidad   hidrológica).     En zonas como Sisal y San Felipe, los pobladores locales no tienen   posibilidad de adquirir terrenos que los turistas sí pueden ocupar, por lo   que han ampliado sus terrenos mediante el relleno de humedales con   basura.     Hay diferentes áreas en restauración con finan-ciamiento de CONAFOR y   CONABIO.
Humedales   costeros | Vulnerabilidad ante eventos   hidrometeorológicos | F | Los humedales proveen servicios   de protección ante el oleaje y el viento.     En las comunidades costeras hay poca asimilación de riesgo a inundación,   solo consideran desplazarse en caso necesario.     LANSREC, UNAM está generando atlas de vulnera-bilidad de Sisal, Progreso y   San Felipe.
Zonas   turismo sol y playa | Sistema playa duna | MF | La instalación de   infraestructura sobre dunas y la instalación de espigones y escolleras que   detienen el transporte litoral de sedimento han generado la erosión de   playas. Además, a mayor infraestructura, habrá más turistas que desarrollen   actividades en zona de playa. Incluso el uso de motos que dañan las   dunas.     Estudios en Telchac han registrado pérdida de duna y presencia de plantas   invasoras.
Sistema   playa duna | Vulnerabilidad ante eventos   hidrometeorológicos | F | Las dunas actúan como una   barrera de protección que contrarresta el efecto del viento, del oleaje y de   las inundaciones. Asimismo, funcionan como reservorio de sedimentos porque   reciben, proveen y almacenan arena, y de ello depende en gran medida la flexibilidad   y resiliencia después de ventos de tormenta.
Zonas   turismo sol y playa | Áreas para desarrollo de   infraestructura acuícola y pesquera | M | Al crecer las áreas de turismo   (hoteles y casas de segunda residencia, marinas) desplazan a la acuacultura y   la pesca comercial o limitan su crecimiento. En particular, se ha limitado el   espacio para resguardo de las embarcaciones de los pescadores comerciales.             Actualmente el problema es moderado, pero si el crecimiento del turismo se   da en zonas aledañas a puertos de abrigo de embarcaciones de pesca comercial   habrá una mayor afectación.      Se ha anunciado un programa de desarrollo de infraestructura para turismo   náutico.
Zonas   turismo sol y playa | Residuos sólidos y líquidos | MF | No hay buen manejo de residuos   ni suficientes plantas de tratamiento, por lo que sigue existiendo vertederos   de aguas residuales hacia el mar.
Zonas de   turismo de sol y playa | Consumo de agua | F | El uso de agua por turismo se   calcula en alrededor de 600l/día, 4 veces el consumo de agua por habitante en   zonas urbanas.
Humedales   costeros | Hábitat de flora y fauna | MF | El tamaño y calidad de los   humedales proveen hábitat a diversas especies de flora y fauna.
Inversión | Zonas turismo sol y playa | NE | Se puede ver en la zona de   Celestún y del Cuyo que ya hay lotificación en la zona costera para el   desarrollo de casas y hoteles.      Se ha anunciado un programa de desarrollo de infraestructura para turismo   náutico.     El proyecto de Tren Maya va a ser un detonador de inversión     El proyecto de Ciudad Maderas lo promueven asociado a un club de playa. Va   de Sierra Papacal a Chuburná y anuncian 70,000 lotes. No sólo va a afectar   ecosistemas costeros, sino también otros ecosistemas.
Acuífero:   calidad del agua | Zonas de turismo de sol y playa | NE | En general, el agua que surte a   la zona norte de la costa (Progreso) se extrae de pozos de Mérida y sierra   Papacal.     Las casas de segunda residencia sí extraen agua del acuífero de la   costa.     La contaminación del acuífero fluye hacia la costa. Sí hay reportes de   contaminación y salinización que afecta la calidad del agua.



</body>

</html>

**Comment by Nayita** [comment]
@dpedroza74 

Ver tabla en html. No hay forma de dar formato a tamaño de columnas. Sólo he corregido texto en separaciones silábicas
Ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\build\html

**Comment by Nayita** [comment]
### AVISO

Listas las correcciones solicitadas.

- [x] @vichdzgeo Favor de publicar

**Comment by dpedroza74** [comment]
@Nayita 
Favor de sustituir en la página la lista de asistencia con la que ya incluye los talleres de noviembre que está en la carpeta \FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\tur

**Comment by Nayita** [comment]
### AVISO

Lista la sustitución.

- [ ] @vichdzgeo favor de publicar
