### ISSUE TITLE
Integrar informe de talleres del pronóstico de cambio climático #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#113]
FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos

## Insumos previos al taller
Archivos: 
- cambio_climatico_v4.mdl
- fi_cambio_clima_v4.png

![fi_cambio_clima_v4](https://user-images.githubusercontent.com/57197109/139381150-e93e9a70-e560-418d-b251-098d5a2cca04.png)

**Comment by TatianaMerino** [comment]
## Insumos del taller
- ksmi_cambio_clima. xlsx
- cambio_clima_taller. mdl
- fi_cambio_clima_taller. png

![fi_cambio_clima_taller](https://user-images.githubusercontent.com/57197109/139512008-2fecc7a6-ade1-455b-9d22-3faf625e856b.png)

## Insumos para informe
- cambio_clima_informe.mdl
- fi_cambio_informe.png
- definiciones_cambio_clima.xlsx @dpedroza74 

![fi_cambio_clima_informe_v2](https://user-images.githubusercontent.com/57197109/139739878-26928329-ba9f-4f27-be4b-a3f9ee6d3885.png)

**Comment by TatianaMerino** [comment]
## AVISO

Listo el video del taller de cambio climmático para subir a la página: **vi_cambio_clima_29oct21.mp4**

**Comment by ofegarcia** [comment]
Lista la tabla de justificación de evaluación de la intensidad de las interacciones.
Ruta: fmx_estudio_tecnico\pronostico\talleres\resultados\cambio_clim\notas
Archivo: evaluac_intensidad_clim_29oct21

**Comment by dpedroza74** [comment]
@Nayita 

Favor de subir a la página productos del taller
En la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\cambio_clima
están las imágenes de

- Diagrama que representa los efectos del cambio climático
- Interacciones del diagrama que representa los efectos del cambio climático

La lista de asistencia está en FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\camb_clim

**Comment by TatianaMerino** [comment]
@Nayita 

**Variables del diagrama que representa los efectos del cambio climático**

Variable | Definición | Unidades
-- | -- | --
Acuífero: calidad del agua | Índice | Adimensional
Acuífero: disponibilidad de agua | Disponibilidad Media Anual de   Agua Subterránea | Hectómetros cúbicos
Cobertura vegetal | Superficie con cobertura vegetal   natural | Hectáreas
Generación y distribución de energía | Superficie de instalaciones de energía eólica, solar y termoeléctricas | Hectáreas
Hábitat de flora y fauna | Superficie total del hábitat interior de parches de vegetación natural | Hectáreas
Vulnerabilidad ante eventos   hidrometeorológicos | Índice | Adimensional
Vulnerabilidad del acuífero | Superficie de acuífero con   vulnerabilidad alta a la contaminación | Hectáreas
Zonas turismo sol y playa y turismo de   naturaleza | Superficie con uso turístico de   sol y playa y turismo de naturaleza | Hectáreas
Zonas urbanas e industriales | Superficie de zonas urbanas e   industriales | Hectáreas
Todos los sectores | Superficie apta para todos los   sectores | Hectáreas
Emisión de gases GEI | Emisiones de contaminantes   atmosféricos | Toneladas al año
Temperatura | Temperatura promedio | Grados Celcius
Vectores de enfermedades | Índice | Adimensional
Cobertura    de especies melíferas | Superficie de distribución de   especies melíferas | Hectáreas
Zonas ganadería porcino y avícola | Superficie de zonas de uso   pecuario porcino y avícola | Hectáreas
Zonas agrícolas | Superficie de zonas de uso   agrícola | Hectáreas
Zonas ganadería bovinos | Superficie de zonas de uso   pecuario bovino | Hectáreas
Frecuencia e intensidad de eventos   extremos | Frecuencia, intensidad y   duración de eventos hidrometeorológicos extremos (nortes, huracanes, lluvias,   etc.) | Número, Categoría de tormentas y   huracanes, Días
Cambio en el nivel del mar | Cambio en el nivel medio del   mar | Milímetros al año
Precipitación | Patrones de precipitación | Milímetros cúbicos
Captura de carbono | Captura de carbono por cobertura   forestal | Toneladas por hectárea
Incendios | Incidencia de incendios | Número de incendios, Superficie   afectada

**Comment by Nayita** [comment]
### AVISO

Listo informe.

- [ ] @vichdzgeo Favor de publicar.

**Comment by dpedroza74** [comment]
@Nayita 

- [x] Favor de sustituir la imagen de 

Interacciones del diagrama que representa los efectos del cambio climático por la que actualmente está en la carpeta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pronostico\cambio_clima

- [x] Incluir debajo de esa imagen la siguiente tabla

**Justificación de la evaluación de intensidad de las interacciones**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/APC_10/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Variable   causante | Variable afectada | Intensidad | Argumentación
-- | -- | -- | --
Cambio   climático | Temperatura | MF | El cambio climático no solo es   aumento de temperatura, se mueven isotermas e isoyetas.      En 2020 hubo inundaciones que antes no se habían tenido en el estado.
Temperatura | Cobertura de especies melíferas | F | Los apicultores han visto que el   cambio de la temperatura afecta a las especies melíferas.
Temperatura | Zonas agrícolas | M | Hay efecto de la temperatura   sobre ciertos cultivos.      Ejemplo efectos sobre maíz (Madero, et al. 2018)*
Temperatura | Vectores de enfermedades | MF | Cambian patrones de distribución   de fauna que es vector de enfermedades
Temperatura | Recarga | F | Aumentos en la temperatura   pueden aumentar la evapotranspiración.
Cambio   climático | Precipitación | F, MF | Han cambiado patrones de   lluvias.     Las proyecciones para la Península señalan reducción de precipitación. El   exceso de arrastre de humedad genera lluvias excesivas.
Precipitación | Recarga | F | La disminución en la   precipitación disminuye la recarga.     Estudios calculan una reducción de entre 20 y 20% de recarga del acuífero   ante escenarios de cambio climático (Rodrí-guez-Huerta et al. 2020)**
Cambio   climático | Frecuencia, intensidad y duración   de eventos extremos | MF | Huracanes y sequías serán más   extremos. Aunque no lleguen a ser huracanes, las lluvias también duran más o   descargan más agua en poco tiempo.      Las inundaciones en zonas urbanas que están a 5msn el manto freático se   inundaron.     En Motul hubo inundaciones en ranchos ganaderos y murieron animales.
Frecuencia,   intensidad y duración de eventos extremos | Vulnerabilidad ante eventos   hidrometeorológicos | F | El efecto de huracanes varía   entre zonas. El efecto de tres tormentas acumuladas en 2020 fue mayor que los   ocasionados por un huracán.     En algunas localidades costeras se han implementado estrategias   adaptativas, como construir las casas de losa y no de madera.
Cambio   climático | Cambio en el nivel del mar | F, MF | Varía por zonas.     Para Progreso se registra una tasa de 2.5 +- 1.2mm/año en el periodo de   1952 a 1984 (Zavala-Hidalgo et al. 2010).
Cambio en   el nivel del mar | Vulnerabilidad ante eventos   hidrometeorológicos | F | El aumento del nivel del mar y   las actividades en la costa generan cambios en la topografía (por   compactación y cambios en patrones de acreción y erosión), que tiene efectos   sobre la vulnerabilidad costera.
*Mardero, S., Schmook, B., López-Martínez, J. O., Cicero, L.,   Radel, C., & Christman, Z. (2018). The uneven influence of climate trends   and agricultural policies on maize production in the Yucatan Peninsu-la,   Mexico. Land, 7(3), 80.     **Rodríguez-Huerta, E., Rosas-Casals, M., & Hernández-Terrones, L. M.   (2020). A water balance model to estimate climate change impact on   groundwater recharge in Yucatan Peninsula, Mexico. Hydrological Sciences   Journal, 65(3), 470-486.     ***Zavala-Hidalgo, J., De Buen Kalman, R., Romero-Centeno, R., &   Hernández-Maguey, F. (2010). Tendencias del nivel del mar en las costas   mexicanas. Vulnerabilidad de las zonas costeras mexicanas ante el cambio   climático, 249-268.



</body>

</html>

**Comment by Nayita** [comment]
@dpedroza74 

Ver html para verificar la nueva tabla.
Ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\build\html

**Comment by dpedroza74** [comment]
@Nayita 

Favor de sustituir en la página la lista de asistencia con la que ya incluye los talleres de noviembre que está en la carpeta FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\pagina web\camb_clim

**Comment by Nayita** [comment]
### AVISO

Lista la sustitución.

- [ ] @vichdzgeo favor de publicar
