### ISSUE TITLE
Integrar modelo general de factores de transformación con escenarios para pronóstico #FOMIX 

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#114]
A partir de los modelos (diagramas de flujo y KSIM) de los talleres virtuales del pronóstico, se integró la información en un solo modelo. 

## Insumos 
Diagramas VENSIM y modelos KSIM individuales en #68 #80 #110  #111 #108 #112 #113  

Ruta: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim

## Diagramas de flujo
En: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\diagramas\vensim

- Diagrama completo: **integrado_v2.mdl**
- Diagrama del subsistema ambiental: **sub_ambiental.mdl**
- Diagrama del subsistema sectorial: **sub_social_v2.mdl** 

## KSIM
En: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\talleres

- Intensidades y conexiones recopiladas de los talleres, datos, e insumos: **elementos_modelo.xlsx**
- Datos de tasas de cambio
- KSIM base: esta carpeta contiene los insumos para hacer los escenarios y trabajar en los talleres

## Insumos para talleres presenciales 
En: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\escenarios

- Una carpeta para cada escenario con cuatro archivos: **ksim_global.xlsx**; **matriz_alfa.xlsx**; **matriz_beta.xlsx**; **datos.xlsx**
- Los libros "datos.xlsx" se leen en script para graficar las iteraciones de cada escenario

**Comment by TatianaMerino** [comment]
### Insumo: sistema socioambiental
En: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos

- sist_sociamb.ai 
- sist_socioamb.png

![sist_socioamb](https://user-images.githubusercontent.com/57197109/141650854-26003dc1-beed-45b1-b761-b976638b4820.png)

@dpedroza74

**Comment by TatianaMerino** [comment]
## Taller agricultura 
e1_agr: modelo antes de ajuntar las funciones de distribución. 

e2_agr: modelo con los ajustes siguientes: 
- Las condiciones iniciales para simulación con distribución uniforme discreta con valor máximo preestablecido por Luis. 
- Todas las funciones de las matrices alfa y beta se reconstruyeron. Los rangos de las distribuciones uniformes continuas (beta) y discretas (alfa, a excepción de los residuos) son 1-2. 

**Primera calibración del modelo e2_agr**. Las modificaciones del modelo para su calibración están en FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\escenarios\cal_agr ; esta carpeta tiene los datos y gráficas, así como una ppt con el proceso que se siguió. De las gráficas obtenidas, se eligieron los cuatro escenarios con los parámetros del modelo completos como e3, e4 y e5, donde e5 corresponde al modelo final de la calibración. 

Cada escenario está en una carpeta independiente con las características necesarias para correr las gráficas en R @iaga 

Escenario|Datos de calibración
--|--
e2| inicial
e3| pre_estrategico
e4| estrategico_d2
e5| final

**Comment by iaga** [comment]
@TatianaMerino se incluyeron en las carpetas los archivos con las gráficas de los escenarios y los Rmarkdown.

**Observaciones:**
- Dejar los nombres de las columnas como salen de crystal ball: no cambiar a número
- Verificar que la hoja con los valores de prueba se llame "Datos1" sin espacio
- Corroborar por qué una variable de interacción quedó en medio de la hoja con valores de prueba para el escenario 2
- Verificar que la hoja con valores de prueba y estadísticas tengan las mismas variables: Revisar escenario 2

**Comment by iaga** [comment]
## Script para generar las gráficas con todas las condiciones iniciales

Cada carpeta debe contener, además de los archivos en excel, dos archivos:
- dicccionario_abrev.csv. El diccionario con el significado de las abreviaturas del modelo.
- ex_xxx.Rmd. El archivo Rmd que genera el html con las gráficas de los escenarios. ex es el número d escenario y xxx el nombre del taller.

Para correr el código es necesario modificar en la cabecera del Rmd los parámetros **p_esc** que representa el escenario, **p_nombre_del taller**, **p_time** el intervalo de tiempo de la simulación, **p_vars** las variables que se desean graficar y **p_conf_level** el intervalo de confianza.

params:
  p_esc: e1
  p_nombre_taller: Agricultura
  p_time: !r c('0', '5', '10', '15', '20', '25')
  p_vars: !r c('AGR', 'CFOR', 'URB', 'VACUI')
  p_conf_level: 0.95

**Importante:** Es posible incluir hasta 20 variables, en caso de necesitarse más, es necesario modificar el script
