### ISSUE TITLE
Calibrar modelo integrado pronóstico

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#115]
**Objetivo:**
Calibrar el modelo integrado y realizar la selección de escenarios

**Carpeta de trabajo:**
Modelo integrado. \CARPETAS_TRABAJO\apc_temeraria\pronostico\scenarios
Herramientas para seleccionar escenarios. \CARPETAS_TRABAJO\apc_temeraria\pronostico\scenario_discovery

**Insumos:**
Datos para calibrar el modelo
FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\talleres\datos para modelo pronostico.xlsx

**Nota:**
La calibración se realiza con 1000 experimentos, la simulación final será con 10000.

**Comment by iaga** [comment]
# Revisión AGROQUÍMICOS
cal_1
1. Modificación: SIN AGRQ EN ALFA (se elimina la relación AGROQAGR y AGROQPOB en la matriz alfa.

cal_2
1. Relación AGROQ con Ganadería, porcino-avícola y forraje: se modifica la suma para que vaya de 1/3 a 1
2. Relación GANADERÍAS. Crecimiento ganaderías de 1 a 1.5 pasamos 0.5 a 1 (alfa)
3.  Porcícolas

cal_3
1. Reducción en la relación MIELAGR, MIELAGRQ y MIELTEMP
2. Conservamos MIELCFOR (1 a 3)
3. c.i. miel 0.3 a 0.6

**Comment by iaga** [comment]
# Selección de escenarios
\CARPETAS_TRABAJO\apc_temeraria\pronostico\scenario_discovery

Extraer el banco de datos que servirá como insumo para los scritps (datos con el tiempo final de simulación): extraer_25.Rmd

**Árbol de regresión.** arbol.Rmd
**Patient Rule Induction Method (PRIM).** ./insumos/prim_example.py
**Random forest.** ./random_forest.py

## Procedimiento

**Comment by iaga** [comment]
# Actividades:

- Agregar cero y uno a las salidas del parallel
- Mediana de estado inicial y mediana de estado final
- Sacar condición inicial y final
- Variables que afectan y que son afectadas por cada sector
- Regret para estado inicial y para final

**Comment by dpedroza74** [comment]
Subí un documento de Excel _datos para modelo pronostico_ con datos base para la calibración 
en la carpeta FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\talleres

**Comment by iaga** [comment]
# Procedimiento:

## Generación de escenarios
Carpeta de trabajo: scenarios
1.- Correr la simulación para 10000 experimentos: ksim_global.xlsx, matriz_alfa.xlsx, matriz_beta.xlsx
2.- Generar un archivo en excel con dos hojas: Datos1- salidas en el tiempo, Datos-estadística y percentiles
3.- Actualizar el dashboard
4.- Correr el script que genera las trayectoria promedio con los intervalos de confianza: ex.Rmd, donde x representa el número de escenario

## Modelación exploratoria
Carpeta de trabajo: scenario_discovery
1.- Cortar el banco para el tiempo de simulación final t=25: extraer_25.Rmd, salida: banco_25_full.csv
2.- Generar el árbol: arbol.Rmd
3.- Seleccionar una rama relacionada con la región de interés
4.- Sacar archivos para coordenadas paralelas con los experimentos asociados con la rama de interés
5.- Sacar condiciones iniciales para los experimentos seleccionados
6.- Calcular regret inicial y final
7.- Describir las características de los experimentos seleccionados

**Comment by iaga** [comment]
# Modificaciones:

## 3/12/2021
Nota: se modificaron las versiones cal6_r2 y cal5_r2_v2 con
- Eliminar en beta la relación de CONH2O a VACUI
- Eliminar en beta CONH2O a HUMT Y HUMC

Version|Descripción|Cortes
--|--|--|
cal5_r2_v1|1% urbano, restricciones de consumo de agua, de urbano, relación consumo urbano es de 0.1 a 0.3 con factor relativo a agricultura de 0.1|4 (alta cobertura, baja agricultura, alta cobertura, baja urbanización), 14 387 (alta urbanización)
cal6_r2|1% urbano, restricciones de consumo de agua, de urbano, relación consumo urbano es de 0.3 a 0.9 con factor relativo a agricultura de 0.3|22 (alta cobertura, baja urbanización), 3 (alta cobertura, alta urbanización)
cal5_r2_v2|1% urbano, restricciones de consumo de agua, de urbano, relación consumo urbano es de 0.1 a 0.3 con factor relativo a agricultura de 0.1|4 (alta urbanización, baja agricultura, alta cobertura, ), 16 (alta urbanización, alta agricultura, baja cobertura), 25 (baja urbanización, baja cobertura)

**Comment by TatianaMerino** [comment]
## Calibración CONH2O
3/12/2021
- Se aprobó el comportamiento de CONH2O desde cal5_r2_v1. AGR es la actividad con respecto a la cual se calculó el consumo relativo de las otras actividades. 
- Tasa de efectos acumulativos 0.6-1%

## Actualizaciones
07/12/2021
**cal1 de regiones 1,3-7** 
- Actualización de las condiciones iniciales en la matriz alfa correspondiente a cada región. Archivo: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\talleres\valores iniciales.xlsx
- Actualización de matriz beta con las modificaciones del 3/12/2021: se eliminó en beta la relación de CONH2O a VACUI; y CONH2O a HUMT y HUMC.

**cal5_r2_v1, cal5_r2_v2 y cal6_r2**
- Actualización de las condiciones iniciales de CC en matriz alfa. Antes: 0.1-0.5, después: 0.4-0.6

**cal4_r2_v2** : cal4_r2 con actualizaciones
Version|Descripción
--|--|
cal4_r2_v1|1.3% urbano, relación consumo urbano es de 0.3 a 0.9 con factor relativo a agricultura de 0.3

**Comment by TatianaMerino** [comment]
## Escenarios región 2 (r2)

- **Umbral** de pérdida de cobertura de **0.7** (mínimo del intervalo de simulación de la condición inicial CFOR), con **media inicial CFOR** de  **0.8**

- Ecuación de vulnerabilidad (E1): 

(|CFOR25-CFOR0|/|URB25-URB0|) / (CFOR25/0.7)

- Calsificación

Reliability: si E1 < 1 "abajo" del umbral; si E1 >1 "arriba" del umbral

- Diferencia entre cal4_r2_v2 y cal5_r2_v2: **disminución de la tasa de crecimiento de zonas urbanas**

Interacción URBURB en matriz alfa
valor|cal4_v2 | cal5_v2 | cal6
--|-- | -- | -- 
min|0.05 | 0.01 | 0.01
max|0.25 | 0.05 | 0.05
tasa| 1.3%|1%|1%

- Diferencia entre cal5_r2_v2 y cal6_r2: **restricción del consumo de agua por zonas urbanas**

Interacción CONH2OURB en matriz beta (relativo a CONH2OAGR)
valor| cal4_v2 | cal5_v2 | cal6
-- | -- | -- | --
min| 0.3 | 0.3  | 0.1
max| 0.9 | 0.9 | 0.3
factor| 0.3 | 0.3 | 0.1

- Archivo con datos de comparación de escenarios: CARPETAS_TRABAJO\apc_temeraria\pronostico\resultados\region_2\cal4_5_6_r2_cfor_urb_hum.xlsx

- Resolución: **pérdida de 1/5 (20%) de los humedales si la zona urbana se duplica en 50 años con probabilidad de 7-8%**

**Comment by TatianaMerino** [comment]
## Actualizaciones: Región 2 cal7

- Modificación de matrices alfa y beta de las conexiones de GENER, los tipos de energía con las actividades, VHUR y VACUI. Estas actualizaciones deben hacerse para todas las regiones (ocupar cal7_r2 como base para las demás regiones).

- El factor de CONH2OURB con respecto a CONH2OAGR quedó de 0.1 

- Se hizo un escenario con el efecto de AGR sobre CONH2O en la ecuación de Luers. Donde AGR sustituyó a URB, y CONH2O sustituyó a CFOR. El umbral de CONH2O es **0.9** por ser el máximo del intervalo de condición inicial para esta región. 

## Acuerdos
 - Las combinaciones de las variables en la ecuación de Luers serán por los factores de transformación principales: AGR, URB, PMED, PMINI, PMEGA, GANI, GANX, TURSP, TUNT, EEOL, ESOL, ETER sobre los conflictos sectoriales.

- Las variables de respuesta en las que se van a evaluar los efectos son: HUMC, HUMT, HABT, VACUI, VHUR, MIEL, MMAYA, DUNA.

**Comment by TatianaMerino** [comment]
## Para informe

- Nombres: "variable forzante" (e.g., URB -escrita como verbo), "variable de estado" (e.g., CFOR- escrita como verbo o sustantivo) , "repercusión" (e.g., HUMC HUMT).
- En la ecuación de Vulnerabilidad de Luers W = U

# Tendencial Región 2
Revisados 10/12/2021
Nota: el factor de CONH2OURB = 0.3 => intervalo de la interacción= 0.3-0.9

### Efecto 1: URB-CFOR en HUMC y HUMT

- Condiciones iniciales de CFOR: 0.5-0.7, media= 0.6
- U= 0.4 , es 1/3 de la media inicial.
- Coordenadas paralelas : URB, CFOR, CANH2O, CONH2O, HUMC, HUMT, VACUI
- Condiciones iniciales HUMC y HUMT= 0.6-0.9, media= 0.65
- Condiciones iniciales VACUI = 0.4-0.6, media = 0.5
- umbral de riesgo= 0.6 , 1/5 (20%) de la media inicial en humedales 

### Efecto 2: URB-AGR en HUMC y HUMT

- Condiciones iniciales de AGR: 0.2-0.3, media= 0.25
- U= 0.2 , es el valor mínimo inicial.
- Coordenadas paralelas (tiempo 0 y 25): URB, AGR, CANH2O, CONH2O, HUMC, HUMT, VACUI

### Efecto 3: AGR-CONH2O en HUMC y HUMT

- Condiciones iniciales de CONH2O: 0.7-0.9, media= 0.8
- U= 0.9 , es el valor máximo inicial
- Coordenadas paralelas (tiempo 0 y 25): AGR, CANH2O, CONH2O, HUMC, HUMT, VACUI

### Efecto 4: URB-CONH2O en HUMC y HUMT

- Condiciones iniciales de CONH2O: 0.7-0.9, media= 0.8
- U= 0.9 , es el valor máximo inicial
- Coordenadas paralelas (tiempo 0 y 25): URB, CANH2O, CONH2O, HUMC, HUMT, VACUI

**Comment by TatianaMerino** [comment]
### Última calibración de escenario tendencial en la región 2

- Carpeta: tendencial_r2
- Actualizaciones: se agregó la interacción de CFORCFOR que refleja el efecto de recuperación de cobertura forestal; la integracción AGRURB se cambio de positiva a negativa por el efecto de competencia en superficie; actualización de las tasas de AGR, HUMC, HUMT, AVIC, ACUA.

**Comment by TatianaMerino** [comment]
## Avances
13-14/12/21

- El archivo **region_2_umbrales.xlsx** contiene las cruzas necesarias para analizar el modelo de la región 2, con los umbrales y tasas de crecimiento del escenario tendencial. En ese archivo se colocarán las narrativas que se obtengan de la exploración de escenarios. La ruta es: CARPETAS_TRABAJO\apc_temeraria\pronostico\scenario_discovery\region_2
- Primera calibración del modelo de la región 3, **cal1_r3**, a partir de tendencial_r2. Los cambios realizados está descritos en **cambios_cal1_r3.docx**
- Se hicieron carpetas para los escenarios contextuales (turístico y Tren Maya), pero aún no se modificó nada con respecto a tendencial_r2

**Comment by TatianaMerino** [comment]
### Actualización
15/12/21
- En **tendencial_r2**, se eliminó la interacción en matriz beta de BMAT con PMED, PMINI, PMEGA, AVIC, GENER. Estas correcciones se actualizaron en las matrices de Región 2 (contextual_tur y contextual_tren) y en Región 3 (cal1_r3).

**Comment by TatianaMerino** [comment]
## Actualización 
17/12/2021
Se cambió VACUICANH2O por VACUIRECAR

### Versión en vensim
Ruta: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\diagramas\vensim

 **integrado_ksim.mdl**: modelo vensim que corresponde a la calibración de escenario tendencial (corresponde a la ksim calibrada para la Región ll Noroeste). 

@dpedroza74

**Comment by iaga** [comment]
## Diccionario actualizado

La última versión del diccionario con la redacción aprobada se ubica en la ruta: 
\FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\talleres\diccionario_abrev_final.csv

**Comment by TatianaMerino** [comment]
## Actualizaciones Región 2
### Tendencial
Versión: tendencial_r2_v3

### Contextual
Versión: contextual_r2_v1

### Estratégico
Revisado|Nombre|Estrategia|Modificación|Observación
--|--|--|--|--|
sí |r_resp|Reducción de generación y tratamiento de los residuos pecuarios|Residuos pecuarios en alfa  e ineracción de VACUI en beta| No se observa cambio de 10% aprox en VACUI
sí |r_ress|Reducción de generación y tratamiento de los residuos sólidos|Residuos sólidos de URB, TUNT, TUSP, GANX y GANI en alfa  e ineracción de VACUI en beta| No se observa cambio de 10% aprox en VACUI
no |r_ressair|Reducción de afectación de los residuos sólidos al aire| URB, RESP, RESS en beta |Sí se observa cambio de 10% aprox en AIR
sí | r_resl|Reducción de generación y tratamiento de los residuos líquidos|Residuos líquidos de URB, TUNT,TUSP, GANX, GANI, ETER en alfa e ineracción de VACUI en beta|No se observa cambio de 10% aprox en VACUI
sí |r_residuos|Tratamiento y reuso de residuos líquidos, sólidos y pecuarios: reducción a la mitad de la generación de residuos líquidos, sólidos y pecuarios, y que se duplique en eficiencia la capacidad de procesamiento de residuos.| residuos sólidos, líquidos y pecuarios en alfa e ineracción de VACUI en beta| **Sí se observa cambio de 10% aprox en VACUI**
sí | r_tusp| Restricción del turismo de sol y playa| TUSPTUSP alfa| No se observa cambio de 10% aprox en DUNA
sí |r_tuspduna| Restricción de la afectación del turismo de sol y playa al sistema playa-duna| DUNATUSP en alfa| **Sí se observa cambio de 10% aprox en DUNA**
no| r_tmayatunt| Restricción de la afectación del tren maya a turismo de naturaleza y cultural| alfa| SÍ se observa cambio de 10% aprox en HUMC/HUMT
no| r_tmayaurb| Restricción de la afectación del tren maya a las zonas urbanas| alfa| No se observa cambio en HUMC/HUMT
no| r_ganiconh2o| Restricción del consumo de agua por ganadería intensiva| beta| No se observa cambio en HUMC/HUMT
no| r_urbconh2o| Restricción del consumo de agua urbano|  alfa| No se observa cambio en HUMC/HUMT
no| r_tuconh2o| Restricción del consumo de agua por turismos | TUSP y TUNT en beta| No se observa cambio en HUMC/HUMT
no | r_consumo| Restricción del consumo de agua por ganadería intensiva, urbano y turismos| alfa (URB) y beta (GANI, TUSP y TUNT)| Sí se observa cambio, pero menor al 10%, en HUMC/HUMT
no| r_tunt| Restricción de inversión y crecimiento del turismo de naturaleza y cultural| alfa|  No se observa cambio en HUMC/HUMT
no| r_humedales| Restricción de la afectación de humedales costeros y terrestres por zonas urbanas y turismo| de URB, TUNT y TUSP en beta|  **Sí se observa cambio de 10% aprox en HUMC/HUMT**
no| r_eeolcfor|Restricción de la afectación de plantas eólicas a cobertura forestal| beta CFOREEOL| No hay cambio en MURAV, ni en CFOR de aprox 10%
no| r_eeolmurav| Restricción de la afectación de plantas eólicas a la población de aves y murciélagos| beta| **Sí hay cambio en MURAV de aprox 10%**
no| r_cobertura| Restricción de la afectación de actividades sectoriales a la cobertura forestal| AVIC, TUSP, TUNT, URB (alfa), BMAT, MMAYA, GANX, GANI, EEOL, ESOL, ETER, PMINI, PMED, PMEGA, AVIC, TMAYA| Sólo cambio de 10% aprox en HABT y PFOR
no| r_bancos| Restricción de demanda de bancos de materiales por Turismo de naturaleza y cultural y restricción de la afectación de bancos de materiales a la vulnerabilidad del acuífero| BMATTUNT (alfa) y VACUIBMAT (beta)| No hubo cambio del 10% aprox en VACUI
no| r_tusppesca| Restricción de la afectación de la pesca por el turismo de sol y playa| beta | **Sí hubo cambio de aprox 10% en PESCA** 
no| r_tuspacua| Restricción de la afectación de la acuacultura por el turismo de sol y playa| beta | **Sí hubo cambio de aprox 10% en ACUA** 

El modelo **estrategico_r2_v1_r_completo** incluye todas las estrategias anteriores

**Comment by TatianaMerino** [comment]
# Región ll Noroeste

## Escenario tendencial 

Versión: **tendencial_r2_v3**

## Escenario contextual 

 Versión: **contextual_r2_v2**

### Supuestos
**Tren Maya**
- Incremento de residuos líquidos y sólidos por URB y TUNT
- Incremento de consumo de agua por URB y TUNT
- Incremento de generación de energía por URB y TUNT
- Aceleración de URB (expansión urbana) por inversión en el Tren Maya
- El Tren Maya genera aumento de turistas, por lo tanto, genera aceleración del crecimiento de TUNT 
- La tasa de generación de residuos sólidos sobrepasa la tasa de inversión de infraestructura de recolección y tratamiento, lo que impacta en la vulnerabilidad del acuífero

**Inversión turística**
- La tendencia de crecimiento de TUNT y TUSP ya considera la inversión en la región 2. 

### Movimientos
- Activación de TMAYA 0.2 - 0.4 en condiciones iniciales
- Adición de HABTTMAYA en beta -1 - -0.5
- Aumento de RESSURB, RESSTUNT, RESLURB, RESLTUNT al doble en alfa
- Aumento de VACUIRESS 7 - 9 en beta
- Aumento de GENERURB y GENERTUNT en beta
- Aumento de CONH2OURB en alfa y CONH2OTUNT en beta

### Notas
- Las tasas de residuos sólidos y líquidos, demanda de energía y consumo de agua se ajustaron con la tasa de crecimiento poblacional reportada por ONU Hábitat (4.7%).
- Algunas tasas no llegan a ese valor por que disminuye el incremento conforme llega a su máximo, por ello se calculó la tasa a 10 años, la cual se aproxima a la observada.

**Comment by TatianaMerino** [comment]
## Escenario estratégico Región ll Noroeste

### Actualizaciones

- Se utilizaron los cambios explorados individualmente con contextual_r2_v1 para las estrategias en contextual_r2_v2, esto resultó en el modelo completo estratégico **estrategico_r2_v1**. Nota: no se volvió a explorar individualmente cada estrategia. 
- Los resultados de los escenarios tendencial, contextual y estratégico se pueden comparar fácilmente utilizando el dashboard: **dash_comparaciones_r2.xlsx** que se encuentra en:
CARPETAS_TRABAJO\apc_temeraria\pronostico\scenarios\region_2\estrategico_r2_v1

### Bases de los cambios incorporados a estrategico_r2_v1.xlsx
 
- Reducción de afectación de los residuos sólidos al aire.
- Tratamiento y reuso de residuos líquidos, sólidos y pecuarios: reducción a la mitad de la generación de residuos líquidos, sólidos y pecuarios, y que se duplique en eficiencia la capacidad de procesamiento de residuos.
- Restricción del turismo de sol y playa
- Restricción de la afectación del turismo de sol y playa al sistema playa-duna
- Restricción de la afectación del tren maya a turismo de naturaleza y cultural
- Restricción de la afectación del tren maya a las zonas urbanas
- Restricción del consumo de agua por ganadería intensiva, urbano y turismos
- Restricción de inversión y crecimiento del turismo de naturaleza y cultural
- Restricción de la afectación de humedales costeros y terrestres por zonas urbanas y turismo
- Restricción de la afectación de plantas eólicas a la población de aves y murciélagos
- Restricción de la afectación de actividades sectoriales a la cobertura forestal
- Restricción de demanda de bancos de materiales por Turismo de naturaleza y cultural y restricción de la afectación de bancos de materiales a la vulnerabilidad del acuífero
- Restricción de la afectación de la pesca por el turismo de sol y playa
- Restricción de la afectación de la acuacultura por el turismo de sol y playa

## Notas
- Quitar la modificación de TUNT, TUSP y URB a BMAT 
- Quitar la modificación de TUNTTUNT y TUSPTUSP
- Quitar la modificación de URBTMAYA y TUNTTMAYA

## Seguimiento
Para justificar los movimientos del escenario estratégico se revisarán los medios (o mecanismos) por los que se pueden realizar las acciones que se incorporarán a las estrategias y lineamientos ecológicos. @ofegarcia 
Archivo: **acciones_verificacion_r2.doc**
Ruta: CARPETAS_TRABAJO\apc_temeraria\pronostico\scenarios\region_2\estrategico_r2_v1

**Comment by TatianaMerino** [comment]
#  Región l Poniente

## Escenario tendencial
Versión: **tendencial_r1_v1**

### Supuestos
- Las condiciones inciales de URB son las mínimas comparadas con la Región ll Noroeste, por lo tanto, a pesar de que la tasa de crecimiento URB es mayor, la generación de residuos no excede a la estatblacida para la región ll 
- URB llega a valor mínimo de 0 en 25 años, eso debido a las condiciones iniciales bajas. Esto significa que hay localidades que permanecen en su mínimo.
- Calibración de la generación de residuos bajo el mismo principio que la calibración de URB respecto a la región ll Noroeste

## Escenario contextual
Versión: **contextual_r1_v2**

### Supuestos
**Tren Maya**
- Incremento de residuos líquidos y sólidos por URB y TUNT
- Incremento de consumo de agua por URB y TUNT
- Incremento de generación de energía por URB y TUNT
- Aceleración de URB (expansión urbana) por inversión en el Tren Maya
- El Tren Maya genera aumento de turistas, por lo tanto, genera aceleración del crecimiento de TUNT 
- La tasa de generación de residuos sólidos sobrepasa la tasa de inversión de infraestructura de recolección y tratamiento, lo que impacta en la vulnerabilidad del acuífero

**Inversión turística**

- Incremento de la tasa de crecimiento de TUSP por inversión (Región con la mayor inversión en turismo de sol y playa). 
- Incremento de residuos líquidos y sólidos por TUSP
- Incremento de consumo de agua por TUSP
- Incremento de generación de energía por TUSP

### Movimientos
- Activación de TMAYA 0.2 - 0.4 en condiciones iniciales
- Aumento de RESSURB, RESSTUNT, RESLURB, RESLTUNT, RESSTUSP y RESLTUSP al doble en alfa
- Aumento de VACUIRESS 7 - 9 en beta
- Aumento de GENERURB, GENERTUSP, y GENERTUNT en beta
- Aumento de CONH2OURB en alfa y  CONH2OTUNT, CONH2OTUSP en beta
- Calibración de la tasa URB: disminución del impacto URBTMAYA porque bajo la misma intensidad que en la región ll (1-3), la tasa de crecimiento es 6%, lo cual excede lo calibrado para la ll Noroeste 

### Notas
- Las tasas de residuos sólidos y líquidos, demanda de energía y consumo de agua se ajustaron con la tasa de crecimiento poblacional reportada por ONU Hábitat (4.7%).
- Algunas tasas no llegan a ese valor por que disminuye el incremento conforme llega a su máximo, por ello se calculó la tasa a 10 años, la cual se aproxima a la observada.

**Comment by TatianaMerino** [comment]
#  Región lll Centro

## Escenario tendencial
Versión: **tendencial_r3_v1**

### Supuestos

- URB llega a valor mínimo de 0 en 25 años, eso debido a las condiciones iniciales bajas. Esto significa que hay localidades que permanecen en su mínimo.
- Calibración de la generación de residuos bajo el mismo principio que la calibración de URB respecto a la región ll Noroeste

## Escenario contextual
Versión: **contextual_r3_v1**

### Supuestos
**Tren Maya**
- Incremento de residuos líquidos y sólidos por URB y TUNT
- Incremento de consumo de agua por URB y TUNT
- Incremento de generación de energía por URB y TUNT
- Aceleración de URB (expansión urbana) por inversión en el Tren Maya
- El Tren Maya genera aumento de turistas, por lo tanto, genera aceleración del crecimiento de TUNT 
- La tasa de generación de residuos sólidos sobrepasa la tasa de inversión de infraestructura de recolección y tratamiento, lo que impacta en la vulnerabilidad del acuífero

**Inversión turística**

- La tendencia de crecimiento de TUNT  ya considera la inversión en la región 2.
- No hay TUSP, ni inversión en TUSP.

### Movimientos
- Activación de TMAYA 0.2 - 0.4 en condiciones iniciales
- Aumento de RESSURB, RESSTUNT, RESLURB, RESLTUNT 
- Aumento de VACUIRESS 7 - 9 en beta
- Aumento de GENERURB,  y GENERTUNT en beta
- Aumento de CONH2OURB en alfa y  CONH2OTUNT en beta
- Calibración de URBTMAYA y TUNTTMAYA


### Notas
- Las tasas de residuos sólidos y líquidos, demanda de energía y consumo de agua se ajustaron con la tasa de crecimiento poblacional reportada por ONU Hábitat (4.7%).
- Algunas tasas no llegan a ese valor por que disminuye el incremento conforme llega a su máximo, por ello se calculó la tasa a 10 años, la cual se aproxima a la observada.

**Comment by TatianaMerino** [comment]
#  Región lV Litoral centro

## Escenario tendencial
Versión: **tendencial_r4_v1**

### Supuestos
- No hay pesca ni crecimiento de esta actividad en la región, por lo tanto, las interacciones PESCATUSP y PESCAHABT no aplican. 

## Escenario contextual
Versión: **contextual_r4_v2**

### Supuestos
**Tren Maya**
- No hay impacto por Tren Maya

**Inversión turística de sol y playa**

- No hay inversión en turismo de naturaleza y cultural

- Incremento de la tasa de crecimiento de TUSP por inversión 
- Incremento de residuos líquidos y sólidos por TUSP
- Incremento de consumo de agua por TUSP
- Incremento de generación de energía por TUSP

### Movimientos

- Aumento de RESSTUSP y RESLTUSP al doble en alfa
- Aumento de GENERTUSP en beta
- Aumento de CONH2OTUSP en beta

#  Región V Noreste

## Escenario tendencial
Versión: **tendencial_r5_v1**

## Escenario contextual
Versión: **contextual_r5_v2**

### Supuestos
**Tren Maya**
- No hay impacto por Tren Maya

**Inversión turística de sol y playa**

- Incremento de la tasa de crecimiento de TUSP por inversión 
- Incremento de residuos líquidos y sólidos por TUSP
- Incremento de consumo de agua por TUSP
- Incremento de generación de energía por TUSP

### Movimientos

- Aumento de RESSTUSP y RESLTUSP al doble en alfa
- Aumento de GENERTUSP en beta
- Aumento de CONH2OTUSP en beta

#  Región Vl Oriente

## Escenario tendencial
Versión: **tendencial_r6_v1**

## Escenario contextual
Versión: **contextual_r6_v1**

### Supuestos
**Tren Maya**
- Incremento de residuos líquidos y sólidos por URB y TUNT
- Incremento de consumo de agua por URB y TUNT
- Incremento de generación de energía por URB y TUNT
- Aceleración de URB (expansión urbana) por inversión en el Tren Maya
- El Tren Maya genera aumento de turistas, por lo tanto, genera aceleración del crecimiento de TUNT 
- La tasa de generación de residuos sólidos sobrepasa la tasa de inversión de infraestructura de recolección y tratamiento, lo que impacta en la vulnerabilidad del acuífero

**Inversión turística de naturaleza y cultural**

- Aumento de la tasa de crecimiento de TUNT 

### Movimientos
- Activación de TMAYA 0.2 - 0.4 en condiciones iniciales
- Aumento de RESSURB, RESSTUNT, RESLURB, RESLTUNT 
- Aumento de VACUIRESS 7 - 9 en beta
- Aumento de GENERURB,  y GENERTUNT en beta
- Aumento de CONH2OURB en alfa y  CONH2OTUNT en beta
- Aumento de TUNTTUNT en alfa
- Calibración de URBTMAYA para tasa de aprox 2.5% : 0.25-1.5

### Notas
- Las tasas de residuos sólidos y líquidos, demanda de energía y consumo de agua se ajustaron con la tasa de crecimiento poblacional reportada por ONU Hábitat (4.7%).

#  Región Vll Sur

## Escenario tendencial
Versión: **tendencial_r7_v1**

## Escenario contextual
Versión: **contextual_r7_v1**

### Supuestos
**Tren Maya**
- Incremento de residuos líquidos y sólidos por URB y TUNT
- Incremento de consumo de agua por URB y TUNT
- Incremento de generación de energía por URB y TUNT
- Aceleración de URB (expansión urbana) por inversión en el Tren Maya
- El Tren Maya genera aumento de turistas, por lo tanto, genera aceleración del crecimiento de TUNT 
- La tasa de generación de residuos sólidos sobrepasa la tasa de inversión de infraestructura de recolección y tratamiento, lo que impacta en la vulnerabilidad del acuífero

**Inversión turística de naturaleza y cultural**

- Aumento de la tasa de crecimiento de TUNT 

### Movimientos
- Activación de TMAYA 0.2 - 0.4 en condiciones iniciales
- Aumento de RESSURB, RESSTUNT, RESLURB, RESLTUNT 
- Aumento de VACUIRESS 7 - 9 en beta
- Aumento de GENERURB,  y GENERTUNT en beta
- Aumento de CONH2OURB en alfa y  CONH2OTUNT en beta
- Aumento de TUNTTUNT en alfa
- Calibración de URB con URBTMAYA para tasa aprox de 2%: 0.1-0.2

### Notas
- Las tasas de residuos sólidos y líquidos, demanda de energía y consumo de agua se ajustaron con la tasa de crecimiento poblacional reportada por ONU Hábitat (4.7%).

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
