### ISSUE TITLE
Analizar los modelos mentales a partir de entrevistas  #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#116]
Objetivo: obtener y analizar los modelos mentales de las entrevistas papiit.
Insumos: entrevistas depuradas.
Ruta de trabajo: FOMIX\fmx_estudio_tecnico\trabajo_campo\informes\informe_2\mod_ment_papiit

Organización de carpeta: 
- diagramas: modelos mentales en vensim
- analisis: listas de variables y código python
- informe: insumos (figuras de modelos mentales) e informe

## Modelos mentales
En formato vensim
- [ ] Celestún – empresaria
- [ ] Celestún - médica
- [ ] Celestún - pescador
- [ ] Celestún – protección civil
- [x] Dzilam Bravo- pescador
- [ ] Dzilam Bravo -protección civil
- [x] Niños y crías
- [x] Progreso – encargada reserva corchito 
- [x] Progreso – director ecología
- [x] Progreso – médico 
- [x] Progreso – pescador
- [x] Progreso – encargado barco
- [x] Progreso – profesor
- [x] Progreso – protección civil
- [ ] Río Lagartos - enfermería
- [ ] Río Lagartos - médico
- [ ] Río Lagartos - pescador
- [ ] Río Lagartos – presidente municipal
- [ ] Río Lagartos – protección civil
- [ ] Río Lagartos – asociación hoteles
- [x] Sisal - comisario
- [ ] Sisal - empresario
- [ ] Sisal - coordinador
- [x] Sisal- ecoturismo
- [x] Sisal - restaurante
- [x] Sisal - enfermera

## Listas de variables 
En formato txt
- [ ] Celestún – empresaria
- [ ] Celestún - médica
- [ ] Celestún - pescador
- [ ] Celestún – protección civil
- [x] Dzilam Bravo- pescador
- [ ] Dzilam Bravo -protección civil
- [x] Niños y crías
- [x] Progreso – encargada reserva corchito 
- [x] Progreso – director ecología
- [x] Progreso – médico 
- [x] Progreso – pescador
- [x] Progreso – encargado barco
- [x] Progreso – profesor
- [x] Progreso – protección civil
- [ ] Río Lagartos - enfermería
- [ ] Río Lagartos - médico
- [ ] Río Lagartos - pescador
- [ ] Río Lagartos – presidente municipal
- [ ] Río Lagartos – protección civil
- [ ] Río Lagartos – asociación hoteles
- [ ] Sisal - comisario
- [ ] Sisal - empresario
- [ ] Sisal - coordinador
- [ ] Sisal- ecoturismo
- [ ] Sisal - restaurante
- [ ] Sisal - enfermera

**Comment by TatianaMerino** [comment]
## Colores de flechas

- Azul: relación causa efecto
- Morado: relaciones que diminuyen la consecuencia
- Naranja: características y no relaciones causales

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
