### ISSUE TITLE
Integrar informe de la etapa de pronóstico #FOMIX

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#117]
En este issue nos ponemos de acuerdo para el informe de la etapa de pronóstico. 
El material lo integraremos en la carpeta de dropbox (LANCIS)\FOMIX\fmx_estudio_tecnico\pronostico\informe

**Comment by dpedroza74** [comment]
@Nayita 
Favor de preparar los mapas con plantilla que se enlistan en la tabla en el documento lista_mapas_informe que está en la carpeta
FOMIX\fmx_estudio_tecnico\pronostico\informe\mapas

Cada mapa debe ir sobrepuesto con la delimitación de las 7 regiones.

**Comment by TatianaMerino** [comment]
## Diagrama de interacciones del modelo integrado 

A solicitud de hacer un diagrama de redes de las interacciones del modelo integrado para el informe, se hicieron los siguientes insumos: 
- matriz_redes_integrado.xlsx: archivo donde se hizo la combinación de las matrices alfa y beta transpuestas

- **matriz.csv** : matriz para diagrama de redes @iaga 

Carpeta de trabajo: FOMIX\fmx_estudio_tecnico\pronostico\informe\insumos

**Comment by dpedroza74** [comment]
@Nayita 
Favor de preparar también mapa en plantilla con delimitación de regiones de las capas de 

- Unidades de Producción Acuícola 2021 que esta en el proyecto de caracterización en el grupo de subsistema natural (Fuente: Secretaría de Pesca y Acuacultura Sustentables (SEPASY)) **HECHO**

- Banco de materiales que esta en el proyecto de caracterización en el grupo de subsistema productivo (Fuente: Geocomunes)
- ![image](https://user-images.githubusercontent.com/31043244/147796355-846b22d4-9266-4d84-a451-8bc8bac99d35.png)

**Comment by Nayita** [comment]
@dpedroza74 

Listos los mapas. 

Se cambiaron los siguientes mapas:

- Zonas de aprovechamiento actual de milpa maya
- Cenotes
- Granjas porcinas
- Granjas avícolas
- Ubicación de parques eólicos en Yucatán
- Ubicación de parques solares en Yucatán
- Unidades de producción acuícola
- Programa hídrico regional

Mapas cortados

- Ubicación de bancos de materiales en Yucatán
- Semáforo que indica el nivel de contaminación del agua subterránea
- Depresiones kársticas en el estado de Yucatán

**Comment by dpedroza74** [comment]
@Nayita 
Podrías también preparar este mapa de susceptibilidad del terreno a inundaciones pluviales - SGM 2020 que está en la carpeta de Áreas prioritarias para la protección, preservación, conservación y restauración del Lizmap, por favor?

![image](https://user-images.githubusercontent.com/31043244/151266751-085fb4bd-5002-4ab9-b833-80aab3b39b55.png)

**Comment by Nayita** [comment]
### AVISO

@dpedroza74 

Listo el mapa solicitado.

Ruta: FOMIX\fmx_estudio_tecnico\pronostico\informe\mapas

Archivo: mp_riesgo_inundaciones

**Comment by dpedroza74** [comment]
@Nayita 
Por favor generar el mapa de biomasa aérea que está en la carpeta de Áreas prioritarias para la protección, preservación, conservación y restauración del Lizmap, por favor?
La fuente sería: Hernández-Stefanoni _et al._ 2021
Esta es la cita completa
Hernández-Stefanoni, J. L., Castillo-Santiago, M. Á., Andres-Mauricio, J., Portillo-Quintero, C. A., Tun-Dzul, F., & Dupuy, J. M. (2021). Carbon Stocks, Species Diversity and Their Spatial Relationships in the Yucatán Peninsula, Mexico. Remote Sensing, 13(16), 3179.

![image](https://user-images.githubusercontent.com/31043244/152449729-a4807cb4-8f70-4d82-ac90-6fe2206ee416.png)

**Comment by Nayita** [comment]
@dpedroza74 

Listo mapa en ruta: \FOMIX\fmx_estudio_tecnico\pronostico\informe\mapas
Archivo: mp_biomasa_aerea

**Comment by dpedroza74** [comment]
@Nayita 
No está bien la fuente. Te había aclarado en el comentario anterior que la fuente correcta es: Hernández-Stefanoni _et al._ 2021

**Comment by Nayita** [comment]
@dpedroza74 

Listo. Disculpa no vi la nueva cita y la copié directamente del metadato.

**Comment by dpedroza74** [comment]
@Nayita 
sigue teniendo error porque dice **Stafoni** y es 
Hernández-**Stefanoni**

**Comment by Nayita** [comment]
@dpedroza74 
Listo!
