### ISSUE TITLE
Integrar repositorios para transferencia de SIG a EGEY #Fomix #Sistema de conocimiento 

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#118]
### Actividad 1. Creación de proyecto piloto para pruebas de interconectividad
- Agregar capas geográficas en /ENTREGAS/piloto_poety
- Una carpeta por shapefile
- Raster GeoTiff pueden ir en la carpeta raíz
- Archivo de estilos formato .sd con el mismo nombre de las capas geográficas
- Con reglas de nombramiento y estándar del APC

##### Shapefile
- [x] UGA con el estilo que tenemos de municipios en lizmap (no tiene estilo)
- [x] Evapotranspiración (caracterización)
- [x] Sitios Ramsar (caracterización)
- [x] ANP estatales, municipales y privadas (con base en proyecto de caracterización)
- [x] Localidades del marco geoestadístico 2020 (insumos diagnóstico)
- [x] Red de caminos (insumos diagnóstico)
- [x] Zonas parceladas (insumos diagnóstico)
- [x] Áreas de uso común (insumos diagnóstico)
- [x] Uso de suelo y vegetación modificada en la costa con la capa de manglares, para el estado de Yucatán, serie VI (2014) (appcr)
- [x] Modelo cartográfico de humedales (appcr)

##### Raster
Sector milpa maya
- [x] Función de valor de carreteras
- [x] Función de valor de cobertura
- [x] Función de valor de precipitación
- [x] Zonas de aprovechamiento actual del sector milpa maya
- [x] Mapa de aptitud del sector milpa maya

**Comment by vichdzgeo** [comment]
## Aviso

@paola-gp ya están todas las capas excepto la de UGA me indicarías la ruta?

**Comment by paola-gp** [comment]
/FOMIX/fmx_sistema_conocimiento/insumos_dass/poety_uga

**Comment by vichdzgeo** [comment]
@paola-gp de la reunión con @serranoycandela confirmamos que los estilos en los wms son correctos a los que mandamos.

**Comment by paola-gp** [comment]
### Revisión de primera entrega de wms
La ubicación de las bases de datos (no piloto) con los wms que se subirán al sistema se ubican en: /FOMIX/fmx_sistema_conocimiento/wms
Insumo de la primera entrega: bd_wms_primera_entrega.xlsx
- [x] Construir el URL del wms para hacer una verificación de la imagen (campo url_wms) @vichdzgeo 
- [x] Reconstruir las carpetas n1, n2 y n3 con respecto al archivo original @vichdzgeo 
- [x] Avisar a @Nayita cuando estén listas las actividades previas
- [x] Verificar que cada imagen sea la del informe de aptitud @Nayita 
- [x] Si alguna no es crear un campo adicional (error_wms) para identificar los problemas @Nayita

**Comment by vichdzgeo** [comment]
@Nayita en el archivo bd_wms_primera_entrega.xlsx columna M encontrarás la liga completa para ver el WMS.  se han reconstruido las columnas n1,n2,n3 ( Se han dejado por el momento con la formula de Excel.

**Comment by Nayita** [comment]
@paola-gp 

Lista la base de datos de prueba solicitado.

Ruta del archivo de la base de datos de prueba: FOMIX\fmx_sistema_conocimiento\modelo_poety_11_feb\wms
Archivo: bd_wms_prueba.xlsx

Ruta de las imágenes de los mapas y las leyendas: FOMIX\fmx_sistema_conocimiento\modelo_poety_11_feb\wms

**Comment by paola-gp** [comment]
@Nayita @vichdzgeo 

- [x] Se tiene que integrar la base de datos completa de los wms que se han recibido hasta el momento. 
- [x] Se tienen que generar las figuras de todos los wms como se hizo en la prueba que aparece en FOMIX\fmx_sistema_conocimiento\modelo_poety_11_feb\wms y agregar los nombres a la base de datos para subirla al sistema.

**Comment by vichdzgeo** [comment]
## Indicadores

Ruta: FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\wms\local

- [x] Indicadores en formato Shapefile 
- [x] Archivos de estilos SLD 
- [x] Figuras de indicadores
- [x] Figuras de leyenda para indicadores
- [ ] Agregar a la base de datos de entrada al sistema los indicadores

**Comment by vichdzgeo** [comment]
## Información base

@paola-gp ¿ De las capas consideradas como Información base - Administrativa (Municipios, Carreteras, Localidades) se requiere hacer figura y leyenda?

**Comment by vichdzgeo** [comment]
## Figuras de insumos

Ruta: C:\Dropbox (LANCIS)\FOMIX\fmx_sistema_conocimiento

@Nayita del archivo reporte_capas_diagnostico.xlsx 

podrías revisar de esos insumos cuales ya contamos con figura y en dado caso si existen proyectos en Qgis con composiciones para cada mapa de insumo, ya que habrá que generar las figuras de las leyendas.

**Comment by vichdzgeo** [comment]
## Revisar los mapas wms de la última entrega

@Nayita  

- [x] podrías de favor verificar que las capas publicadas en el servicio WMS del EGEY se visualicen correctamente.

la url completa la encontrarás en :C:\Dropbox (LANCIS)\ENTREGAS\poety\entrega_4\bd_relacion_capas_geograficas_entrega_4_poety_18jul.xlsx 

- [ ] Una vez completada y verificada la revisión integrarlas a la base de datos de wms que tenemos para la subida al sistema y rellenar los campos de fig_leyenda y fig_mapa. 

base: FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\wms\bd_wms_figuras_v_poety_abr.xlsx

- [ ] incorporar las figuras de mapa y leyenda a la carpeta FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\wms\figuras\figuras_totales_resc

**Comment by Nayita** [comment]
### AVISO

@vichdzgeo 

Al hacer la revisión de las capas publicadas se detectó la falta de la capa de agricultura tecnificada que sirvió de insumo para el modelo de ordenamiento.

Ya se hizo un nuevo archivo para esa capa.
Ruta: \ENTREGAS\poety\entrega_5
Archivo: bd_relacion_capas_geograficas_entrega_5

**Comment by vichdzgeo** [comment]
## Entrega 5 

@paola-gp 

En la revisión de capas se detecto que falto mandar al EGEY la capa del sector Agricultura tecnificada y los xml de las capas de la entrega_4 

por lo tanto se ha creado el siguiente directorio: \ENTREGAS\poety\entrega_5

el cual contiene la capa faltante  y una carpeta llamada **xml** con los xml que hacían falta de la entrega_4

también se ha creado el archivo bd_relacion_capas_geograficas_entrega_5.xlsx
