### ISSUE TITLE
Integrar Anexos del estudio técnico

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#119]
3.2.2 Anexos del estudio técnico

Esto es lo que dicen los Términos de referencia:
3.2.2 Anexos del estudio técnico. - Documentos probatorios del desarrollo de talleres participativos, reuniones de trabajo, que incluirán la descripción de las herramientas metodológicas y reglas de deci-sión utilizadas, así como las bases de datos y las capas digitales con los metadatos que sean emplearon durante el proceso.

Los insumos están en la carpeta
\FOMIX\fmx_estudio_tecnico\anexos

**Comment by dpedroza74** [comment]
@paola-gp 
en la carpeta
En la carpeta \FOMIX\fmx_estudio_tecnico\anexos está el word **anexos_estudio_tecnico**
- [x] Favor de integrar respuesta a observaciones recibidas en el formulario de validación de mapas de aptitud de personas que manifestaron no estar de acuerdo con el mapa. La tabla está en la sección 2.3 Difusión de resultados en la página 27.

- [x] Favor de revisar la estructura del documento para saber tu opinión

**Comment by paola-gp** [comment]
@dpedroza74 

Ya quedaron las observaciones, agregué algunos comentarios y sugiero agregar la respuesta a Conacyt sobre el proceso participativo como una sección adicional.
