### ISSUE TITLE
Actualizar información y hacer correcciones a mapas para las caracterizaciones #FOMIX 

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#12]
**Objetivo:** Actualizar la información contenida en los mapas elaborados para la caracterización del subsistema socioeconómico de Yucatán. 

**Tareas:**

- [x] Hacer mapa de las siete regiones de Yucatán, para agregar esta capa a los mapas.
- [x]  Actualizar información de shapes, cambiar los datos que tienen que son del censo de población y vivienda 2010 a la información intercensal 2015.

**Comment by CorinaCantero** [comment]
### TAREA 1
**Hacer mapa de siete regiones de Yucatán:**

1.  Seleccionar de la capa base "muni_2018_utm16.shp" los municipios de cada región según la página http://www.yucatan.gob.mx/estado/municipios.php
Ubicación: SIG\desarrollo\sig_fomix\insumos\limites\inegi\div_pol_mpio_2018\muni_2018_utm16.shp
 
2.  Crear una nueva capa vectorial con los objetos seleccionados: edición/copiar objetos espaciales/pegar objetos espaciales/Temporary Scratch Layer

3.  Utilizar la herramienta Dissolve para borrar los límites municipales Vectorial/Herramientas de geoproceso/Dissolve

4.  Eliminar de la tabla de atributos: área, perímetro, nom_mun, cov_, cov_id y agregar una columna llamada "region".

5. Guardar el polígono con el nombre de la región en: SIG/desarrollo/sig_fomix/procesamiento/regiones
 
6. Unir las siete regiones para terminar Vectorial/Herramientas de gestión de datos/Combinar capas vectoriales.
 
7.  Guardar la capa vectorial resultante en la ubicación, con el nombre "regiones_yuc" en: SIG/desarrollo/sig_fomix/procesamiento/regiones

**Comment by CorinaCantero** [comment]
### TAREA 2

**Actualizar datos de mapas:**

**Comment by CorinaCantero** [comment]
@Rocio97 

### TAREA 3

- [ ] **Distribución de la población por municipio:**
Proyecto: mp_numhabitantes
Cambiar las categorías a las siguientes clases:
1) con < 15,000 habitantes; 
2) entre 15,000 - 49,999 habitantes; 
3) entre 50,000 - 99,999 habitantes; 
4) igual o más de 100,000 habitantes

- [ ] **Distribución de las localidades según rango-tamaño**
Proyecto: mp_numhabitantes
Cambiar las categorías a las siguientes clases:
1) con < 15,000 habitantes; 
2) entre 15,000 - 49,999 habitantes; 
3) entre 50,000 - 99,999 habitantes; 
4) igual o más de 100,000 habitantes

- [ ] **Áreas de concentración poblacional**
Proyecto:
Poner las siguientes categorías:
1) entre 50,000 - 99,999 habitantes; 
2) igual o más de 100,000 habitantes

- [ ] **Población indígena por municipio**
Proyecto:
Con la capa actualizada "social.shp" hacer la clasificación de acuerdo con el atributo "t_mun_ind"

- [ ] **Estratos de ingreso de la población (3 mapas)**
Proyecto:
Utilizar la capa actualizada estratos_ingreso, dejar las mismas categorías que se muestran en los diseñadores de impresión
-Población ocupada que percibe menos de un salario mínimo (pob_1_salm)
-Población ocupada que percibe de uno a dos salarios mínimos (po_1_2_salm)
-Población ocupada que percibe más de dos salarios mínimos (mas_dos_salm)

- [ ]  **Población ocupada por sector de actividad (3 mapas)**
Proyecto:
Utilizar la capa actualizada act_economicas.shp, dejar las mismas categorías que se muestran en los diseñadores de impresión
-Población ocupada en el sector de actividad primario por municipio (act_prim)
-Población ocupada en el sector de actividad secundario por municipio (act_sec)
-Población ocupada en el sector de actividad terciario por municipio (act_ter)

**Comment by CorinaCantero** [comment]
##  Preparar mapas: estilo atlas y estilo informe de caracterización

A los mapas ya realizados se les harán correcciones para que existan dos versiones diferentes, una de las versiones será presentada en un atlas y la otra se usará para incluirla en los textos de caracterización.

**Ubicación de proyectos:** SIG\desarrollo\sig_fomix\mapas

Para ambos mapas:

- Dejar activa la capa de loc_principales y localidades_urbanas
Ubicación: sig_fomix/entregables/loc_principales/loc_principales.shp
                  sig_fomix/entregables/localidades_urbanas/localidades_urbanas.shp
- Desactivar capas de carreteras y cuerpo_agua_yuc
- Activar o desactivar capas según la temática de los mapas

### Editar diseñadores de impresión
- Entrar a los diseñadores de impresión (proyecto/diseñadores de impresión)
- Quitar logos de UNAM y LANCIS (seleccionar imagen/editar/borrar)
- En la sección de datos/apariencia cambiar el margen vertical y horizontal a 3mm.
- Cambiar tamaño de letra de los datos a 10. (Tipo de letra/Calibri/10)
- Cambiar la alineación vertical de los datos a Medio
- Asegurarse que en los datos, la fuente incluya autor y año.
- En la caja de datos, cambiar la fecha a Marzo 2020 y cambiar la clave del plano, empezar con "Subsistema... + clave del mapa", según se indica en el documento "organizacion_atlas.docx" ubicado en: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\organizacion_atlas.docx
- En la sección de leyenda, debe cambiarse el nombre "Localidades urbanas" a "Localidades principales". Todos los mapas deben tener en sección de leyenda las simbologías "Límite municipal" o "Límite estatal" (según sea el caso) y "Localidades principales", (en ese orden).

### Mapas para atlas (versión 1)

- Quitar selección del elemento "Mapa 0"/quitar selección de "Bloquear capas", para actualizar la vista del mapa, volver a seleccionar "Bloquear capas" y "Mapa 0".

![1_13](https://user-images.githubusercontent.com/44783182/73573851-f2780d00-4439-11ea-8803-96fe8c5f7ef5.jpg)

**Duplicar diseñador de impresión**
- Duplicar el diseñador de impresión ya editado para que sea más fácil hacer la versión para texto (proyecto/administrador de diseñadores). Ponerle nombre de v2 (versión 2)
### Mapas para textos de caracterización (versión 2)

- Eliminar mapa de la República Mexicana 
- Activar la cuadrícula Ver/Mostrar cuadrícula
- El cuadro de datos, recorrerlo hasta el extremo derecho, dejando dos cuadritos de espacio desde el límite de la hoja
- Recorrer el cuadro de leyenda para aumentar su extensión (cuatro cuadritos antes de la caja de datos)
- Si es necesario re distribuir la información contenida en la sección de simbología, cambiando la separación entre los elementos de la leyenda. (Separación
- Eliminar el título y estirar el mapa al margen superior, dejar dos cuadritos de margen. 
Para poder ver la cuadricula guía, activarla en (Ver/Mostrar cuadrícula)

![1_13](https://user-images.githubusercontent.com/44783182/73573864-fc017500-4439-11ea-982d-c71e3c7d0ec0.jpg)

-  Exportar el mapa como imagen a 300 .ppp
- Guardar los mapas, con el número de la clave del plano y en la carpeta que corresponda, según si es un mapa para el atlas o para el texto y de acuerdo al subsistema. SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes

**Comment by CorinaCantero** [comment]
@Rocio97 

### TAREA 3

**Actualizar la información de los mapas de acuerdo con las capas creadas.**

- [ ] **Distribución de la población por municipio:**
Proyecto: mp_numhabitantes
Cambiar las categorías a las siguientes clases:
1) con < 15,000 habitantes; 
2) entre 15,000 - 49,999 habitantes; 
3) entre 50,000 - 99,999 habitantes; 
4) igual o más de 100,000 habitantes

- [ ] **Distribución de las localidades según rango-tamaño**
Proyecto: mp_numhabitantes
Cambiar las categorías a las siguientes clases:
1) con < 15,000 habitantes; 
2) entre 15,000 - 49,999 habitantes; 
3) entre 50,000 - 99,999 habitantes; 
4) igual o más de 100,000 habitantes

- [ ] **Áreas de concentración poblacional**
Proyecto:
Poner las siguientes categorías:
1) entre 50,000 - 99,999 habitantes; 
2) igual o más de 100,000 habitantes

- [ ] **Población indígena por municipio**
Proyecto:
Con la capa actualizada "social.shp" hacer la clasificación de acuerdo con el atributo "t_mun_ind"

- [ ] **Estratos de ingreso de la población (3 mapas)**
Proyecto:
Utilizar la capa actualizada estratos_ingreso, dejar las mismas categorías que se muestran en los diseñadores de impresión
-Población ocupada que percibe menos de un salario mínimo (pob_1_salm)
-Población ocupada que percibe de uno a dos salarios mínimos (po_1_2_salm)
-Población ocupada que percibe más de dos salarios mínimos (mas_dos_salm)

- [ ]  **Población ocupada por sector de actividad (3 mapas)**
Proyecto:
Utilizar la capa actualizada act_economicas.shp, dejar las mismas categorías que se muestran en los diseñadores de impresión
-Población ocupada en el sector de actividad primario por municipio (act_prim)
-Población ocupada en el sector de actividad secundario por municipio (act_sec)
-Población ocupada en el sector de actividad terciario por municipio (act_ter)

**Comment by CorinaCantero** [comment]
### NOTA
Leyenda anterior para mapa de presencia indígena: 

![image](https://user-images.githubusercontent.com/44783182/76007791-3d22f400-5ed4-11ea-8a74-eb073f9967c0.png)

**Comment by CorinaCantero** [comment]
### TAREA
@Rocio97 

Reclasificar por cuantiles las siguientes capas:

**Proyecto mp_actpredominantes**

- Población ocupada en el sector de actividad primario por municipio (act_prim)
- Población ocupada en el sector de actividad secundario por municipio (act_sec)
- Población ocupada en el sector de actividad terciario por municipio (act_ter)

**Proyecto mp_ingresomun**

- Población ocupada que percibe menos de un salario mínimo (pob_1_salm)
- Población ocupada que percibe de uno a dos salarios mínimos (po_1_2_salm)
- Población ocupada que percibe más de dos salarios mínimos (mas_dos_salm)

**Proyecto mp_pobreza**
- Población en condición de pobreza por municipio
- Población en condición de pobreza extrema por municipio
- Rezago educativo por municipio

**### Correciones**
- El mapa "Grado de rezago social por municipio" debe estar clasificado según el atributo "gra_r_social" (alto, medio, bajo, muy bajo)
- Revisar el tamaño de la rosa de los vientos, en el mapa "3_25" del modo texto está más alargada.
- Los títulos de las leyendas tienen diferente tamaño de fuente, dejar en Calibri 12 Regular.
- Poner las regiones en los mapas que hace falta

**Comment by CorinaCantero** [comment]
### Tareas
Según lo acordado en la reunión del 24/03/20:

- Poner entre el título de la leyenda y la leyenda, la palabra "cuartiles", cuando se haya hecho la clasificación por ese método.
- Quitar la información que viene en los asteriscos en esta serie de mapas.
- Poner una transparencia a la capa principal del (20-25%)

![image](https://user-images.githubusercontent.com/44783182/77668144-a4b6e700-6f48-11ea-82bc-ab97554a55fc.png)

**Comment by CorinaCantero** [comment]
### AVISO
@ofegarcia 

Ya están listos los mapas para el subsistema socioeconómico, pero faltan mapas de:

- Migración
- Inmigración

Ubicación: \SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico\texto

**Comment by CorinaCantero** [comment]
### TAREA Mapas subsistema natural 
@Rocio97 

Actualizar los mapas del subsistema natural de FOMIX, segir las indicaciones de los comentarios anteriores y los mismos estilos que se utilizaron para los mapas del subsistema socioeconómico.

Especialmente realizar los siguientes cambios: 

- Agregar la capa de regiones de Yucatán a todos los mapas
- Editar en la leyenda el límite municipal/estatal para que en lugar de  cuadros aparezcan líneas
- Quitar cuerpos de agua en los mapas que aún esté activa dicha capa

**Proyecto mp_fallas_lit**
- [ ]  Geología superficial y principales características estructurales

**Proyecto mp_geomorf**
- [ ]  Fisiografía

**Proyecto mp_edafo**

- [ ] Edafología
- [ ] Tipos de erosión y degradación del suelo

 **Proyecto mp_clima**

- [ ] Clima
- [ ] Evapotranspiración real (isolíneas)
- [ ]  Isotermas medias anuales
- [ ] Precipitación media anual

**Proyecto mp_riesgo_eventosnat**

- [ ] Grado de riesgo por ciclones tropicales por municipio
- [ ] Grado de riesgo por inundaciones por municipio
- [ ] Grado de riesgo por sequías por municipio

**Proyecto mp_flora_fauna**

- [ ] Registro de ejemplares de anfibios
- [ ] Registro de ejemplares de reptiles 
- [ ] Registro de ejemplares de mamíferos
- [ ] Registro de ejemplares de aves
- [ ] Registro de ejemplares de plantas

Guardar las imágenes en la siguientes ubicaciones:
Mapas para atlas: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\atlas
Mapas para texto: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto

**Comment by CorinaCantero** [comment]
### Aviso

![image](https://user-images.githubusercontent.com/44783182/80119065-d5416f00-854e-11ea-91c8-420a5fd7b20e.png)

**Comment by CorinaCantero** [comment]
### Pendientes mapas subsistema socioeconómico
Acuerdos de reunión 13/05/2020 con @ofegarcia para mapas faltantes del subsistema socioeconómico:

- [ ] Hacer mapa de lugares centrales y marginación (sin carreteras)
- [ ] Quitar la capa de municipios a los mapas: 3_5 a 3_9
- [ ] Cambiar los rangos de número de habitantes a los mapas: 3_2, 3_6 (quitar rural y urbano) y 3_7:
< 2, 500
entre 2,500-15,000
15,000-50,000
50,000-100,000
 menos de 100,000

- [ ] Hacer **mapas de migración** utilizando la siguiente información: 

- [ ] Mapa de categoría migratoria: archivo bd_migracion, atributo catm_10 Ruta: FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_socioeconomico
- [ ] Mapa de inmigración estatal: archivo bd_migracion, atributo pob_oten
- [ ] Mapa de inmigración municipal: bd_migracion, atributo pob_otrm 
- [ ] Mapa de principales corrientes migratorias: del documento de Mendeley "Prontuario de migración interna", pág. 30 (mapa con los estados de la Península de Yucatán y la flecha de migración)

- [ ] Actualizar mapa de tipologia municipal con datos del SUN 2018 (11 municipios), utilizando el archivo  sun_2018, columna "tipo_cd", ubicado en: \FOMIX\fmx_insumos\fmx_estadisticas\conapo\insumos\sun_2018;
en donde: 1=zona metropolitana, 2=conurbación y 3=centro urbano.

**Comment by ofegarcia** [comment]
@CorinaCantero 
***Tarea***
Elaborar los siguientes mapas de AGEB para la caracterización socioeconómica:



![image](https://user-images.githubusercontent.com/54822363/83157064-cb200c80-a0c8-11ea-8adb-e303e1e7cc08.png)



**Base de datos: bd_ageb_caract**
- [ ] Población. Campo:	pobt_10, Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Número de campo: 12
- [ ] 	Migración. Campo: ap_reoe05, Población de 5 años y más residente en otra entidad en  junio de 2005. Número de campo: 63
- [ ] 	Población indígena. Campo: ap_5hli, Población de 5 años y más que habla alguna lengua indígena. Número de campo: 64
- [ ] 	Educación. Campo:	ap_15_an, Población de 15 años y más analfabeta. Número de campo: 69
- [ ] 	Salud. Campo:	ap_no_af,	Población sin derechohabiencia a servicios de salud. Número de campo: 81
- [ ] 	Vivienda. Campo: av_cserv, Viviendas particulares habitadas que disponen de luz eléctrica, agua entubada de la red pública y drenaje. Número de campo: 102

**Base de datos: bd_ageb_diag_pobr**	
- [ ] Pobreza. Campo: c_pobr, Categoría del municipio según el porcentaje de población que vive en condición de pobreza. Número de campo: 11
- [ ] Pobreza extrema. Campo: c_pobr_e, Categoría del municipio según el porcentaje de población que vive en condición de pobreza extrema. Número de campo: 12

**Base de datos. bd_ageb_diag_rezago**	
- [ ] Rezago social. Campo: ag_rezs, Grado de rezago social por AGEB urbana. Número de campo: 14

**Comment by CorinaCantero** [comment]
### AVISO
@aleestrada Aquí puedes poner que mapas se necesitan para el subsistema productivo y cuales son los insumos para hacerlos.

**Comment by aleestrada** [comment]
@CorinaCantero 

Realizar los siguietes mapas para la caracterización del sistema productivo:

- [ ] Producto bruto total
- [ ] Inversión
- [ ] Población ocupada
- [ ] Unidades económicas
- [ ] Participación del municipio en la producción del estado
- [ ] Participación del municipio en la inversión del estado
- [ ] Participación del municipio en el total de población ocupada del estado
- [ ] Participación del municipio en el total de unidades económicas del estado

Mapa|Base de datos|Campo|Unidades
---|---|---|---|
Producto bruto total|bd_activ_ec_muni|prod_brut|Millones de pesos
Inversión|bd_activ_ec_muni|inv|Millones de pesos
Población ocupada|bd_activ_ec_muni|per_ocup|Personas
Unidades económicas|bd_activ_ec_muni|ue|
Participación del municipio en la producción del estado|bd_activ_ec_part_edo_muni|p_brut_pe|porcentajes
Participación del municipio en la inversión del estado|bd_activ_ec_part_edo_muni|inv_pe|porcentajes
Participación del municipio en el total de población ocupada del estado|bd_activ_ec_part_edo_muni|per_oc_pe|porcentajes
Participación del municipio en el total de unidades económicas del estado|bd_activ_ec_part_edo_muni|ue_pe|porcentajes

**Comment by CorinaCantero** [comment]
### AVISO

@aleestrada Ya están listos los mapas solicitados en el comentario anterior en la siguiente ruta: 
\SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_productivo\texto

**Comment by CorinaCantero** [comment]
### AVISO

@aleestrada En la carpeta del comentario anterior están los mapas 2.9, 2.10a-2.10c de tenencia de la tierra y cultivos principales.

**Comment by CorinaCantero** [comment]
### AVISO
@ofegarcia Listo el mapa síntesis del subsistema socioeconómico 3_23, en la carpeta SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico\texto

**Comment by aleestrada** [comment]
AVISO

Información para Mapa de Concentración Industrial

Carpeta: FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_productivo

Mapa|Base de Datos|Campo|Unidades|Año|Fuente
---|---|---|---|---|---|
Concentración Industrial| bd_conc_indust.csv|concen_ind|Índice|2015|INEGI

**Comment by CorinaCantero** [comment]
### AVISO
@aleestrada 
Listo el mapa de concentración industrial, en la carpeta: \SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_productivo\texto\2_11

**Comment by aleestrada** [comment]
AVISO
@CorinaCantero 

Información para Mapa de Actividad Principal por Municipio

Carpeta: FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_productivo

Mapa|Base de Datos|Campo|Unidades|Año|Fuente
---|---|---|---|---|---|
Actividad Principal por Municipio| bd_activ_principal.csv|ac_ec_prin|Rama de actividad económica|2014|INEGI

**Comment by CorinaCantero** [comment]
### AVISO
@aleestrada Listo el mapa Actividad económica principal por municipio es el 2_12, por favor verificar que en el informe esté la última versión de los mapas 2.9 a 2.12 porque les hice modificaciones

**Comment by CorinaCantero** [comment]
@ofegarcia 

Trabajar en las bases de datos bd_ageb_caract y bd_ageb_diag_pobr_16jul20 para verificar que tenga los siguientes campos :

Campo | Descripción | Notas |
-- | -- | -- | 
cve_ent | Clave de la entidad | Dos dígitos | 
nom_ent | Nombre de la entidad | Con acentos | 
cve_mun | Clave del municipio | Sin prefijos de ceros | 
nom_mun | Nombre del municipio | Sin acentos y sin prefijos numéricos | 
mun_ori | Nombre del municipio | Con acentos y sin prefijos numéricos | 
id_region | ID región | Números arábigos | 
region | Nombre de la región | Número romano y nombre | 
cvegeo | ID entidad (dos dígitos) + ID municipio (tres dígitos) |   |
cve_loc | Clave de la localidad | Clave de la localidad de AGEB | 
nom_loc | Nombre de la localidad | Nombre de la localidad de AGEB |  
cve_ageb | Clave de la AGEB | Cuatro dígitos | 
fol_ageb | Nombre de la AGEB | entidad+municipio+localidad+ageb |

**Comment by ofegarcia** [comment]
@CorinaCantero , @aaron-ts 
Listas las bases de datos de AGEB de caracterización y pobreza, con los campos solicitados. Tal como se indicó, se encuentran en: FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_socioeconomico\provisionales

Archivos: 
-	bd_ageb_caract_6sep20
-	dd_ageb_caract_6sep20
-	bd_ageb_diagn_pobr_6sep20
-	bd_ageb_ diagn_pobr _6sep20

Solicito indicaciones para sustituir los archivos originales que se modificaron, por esta nueva versión, para que los nuevos queden como la versión final.
