### ISSUE TITLE
Explorar escenarios modelo pronóstico

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#120]
## Procesamiento
\CARPETAS_TRABAJO\apc_temeraria\pronostico\scenario_discovery\

## Resultados
Los resultados de la exploración se ubican en la ruta:
\FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\escenarios

**Comment by iaga** [comment]
## Región 2
@ofegarcia @dpedroza74 La versión actualizada de **tendencial_r2.html** se encuentra en la carpeta \FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\escenarios\r2

**Comment by iaga** [comment]
# Versiones finales de los escenarios

Ruta:
\CARPETAS_TRABAJO\apc_temeraria\pronostico\scenario_discovery\region_x

Región|Tendencial|Contextual|Estratégico
--|--|--|--|
1|tendencial_r1_v1|contextual_r1_v2|estrategico_r1_v1
2|tendencial_r2_v3|contextual_r2_v2|estrategico_r2_v2
3|tendencial_r3_v1|contextual_r3_v1|estrategico_r3_v1
4|tendencial_r4_v1|contextual_r4_v2|estrategico_r4_v1
5|tendencial_r5_v1|contextual_r5_v2|estrategico_r5_v1
6|tendencial_r6_v1_t15|contextual_r6_v1_t15|estrategico_r6_v1_t15
7|tendencial_r7_v1|contextual_r7_v1|estrategico_r7_v1

**Comment by iaga** [comment]
## Actividades:

- [x] Automatizar la salida con el formato requerido para la tabla de criterios
- [x] Correr las regiones faltantes
- [x] Cambiar la gráfica de las coordenadas paralelas
- [x] Revisar los productos finales para todas las regiones

**Comment by iaga** [comment]
## Modificaciones R2

### Modificaciones:
- TUNT->CON->CAN->HUMC
- TUSP->CON->CAN->HUMC
- URB->CON->CAN->HUMC
- URB->CON->CAN->HUMT, quitar RECAR
- RESS (URB, GAN, TUR)
- RESL (URB, GAN, TUR)
- RESP->AIR (POR, AVIC)
- VACUI (RESS/RESL)
- GANI/GANX/ETER/URB/TUNT/TUSP → RESL → VACUI
- GANI/GANX/URB/TUNT/TUSP → RESS → VACUI
- Eliminar: CFOR, CFOR-MMAYA, CANH2O, TUNT-HUMC, TUSP-HUMT

**Comment by TatianaMerino** [comment]
@dpedroza74 @ofegarcia 
Listos los mecanismos de los escenarios de las 7 regiones 
carpeta: FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\escenarios

**Comment by iaga** [comment]
# Generar versiones finales en formato HTML y PDF

Importante: revisar que los indirectos tengan las tablas correctamente.

## Procedimiento para PDF

1.- Insertar saltos de página entre cada exploración
2.- Modificar ÚNICAMENTE los archivos para las páginas cortadas **margen inferior** de 0.6
3.- Imprimir la primera página del archivo con el índice
4.- Generar otro archivo madre para imprimir:
4..1- En el archivo madre: comentar la cabecera de título
4.2.- Incluir el código para numerar secciones (agregar secciones en blanco)
4.3.- Poner en negritas la cabecera
4.4.- \newpage antes del título
5.- Imprimir un PDF con la página 2 y 3 con **margen inferior** de 0.5: knit-1.pdf
6.- Imprimir otro PDF de la página 3 en adelante con **margen inferior** de 0.6: knit-2.pdf
7.- Copiar el índice y el título al archivo índice.html
8.- Generar PDF final que incluya el índice y a todas las regiones

**Configuración de la impresión: **
![imagen](https://user-images.githubusercontent.com/41757755/152652388-c2e5bf0e-e703-408a-a705-c4db15dd0329.png)

### Terminados
- [x] 1. Región 1. Tendencial
- [x] 2. Región 1. Contextual
- [x] 3. Región 1. Estratégico
- [x] 4. Región 2. Tendencial
- [x] 5. Región 2. Contextual
- [x] 6. Región 2. Estratégico
- [x] 7. Región 3. Tendencial
- [x] 8. Región 3. Contextual
- [x] 9. Región 3. Estratégico
- [x] 10. Región 4. Tendencial
- [x] 11. Región 4. Contextual
- [x] 12. Región 4. Estratégico
- [x] 13. Región 5. Tendencial
- [x] 14. Región 5. Contextual
- [x] 15. Región 5. Estratégico
- [x] 16. Región 6. Tendencial
- [x] 17. Región 6. Contextual
- [x] 18. Región 6. Estratégico
- [x] 19. Región 7. Tendencial
- [x] 20. Región 7. Contextual
- [x] 21. Región 7. Estratégico

**Comment by iaga** [comment]
@TatianaMerino favor de indicar los escenarios que hay que generar de nuevo y qué modificaciones se hicieron (de forma general):

- [x] 12. Región 4. Estratégico: se agregó TUSP-DUNA
- [x] 7. Región 3. Tendencial: se agregó RESP-VACUI
- [x] 8. Región 3. Contextual: se agregó RESP-VACUI
- [x] 2. Región 1. Contextual: se eliminó TUNT-RESS-VACUI (sobraba, ya está TUNT-VACUI)
- [x] 13. Región 5. Tendencial: se eliminó TUSP-HUMT
- [x] 15. Región 5. Estratégico: se agregó TUNT-HABT
- [x] 4. Región 2. Tendencial: se eliminó RESS-VACUI, se cambió RESL-VACUI por ETER-VACUI 
- [x] 5. Región 2. Contextual: se eliminó RESS-VACUI, se cambió RESL-VACUI por ETER-VACUI 
- [x] 6. Región 2. Estrategico: se agregó ETER-VACUI


Nota: en R6 falta AGR-MMAYA  y en R2 falta URB-MMAYA y PMINI-AIR porque no se encontraron en estratégico. Se dejarán en tendencial y contextual y en la tabla de resultados en el escenario estratégico se pondrá el cambio de la tasa media en condición final del estratégico con respecto al tendencial.

**Comment by TatianaMerino** [comment]
AVISOS: 
@dpedroza74 
Los html de las regiones ya fueron actualizados en fmx_estudio_tecnico\pronostico\talleres\insumos\escenarios

@ofegarcia 
Los insumos para las tablas de regiones de resultados del pronóstico están en esa misma ruta, en la carpeta de la región correspondiente. Se generará un documento en word de cada tabla en esas carpetas para poner el ID del criterio. 

Tablas listas para agregar ID:  

- [x] r1
- [x] r2
- [x] r3
- [x] r4
- [x] r5
- [x] r6
- [x] r7

**Comment by TatianaMerino** [comment]
@ofegarcia 
Favor de completar la versión corregida de la tabla de la región 1: 
**tabla_informe_r1_v2**

**Comment by TatianaMerino** [comment]
@ofegarcia 
Tablas listas para agregarse al informe 
Favor de poner título y describir el ID

- [x] R1: tabla_informe_r1_final (revisar pesca)
- [x] R2: tabla_informe_r2_final (revisar pesca)
- [x] R3: tabla_informe_r3_final
- [x] R4: tabla_informe_r4_final (revisar pesca)
- [x] R5: tabla_informe_r5_final
- [x] R6: tabla_informe_r6_final
- [x] R7: tabla_informe_r7_final

**Comment by iaga** [comment]
# Salidas para informe
 \CARPETAS_TRABAJO\apc_temeraria\pronostico\scenario_discovery\finales

- **htmls**. Los htmls para todas las regiones numerados del 1 al 21. Incluye un archivo en excel con la cabecera que se incluyó en el índice de la página en línea.
- **escenarios.pdf**. Archivo con la unión de todos los escenarios para todas las regiones y el índice. 
-- Para cada región se generó una carpeta r_x que contiene: 1) El índice para esa región, 2) El primer escenario a imprimir, incluye el título, 3) El resto de los escenarios
-- El índice se realizó por medio del archivo **indice.Rmd**, contiene una copia del índice para cada escenario con la numeración correspondiente

**Comment by iaga** [comment]
# Descripción general del código

- Existe un archivo madre para cada escenario, para cada región: tendencial_rx, contextual_rx, estrategico_rx. Este archivo sirve para generar el html de cada región. En él se incluye el nombre de cada exploración.
- El archivo madre genera un archivo de salida que resume los cambios para las variables de interés
- Cada exploración puede ser para dos (forzante, estado) o tres variables (forzante, estado, repercusión). Cada caso contiene: 
  - La dinámica promedio en el tiempo, 
  - La tabla con los parámetros que se utilizaron para generar el árbol de clasificación, 
  - El árbol, 
  - Él o los casos seleccionados para ese árbol particular, 
  - Las coordenadas paralelas de los casos, 
  - Los boxplots
  - La tabla final que resume los cambios respecto a la condición inicial y final para las variables de interés
- Es necesario que cada carpeta contenga:
   - El archivo madre. Contiene la cabecera con los parámetros del Rmarkdown, el título, etc.
   -  Los "childs" para cada exploración: ejemplo, agr_cfor.Rmd. Cada uno de estos NO debe contener la cabecera típica de un archivo Rmarkdown y no puede correr de forma independiente.
  - Los archivos: 
        - **functions_code.R** Contiene la lista de paquetes y todas las funciones para el código,
        - **config_ini.R** La definición de las variables de repercusión, la ruta donde se lee el archivo de entrada y el diccionario
        - **config_ini_part2.R** Prepara los bancos de datos para los cálculos estadísticos y el árbol 
        - **preparar_tabla.R** Calcula las probabilidades y genera las etiquetas necesarias para la tabla final
        - **desplegar_tabla.R** Código para desplegar la tabla en función del número de parámetros
        - **doc.css** este archivo es necesario para que se puedan poner en paralelo las coordenadas paralelas,
        - **diccionario_abrev.csv** definición en texto de las abreviaturas de los sectores, 
        - **parametros.csv** los parámetros que definen el valor umbral
- Para compilar, es necesario compilar el archivo madre

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
