### ISSUE TITLE
Integrar segunda entrega CONACYT

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/fomix#121]
Los archivos de la segunda entrega se colocan  en la siguiente ruta:

FOMIX/fmx_estudio_tecnico/entregas/segunda_entrega

Enlace a la página del informe: https://lancisapc.wixsite.com/fomixpoety

**Índice de la segunda entrega**

**1.	Estudio técnico para la actualización del POETY**

> -  Etapa de diagnóstico 

- > Análisis de aptitud

> - Documento **(Concluido y ya en la página)**

> - En línea **(Concluido y ya en la página)**

- > Análisis de conflictos

> - Documento **(Concluido y ya en la página)**

> - En línea **(Concluido y ya en la página)**

- > Análisis de interacciones sectoriales **(Responsable @iaga, nombre del archivo: redes.pdf)**

> - Documento 

> - En línea 

- > Áreas a proteger, preservar, conservar o restaurar **(Responsable @paola-gp , nombre del archivo: areas_conservar.pdf)**

> - Etapa de pronóstico 

> - Documento **(Responsable @dpedroza74 , nombre del archivo: pronostico.pdf)**

- > Escenarios **(Responsable @iaga, en documento y en línea, nombre del archivo: escenarios.pdf)**

> - Documento **(Concluido y ya en la página)**

> - En línea

- > Talleres **(Concluido en línea y ya en la página)**

- > Escenarios **(Responsable @iaga, en documento y en línea, nombre del archivo: escenarios.pdf)**

> - Etapa de propuesta 

- > Documento **(Nombre del archivo: propuesta_poety.pdf)**

- > Catálogo de estrategias ecológicas **(Nombre del archivo: catalogo_estrategias.pdf)**

- > Catálogo de criterios de regulación ecológica **(Nombre del archivo: catalogo_criterios.pdf)**

- > Fichas de las UGA **(Nombre del archivo: fichas_uga.pdf)**

- Geoportales

- > Visualizador de capas (lizmap) **(Concluido y ya en la página)**

- > Portal de metadatos **(Concluido y ya en la página)**

**2.	Anexos del estudio técnico** **(Anteponer la palabra "anexo_" a cada archivo, el nombre del producto (escenarios, pronóstico, etc., y numeración consecutiva)**
Ejemplos: 
anexo_areas_conservar_1, anexo_areas_conservar_2
anexo_pronostico_1
anexo_escenarios_1

**3.	Sistema desarrollado e implementado**

- Programa de planeación colaborativa

- Informe **(Nombre del archivo: programa_pc.pdf)** **(Concluido y ya en la página)**

- Liga al servidor de prueba **(Concluido y ya en la página)**

- Manuales de uso **(Nombre del archivo: manual_uso_sistema.pdf)**

**Informe de avance financiero**
(Dropbox con carpetas)

**Comment by Nayita** [comment]
### Actividades

- Favor de ponerse como responsables si no aparecen previamente en el índice
- Poner sus archivos finales en la ruta:FOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\pdf 
- Sustituir sus archivos en esa carpeta. Ya existen unos archivos dummy con los nombres asignados
- Poner sus anexos en la ruta: \FOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\anexos
- Ponerse en contacto con @Nayita si tienen duda o quieren cambiar nombres de archivos y anexos

**Comment by iaga** [comment]
@Nayita el archivo pdf con la salida de los escenarios se ubicó en la ruta indicada. Ya está todo integrado, lo único que hace falta es la portada (no tengo idea qué numeración le toca). ¿Podrías indicarme dónde coloco los htmls asociados?

**Comment by Nayita** [comment]
@iaga 

Ninguno de los productos lleva numeración como puedes ver en el índice, solamente se le pondrá el título.

Necesito consultar la ubicación de los htmls asociados. En cuanto lo sepa, te lo informo.

**Comment by iaga** [comment]
@Nayita se actualizó el archivo PDF de escenarios con la portada sin numeración, favor de confirmar que no hay ningún error en la portada.

**Comment by Nayita** [comment]
@iaga 

Lista la carpeta "insumos" para que coloques htmls, archivo md, e imágenes del archivo de análisis de interacciones sectoriales.

Ruta: FOMIX\fmx_estudio_tecnico\entregas\segunda_entrega

**Comment by Nayita** [comment]
@iaga 

Ya actualicé el índice y puse el nombre que le corresponde al archivo de Análisis de interacciones sectoriales. Favor de verificar.

**Comment by iaga** [comment]
@Nayita 

1) Listos los htmls, se ubicaron en la carpeta: "htmls_escenarios". Están numerados del 1 al 21, para que se suban en ese orden. El título de cada liga está en el archivo headers.xlsx incluido en la carpeta.
2) Correcto el título y nombre de archivo verificado.

**Comment by dpedroza74** [comment]
@Nayita 
Ya subí a la carpeta FOMIX/fmx_estudio_tecnico/entregas/segunda_entrega el documento del Programa de Planeación Colaborativa (programa_plan_colab) que forma parte del producto 3. Sistema desarrollado e implementado

**Comment by dpedroza74** [comment]
@Nayita 

El producto **Anexos del estudio técnico** no son los anexos de las demás secciones, sino que es un informe que se va a llamar así "Anexos del estudio técnico" y 4 anexos separados. 
En la carpeta FOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\anexos te estoy poniendo estoy poniendo esos anexos separados
El anexo 8.2 son las listas de los talleres, que te pido que por favor las juntes en un sólo pdf.
El anexo 8.2 son minutas que te pido que por favor las juntes en un sólo pdf, acomodadas por fechas
Los anexos 8.4 y 8.5 son archivos de Excel

Aún no termino el informe "Anexos del estudio técnico" pero puedes ir subiendo esos anexos

**Comment by dpedroza74** [comment]
@Nayita 

Puedes por favor cambiar los títulos de la etapa de pronóstico en la página de entrega 

**Etapa de pronóstico**
Informe
Anexo escenarios (el pdf que entregó Ileana)

En línea
- Talleres 
- Escenarios

**Comment by iaga** [comment]
@Nayita listos los insumos para el informe de redes (md, html y figuras). Sólo es necesario actualizar la liga de las figuras, se supone que las tablas deben leerse sin ningún problema, por si acaso, puse el documento en word por si necesitas poner las tabla como figura.

**Comment by TatianaMerino** [comment]
@Nayita listos los anexos de pronóstico de modelación. Por la longitud, se separó el anexo en 7 por regiones. 
anexo_pronostico_ksim_region_1 (1 a 7)

**Comment by dpedroza74** [comment]
@Nayita 
Ya está el informe de pronóstico para subirlo a la página de entrega
**informe_pron** en la carpetaFOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\word

Tiene ahí un problema en el índice que no me pone los puntos suspensivos con el número de página. No sé si tú le sabes arreglar eso.

**Comment by dpedroza74** [comment]
@Nayita
Ya está el informe del producto Anexos del estudio técnico para subirlo a la página de entrega
informe_anexos_estudio_tecnico en la carpetaFOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\word

**Comment by dpedroza74** [comment]
@Nayita 
En la carpeta carpetaFOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\word subí el informe del sistema **informe_sistema**
Necesito que cuando lo pases a pdf le insertes al final del documento los dos oficios de entrega que puse en la carpeta FOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\pdf\sistema_oficios

Aún nos faltaría el oficio de la última entrega que se hace el lunes. Una vez que tengamos ese, también te pediré que lo anexes al pdf del informe y ya ese completo lo subes a la página de entrega.

**Comment by dpedroza74** [comment]
@Nayita 
En la carpeta carpetaFOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\word subí el informe del sistema informe_propuesta
para subirlo a la página

**Comment by dpedroza74** [comment]
@Nayita 
Ya no vamos a anexar los oficios que te había pedido que anexaras al pdf del informe del sistema. Entonces,  en el archivo informe_sistema que está en la  carpeta FOMIX\fmx_estudio_tecnico\entregas\segunda_entrega\word le quité la referencia de que íbamos a anexar los oficios de entrega. Por lo tanto, así como está está listo para subirlo a la página de entrega

**Comment by paola-gp** [comment]
### Actualización de página de entrega

@Nayita 

- Se sustituyeron los archivos del manual de uso del sistema, las appc en la carpeta .pdf con los productos a entregar (el segundo está también agregado en /word, para el primero solo hay pdf

- [x] Agregar contraseña a la página
- [x] Agregar enlace del entregable **Repositorio de capas geográficas** a la carpeta: /ENTREGAS/poety
- [x] Agregar enlace del informe financiero ya agregado a la carpeta correspondiente

En la sección 3: Sistema desarrollado e implementado
- [x] Cambiar el nombre de "Manuales de uso" a "Manual de usuario"
- [x] Quitar elemento **Página principal** 
- [x] Cambiar el nombre de **Servidor de prueba** a **Servidor de pruebas del sistema**  y poner el enlace: http://poety-dev.sigplanning.com.mx
- [x] Agregar los geoportales dentro de la sección  3

Segunda parte
- [x] Eliminar elemento **Fichas de las UGA** 
En la sección de etapa de propuesta  agregar con base en carpeta: /entregas/segunda_entrega/csv_sistema

- [x] Asignación de lineamientos por UGA  (bd_lineamiento.csv)
- [x] Asignación de criterios por UGA (bd_criterios_uga.csv) Nota: esperar confirmación del archivo con @dpedroza74 
- [x] Asignación de estrategias por UGA (bd_estrategias_uga.csv)
- [x] Catálogo de criterios (bd_catalogo_criterios.csv)
- [x] Catálogo de estrategias (bd_catalogo_estrategias.csv)
- [x] Indicadores por UGA (bd_indicadores_uga.csv)  NOTA: no usar este archivo para el sistema hasta que se corrija el problema de nombres de campos  @vichdzgeo 

Tercera parte

- [x] Actualizar el elemento **En línea** de **Análisis de interacciones sectoriales** con la liga correcta

**Comment by dpedroza74** [comment]
@Nayita ya están en la carpeta de csv todos los archivos completos

**Comment by paola-gp** [comment]
@Nayita 

### Entrega en físico
- [x] Crear carpeta para descarga y entrega en físico del estudio ténico en /descarga

- [x] Organizar por carpetas los entregables con base en la siguiente estructura y copiar los entregables a las carpetas y subcarpetas 

Carpeta: Estudio_Tecnico_Diagnostico
Subcarpeta: Analisis_Aptitud (2 archivos)
Subcarpeta: Analisis_Conflictos (2 archivos, agregar el de interacciones sectoriales)
Subcarpeta: Areas_Prioritarias (1 archivo)
Carpeta: Estudio_Tecnico_Pronostico (9 archivos)
Carpeta: Estudio_Tecnico_Propuesta (7 archivos)
Carpeta: Anexos_Estudio_Tecnico (5 archivos)
Carpeta: Sistema_Desarrollado (3 archivos)

- [x] Verificar que sean los archivos correctos de todo lo que se debe entregar en pdf y csv (porque quedaron algunos repetidos o en formatos que no se van a entregar, p. ej. informe_oficios está duplicado, catalogo_estrategias.pdf catalogo_criterios.pdf). Esto es, se debe poder descargar la entrega completa con excepción de los informes en línea (sphinx), capas geográficas y portales (geonetwork, lizmap y sistema de conocimiento)

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
