### ISSUE TITLE
Integrar repositorio de bases de datos (shape, txt y figuras) del modelo de ordenamiento  #poety #propuesta #ET #sistema

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#122]
### Versión del 11 de febrero 2022:  
FOMIX/fmx_sistema_conocimiento/modelo_poety_11_feb 

- [x] Mapa en formato shapefile de UGA con _id_uga_ y _clave_uga_  con el nombre poety_uga_11feb22.shp con metadato @vichdzgeo 
- [x] Figuras formato fig-clave_uga-general.png & fig-clave-uga-zoom.png en carpeta /figuras_uga @vichdzgeo 
- [x] bd_indicadores_basicos.txt  @vichdzgeo   _Dejar provisionalmente los nombres de los campos del piloto con los datos que se puedan llenar._ 

nombre_campo | titulo_ficha
-- | --
id_uga |  
clave_uga |  
nombre |  
superficie | Extensión (km²):
selva_p | Selva (%):
manglar_p | Manglar (%):
urbano_p | Urbano (%):
hum_t_n | Número de humedales terrestres:
hum_t_p | Humedales terrestres (%):
ram_p | Sitio Ramsar:
hum_cos_p | Humedales costeros (%):
cal_parc_p | Calidad de parche de cobertura forestal (%):
parche_n | Número de parches de cobertura forestal prioritarios:
integridad_p | Integridad ecológica:
riqueza_p | Riqueza de especies:
biomasa_p | Biomasa árbórea (%):
apc_p | Áreas prioritarias para la conservación (%):
recarga_i | Índice de recarga al acuífero:
vul_acu_i | Índice de vulnerabilidad del acuífero:
sus_ladera_p | Susceptibilidad por inestabilidad de laderas (%):
sus_hundimiento_p | Susceptibilidad a hundimientos (%):
sus_incendio_p | Susceptibilidad a incendios forestales (%):
pel_inunda_p | Riesgo por inundaciones pluviales (%):
ries_ciclones_p | Riesgo por ciclones tropicales (%):
vul_cc_p | Vulnerabilidad de asentamientos humanos a inundaciones por cambio climático (%):

- [x] bd_uga_grupo.txt  @vichdzgeo 
- [x] bd_grupo_sector.txt @vichdzgeo 
- [x] bd_sectores.txt @vichdzgeo 

- [x] bd_lineamiento.txt
- [x] bd_catalogo_criterios.txt
- [x] bd_catalogo_estrategias.txt
- [x] bd_criterios_uga.txt
- [x] bd_estrategias_uga

Requisitos de la base de datos:

- Un archivo en formato .txt separado por tabuladores por cada elemento de la base de datos
- Formato utf8
- Nombre del archivo como aparece en la lista 
- No cambiar, agregar o quitar campos
- Todas las bases de datos que tienen id_uga no puede tener campos vacíos (excepto bd_criterios_uga y bd_estrategias_uga)

[bases_datos_sistema.xlsx](https://github.com/lancis-apc/fomix/files/8052348/bases_datos_sistema.xlsx)

**Comment by vichdzgeo** [comment]
## Relación de ugas con actividades

[bd_sectores_bd_grupo_sector.xlsx](https://github.com/lancis-apc/fomix/files/8052392/bd_sectores_bd_grupo_sector.xlsx)

@TatianaMerino @iaga 

NOTA: Se agrega a bd_sectores el id 17 como Área natural protegida

**Comment by dpedroza74** [comment]
> [](https://github.com/lancis-apc/fomix/files/8052348/bases_datos_sistema.xlsx)

@paola-gp en las bd hay una columna que se llama clave_uga, qué se pone ahí?

**Comment by vichdzgeo** [comment]
## Aviso

### archivo shape de UGA
- Se agrego el campo titulo_uga
- se actualiza los archivos de la carpeta modelo_poety_11_feb\uga y el archivo uga.zip

## Bases de datos 
- Se elimina el archivo bd_indicadores_basicos.txt
- Se verifican el nombre y tipo de datos a partir del archivo modelo_poety_11_feb/diccionario_datos_indicadores.csv
- Se actualizan los datos de apr_p 
- Se actualiza el archivo modelo_poety_11_feb/txt/bd_indicadores_basicos_v2.txt
- se genera el archivo txt diccionario_datos_indicadores.txt

@paola-gp

**Comment by dpedroza74** [comment]
@paola-gp y @vichdzgeo 
Ya subí las bases de datos con los id de criterios y estrategias corregidos (para que queden id de 4 caracteres )y con los prefijos corregidos, para que por favor me apoyen con la verificación y la conversión a  formato .txt separado por tabuladores por cada elemento de la base de datos - utf8
bd_lineamiento
bd_catalogo_criterios
bd_catalogo_estrategias
bd_criterios_uga
bd_estrategias_uga
a la carpeta FOMIX\fmx_sistema_conocimiento\modelo_poety_11_feb\excel

**Comment by vichdzgeo** [comment]
@paola-gp 

listas las bases de datos en txt

- bd_lineamiento
- bd_catalogo_criterios
- bd_catalogo_estrategias
- bd_criterios_uga
- bd_estrategias_uga

ya fueron sustituidas en el directorio:

FOMIX\fmx_sistema_conocimiento\modelo_poety_11_feb\txt

**Comment by vichdzgeo** [comment]
@paola-gp 

Listas las bases de datos en txt, figuras de UGA y shapefile

NOTA: la base de datos  **bd_grupo_sector.txt** en _id_uga_ : 158 en el campo _lista_id_sector_prio_ esta vacío (ya que esta sujeta a las regulaciones que tiene la Federación por ser humedal costero).

**Comment by vichdzgeo** [comment]
@paola-gp listo la actualización del archivo bd_grupo_sector.txt para la versión del 12 de abril
