### ISSUE TITLE
Graficar la salida promedio en el tiempo de los escenarios de pronóstico

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#123]
## Descripción:

A partir de la salida del modelo, se generaron scripts en R para presentar la salida promedio en el tiempo en los talleres de pronóstico

Características:

- Permite seleccionar las variables a graficar
- Muestra la trayectoria promedio de todas las variables seleccionadas
- Para cada variable, corta en subconjuntos el intervalo de simulación

## Importante
Únicamente es necesario modificar los parámetros en la cabecera del script

params:
  p_esc: e1
  p_sector: URB
  p_nombre_taller: Urbano
  p_time: !r c('0', '5', '10', '15', '20', '25')
  p_vars: !r c('URB','TMAYA', 'CFOR', 'VACUI', 'VHUR', 'GEI', 'GANX', 'PMEGA', 'AGR', 'BMAT', 'TUSP', 'TUNT', 'PESCA', 'ACUA')
  p_conf_level: 0.95

## Ejemplo con la salida del script:

![imagen](https://user-images.githubusercontent.com/41757755/154124085-6685f0a6-bbb3-4ce7-b456-f1e4541db072.png)

![imagen](https://user-images.githubusercontent.com/41757755/154124200-ca6c1b20-af85-4f97-8284-01dc77ad8b85.png)

**Comment by iaga** [comment]
## Lista con los scripts finales

**Ruta:**
\FOMIX\fmx_estudio_tecnico\pronostico\talleres\insumos\ksim\escenarios

Taller|Salidas
--|--
Agricultura|\agr\e9_agr\e9_agr.html
Pecuario bovino|\bov\e2_bov\e2_bov.html
Cambio climático|clima\e1_clima\e1_clima.html
Energía|ener\e2_ener\e2_ener.html
Pecuario porcino y avícola|por_avi\e2_por_avi\e2_por_avi.html
Turismo de sol y playa|tur_sol_playa\e3_tur_sol_playa.html
Urbano e Industrial|urb\e1_urb\e1_urb.html

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
