### ISSUE TITLE
Describir las UGA por sectores y estrategia de conservación #propuesta #FOMIX

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/fomix#126]
Descripción de los principales resultados del análisis de aptitud sectorial y la zonificación del estado en UGA

- [x] Imágenes de UGA con áreas de conservación y restauración @vichdzgeo 
- [x] Bases de datos @vichdzgeo 
- [x] Documento (html o pdf) con imágenes de UGA, gráficas de residuales y promedios @TatianaMerino 
- [x] Resumen de los resultados que describen por sector la aptitud en las UGA @TatianaMerino y @ofegarcia

**Comment by TatianaMerino** [comment]
## Insumos
Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\descripcion

- **explicacion_ugas_v3.docx**: Borrador de descripción 
- **bd_sectores_ugas_aptitud_conficto.xlsx**: Áreas de aptitud A y MA con conflicto en áreas prioritarias por sector en UGAs seleccionadas por el modelo de optimización #125 

Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\asignacion_ugas\v6
- **gr_residuales_promedios.Rmd**: script para generar el documento con gráficas e imágenes #105

**Comment by TatianaMerino** [comment]
@vichdzgeo 
Favor de generar:
- una base de datos (una completa o una por sector) con todas las UGA que sea la cruza de UGA-aptitud del sector-áreas prioritarias
- mapa de appcr actualizado #84

**Comment by TatianaMerino** [comment]
## Aptitud sectorial para propuesta
que se corrió en el modelo de optimización

Sector | restricciones | aprovechamiento actual | escenario
-- | -- | -- | --
agricultura | vulnerabilidad del acuífero alta y muy alta, y localidades | unidades y distritros de riego; agricultura de temporal y de riego | CLP
apicultura |   |   | CLP
conservación | las   localidades |   | CLP
energía |   |   | CLP
forestal |   |   | CLP
industrial |   |   | CLP
milpa maya |   |   | CLP
minería | vulnerabilidad del acuífero alta y muy alta |   | CLP
bovino |   |   | CLP
porcino y avícola | vulnerabilidad del acuífero alta y muy alta |   | OWA restrictivo
pesca | las UGA establecidas en el POETCY |   | OWA restrictivo
turismo naturaleza |   |   | CLP
turismo de sol y playa |   |   | CLP
urbano | las localidades |   | CLP

**Comment by TatianaMerino** [comment]
## Descripción de UGA por estrategia de conservación y aptitud sectorial
Ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\descripcion

- Análisis de datos y generación de redacción de aptitud sectorial: **descripcion_aptitud_opt_28mar22.xlsx** 
- Borrador más reciente: explicacion_ugas_v6.docx
 @paola-gp @ofegarcia

**Comment by TatianaMerino** [comment]
## Actualización

@ofegarcia @paola-gp 

La descripción de las UGA  por estrategia de consevación y sectores ya está actualizada en el informe de propuesta **informe_propuesta_v_abril** en FOMIX\fmx_estudio_tecnico\propuesta\informe abril

Nota: **Falta describir el criterio de preponderancia de la estrategia de conservación y revisar dónde se dejará la descripción sectorial.**

**Comment by vichdzgeo** [comment]
## Figuras de UGA

ruta: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\ugas\figuras\zoom\finales

@TatianaMerino

**Comment by TatianaMerino** [comment]
## Figuras 

- Exploración de residuales de Gower y promedios de aptitud 
Ruta: fmx_estudio_tecnico/propuesta/analisis_ugas/asignacion_ugas/v6/gr_residuales_promedios
- Gráficas en informe de propuesta
Ruta: fmx_estudio_tecnico/propuesta/analisis_grupos/gr_informe
