### ISSUE TITLE
Integrar tercera entrega CONACYT

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/fomix#127]
Los archivos de la tercera entrega se colocan en la siguiente ruta:

FOMIX/fmx_estudio_tecnico/entregas/tercera_entrega

La estructura de carpetas es exactamente igual que la de la segunda entrega.

**Comment by dpedroza74** [comment]
Este es el índice de los informes finales del estudio técnico que acordamos ayer y los faltantes

**1. Etapa de Caracterización**
  1.1 Subsistema natural
  1.2 Subsistema productivo
  1.3 Subsistema socioeconómico

1.4 Anexos de la etapa de Caracterización
1.4.1 Subsistema natural
  1.4.1.1 Métodos
  1.4.1.2 Documentación
1.4.2 Subsistema productivo
  1.4.2.1 Métodos
  1.4 .2.2 Documentación
1.4.3 Subsistema económico
  1.4.3.1 Métodos

- [x] Verificar con Luis si se van a quitar secciones y si se incluye un párrafo de introducción y se integran todos los archivos en un solo documento (informe y anexos) @paola-gp y @dpedroza74 
- [x] Cambiar numeración en los anexos y sus referencias en subsistema socioecon @ofegarcia  
- [x] Cambiar numeración en los anexos y sus referencias en subsistema natural @Nayita 
- [x] Cambiar numeración en los anexos y sus referencias en subsistema productivo @dpedroza

**2. Etapa de Diagnóstico**
  **2.1 Análisis de aptitud** 
    2.1.1 Introducción
    2.1.2 Talleres para el análisis de aptitud sectorial 
    2.1.3 Referencias
    2.1.4 Resultados
- [x] Correcciones en el documento en secciones 2.1.1 y 2.1.2 @dpedroza74 
- [x] Correcciones en mapas en la sección 2.1.4 @Nayita @vichdzgeo 

  **2.2 Análisis de conflictos ambientales**
    2.2.1 Descripción de conflictos y ubicación de áreas potenciales de conflictos
    2.2.2 Análisis de redes
- [x] Revisar con Luis nombre de las secciones y juntar todo en un documento @dpedroza74 
- [x] Meter la matriz de conflictos completa y volver a meter los resultados de la descripción de conflictos @Nayita 

  **2.3 Áreas prioritarias para la conservación y la restauración**
    2.3.1 Índice para definir las áreas prioritarias para la conservación
      2.3.1.2Modelo de decisión
      ....
    2.3.2 Índice para definir las áreas prioritarias para la restauración
      ....
- [x] Terminar informe, cambiando la numeración @paola-gp @vichdzgeo 

  **2.4 Indicadores ambientales**
    2.4.1 Riesgo
.....
- [x] Terminar el informe @paola-gp @vichdzgeo 

**2.5 Anexos de la etapa de Diagnóstico**
  2.5.1 Análisis de aptitud
    2.5.1.1Modelación multicriterio
    2.5.1.2 Proceso Analítico Jerárquico (AHP)
   ...
  2.5.2 Áreas prioritarias para la conservación y la restauración
    2.5.2.1 Clasificación de las clases de uso de suelo y vegetación
    2.5.2.1 Análisis de calidad de parches de cobertura natural
   ...
- [x] Cambio en la numeración y revisión del anexo de análisis de aptitud 2.5.1@dpedroza74 
- [x] Renumeración del anexo de la sección 2.5.2 áreas prioritarias para la conservación @paola-gp 
- [x] integrar todo en un sólo documento de anexos @paola-gp @dpedroza74 

3 **Etapa de Pronóstico**
  3.1 Bases teóricas y metodológicas
    ....
  3.2 Talleres
        3.3 Resultados
..
  3.4 Escenarios
 ...
  3.5 Referencias

  **3.6 Anexos de la etapa de Pronóstico**

    3.6.1 Datos de referencia para el establecimiento de valores iniciales
    3.6.2 Datos de referencia para el escenario tendencial
    3.6.3 Datos de referencia para el escenario contextual
    3.6.4 Modelos KSIM
    3.6.5 Escenarios

- [x] Hacer introducción de anexos
- [x] Hacer un párrafo de introducción de lo que hay en los pdf de modelos KSIM y escenarios @TatianaMerino  
- [x] Hacer zip de las secciones 3.7.4 y 3.7.5 @Nayita 

**4. Etapa de propuesta**
  4.1Antecedentes
   4.1.1
  ...
  4.2 Modelo 
  4.3 Mapa de las unidades de gestión ambiental
  4.4 Catálogo de estrategias ecológicas
  4.5 Catálogo de criterios de regulación ecológica
  4.6 Fichas de unidades de gestión ambiental

- [x] Cambiar índice, integrando las secciones acordadas con Luis el lunes @daniela @TatianaMerino @paola-gp 
- [x] Hacer mapa de UGA tamaño carta @paola-gp @vichdzgeo 
- [x] Incluir mapas de aptitud modificados en el sistema @vichdzgeo 
- [x] Terminar bases de datos para integrar fichas @dpedroza74 @vichdzgeo 

**5. Documentación de mecanismos de participación**
- [x] cambiar índice, quitar minutas y referencias a anexos @dpedroza74 
- [x] incluir listas de asistencia @dpedroza74 


@Nayita 
- [x] Cambiar las numeraciones de todas las carátulas
- [x] Incluir en la carátula de caracterización la aclaración que tiene actualmente sobre la fecha de entrega (8 de julio de 2020)
- [x] Incluir en todas las demás carátulas la fecha marzo 2022

**Comment by dpedroza74** [comment]
@Nayita y @paola-gp 

Ya puse en la carpeta FOMIX\fmx_estudio_tecnico\diagnostico (afuera de las carpetas)
los informes que tenemos que trabajar para la última entrega en formato de word de
- analisis_aptitud
- analisis_conflictos
- anexos_diagnostico

@paola-gp en el de anexos_diagnostico es donde tendrías que incluir los anexos de lo que generaron para identificar las Áreas prioritarias para la conservación y la restauración (me refiero a Clasificación de las clases de uso de suelo y vegetación, Análisis de calidad de parches de cobertura natural, etc.)

@Nayita en el archivo analisis_conflictos ya incluí lo del análisis de redes de Ileana y faltaría que ahí metieras lo de la  Matriz de conflictos (2.2.2) que vimos ayer que estaba cortada y en la sección que le llamé _2.2.3 Descripción de conflictos y ubicación de áreas potenciales de conflictos entre pares de sectores incompatibles_ incluir los resultados que están en línea

**Comment by TatianaMerino** [comment]
@dpedroza74
 
El informe de pronóstico corregido para la última entrega es **informe_pron_abril**, y se encuentra en 
FOMIX\fmx_estudio_tecnico\pronostico\informe

**Comment by dpedroza74** [comment]
@Nayita 
Puse en la carpeta \FOMIX\fmx_estudio_tecnico\anexos
los 4 documentos para la sección **5. Documentación de mecanismos de participación** del informe:
documentacion_participa (word)
anexo_asistencia_talleres (pdf) 
anexo_formul_validacion_aptitud (Excel)
anexo_formul_conflictos (Excel)

Una vez que el documento de word tenga su carátula lista y se tenga la versión en pdf, te pido que le anexes el anexo de listas de asistencia. Las bases de datos de los dos formularios en Excel quedarán por separado

**Comment by dpedroza74** [comment]
@Nayita 
Ya está en la carpeta FOMIX\fmx_estudio_tecnico\pronostico los 3 documentos para la sección de Pronóstico
**3 Etapa de Pronóstico** y **3.6 Anexos de la etapa de Pronóstico**

informe_pronostico (word)
anexos_pronostico (word)
anexos_pronostico_3_6_4_y_5 (zip)

**Comment by dpedroza74** [comment]
@Nayita 
¿Nos podrías decir dónde están los archivos en word de la caracterización (informe y anexos por subsistema) para que podamos hacer los cambios para esta entrega, por favor?

**Comment by paola-gp** [comment]
@Nayita @dpedroza74 

Mi opinión sobre lo que se debe eliminar del primer informe:
### subsistema natural
- [x] 3.1.2.7 Uso potencial del territorio
- [x] 3.1.3.2 Vulnerabilidad costera a ciclones tropicales e inundaciones
### Subsistema productivo
- [x] Análisis de redes de las relaciones entre los sectores de actividad económica (solo después de la tabla 3.2.1
- [x] Tabla 3.2.20 y el texto que le precede (que cita la tabla)
- [x] Sección 3.2.4.3 
- [x] Todas las tablas de **insumos para el análisis de aptitud del sector X** y el texto que lo cita en la sección 3.2.5 (para que no haya confusión sobre los atributos que salieron de los talleres??)

**Comment by Nayita** [comment]
### AVISO

Ruta de los informes y anexos de caracterización por subsistema: FOMIX/fmx_estudio_tecnico/caracterizacion_subs/procesamiento

**Comment by dpedroza74** [comment]
@Nayita 
Ya está en la carpeta FOMIX\fmx_estudio_tecnico\caracterizacion_subs
informe_carac_subs_productivo
informe_carac_subs_socioec
y
anexos_caracterizacion
- [x] en este archivo de anexos falta que por favor hagas la descripción de las bases de datos del subsistema natural

También subí una carpeta bases_datos_carac en la que están todas las bases de datos
- [x] para que por favor la hagas un archivo zip

Por favor cuando termines las modificaciones del informe del subsistema natural nos avisas a Paola y a mí para que hagamos la revisión ya integrada

**Comment by Nayita** [comment]
@paola-gp 

Revisar archivos del subsistema natural para vo. bo. 
Ruta: FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural
Archivo: subsistema_natural_1_1
Ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs
Archivo: anexos_caracterizacion

**Comment by Nayita** [comment]
@paola-gp @dpedroza74 

De acuerdo al índice de informes finales faltan los siguientes archivos para concluir la entrega:

2.4 Indicadores ambientales
4.2 Modelo
4.3 Mapa de las unidades de gestión ambiental
4.4 Catálogo de estrategias ecológicas
4.5 Catálogo de criterios de regulación ecológica
4.6 Fichas de unidades de gestión ambiental

Los demás documentos ya están listos de acuerdo a lo solicitado.

**Comment by dpedroza74** [comment]
@paola-gp 

Ya subí a la carpeta FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\txt las bases de datos en formato txt separado por tabulaciones UTF8
bd_catalogo_criterios
bd_catalogo_estrategias
bd_criterios_uga
bd_estrategias_uga
bd_lineamiento

**Comment by paola-gp** [comment]
> @paola-gp
> 
> Ya subí a la carpeta FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\txt las bases de datos en formato txt separado por tabulaciones UTF8 bd_catalogo_criterios bd_catalogo_estrategias bd_criterios_uga bd_estrategias_uga bd_lineamiento

@vichdzgeo: verificas los archivos con el programita que hiciste?

**Comment by vichdzgeo** [comment]
El proceso que tiene excel no esta respetando la codificación UTF8 a pesar de que indicaste que la codificación sea UTF8 el archivo txt tiene codificación ANSI 

Por otra parte, los archivos txt tienen columnas sin nombre, esto también es problema de excel

Dado estos problemas, @dpedroza74  ¿podrías colocar los archivos de las bases de datos en formato excel en la carpeta arpeta FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\excel\

Ya con el código verifico y me encargo de transformar a txt.

**Comment by dpedroza74** [comment]
@vichdzgeo ya subí las bases de datos en Excel.

**Comment by vichdzgeo** [comment]
## Informe de indicadores

He terminado de agregar las figuras de los indicadores al documento.

Cualquier observación o modificación, estoy al pendiente. 

Ruta: Dropbox (LANCIS)\FOMIX\fmx_estudio_tecnico\diagnostico\indicadores
- informe_indicadores.docx

@paola-gp @Nayita

**Comment by vichdzgeo** [comment]
@paola-gp ¿parches prioritarios entra en el informe de indicadores?

**Comment by vichdzgeo** [comment]
@Nayita @paola-gp se actualiza la ruta del informe

**Comment by TatianaMerino** [comment]
## AVISO
@dpedroza74 @Nayita 
Listas las gráficas de promedios y residuales de los grupos de aptitud en el informe de propuesta.

**Comment by Nayita** [comment]
### AVISO

@dpedroza74 @paola-gp 

Listos los informes que faltaban para terminar la entrega. Favor de revisar.

Ruta: \FOMIX\fmx_estudio_tecnico\entregas\tercera_entrega

Quedo pendiente de cualquier corrección

**Comment by dpedroza74** [comment]
@Nayita 
Podrías cambiar en el informe de subsistema natural el nombre del índice, porque dice índice de capítulo y los demás informes sólo dice índice

**Comment by dpedroza74** [comment]
@Nayita 
Puse en un archivo zip los dos archivos de excel que están en  la carpeta FOMIX\fmx_estudio_tecnico\entregas\tercera_entrega\anexos y lo puse en la carpeta de zip

**Comment by dpedroza74** [comment]
> @Nayita Podrías cambiar en el informe de subsistema natural el nombre del índice, porque dice índice de capítulo y los demás informes sólo dice índice

ya lo hice yo

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
