### ISSUE TITLE
Preparar informe de propuesta #fomix #et #propuesta

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#128]
/FOMIX/fmx_estudio_tecnico/propuesta

@TatianaMerino @dpedroza74: favor de documentar que contienen los distintos archivos .docx que tienen en la carpeta y armar en este issue en el índice de como quedarían incorporados en un solo documento

**Comment by dpedroza74** [comment]
@paola-gp 
Para no tener confusión puse una carpeta \FOMIX\fmx_estudio_tecnico\propuesta\informe_febrero
en la que está el informe (un sólo documento de word) que se entregó en febrero y las bases de datos.

**Comment by dpedroza74** [comment]
@paola-gp @TatianaMerino @vichdzgeo  
Puse una carpeta \FOMIX\fmx_estudio_tecnico\propuesta\informe abril en el incluí el documento de word del informe informe_propuesta_v_abril en el que hice los cambios en el índice y señalo con amarillo dónde hace falta incluir los temas que definimos hoy en la reunión.

**Comment by TatianaMerino** [comment]
## AVISO
@dpedroza74 
Listas las gráficas de promedios y residuales de los grupos de aptitud en el informe de propuesta. 

### Insumos
FOMIX\fmx_estudio_tecnico\propuesta\analisis_grupos\gr_informe

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
