### ISSUE TITLE
Preparar faltantes para entrega final estudio técnico

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#129]

**Comment by paola-gp** [comment]
### Crear una cuarta entrega que incluya todo y lo que ya se entregó en la entrega tres con las siguientes actualización:

\FOMIX\fmx_estudio_tecnico\entregas\cuarta_entrega

- [x] propuesta_informe_v_abril @TatianaMerino 
- [x] informe_analisis_aptitud @Nayita 
- [x] anexos_diagnostico @dpedroza74 

- Mapa de aptitud de agricultura tecnificada que sirvió de insumo para el modelo de ordenamiento (título mapa)
- Mapa de aptitud insumo para el modelo de ordenamiento (titulo sección Sphinx)
- Justificación (agregar a metadatos)
- Mapa

**Además agregar:**

Última versión: \fmx_sistema_conocimiento\modelo_poety_jun

### Bases de datos POETY **bd_poety**
- [x] Bases de datos txt de la última versión del poety `FOMIX\fmx_sistema_conocimiento\modelo_poety_jun\txt`
- [x] Mapa de UGA con metadatos
- [x] Zip de figuras de UGA
### bd_capas_locales
ruta: `FOMIX\fmx_sistema_conocimiento\modelo_poety_jun\shp`

- [x] capas de indicadores locales (capas locales) 
- [x] TXT y excel de capas de indicadores locales `bd_capas_locales_indicadores.txt y bd_capas_locales_indicadores.xlsx`
- [x] ZIP de imágenes de mapas locales  `figuras_leyendas.zip`
### bd_capas_wms
ruta `C:\Dropbox (LANCIS)\FOMIX\fmx_sistema_conocimiento\modelo_poety_jun\wms`
- [x] TXT y excel de wms `bd_wms_figuras_v_poety_abr.txt y bd_wms_figuras_v_poety_abr.xlsx`
- [x] ZIP de imágenes wms `figuras/wms_figuras_leyendas.zip`


Sistema de conocimiento
- Documento de explicación del sistema
- [x] Manuales (pedir la última versión de instalación)

**Proyectos QGIS** 
Ruta: `C:\Dropbox (LANCIS)\ENTREGAS\proyectos_qgis_sds`

Base de datos de geonetwork `bd_metadatos_poety.csv`

- [x] Proyecto QGIS y carpetas de caracterización `caracterizacion.zip`
- [x] Proyecto QGIS y carpetas de insumos diagnóstico `proyectos_qgis_poety.zip`
- [x] Proyecto QGIS y carpetas de análisis de aptitud `proyectos_qgis_poety.zip`
- [x] Proyecto QGIS y carpetas de APPCR `proyectos_qgis_poety.zip`
- [x] Proyecto QGIS y carpetas de indicadores  `ugas_indicadores.zip`

**Comment by vichdzgeo** [comment]
## Mapas de aptitud para el modelo de ordenamiento

ruta: sig_fomix\entregables\lizmap_segunda_entrega\categorizados_informe

- conservacion_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/4df8dfb0-7799-4cea-b78d-10e048dc8750)
- mineria_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/29979247-ff22-41b5-97bf-6704789e5160) 
- agricultura_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/00aac099-bd59-4040-8927-b71626ac5433)
- urbano_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/26da80c3-36f9-4ddb-a6e8-23422a1136c9) 
- pesca_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/a63992b3-6de2-4c3d-bd54-9505b8ea2846)
- porcino_avicola_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/1d02b627-2b60-4140-a8a3-1f722044b757)

@Nayita  

NOTA: URBANO solo lleva cuatro categorias

**Comment by dpedroza74** [comment]
@Nayita 
Ya quedó el documento de word **anexos_diagnostico** en la carpeta FOMIX\fmx_estudio_tecnico\diagnostico
el cual ya contiene el anexo metodológico de OWA
Para que por favor sustituyas el archivo de la última entrega por este en la entrega final

**Comment by dpedroza74** [comment]
@Nayita 
En la carpeta FOMIX\fmx_estudio_tecnico\diagnostico subí el documento en word **texto_capas_moe** con el texto que hay que poner en la sección Sphinx y en el informe de análisis de aptitud, bajo el título **Mapa de aptitud insumo para el modelo de ordenamiento** que se va a adicionar para los sectores Minería, Pecuario porcino y avícola, Pesca y Urbano. 

En el documento de word está el texto para todos los sectores.

**Comment by vichdzgeo** [comment]
## Aviso

@Nayita 
- ya estan los metadatos de los mapas de aptitud en geonetwork, favor de verificar y corregir lo que creas conveniente, ademas de agregar la figura y el texto de la justificación
- El mapa de urbano_moe cuenta ya con una paleta de color para que se carguen las 4 categorías.

**Comment by Nayita** [comment]
@dpedroza74 

Falta la justificación para el sector conservación. Favor de agregar al documento.

**Comment by dpedroza74** [comment]
> @dpedroza74
> 
> Falta la justificación para el sector conservación. Favor de agregar al documento.

Según yo no hubo cambios en el mapa de aptitud para conservación. 
@vichdzgeo puedes confirmar?

**Comment by Nayita** [comment]
@dpedroza74 

Víctor lo puso en este comentario para que hiciera los mapas:

> ## Mapas de aptitud para el modelo de ordenamiento
> ruta: sig_fomix\entregables\lizmap_segunda_entrega\categorizados_informe
> 
> * conservacion_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/4df8dfb0-7799-4cea-b78d-10e048dc8750)
> * mineria_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/29979247-ff22-41b5-97bf-6704789e5160)
> * agricultura_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/00aac099-bd59-4040-8927-b71626ac5433)
> * urbano_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/26da80c3-36f9-4ddb-a6e8-23422a1136c9)
> * pesca_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/a63992b3-6de2-4c3d-bd54-9505b8ea2846)
> * porcino_avicola_moe.tif -> [Metadato](http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/1d02b627-2b60-4140-a8a3-1f722044b757)
> 
> @Nayita
> 
> NOTA: URBANO solo lleva cuatro categorias

**Comment by vichdzgeo** [comment]
@dpedroza74 @Nayita 

El mapa de conservación que se ingreso para el modelo de ordenamiento no incluye las ANP como aprovechamiento actual. considero que es importante mostrar el mapa que se utilizó. 

Sin embargo el motivo de utilizar el mapa de conservación sin ANP: 
- Las ANP ya están destinadas a conservación, por lo tanto si estas áreas estaban presentes en el mapa, restarían importancia a otras áreas del estado que tuviesen aptitud de conservación según el modelo de decisión.

@dpedroza74  consideras que requerimos una justificación explicita en el informe para esta decisión? si es así cual sería?

**Comment by dpedroza74** [comment]
> @dpedroza74 @Nayita
> 
> El mapa de conservación que se ingreso para el modelo de ordenamiento no incluye las ANP como aprovechamiento actual. considero que es importante mostrar el mapa que se utilizó.
> 
> Sin embargo el motivo de utilizar el mapa de conservación sin ANP:
> 
> * Las ANP ya están destinadas a conservación, por lo tanto si estas áreas estaban presentes en el mapa, restarían importancia a otras áreas del estado que tuviesen aptitud de conservación según el modelo de decisión.
> 
> @dpedroza74 consideras que requerimos una justificación explicita en el informe para esta decisión? si es así cual sería?

@paola-gp 
Yo creo que no es necesario incluir este mapa en la sección del análisis de aptitud, porque de por sí en el modelo se explica que se están separando las ANP como UGA independientes. Pero no sé si tú quedaste con @vichdzgeo que sí se incluya además eso en la sección de aptitud

**Comment by vichdzgeo** [comment]
## Reglas de txt

@paola-gp he colocado el archivo reglas_txt.xlsx en  FOMIX\fmx_sistema_conocimiento con las reglas específicas para cada TXT

**Comment by vichdzgeo** [comment]
## Manuales

Ruta:\FOMIX\fmx_sistema_conocimiento\manuales

- Generar estilos para capas vectoriales (estilos.md)
- Exportar capa vectorial con codificación UTF-8 en Qgis (exportar_capa_utf8.md)
- Convertir una capa vectorial multipoligono a polígonos individuales (single_parts.md)

@Nayita podrías revisar de favor someramente los manuales y ver si las indicaciones se comprenden. existe una versión en PDF de cada uno de ellos para su fácil lectura.

**Comment by TatianaMerino** [comment]
## Informe propuesta 
@Nayita 

Las modificaciones al informe de propuesta se hicieron en el word de la cuarta entrega: 
FOMIX\fmx_estudio_tecnico\entregas\cuarta_entrega\word

**Comment by Nayita** [comment]
@vichdzgeo 

Revisados los manuales. Las indicaciones se comprenden bastante bien. Hay errores de dedo y de ortografía que hay que corregir y sugiero que todas las palabras en inglés las pongas en cursivas, y no solamente algunas, aun cuando ya estén en negritas.

Si requieres que haga estas correcciones en los archivos md, avísame y las hago

**Comment by Nayita** [comment]
@vichdzgeo 

- [x] publicar el informe de aptitud en el shpinx para que se actualicen en la página web

**Comment by Nayita** [comment]
@vichdzgeo 

Listas las correcciones de los manuales en los archivos md y hechos los pdfs respectivos.

**Comment by dpedroza74** [comment]
@Nayita 
Para la entrega final subí el informe de propuesta con correcciones en la carpeta FOMIX\fmx_estudio_tecnico\propuesta\informe junio

**Comment by dpedroza74** [comment]
@vichdzgeo @paola-gp 

Conforme lo acordado con Luis y Paola puse todos los criterios que aplican a algún sector en todas las UGA.

Vic, subí en la carpeta \FOMIX\fmx_sistema_conocimiento\modelo_poety_jun\excel la nueva base de datos de asignación de criterios a UGA. Me podrías ayudar a pasarlo a .txt delimitado por tabuladores / UTF-8 para subirlo al sistema por favor?

**Comment by vichdzgeo** [comment]
@dpedroza74 

el archivo a sido convertido y sustituido

FOMIX\fmx_sistema_conocimiento\modelo_poety_12_abr\bd_criterios_ugas.txt

**Comment by paola-gp** [comment]
@vichdzgeo 
No sustituir en el proyecto 12_abr para mantener esa versión intacta. Poner todo lo nuevo en la versión de junio como lo reportó Daniela.

**Comment by vichdzgeo** [comment]
@paola-gp @dpedroza74 

- [x]  Se ha restaurado el archivo bd_criterios_ugas.txt de la versión12_abr

- [x] Lista la una copia de los archivos faltantes a modelo_poety_jun/txt para tener una versión completa (Se renombran los archivos conforme a lo índicado en la guía rápida de carga)
- [x] Lista la copia de modelo_poety_jun/uga y sus figuras en modelo_poety_jun/figuras_uga
- [x] Lista la copia de indicadores en formato shapefile en modelo_poety_jun/shp 

- [ ] Se crea una copia de la versión de wms de 12_abr, aún no se actualiza con las capas de la última entrega. en espera de la revisión

**Comment by dpedroza74** [comment]
@vichdzgeo cc. @paola-gp 

Informo que hice cambio en la nomenclatura del ID de los criterios de calidad del aire para que no se confundiera la "I" se cambió de **CI** y **CR**
Vic por favor podrías volver a pasar las dos bases de datos  a formato .txt que están en  la carpeta \FOMIX\fmx_sistema_conocimiento\modelo_poety_jun\excel
son la base de datos del catálogo de criterios y la de asignación de criterios a UGA

**Comment by paola-gp** [comment]
@dpedroza74 

Ya están las tres versiones finales de los manuales de **guia_admon_geovisualizador**, **guia_geovisualizador** y **guia_carga_bd_programa** en word y pdf (optimizado para consulta) tanto en \fmx_sistema_conocimiento\proyecto_sistema\manuales\versiones finales
como en la carpeta de capacitación a la que tienen acceso la SDS para hacer pruebas.

**Comment by vichdzgeo** [comment]
### Aviso

@dpedroza74 @paola-gp 
Los archivos bd_criterio_uga.txt y bd_catalogo_criterios.txt han sido actualizados.

**Comment by dpedroza74** [comment]
@paola-gp 
Ya están en la carpeta \FOMIX\fmx_sistema_conocimiento\proyecto_sistema\manuales\versiones finales las versiones finales de 
**manual_usuario_sistema_poety** y **guia_monitoreo_poety**

**Comment by dpedroza74** [comment]
@Nayita 
Se ajustaron fórmulas en el informe de propuesta, la última versión está en 
FOMIX\fmx_estudio_tecnico\propuesta\informe junio

**Comment by dpedroza74** [comment]
@Nayita 

Armé una carpeta en FOMIX\fmx_sistema_conocimiento\proyecto_sistema\material bitacora en la que incluí un word con textos y carpetas con figuras y dpf que se publican en la bitácora ambiental, para que por favor también la pongas en el disco de entrega, por favor.

**Comment by Nayita** [comment]
### AVISO

Listo el disco duro externo que se entregará al gobierno de Yucatán con toda la información correspondiente a la cuarta entrega. En espera de indicaciones de etiqueta o lo que se requiera para concretar la entrega.

**Comment by Nayita** [comment]
La actividad se ha concluido. El disco duro se guarda hasta nuevo aviso de acuerdo a indicaciones de Luis. Por lo pronto se cierra el issue.
