### ISSUE TITLE
Realizar diagnóstico de subsistema productivo

### ISSUE THREAD

**Issue by aleestrada** [lancis-apc/fomix#13]
Carpeta de trabajo
\CARPETAS_TRABAJO\aestrada\FOMIX

Productos

- [x] Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad.
- [x] Matriz de la estructura económica de la entidad por periodos de análisis
- [x] Matriz de coeficientes de especialización económica
- [x] Matriz de tamaño de establecimientos industriales por rama de actividad económica
- [x] Matriz de ritmo de crecimiento de la inversión por rama y municipio
- [x] Base de datos del diagnóstico del subsistema productivo
- [ ] Elaboración de informe
- [x] Bases de datos

**Comment by aleestrada** [comment]
Se realizó la busqueda de la información necesaria para poder realizar el análisis, de tal forma que se tienen las siguientes bases de datos:

Se encuentran en la carpeta:

\CARPETAS_TRABAJO\aestrada\FOMIX\insumos

- PIB del estado de Yucatan por tipo de actividad económica a precios constantes del 2013 (2003-2018)
- Censo económico para el estado de Yucatán 2014
- Matriz de insumo - producto del estado de Yucatán

###

**Comment by milocortes** [comment]
#### Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad.

Se generaron dos productos (.csv) con el siguiente contenido:

* `yuc_porcentajes_act_ec_muni.csv`, se presenta la participación de cada rama de actividad en el total municipal para todas las variables del censo económico para los años 2004 2009 y 2013.
* `yuc_porcentajes_muni.csv`, se presenta la participación de cada municipio para el total del estado de Yucatán para todas las variables del censo económico para los años 2004 2009 y 2013.

Los productos, así como es script que los produjo, se encuentran en la ruta `\CARPETAS_TRABAJO\hcortes\fomix`. 

La carpeta `fomix` tiene la siguiente estructura:

```
.
├── data
│   └── yucatan_ce_09-14.csv
├── output
│   ├── yuc_porcentajes_act_ec_muni.csv
│   └── yuc_porcentajes_muni.csv
└── scripts
    └── yuc_censos.R

```

**Comment by aleestrada** [comment]
#### Acuerdos de la reunión

Derivado de la reunión del día 23 de marzo de 2020, se llegaron a los siguientes acuerdos.

@milocortes estará encargado de realizar los insumos para los productos:

-  Matriz de tamaño de establecimientos industriales por rama de actividad económica
-  Matriz de ritmo de crecimiento de la inversión por rama y municipio

@aleestrada estará encargada de:

- Análisis de la matriz de insumo - producto
- Redacción del informe

**Comment by aleestrada** [comment]
### Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad

El análisis se divide en dos partes, de acuerdo a la disponibilidad de datos:

- Parte estatal: Se realiza con datos del Producto Interno Bruto (PIB) del estado de Yucatán a precios constantes del 2013, para el periodo 2003 -2018. Los datos se desagregan a nivel sectorial en los sectores: primario (I), secundario (II) y terciario (III). 
- Parte municipal: Dado que no existen datos del PIB a nivel municipal, ni desagregados a nivel de rama, se utilizan datos de la producción ruta total (que puede ser usado como equivalente del PIB) por municipio a nivel sector y rama de actividad ecónomica.

#### Insumos
-  Producto Interno Bruto (PIB) del estado de Yucatán a precios constantes del 2013, para el periodo 2003 -2018.
Ruta: 
\CARPETAS_TRABAJO\aestrada\FOMIX\insumos\pib_yucatan.csv

- Censos económicos 2004, 2009, 2014
Ruta:
\CARPETAS_TRABAJO\hcortes\fomix\data\yucatan_ce_09-14.csv


#### Producto
**- PIB estatal**
Base de datos:
\FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_productivo\pib_yucatan.csv

Tableau:
 \CARPETAS_TRABAJO\aestrada\FOMIX\tableau\pib.twb

**- Porcentaje de participación de cada una de las ramas en el total estatal de las variables analizadas**
Base de datos:
\FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_productivo\bd_sectorial_activ_part_muni.csv

Tableau:
 \CARPETAS_TRABAJO\aestrada\FOMIX\tableau\tableau_act_econ.twb

**- Partcipación del municipio en el total estatal de cada una de las variables analizadas** 
Base de datos:
\FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_productivo\bd_sectorial_part_activ_econ.csv

Tableau: 
\CARPETAS_TRABAJO\aestrada\FOMIX\tableau\part_municipio.twb

**Comment by aleestrada** [comment]
### Matriz de la estructura económica de la entidad por periodos de análisis

Para esta parte de la caracterización se utiliza la **matriz de insumo - producto** del estado de Yucatán, además de la información obtenida en el **Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad**.

#### Insumos

Matriz de insumo - producto a nivel sector para el 2008:
\CARPETAS_TRABAJO\aestrada\FOMIX\insumos\MIP_Estatales_t_pb_pxp_2008.xlsx

#### Análisis

La matriz de insumo producto refleja las relaciones económicas que se llevan a cabo entre los diferentes sectores y permite el análisis de los vínculos productivos al interior de una economía.

A partir del enfoque insumo-producto es posible analizar en detalle el proceso de producción
en cuanto al requerimiento de insumos (productos) de un sector, desde otros a nivel nacional, o
internacional (en el caso de los insumos intermedios importados).

**Comment by aleestrada** [comment]
### Matriz de coeficientes de especialización económica

#### Insumos:
Censos económicos 2004, 2009, 2014
Ruta:
\CARPETAS_TRABAJO\hcortes\fomix\data\yucatan_ce_09-14.csv

#### Procesamiento

Para el cálculo de los coeficientes de especialización se siguio a (Dávila, 2004) y CEDRUS y se utilizó la siguiente fórmula:

IEE = (v_ij/sum_j (v_ij))/((sum_i (v_ij))/sum_i sum_j v_ij)

Representa la relación entre la participación del sector “i” en la región “j” y la participación del mismo sector en el total nacional/regional.

**Comment by aleestrada** [comment]
### Matriz de tamaño de establecimientos industriales por rama de actividad económica

El cálculo de esta matriz estuvo a cargo de @milocortes 

#### Insumos
Censos económicos 2004, 2009, 2014
Ruta:
\CARPETAS_TRABAJO\hcortes\fomix\data\yucatan_ce_09-14.csv

#### Procesamiento
@milocortes

**Comment by aleestrada** [comment]
#### Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad.

Se generaron cinco productos (.csv) con el siguiente contenido:

| Archivo   |     Descripción      |  Año | Fuente|
|----------|:-------------:|------:|------:|
|```yuc_porcentajes_act_ec_muni.csv```|Participación de cada rama de actividad en el total municipal para todas las variables del censo económico|2004,2009,2014|INEGI|
|```yuc_porcentajes_muni.csv```| Participación de cada municipio para el total del estado de Yucatán para todas las variables del censo económico| 2004,2009,2014|INEGI|
| ```mat_tc_muni.csv```|   Matriz de ritmo de crecimiento de la inversión por municipio  |   2009,2014 |INEGI |
| ```mat_tc_rama.csv ```| Matriz de ritmo de crecimiento de la inversión por rama  |   2009,2014 | INEGI|
| ```denue_yuc_rama_wide.csv``` |Matriz de tamaño de establecimientos industriales por rama de actividad económica   | 2015 | INEGI |

Los datos así como los scripts que generaron  los productos ```yuc_porcentajes_act_ec_muni.csv```,```yuc_porcentajes_muni.csv```, ```mat_tc_muni.csv``` y ```mat_tc_rama.csv ```,  se encuentran en la ruta ```\CARPETAS_TRABAJO\hcortes\fomix```

La carpeta ```fomix``` tiene la siguiente estructura:
```
.
├── data
│   ├── nombre_variables.txt
│   ├── regiones_yuc.csv
│   └── yucatan_ce_09-14.csv
├── output
│   ├── mat_tc_muni.csv
│   ├── mat_tc_rama.csv
│   ├── yuc_porcentajes_act_ec_muni.csv
│   └── yuc_porcentajes_muni.csv
└── scripts
    ├── yuc_censos.R
    └── yuc_regiones.R
```

Por su parte, los datos así como los scripts que generaron el producto  ```denue_yuc_rama_wide.csv```, se encuentra en la ruta  ```\CARPETAS_TRABAJO\hcortes\denue```.

La carpeta ```denue``` tiene la siguiente estructura:

```
.
├── data
│   └── 2015
│       ├── DENUE_INEGI_11_.csv
│       ├── DENUE_INEGI_21_.csv
│       ├── DENUE_INEGI_22_.csv
│       ├── DENUE_INEGI_23_.csv
│       ├── DENUE_INEGI_31-33_.csv
│       ├── DENUE_INEGI_43_.csv
│       ├── DENUE_INEGI_46111_.csv
│       ├── DENUE_INEGI_46112-46311_.csv
│       ├── DENUE_INEGI_46321-46531_.csv
│       ├── DENUE_INEGI_46591-46911_.csv
│       ├── DENUE_INEGI_48-49_.csv
│       ├── DENUE_INEGI_51_.csv
│       ├── DENUE_INEGI_52_.csv
│       ├── DENUE_INEGI_53_.csv
│       ├── DENUE_INEGI_54_.csv
│       ├── DENUE_INEGI_55_.csv
│       ├── DENUE_INEGI_56_.csv
│       ├── DENUE_INEGI_61_.csv
│       ├── DENUE_INEGI_62_.csv
│       ├── DENUE_INEGI_71_.csv
│       ├── DENUE_INEGI_72_.csv
│       ├── DENUE_INEGI_81_.csv
│       ├── DENUE_INEGI_93_.csv
│       └── files.txt
├── output
│   ├── denue_yuc_rama.csv
│   └── denue_yuc_rama_wide.csv
└── script
    └── DENUE_datos.R
```

**Comment by milocortes** [comment]
### Matriz de ritmo de crecimiento de la inversión por rama y municipio

#### Insumos 

Censos económicos 2004, 2009, 2014. INEGI

Ruta: ```\CARPETAS_TRABAJO\hcortes\fomix\data```

Archivos:
```.
├── data
│   ├── nombre_variables.txt
│   ├── regiones_yuc.csv
│   └── yucatan_ce_09-14.csv
```

#### Procesamiento

Se calculó la tasa de crecimiento media anual de la inversión para cada rama de actividad ecónomica así como para cada municipio. Se presenta la fórmula para su cálculo.

![CodeCogsEqn](https://user-images.githubusercontent.com/20075516/79894233-c29e2d00-83ca-11ea-9c13-1ea70d27ba1c.png)

Donde :
* **VF** es el valor final (o actual).
* **VI** es el valor inicial.
* **N** es la cantidad de periodos entre ambos valores. En nuestro caso, este valor es igual a 5 pues es la cantidad de años entre cada levantamiento del censo. 

#### Productos

Ruta: ```\CARPETAS_TRABAJO\hcortes\fomix\output``

Archivos:

``` 
├── output
│   ├── mat_tc_muni.csv
│   ├── mat_tc_rama.csv
```

Donde: 
*  ```mat_tc_muni.csv``` es la **Matriz de ritmo de crecimiento de la inversión por municipio**
*  ```mat_tc_rama.csv``` es la **Matriz de ritmo de crecimiento de la inversión por rama**

**Comment by aleestrada** [comment]
@milocortes es necesario generar los dicccionarios de datos dd de las bases que generaste de acuerdo a lo establecido en el issue #19 

En la carpeta sub_productivo ya existen algunos dd que te puedes servir de guía

**Comment by aleestrada** [comment]
### Matriz de coeficientes técnicos de estructura ecónomica

Esta matriz está relacionada con la matriz de la esctructura económica del estado de Yucatán.



#### Insumos

Matriz de insumo - producto a nivel sector para el 2008:
\CARPETAS_TRABAJO\aestrada\FOMIX\insumos\MIP_Estatales_t_pb_pxp_2008.xlsx

#### Análisis

La matriz de insumo producto refleja las relaciones económicas que se llevan a cabo entre los diferentes sectores y permite el análisis de los vínculos productivos al interior de una economía.

A partir del enfoque insumo-producto es posible analizar en detalle el proceso de producción
en cuanto al requerimiento de insumos (productos) de un sector, desde otros a nivel nacional, o
internacional (en el caso de los insumos intermedios importados).

**Comment by aleestrada** [comment]
## Informe

#### Anexo metodológico

- [x] Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad.
- [x] Matriz de la estructura económica de la entidad por periodos de análisis
- [x] Matriz de coeficientes de especialización económica
- [x] Matriz de tamaño de establecimientos industriales por rama de actividad económica
- [x] Matriz de ritmo de crecimiento de la inversión por rama y municipio
- [x] Base de datos del diagnóstico del subsistema productivo


#### Bases de datos

- [x] Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad.
- [x] Matriz de la estructura económica de la entidad por periodos de análisis
- [x] Matriz de coeficientes de especialización económica
- [x] Matriz de tamaño de establecimientos industriales por rama de actividad económica
- [x] Matriz de ritmo de crecimiento de la inversión por rama y municipio
- [x] Base de datos del diagnóstico del subsistema productivo

#### Informe

- [x] Análisis de tamaño, importancia y composición de la estructura productiva estatal, municipal, de los sectores primario, secundario y terciario, por sector y rama de actividad.
- [x] Matriz de la estructura económica de la entidad por periodos de análisis
- [x] Matriz de coeficientes de especialización económica
- [x] Matriz de tamaño de establecimientos industriales por rama de actividad económica
- [x] Matriz de ritmo de crecimiento de la inversión por rama y municipio
- [x] Base de datos del diagnóstico del subsistema productivo
