### ISSUE TITLE
Redactar caracterización socioeconómica de Yucatán #fomix

### ISSUE THREAD

**Issue by ofegarcia** [lancis-apc/fomix#16]
Meta: Describir las condiciones socio-demográficas por municipio y región que tienen influencia sobre el patrón de ocupación territorial a escala de AGEB (área geoestadística básica), municipal y regional estatal. En cada escala se generarán indicadores de población total, crecimiento poblacional, población económicamente activa, marginación, ingresos, distribución de la población por actividad económica, migración. Se analizará la distribución espacial de la población (localidades urbanas, rurales y aisladas, asentamientos regulares e irregulares, sistema de ciudades, lugares centrales y regiones de alta marginación) y condiciones (infraestructura, equipamiento y servicios básicos). En cuanto a la vulnerabilidad, se caracterizarán los aspectos sociales y culturales que contribuyen a identificar cuantitativa y cualitativamente a la población en condiciones de rezago, pobreza y marginación

Productos:
Texto que contenga la caracterización y análisis que incluya:
- [x] Distribución de los asentamientos humanos,
- [x] Dinámica demográfica, 
- [x] Condiciones de vida de la población por tipo de asentamiento, 
- [x] Servicios de la vivienda, 
- [x] Dotación de infraestructura,
- [x] Equipamientos y servicios urbanos, 
- [x] Características culturales e identificación de los territorios de los grupos indígenas,
- [x] Identificación de los lugares centrales, accesibilidad de los asentamientos. 

Gráficas y bases de datos de 
- [x] Tasa de crecimiento por municipio, 
- [ ] Tasa global de fecundidad por municipio, 
- [ ] Tasas de mortalidad infantil por municipio, 
- [ ] Tasa de crecimiento social por municipio; 

Mapas. 
 [ ] Grado de marginación por municipio, 
 [ ] Flujo migratorio, 
 [ ] Presencia indígena por municipio,
 [ ] Inmigración municipal, 
 [ ] Estrato de ingreso de la población, 
 [ ] Población ocupada por sector, 
 [ ] Áreas de concentración, 
 [ ] Municipios según grado de dispersión, 
 [ ] Distribución de las localidades según rango-tamaño, carreteras¸ lugares, localidades, 
 [ ] Síntesis del diagnóstico; 

Base de datos:
 [ ] Ingreso y ocupación, 
 [ ] Características de la vivienda, 
 [ ] Cobertura escolar y eficiencia terminal, 
 [ ] Salud

 [ ] Diagnóstico del subsistema social
 [ ] Edad y sexo, por grupos quinquenales de edad; 
 [ ] Gráfica de Lorenz sobre concentración y dispersión de los asentamientos humanos.

**Comment by ofegarcia** [comment]
Los avances de la caracterización socioeconómica se encuentran en los siguientes sitios:

Documento de texto: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs
archivo: fomix_caract_socioecon_5mzo_20

Bases de datos: \FOMIX\fmx_insumos\fmx_estadisticas
archivos: 
- bd_ageb_ogr
- bd_municipios_ogr
- bd_regiones_ogr

**Comment by CorinaCantero** [comment]
**Mapas subsistema socioeconómico**

Los mapas para el subsistema socioeconómico se ubican en: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico\texto

En la carpeta SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico, se encuentra el archivo bd_mapas_socioeconomico, que contiene una relación entre los mapas solicitados en los términos de referencia del proyecto, la clave y el nombre del mapa

**Comment by CorinaCantero** [comment]
**Mapas subsistema socioeconómico**
@ofegarcia 

Los mapas para el subsistema socioeconómico se ubican en: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico\texto

En la carpeta SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico, se encuentra el archivo "bd_mapas_socioeconomico", que contiene una relación entre los mapas solicitados en los términos de referencia del proyecto, la clave y el nombre del mapa.

**Comment by ofegarcia** [comment]
*Pendientes para completar el informe de caracterización socioeconómica*

Cambios en el texto
•	 Incluir figuras y redacción de gráficas de cajas y bigotes 
•	 Incluir información de asentamientos irregulares que proporcione la SDS
•	 Cambiar las numeraciones de los títulos y subtítulos según el índice que se defina 
•	 Revisar numeración de tablas y figuras
•	 Revisar citas 
•	 Incluir mapas de AGEB y su descripción 
•	 Incluir mapas de territorios indígenas, flujo migratorio, migración Mex-EUA y su descripción
•	  Calcular índice de Gini 

Redacción de anexos metodológicos:
•	  Método para calcular la tasa de crecimiento medio anual 
•	  Método para elaborar gráfica de Lorenz 
•	  Método para calcular el índice de Gini
Mapas faltantes:
•	  Mapa de municipios @CorinaCantero
•	  Mapa de territorios indígenas @CorinaCantero
•	  Mapas de AGEB @CorinaCantero
•	  Mapa de migración México – Estados Unidos @CorinaCantero  
•	  Mapa síntesis del subsistema socioeconómico

**Comment by ofegarcia** [comment]
*Pendientes para completar el informe de caracterización socioeconómica*

Cambios en el texto
[ ] Sustituir figuras corregidas (mapas asociados a gráficas de Tableau) 
[ ]  Incluir mapa y descripción de síntesis 

Mapa faltante:
[ ]  Mapa síntesis del subsistema socioeconómico
