### ISSUE TITLE
Generar análisis FODA #FOMIX

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#17]
La propuesta especifica:
Meta 1.1.1. Análisis FODA
Como parte de la planeación estratégica, la primera etapa de la PBC, se implementará el análisis FODA (fortalezas, oportunidades, debilidades y riesgos) para distinguir las cuestiones prioritarias entre la amplia gama de retos y circunstancias que envuelven la gestión del POETY. El análisis FODA se dirigirá a la evaluación de medios de gobernanza, capacidad para la elaboración de estudios técnicos, recursos humanos, financiamiento, infraestructura física, equipamiento e infraestructura de cómputo, procedimientos de manejo de información, procedimientos administrativos y mecanismos de vinculación intersectorial. El análisis FODA se aplicará en talleres y reuniones de trabajo con funcionarios de SEDUMA, así como en grupos focales con miembros del Comité de Ordenamiento Ecológico del OETY y de la Comisión Técnica de Seguimiento y Evaluación del OETY.
Respecto a los factores internos en la gestión del POETY, se determinarán tanto las capacidades instaladas (es decir, las fortalezas) como las limitaciones (es decir, las debilidades) que conciernen la gestión del POETY. Se hará énfasis en los procedimientos de vinculación entre el POETY y otros instrumentos de planeación ambiental y territorial.
Respecto a los factores externos en la gestión del POETY, se examinarán el Plan Estatal de Desarrollo, el Programa Especial de Acción ante el Cambio Climático del Estado de Yucatán Plan, y los planes sectoriales (oportunidades), así como las tendencias de desarrollo social y económico, el crecimiento urbano y la vulnerabilidad al cambio climático (amenazas).
En particular, será importante analizar la coordinación que existe con la Secretaría Técnica de Planeación y Evaluación (SEPLAN), el Consejo de Planeación y Evaluación del Estado de Yucatán (COPLEDEY) y el Sistema de Información Estadística y Geográfica del Estado de Yucatán (SIEGY) con el ordenamiento ecológico. Asimismo, se analizará la operación del Comité de Ordenamiento Ecológico del OETY y de la Comisión Técnica de Seguimiento y Evaluación del OETY.
La matriz FODA incluirá el conjunto de cursos de acción conforme a cuatro tipos de estrategias: maximizar las fortalezas y las oportunidades, minimizar las debilidades aprovechando las oportunidades, maximizar las fortalezas para minimizar las amenazas, y minimizar las debilidades evitando las amenazas.
Con esta base, se enlistarán los recursos técnicos, materiales y humanos con los que cuentan los sectores para participar en el proceso de ordenamiento ecológico.

Los documentos generados se encuentran en : FOMIX\fmx_diagnostico_institucional\foda

**Comment by dpedroza74** [comment]
Se preparó una presentación: foda_6nov19.pptx y una referencia de los factores internos y externos: taller_foda_6nov2019.docx para iniciar la sesión. 

Se subió a la carpeta la lista de asistencia, los audios y las fotos de los rotafolios de la reunión. 

La última versión del reporte que sigue trabajándose es: fmx_reporte_foda_ 6_8nov2019_v10mar20.docx

Las versiones anteriores del reporte se pusieron en la carpeta de auxiliares

**Comment by ofegarcia** [comment]
Pendientes identificados para atender requerimientos específicos establecidos en la propuesta
- [ ] Incluir en la sección de factores externos los programas sectoriales: 1) Gobierno abierto, eficiente y con finanzas sanas y 2) Ciudades y comunidades sostenibles
- [ ] Incluir en la sección de factores externos el Programa regional (VII regiones)
- [ ] Valorar si se requiere mayor información para atender las tendencias: "Respecto a los factores externos en la gestión del POETY, se examinarán el Plan Estatal de Desarrollo, el Programa Especial de Acción ante el Cambio Climático del Estado de Yucatán y los planes sectoriales (oportunidades), así como las tendencias de desarrollo social y económico, el crecimiento urbano y la vulnerabilidad al cambio climático (amenazas).
- [ ] Definir cómo atender el requerimiento de enlistar los recursos de los sectores: "Con esta base (Análisis FODA), se enlistarán los recursos técnicos, materiales y humanos con los que cuentan los sectores para participar en el proceso de ordenamiento ecológico."

Los documentos generados se encuentran en : /FOMIX/fmx_diag_insti/foda
