### ISSUE TITLE
Compilar banco de datos documental en Mendeley #FOMIX

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#2]
### INSTRUCCIONES

1. Ubicación de repositorio de Mendeley: /FOMIX/fmx_insumos/fmx_mendeley
2. Ubicar los insumos (provenientes de las fuentes oficiales) sin renombrar o clasificar en /FOMIX/fmx_insumos/fmx_mendeley/insumos @dpedroza74 @ofegarcia 
3. Compilar el repositorio en Mendeley llenando los campos: autor, título, año y palabras clave (tags) en  /FOMIX/fmx_insumos/fmx_mendeley
4. Renombrar automáticamente con autor y año
5. Se irán eliminando los insumos originales, (la carpeta  /FOMIX/fmx_insumos/fmx_mendeley/insumos solo contendrá los documentos no compilados en Mendeley)

**Comment by Nayita** [comment]
La cuenta que se utilizó para hacer el repositorio de fomix es: apclancis@gmail.com. 
La contraseña está registrada en el archivo para ese fin.

**Comment by Nayita** [comment]
@ofegarcia 
Se concluyó con la revisión y compilación de la información de los documentos del proyecto. Se encontró solo un documento incompleto: Ordenamiento Territorial del Estado de Yucatan: Visión 2030.
Se revisará periódicamente la carpeta de insumos para ir nutriendo el Mendeley del proyecto.

**Comment by Nayita** [comment]
### Nota
Se ha eliminado del Mendeley toda la información del POEL. 
Corina hará la organización de esas carpetas.

**Comment by CorinaCantero** [comment]
Se terminaron de agregar todos los documentos de la carpeta "oe_pucc" brindada por el gobierno del estado de Yucatán. Ya están listos en el proyecto de Mendeley (organizados por carpetas) y en la carpeta de dropbox: FOMIX/fmx_insumos/fmx_mendeley

En el issue #1 se especifica la información que contenía dicha carpeta.

**Comment by CorinaCantero** [comment]
Se agregó en el proyecto de Mendeley los documentos descargados de la página de la Bitácora Ambiental del POETY.

**Comment by CorinaCantero** [comment]
Se terminaron de agregar al proyecto de Mendeley los documentos brindados por el Dr. Batllori.

**Comment by dpedroza74** [comment]
Ya subí las que me faltaban

**Comment by dpedroza74** [comment]
@Nayita 
@CorinaCantero 
No encuentro la carpeta donde podía subir insumos nuevos Ruta: /FOMIX/fmx_insumos/fmx_mendeley/insumos

Me podrían  informar si la quitaron por error o dónde podemos subir ahora lo nuevo

**Comment by CorinaCantero** [comment]
### Aviso
@dpedroza74 

Al parecer como Mendeley está sincronizado con esa carpeta, se borra cuando se procesan todos los archivos. Ya la volví a crear, pero si en otra ocasión la necesitas y no está, la puedes volver a crear sin problemas.

**Comment by dpedroza74** [comment]
Ok, gracias.
@CorinaCantero 
@ofegarcia 
@aleestrada 

Voy a subir a esa carpeta los programas de gobierno para que por favor revisen que la caracterización que están integrando no tenga datos inconsistentes con estos documentos 

- Plan Estatal de Desarrollo
- Programa Sectorial Yucatán con Economía Inclusiva
- Programa Sectorial Yucatán con Calidad de Vida y Bienestar Social
- Programa Sectorial Yucatán Cultural con Identidad para el Desarrollo
- Programa Sectorial Yucatán Verde y Sustentable
- Programa Especial de Igualdad de Género, Oportunidades y No Discriminación
- Programa Especial de Innovación, Conocimiento y Tecnología
- Programa Especial de Paz, Justicia y Gobernabilidad
- Programa Especial de Gobierno Abierto, Eficiente y con Finanzas Sanas
- Programa Especial de Ciudades y Comunidades Sostenibles
- Programa Especial de Salud
- Programa Especial de Turismo
- Programa Regional (VII Regiones)

**Comment by CorinaCantero** [comment]
### Aviso

Se agregaron los archivos que @dpedroza74 enlistó en el comentario anterior a Mendeley, pero para facilitar la organización los archivos se movieron a la siguiente carpeta: 

FOMIX\fmx_insumos\fmx_programas_gobyuc

@aleestrada 
@ofegarcia

**Comment by CorinaCantero** [comment]
@Nayita Aquí puedes reportar los avances o cualquier cosa relacionada al proyecto Mendeley de FOMIX

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
