### ISSUE TITLE
Generar script para cuantificar Áreas de tipo de suelo y vegetación (para todas las series de vegetación) a nivel Municipal

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#20]
la ruta del script para pasar los datos de la series de uso de suelo y vegetación se encuentra en la siguiente ruta:
C:\Dropbox LANCIS)\CARPETAS_TRABAJO\vhernandez\geo_lancis\codigos\datos_nivel_municipio.py

Producto:

ruta: SIG\desarrollo\sig_fomix\entregables\municipios_usv\

Se realizo el proceso de verificación de que los valores de las clases tuviesen area
los archivos finales son :
se entregan 6 csv:
mun_usv_s#.csv donde # es el número de serie que va de 1 a 6

para más información ver los comentarios de los dias 30 de marzo, 1 y 6 de abril en el issue  #19

**Comment by CorinaCantero** [comment]
### Aviso

Ruta de shape de ANP: \SIG\desarrollo\sig_fomix\insumos\ambiente\sds\anps_sds

**Comment by CorinaCantero** [comment]
### Aviso

- Ruta de shape de ANP: \SIG\desarrollo\sig_fomix\insumos\ambiente\sds\anps_sds
@vichdzgeo

**Comment by vichdzgeo** [comment]
## Actualización 

se generaron las cruzas de las clasificaciones 2, 3 y 4 de las series de USV 

se ocupa el script 
CARPETAS_TRABAJO\vhernandez\geo_lancis\codigos\datos_nivel_municipio.py

### Producto

ubicacion : \SIG\desarrollo\sig_fomix\entregables\nivel_municipios_usv\

se encuetran en subcarpetas segun el tipo de clasificacion de USV 

- clasificacion_2/
- clasificacion_3/
- clasificacion_4/

dentro de cada subcarpeta se encuentra el archivo shapefile y el csv para su consulta

nombrados  de la siguiente forma
mun_usv_s#_c&

donde # corresponde al número de serie (1,2,3,4,5,6)
donde & corresponde al número de clasificación (2,3,4)
@CorinaCantero
