### ISSUE TITLE
METAISSUE: Generar proyecto del sistema de conocimiento #FOMIX

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#21]
**Objetivo:** Diseñar, desarrollar e implementar un sistema de gestión para el ordenamiento ecológico del territorio del estado de Yucatán (Sistema) que funcione como un sistema de información geográfica para la puesta en marcha de la actualización del POETY, para el manejo, análisis y visualización de información que facilite la gobernanza colaborativa en el proceso de ordenamiento ecológico en la entidad y su articulación con otros instrumentos de planeación pertinentes.

**PRODUCTO COMPROMETIDO**
 4.1.1 Proyecto del Sistema. - Documento donde se especificará el diseño y arquitectura informática del sistema de conocimiento y soporte geográfico de decisiones para la gestión del POETY. El proyecto describirá la infraestructura tecnológica de software y hardware que se requiere para la operación del Sistema, el cual cumplirá con las siguientes funciones: 
a) Organizar de manera dinámica toda la información relevante del POETY; 
b) simplificar la consulta de informes técnicos; 
c) dar elementos de sustento en los procedimientos administrativos para la emisión de permisos, licencias y autorizaciones; 
d) facilitar la gobernanza colaborativa del ordenamiento ecológico; 
e) servir de base para la configuración de la bitácora ambiental del POETY; 
f) permitir la realización de procedimientos de geovisualización que incluyan como mínimo manejo de bancos de datos, manejo de modelos de análisis, generador de reportes gráficos y tabulares e interfaces de operación; y 
g) facilitar la exploración y geovisualización de los procesos multi-escalares, multitemporales y multi-sectoriales de la transformación territorial y la vulnerabilidad de los ecosistemas al cambio climático.

**ACTIVIDADES Y SUBPRODUCTOS**
**Meta 4.1.1. Identificación de necesidades del usuario y otros beneficiarios**
La identificación de necesidades del usuario y otros beneficiarios se desarrollará a partir de las brechas detectadas en el diagnóstico y las directrices establecidas en la estrategia de fortalecimiento (objetivos específicos I y II). Se considerarán los requerimientos de un proceso de involucramiento ininterrumpido (como se describe en el objetivo III, se define como una modalidad de la planeación colaborativa que involucra la interacción con los agentes sociales relevantes sin interrupción a todo lo largo de una investigación transdisciplinaria). 
Las necesidades de los usuarios se contextualizarán conforme a fase de convocatoria que postula EAST. Así, se examinarán las capacidades en cuanto a las vertientes (1) socio-institucional  para determinar las relaciones que gobierna las conductas de los individuos dentro de un orden social, con un propósito que trasciende las intenciones individuales; (2) grupal para identificar las expectativas, valores, perspectivas y relaciones que se establecen en los grupos y que definen cómo se incorporan a un proceso participativo las cuestiones y los modos de deliberación que se utilizan);  (3) socio-tecnológica para determinar la capacidad instalada o por desarrollar para la conducción del proceso participativo, se incluirá lo referente al equipo, las instalaciones, los programas, y el personal que da soporte técnico al proceso. A partir de las acciones que se contemplen para la convocatoria, se identificarán los mecanismos, los procedimientos y los protocolos necesarios para inducir el proceso cíclico de apropiación- transformación- innovación que postula EAST. 

**Meta 4.1.2. Diseño y arquitectura informática del sistema de gestión**
La arquitectura informática del sistema de gestión del POETY se diseñará dando énfasis a la integración de un todo coherente la participación social, el diagnóstico ambiental y la resolución de conflicto, como se ilustra en la figura siguiente. Se buscará que el sistema de gestión se convierta en un instrumento para hacer evidentes los mecanismos por los que se llega a ciertas decisiones y un registro de los compromisos acordados entre los diferentes sectores de la sociedad. Incluirá por lo tanto una serie de indicadores ambientales para monitorear y evaluar el cumplimiento y la efectividad de los programas y las acciones que se proponen para solucionar o prevenir problemas y conflictos ambientales. Por ser la pieza central del sistema de gestión del POETY, se enfatizará en el diseño informático el papel de la bitácora ambiental en la gestión del POETY a lo largo del tiempo, 
 
La arquitectura del sistema se dirigirá de manera espacial hacia propiciar el buen funcionamiento del comité del POETY. Para ello, el sistema proveerá las condiciones para los procesos de toma de decisiones tangan (1) legitimidad, que se logra con el reconocimiento del proceso, por parte de los agentes sociales, como una forma adecuad para resolver las cuestiones ambientales y la conformación de un órgano de control serio e incluyente; (2) credibilidad, que depende de la confiabilidad de la información que fundamenta las decisiones sobre la ocupación territorial y la resolución de las cuestiones ambientales; y (3) pertinencia, que se deriva de la manera en la que el órgano ejecutivo atiende las cuestiones a resolver y los mecanismos para su solución.
Las funciones del sistema de conocimiento incluirán la consulta interactiva a la bitácora ambiental en línea mediante (1) acceso interactivo a bancos de datos de la caracterización ambiental y socio-económica, (2) monitoreo y evaluación pública a través de índices e indicadores del desempeño del ordenamiento ecológico; y (3) consulta interactiva de mecanismos de resolución de conflictos del programa de ordenamiento ecológico con base en los criterios, estrategias y lineamientos de regulación ecológico en cada UGA. Se entregará toda la documentación que corresponda, incluyendo manuales para cada tipo de usuario (por ejemplo, público, organizaciones, autoridades, etc.) y diagramas UML que detallen la estructura y operación del sistema.

**MECANISMO DE TRANSFERENCIA**
Para la entrega del proyecto del sistema se contempla entregar un documento con las especificaciones técnicas que tendrán las plataformas. Esto incluirá una descripción de las interfaces de usuario, así como un análisis de los casos de uso. Es decir, una descripción exhaustiva de las operaciones que cada usuario podrá ejecutar y de las interfaces que se lo permitirán. Esta entrega se acompañará con una presentación del diseño del sistema y sus componentes en las instalaciones de la SDS

Consultar anexo metodológico de la propuesta

**UBICACIÓN DE DOCUMENTOS EN EL DROPBOX**
/FOMIX/fmx_sistema_conocimiento/proyecto_sistema

**Comment by dpedroza74** [comment]
**Acuerdos reunión 18/3/2020**

- Se tomará como ejemplo documento de Arquitecture for Ordenamiento ecológico web app que entregó la empresaIO Fractal para el sistema automatizado que se desarrollo para SEMARNAT

- Daniela envió por correo el documento y las especificaciones del producto de la propuesta fomix para que sea revisado por @milocortes, @aaron-ts @serranoycandela

- Fidel @serranoycandela presentará un programa de trabajo que incluya a @milocortes  y a @aaron-ts

**Comment by dpedroza74** [comment]
Acuerdos reunión 25/3/2020
Daniela y Fidel

Daniela comentó ideas preliminares sobre los contenidos y funciones  que se requieren para el sistema y subió el documento  _fomix_requerimientos sistema.doc_
en  FOMIX/fmx_sistema_conocimiento/proyecto_sistema/insumos
para que las puedan revisar @serranoycandela, @milocortes y @aaron-ts

**Comment by serranoycandela** [comment]
Subí el cronograma del plan de trabajo en:
https://github.com/lancis-apc/fomix/blob/master/cronograma_sistema_fomix.xlsx
![cronograma_sistema_fomix](https://user-images.githubusercontent.com/12860576/79484986-234bf500-7fda-11ea-85a1-20254f2a9cd5.png)

**Comment by serranoycandela** [comment]
@dpedroza74 @milocortes @aaron-ts 
Hice un esquema de lo que entendí en las conversaciones con Daniela de lo que será el sistema lo comparto y espero sus comentarios.

![Screen Shot 2020-04-20 at 11 42 43](https://user-images.githubusercontent.com/12860576/79777137-6ec51280-82fc-11ea-96a5-0fe372e2cf0c.png)

**Comment by dpedroza74** [comment]
Se llevaron a cabo dos reuniones virtuales los días 28 de abril y 2 de junio con los enlaces técnicos y el enlace de informática de la SDS y con el enlace en la Subsecretaría de Tecnologías de la Información y Comunicaciones del Gobierno del Estado (STIC) 

- LANCIS hizo presentación del concepto del sistema de conocimiento para el POETY
- STIC hizo presentación del proyecto OCDE en el que desarrollan plataforma de gestión de trámites y el Ecosistema Georreferenciado del Estado de Yucatán (EGEY)

Como resultado se acordaron ajustes al diseño y contenidos propuestos por LANCIS. 

Las presentaciones, minutas, audios y video de zoom se encuentran en 
/FOMIX/fmx_sistema_conocimiento/proyecto_sistema/reuniones%20virtuales

**Comment by dpedroza74** [comment]
@serranoycandela @milocortes @paola-gp @aaron-ts 

Subí en el dropbox los lineamientos de la Subsecretaría de Tecnologías de Información y Comunicación del Gobierno de yucatán

/FOMIX/fmx_sistema_conocimiento/proyecto_sistema/insumos/lineamientos%20sctic
