### ISSUE TITLE
Generar análisis de cambio de uso de cobertura #FOMIX 

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#24]
**Objetivo:**
Hacer análisis del cambio de uso de suelo y vegetación para el estado de Yucatán, los resultados se incluirán en el informe de la caracterización del subsistema natural FOMIX.

**Tareas:**

- [x] Reclasificar las seis capas de usv de INEGI @CorinaCantero 

- [ ] Hacer script para futuras reclasificaciones o cambios en las clases de cobertura @vichdzgeo 

- [x] Hacer script y generar matrices de transición entre las series @vichdzgeo :

- S1-S2, S2-S3, S3-S4, S4-S5, S5-S6, S3-S6, S1-S3
Los shapes están a una escala 1:250,000 por lo que se usará un tamaño de pixel de 100x100

- [x] Preparar las matrices de transición identificando las transiciones que sean inconsistentes y calculando los porcentajes (probabilidades). @CorinaCantero 

- [x] Redactar informe de cambio de uso de cobertura e índices generados a partir de dicho análisis #23 @CorinaCantero 

**Ubicación:**
Capas de usv:  SIG\desarrollo\sig_fomix\entregables\usv_v2

> **Actualización 07/05/2020**
> _Información geográfica:_ 
>- Capas geográficas con 4 reclasificaciones con la serie 1 sin correcciones para falsos cambios.
Ruta: SIG\desarrollo\sig_fomix\procesamiento\usv_v2\versiones\origen
> - Capas geográficas con 4 reclasificaciones y la serie 1 de usv INEGI corregida para falsos cambios. Ruta: SIG\desarrollo\sig_fomix\entregables\usv_v2

> _Bases de datos:_
>- Matrices de transición sin correcciones en la serie 1 por falsos cambios: 
Ruta: FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\matrices_v1
>- Matrices de transición con correcciones en la serie 1 por falsos cambios:
Ruta; FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\matrices_v2

**Comment by CorinaCantero** [comment]
### Reclasificación 

**Método**

1. Se descargaron las seis capas de Uso del suelo y vegetación, escala 1:250,000, serie I, serie II, serie III, serie IV, serie V y serie VI de INEGI. 
De acuerdo con INEGI corresponden a los siguientes años:

Serie | Año
-- | --
I | 1985
II | 1993
III | 2002
IV | 2007
V | 2011
VI | 2014

Fuente: https://www.snieg.mx/DocumentacionPortal/geografico/sesiones/doc_22017/Present_Serie_VI_Carta_U_Sue.pdf

2. Las capas fueron recortadas para el área de estudio (estado de Yucatán). Utilizando el script "cortar_capa" ubicado en SIG\desarrollo\sig_becarios\procesamiento\tematicos_yucatan y se reproyectaron a EPSG 32616 WGS 84/UTM zone 16N

3.  Se analizó el área y las categorías de uso de suelo y vegetación originales de INEGI y se decidió agruparlas en 19 nuevas categorías, con el objetivo de mostrar las diferencias entre los cambios de vegetación primaria y vegetación secundaria y las coberturas naturales de las antropogénicas. 
El archivo de las seis series con las categorías originales de INEGI y la nueva clasificación se ubica en: 
Quedando las siguientes categorías: 

Categoria | Descripción
-- | --
1 | Agricultura de riego
2 | Agricultura de temporal
3 | Cuerpo de agua
4 | Manglar
5 | Pastizal
6 | Selva baja
7 | Selva mediana
8 | Sin vegetación
9 | Asentamiento humano
10 | Vegetación de duna costera
11 | Vegetación de petén
12 | Vegetación secundaria de selva   baja
13 | Vegetación secundaria de selva   mediana
14 | Vegetación secundaria de manglar
15 | Acuícola
16 | Bosque cultivado/Palmar inducido
17 | Tular
18 | Vegetación halófila hidrófila
19 | Sábana

**Comment by vichdzgeo** [comment]
## Procedimiento

1.  Se define el siguiente extent para el procedimiento

xmin = 145391
xmax =444591
ymin =2163427
ymax =2391827

2992, 2284

con tamaño de pixel de 100 m x 100 m por lo cual cada pixel representa 1 ha 

2.   se aplica un segundo recorte a las capas de USV (ubicadas en SIG\desarrollo\sig_fomix\entregables\usv_v2) con la máscara de corte del estado (SIG/desarrollo/sig_fomix/entregables/mascara_municipios_2018/area_municipios_2018_yuc.shp)
este proceso es realizado mediante el script -> cortes_usv.py ubicado en SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura
> **Producto** 
sig_fomix/procesamiento/cambio_cobertura/insumos/usv_clip/

3.  Se rasteriza la máscara con un valor de **20** dado que las categorías van del 1 al 19, el valor de **20** expresa territorio o área no clasificada pero perteneciente al área de estudio, este proceso es realizado mediante el script p1_rasterizar_mascara.py ubicado en SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura

> **Producto** SIG/desarrollo/sig_fomix/procesamiento/cambio_cobertura/insumos/mascara/yucatan_mask.tif

4. Se rasterizan las capas resultantes del paso 2, este proceso se realiza con el código p1_rasterizar_series.py ubicado en 

> **Producto**
tp_usv_serie_i_yuc_clip.tif (donde i, va del 1 al 6) ubicado en sig_fomix/procesamiento/cambio_cobertura/insumos/usv_clip/ 

5. las capas tif resultantes del paso 4, se les aplica la máscara raster (producto del paso 3) para este proceso se ocupa el código p2_aplicar_mascara.py ubicado en SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura

> **Producto**
usv_serie_i_yuc_clip.tif (donde i, va del 1 al 6) ubicado en sig_fomix/procesamiento/cambio_cobertura/insumos/usv_clip/ 

6. las capas tiff resultantes del paso 6 son los insumos para generar las matrices de transición, se realizan

**Comment by CorinaCantero** [comment]
### AVISO
Están listas las capas geográficas con las tres nuevas clasificaciones @vichdzgeo 
Ubicación: \SIG\desarrollo\sig_fomix\entregables\usv_v2

**Comment by CorinaCantero** [comment]
### Reclasificación parte 2

1. A las capas de las seis series de uso de suelo y vegetación ya reclasificadas (comentario 1), se les hicieron tres nuevas clasificaciones que se detallan a continuación: 

**Categoría 2**:  En esta clasificación no se distingue la vegetación secundaria de la primaria, por lo cual se juntaron las vegetaciones secundarias de selva baja, selva mediana y manglar con las vegetaciones primarias de las mismas, quedando así 16 categorías: 

Categoría 2 | Descripción
-- | --
1 | Agricultura de riego
2 | Agricultura de temporal
3 | Cuerpo de agua
4 | Manglar
5 | Pastizal
6 | Sin vegetación
7 | Asentamiento humano
8 | Vegetación de duna costera
9 | Vegetación de petén
10 | Selva baja
11 | Selva mediana
12 | Acuícola
13 | Bosque cultivado/Palmar inducido
14 | Tular
15 | Vegetación halófila hidrófila
16 | Sábana

**Categoría 3:** En esta clasificación se distingue únicamente la cobertura natural de la no natural, se considera como vegetación natural, las vegetaciones de petén, selva baja, selva mediana, veg. dunas costeras, tular, cuerpos de agua, sábana y vegetación hidrófila-hipsófila. Por otra parte, se considera como cobertura no natural: agricultura, zona urbana, desprovisto de vegetación, pastizales y bosque cultivado/palmar inducido.

Categoría 3 | Descripción
-- | --
1 | Natural
2 | No natural

Categoría 4: En esta clasificación se distingue la cobertura urbana, la agropecuaria y la natural. Se considera cobertura urbana: desprovisto de vegetación y zona urbana; la categoría agropecuario incluye: agricultura, pastizales, bosque cultivado/palmar inducido y acuicultura, el resto de las vegetaciones corresponde a la categoría natural. 


Categoría 4 | Descripción
-- | --
1 | Asentamiento humano
2 | Agropecuario
3 | Natural

**Nota:** El desglose puntual de cada una de los usos de suelo y vegetación originales de INEGI y las cuatro re clasificaciones elaboradas se detalla en el archivo "usv_inegi" ubicado en: FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv

**Comment by vichdzgeo** [comment]
## Reclasificacion parte 2


### Producto

uta: sig_fomix/procesamiento/cambio_cobertura/matriz_transicion/


archivos CSV que contienen la matriz de transición separados por carpetas según el número de clasificación correspondiente
|carpeta| descripcion|
|-----|------|
|claficacion_1| correspondiente a categoría 1|
|claficacion_2| correspondiente a categoría 2|
|claficacion_3|correspondiente a categoría 3|
|claficacion_4| correspondiente a categoría 4|
ej de nombre:

s1_vs_s2.csv
donde las columnas de la matriz representan las clases de la s1 y los renglones de la matriz representan las clases de la s2

@CorinaCantero

**Comment by vichdzgeo** [comment]
## Capas con múltiplos
@CorinaCantero  las capas se encuentran en 
\sig_fomix\procesamiento\cambio_cobertura\insumos\usv_clip\salida_mul\

en un archivo comprimido **series_mult.zip** 

> Nota: Por el valor de pixel de la serie 6 se cambia el tipo a Float32

el código utilizado para este proceso se encuentra en
SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura\multiplicar_capas.py

**Comment by CorinaCantero** [comment]
### Falsos cambios en la serie I 
@vichdzgeo 
**Ubicación:**
- Capas de usv: SIG\desarrollo\sig_fomix\entregables\usv_v2

- Reclasificar la serie I de acuerdo con la siguiente tabla: 

Serie 1 | Serie 2 | Serie 3 | Serie 4 | Serie 5 | Serie 6 | Reclasificar en S1 como
-- | -- | -- | -- | -- | -- | --
Agricultura de temporal | Selva baja | Selva baja | Selva baja | Selva baja | Selva baja | Selva baja
Agricultura de temporal | Selva mediana | Selva mediana | Selva mediana | Selva mediana | Selva mediana | Selva mediana
Agricultura de riego | Selva baja | Selva baja | Selva baja | Selva baja | Selva baja | Selva baja
Agricultura de riego | Selva mediana | Selva mediana | Selva mediana | Selva mediana | Selva mediana | Selva mediana
Pastizal | Selva baja | Selva baja | Selva baja | Selva baja | Selva baja | Selva baja
Pastizal | Selva mediana | Selva mediana | Selva mediana | Selva mediana | Selva mediana | Selva mediana

**Nota:**
Los campos que corresponden a la clasificación 2 (16 categorías) son:

id_clase2 | Número identificador de la clase reclasificado con las categorias  2
-- | --
clase2 | Texto descriptivo de las categorias de tipo 2

**Comment by vichdzgeo** [comment]
## Ajuste en la clasificación de la serie I por falsos cambios
ruta:SIG\desarrollo\sig_fomix\entregables\cambio_cobertura\

**Producto vectorial**

reclasificacion_s1/r_usv_serie1_yuc.shp

el nombre del campo que contiene ya los valores corregidos es **rid_clase2** y se actualizo el campo **clase2** con el nombre correspondiente según su id.

Capa generada a partir del ajuste de la clasificación de falsos cambios en la capa raster correspondiente a la serie1
@CorinaCantero

**Comment by CorinaCantero** [comment]
### AVISO
@vichdzgeo 

Ya está clasificada la capa "r_usv_serie1_yuc.shp" con las clasificaciones 3 y 4.
Ubicación: SIG\desarrollo\sig_fomix\entregables\cambio_cobertura\reclasificacion_s1/r_usv_serie1_yuc.shp

La tabla de atributos de dicha capa queda así: 

Campo | Descripción
-- | --
rid_clase2 | Número identificador de la clase reclasificada y con falsos cambios corregidos con las clasificación  2
clase2 | Texto descriptivo de las categorías de la clasificación tipo 2 (con falsos cambios corregidos)
id_clase3 | Número identificador de la clase reclasificada con las categorías  3
clase3 | Texto descriptivo de las categorías de la clasificación tipo 3
id_clase4 | Número identificador de la clase reclasificada con las categorías  4
clase4 | Texto descriptivo de las categorías de la clasificación tipo 4

**Comment by vichdzgeo** [comment]
# Aviso

@CorinaCantero 

Las matrices para la clasificaciones 2,3 y 4  ya se encuentran en la siguiente ubicación dentro de su respectiva carpeta: 

\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura\matriz_transicion\

se nombraron de la siguiente manera
- r_s1_vs_s2.csv
- r_s1_vs_s3.csv

> las matrices anteriores se movieron a una subcarpeta llamada **anteriores**





los raster se encuentran en la siguiente ubicación

SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura\insumos\usv_clip\salida


y se nombran :
r_usv_serie1_yuc_c2.tif
r_usv_serie1_yuc_c3.tif
r_usv_serie1_yuc_c4.tif

**Comment by vichdzgeo** [comment]
##Aviso
@CorinaCantero 
Se sustituye en la carpeta SIG\desarrollo\sig_fomix\entregables\usv_v2 la capa correspondiente a la serie1 ya corregida, tambien se cambia el nombre "rid_clase2" por "id_clase2" 

las versiones anteriores pueden encontrarse en SIG\desarrollo\sig_fomix\procesamiento\usv_v2\versiones\originales

**Comment by CorinaCantero** [comment]
## Cruces de capas de USV con capas de municipios y regiones
@vichdzgeo 

**Actividades**
- [ ] Base de datos del área de tipo de suelo y vegetación (para las seis series de vegetación) por municipio (106 municipios).
- [ ] Base de datos del área de tipo de suelo y vegetación por región (7 regiones)

> **Nota:** Hacer las bases de datos con los cruces de municipios y regiones para las tres clasificaciones: clasificación 2 (16 categorías), clasificación 3 (2 categorías) y clasificación 4 (3 categorías).

**Insumos:**

- **Capa de municipios:** 
Ruta: SIG\desarrollo\sig_fomix\entregables\mun_region
Esta capa contiene municipios y regiones, siendo de interés los siguientes atributos:

Nombre del atributo | Descripción
-- | --
cve_mun | Clave del municipio
nom_mun | Nombre del municipio
region | Nombre de la región
id_region | Número identificador de la región

- **Capa de regiones sin municipios**
Ruta: SIG\desarrollo\sig_fomix\procesamiento\regiones\regiones_yuc2.shp
Esta capa solo contiene las siete regiones

Nombre del atributo | Descripción
-- | --
region | Nombre de la región
no_region | Número romano de la región
id_region | Número identificador de la región

**Capas de uso de suelo y vegetación**
Ruta: \SIG\desarrollo\sig_fomix\entregables\usv_v2

**Comment by vichdzgeo** [comment]
@CorinaCantero 

listas las bases de datos a nivel de municipio por clasificaciones ver issue #20 

listas las bases de datos a nivel de regiones por clasificaciones ver issue  #29

**Comment by CorinaCantero** [comment]
### AVISO

Ubicación del informe de cambio de cobertura: 
\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\informe_cambio_cobertura
@vichdzgeo

**Comment by CorinaCantero** [comment]
### AVISO

Los procedimientos y resultados (gráficas y mapas) de cambio de cobertura e índices asociados se mencionan en el issue #31

**Comment by CorinaCantero** [comment]
### AVISO

@vichdzgeo 

Ruta del archivo .xls de clases originales de INEGI: 
FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\usv_inegi

Ruta shape del Inventario Nacional Forestal 2009-2014:
SIG\desarrollo\sig_fomix\insumos\cobertura\conafor\inventario_forestal\continuo_cobertura_yuc_utm16.shp

Ruta shape del Inventario Nacional Forestal 2004-2009:

**Comment by paola-gp** [comment]
### Reclasificación y mejora de series USV con uso del suelo y vegetación de la zona costera asociada a los manglares en la Región Península de Yucatán

Serie USV | Año | Serie manglares | Año
-- | -- | -- | --
I | 1985 | I | 1981
II | 1993 |   |  
III | 2002 | II | 2005
IV | 2007 |   |  
V | 2011 | III | 2010
VI | 2014 | IV | 2015

**Comment by paola-gp** [comment]
### Matrices de confusión

Issue relacionado #84 
- [x] Reclasificar todas las series de INEGI con base en resultados de análisis INEGI-INF y Conafor matrices_confusion_cobertura_Cats_v4.xlsx


id | Clase
-- | --
1 | Acuícola
2 | Agricultura
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar, petén, tular e hidrófila
9 | Selva
11 | Sin vegetación
14 | Duna costera
17 | ND


- [x] Matríz de confusión Serie I a Serie II
- [x] Matriz de confusión **Serie II** a Serie III
- [x] Matriz de confusión Serie III a Serie IV
- [x] Matriz de confusión Serie IV a Serie V
- [x] Matriz de confusión Serie V a VI
- [x] Matríz de confusión Serie I a Serie III
- [x] Matríz de confusión Serie III a Serie VI
- [ ] Mejorar capas Series analizadas y acordadas

**Comment by vichdzgeo** [comment]
## Capa de cobertura serie VI corregida con humedales 

> **El resultado de esta capa reclasifica la categoría  de USV Manglar <Otros humedales> como la categía de USV SVI <Cuerpo de agua>**

Insumos: 

- serie 6 INEGI
`SIG/desarrollo/sig_fomix/procesamiento/analisis_aptitud/insumos/generales/cobertura_usv_svi_16cats.tif`

- USV Manglar 2015
`SIG/desarrollo/sig_fomix/procesamiento/areas_conservacion/insumos/series_manglar/usv_manglar_2015.shp`

### Reglas de reclasificación para USV Manglar 2015


Categoría | id | id USV SVI INEGI
-- | -- | --
Agrícola - Pecuaria | 1 | 2
Cuerpos de agua | 2 | 6
Desarrollo antrópico | 3 | 4
Manglar | 4 | 7
Manglar perturbado | 5 | 7
Otros humedales | 7 | 6
Otra vegetación | 6 | 14
Sin vegetación | 8 | 11
NA | 9 | 17

## Capa Corregida**

Ruta: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\insumos\generales\cobertura_usv_svi_16cats_costa_manglar.tif

@CorinaCantero @paola-gp

**Comment by vichdzgeo** [comment]
## Actualizaciones 

## Capas de cobertura para la zona de estudio (Yucatán) de uso de suelo y vegetación de INEGI mejoradas con la capas uso del suelo y vegetación de la zona costera asociada a los manglares en la Región Península de Yucatán

`Ruta: SIG\desarrollo\sig_fomix\procesamiento\areas_conservacion\procesamiento\inegi\series_corregidas`

- usv_serie1_100m_v4_corregida.tif
- usv_serie3_100m_v4_corregida.tif
- usv_serie5_100m_v4_corregida.tif
- usv_serie6_100m_v4_corregida.tif

## Matices de confusión

Se calcularon las matrices de confusión para las series S1,S3,S5,S6
`Ruta:  \sig_fomix\procesamiento\areas_conservacion\procesamiento\inegi\matrices\matrices_s1_s3_s5_s6_corregida_abril.xlsx`
