### ISSUE TITLE
Generar script para cuantificar Áreas Naturales Protegidas por municipio y por tipo de vegetación #fomix

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#25]
**Objetivo**: Generar base de datos de Áreas Naturales Protegidas por municipio y por tipo de vegetación para el estado de Yucatán.

**Insumos:**
- Áreas Naturales Protegidas Federales:
SIG\desarrollo\sig_fomix\procesamiento\anp\anp_federal_yuc
Metadato: http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/ce887b90-6a5e-4256-9692-ccc10c99713e
- Áreas Naturales Protegidas Estatales, Municipales y Privadas: 
SIG\desarrollo\sig_fomix\procesamiento\anp\anp_estatal_mun_priv_yuc
Metadato:
- Límites municipales 2018 INEGI con regiones:
SIG\desarrollo\sig_fomix\entregables\mun_region
- Serie I a VI de uso de suelo y vegetación:
SIG\desarrollo\sig_fomix\entregables\usv_v2

**Comment by CorinaCantero** [comment]
### Aviso

Se cambió el shape proporcionado por la SDS por shapes de CONANP, debido a que el área de una de las ANP "San Juan Bautista Tabi" tenía un área incorrecta que se visualizaba al ponerla sobre una imagen satélite.

![image](https://user-images.githubusercontent.com/44783182/80415109-aa7d5080-8897-11ea-8656-ad6bb1676f77.png)

**Comment by CorinaCantero** [comment]
### Método:

1. Se descargó la capa de  Áreas Naturales Protegidas Federales de la República Mexicana.
 de CONANP 2017 y la capa de Áreas Naturales Protegidas Estatales, Municipales, Ejidales y Privadas de México 2015, de CONABIO.
2. Se recortaron las capas para el estado de Yucatán y se reproyectaron a EPSG 32616 WGS 84/UTM zone 16N.
3. Se verificó que las ANP correspondieran a las reportadas por la Secretaría de Desarrollo Sostenible (SDS) del estado de Yucatán.
3. Debido a que la ANP estatal "Ich Kool Balamtun" no está incluida en la capa original de CONABIO,  se recortó el polígono de la capa de anp proporcionada por la SDS* y se añadió al insumo final "anp_estatal_mun_priv_yuc", con la herramienta de unión (vectorial/herramientas de geoproceso/unión) de QGIS.

Nota: 
*Ubicación de la capa de anps, SDS: SIG\desarrollo\sig_fomix\insumos\ambiente\sds\anps_sds\anps

Tabla de ANP en el estado de Yucatán:
Área   Natural Protegida | Jurisdicción
-- | --
Bala'an Ka'ax | Federal
Dzibilchantún | Federal
Playa adyacente a la localidad denominada Río Lagartos | Federal
Ría Celestún | Federal
Ría Lagartos | Federal
Geohidrológica del   anillo de cenotes | Estatal
Reserva Biocultural del   Pucc | Estatal
Dzilam | Estatal
Ciénegas y Manglares de   la Costa Norte | Estatal
El Palmar | Estatal
Lagunas de Yalahau | Estatal
San Juan Bautista Tabi y   Anexa Sacnité | Estatal
Kabah | Estatal
Ich Kool Balamtun | Estatal
Cuxtal | Municipal
Bioparque Xla´kaj | Municipal
El Zapotal | Privada
Kaxil kiuic | Privada

**Comment by vichdzgeo** [comment]
## Producto

ubicación: 
\SIG\desarrollo\sig_fomix\entregables\nivel_municipios_anp_usv

Se usa el script datos_nivel_municipio.py y se almacena una copia en la carpeta correspondiente a procesamiento 


ruta : 
 
 Nota:

- Se consideraron todas las Jurisdicciones para el proceso

- Se calcularon áreas expresadas en Ha (si lo desean pueden expresarse en términos de porcentaje)

-  Se calcula para las clasificaciones 2,3, y 4 de USV, existe una carpeta por clasificación 

se nombran las bases de datos como 

mun_anp_usv_s_#.shp , Dónde #, corresponde al número de serie (1,2,3,4,5,6)

@CorinaCantero
