### ISSUE TITLE
Hacer análisis de fragmentación del territorio #fomix

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#28]
**Objetivo:** generar análisis de fragmentación del territorio como parte de los insumos del subsistema natural del proyecto FOMIX.

**Insumos:**
Capas de uso de suelo y vegetación: \SIG\desarrollo\sig_fomix\entregables\usv_v2

**Resultados:**
Ubicar los resultados en la siguiente ruta: 
\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\fragmentacion

> **Actualización 07/05/2020**
> _Información geográfica:_ 
>- Capas geográficas con 4 reclasificaciones con la serie 1 sin correcciones para falsos cambios.
Ruta: SIG\desarrollo\sig_fomix\procesamiento\usv_v2\versiones\origen
> - Capas geográficas con 4 reclasificaciones y la serie 1 de usv INEGI corregida para falsos cambios. Ruta: SIG\desarrollo\sig_fomix\entregables\usv_v2

**Comment by BioloArturo** [comment]
Método
1-Para el análisis de fragmentación se utilizaron los mapas de la serie III a la serie VI elaborados en el Laboratorio Nacional de Ciencias de la Sostenibilidad (LANCIS). Cada uno de los mapas fue convertido de un archivo vectorial a un archivo ráster utilizando el sistema de información geográfico QGIS. 
2-Para calcular las métricas del paisaje se utilizó el programa FRAGSTATS.
3-Se calculó el cambio relativo para las 4 métricas utilizadas como indicadores del análisis de fragmentación: Área, Dimensión Fractal, Tamaño de Parche, Número de parches.
Cambio relativo=(cantidad final-cantidad incial)/(cantidad inicial)
4- Se calculó el intervalo de confianza para el tamaño de parche y la dimensión fractal:
IC=(1.96*Desviación Estandar (area o la dimensión fractal))/(√número  de parches)
IC Mayor=Promedio+IC
IC Menos=Promedio-IC
5- Se calculó el índice de fragmentación 
La ecuación utilizada para calcular el índice de fragmentación es:
F=(superficie total del hábitat)/((Número de manchas*dispersión de las manchas))
 Donde, dispersión de las manchas (Rc) 
(R_c) =2d_c (λ/π)
λ=densidad de las manchas=(número de manchas)/(superficie total del area de estudio)*100
d_c= distancia media desde una mancha (su centro o centroide) hasta la mancha mas cercana. 
6-La información obtenida fue acomodada en tablas de Excel.

**Comment by CorinaCantero** [comment]
**Insumos**
@BioloArturo 
Capas de uso de suelo y vegetación seis series INEGI ubicación: \SIG\desarrollo\sig_fomix\entregables\usv_v2

1. Explicación de las clasificaciones hechas a las capas:

**Clasificación 1:** Se analizó el área y las categorías de uso de suelo y vegetación originales de INEGI y se decidió agruparlas en 19 nuevas categorías, con el objetivo de mostrar las diferencias entre los cambios de vegetación primaria y vegetación secundaria y las coberturas naturales de las antropogénicas. Quedando las siguientes categorías: 

Categoría | Descripción
-- | --
1 | Agricultura de riego
2 | Agricultura de temporal
3 | Cuerpo de agua
4 | Manglar
5 | Pastizal
6 | Selva baja
7 | Selva mediana
8 | Sin vegetación
9 | Asentamiento humano
10 | Vegetación de duna costera
11 | Vegetación de petén
12 | Vegetación secundaria de selva   baja
13 | Vegetación secundaria de selva   mediana
14 | Vegetación secundaria de manglar
15 | Acuícola
16 | Bosque cultivado/Palmar inducido
17 | Tular
18 | Vegetación halófila hidrófila
19 | Sábana

**Clasificación 2**:  En esta clasificación no se distingue la vegetación secundaria de la primaria, por lo cual se juntaron las vegetaciones secundarias de selva baja, selva mediana y manglar con las vegetaciones primarias de las mismas, quedando así 16 categorías: 

Categoría 2 | Descripción
-- | --
1 | Agricultura de riego
2 | Agricultura de temporal
3 | Cuerpo de agua
4 | Manglar
5 | Pastizal
6 | Sin vegetación
7 | Asentamiento humano
8 | Vegetación de duna costera
9 | Vegetación de petén
10 | Selva baja
11 | Selva mediana
12 | Acuícola
13 | Bosque cultivado/Palmar inducido
14 | Tular
15 | Vegetación halófila hidrófila
16 | Sábana

El archivo de categorías originales de INEGI de las seis series de INEGI y las nuevas re clasificaciones se ubica en: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos\subnatural\cambio_usv\usv_inegi

Explicación de las tablas de atributos de los shapes:

Se detallan los campos agregados a las capas originales de INEGI, en el próximo comentario se explican las re clasificaciones realizadas: 

Campo | Descripción
-- | --
id_clase1 | Número identificador de la clase reclasificado con las categorias  1
clase1 | Texto descriptivo de las categoriasde tipo 1
id_clase2 | Número identificador de la clase reclasificado con las categorias  2
clase2 | Texto descriptivo de las categorias de tipo 2
id_clase3 | Número identificador de la clase reclasificado con las categorias  3
clase3 | Texto descriptivo de las categorias de tipo 3
id_clase4 | Número identificador de la clase reclasificado con las categorias  4
clase4 | Texto descriptivo de las categorias de tipo 4

**Comment by CorinaCantero** [comment]
### AVISO
@BioloArturo 

El shape de la serie 1 corregido para los falsos cambios, se encuentra en: SIG\desarrollo\sig_fomix\entregables\cambio_cobertura\reclasificacion_s1/r_usv_serie1_yuc.shp

La tabla de atributos de dicha capa queda así: 

Campo | Descripción
-- | --
rid_clase2 | Número identificador de la clase reclasificada y con falsos cambios corregidos con la clasificación  de tipo 2
clase2 | Texto descriptivo de las categorías de la clasificación tipo 2 (con falsos cambios corregidos)
id_clase3 | Número identificador de la clase reclasificada con la clasificación de tipo  3
clase3 | Texto descriptivo de las categorías de la clasificación tipo 3
id_clase4 | Número identificador de la clase reclasificada con la clasificación de tipo  4
clase4 | Texto descriptivo de las categorías de la clasificación tipo 4

**Comment by BioloArturo** [comment]
@paola-gp :  
Buenos días. Los archivos raster .tif de las regiones se encuentran en : 
C:\Dropbox (LANCIS)\SIG\desarrollo\sig_fomix\procesamiento\frag_series\salida
Los archivos ESRI Shapefile (SHP):
 C:\Dropbox (LANCIS)\SIG\desarrollo\sig_fomix\procesamiento\frag_series\insumos\series_frags

**Comment by vichdzgeo** [comment]
## Datos a nivel municipal relacionados con region y clase de tipo de vegetación 

Ruta: SIG/desarrollo/sig_fomix/procesamiento/nivel_municipios_usv/

NOTA : No modificar estos archivos ,realizar una copia en la carpeta de trabajo 

tp_inters_mun_usv_s1_c2.shp
tp_inters_mun_usv_s2_c2.shp
tp_inters_mun_usv_s3_c2.shp
tp_inters_mun_usv_s4_c2.shp
tp_inters_mun_usv_s5_c2.shp
tp_inters_mun_usv_s6_c2.shp

**Comment by BioloArturo** [comment]
La base de datos por municipio se encuentra en:
C:\Dropbox (LANCIS)\SIG\desarrollo\sig_fomix\procesamiento\frag_series\insumos
Los archivos ESRI por serie en:
C:\Dropbox (LANCIS)\SIG\desarrollo\sig_fomix\procesamiento\frag_series\insumos\municipios_frags

**Comment by paola-gp** [comment]
@vichdzgeo @paola-gp 
Indicar ubicación de insumos y productos

**Comment by vichdzgeo** [comment]
## Rutas

## Para insumos geográficos

SIG\desarrollo\sig_fomix\procesamiento\analisis_fragmentacion

## Productos

**Comment by vichdzgeo** [comment]
## Generar los insumos requeridos para fragstats


### Insumos
- capa de uso de suelo y vegetación serie VI, INEGI
- Carreteras de Yucatán, INEGI

## Procedimiento

- Agregar un campo **'id_frag'** de tipo entero y clasificar según lo siguiente:

categoría | id_frag
-- | --
Acuícola | 999
Agricultura de riego | 999
Agricultura de temporal | 999
Asentamiento humano | 999
Bosque cultivado/Palmar inducido | 13
Cuerpo de agua | 999
Manglar | 4
Pastizal | 5
Selva baja | 10
Selva mediana | 11
Sin vegetación | 999
Sábana | 16
Tular | 14
Vegetación de duna costera | 8
Vegetación de petén | 9
Vegetación halófila hidrófila | 15

- Rasterizar la capa de uso de suelo y vegetación con el campo **id_frag**, el archivo resultante tiene que ser de tipo entero y tener valor de no data de **-9999**
- Rasterizar la capa de carreteras, esta capa se rasteriza con el campo **presencia** 
- Se asignan el valor de 0 a los pixeles nulos de la capa carretera, esto representa la ausencia
- Se genera un segundo producto con la capa raster de uso de suelo y vegetación y con la capa raster de carreteras (1 = presencia, 0 = ausencia)  generando una condicional donde si en el pixel existe la presencia de carretera se asigna 999, en caso contrario se asigna el valor de la capa raster de uso y vegetación

### Productos resultantes 
Ruta: SIG\desarrollo\sig_fomix\procesamiento\analisis_fragmentacion\insumos

- usv_serie6_yuc.tif
- usv_serie6_yuc_con_carreteras.tif

**Comment by CorinaCantero** [comment]
### INSUMOS

## Cobertura
- Mapa revisado de cobertura 2016 CONAFOR
Ruta: SIG\desarrollo\sig_fomix\insumos\cobertura\conafor\cobertura_16

## Cambio de cobertura
- Cambios de cobertura entre 2016 y 2019 de CONABIO
Ruta: SIG\desarrollo\sig_fomix\insumos\ambiente\conabio\eoss4tnc_lancoverchanges

- Mapas cambio de cobertura de CONAFOR
Periodos

- 2000 - 2003
- 2003 - 2011
- 2011 - 2014|
- 2014 - 2016

Ruta: SIG\desarrollo\sig_fomix\insumos\ambiente\conafor\cambio_cobertura
