### ISSUE TITLE
Generar mapas temáticos con base en términos de referencia para el estado de Yucatán #fomix

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/fomix#3]
Ruta:
SIG\desarrollo\sig_becarios\procesamiento\caracterizacion_natural

Área de estudio: Estado de Yucatán

#### Actividades:

- [x] Revisar el Anexo de la Demanda Específica YUC-2018-04-01, página 14: 1. Descriptiva y Diagnóstico
\SIG\desarrollo\sig_becarios\procesamiento\caracterizacion_natural\FOMIX_YUCATAN_DEMANDA_ESPECIFICA_2018-04.pdf

- [x] Revisar el Anexo de la Demanda Específica YUC-2018-04-01, Subsistema productivo y socio-económico
\SIG\desarrollo\sig_becarios\procesamiento\caracterizacion_natural\FOMIX_YUCATAN_DEMANDA_ESPECIFICA_2018-04.pdf

- [x] Hacer lista de los insumos necesario para la generación de los mapas temáticos solicitados para el subsistema natural, subsistema socioeconónimo y subsistema productivo

- [x] Verificar en la plataforma de GeoNetwork si se cuenta con esos insumos en caso contrario recopilar la información en fuentes oficiales y generar los metadatos.

- [x] Generar los mapas temáticos en QGIS en un solo proyecto.

**Comment by CorinaCantero** [comment]
##  Preparar mapas estilo atlas y para los textos de caracterización

A los mapas ya realizados se les harán correcciones para que existan dos versiones diferentes, una de las versiones será presentada en un atlas y la otra se usará para incluirla en los textos de caracterización.

Para ambos mapas:

- Dejar activa la capa de loc_principales y loc_urb2
-Desactivar capas de carreteras y cuerpo_agua_yuc

### Mapas para atlas (versión 1)

- Quitar logos de UNAM y LANCIS
- Cambiar tamaño de letra de los datos a 10
- Cambiar la alineación vertical de los datos a Medio

### Mapas para textos de caracterización

-Eliminar mapa de la República Mexicana
-El cuadro de datos, recorrerlo hasta el extremo derecho, dejando dos cuadritos de espacio desde el límite de la hoja
-Recorrer el cuadro de simbología para aumentar su extensión (cuatro cuadritos antes de la caja de datos)
-Re distribuir la información contenida en la sección de simbología, cambiando la separación entre los elementos de la leyenda.

**Comment by CorinaCantero** [comment]
Empezar con los proyectos: 

- [ ] mp_fomix_usv
- [ ] mp_geomorf
- [ ] mp_fomix_fgeomorfohidro
- [ ] mp_fallas_litol
- [ ] mp_cuencas_hidrologicas
- [ ] mp_clima
- [ ] mp_edafo
- [ ] mp_riesgo_eventosnat

@Nayita

**Comment by ofegarcia** [comment]
@paola-gp @CorinaCantero 
La lista de mapas necesarios, por el momento, para caracterización socioeconómica está en 
SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico

**Comment by CorinaCantero** [comment]
### TAREA 1

**Hacer mapa de siete regiones de Yucatán:**

1.  Seleccionar de la capa base "muni_2018_utm16.shp" los municipios de cada región según la página http://www.yucatan.gob.mx/estado/municipios.php
Ubicación: SIG\desarrollo\sig_fomix\insumos\limites\inegi\div_pol_mpio_2018\muni_2018_utm16.shp
 
2.  Crear una nueva capa vectorial con los objetos seleccionados: edición/copiar objetos espaciales/pegar objetos espaciales/Temporary Scratch Layer

3.  Utilizar la herramienta Dissolve para borrar los límites municipales Vectorial/Herramientas de geoproceso/Dissolve

4.  Eliminar de la tabla de atributos: área, perímetro, nom_mun, cov_, cov_id y agregar una columna llamada "region".

5. Guardar el polígono con el nombre de la región en: SIG/desarrollo/sig_fomix/procesamiento/regiones
 
6. Unir las siete regiones para terminar Vectorial/Herramientas de gestión de datos/Combinar capas vectoriales.
 
7.  Guardar la capa vectorial resultante en la ubicación, con el nombre "regiones_yuc" en: SIG/desarrollo/sig_fomix/procesamiento/regiones

**Comment by Nayita** [comment]
## Aviso

@CorinaCantero 
Se concluyó los mapas para Atlas y texto Hasta mp_clima/Clima y Clima_v2

**Comment by CorinaCantero** [comment]
### AVISO

@paola-gp 
La base de datos con los mapas que tienen unidades cuantitativas está ubicada en: FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos\relacion_mapas_unidades

**Comment by CorinaCantero** [comment]
### AVISO

Se concluyeron los mapas para la primera entrega de FOMIX, se enlistan a continuación: 

## SUBSISTEMA NATURAL

Clave | Nombre del mapa
-- | --
1.1a | Delimitación del área de estudio
1.1b | Mapa base
1.2 | Geología superficial y principales características estructurales
1.3 | Fisiografía
1.3a | Unidades de paisaje
1.4 | Edafología
1.5 | Degradación del suelo
1.6 | Clima
1.7 | Temperatura media anual
1.7a | Temperatura máxima promedio
1.7b | Temperatura mínima promedio
1.8 | Precipitación media anual
1.9 | Evapotranspiración real (isolíneas)
1.11 | Índice de riesgo a eventos naturales
1.12 | Vulnerabilidad costera a eventos naturales
1.13a | Uso potencial agrícola
1.13b | Uso potencial forestal
1.13c | Uso potencial pecuario
1.14a | Vulnerabilidad máxima de asentamientos humanos a inundaciones (modelo de   cambio climático)
1.14b | Vulnerabilidad máxima de la población al incremento en la distribución   del dengue  (modelo de cambio   climático)
1.19 | Regionalización hidrológica CONAGUA
1.20 | Cuerpos de agua
1.22a | Semáforo de la calidad del agua superficial
1.22b | Semáforo de la calidad del agua subterránea
1.23a | Áreas Naturales Protegidas Federales
1.23b | Áreas Naturales Protegidas Estatales, Municipales y Privadas
1.24 | Áreas de importancia para la conservación de las aves (AICAS)
1.25 | Sitios RAMSAR
1.26 | Regiones Marinas Prioritarias
1.27 | Regiones Hidrológicas Prioritarias
1.28 | Regiones Terrestres Prioritarias
1.29 | Sitios terrestres prioritarios para la conservación de la biodiversidad
1.30 | Sitios prioritarios acuáticos epicontinentales y marinos para la   conservación de la biodiversidad
1.31 | Registros de ejemplares de anfibios
1.32 | Registros de ejemplares de reptiles
1.33 | Registros de ejemplares de mamíferos
1.34 | Registros de ejemplares de aves
1.35 | Registros de ejemplares de plantas
1.36 | Uso de suelo y vegetación serie VI
1.36b | Uso de suelo y vegetación serie I
1.36c | Uso de suelo y vegetación serie III
1.37a | Cambio de uso de suelo y vegetación SI-SIII (1985-2002)
1.37b | Cambio de uso de suelo y vegetación SIII-SVI (2002-2014)
1.38 | Índice de calidad de los recursos
1.39a | Fragilidad del territorio, 2002
1.39b | Fragilidad del territorio, 2014
1.40 | Síntesis del subsistema natural
RUTA: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto

## SUBSISTEMA SOCIOECONÓMICO

Clave | Nombre del   mapa
-- | --
3.1 | Regiones del estado   de Yucatán
3.1b | Áreas Geoestadísticas   Básicas (AGEB) Urbanas
3.2 | Distribución de la   población por municipio, 2015
3.3 | Ciudades del estado   de Yucatán, 2018
3.4 | Grado de dispersión   poblacional por municipio, 2010
3.5 | Carreteras y   localidades cercanas a ciudades, 2010
3.6 | Carreteras y   localidades, 2010
3.7 | Distribución de las   localidades según rango-tamaño, 2010
3.8 | Áreas de   concentración poblacional, 2010
3.9 | Localidades aisladas,   2010
3.10 | Población indígena   por municipio, 2015
3.10b | Distribución   geográfica del pueblo indígena maya, 2015
3.11a | Población ocupada que   percibe hasta un salario mínimo, 2015
3.11b | Población ocupada que   percibe de uno a dos salarios mínimos, 2015
3.11c | Población ocupada que   percibe más de dos salarios mínimos, 2015
3.12a | Población ocupada en   el sector primario por municipio, 2015
3.12b | Población ocupada en   el sector secundario por municipio, 2015
3.12c | Población ocupada en   el sector terciario por municipio, 2015
3.13 | Población en   situación de pobreza por municipio, 2015
3.14 | Población en   situación de pobreza extrema por municipio, 2015
3.15 | Grado de marginación   por municipio, 2015
3.15a | Marginación y lugares   centrales, 2015
3.16 | Rezago social por   municipio, 2015
3.17 | Rezago educativo por   municipio, 2015
3.18 | Principales corrientes migratorias   interestatales, 2005-2010
3.19 | Categoría migratoria por municipio,   2010
3.20 | Inmigración nacional e internacional   por municipio, 2015
3.21 | Migración   intraestatal por municipio, 2015
3.22 | Grado de intensidad   migratoria México-Estados Unidos por municipio, 2010
3.23 | Síntesis subsistema   socioeconómico

Ruta: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_socioeconomico\texto

## SUBSISTEMA PRODUCTIVO

Clave | Nombre del   mapa
-- | --
2.1 | Producto bruto   total
2.2 | Inversión
2.3 | Población ocupada
2.4 | Unidades económicas
2.5 | Participación del   municipio en la producción del estado
2.6 | Participación del   municipio en la inversión del estado
2.7 | Participación del   municipio en el total de población ocupada del estado
2.8 | Participación del   municipio en el total de unidades económicas del estado
2.9 | Tenencia de la tierra
2.10a | Superficie sembrada   de pastos y praderas, 2018
2.10b | Superficie sembrada   de maíz grano, 2018
2.10c | Superficie sembrada de naranja, 2018
2.11 | Índice de concentración industrial
2.12 | Principal actividad económica por municipio

Ruta: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_productivo\texto

**Comment by CorinaCantero** [comment]
### ACTUALIZACIÓN

Se modifica la plantilla para las entregas subsecuentes del proyecto FOMIX, quedando dos versiones: 

Versión para presentaciones:
![fragilidad_s3](https://user-images.githubusercontent.com/44783182/101950074-46a36000-3bba-11eb-80ed-e535b3c33936.png)
Versión para informes:
![fragilidad_s3](https://user-images.githubusercontent.com/44783182/101950111-56bb3f80-3bba-11eb-8827-14f9bcb2bead.png)

**Comment by CorinaCantero** [comment]
## REPORTE DE PROYECTOS QGIS GENERADOS HASTA EL 30/09/2021

Para el proyecto FOMIX se han creado cuatro clases de proyectos en QGIS: 

a) **Lizmap**: son proyectos que se configuraron para su publicación como Lizmaps, las capas contienen estilos y en algunos casos están vinculadas a sus metadatos.
b) **Capas con estilos y plantilla**: son proyectos en donde las capas tienen estilos cargados y composiciones de impresión (plantillas) para generar imágenes de mapas. 
c) **Capas con estilos**: son proyectos en donde las capas tienen estilos cargados.
d) **Capas cargadas**: son proyectos que contienen capas sin estilos. 

En la siguiente base de datos se encuentra un compilado de los proyectos que se han creado hasta el momento para el proyecto FOMIX y las plantillas que se generaron (se copia dicha tabla en este comentario).

**Ruta: SIG\desarrollo\sig_fomix\bd_proyectos_plantillas**

Nombre del proyecto | Descripción | Avance | Ubicación
-- | -- | -- | --
mp_areas_conservar_restaurar | Capas generadas para el análisis de áreas a preservar, proteger,   restaurar y conservar | Capas con estilos y plantilla | SIG\desarrollo\sig_fomix\mapas
mp_talleres_aptitud | Capas generadas en los talleres sectoriales (FV, exclusión,   aprovechamiento actual y aptitud) | Capas con estilos y plantilla | SIG\desarrollo\sig_fomix\mapas
mp_atlas_aptitud | El proyecto se generó para preparar los mapas de aptitud con el fin de   impresión, no se concluyó. Se necesitan vectorizar los rasters de exclusión y   aprovechamiento actual para sobreponerlos al mapa de aptitud | Capas con estilos y plantilla | SIG\desarrollo\sig_fomix\mapas
mp_mapas_anio_dos | Capas utilizadas durante el año dos del proyecto | Capas con estilos y plantilla | SIG\desarrollo\sig_fomix\mapas
mp_subsistema_natural | Proyecto con las versiones entregadas del subsistema natural | Capas cargadas | SIG\desarrollo\sig_fomix\mapas
mp_subsistema_socioeco | Proyecto con las versiones entregadas del subsistema socioeconómico | Capas cargadas | SIG\desarrollo\sig_fomix\mapas
mp_subsistema_productivo | Proyecto con las versiones entregadas del subsistema productivo | Capas cargadas | SIG\desarrollo\sig_fomix\mapas
subsistemas | Versión anterior del proyecto de la entrega uno (incluye las capas de los   tres subsistemas) | Lizmap | SIG\desarrollo\sig_fomix\mapas\sub_natural
1_2 a 1_40 | 47 proyectos uno por cada mapa elaborado en la caracterización   natural (Revisar en comentarios anteriores que significa cada clave) | Capas con estilos y plantilla | SIG\desarrollo\sig_fomix\mapas\sub_natural
2_1 a 2_12 | 14 proyectos uno por cada mapa elaborado en la caracterización subsistema   productivo (Revisar en comentarios anteriores que significa cada clave) | Capas con estilos y plantilla | SIG\desarrollo\sig_fomix\mapas\sub_productivo
3_1 a 3_23 | 26 proyectos uno por cada mapa elaborado en la caracterización subsistema   socioeconómico (Revisar en comentarios anteriores que significa cada clave) | Capas con estilos y plantilla | SIG\desarrollo\sig_fomix\mapas\sub_socioeconomico

## En los siguientes proyectos se cargaron las capas de insumos disponibles 
**Ruta: SIG\desarrollo\sig_fomix\insumos**

Nombre del proyecto | Descripción | Avance
-- | -- | --
agricultura | Contiene insumos disponibles en la categoría temática agricultura (hasta   antes de los talleres sectoriales) | Lizmap
agua | Contiene insumos disponibles en la categoría temática agua (hasta antes   de los talleres sectoriales) | Lizmap
ambiente | Contiene insumos disponibles en la categoría temática ambiente (hasta   antes de los talleres sectoriales) | Lizmap
amc | Contiene insumos disponibles en la categoría temática atmósfera,   meteorología y clima (hasta antes de los talleres sectoriales) | Lizmap
biota | Contiene insumos disponibles en la categoría temática biota (hasta antes   de los talleres sectoriales) | Lizmap
cobertura | Contiene insumos disponibles en la categoría temática cobertura (hasta   antes de los talleres sectoriales) | Lizmap
conservacion | Se creo para mostrar los insumos potenciales de ser utilizados en el   taller del sector conservación | Lizmap
cuerpos_agua | Contiene las capas de cuerpos de agua | Lizmap
economia | Contiene insumos disponibles en la categoría temática economía  (hasta antes de los talleres   sectoriales) | Lizmap
geocientifica | Contiene insumos disponibles en la categoría temática geocientífica   (hasta antes de los talleres sectoriales) | Lizmap
mineria | Contiene insumos disponibles en la categoría temática minería (hasta   antes de los talleres sectoriales) | Lizmap
p_catastral | Contiene insumos disponibles en la categoría temática planeación   catastral (hasta antes de los talleres sectoriales) | Lizmap
redes_sum | Contiene insumos disponibles en la categoría temática redes de suministro   (hasta antes de los talleres sectoriales) | Lizmap
sector_energia | Se creo para mostrar los insumos potenciales de ser utilizados en el   taller del sector energía | Lizmap
sociedad | Contiene insumos disponibles en la categoría temática sociedad (hasta   antes de los talleres sectoriales) | Lizmap
transporte | Contiene insumos disponibles en la categoría temática transporte (hasta   antes de los talleres sectoriales) | Lizmap
turismo | Se creo para mostrar los insumos potenciales de ser utilizados en el   taller del sector turismo | Lizmap
vulnerabilidad_acuifero | Contiene insumos disponibles en la categoría temática vulnerabilidad del   acuífero (hasta el 30/09/21) | Lizmap
francisco_bautista | Contiene las capas entregadas por el Dr. Bautista hasta el 30/09/21 | Capas cargadas
riesgos | Contiene los insumos disponibles en la categoría temática riesgos   naturales | Capas con estilos

## Los siguientes proyectos son de Lizmaps **entregables** y que están disponibles en el [visualizador de capas](http://sig.apps.lancis.ecologia.unam.mx/index.php/view/)

Nombre   del proyecto | Descripción | Avance | Ubicación
-- | -- | -- | --
subsistemas_fomix | Proyecto de la entrega 1 (incluye las capas de los tres subsistemas de la   caracterización) | Lizmap | SIG\desarrollo\sig_fomix\mapas\sub_natural
acuacultura | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector acuacultura | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
agricultura | Contiene capas de FV, exclusión, aprovechamiento actual, aptitud y   aptitud integrada del sector agricultura | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
apicultura | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector apicultura | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
areas_conservar_restaurar | Capas utilizadas de insumos y productos del análisis de áreas a   preservar, proteger, restaurar y conservar | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
bovino | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector bovino | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
conservacion | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector conservación | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
energía | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector energía | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
forestal | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector forestal | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
industrial | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector industrial | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
insumos | Capas de insumos utilizados durante los talleres de aptitud | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
milpa | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector milpa maya | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
mineria | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector minería | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
pesca | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector pesca | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
porcino_avicola | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector porcino y avícola | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
turismo | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector turismo | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega
urbano | Capas de FV, exclusión, aprovechamiento actual, aptitud y aptitud   integrada del sector urbano | Lizmap | SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega

**Comment by CorinaCantero** [comment]
### REPORTE DE PLANTILLAS GENERADAS HASTA EL 30/09/21

- En el siguiente archivo se encuentra la base de datos referente a las plantillas creadas hasta el momento: 
Ruta: SIG\desarrollo\sig_fomix\bd_proyectos_plantillas

- En cuanto las composiciones de impresión generadas se crearon dos proyectos en donde se cargaron los insumos para las plantillas del primer y segundo año de FOMIX: 

1. **Primer año: SIG\desarrollo\sig_fomix\mapas\plantillas\plantillas_primer_anio** (Caracterización)
2. **Segundo año: SIG\desarrollo\sig_fomix\mapas\mp_mapas_anio_dos** (vigente)

Independientemente de los proyectos en donde ya están configurados las composiciones de impresión (plantillas_primer_anio y mp_mapas_anio_dos),  el formato general de las mismas puede agregarse a cualquier proyecto nuevo de Qgis por medio de plantillas; `para cargar una plantilla guardada, se debe crear una nueva composición de impresión y desde la pestaña 'Diseño' seleccionar la opción 'Añadir elementos desde plantilla'.`

**Ruta de las plantillas: SIG\desarrollo\sig_fomix\mapas\plantillas**

`NOTA: Si hay dudas es recomendable consultar el 'Manual para la composición de mapas y atlas en QGIS'
`

Nombre plantilla | Uso | Proyecto
-- | -- | --
pl_uno_informe | Plantilla para mapas del año uno | plantillas_primer_anio
pl_dos_datos | Plantilla para mapas del año dos con caja de datos | mp_mapas_anio_dos
pl_dos_datos_regiones | Plantilla para mapas del año dos con caja de datos y regiones | mp_mapas_anio_dos
pl_dos_sin_datos | Plantilla para mapas del año dos sin    caja de datos | mp_mapas_anio_dos
pl_dos_sin_datos_regiones | Plantilla para mapas del año dos sin    caja de datos y con regiones | mp_mapas_anio_dos
pl_fv_continua | Plantilla para funciones de valor continuas | mp_areas_conservar_restaurar
pl_aprov_actual | Talleres de aptitud para hacer mapas de aprovechamiento actual | mp_talleres_aptitud
pl_aptitud | Talleres de aptitud para hacer mapas de aptitud | mp_talleres_aptitud
pl_exclusion | Talleres de aptitud para hacer mapas de exclusión | mp_talleres_aptitud
pl_fv_categorica | Talleres de aptitud para mapas de funciones de valor | mp_talleres_aptitud
pl_atlas_aptitud | Atlas de los mapas de aptitud para imprimir | mp_atlas_aptitud
pl_atlas_costa | Para hacer mapas de la costa de Yucatán con acercamiento | plantillas_primer_anio

----------------------------------------------------------------------------------------------------------------------------------------------
### A continuación se muestran ejemplos de las plantillas: 

### Plantillas informes año uno 

**pl_uno_informe**

![1_3](https://user-images.githubusercontent.com/44783182/135486177-96754563-fffa-48fd-865e-9928fc722c53.jpg)

**pl_atlas_costa** - Genera diez imágenes de la zona costera de Yucatán

![1_12(1)](https://user-images.githubusercontent.com/44783182/135489230-7e6c9bdb-eecf-441e-82c3-1d598638d4b6.jpg)

### Plantillas informes año dos FOMIX

**pl_dos_datos**
![mapa_cobertura_s3](https://user-images.githubusercontent.com/44783182/135368966-21520969-bc1e-4cca-b03a-5d3dcc4877a1.png)

**pl_dos_datos_regiones**
![fragilidad_s3](https://user-images.githubusercontent.com/44783182/135371404-6485fdb2-6013-4234-a390-3bb499e50b6b.png)

**pl_dos_sin_datos**
![usv_s1_s3](https://user-images.githubusercontent.com/44783182/135371495-612ccb7b-b24c-47aa-9d8d-dc109ba5114d.png)

**pl_dos_sin_datos_regiones**
![calidad_recursos_naturales](https://user-images.githubusercontent.com/44783182/135371476-0ed5d6c0-1f24-4f34-8012-e13f71c8ff93.png)

**pl_fv_continua**
![mapa_fv_riqueza_melifera_v2](https://user-images.githubusercontent.com/44783182/135369020-b93a13bc-1dbd-4e07-b8cd-ac3c5262ec60.png)


### Plantillas informe talleres de aptitud sectoriales 

**pl_fv_categorica**
![mapa_fv_ene_ind_sol_cobertura_usv_svi_16cats](https://user-images.githubusercontent.com/44783182/135369758-dcd7dad1-f316-453f-bdfe-ed6da8d8c585.png)

**pl_aptitud**
![mapa_aptitud_biomasa](https://user-images.githubusercontent.com/44783182/135369628-a22dfe8f-d1cb-4267-bb5b-5f4557099ccb.png)

**pl_aprov_actual**
![mapa_aprov_actual_eolica](https://user-images.githubusercontent.com/44783182/135369475-5892fcb0-0272-4872-ba40-c504e079fab2.png)

**pl_exclusion**
![mapa_exclusion_forestal](https://user-images.githubusercontent.com/44783182/135369389-c6f2e25e-4d57-46cf-b49a-b7caf0641250.png)

**pl_atlas_aptitud**
![image](https://user-images.githubusercontent.com/44783182/135370185-df279e90-e071-488b-b08e-2c8cc185c1fe.png)

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue
