### ISSUE TITLE
Generar gráficas y mapas para el análisis de cambio de cobertura e índices asociados #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#31]
**Objetivo:**
Generar gráficas y mapas para el análisis de cambio de cobertura e índices asociados para incluirlos en el informe de caracterización natural de FOMIX.

**Actividades:**

1. Generar gráficas a nivel regional de los tres indicadores asociados al cambio de cobertura: @Nayita 

 a) Gráfica de la tasa de deforestación a nivel regional (%)
 b) Gráfica de cobertura natural/cobertura total a nivel regional (%)
 c) Gráfica extensión de la frontera agrícola a nivel regional (%)

2. Generar mapa de cambio de cobertura utilizando la clasificación del libro Palacios-Prieto, J. L. et al. (2004) Indicadores para la caracterización y ordenamiento del territorio. 1ra edición, Ine.Gob.Mx. 1ra edició. México (pág 40). @CorinaCantero 

**Insumos:**
Ruta: FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\indicadores/
Para gráficas a y b: /usv_c3_reg
Para gráfica c: usv_c4_reg

**Comment by Nayita** [comment]
### Aviso
@CorinaCantero 
Listas las tres gráficas solicitadas. Espero visto bueno.

![gr_cobertura_reg](https://user-images.githubusercontent.com/25210323/82080790-d3308300-96aa-11ea-82ad-a216f0c38d3a.png)

![gr_deforesta_reg](https://user-images.githubusercontent.com/25210323/82080813-dd528180-96aa-11ea-98db-7609a5d6d954.png)

![gr_frontera_agricola](https://user-images.githubusercontent.com/25210323/82080832-e3e0f900-96aa-11ea-98e2-11b0585b7e4a.png)

**Comment by CorinaCantero** [comment]
![image](https://user-images.githubusercontent.com/44783182/82956769-1c1feb80-9f77-11ea-8369-e1b5b55a72fd.png)

**Comment by CorinaCantero** [comment]
### Método para realizar los mapas de cambio de cobertura 

Se elaboraron dos mapas de cambio de cobertura para los periodos de 1985-2002 (SI-SIII) y 2002-2014 (SIII-SVI) de cambio de vegetación y uso del suelo. 

**Método**

Para realizar los mapas de cambio de cobertura 1985-2002 (SI-SIII) y 2002-2014 (SIII-SVI), se utiliza-ron las capas ráster ya preparadas #24. Con la herramienta calculadora ráster se sumaron las dos capas rasterizadas (S1-SIII y SIII-SVI), el ráster resultante se convirtió a una capa vectorial, en la cual se indica el resultado de la suma de ambas series de uso de suelo, según el resultado obtenido se colocó en la tabla de atributos el tipo de uso de suelo o vegetación correspondiente a cada suma para los tiempos 1 y 2. 
Ubicación de capas con sumas: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura\cambio_usv; "rs1_vs_s3_final2" y "s3_vs_s6_final".

Finalmente se categorizó el resultado de las sumas según las transiciones ocurridas en el tiempo, en ocho categorías propuestas por (Palacios-Prieto et al., 2004):

•	Conservada: se refiere a la cobertura vegetal que no ha sufrido cambio en el tiempo.
•	Deforestada: es la superficie que cambió su uso de suelo de formas de vida arbórea (veg. sec. de selva baja y veg. sec. de selva mediana) a zonas de cultivos, pastizales o a otros usos antrópicos como el urbano
•	Revegetada: es la superficie donde anteriormente se llevaba alguna actividad agropecuaria (agricultura, acuícola, pastizales, bosque cultivado/palmar inducido) y actualmente se encuentra ocupada por selva, vegetación hidrófila, tular, sabana o algún otro tipo de cobertura natural.
•	Degradada: es la superficie que presentó cambio en el uso de suelo, pérdida de cobertura vege-tal no arbórea (otros tipos de vegetación, sabana, tular, vegetación hidrófila-hipsófila, etc) por pastizales, cultivos y otras coberturas antrópicas.
•	Por actividad productiva: se refiere a la superficie donde anteriormente se presentaba una co-bertura de origen antrópico como: pastizales, asentamiento humano, o bien formaba parte de un cuerpo de agua, pero actualmente ha cambiado de actividad productiva.
•	Sin cambio: es la superficie de las zonas donde el uso de suelo correspondía a cultivos, pastizales y otros usos, y que actualmente se mantiene en el mismo tipo de uso antrópico.
•	Falso cambio: son aquellos cambios de cobertura que resultan poco probables.
•	Cambio dentro de cobertura natural: son los cambios de cobertura que ocurren dentro de los tipos de cobertura natural.

Ubicación del archivo de Excel con las sumas resultantes y a que cambio de cobertura corresponden: 
FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\claves_cambio_usv.xlsx (Hojas: usvs1_vs_s3 y usvs3_vs_s6)

**Comment by CorinaCantero** [comment]
### AVISO

Gráficas para el análisis de cobertura.

a) Gráfica de tasa de cambio de cobertura (2) a nivel estatal. Ejemplo:
![image](https://user-images.githubusercontent.com/44783182/84714468-5e639980-af33-11ea-85c6-6bd8f97aeee8.png)

b) Gráfica apilada por tipo de cobertura (7 una por región) Ejemplo: 
![image](https://user-images.githubusercontent.com/44783182/84714568-b00c2400-af33-11ea-8f8c-0715866f5c98.png)

En el eje de las x van las seis series de uso de suelo y vegetación, en el eje de las y la coberturas en hectáreas.  Lo que en la imagen dice "Serie I, Serie II" serían los diferentes tipos de cobertura.

Ubicación de la base de datos: 
FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\bd_indicadores\tasas_cambio_coberturas

@Nayita

**Comment by Nayita** [comment]
### Aviso
Listas gráficas de tasa de cambio de cobertura. Ruta:\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\bd_indicadores
Archivos:
gr_tasa_cambio_85-02.png
gr_tasa_cambio_02-14.png

![gr_tasa_cambio_02-14](https://user-images.githubusercontent.com/25210323/85315471-bc870400-b480-11ea-8a99-607fdbb14ba1.png)

![gr_tasa_cambio_85-02](https://user-images.githubusercontent.com/25210323/85315486-c3157b80-b480-11ea-8b27-7412a60983ac.png)

**Comment by Nayita** [comment]
@CorinaCantero 
Listas las graficas de cobertura.
Ruta:\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv\bd_indicadores
Archivos:bd_cobertura_sur.png
bd_cobertura_oriente.png
bd_cobertura_poniente.png
bd_cobertura_noroeste.png
bd_cobertura_noreste.png
bd_cobertura_centro.png
bd_cobertura_litoral.png

Ejemplo

![gr_cobertura_centro](https://user-images.githubusercontent.com/25210323/85354814-fb44aa80-b4d0-11ea-81c3-0e241c017b45.png)

**Comment by CorinaCantero** [comment]
Serie    de Uso de     Suelo y    Vegetación | Tipo de    cobertura | Región     I Poniente | Región     II    Noroeste | Región     III    Centro | Región     IV    Litoral centro | Región     V    Noreste | Región     VI    Oriente | Región     VII Sur
-- | -- | -- | -- | -- | -- | -- | -- | --
Serie I   (1985) | Asentamiento humano | 2,030 | 11,270 | 0 | 3,340 | 0 | 0 | 0
Agropecuario | 45,130 | 111,440 | 54,260 | 102,360 | 308,360 | 20,230 | 38,320
Natural | 399,770 | 254,860 | 206,070 | 188,950 | 475,670 | 1,027,050 | 693,240
Total | 446,930 | 377,570 | 260,330 | 294,660 | 784,030 | 1,047,280 | 731,550
Serie II   (1993) | Asentamiento humano | 8,610 | 25,670 | 1,720 | 6,350 | 6,650 | 4,200 | 4,010
Agropecuario | 80,320 | 92,790 | 45,230 | 114,900 | 392,350 | 71,340 | 89,170
Natural | 358,690 | 259,350 | 213,380 | 173,930 | 385,590 | 972,050 | 638,650
Total | 447,620 | 377,810 | 260,330 | 295,180 | 784,590 | 1,047,590 | 731,840
Serie III   (2002) | Asentamiento humano | 9,100 | 26,380 | 1,890 | 5,320 | 9,190 | 4,360 | 4,010
Agropecuario | 68,640 | 71,510 | 52,550 | 135,750 | 434,720 | 52,380 | 93,620
Natural | 370,890 | 280,760 | 205,890 | 154,190 | 340,680 | 990,850 | 634,200
Total | 448,620 | 378,650 | 260,330 | 295,270 | 784,590 | 1,047,590 | 731,840
Serie IV   (2007) | Asentamiento humano | 12,740 | 43,070 | 2,330 | 6,870 | 8,990 | 5,900 | 4,690
Agropecuario | 70,800 | 64,360 | 58,100 | 150,080 | 457,930 | 82,110 | 107,990
Natural | 365,090 | 271,220 | 199,890 | 138,320 | 317,670 | 959,580 | 619,160
Total | 448,620 | 378,650 | 260,330 | 295,270 | 784,590 | 1,047,590 | 731,840
Serie V   (2011) | Asentamiento humano | 13,420 | 48,970 | 3,110 | 7,500 | 8,970 | 6,900 | 5,380
Agropecuario | 64,870 | 59,030 | 64,690 | 145,980 | 461,940 | 122,530 | 113,610
Natural | 370,340 | 270,660 | 192,530 | 141,800 | 313,780 | 918,150 | 612,840
Total | 448,630 | 378,660 | 260,330 | 295,280 | 784,690 | 1,047,590 | 731,840
Serie VI   (2014) | Asentamiento humano | 14,190 | 56,940 | 3,230 | 7,530 | 9,140 | 8,040 | 5,470
Agropecuario | 62,860 | 52,820 | 70,550 | 142,400 | 483,790 | 276,650 | 140,530
Natural | 371,580 | 268,900 | 186,560 | 145,350 | 291,760 | 762,900 | 585,840
Total | 448,630 | 378,660 | 260,330 | 295,280 | 784,690 | 1,047,590 | 731,840
