### ISSUE TITLE
Procedimiento para la publicación de códigos en el repositorio

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#34]
## Ingresar al repositorio

https://github.com/lancis-apc/fomix/

se muestra el contenido del repositorio en general, hacer clic en la carpeta códigos 

![image](https://user-images.githubusercontent.com/38017509/83785310-bf978d00-a656-11ea-966a-5b4153f55887.png)

## Seleccionar el subsistema

hacer clic en la carpeta que corresponda según el subsistema al que pertenezca el código

![image](https://user-images.githubusercontent.com/38017509/83785582-2157f700-a657-11ea-94f9-e6b305c56ae6.png)

### Hacer clic en el botón **Upload files**

![image](https://user-images.githubusercontent.com/38017509/83786851-9841bf80-a658-11ea-97e7-eca5d83a6fa7.png)

### Seleccionar el archivo

Se muestra la siguiente pantalla,  hacer clic en **choose your files**

![image](https://user-images.githubusercontent.com/38017509/83789408-4ac75180-a65c-11ea-822b-2402626e074f.png)

Se muestra una ventana emergente, navegar hasta la carpeta local que contiene el archivo, seleccionarlo y hacer clic en el botón **Abrir**

`NOTA: Se puede seleccionar dos archivos o más en el mismo paso`

![image](https://user-images.githubusercontent.com/38017509/83789690-b1e50600-a65c-11ea-8d37-a6c398c45136.png)

Para guardar cambios escriba  una descripción corta (máximo 50 caracteres)  en el campo   (1) y una descripción general en el campo (2), hacer clic en el botón ** Commit changes** 

![image](https://user-images.githubusercontent.com/38017509/83792209-54eb4f00-a660-11ea-8ee2-7d18d123e186.png)

Si todo ha salido bien, el código se mostrará en el directorio elegido 

![image](https://user-images.githubusercontent.com/38017509/83792453-b6132280-a660-11ea-9fe4-797cbbf1f3e9.png)

Al hacer clic en el archivo se muestra la contenido, copia la dirección indicada en la barra de direcciones, está dirección será la url que haga referencia al código

https://github.com/lancis-apc/fomix/blob/master/codigos/natural/matriz_transicion.py

![image](https://user-images.githubusercontent.com/38017509/83793262-eb6c4000-a661-11ea-93d0-8f48dde0e0b8.png)

**Comment by vichdzgeo** [comment]
@aaron-ts

**Comment by aleestrada** [comment]
@milocortes @aleestrada 
Por favor hay que seguir este procedimiento para subir los códigos utilizados en la caracterización
