### ISSUE TITLE
Generar índice de calidad de recursos

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#35]
Ruta de trabajo: 
SIG/desarrollo/sig_fomix/procesamiento/indice_calidad/

Ruta de insumos
SIG/desarrollo/sig_fomix/procesamiento/indice_calidad/insumos/

**Comment by paola-gp** [comment]
![image](https://user-images.githubusercontent.com/25205806/84088275-c1908180-a9b1-11ea-9c01-9c32e63544d6.png)

**Comment by vichdzgeo** [comment]
insumo | rango
-- | --
Densidad de arbolado | 68 - 1400
Composición total | 2 - 44
Carbono almacenado | 2.02778 - 50.16204



insumo | campo de interes | valor
-- | -- | --
suelo | GRADO | Ligero     Moderado     Fuerte     Extreno
vulnerabilidad_intrinseca_hidrica | CLASIFIC | Bajo     Medio     Alto     Muy alto     Extremo

@paola-gp

**Comment by paola-gp** [comment]
Factor de progresión para mapa integrado 1.3

**Comment by vichdzgeo** [comment]
## Procedimiento

Se utiliza el script indice_calidad.py para integrar las funciones de valor y utilizar la combinación lineal ponderada para crear el índice, con los pesos especificados anteriormente

## Producto
El producto se encuentra en la ruta 

SIG/desarrollo/sig_fomix/procesamiento/indice_calidad/procesamiento/indice_calidad_recursos.tif
fp 1.3 wf 
![image](https://user-images.githubusercontent.com/38017509/84858112-22fac500-b030-11ea-8b59-916682c535ba.png)


![image](https://user-images.githubusercontent.com/38017509/84858102-1aa28a00-b030-11ea-8c2b-c235e16e4621.png)

**Comment by paola-gp** [comment]
@Nayita

**Comment by vichdzgeo** [comment]
## Actividades

- [ ] Generar una tabla que contenga por región por categoría el área kilómetros cuadrados

- [ ] modificar el mapa, que se visualicen las regiones

**Comment by vichdzgeo** [comment]
@CorinaCantero podrías indicarme el estilo para representar las regiones.

**Comment by vichdzgeo** [comment]
### Producto

se cuantifica el área por categoría por región para el índice de calidad



Categoría | Descripción
-- | --
1 | Muy baja
2 | Baja
3 | Media
4 | Alta
5 | Muy alta



ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_calidad\procesamiento\calidad_recursos_regiones.csv

region | categoria | m2 | km2 | porcentaje_estado
-- | -- | -- | -- | --
1 | 1 | 168870000 | 168.87 | 0.4%
1 | 2 | 555380000 | 555.38 | 1.4%
1 | 3 | 2134470000 | 2134.47 | 5.4%
1 | 4 | 1288450000 | 1288.45 | 3.3%
1 | 5 | 338120000 | 338.12 | 0.9%
2 | 1 | 286550000 | 286.55 | 0.7%
2 | 2 | 730320000 | 730.32 | 1.9%
2 | 3 | 1992690000 | 1992.69 | 5.0%
2 | 4 | 774450000 | 774.45 | 2.0%
2 | 5 | 19890000 | 19.89 | 0.1%
3 | 1 | 24990000 | 24.99 | 0.1%
3 | 2 | 332160000 | 332.16 | 0.8%
3 | 3 | 1403950000 | 1403.95 | 3.6%
3 | 4 | 841510000 | 841.51 | 2.1%
3 | 5 | 760000 | 0.76 | 0.0%
4 | 1 | 110830000 | 110.83 | 0.3%
4 | 2 | 1795050000 | 1795.05 | 4.5%
4 | 3 | 1020170000 | 1020.17 | 2.6%
4 | 4 | 29790000 | 29.79 | 0.1%
5 | 1 | 70000 | 0.07 | 0.0%
5 | 2 | 2665110000 | 2665.11 | 6.7%
5 | 3 | 4124220000 | 4124.22 | 10.4%
5 | 4 | 959350000 | 959.35 | 2.4%
5 | 5 | 11050000 | 11.05 | 0.0%
6 | 1 | 9980000 | 9.98 | 0.0%
6 | 2 | 63300000 | 63.3 | 0.2%
6 | 3 | 4146160000 | 4146.16 | 10.5%
6 | 4 | 5549250000 | 5549.25 | 14.0%
6 | 5 | 706730000 | 706.73 | 1.8%
7 | 1 | 34040000 | 34.04 | 0.1%
7 | 2 | 124770000 | 124.77 | 0.3%
7 | 3 | 1064590000 | 1064.59 | 2.7%
7 | 4 | 2901670000 | 2901.67 | 7.3%
7 | 5 | 3193310000 | 3193.31 | 8.1%

**Comment by Nayita** [comment]
@paola-gp 
Lista la figura de la jerarquía.
Ruta:\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\figuras
Archivo: indice_calidad_recursos.png

![indice_calidad_recursos](https://user-images.githubusercontent.com/25210323/85086726-0df17380-b1a1-11ea-950c-30679ea81dce.png)

**Comment by vichdzgeo** [comment]
@CorinaCantero

El proyecto se encuentra en

SIG\desarrollo\sig_fomix\procesamiento\indice_calidad\indice_calidad.qgs

Instrucciones de importación:

- Abrir el proyecto en qgis 3

- Guardar el proyecto desde qgis en la carpeta de mapas (Dónde están todos los demás)

**Comment by Nayita** [comment]
@paola-gp 

Lista la corrección. Favor de revisar.
Ruta:\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\figuras
Archivo: indice_calidad_recursos.png

![indice_calidad_recursos](https://user-images.githubusercontent.com/25210323/85164718-5b65f300-b22a-11ea-8df8-253bab75e6c4.png)

**Comment by CorinaCantero** [comment]
### Degradación del suelo
@paola-gp 

**Referencia:** Degradación del suelo en la República Mexicana - Escala 1:250 000: SEMARNAT y Colegio de Postgraduados, 2003. 
Ubicación: SIG\desarrollo\sig_fomix\insumos\geocientifica\semarnat\suelos\degradacion_suelo_yuc

**Artículo:**

Evaluación de la degradación del suelo causada por el hombre en la república mexicana, escala 1:250 000. SEMARNAT- Colegio de Postgraduados. 2003.
Ubicación: FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos\degradacion_suelo

"En el presente documento se muestra la información nacional sobre indicadores del estado actual y de la tasa de degradación de los suelos...En particular, se reportan datos sobre erosión hídrica y eólica, así como de la degradación física y química de los suelos, cada una con su superficie y nivel de afectación, e incluye sus principales causas para terrenos agropecuarios y forestales."

**Comment by CorinaCantero** [comment]
### AVISO

Favor de especificar la fuente de los insumos para este índice para poder ponerlo en el mapa, según yo fueron: 

Suelo: Degradación del suelo en la República Mexicana - Escala 1:250 000: SEMARNAT y Colegio de Postgraduados, 2003.
Agua: Batllori Sampedro, E. y Canto Mendiburu, S. (219) 
Vegetación: ?
@paola-gp @vichdzgeo

**Comment by paola-gp** [comment]
Vegetación: CONAFOR. 2014. Inventario Nacional Forestal y de Suelos 2009-2014.

**Comment by CorinaCantero** [comment]
### AVISO

Listo mapa calidad de recursos, ubicación versión texto: \SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto\1_38

![image](https://user-images.githubusercontent.com/44783182/85177692-367d7a00-b242-11ea-8cba-7b62c1dc7860.png)

@paola-gp

**Comment by paola-gp** [comment]
@Nayita y @CorinaCantero: listo informe FOMIX/fmx_estudio_tecnico/caracterizacion_subs/procesamiento/sub_natural/calidad_recursos

**Comment by vichdzgeo** [comment]
## Insumos de la vulnerabilidad intrínseca del agua


Variables | Nombre del archivo | Campo | Unidades | categorias | fuente
-- | -- | -- | -- | -- | --
Nivel freático | POLIGONO_NIVEL_FREATICO | N_FREAT_M | metros ? | NA | POETY 2007
Densidad de Dolinas | DENSIDAD DE DOLINAS | Grado | Adimensional | Muy bajo     Bajo     Medio     Alto     Muy alto | ATLAS DE PRELIGROS 2013
Presencia de Cenotes | Buffer100mtrscenotes_Dissolv2 |   | presencia |   | SEDUMA 2018
Fallas y fracturas | LINEAMIENTOS ESTRUCTURALES |   | presencia |   | ATLAS DE PRELIGROS 2013
Unidad   cronoestratigráfica, Geología (tipo de roca) | GEOLOGIA_POETY2007_SELVAMAYA_MOD_DRBATLLORI | CRONOLOGIA | Adimensional | Cuaternario     Eoceno     Terciario | ATLAS DE PRELIGROS 2013
Gravimetría conductividad   hidráulica | conductividad_hidraulica | CAT | Adimensional | Muy bajo     Muy alto | ARELLANO CATALAN O.2017
Imagen gravimetría, densidad   de la roca | Poligonos_gravimetría_DISOLVE_final | GRADO VUL | Adimensional | Alto     Muy Alto     Maximo     Extremo | ARELLANO CATALAN O.2017
Dureza del agua | no hay archivo | -- | -- | -- | --
Topografía | no hay archivo | -- | -- | -- | --
Espesor del suelo | ESPESOR DE SUELOS | GRADO | Adimensional | Muy bajo     bajo     Medio     Alto     Muy alto | ATLAS DE PRELIGROS 2013
Tipo de suelo | EDAFOLOGÍA_DISOLVE | DISOLVE |   |   | POETY 2007
Uso y tipo de vegetación | vegetacion_vul_2 | DESCRIPCIO |   |   | INEGI SERIE VI
Humedad   Promedio (meses) del suelo | poligonos_humedad_DIS | SIMBOLOGIA | meses |   | CONABIO 2002 ?
Precipitación Acumulada anual   (mm) | PRECIPITACION_MEDIA_ANUAL_RANGO | PRECIP_MEDIA | mm |   | ATLAS DE PRELIGROS 2013
Tipo de Clima | CLIMAS | MAX MIN |   |   | ATLAS DE PRELIGROS 2013
Variación de Temperatura | TEMMAX-TEMMIN |   | C° |   | ATLAS DE PRELIGROS 2013
Evapotranspiración | evapotranspiración_yuc_conabio | RANGO | mm (las isolíneas tienen valores   desde >100 mm a >1200 mm divididas cada 100 mm) | CONABIO 2002
