### ISSUE TITLE
Generar índice de riesgo a eventos naturales

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#36]
presencia de fenómenos geomorfohidrológicos (ciclones, huracanes, inundaciones, heladas, sequías, granizadas, y otros)..

**Comment by vichdzgeo** [comment]
insumo | campo de interés | valor | campo de interés | valor | Observaciones
-- | -- | -- | -- | -- | --
Ciclones | R_CICTRO | 0.01839 - 1.43697 | RCLA_CICTR |  Muy bajo     Bajo     Medio     Alto     Muy alto |  
Granizo | R_Gra | 0 - 0.17424 | Rcla_Gra | Muy bajo |  
Inundación | Porcenta_1 | 1.094743 - 26.956886999999998 | Peligro_IN | Muy bajo     Bajo     Medio     Alto     Muy alto | Porcenta_1 representa  el área   inundable entre el área total del municipio *100
Sequía | R_SEQUIA | 0.138 - 0.972 | RCLA_SEQ | Muy bajo     Bajo     Medio |  

@paola-gp

**Comment by paola-gp** [comment]
![image](https://user-images.githubusercontent.com/25205806/84088184-99a11e00-a9b1-11ea-89c8-ca715b4731fe.png)

**Comment by vichdzgeo** [comment]
## Procedimiento 

Para la creación del índice se llevan a ideales los insumos para generar las funciones de valor, estas se integran utilizando la combinación lineal ponderada con los respectivos pesos descritos en el diagrama.

Para la integración y generación del índice se crea el script indice_riesgo.py 

## Producto
ruta: 

SIG/desarrollo/sig_fomix/procesamiento/indice_riesgo/procesamiento/indice_calidad_riesgo_eventos_nat.tif'

![image](https://user-images.githubusercontent.com/38017509/84858538-014e0d80-b031-11ea-85e3-603a4b463f53.png)

![image](https://user-images.githubusercontent.com/38017509/84858525-fb582c80-b030-11ea-8172-e8e96bd38e76.png)

**Comment by paola-gp** [comment]
@Nayita

**Comment by CorinaCantero** [comment]
### AVISO

Nombre insumo | Fuente | Año | Página web
-- | -- | -- | --
Grado de riesgo por ciclones tropicales   hasta 2015 | CENAPRED | 2015 | http://www.atlasnacionalderiesgos.gob.mx/archivo/visor-capas.html
Grado de riesgo por granizo por municipio | CENAPRED | 2012 | Geoportal CONABIO
Indice de peligro por inundación | CENAPRED | 2016 | http://www.atlasnacionalderiesgos.gob.mx/archivo/visor-capas.html
Grado de riesgo por sequías por municipio | CENAPRED | 2012 | http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/d5c4fa2a-1b24-4274-a9cb-3f25d3b7b3a7

**Comment by CorinaCantero** [comment]
## Definiciones 
@paola-gp 

**Capas del Atlas Nacional de Riesgo**
- Grado de riesgo por ciclones tropicales hasta 2015
"Es importante recalcar que el riesgo mostrado sería el relacionado con los efectos directos
de los ciclones: viento, oleaje, marea de tormenta y lluvia, aunque el impacto de este último podría sentirse más allá de las zonas costeras, afectando estados que ni siquiera tienen costas. Además, la lluvia generaría otro tipo de peligros, como deslizamientos, inundaciones, flujos de escombros, avenidas repentinas, etc."
- Grado de riesgo por sequías por municipio
"Hay que recordar que el riesgo es la combinación del fenómeno natural, escases de agua, con la exposición y la vulnerabilidad."

Insumo (texto): "Mapas de índices de riesgo a escala municipal por fenómenos hidrometeorológicos" Revisar sección de obtención de mapas de riesgo a escala municipal.
\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos\mapas_indices_riesgo_hidro

- Grado de riesgo por granizo por municipio
"El mapa muestra el grado de riesgo por granizo por municipio en México a escala 1:200000. El grado de riesgo se obtuvo considerando el logaritmo natural de la densidad de población más tres (Ln[D)+3) por municipio y de acuerdo al censo 2010, el índice de vulnerabilidad social (IVS) y el índice de peligro por tormentas de granizo."
"Procedimiento:
 1. Se realizó la descarga de información a través de la página del Atlas Nacional de Riesgos del CENAPRED http://www.atlasnacionalderiesgos.gob.mx/index.php/biblioteca/category/17-hidrometeorologicos, esta se encontraba de origen en formato shapefile. 2. Se hizo una revisión de la información en el Sistema de Información Geográfica ArcGis Desktop con la aplicación de Arcmap, versión 10.2. para analizar su contenido. 3. Se renombró el shapefile como rgranizogw. 4. En el mismo programa, se cambió el sistema de referencia, de proyección Cónica Conforme de Lambert a Coordenadas Geográficas con datum WGS84. Para mayor información con respecto a la metodología consultar los siguientes documentos: -Mapas de índices de riesgo a escala municipal por fenómenos hidrometeorológicos. -Guía básica para la elaboración de atlas estatales y municipales de peligros y riesgos (fenómenos hidrometeorológicos). http://www.atlasnacionalderiesgos.gob.mx/index.php/biblioteca/category/9-iii-riesgos-hidrometeorologicos"

- Grado de riesgo por sequías por municipio
"El mapa muestra los grados de sequía por municipio en México a escala 1:200000. El grado de riesgo se obtuvo considerando el logaritmo natural de la densidad de población más tres (Ln[D)+3) por municipio y de acuerdo al censo 2010, el índice de vulnerabilidad social (IVS) y el índice de peligro por sequías."
"Procedimiento: 1. Se realizó la descarga de información a través de la página del Atlas Nacional de Riesgos del CENAPRED http://www.atlasnacionalderiesgos.gob.mx/index.php/biblioteca/category/17-hidrometeorologicos, esta se encontraba de origen en formato shapefile. 2. Se hizo una revisión de la información en el Sistema de Información Geográfica ArcGis Desktop con la aplicación de Arcmap, versión 10.2. para analizar su contenido. 3. Se renombró el shapefile como rsequiasgw. 4. En el mismo programa, se cambió el sistema de referencia, de proyección Cónica Conforme de Lambert a Coordenadas Geográficas con datum WGS84. Para mayor información con respecto a la metodología consultar los siguientes documentos: -Mapas de índices de riesgo a escala municipal por fenómenos hidrometeorológicos. -Guía básica para la elaboración de atlas estatales y municipales de peligros y riesgos (fenómenos hidrometeorológicos). http://www.atlasnacionalderiesgos.gob.mx/index.php/biblioteca/category/9-iii-riesgos-hidrometeorologicos "

**Comment by Nayita** [comment]
@paola-gp 
Lista figura de la jerarquía
Ruta:\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\figuras
Archivo: indice_r_eventos_natural

![indice_r_eventos_natural](https://user-images.githubusercontent.com/25210323/85084488-87d22e80-b19a-11ea-92f1-5685752f4808.png)

**Comment by vichdzgeo** [comment]
## Producto

ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_riesgo\procesamiento\regiones_riesgo_eventos_naturales.csv

se cuantifica el área por categoría por región para el índice de riesgo a eventos naturales


categoria | descripción
-- | --
1 | Muy Bajo
2 | Bajo
3 | Medio
4 | Alto
5 | Muy Alto




region | categoria | m2 | ha | porcentaje_area_total
-- | -- | -- | -- | --
1 | 1 | 810670000 | 81070 | 2.05%
1 | 2 | 2005840000 | 200580 | 5.07%
1 | 3 | 1688160000 | 168820 | 4.27%
2 | 1 | 63430000 | 6340 | 0.16%
2 | 2 | 708180000 | 70820 | 1.79%
2 | 3 | 2428090000 | 242810 | 6.14%
2 | 4 | 605010000 | 60500 | 1.53%
3 | 3 | 1204740000 | 120470 | 3.05%
3 | 4 | 1398630000 | 139860 | 3.54%
4 | 2 | 786250000 | 78630 | 1.99%
4 | 3 | 1385140000 | 138510 | 3.50%
4 | 4 | 791700000 | 79170 | 2.00%
5 | 1 | 452110000 | 45210 | 1.14%
5 | 2 | 665090000 | 66510 | 1.68%
5 | 3 | 1534280000 | 153430 | 3.88%
5 | 4 | 5215490000 | 521550 | 13.19%
6 | 2 | 356320000 | 35630 | 0.90%
6 | 3 | 997260000 | 99730 | 2.52%
6 | 4 | 6459030000 | 645900 | 16.34%
6 | 5 | 2662810000 | 266280 | 6.74%
7 | 3 | 4910130000 | 491010 | 12.42%
7 | 4 | 2408250000 | 240830 | 6.09%

**Comment by vichdzgeo** [comment]
@CorinaCantero 

El proyecto se encuentra en 

SIG\desarrollo\sig_fomix\procesamiento\indice_riesgo\indice_riesgos_a_eventos_nat.qgs

Instrucciones de importación:

- Abrir el proyecto en qgis 3

- Guardar el proyecto desde qgis en la carpeta de mapas (Dónde están todos los demás)

**Comment by CorinaCantero** [comment]
### AVISO

Listos mapas índice de riesgo a eventos naturales, ubicación mapa versión texto:
\SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto\1_11

![image](https://user-images.githubusercontent.com/44783182/85171485-bb619700-b234-11ea-8df2-30eb68a0424d.png)

**Comment by paola-gp** [comment]
@Nayita @CorinaCantero listo: /FOMIX/fmx_estudio_tecnico/caracterizacion_subs/procesamiento/sub_natural/riesgo_enatural

**Comment by paola-gp** [comment]
@Nayita @CorinaCantero actualizado informe:

/FOMIX/fmx_estudio_tecnico/caracterizacion_subs/procesamiento/sub_natural/riesgo_enatural
