### ISSUE TITLE
Actualizar informe de vulnerabilidad costera de Yucatán 

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#37]

**Comment by Nayita** [comment]
### Actividades

- [ ] Integrar imágenes de jerarquías al informe.

- [ ] Elaborar tabla de capas que se utilizaron para hacer el análisis de vulnerabilidad

Ruta de los productos: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs

**Comment by Nayita** [comment]
@vichdzgeo 
Favor de indicarme dónde puedo ver las superficies por regiones del mapa de vulnerabilidad costera

**Comment by vichdzgeo** [comment]
## Producto
Ruta: SIG\desarrollo\sig_fomix\procesamiento\vulnerabilidad_costera\regiones_vulnerabilidad_costera_ha.csv

categoria | Descripción
-- | --
1 | Muy Baja
2 | Baja
3 | Media
4 | Alta
5 | Muy Alta




region | categoria | m2 | ha
-- | -- | -- | --
1 | 2 | 2810000 | 280
1 | 3 | 100780000 | 10080
1 | 4 | 26810000 | 2680
1 | 5 | 89610000 | 8960
2 | 1 | 110000 | 10
2 | 2 | 900000 | 90
2 | 3 | 33230000 | 3320
2 | 4 | 26590000 | 2660
2 | 5 | 77370000 | 7740
4 | 1 | 180000 | 20
4 | 2 | 37410000 | 3740
4 | 3 | 102230000 | 10220
4 | 4 | 50200000 | 5020
4 | 5 | 117260000 | 11730
5 | 1 | 1080000 | 110
5 | 2 | 24830000 | 2480
5 | 3 | 83170000 | 8320
5 | 4 | 54290000 | 5430
5 | 5 | 156600000 | 15660

**Comment by vichdzgeo** [comment]
@CorinaCantero 

El proyecto se encuentra en 

SIG\desarrollo\sig_fomix\procesamiento\vulnerabilidad_costera\vulnerabilidad_costera_yuc.qgs

Instrucciones de importación:

- Abrir el proyecto en qgis 3

- Guardar el proyecto desde qgis en la carpeta de mapas (Dónde están todos los demás) con el nombre que le corresponde para FOMIX

**Comment by CorinaCantero** [comment]
### AVISO

Listos los mapas de vulnerabilidad costera a eventos naturales. Ubicación:
SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto

Son 10 mapas: del 1_12(1) al 1_12(10)
@Nayita 

![image](https://user-images.githubusercontent.com/44783182/85185547-f6c28c80-b259-11ea-84f5-2a6cc8de7b5b.png)

**Comment by Nayita** [comment]
@vichdzgeo 
Favor de indicar dónde encuentro el modelo AHP para los criterios de Exposición, Susceptibilidad y Resiliencia.

Se encontró este esquema pero le falta el criterio Resiliencia.

![vulnerabilidad_costera_v2](https://user-images.githubusercontent.com/25210323/85813185-25dc7080-b728-11ea-8e78-1995f0cd4ff3.png)

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
