### ISSUE TITLE
Generar índice de fragilidad del territorio

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#38]
![image](https://user-images.githubusercontent.com/38017509/84931886-0f377900-b099-11ea-98e6-678f21d4049a.png)

**Comment by vichdzgeo** [comment]
## Procedimiento

Ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_fragilidad_del_territorio

Se utiliza el código indice_frag_territorio.py  utilizar Qgis 3.10 o superior. 

1. se crean las funciones de valor a partir de los insumos

1. Se construye el índice a partir de las funciones de valor utilizando la combinación lineal ponderada, los pesos asignados son los siguientes

 |variable | peso | ruta |
 |---|---|---|
 |fv_area| 0.10| procesamiento/fv_serie#_area.tif|
 |fv_dimension_fractal|0.20| procesamiento/fv_serie#_dimension_fractal.tif|
 | fv_tamano_parche | 0.35|procesamiento/fv_serie#_tamano_parche.tif|
 | fv_numero_de_parches| 0.35| procesamiento/fv_serie#_numero_de_parches.tif'

3. se crea la capa que representa el índice-> procesamiento/serie#_indice_fragilidad.tif

el símbolo # representa el número de serie.

**Comment by vichdzgeo** [comment]
## Prodicto

Ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_fragilidad_del_territorio

1.  la capa que representa el índice se encuentra en -> procesamiento/serie#_indice_fragilidad.tif

**Comment by vichdzgeo** [comment]
## Actividad

Calcular el valor promedio de la capa de índice de la serie 6 y la serie 3 para cada clase en cada región.

Las clases consideradas son: Natural, Urbano y Agropecuario

ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_fragilidad_del_territorio\procesamiento\promedios__indice_series_region_c4.xlsx


region | clase | nom_clase | mean_serie3 | mean_serie6
-- | -- | -- | -- | --
1 | 1 | urbano | 0.65268599 | 0.67276753
1 | 2 | Agropecuario | 0.73856718 | 0.68583075
1 | 3 | Natural | 0.56498985 | 0.41379999
2 | 1 | urbano | 0.72895977 | 0.72914894
2 | 2 | Agropecuario | 0.83494532 | 0.72956795
2 | 3 | Natural | 0.55751058 | 0.52617752
3 | 1 | urbano | 0.67895943 | 0.66768969
3 | 3 | Natural | 0.61444629 | 0.53888637
3 | 2 | Agropecuario | 0.7345723 | 0.72814308
4 | 3 | Natural | 0.67254129 | 0.64720922
4 | 1 | urbano | 0.6744601 | 0.66265123
4 | 2 | Agropecuario | 0.75094429 | 0.70844695
5 | 3 | Natural | 0.74645768 | 0.735535
5 | 2 | Agropecuario | 0.81684245 | 0.75057478
5 | 1 | urbano | 0.67629094 | 0.65809845
6 | 1 | urbano | 0.7652036 | 0.73492553
6 | 2 | Agropecuario | 0.88936928 | 0.87632456
6 | 3 | Natural | 0.22474128 | 0.393068
7 | 1 | urbano | 0.69477165 | 0.67235521
7 | 2 | Agropecuario | 0.80027504 | 0.79743136
7 | 3 | Natural | 0.4221239 | 0.46635415

**Comment by paola-gp** [comment]
@Nayita

**Comment by Nayita** [comment]
@paola-gp 
Lista figura de jerarquía.
Ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\figuras
Archivo: indice_fragilidad.png

**Comment by vichdzgeo** [comment]
## MAPAS

@CorinaCantero

Los proyectos se encuentran en

SIG\desarrollo\sig_fomix\procesamiento\\indice_fragilidad_del_territorio\

- fragilidad_territorio_serie3.qgs
- fragilidad_territorio_serie6.qgs

NOTA:
En lugar de colocar la serie en el nombre del mapa se coloca el año representativo para la serie.


Instrucciones de importación:

Abrir el proyecto en qgis 3

Guardar el proyecto desde qgis en la carpeta de mapas (Dónde están todos los demás)

**Comment by CorinaCantero** [comment]
### AVISO

Listos los mapas de fragilidad del territorio, ubicación de la versión atlas:

\SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto

1_39a Fragilidad del territorio, 2002
1_39b Fragilidad del territorio, 2014

@paola-gp @vichdzgeo @BioloArturo

**Comment by vichdzgeo** [comment]
@CorinaCantero @paola-gp seria más adecuado colocar en el nombre de la simbología el año?

**Comment by vichdzgeo** [comment]
variable | serie 3 | serie 6
-- | -- | --
  | min | max | min | max
area_mn | 2.308 | 65,957.867 | 2.154 | 33,825.500
area_frag | 26.790 | 989,356.938 | 26.473 | 761,522.562
frac_mn | 1.005 | 1.118 | 1.007 | 1.159
np | 1.000 | 73.000 | 1.000 | 125.000

**Comment by vichdzgeo** [comment]
## Actualización 

ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_fragilidad_del_territorio\procesamiento\

@CorinaCantero 

Favor de actualizar los mapas de fragilidad con las siguientes capas resultantes

Fragilidad para la serie3
- serie3_fragilidad_n_wf_1_4.tif

Fragilidad para la serie6

- serie6_fragilidad_n_wf_1_4.tif

@paola-gp 

Las bases de datos del área por categoría por región se encuentran en : 
ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_fragilidad_del_territorio\procesamiento\
y son: 

- db_promedios_region_clase_serie3.csv
- db_promedios_region_clase_serie6.csv

el redondeo que se aplico a los km² fue de 0.1 (correspondiente a 10 ha)

**Comment by CorinaCantero** [comment]
### AVISO

Ya están listos los mapas de fragilidad con correcciones.
Ubicación: \SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto

1_39a Fragilidad del territorio, 2002
1_39b Fragilidad del territorio, 2014

@paola-gp @vichdzgeo

**Comment by paola-gp** [comment]
@Nayita y @CorinaCantero listo informe:
/FOMIX/fmx_estudio_tecnico/caracterizacion_subs/procesamiento/sub_natural/fragilidad
