### ISSUE TITLE
Generar índice de habitabilidad

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#39]

**Comment by CorinaCantero** [comment]
### Insumos
Ubicación:
Rangos de humedad: SIG\desarrollo\sig_fomix\insumos\amc\unam\rangos_humedad
Regímenes de humedad del suelo: SIG\desarrollo\sig_becarios\procesamiento\tematicos_yucatan\salida\recortes_utm16\reg_humedad_suelo_yuc

Temperatura promedio anual: SIG\insumos\amc\conabio\vector\temp_medanual

**Comment by vichdzgeo** [comment]
## Aviso

### Temperatura máxima absoluta 
representan isotermas que van de 28°C a 38°C

### Temperatura máxima promedio

Representan zonas que van de un rango mínimo de 30°C a 32° C a un rango máximo de 36°C a 38°C

@paola-gp

**Comment by paola-gp** [comment]
Por instrucciones de Luis no se entrega este índice en la primera entrega.
