### ISSUE TITLE
Elaborar encuestas para el diagnóstico de capacidades institucionales de #FOMIX

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#4]
La ubicación de esta actividad se encuentran en: /FOMIX/fmx_diag_insti

**Comment by paola-gp** [comment]
Reactivos desarrollados: @dpedroza74  

- [ ]  fomix_diagnostico_recursos_computo.docx contiene los 20 reactivos de hardware, sofware e internet. @paola-gp 

- [ ] fomix_diagnostico_recursos_equipamiento.docx  @paola-gp 

- [ ] fomix_diagnostico_recursos_capacidades_tecnicas.docx @paola-gp

**Comment by dpedroza74** [comment]
Desarrollé preguntas sobre la formación, experiencia y capacidades del personal, sobre sus funciones y actividades y sobre el equipo de cómputo que tienen asignado para realizar sus actividades (con base en los reactivos proporcionados por Paola). La lista de preguntas están en el archivo fomix_encuesta_diag_rec_hum_computo_ SDS.xlsx que está en:  /FOMIX/fmx_diag_insti/encuestas

Éstas se subieron a la plataforma Surveymonkey y se envió la liga a la lista de funcionarios proporcionada por la SDS. Los funcionarios respondieron de manera directa el cuestionario, ya sea en la plataforma Surveymonkey o en un formato de Excel.  

Se recibieron 4 encuestas en Excel que están en /FOMIX/fmx_diag_insti/encuestas y las recibidas en la plataforma están en el documento diagnostico_recursos_humanos_materiales_9ene.xlsx

Todas las encuestas se juntaron en el documento: Diagnóstico recursos humanos y materiales_analisis_ene9.xlsx
En este archivo de trabajo hice los análisis que incluí en el reporte: fomix_reporte_encuestas.docx
