### ISSUE TITLE
Definir los estilos cartográficos

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#40]
# Límites

**Comment by CorinaCantero** [comment]
## **Estilo para regiones:** 
es_regiones
Ubicación: SIG\desarrollo\sig_fomix\mapas\estilos
Tipo de capa del símbolo: relleno sencillo 
Color de relleno: transparente
Color de marca: negro #000000
Anchura de marca: 0.20

### Etiquetas regiones
Etiquetar con: no.región
**Texto**
Tipo de letra: MS Shell DLG 2
Estilo: Normal 
Tamaño: 10
Color: negro #000000
Buffer: Dibujar buffer de texto
Tamaño: 1 mm
Color: blanco #ffffff
Ubicación 
Alrededor de centroide
Centroide: Polígono visible 
Distancia: 0.0 

## Estilo para municipios
es_municipios, ubicación:
SIG\desarrollo\sig_fomix\mapas\estilos

No llevan etiqueta 


**Ejemplo:**
![Uploading image.png…]()

@vichdzgeo
