### ISSUE TITLE
Generar mapas de síntesis 

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#41]
## Insumos

- Capa de municipios

- Capa normalizada de fragilidad para el año 2014

- Capa de calidad de recursos naturales

## Objetivo

tener un valor promedio de calidad de recursos y de fragilidad por municipio 

## Producto

SIG\desarrollo\sig_fomix\procesamiento\sintesis\salida\bd_sistesis_mun_calidad_fragilidad_yuc.csv

cve_mun: corresponde a la clave municipal 
calidad: corresponde al valor promedio de los píxeles de la capa de calidad de recursos naturales para el municipio.
fragilidad: corresponde al valor promedio de los píxeles de la capa de fragilidad para el año 2014.

@paola-gp

**Comment by vichdzgeo** [comment]
## Procesamiento

- [ ] Relacionar con la capa vectorial de municipios la base de datos `sistesis_mun_calidad_fragilidad.xls` de clusters

## Producto

ruta: 

SIG\desarrollo\sig_fomix\procesamiento\sintesis\salida\sintesis_sistema_natural.shp

@CorinaCantero  capa lista para realizar el mapa

**Comment by CorinaCantero** [comment]
### AVISO

Listo el mapa síntesis del subsistema natural @paola-gp 
Ubicación: 
\SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto\1_40

**Comment by paola-gp** [comment]
@Nayita y @CorinaCantero: listo informe en /fmx_estudio_tecnico/caracterizacion_subs/procesamiento/sub_natural/sintesis

**Comment by vichdzgeo** [comment]
# Producto 
## subsistema socioeconómico
ruta:

SIG\desarrollo\sig_fomix\procesamiento\sintesis\salida\sintesis_sistema_socioeconomico.shp

@CorinaCantero capa lista para realizar el mapa
