### ISSUE TITLE
Integrar informe final año 1 

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#43]
@aleestrada @CorinaCantero @dpedroza74 @ofegarcia @vichdzgeo @serranoycandela 
#### Todas las entregas deberán estar ubicadas en FOMIX/fmx_estudio_tecnico/entregas con base en los siguientes lineamientos:

#####1. Archivos originales de informes, anexos metodológicos y documentos que originalmente estén en formato word en **/word**

#####2. Archivos de word con base en la plantilla con el índice y referencias actualizadas. 

#####3. Bases de datos y otros documentos afines en formato excel favor de: (1) agregarlos a **/excel** o (2) reportar por este medio la ubicación del insumo.

#####4. Todas las bases de datos deben incluir su diccionario de datos.  

#####5.  Archivos provenientes de cualquier otro formato convertirlos a pdf y ubicarlos en **/pdf**

#####6. Una vez generadas las ligas no se podrán eliminar o modificar los nombres de los archivos, solo sobrescribir. Seguir la tabla siguiente para el nombramiento.  Si agregan archivos adicionales avisar a @Nayita:

Nombre de sección | Nombre del   entregable | Responsable
-- | -- | --
#1. Diagnóstico para   la gestión del ordenamiento ecológico del territorio. | diagnostico_1.docx | Daniela
#2. Estrategia de fortalecimiento en materia de ordenamiento   ecológico. | estrategia_2.docx | Daniela
#3. Estudio técnico para la actualización del POETY- Etapa de   caracterización |  
#3.1 Subsistema   natural | subsistema_natural_3_1.docx | Corina
#3.2 Subsistema   Productivo | subsistema_productivo_3_2.docx | Daniela y Ale
#3.3 Subsistema Socioeconómico | subsistema_socioeconomico_3_3.docx | Ofelia
#4. Proyecto del sistema |   |  
#4.1 Identificar las   necesidades del usuario y otros beneficiarios | sistema_necesidades_usuario_4_1.docx | Daniela
#4.2 Desarrollar el diseño y arquitectura del sistema de gestión | diseno_sistema_4_2.docx | Fidel
#5. Anexos |   |  
#1.Diagnóstico para   la gestión OE |   |  
#1.1      Métodos | anexo_diagnostico_metodo_1_1 | Daniela
#1.2      Documentos   y bases de datos | anexo_diagnostico_documentacion_1_2_1.docx | Daniela
  | anexo_diagnostico_documentacion_1_2_2.xlsx | Daniela
  | anexo_diagnostico_documentacion_1_2_3.xlsx | Daniela
  | anexo_diagnostico_documentacion_1_2_4.xlsx | Daniela
#2.Estrategia |   |  
#2.1      Métodos | anexo_estrategia_metodo_2_1.docx | Daniela
#2.2      Documentos   y bases de datos | anexo_estrategia_documentacion_2_2 | Daniela
  | 12? |  
#3.Caracterización   Subsistema Natural |   | Corina
#3.1. Métodos | anexo_sub_natural_metodo_3_1.docx | Corina
#3.2. Documentos y   bases de datos | anexo_sub_natural_documentacion_3_2 | Corina
#4. Caracterización   Subsistema Productivo |   | Alejandra
#4.1. Métodos | anexo_sub_productivo_metodo_4_1.docx | Alejandra
#4.2. Documentos y   bases de datos | anexo_sub_productivo_documentacion_4_2 | Alejandra
#5. Caracterización   Subsistema Socioeconómico |   |  
#5.1 Métodos | anexo_sub_socioeconomico_metodo_5_1.docx | Ofelia
#5.2 Documentación y   bases de datos | anexo_sub_socioeconomico_documentacion_5_2 | Ofelia
  | 7? |  
#6. Scripts |   |  
#6.1 Subsistema   natural | https://github.com/lancis-apc/fomix/tree/master/codigos/natural | Víctor
#6.2 Subsistema   productivo | https://github.com/lancis-apc/fomix/tree/master/codigos/productivo | Víctor
#6.3 Subsistema socio-económico | https://github.com/lancis-apc/fomix/tree/master/codigos/socioeconomico | Víctor
#6.4 Sistema de gestión de bases de datos | Liga | Aarón
#7. Visualizador de mapas | Liga | Víctor

**Comment by CorinaCantero** [comment]
### AVISO

URL de la página web para la primera entrega FOMIX: https://lancisapc.wixsite.com/fomixpoety

**Comment by dpedroza74** [comment]
@Nayita 
Ya subí al dropbox todo lo del capítulo 1 diagnostico

Carpeta word:
diagnostico_1
anexo_diagnostico_1_metodo 
anexo_diagnostico_1_documentacion

Carpeta excel:
anexo_diagnostico_documentacion_1_2_2_1
anexo_diagnostico_documentacion_1_2_6_1          
anexo_diagnostico_documentacion_1_2_6_2          
anexo_diagnostico_documentacion_1_2_6_3  

Carpeta pdf:
anexo_diagnostico_documentacion_1_2_5_1          
anexo_diagnostico_documentacion_1_2_5_2          
anexo_diagnostico_documentacion_1_2_5_3

**Comment by paola-gp** [comment]
@aleestrada, @CorinaCantero @ofegarcia @dpedroza74 

#### Entrega de bases de datos en la sección de documentación

1. Para simplificar el número de archivos y que las bases de datos estén completas, agregar el diccionario de datos en una hoja que diga diccionario. Si no citaron la fuente completa de la base de datos en el documento principal, poner la fuente completa en el diccionario. 
2. Favor de referirse a las bases de datos y otros archivos de documentación en el documento principal, para que el lector sepa donde encontrarlas y a qué se refieren esos archivos.

**Comment by CorinaCantero** [comment]
@Nayita 
Listos documentos en la carpeta de entrega del subsistema natural 

Carpeta word: 
subsistema_natural_3_1_v1
anexo_sub_natural_metodo_3_1
anexo_sub_natural_documentacion_3_2

Carpeta pdf:
subsistema_natural_3_1
anexo_sub_natural_metodo_3_1
anexo_sub_natural_documentacion_3_2

Carpeta excel: 
FOMIX\fmx_estudio_tecnico\entregas\excel\capitulo_5\sub_natural

Carpeta zip: 
anexo_sub_natural_documentacion_3_2

Nota: ya se corrigió el URL para la carpeta zip y se agregó a la página web.

**Comment by Nayita** [comment]
### Actualización de los documentos que conforman la página web

- [ ]  Diagnóstico para   la gestión del ordenamiento ecológico del territorio. diagnostico_1.docx 

- [ ]  Estrategia de fortalecimiento en materia de ordenamiento   ecológico. estrategia_2.docx 

Estudio técnico para la actualización del POETY- Etapa de   caracterización   

- [ ] Subsistema   natural.  subsistema_natural_3_1.docx 

- [ ] Subsistema   Productivo. subsistema_productivo_3_2.docx 

- [ ] Subsistema Socioeconómico. subsistema_socioeconomico_3_3.docx 

Proyecto del sistema  

- [ ] Necesidades del usuario y otros beneficiarios. sistema_necesidades_usuario_4_1.docx 

- [ ] Diseño y arquitectura del sistema de gestión. diseno_sistema_4_2.docx 

 Anexos   
Diagnóstico para la gestión OE 

- [ ] 1.1 Métodos. anexo_diagnostico_metodo_1_1.docx 

- [ ] 1.2 Documentos y bases de datos. anexo_diagnostico_documentacion_1_2_1.docx,  
Carpeta excel:
anexo_diagnostico_documentacion_1_2_2_1
anexo_diagnostico_documentacion_1_2_6_1
anexo_diagnostico_documentacion_1_2_6_2
anexo_diagnostico_documentacion_1_2_6_3

Carpeta pdf:
anexo_diagnostico_documentacion_1_2_5_1
anexo_diagnostico_documentacion_1_2_5_2
anexo_diagnostico_documentacion_1_2_5_3

Estrategia  

- [ ] 2.1 Métodos. anexo_estrategia_metodo_2_1.docx 

- [ ] 2.2 Documentos y bases de datos. anexo_estrategia_documentacion_2_2 
 
Caracterización   Subsistema Natural 

- [ ] 3.1. Métodos. anexo_sub_natural_metodo_3_1.docx 

- [ ] 3.2. Documentos y bases de datos. anexo_sub_natural_documentacion_3_2.docx
Bases de datos. Carpeta excel: 
FOMIX\fmx_estudio_tecnico\entregas\excel\capitulo_5\sub_natural 

Caracterización   Subsistema Productivo 

- [ ] 4.1. Métodos. anexo_sub_productivo_metodo_4_1.docx 

- [ ] Documentos y   bases de datos. anexo_sub_productivo_documentacion_4_2 

Caracterización   Subsistema Socioeconómico  

- [ ] 5.1 Métodos. anexo_sub_socioeconomico_metodo_5_1.docx 

- [ ] 5.2 Documentación y bases de datos. anexo_sub_socioeconomico_documentacion_5_2.docx

**Comment by dpedroza74** [comment]
@Nayita 
Listos achivos de anexos de estrategia en la carpeta de entrega 

Carpeta word:
anexo_estrategia_documentacion_2_2

Carpeta pdf:
anexo_estrategia_documentacion_2_2_2_1
anexo_estrategia_documentacion_2_2_2_2
anexo_estrategia_documentacion_2_2_2_3

**Comment by Nayita** [comment]
### Acciones que se hacen antes de convertir un documento docx. a pdf

1. Sustituir la portada. Ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos\portada.docx

2. Actualizar títulos en el recuadro según corresponda al archivo, de acuerdo al documento nombres_archivos.docx. Ruta: \FOMIX\fmx_estudio_tecnico\entregas
Si son anexos, poner el subtítulo "5. Anexos" debajo del título del proyecto, dejando un espacio, con el mismo tipo de letra y tamaño que el título del proyecto, en color negro y negritas.

3. Copiar manualmente los encabezados. 
Para documentos con título y subtítulo del capítulo. Poner el título a la izquierda y el subtítulo a la derecha del recuadro del encabezado.
Para documentos con un sólo título poner el nombre del proyecto a la izquierda y el título del capítulo a la derecha.
Para anexos, solo poner el título del capítulo.

4. Verificar el título del índice. Debe decir "Índice del capítulo #". 

5. Verificar que los campos del índice estén actualizados y que tengan los vínculos activos.

6. Al convertir el word a pdf verificar en "opciones", antes de hacer clik en el botón "guardar", que esté activada la siguiente casilla "Etiquetas de la estructura del documento para accesibilidad".

### Archivos en formato .zip

Anexos  

1. Diagnóstico para la gestión OE. Documentos y bases de datos. 
Carpeta excel:
anexo_diagnostico_documentacion_1_2_2_1
anexo_diagnostico_documentacion_1_2_6_1
anexo_diagnostico_documentacion_1_2_6_2
anexo_diagnostico_documentacion_1_2_6_3
Carpeta pdf:
anexo_diagnostico_documentacion_1_2
anexo_diagnostico_documentacion_1_2_5_1
anexo_diagnostico_documentacion_1_2_5_2
anexo_diagnostico_documentacion_1_2_5_3

2. Estrategia. Documentos y bases de datos. 
Carpeta pdf:
anexo_estrategia_documentacion_2_2
anexo_estrategia_documentacion_2_2_2_1
anexo_estrategia_documentacion_2_2_2_2
anexo_estrategia_documentacion_2_2_2_3

3. Caracterización Subsistema Natural. Documentos y bases de datos. 
Carpeta pdf
anexo_sub_natural_documentacion_3_2
Carpeta excel:
FOMIX\fmx_estudio_tecnico\entregas\excel\capitulo_5\sub_natural

4. Caracterización Subsistema Productivo. Documentos y bases de datos. 
Carpeta pdf
anexo_sub_productivo_documentacion_4_2
Carpeta excel:
Bases de datos

5. Caracterización Subsistema Socioeconómico. Documentación y bases de datos. 
Carpeta pdf
anexo_sub_socioeconomico_documentacion_5_2
Carpetal excel:
Bases de datos

**Comment by ofegarcia** [comment]
**Aviso**

@Nayita 
Ya subí al dropbox (carpeta word), los documentos de texto del subsistema socioeconómico:
- subsistema_socioeconomico_3.3
- anexo_sub_socioeconomico_metodo_5_1

**Comment by ofegarcia** [comment]
***Aviso***

@Nayita 
Ya subí al dropbox (carpeta excel/capitulo_5/sub_socioeconomico), las bases de datos del subsistema socioeconómico:

anexo_sub_socioeconomico_documento_5_2_1
anexo_sub_socioeconomico_documento_5_2_2
anexo_sub_socioeconomico_documento_5_2_3
anexo_sub_socioeconomico_documento_5_2_4
anexo_sub_socioeconomico_documento_5_2_5
anexo_sub_socioeconomico_documento_5_2_6
anexo_sub_socioeconomico_documento_5_2_7
anexo_sub_socioeconomico_documento_5_2_8
anexo_sub_socioeconomico_documento_5_2_9
anexo_sub_socioeconomico_documento_5_2_10

**Comment by aleestrada** [comment]
## Aviso

@Nayita 

Se subieron a la carpeta de word los archivos correspondientes al informe del subsistema productivo:
- subsistema_productivo_3_2.docx
- anexo_sub_productivo_metodo_4_1.docx

**Comment by dpedroza74** [comment]
@Nayita 
Ya subí los documentos de la estrategia en la carpeta word:
estrategia_2
anexo_estrategia_metodo_2_1

**Comment by paola-gp** [comment]
@aleestrada @dpedroza74 

### Subsistema productivo

Los nombres de los archivos de las bases de datos del subistema productivo no quedaron conforme a los acuerdos de entrega, pero por cuestión de tiempo ya no los vamos a cambiar. Lo que si necesitamos es que queden todos citados en el documento principal, faltan algunos.

**Comment by paola-gp** [comment]
@vichdzgeo @aleestrada @milocortes 

#### Scripts

Favor de crear un readme que explique lo que se incluye en la carpeta de scripts. Los scripts deben estar documentados.

**Comment by vichdzgeo** [comment]
@paola-gp 

actualizado el readme de las carpetas de códigos de los subsistemas natural y socioeconómico

**Comment by milocortes** [comment]
@paola-gp : Se actualizó el readme del subsitema productivo.

**Comment by CorinaCantero** [comment]
@paola-gp @Nayita 
Listas las correcciones a los informes

**Comment by CorinaCantero** [comment]
### AVISO

Tamaño de los archivos .pdf de la entrega FOMIX
@paola-gp 


Nombre   del archivo | Número de páginas | Tamaño del archivo (KB)
-- | -- | --
diagnostico_1.pdf | 90 | 2,409
estrategia_2.pdf | 45 | 908
subsistema_natural_3_1.pdf | 109 | 10,587
subsistema_productivo_3_2.pdf | 94 | 5,353
subsistema_socioeconomico_3_3.pdf | 96 | 8,311
sistema_necesidades_usuario_4_1.pdf | 8 | 314
diseno_sistema_4_2.pdf | 56 | 3,377
anexo_diagnostico_metodo_1_1.pdf | 12 | 490
anexo_diagnostico_documentacion_1_2.pdf | 39 | 3,255
anexo_diagnostico_documentacion_1_2_5_1.pdf | 11 | 241
anexo_diagnostico_documentacion_1_2_5_2.pdf | 17 | 298
anexo_diagnostico_documentacion_1_2_5_3.pdf | 13 | 229
anexo_estrategia_metodo_2_1.pdf | 6 | 283
anexo_estrategia_documentacion_2_2.pdf | 115 | 2,613
anexo_sub_natural_metodo_3_1.pdf | 18 | 622
anexo_sub_natural_documentacion_3_2.pdf | 36 | 1,792
anexo_sub_productivo_metodo_4_1.pdf | 9 | 395
anexo_sub_productivo_documentacion_4_2.pdf | 17 | 563
anexo_sub_socioeconomico_metodo_5_1.pdf | 11 | 440
TOTAL | 802 | 42,480

**Comment by paola-gp** [comment]
En \FOMIX\fmx_estudio_tecnico\entregas\informe_financiero está informe_financiero.zip

**Comment by paola-gp** [comment]
@rociobrito: Poner todos las facturas (.pdf) y CFDI (.xml) de todos los comprobantes fiscales

**Comment by paola-gp** [comment]
@rociobrito: poner oficios de estudiantes en /FOMIX/fmx_estudio_tecnico/entregas/informe_financiero/COMPROBANTES/ESTUDIANTES ASOCIADOS

y oficios de investigadores asociados en:
/FOMIX/fmx_estudio_tecnico/entregas/informe_financiero/COMPROBANTES/INVESTIGADORES ASOCIADOS

**Comment by Nayita** [comment]
@CorinaCantero 
Listos los vínculos de las nuevas secciones de la página web. Ruta: \FOMIX\fmx_estudio_tecnico\entregas\secciones.docx

**Comment by Nayita** [comment]
### Informe completo

Ruta: FOMIX\fmx_estudio_tecnico\entregas\informe_completo\informe_completo_etapa1

Archivos:

- anexos_tecnicos.zip

- seccion_financiera.zip

- informe_avance.pdf

- informe_tecnico.pdf

- [ ] yuc_2018_04_01_88958_etapa1_zip

**Comment by Nayita** [comment]
### Actividades

- [ ] Limpiar archivos de la carpeta FOMIX\fmx_estudio_tecnico\entregas

- [ ] Poner en plantilla las tablas del archivo informe_avances.pdf

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
