### ISSUE TITLE
Limpiar y actualizar sistema de información geográfica #FOMIX

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#44]
1. - [x] Lista de trabajo e identificación de problemas  - Corina
1. - [x] Revisar que todas las capas estén en la proyección definida para el proyecto, sin excepciones. - Corina
1. - [x] Corregir la plantilla de entrega para FOMIX  - Corina - Paola
1. - [x] Recortar los insumos a la zona de estudio definida (sin islas)  - Corina ( ver issue #45)
1. - [x] Unificar los nombres (agregar tabla) - Corina
1. - [x] Transformar a shapefile archivos de origen como kmz, geojson, kml, dwg y eliminar caracteres especiales -
 incluyendo la ñ  - Víctor 
1. - [x] Identificar las capas que de origen tienen una codificación erronéa - Víctor
1. - [x] Eliminar los campos nulos,área o perímetro, o si son imposibles de identificar. - Corina 
1. - [x] Generar todos los mapas faltantes del subsistema socioeconómico - Corina 
1. - [x] Almacenar las capas/productos finales en la carpeta de entregables - 
1. - [ ] Establecer reglas en la representación de datos numéricos, rangos o intervalos - Paola 
   1. - [x] Generar los metadatos correspondientes  y asociarlos con el recurso padre, la ruta indicada en los metadatos debe ser de la carpeta de entregables -Corina. 
1. - [ ] Verificar utilizar los estilos definidos previamente por el laboratorio
1. - [x] Versión actualizada del lizmap  (Producto final)

@CorinaCantero @paola-gp

**Comment by vichdzgeo** [comment]
## Verificación capas

@CorinaCantero 

en la siguiente base de datos podrás ver que capas contienen
ruta C:\Dropbox (LANCIS)\SIG\desarrollo\sig_fomix\procesamiento\verificacion_capas.xlsx

- Nulos
- Errores en la codificación
- Errores en la proyección
- Capas que se encuentran en sig_becarios y hay que moverlas

**Comment by CorinaCantero** [comment]
### Campos acordados para bases de datos

![image](https://user-images.githubusercontent.com/44783182/87580943-cfff4680-c69d-11ea-94f8-8459a268217f.png)

**Comment by CorinaCantero** [comment]
### Tabla de correcciones a capas geográficas utilizadas en la primera etapa FOMIX

Nombre | nulos | Codificación | Proyección | Formato de acuerdo a bases de datos | Url
-- | -- | -- | -- | -- | --
yucatan | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/mapas/plantillas/recursos/yucatan/yucatan.shp
regiones_yuc | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/regiones/regiones_yuc.shp
muni_2018_utm16 | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/limites/inegi/div_pol_mpio_2018/muni_2018_utm16.shp
carretera_yuc | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/carretera_yuc.shp
localidades_urbanas | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/localidades_urbanas/localidades_urbanas.shp
loc_principales | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/loc_principales/loc_principales.shp
evapotrans_yuc | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/evapotrans_yuc.shp
precipitacion_ma_yuc | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/precipitacion_ma_yuc.shp
temp_minp_yuc | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/amc/conabio/temp_min_promedio/temp_minp_yuc.shp
temp_maxp_yuc | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/temp_maxp_yuc.shp
clima_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/clima_yuc.shp
degradacion_suelo_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/degradacion_suelo_yuc.shp
edafologia_yuc | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/edafologia_yuc.shp
rs1_vs_s3_final | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/cambio_cobertura/cambio_usv/rs1_vs_s3_final.shp
s3_vs_s6_final | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/cambio_cobertura/cambio_usv/s3_vs_s6_final.shp
usv_serie1_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/usv_v2/usv_serie1_yuc.shp
usv_serie3_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/usv_v2/usv_serie3_yuc.shp
usv_serie6_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/usv_v2/usv_serie6_yuc.shp
Registros de plantas vasculares   endémicas | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/plantas_yuc/plantas_yuc.shp
plantas_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/plantas_yuc/plantas_yuc.shp
aves endemismo | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/aves_yuc/aves_yuc.shp
aves_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/aves_yuc/aves_yuc.shp
mamiferos_yuc_end | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/mamiferos_yuc/mamiferos_yuc.shp
mamiferos_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/mamiferos_yuc/mamiferos_yuc.shp
reptiles_yuc_endemica | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/reptiles_yuc/reptiles_yuc.shp
reptiles_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/reptiles_yuc/reptiles_yuc.shp
anfibios_yuc_endemica | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/anfibios_yuc/anfibios_yuc.shp
anfibios_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/flora_fauna_yuc/anfibios_yuc/anfibios_yuc.shp
sp_acuaepi_yuc | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/sp_acuaepi_yuc.shp
subprovincia_fisiografica_yuc_utm16 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/geocientifica/inegi/fisiografia/subprovincia_fisiografica_yuc_utm16.shp
sistema_topoforma_yuc_utm16 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/sistema_topoforma_yuc_utm16.shp
sp_terrestres_yuc | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/sp_terrestres_yuc.shp
rtp_utm16 | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/ambiente/conabio/regiones_terr_priori/rtp_utm16.shp
rhpri_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/ambiente/conabio/regiones_hidro_priori/rhpri_yuc.shp
rmp_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/ambiente/conabio/regiones_marinas_priori/rmp_yuc.shp
ramsar_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/ramsar_yuc.shp
aicas_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/ambiente/conabio/aicas/aicas_yuc.shp
anp_estatal_mun_priv_yuc2 | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/anp/anp_estatal_mun_priv_yuc2.shp
anp_federaL_yuc_recorte | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/anp_federaL_yuc_recorte.shp
cuerpos_agua_puntos_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/agua/inegi/red_hidrografica/rh_yuc/cuerpos_agua_puntos_yuc.shp
calidad_aguasub_yuc2 | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/agua/conagua/calidad_aguasub/calidad_aguasub_yuc2.shp
calidad_agua_superficial_yuc | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/agua/conagua/calidad_aguasuperficial/calidad_agua_superficial_yuc.shp
continuo_nacional_geologia_utm16 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/geocientifica/inegi/geologia/continuo_nacional_geologia_utm16.shp
fallas_fracturas_yuc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/fallas_fracturas_yuc.shp
cuenca_disp_yuc_utm16 | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/agua/conagua/cuencas_disponibilidad/cuenca_disp_yuc_utm16.shp
regiones_hidro_yuc | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/regiones_hidro_yuc.shp
vul_max_in | si | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/vul_efectos_clima/vul_max.shp
vul_max_den | si | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/vul_efectos_clima/vul_max.shp
usop_pec_umt16 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/cobertura/inegi/potencial_tierra/usop_pec_umt16.shp
usop_for_utm16 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/cobertura/inegi/potencial_tierra/usop_for_utm16.shp
usop_agr_utm16 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/cobertura/inegi/potencial_tierra/usop_agr_utm16.shp
sintesis_sistema_natural | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sintesis/salida/sintesis_sistema_natural.shp
act_eco_principal | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/act_eco_principal/act_eco_principal.shp
Participación del municipio en el   total de unidades económicas del estado | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_part_edo_muni.shp
Participación del municipio en el   total de población ocupada del estado | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_part_edo_muni.shp
Participación del municipio en la   inversión del estado | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_part_edo_muni.shp
Participación del municipio en la   producción del estado | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_part_edo_muni.shp
unidades_economicas | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_muni.shp
poblacion_ocupada | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_muni.shp
inversión | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_muni.shp
producto_bruto | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sub_productivo/activ_ec_muni.shp
tierra_uso_comun_yuc | si | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/cobertura/ran/tierras_uso_comun/tierra_uso_comun_yuc.shp
pastos_praderas_yuc | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/cultivos_principales/pastos_praderas_yuc.shp
maiz_grano_yuc | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/cultivos_principales/maiz_grano_yuc.shp
naranja_yuc | si | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/cultivos_principales/naranja_yuc.shp
concentracion_industrial | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/concentracion_indus/concentracion_industrial.shp
pob_localida_rango_tamaño | no | error en la codificación | EPSG:4326 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/entregables/pobcloc10gw/pob_localidad_yuc.shp
indice_dispersion_v2 | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/clasificacion_poblaciones/salida/indice_dispersion_v2.shp
sun_2018_yuc | si | error en la codificación | EPSG:4326 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/sociedad/conapo/sistema_urbano_2018/sun_2018_yuc.shp
migracion_mexeua_yuc | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/migracion_mexeua_yuc.shp
inmigracion_municipal | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_migracion.shp
inmigracion_estatal | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_migracion.shp
distribucion_pob_yuc 2010 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/sig_becarios/distribucion_pob_yuc.shp
ageb_urb | no | codificación correcta |   | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/socioec_ageb/insumos/ageb_urb.shp
categoria_migratoria | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_migracion.shp
yuc_pobreza_rzgo_edu | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_pobreza_mun.shp
yuc_pobreza_rzgo_soc | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_pobreza_mun.shp
yucatan_loc_clasificacion_v2 | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/clasificacion_poblaciones/salida/yucatan_loc_clasificacion_v2.shp
yuc_social_mun | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_social_mun.shp
yuc_pobreza_pob_pobre | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_pobreza_mun.shp
yuc_pobreza_mun_pob_extrema | no | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_pobreza_mun.shp
yuc_act_eco_mun_primarias | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_act_eco_mun.shp
yuc_act_eco_mun-secu | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_act_eco_mun.shp
yuc_act_eco_mun_terciarias | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_act_eco_mun.shp
yuc_ingreso_mun | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_ingreso_mun.shp
yuc_ingreso_dos_sa | no | codificación correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_ingreso_mun.shp
yuc_ingreso_uno | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/actualizacion_mapas/shapes_yuc/yuc_ingreso_mun.shp
mayas_utm16 | si | error en la codificación | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/insumos/sociedad/inpi/mayas_utm16.shp
sintesis_sistema_socioeconomico | no | codificación   correcta | EPSG:32616 | no | C:/Dropbox   (LANCIS)/SIG/desarrollo/sig_fomix/procesamiento/sintesis/salida/sintesis_sistema_socioeconomico.shp

**Comment by ofegarcia** [comment]
### Relación de mapas generados en Tableau para el subsistema socioeconómico, que no están en el SIG de Fomix



Mapa | Figura en texto | Variable en base   de datos | Base de datos | Anexo
-- | -- | -- | -- | --
Población total | 3.3.1 | pobt_15 | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Hijos nacidos vivos | 3.3.4 | prohv_10 | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Tasa media anual de crecimiento poblacional | 3.3.8 | t_crecma | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Índice de intensidad migratoria | 3.3.9 | iim_a100 | bd_migracion | anexo_sub_socioeconomico_documentacion_5_2_3
Porcentaje de PEA ocupada | 3.3.10 | p_pea_oc | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de PEA ocupada en sector primario | 3.3.12 a) | p_sec_pri | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de PEA ocupada en sector secundario | 3.3.12 b) | p_sec_sec | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de PEA ocupada en sector terciario | 3.3.12 c) | p_sec_ter | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de PEA ocupada que recibe hasta un salario mínimo | 3.3.13 a) | p_pob_1s | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de PEA ocupada que recibe más de un salario mínimo y   hasta dos | 3.3.13 b) | p_pob_a2s | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de PEA ocupada que recibe más de dos salarios | 3.3.13 c) | p_pob_m2s | bd_socioec_diagn | anexo_sub_socioeconomico_documentacion_5_2_1
Salarios integrados | 3.3.13 d) | P 123sal | Esta   variable no está en la base de datos, se generó en Tableau al combinar los   tres niveles de salario
Grado de marginación | 3.3.16 | marg_i_15 | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_2
Porcentaje de población analfabeta | 3.3.21 | p_analf | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de población afiliada a servicios de salud | 3.3.22 | p_pob_af | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Porcentaje de viviendas sin drenaje | 3.3.24 | visindre | bd_socioec_caract | anexo_sub_socioeconomico_documentacion_5_2_1
Población indígena (núm de habitantes) | 3.3.28 | pob_ind_t | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Población indígena económicamente activa | 3.3.30 a) | ip_act | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Población indígena desocupada | 3.3.30 b) | ip_des | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Población indígena con ingreso menor a 1 sm | 3.3.31 a) | ip_1sm | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Población indígena con ingreso de 1 a 2 sm | 3.3.31 b) | ip_1a2sm | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Número de viviendas indígenas sin drenaje | 3.3.32 a) | iv_nodren | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Número de viviendas indígenas sin electricidad | 3.3.32 b) | iv_noelec | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Población indígena alfabeta | 3.3.33 | ip15_alf | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5
Población indígena monolingüe | 3.3.34 | ip5_mon | bd_indigena | anexo_sub_socioeconomico_documentacion_5_2_5

**Comment by CorinaCantero** [comment]
### AVISO
@vichdzgeo 
Ubicación de las capas de flora y fauna a las que hay que corregir los campos nulos: 
\SIG\desarrollo\sig_fomix\entregables\flora_fauna_yuc 
-registro_anfibios
-registro_mamiferos
-registro_plantas
-registro_aves
-registro_reptiles

**Comment by vichdzgeo** [comment]
# AVISO 

@CorinaCantero 

Listas las correcciones de los campos nulos para las capas de flora_fauna_yuc
-registro_anfibios
-registro_mamiferos
-registro_plantas
-registro_aves
-registro_reptiles

**Comment by vichdzgeo** [comment]
# Aviso 

@CorinaCantero @ofegarcia 

ruta: \SIG\desarrollo\sig_fomix\procesamiento\socioeconomico\


listas las capas faltantes del subsistema socioeconómico 

diccionario de apoyo: insumos\diccionario_capas_socioeconomico.xls

@ofegarcia favor de hacer una verificación que las columnas correspondientes de clusters sean las correctas para las variables.

NOTA: en las capas se agregaron los campos de clusters correspondientes, por limitaciones del sistema  y protocolo el nombre de los campos originalmente estaban como "clusters_##" exedian el tamaño permitido asi que se cambiarón por "cls##"



se realizaron las siguientes capas, @CorinaCantero favor de organizarlas tanto en procesamiento como entregables, si consideras un nombre mejor para las capas favor de modificarlo :

ruta =  \SIG\desarrollo\sig_fomix\procesamiento\socioeconomico\procesamiento

- poblacion_total.shp
- hijos.shp
- tma_crecimiento_pob.shp
- indice_intensidad_megratoria.shp
- porcentaje_pea_ocupada.shp
- grado_marginacion.shp
- pob_analfabeta.shp
- pob_afiliados_salud.shp
- viviendas_sin_drenaje.shp
- pob_indigena.shp
- pob_indigena_economica.shp
- pob_indigena_hablantes.shp

**Comment by CorinaCantero** [comment]
### **REPORTE DE AVANCE DE ACTIVIDADES**

Hasta el momento se han realizado las siguientes actividades: 

1. Reacomodar la información geográfica (insumos y entregables) de acuerdo con el protocolo. 
- Los insumos se encuentran organizados en carpetas de acuerdo al tema y al proveedor de la información en la siguiente ubicación: \SIG\desarrollo\sig_fomix\insumos
- Los entregables se organizaron en cuatro carpetas: limites, sub_natural, sub_productivo y sub_socioeconomico. Ubicación: \SIG\desarrollo\sig_fomix\entregables

2. Corrección de capas geográficas
Se corrigieron de las capas geográficas que lo requerían: la proyección, los campos nulos (agregando "nd" a los registros de tipo carácter y "-999.00" a los registros de tipo numérico), la codificación de la fuente de datos (UTF-8), se eliminaron los caracteres especiales (excepto en los casos permitidos) y se eliminaron los campos de áreas, perímetros o campos cuya información no era útil por no ser rastreable su significado. 

3. Se agregó a todas las tablas de atributos los campos requeridos para cumplir con el protocolo de bases de datos del APC-LANCIS, es decir los campos: cve_ent, nom_ent, cve_mun, nom_mun, mun_ori, cve_geo, id_region, region.

4. Se elaboraron los metadatos de los insumos padres faltantes y de todos los entregables. Faltan los siguientes metadatos: 
cambio_cob_s1_s3
cambio_cob_s3_s6
usv_serie1
usv_serie3
usv_serie6
registro_plantas
registro_aves
registro_mamiferos
registro_reptiles
registro_anfibios
sintesis_sub_natural
sintesis_socioeco

###  Actividades faltantes

1. Generar capas geográficas de las bases de datos por AGEB y sus metadatos
2. Corregir la plantilla de mapas 
3. Guardar los estilos utilizados para cada capa geográfica

@vichdzgeo

**Comment by CorinaCantero** [comment]
**AVISO**
Ruta de la capas insumos para calidad de recursos de incertidumbre y predicción, favor de especificar cual fue la que se utilizó (densidad de arbolado y composición total): 
SIG\desarrollo\sig_fomix\insumos\cobertura\snigf
@vichdzgeo

**Comment by vichdzgeo** [comment]
@CorinaCantero 

se utilizaron los insumos de la carpeta **raster_prediccion**

el producto obtenido es el raster del insumo recortado y alineado a los parámetros del proyecto 


insumo | subproducto (insumo para la función de valor)
-- | --
PRED_Daso_A_Densidad_tot_.tif | tp_snigf_densidad_arbolado.tif
PRED_Daso_A_CO2.ha_aerea_.tif | tp_snigf_carbono_almacenado.tif
PRED_Comp_Total_QRF_band1 | tp_snigf_composicion_total


**NOTA**
estos subproductos se llevan a ideales en el código indice_calidad.py

**Comment by CorinaCantero** [comment]
### AVISO
@vichdzgeo 

Listos los metadatos de insumos que estaban pendientes: 

Riesgo   a granizo | http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/834e84f5-8a26-409d-ac7b-50facd55f311
-- | --
Calidad del agua dr. Batllori | 
Densidad de arbolado | http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/63e183aa-8330-4d10-8eb0-1b5c85f8e0ae
Composición total | http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/e66e34d7-810d-412a-8a6c-5dbf7cd88eb1
Carbono almacenado | http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/c475d401-d0f7-4848-80e1-ab607c25af0a

Favor de indicar cuál fue la capa que se utilizó para la calidad del agua del Dr. Batllori
