### ISSUE TITLE
Definir la zona de estudio #FOMIX

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#45]
## Proyección 

Universal Transversa de Mercator Zona 16 Norte EPSG: 32616 

## Zona de estudio

La zona de estudio comprende los municipios de Yucatán

Utilizar las siguientes capas para los recortes de los insumos

| Proyección | Ruta |
|---|---|
WGS84| SIG/desarrollo/sig_fomix/entregables/mascara_municipios_2018/area_municipios_2018_yuc_wgs84.shp|
Cónica conforme de Lambert (EPSG:6372)| SIG/desarrollo/sig_fomix/entregables/mascara_municipios_2018/area_municipios_2018_yuc_ccl.shp|
UTM 16N (EPSG:32616)| SIG/desarrollo/sig_fomix/entregables/mascara_municipios_2018/area_municipios_2018_yuc.shp|

## Región

La región definida para capas raster es:

xmin = 145391m
xmax =444591m
ymin =2163427m
ymax =2391827m

renglones (Width) =2992, columnas(Height) = 2284 

tamaño de pixel = (100,100) m

**Comment by CorinaCantero** [comment]
### Campos acordados para bases de datos
![image](https://user-images.githubusercontent.com/44783182/87580854-b52cd200-c69d-11ea-91f0-306e34d8b7f8.png)

**Comment by vichdzgeo** [comment]
# Tamaños de pixel compatibles con la región definida

## Menores a 100 m
- tamaño de pixel: 10 m  renglones= 29920, columnas = 22840
- tamaño de pixel: 20 m  renglones= 14960 , columnas = 11420
- tamaño de pixel: 50m  renglones= 5984, columnas = 4568

## Mayores a 100 m

- tamaño de pixel: 200m  renglones= 1496, columnas = 1142
- tamaño de pixel: 400m  renglones= 748, columnas = 571
