### ISSUE TITLE
Compilar base de datos de cambio climático para Yucatán

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#46]
- [x] Definir ubicación de datos @CorinaCantero 

- [x] Bajar todos los datos de : https://www.gob.mx/inecc/acciones-y-programas/deltas-de-cambio-anomalias-de-4-modelos-de-circulacion-global @Nayita 

- [x] Hacer script para cortar datos a Yucatán @vichdzgeo

**Comment by CorinaCantero** [comment]
Carpeta para colocar los datos de cambio climático:
\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_climatico
@Nayita

**Comment by Nayita** [comment]
### Aviso

De los archivos descargados falta la siguiente información:


Francia |   |  
-- | -- | --
RCP | Periodo | Archivos faltantes
8.5 | 2045-2069 | Precipitación, temperatura máxima
E. U. A |   |  
8.5 | 2015-2039 | Temperatura máxima
  | 2045-2069 | Precipitación, temperatura máxima
Reino Unido |   |  
4.5 | 2015-2039 | Temperatura máxima
8.5 | 2045-2069 | Precipitación, temperatura máxima
Alemania |   |  
4.5 | 2015-2039 | Temperatura media
8.5 | 2045-2069 | Precipitación, temperatura máxima

**Comment by Nayita** [comment]
### Aviso
@vichdzgeo 

Archivos totalmente extraídos con el archivo log correspondiente divididos por carpetas. 
Se están buscando los archivos faltantes mencionados en el comentario anterior.

**Comment by Nayita** [comment]
### Aviso
Archivos faltantes localizados y descargados los zips en la carpeta FOMIX/fmx_estudio_tecnico/caracterizacion_subs/procesamiento/sub_natural/cambio_climatico

No se  pudieron extraer por falta de espacio en disco duro.

### Nota importante

Queda pendiente hacer el diccionario de los datos descargados.

**Comment by Nayita** [comment]
### AVISO

Listo el diccionario de bases de datos. Ruta: FOMIX/fmx_estudio_tecnico/caracterizacion_subs/procesamiento/sub_natural/cambio_climatico

Archivo: diccionario_cambio_climatico.xlsx

**Comment by vichdzgeo** [comment]
## Capas de cambio climático para el estado de Yucatán

Insumos:
FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_climatico

Ruta:
SIG\desarrollo\sig_fomix\entregables\cambio_climatico

Se procesaron 1,152 capas raster, que son recortadas utilizando la máscara del estado de Yucatán, los productos resultantes contienen la misma extensión y tamaño de pixel para cumplir con las especificaciones técnicas del proyecto. 

- Se detectaron capas tiff faltantes, estas fueron generadas por medio de los archivos txt existentes 
- Se proyectaron a UTM zona 16
- El tamaño de pixel se establece de 100 x 100 metros (este tamaño es para cumplir con las especificaciones técnicas del proyecto y por ninguna circunstancia debe entenderse como una mejora en la resolución de los datos originales)
La resolución de los datos originales es de 30" (aproximadamente 900m , [1º = 111.3 km] rT =40.075 km])

**Comment by vichdzgeo** [comment]
## Documentación 

recurso 
http://atlasclimatico.unam.mx/atlas/kml/

**Comment by vichdzgeo** [comment]
## Formato requerido  para generar las bases de datos

@aaron-ts , favor de especificar el formato requerido para la base de datos de  cambio climático

se cuentan con 4 modelos de cambio climático, los cuales contienen 4 variables (precipitación, temperatura máxima, media y mínima) por mes para dos reforzamientos radiativos (rcp 4.5 y rcp 8.5) para dos horizontes ( 2015-2039 (25 años) y 2075-2099 (25 años)  para cada uno de se tienen que desarrollar  bases de datos de promedios mensuales por municipio para las 4 variables.
