### ISSUE TITLE
Administrar y gestionar activos de información #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#47]
### ETAPAS Y ORGANIZACIÓN DEL PROYECTO FOMIX

El proyecto 'Sistema de conocimiento para la gestión del Ordenamiento Ecológico del Territorio del estado de Yucatán' se conforma de los siguientes productos:

1. **Diagnóstico para la gestión del ordenamiento ecológico del territorio**
Consiste en la identificación de recursos y capacidades disponibles para la gestión del OET 
Ubicación: fmx_diagnostico_gestion

2.  **Estudio técnico** 
- **Caracterización**: contiene la descripción del sistema socio-ecológico de la entidad analizando los subsistemas natural, productivo y socioeconómico. 
Ubicación: fmx_estudio_tecnico\caracterizacion_subs
-  **Diagnóstico:** incluye el análisis de aptitud, análisis de conflictos e identificación de áreas que se deben preservar, conservar, proteger y restaurar. 
Ubicación: fmx_estudio_tecnico\diagnostico
- **Pronóstico**: examinar el comportamiento del territorio estatal bajo los escenarios tendencial, contextual y alternativo.
Ubicación: fmx_estudio_tecnico\pronostico
- **Propuesta:** contiene el modelo de ordenamiento ecológico (UGA), las estrategias ecológicas, los criterios de regulación ecológica y los indicadores. 
Ubicación: fmx_estudio_tecnico\propuesta

3. **Sistema**

**Ubicación:** FOMIX\fmx_diseno_sistema
FOMIX\fmx_sistema_conocimiento 
- **Proyecto del sistema**: contiene las especificaciones del diseño y arquitectura informática del sistema de conocimiento y soporte geográfico de decisiones para la gestión del POETY. 
- **Sistema desarrollado e implementado**: infraestructura tecnológica de software y hardware del Sistema.
- **Puesta en marcha del Sistema:** documentos probatorios de la capacitación del personal de la SDS, pruebas de funcionamiento y la implementación de una estrategia de difusión y divulgación del Sistema.
- **Plan de seguridad, mantenimiento y soporte técnico del Sistema:** documento con el plan que garantice el correcto funcionamiento del Sistema.

**Comment by CorinaCantero** [comment]
@Nayita En este issue puedes poner comentarios acerca de la revisión de las carpetas de FOMIX

**Comment by Nayita** [comment]
### Aviso

Se hizo revisión de la carpeta y se cambiaron nombre de archivos conforme a protocolo excepto en las siguientes carpetas, por desconocer si son insumos en scripts de procesos y elaboración de gráficas:

- \FOMIX\fmx_diseno_sistema

- \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_socioeconomico\carac_sectorial\agricola

### Nota importante
Falta actualizar el README general.

**Comment by Nayita** [comment]
@aleestrada 

En la siguiente ruta se encuentran archivos que no están nombrados respecto a protocolo. Favor de revisar y notificar si son insumos o se pueden cambiar los nombres. 

Ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_socioeconomico\carac_sectorial\agricola

**Comment by Nayita** [comment]
@serranoycandela 

Sigo en espera de notificación si los archivos de la ruta siguiente son insumos o no para renombrarlos conforme a protocolo.
Ruta:\FOMIX\fmx_diseno_sistema

**Comment by CorinaCantero** [comment]
### TAREAS

1.  Identificar versiones finales de los archivos y las versiones antiguas moverlas a "auxiliares": 
- [ ] FOMIX\fmx_estudio_tecnico\diagnostico\conflictos\matriz
- [ ] FOMIX\fmx_estudio_tecnico\diagnostico\grupos_aptitud
- [ ] FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\presentaciones\pgp 
- [ ] FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\presentaciones\dp_tm

2. Conflictos: ¿Este documento es el mismo que está en fmx_estudio_tecnico\diagnostico\conflictos\?
- [ ] FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\conflictos
- [ ] FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores --- Hay un documento suelto de conflictos

3. Hay dos carpetas de FV
- [ ] FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\turismo 

4. Hacer readme de las carpetas: 
- [ ] fmx_diseno_sistema
- [ ] fmx_documentacion
- [ ] fmx_sistema_conocimiento

**Comment by CorinaCantero** [comment]
### AVISO

Se llevo a cabo una primera reunión para la entrega de activos de información de FOMIX con @Nayita, quedan pendientes los siguientes puntos: 

- [x] Aclarar en readme que la carpeta FOMIX\fmx_comite será la en donde se alojen los insumos y el procesamiento de los archivos referentes al comité, mientras que en la carpeta FOMIX\fmx_estudio_tecnico\bitacora_ambiental\pdf\comite se guardarán únicamente las versiones finales de los archivos en .pdf y que se vayan a mostrar en la página de la bitácora ambiental.
- [x] Mover la carpeta FOMIX/fmx_documentacion
- [x] Hacer readme de las carpetas:  fmx_diseno_sistema y fmx_sistema_conocimiento
- [x] Reunión con Daniela para revisar los siguientes puntos: 
- La carpeta fmx_planeacion ¿se puede mover a la carpeta fmx_docs_admin_proyecto?
- La carpeta fmx_estrategia_institucional ¿se puede mover a fmx_diagnostico_institucional?
- La carpeta FOMIX\fmx_estudio_tecnico\anexos ¿se puede mover a FOMIX\fmx_estudio_tecnico\diagnostico\talleres?
- Carpeta fmx_informes

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
