### ISSUE TITLE
METAISSUE Desarrollar productos etapa 2 #FOMIX

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#48]
**Metas y productos comprometidos** 

- Estudio técnico
Metas
3.2.1 Etapa de diagnóstico del POETY.
3.2.2 Etapa de pronóstico del POETY.
3.2.3 Etapa de propuesta del POETY.
Productos
3.2.1 Estudio técnico para la actualización del POETY- etapas de diagnóstico, pronóstico y propuesta. - Documento que contendrá las etapas de diagnóstico, pronóstico y propuesta del estudio técnico para la actualización del POETY. El contenido del diagnóstico integral del territorio incluirá el análisis de aptitud, el análisis de conflictos y la identificación de áreas que se deban preservar, conservar, proteger y restaurar. El contenido del pronóstico examinará el comportamiento del territorio estatal bajo los escenarios tendencial, contextual y alternativo. El contenido de la propuesta incluirá el programa ordenamiento ecológico, que estará compuesto por el modelo de ordenamiento ecológico (un mapa de las unidades de gestión ambiental (UGA) y los lineamientos ecológicos), las estrategias ecológicas, los criterios de regulación ecológica y los indicadores.

3.2.2 Anexos del estudio técnico. - Documentos probatorios del desarrollo de talleres participativos, reuniones de trabajo, que incluirán la descripción de las herramientas metodológicas y reglas de decisión utilizadas, así como las bases de datos y las capas digitales con los metadatos que sean emplearon durante el proceso.

- Sistema
Metas
4.2.1 Programa de planeación colaborativa del POETY que refleje explícitamente las prioridades, necesidades y capacidades de los actores sociales, para con ello lograr una evaluación regional integrada del estado.
4.2.2 Preparación de algoritmos de despliegue de datos, modelación, análisis y geo-visualización y programación de interfaces.
4.2.3 Pruebas de concepto y funcionalidad e instalación de la plataforma computacional en SEDUMA.
Productos
4.2.1 Sistema desarrollado e implementado. - Infraestructura tecnológica de software y hardware del sistema de gestión para el ordenamiento ecológico del territorio del estado de Yucatán, desarrollada e implementada de acuerdo con las especificaciones del proyecto correspondiente (producto esperado 4.1.1).

**Resumen actividades y métodos comprometidos (Leer detalle en la propuesta)**
_Etapa de diagnóstico:_
- Análisis de aptitud. Se implementarán técnicas de modelación multicriterio integradas a un sistema de información geográfica
- Análisis de conflictos. Se identificarán las interacciones sectoriales con el fin de entender la compleja red de conexiones entre los distintos sectores y subsistemas. Se analizarán los flujos de conocimiento e información como los patrones de compatibilidad/incompatibilidad en el uso de los recursos y ocupación del territorio. Se aplicará un método topológico en el que se representará la manera en que las relaciones o lazos entre sectores facilitan u obstruyen sus acciones y comportamiento. 
- Delimitar las áreas que se deberán preservar, conservar, proteger o restaurar, así como aquellas que requieran el establecimiento de medidas de mitigación para atenuar o compensar impactos ambientales adversos. Se considerarán aspectos sobre degradación ambiental, desertificación o contaminación; conservación de los ecosistemas y la biodiversidad y el mantenimiento de los bienes y servicios ambientales; áreas naturales protegidas, hábitats críticos para la conservación de la vida silvestre y áreas de refugio para proteger especies acuáticas; recursos naturales importantes para el desarrollo de actividades sectoriales; y susceptibilidad a riesgos naturales o a efectos negativos del cambio climático.

_Etapa de pronóstico:_ 
- Generación de la estructura del sistema socio-ecológico acoplado. Estará basada en el esquema de evaluación regional integrada (Bojórquez-Tapia et al. 2011), a través del cual será posible sintetizar analíticamente tanto las representaciones cartográficas bona fide (que corresponden a rasgos geográficos reales) como las representaciones cartográficas fíat (que corresponden a mandatos administrativos, son producto del consentimiento o se asocian a algún tipo de autorización). El acoplamiento entre el ámbito material y el simbólico del sistema socio-ecológico, se establecerá implementando el ANP (proceso analítico reticular) para relacionar las dimensiones télica (propósitos), agencial (sectores y factores de cambio) y constitutiva (atributos en mapas) del territorio 
- Generación de los tres escenarios bajo los cuales se podrían (1) exacerbar los conflictos ambientales, de no tomarse ninguna medida preventiva o correctiva, escenario tendencial; (2) resolver los conflictos ambientales con la implementación del POETY, o escenario estratégico; o (3) modificar la aptitud territorial con la ejecución de proyectos sectoriales específicos, o escenario alternativo).
Escenario tendencial: se considerarán series de datos desde 1970 a la fecha, con el fin de delinear las trayectorias históricas de los procesos de transformación territorial lo más detalladamente posible

Modelación dinámica de sistemas: (1) Implementación de un conjunto de modelos biofísicos integrados que simularán el cambio climático, el cambio de uso del suelo, el crecimiento urbano, el ciclo del agua urbana y las interacciones con la infraestructura; (2) análisis de decisiones multicriterio (que resultará del diagnóstico), mediante la implementación de la super-matriz del ANP (o proceso analítico reticular, antes mencionado) y que equivale matemáticamente a un proceso de cadena de Markov para, de esta manera, capturar la dependencia y la retroalimentación del sistema y simular la evolución de la aptitud y la vulnerabilidad para cada actor social; (3) optimización espacial, con lo que se delinea el espacio de decisión de cada uno de los actores sociales, se identifican las actividades factibles, y se determina el conjunto de actividades que satisfagan óptimamente los objetivos, de acuerdo con las restricciones del caso; (4) geosimulación, que consiste en la simulación dinámica mediante la fusión de Autómatas Celulares (CA, por sus siglas en inglés) y Modelos Basados en Agentes 

Para simular el crecimiento urbano de la zona metropolitana de Mérida se utilizará el modelo SLEUTH (Clarke 1997), que es un modelo predictivo basado en autómatas celulares. Para la identificación de zonas vulnerables a la contaminación de los acuíferos por residuos sólidos y líquidos se usará la técnica de simulación V DRASTIC (Bojórquez-Tapia et al. 2009). En materia de cambio climático se analizarán los escenarios y las medidas de adaptación establecidas en el PEACC.

Se prevé que el modelo se verifique en talleres con los actores sociales cuyo fin será determinar los rangos de valores de los parámetros críticos y, de esta forma, capturar la incertidumbre inherente al sistema socio-ecológico y los procesos de toma de decisiones

- Generación de los indicadores ambientales (naturales, sociales y económicas) para la bitácora ambiental del POETY

_Etapa de propuesta:_

- Generación del modelo de ordenamiento ecológico consistirá en el mapa de regionalización ecológica que se derive del análisis de aptitud. En este modelo se señalará la actualización de las UGA, a las que se les asociarán los lineamientos y estrategias ecológicas que correspondan para maximizar el consenso sobre la ocupación territorial y minimizar los conflictos ambientales. 
- Generación de los lineamientos y las estrategias ecológicas. Abarcarán cuestiones relevantes relacionadas con la vulnerabilidad y la adaptación al cambio climático, para lo cual se considerarán las disposiciones incluidas en el Plan Especial de Acción ante el Cambio Climático del Estado de Yucatán. 
- Generación de los criterios de regulación ecológica. Contarán con la motivación técnica y el fundamento legal 
- Elaboración de fichas técnicas

_Desarrollo e implementación del Sistema_ 

- Programa de planeación colaborativa. Establecer los mecanismos para a la implementación práctica el esquema de involucramiento ininterrumpido del POETY con base en el sistema de gestión. Conforme a EAST, el programa se dividirá en tres fases. Durante la fase de convocatoria, el programa estará dirigido eliminar las barreras socio-institucionales, grupales y socio-tecnológicas. Durante la fase de participación, el programa relacionará la agenda con los elementos de conducción del sistema socio-ecológico dentro de trayectorias de desarrollo sostenible. Durante la fase de apropiación del sistema de gestión del POETY por parte de los actores sociales posibilitará la transformación de sus capacidades de influir en la conducción del sistema socio-ecológico.
- Preparación de algoritmos. Requerirá la integración de procedimientos algorítmicos y de simulación sustentados en el paradigma de la complejidad y de incertidumbre extrema. Construir plataformas de geo-visualización para desplegar los resultados de los análisis de aptitud y de vulnerabilidad territorial. Las aplicaciones se integrarán en módulos de geovisualización con indicadores específicos para la bitácora ambiental. En el diseño de las plataformas de geo-visualización se buscará aprovechar las capacidades de la red para acceder a información distribuida en múltiples servidores y bases de datos de forma expedita y sintética. 
- Pruebas de concepto y funcionalidad. En particular, se probarán las aplicaciones computacionales para el análisis de aptitud, geovisualización, simulación dinámica, geosimulación y bitácora ambiental. Las pruebas funcionales serán de tipo de caja negra para evaluar el comportamiento externo del sistema de gestión. Asimismo, se incluirán pruebas de seguridad e interoperatividad. También se realizarán pruebas no funcionales para evaluar el rendimiento, usabilidad, mantenibilidad, fiabilidad y portabilidad del sistema.

**Comment by dpedroza74** [comment]
Temas revisados en la primera reunión de organización 23 julio 2020


Producto | Información | Responsables
-- | -- | --
Aptitud | Solicitud de información identificada   Modelos tipo   OWA   Preparar mapas funciones de valor | Daniela, Luis, Paola       Víctor, Corina
Áreas que se deberán preservar, conservar, proteger o restaurar | Información faltante e integración        ·           Revisar análisis fragmentación   ·           Multicriterio   ·           Modelación multiobjetivo | Luis, David, Víctor, Paola
Análisis de conflictos | Conflictos – análisis documental | Daniela
Simulación escenarios | Series históricas (desde 1970) – escenario tendencial       Tipo de políticas que se aplicaron (programas, inversiones)        Bases de datos e información documental sobre tendencias de   desarrollo   ·           Proyecciones población, energía, agua,   residuos   ·           PDE, PDU, proyectos federales, PEACC | Nadia, Ofelia, Corina
  | SLEUTH | Fidel, Víctor, Paola
  | V Drastic - Batllori | Luis, Víctor
  | Cambio climático | Nadia
  | ABM -diseño de entrevistas |  
Programa colaborativo |   | Luis, Daniela, Paola
Preparar los algoritmos y programar de interfaces. |   | Fidel, Aaron, Hermilo

**Comment by ofegarcia** [comment]
@paola-gp, @dpedroza74 
Se realizó síntesis de las especificaciones contenidas en los términos de referencia para las etapas II y III del proyecto FOMIX. 
El documento denominado **especif_propuesta_fomix_II_y_III** se encuentra en fomix/fmx_doc_admin_proyecto.

**Comment by paola-gp** [comment]
### Índice de entrega de etapa 2 

@dpedroza74 y @ofegarcia : podrían revisar esta propuesta para ir armando en la página con el contenido adicional?

### 1. Análisis de aptitud sectorial
### 2. Análisis de conflictos ambientales
#### 2.1  Índices y características de los conflictos 
#### 2.2 Análisis de redes de conflictos
### 3. Actualización de la caracterización y diagnóstico
#### 3.1 Actualización de subsistema socioeconómico con información del último censo
#### 3.2 Clasificación de clases de uso de suelo y vegetación
####3.3 Análisis de calidad de parches de cobertura natural 
### 4. Identificación de áreas a proteger, preservar, conservar o restaurar
#### 4.1 Construcción de indicadores
#### 4.2 Construcción de índice de áreas a proteger, preservar, conservar o restaurar
### 5.  Sistema de conocimiento para la gestión del Ordenamiento Ecológico del Territorio (OET) del estado de Yucatán
####  5.1 Visualizador de capas geográficas 
#### 5.2 Portal de metadatos
#### 5.3 Portal de indicadores

**Comment by dpedroza74** [comment]
Estudio técnico para la actualización del POETY
1.	Caracterización
1.1.	Subsistema natural
1.2.	Subsistema productivo
1.3.	Subsistema socioeconómico
1.4.	Anexos
1.4.1.	Caracterización del subsistema natural
1.4.1.1.	Métodos
1.4.1.2.	Documentación
1.4.2.	Caracterización del subsistema productivo
1.4.2.1.	Métodos
1.4.2.2.	Documentación
1.4.3.	Caracterización del subsistema socioeconómico
1.4.3.1.	Métodos
2.	Diagnóstico
2.1.	Análisis de aptitud sectorial
2.2.	Análisis de conflictos ambientales
2.2.1.	Caracterización de los conflictos e índices
2.2.2.	Análisis de interacciones sectoriales
2.3.	Identificación de áreas a proteger, preservar, conservar o restaurar
2.3.1.	Clasificación de clases de uso de suelo y vegetación
2.3.2.	Análisis de calidad de parches de cobertura natural
2.3.3.	Construcción de indicadores
2.3.4.	Construcción de índice de áreas a proteger, preservar, conservar o restaurar


Sistema de conocimiento para la gestión del Ordenamiento Ecológico del Territorio (OET) del estado de Yucatán
Visualizador de capas geográficas
•	Portal de metadatos
•	Portal de indicadores

**Comment by Nayita** [comment]
@dpedroza74 

La propuesta de índice es para la página web de entregas al CONACYT (lancisapc.wixsite.com/fomixpoety), diferente a la página para la SDS (www.yucatan-poety.com)

**Comment by dpedroza74** [comment]
Subí a /FOMIX/fmx_estudio_tecnico/anexos
los avances del producto _3.2.2 Anexos del estudio técnico. - Documentos probatorios del desarrollo de talleres participativos, reuniones de trabajo, que incluirán la descripción de las herramientas metodológicas y reglas de decisión utilizadas, así como las bases de datos y las capas digitales con los metadatos que sean emplearon durante el proceso_.

Tenemos que platicar cómo vamos entregar videos y a referir lo de las bases de datos y capas.

**Comment by paola-gp** [comment]
@dpedroza74 

Veo dos problemas con tu propuesta para la entrega de la etapa 2. La primera es que no corresponde con los nombres de productos que buscará y revisará CONACYT y el segundo es que no queremos que revise de nuevo la etapa 1 (no queremos abrir ese frente).

**Comment by dpedroza74** [comment]
3.2.1 Estudio técnico para la actualización del POETY
3.2.1.1 Etapa de diagnóstico
    

- Análisis de aptitud
-     Análisis de conflictos
-     Áreas

 que se deberán preservar, conservar, proteger o restaurar
3.2.1.2 Etapa de pronóstico
Estructura del sistema socio-ecológico acoplado
Escenarios
Indicadores ambientales
3.2.1.3 Etapa de propuesta
Modelo de ordenamiento ecológico
Lineamientos y las estrategias ecológicas
Criterios de regulación ecológica
Fichas técnicas

3.2.2 Anexos del estudio técnico

**Comment by paola-gp** [comment]
@dpedroza

Lo dejamos tal cual? ¿empezamos una entrega con 3.2.1?  ¿Mi propuesta con algunas adecuaciones no te convence? ¿vamos a entregar indicadores? ¿vamos a entregar fichas técnicas? ¿en donde queda el sistema?

**Comment by dpedroza74** [comment]
@paola-gp 
Pues en mi opinión, sí deberíamos entregar con los números de producto que vienen en el CAR, justo para que puedan buscar en lo que estamos entregando, conforme a lo que nos comprometimos. Yo propondría poner el índice de la etapa 1 (en gris - sin ligas) y seguir con los de la etapa 2 a partir de ahí
Etapa 1
1.1.1 Diagnóstico....
2.1.1 Estrategia.....
3.1.1 Estudio... caract
4.1.1 Proyecto ...

**Etapa 2
3.2.1 Estudio técnico 
diagn
pron
prop
3,2.2 Anexos
4.2.1 Sistema desarrollado e implementado**

Ahora, lo de los indicadores y las fichas está comprometido en la parte metodológica. No tengo idea si en dos semanas estaremos en la posibilidad de entregar eso o no y asumo que Luis tendrá que tomar esa decisión, conforme a lo que le digas qué es viable.  Sé que aún falta mucho de cómo se va a integrar lo de los grupos de aptitud con los resultados de escenarios para hacer ya la propuesta de las UGA.
