### ISSUE TITLE
Atender observaciones de CONACYT #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#50]
### OBSERVACIONES PRIMERA ENTREGA

Se enlistan las observaciones hechas por CONACYT a la primera entrega del proyecto FOMIX: 

- [x] 1) Aunque el documento de informe técnico está completo, dado que está integrado por diferentes secciones y apartados, se considera que podría ser más accesible si tuviera un índice general, con la paginación en orden en todo el documento. Considere esta observación para los informes subsiguientes. **Nadia**

2) Deberá corregir los diferentes errores de tecleo, imprecisiones en figuras y párrafos, lo mismo que las inconsistencias en las fuentes bibliográficas enlistadas en el anexo 1.

3) Deberá corregir la falta de precisión en la metodología, tal cual se le señala en el Anexo 1.

- [x] 4) Se identificaron varios enlaces que no están vigentes o actualizados, por mencionar uno, el caso de Mapa 3.3.19. **Ofelia**

- [ ] 5) Se requiere que mantenga el trabajo coordinado con el Usuario, a fin de que éste último garantice que el personal que debe involucrarse, así lo haga. Para la siguiente etapa se solicita que asegure que quede explícita la forma en la cual el Usuario haya utilizado la información que conforma el producto principal de este proyecto para incidir en la regulación de los cambios de uso de suelo. Asimismo, deberá garantizar que diferentes sectores de la sociedad civil sean conocedores de la herramienta (producto 4.2.1), no limitando la difusión a talleres y reuniones, sino mediante otros medios que garanticen que la población en Yucatán conozca los principales problemas. **Daniela**

- [ ] 6) Se recomienda considerar sesiones informativas en diferentes universidades e institutos tecnológicos de la entidad, a fin de que estudiantes aprendan a manejar la herramienta y puedan incorporarla como fuente de información en sus estudios de tesis. **Daniela**

- [ ] 7) Señala que no fue posible aplicar el FODA en grupos focales como se había considerado en la propuesta del proyecto, dado que “el Comité de Ordenamiento Ecológico del OETY no está en operación.” Aunque no esté en operación, sí existe y hay una lista de sus miembros, así como del Órgano Técnico del Ordenamiento. Por lo que se debió consultar e invitar cuando menos al órgano interno. Se solicita presente la justificación de por qué no se hizo de esa forma. **Daniela**

- [ ] 8) Deberá precisar a detalle las actividades programadas a realizar por las dos personas a contratar como investigadores asociados, las razones por las cuales se aplazó su incorporación, y qué es lo que se tiene programado que realicen en la siguiente etapa. En función de lo anterior, deberá volver a realizar el procedimiento para dar de alta a estas dos personas. **Daniela**

**Capítulo Financiero**

1) Se observó que las facturas que amparan los gastos de la partida de pasajes y viáticos se emitieron con el método de pago (PPD) pago en parcialidades o diferido. Los complementos de pago de dichas facturas no fueron proporcionados. Por lo que se le solicita que entregue los complementos de pago.

- [ ] 2) Se observó que el Sujeto de Apoyo en esta etapa sólo ejerció el 26% del total de los recursos ministrados, por lo que se le solicita la justificación detallada de porqué se presentó dicho subejercicio. **Daniela**

**Estas recomendaciones deberá atenderlas a más tardar el 4 de septiembre de 2020.**

**Comment by Nayita** [comment]
@milocortes 

Favor de revisar y corregir en el documento el punto 7 del Anexo 1 (donde aparece tu nombre). 
Archivo subsitema_productivo_3_2

**Comment by Nayita** [comment]
### Aviso
@milocortes @dpedroza74 @CorinaCantero @ofegarcia 

Favor de notificar cuando hayan realizado sus correcciones en los documentos vía issue.
Poner los archivos corregidos para convertirlos a PDF en la siguiente ruta: /FOMIX/fmx_procesamiento/documentos_corregidos

**Comment by CorinaCantero** [comment]
**Respuesta a observaciones** 

3)

- Mapa 3.1.4 Fisiografía. Fuente INEGI, 2001. Es la fuente más actualizada disponible "Conjunto de datos vectoriales Fisiográficos. Continuo Nacional serie I. Escala 1:1 000 000" 
- Mapa 3.1.5 Unidades de paisaje. Fuente INEGI, 2005. La fuente correcta es la SDS-Yucatán, 2005 **Pendiente justificación**
- Mapa 3.1.6 Edafología. Fuente INAFAP-CONABIO, 1995. 
De acuerdo con la búsqueda, la información edafológica más actualizada corresponde al "Conjunto de datos vectoriales edafológico, escala 1:250,000 Serie II. (Continuo Nacional). 2014", sin embargo la información no ha podido ser rastreada en la página web de INEGI (https://www.inegi.org.mx/400.html?aspxerrorpath=/geo/contenidos/recnat/edafologia/vectorial_serieii.aspx) ni descargada del geoportal de CONABIO en donde está disponible el metadato de dicha información (http://www.conabio.gob.mx/informacion/metadata/gis/eda250s2gw.xml?_httpcache=yes&_xsl=/db/metadata/xsl/fgdc_html.xsl&_indent=no), se realizó una solicitud de información a INEGI vía electrónica y estamos en espera de poder obtener esa información. 
Por otra parte, en la página web de INEGI se encuentra disponible el "Conjunto de datos edafológicos. Escala 1:1 000 000 serie I (2005, INEGI)", pero se decidió no utilizar esa información a pesar de ser más reciente que la que se presenta en el documento "3.1 Subsistema natural" debido a que no cuenta con metadatos y contiene solamente 7 tipos de suelo vs 12 tipos de suelo que contiene la información de INAFAP-CONABIO, 1995, considerando a esta última más completa y detallada. 

- Tabla 3.1.1 Tipos de suelo en el estado de Yucatán. Fuente: INIFAP-CONABIO, 1995; FAO, 2006.
Esta tabla fue elaborada con la información geográfica del apartado anterior, es por eso que tienen la misma fuente.

4)  Se agrega en las referencias el enlace de la fuente: http://bitacoraordenamiento.yucatan.gob.mx/archivos/200706294825.pdf

5) La Península de Yucatán es una zona de paso de un gran número de aves migratorias, además de tener una gran riqueza de especies residentes y endémicas de aves (Chablé et al, 2010). En el estado están registradas 479 especies de aves, 25 órdenes, 70 familias y 267 géneros. El orden más diverso es el de los Passeriformes con 217 especies, seguido por los Charadriformes con 62 (CONABIO, 2020).

6) La información solicitada se encuentra en el anexo 3.2 Caracterización del subsistema natural/Documentos y bases de datos, (anexo_sub_natural_documentacion_3_2),  apartado 3.2.2 Biota (vegetación y fauna silvestre), específicamente en las tablas:
**3.2.4** Especies de mamíferos del estado de Yucatán listados en la NOM-059-SEMARNAT-2010 
**3.2.7** Especies de aves relevantes en el estado de Yucatán
`Nota`: Se corrige el documento 3.1 Subsistema natural para especificar dichas tablas en él

@Nayita Listas las correcciones solicitadas, el archivo se encuentra en: FOMIX\fmx_procesamiento\documentos_corregidos\subsistema_natural_3_1

**Comment by milocortes** [comment]
> @milocortes
> 
> Favor de revisar y corregir en el documento el punto 7 del Anexo 1 (donde aparece tu nombre).
> Archivo subsitema_productivo_3_2

@Nayita ,se corrijió la observación al archivo subsistema_productivo_3_2. Las cifras corresponden a valores en millones de pesos. El archivo corregido se cargó a la ruta /FOMIX/fmx_procesamiento/documentos_corregidos

**Comment by ofegarcia** [comment]
Atendidas las observaciones relativas la subsistema socioeconómico. Se cargó el archivo corregido a la ruta /FOMIX/fmx_procesamiento/documentos_corregidos.

### **Respuesta a observaciones**
**4) Se identificaron varios enlaces que no están vigentes o actualizados, por mencionar uno, el caso de Mapa 3.3.19**. 
Se corrigieron enlaces erróneos o no vigentes en la Figura 3.3.20 y en el mapa 3.3.19. 
Se revisaron y actualizaron ligas a documentos referidos en la biografía para dirigir al lector al documento específico en mención.

**Anexo 1 del oficio**
**En la caracterización socioeconómica en sobre todo en el componente de Migración internacional, los datos que maneja son datos antiguos, por ejemplo “En 2004 el flujo migratorio de Yucatán era de 37,601 migrantes, de los cuales el 98% se fue a Estados Unidos; para 2011 se reportaron 45,000 migrantes originarios de 101 municipios del estado de Yucatán”.** 

Se incorporó información de 2018 y 2019 en los apartados de demografía, fecundidad, migración (interna e internacional), educación, salud y drenaje, proveniente de las siguientes fuentes: 

- INEGI, 2018. Encuesta Nacional de la Dinámica Demográfica
- Aguilar, Muradás y Gutiérrez, 2019. Proyecciones 2016-2050 de la Población de México y de las entidades federativas (Yucatán). 
Esta última referencia ya se había considerado en la caracterización, pero se había citado como 2016. Se actualizó la fecha, en virtud de haber sido publicado en 2019 y se adicionaron datos de proyecciones de migración.

**Comment by Nayita** [comment]
### Información actualizada en el informe 
Anexos

- [ ] anexo_diagnostico_documentacion_1_2.zip

- [ ] anexo_sub_natural_documentacion_3_2.zip

Documentos

- [ ] indice_anexos.pdf

- [ ] indice_estudio_tecnico.pdf

- [ ] diagnostico_1.pdf

- [ ] estrategia_2.pdf

- [ ] subsistema_natural_3_1.pdf

- [ ] subsistema_productivo_3_2.pdf

- [ ] subsistema_socioeconomico_3_3.pdf

Sección financiera

- [ ] \FOMIX\fmx_estudio_tecnico\entregas\seccion_financiera\COMPROBANTES\PASAJES Y VIATICOS\COMPLEMENTOS DE PAGO. Se creo la carpeta COMPLEMENTOS DE PAGO, de acuerdo al google drive de la Administración del instituto y se pusieron todos los archivos que contenía dicha carpeta.

Informe completo
Se actualizó:

- [ ] anexos_tecnicos.zip

- [ ] indice_general.zip

- [ ] informe_tecnico.pdf

- [ ] seccion_financiera.zip

**Comment by CorinaCantero** [comment]
### OBSERVACIONES PREVIAS A LA SEGUNDA ENTREGA - JULIO 2021
@dpedroza74 

Ubicación del oficio FOMIX/YUC/2021/071 enviado por CONACYT: 
FOMIX\fmx_docs_admin_proyecto\oficios_conacyt\fmx_yuc_2021_071

Peticiones para el 09/07/2021

- [ ] Un mapa de actores locales, necesario para realizar el proceso de consulta y talleres.
- [ ] Listado de todos los actores invitados a cada uno de los talleres, donde se especifique con
- [ ] cuánto tiempo de anticipación se les notificó y qué información se proporcionó al respecto.
- [ ] Listado de fuentes de información utilizadas para la realización de los mapas.
- [ ] Listado con el nombre de los miembros del Grupo de Trabajo que participaron directamente en los talleres de consulta y en el proceso de procesamiento de información, especificando las actividades que realizaron.

**Comment by dpedroza74** [comment]
@paola-gp @ofegarcia 

Subí en dropbox FOMIX/fmx_docs_admin_proyecto/oficios_conacyt el docucmento
respuesta Oficio FOMIX-YUC-2021-071
con la información del punto 1 - mapa de actores y el punto 4  listado miembros grupo de trabajo que participaron en talleres

**Comment by CorinaCantero** [comment]
### AVISO
@dpedroza74 

El archivo respuesta Oficio FOMIX-YUC-2021-071 se moverá a la carpeta: \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\conacyt, en esa ubicación se guardarán todos los archivos de respuesta para CONACYT respecto a los talleres de aptitud.

**Comment by paola-gp** [comment]
@dpedroza74 

Ya está completa y en plantilla la respuesta del punto 3 en: listado_fuentes_informacion.docx (y versión pdf).

**Comment by paola-gp** [comment]
@dpedroza74 @CorinaCantero 

/FOMIX/fmx_estudio_tecnico/diagnostico/talleres/conacyt están los cuatro anexos al oficio de respuesta en formato pdf, por si se necesitan mover a otra ubicación.

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
