### ISSUE TITLE
Preparar reunión con Secretaria SDS Yucatán TBD

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#51]
Ubicación de los productos (bases de datos listas para Tableau y mapas provisionales): \SIG\desarrollo\sig_fomix\procesamiento\presentacion_sds

Generación de bases de datos de:
@vichdzgeo 
#### Vulnerabilidad

- [x] 1.  Vulnerabilidad intrínseca de agua promedio por municipios

- [x] 1.1.  Calcular vulnerabilidad intrínseca promedio en zonas urbanas con ID municipales

- [x] 1.2.  Calcular vulnerabilidad intrínseca promedio en ANP con ID municipales

- [x] 1.3 Hacer un filtro de 1 en municipios costeros

#### Fragilidad 

- [x] 2.  Fragilidad promedio por municipios en dos fechas

- [ ] 2.1.  Hacer un filtro de 1 en zonas urbanas **No se puede**

- [x] 2.2.  Calcular fragilidad promedio en ANP y añadir con ID municipales

- [x] 2.3 Hacer un filtro de 1 en municipios costeros

#### Capital natural 
@CorinaCantero 

- [x] Preparar capas geográficas de capital natural

- [x] Índice de capital natural (ICN) por municipios
- [x] Índice de degradación ecológica (IDE) por municipios
- [x] Índice de impacto antropogénico (IIA) por municipios
- [x] Índice de integridad ecológica (IIE) por municipios
- [x] Índice de sustentabilidad de capital natural 
Fuente: http://geoportal.conabio.gob.mx/

**Comment by CorinaCantero** [comment]
### AVISO

Listas capas índice de capital natural recortadas y con protocolo de bases de datos del APC, ubicación: SIG\desarrollo\sig_fomix\entregables\ind_cap_natural


Índice | Carpeta
-- | --
Índice de capital natural (ICN) por municipios | ind_cap_nat
Índice de degradación ecológica (IDE) por municipios | ind_degra_ecol
Índice de impacto antropogénico (IIA) por municipios | ind_impacto_antrop
Índice de integridad ecológica (IIE) por municipios | ind_integ_eco
Índice de sustentabilidad de capital | ind_sust_cn

**Comment by vichdzgeo** [comment]
@CorinaCantero indicar la ruta de los polígonos de las zonas urbanas.

**Comment by CorinaCantero** [comment]
**AVISO**
@vichdzgeo Ubicación capa localidades urbanas: SIG\desarrollo\sig_fomix\entregables\loc_urb_svi_a\loc_urb_svi_a.shp

**Comment by vichdzgeo** [comment]
# Vulnerabilidad intrínseca 
 
Ruta: SIG\desarrollo\sig_fomix\procesamiento\indice_calidad\

# Acuerdos 
En la reunión establecida con Luis y Fidel, se acordó 

1. clasificar la vulnerabilidad de acuerdo a lo siguiente: -> insumos\agua\presentacion_secretariavulnerabildiad_intrinseca.shp

|CLASIFIC|vuln|
|--|---|
BAJO| 0.0625|
|MEDIO|0.0125|
|ALTO|0.25|
|MUY ALTO|0.5|
|EXTREMO|1|

2. Digitalizar los espacios faltantes dentro de la zona de estudio y asignarle el valor de vuln más cercano `insumos\agua\presentacion_secretariaareas_vulnerabilidad_intrinseca_faltantes.shp`
3. Generar el raster  `->  insumos\agua\presentacion_secretariavulnerabilidad_intrinseca_agua_batllori.tif`
4. Calcular el valor promedio de vulnerabilidad por municipio  `-> procesamiento_presentacion\municipios\vulnerabilidad_intrinseca_agua_mun.shp`
5. Calcular el valor promedio de vulnerabilidad por municipio costero` ->procesamiento_presentacion\municipios\vulnerabilidad_intrinseca_agua_mun_costeros.shp`
6. calcular el valor promedio por anp (cruzada con municipios), se calculo tanto para anp federal como para anp municipal, estatal y privadas `procesamiento_presentacion\anp\`
7. calcular el valor promedio por zonas urbanas ` procesamiento_presentacion/loc_urb_svi_a/`

# Producto

## Ruta
\SIG\desarrollo\sig_fomix\procesamiento\presentacion_sds\vulnerabilidad_intrinseca_agua

- vulnerabilidad_intrinseca_agua_anp_est_mun_priv.csv
- vulnerabilidad_intrinseca_agua_anp_federales.csv
- vulnerabilidad_intrinseca_agua_localidades_urbanas.csv
- vulnerabilidad_intrinseca_agua_mun.csv
- vulnerabilidad_intrinseca_agua_mun_costeros.csv

**NOTAS:**

- Todas las tablas tienen el campo **cve_mun**

- las tablas **vulnerabilidad_intrinseca_agua_anp_est_mun_priv** y **vulnerabilidad_intrinseca_agua_anp_federales** contienen el campo **nombre** el cual corresponde al nombre del anp 

- la tabla **vulnerabilidad_intrinseca_agua_localidades_urbanas** contiene el campo **cve_loc** que corresponde a la clave de la localidad asignada por INEGI y el campo **nombre** que corresponde al nombre de la localidad

**Comment by vichdzgeo** [comment]
# Fragilidad del territorio 

## Produtos

tablas en formato csv

###  Ruta 
sig_fomix\procesamiento\presentacion_sds\fragilidad


Producto | Descripción
-- | --
fragilidad_anp_est_mun_priv_2002_2014.csv | fragilidad promedio por anp (estatales,municipales y privadas) cruzadas   con los municipios
fragilidad_anp_federales_2002_2014.csv | fragildiad promedio de anp federales cruzadas con municipios
fragilidad_municipios_2002_2014.csv | fragilidad promedio por municipio para los años 2002 y 2014
fragilidad_municipios_costeros_2002_2014.csv | fragilidad promedio por municipio costero    para los años 2002 y 2014


**NOTAS:**
- Todas las tablas tienen el campo **cve_mun**
- las tablas **fragilidad_anp_est_mun_priv_2002_2014** y **fragilidad_anp_federales_2002_2014** contienen el campo nombre el cual corresponde al nombre del anp

**Comment by vichdzgeo** [comment]
# Capital natural 

## Ruta

sig_fomix\procesamiento\presentacion_sds\capital_nat

Producto | Descripción | campo del índice | Notas
-- | -- | -- | --
indice_capital_natural.csv | Índice de capital natural (ICN) por municipios | ind_cn |  
indice_degradacion_ecologica.csv | Índice de degradación ecológica (IDE) por municipios | ind_deg_ec |  
indice_impacto_antropogenico.csv | Índice de impacto antropogénico (IIA) por municipios | ind_imp_an |  
indice_integridad_ecologica.csv | Índice de integridad ecológica (IIE) por municipios | pind_ie |  
indice_sustentabilidad_de_capital.csv | Índice de sustentabilidad de capital natural | sust_clas | campo con tres categorías: Sustentable, En riesgo, No sustentable

**Comment by vichdzgeo** [comment]
## Shape

Se agregan los archivos vectoriales  para realizar las uniones en proyección wgs84

### Ruta 
shapes/


- municipios_yuc.shp
- localidades_urbanas.shp
- anp_federales_yuc.shp
- anp_municipales_estatales_privadas_yuc.shp

**Comment by vichdzgeo** [comment]
@paola-gp

**Comment by CorinaCantero** [comment]
Mapas preparados para la presentación: 
Ubicación: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\mapas_anio_dos\presentaciones

![calidad_recursos_naturales](https://user-images.githubusercontent.com/44783182/93268002-1f332780-f772-11ea-9a34-232fc1b3cfd3.png)
![fragilidad_s3](https://user-images.githubusercontent.com/44783182/93268013-23f7db80-f772-11ea-9f4e-b3a85e73a232.png)
![fragilidad_s6](https://user-images.githubusercontent.com/44783182/93268024-2823f900-f772-11ea-81e7-9ecccea5fd20.png)
![usv_s1_s3](https://user-images.githubusercontent.com/44783182/93268035-2c501680-f772-11ea-8a9e-535869a5dfa7.png)
![usv_s3_s6](https://user-images.githubusercontent.com/44783182/93268044-2fe39d80-f772-11ea-83a6-356ce4a40c0f.png)

**Comment by CorinaCantero** [comment]
### Mapas generados para la presentación: 
Ubicación: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\mapas_anio_dos\presentaciones

![calidad_recursos_naturales](https://user-images.githubusercontent.com/44783182/93268813-7e456c00-f773-11ea-9a55-3c74a9b520ae.png)
![fragilidad_s3](https://user-images.githubusercontent.com/44783182/93268817-80a7c600-f773-11ea-98cb-dfdb02ad95e4.png)
![usv_s1_s3](https://user-images.githubusercontent.com/44783182/93268822-843b4d00-f773-11ea-8184-502b89a86a60.png)
![usv_s3_s6](https://user-images.githubusercontent.com/44783182/93268825-856c7a00-f773-11ea-8e0e-d98b9ae0c7cf.png)

**Comment by vichdzgeo** [comment]
## Visualizadores

## Aptitud y vulnerabilidad 

http://sig.apps.lancis.ecologia.unam.mx/index.php/view/map/?repository=apvuln&project=vulnerabilidad_aptitud_yuc

## Caracterización 

http://sig.apps.lancis.ecologia.unam.mx/index.php/view/map/?repository=natural&project=subsistemas_fomix

**Comment by paola-gp** [comment]
@CorinaCantero @Nayita @dpedroza74: favor de indicar dónde deberán quedar alojadas las presentaciones del 18/sep/20

**Comment by CorinaCantero** [comment]
### AVISO
@paola-gp @dpedroza74 @Nayita 
Ubicación para guardar las presentaciones: FOMIX\fmx_reuniones_sds\presentacion_18sep20

**Comment by paola-gp** [comment]
#### Insumos presentación 18 de septiembre de análisis de aptitud

Se encuentran reportados en https://github.com/lancis-apc/planeacion-colaborativa/issues/849#issuecomment-692886238
