### ISSUE TITLE
Compilar información para el pronóstico de #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#53]
### Aviso

Los archivos de la información recabada se pondrán en la siguiente ruta: FOMIX\fmx_estudio_tecnico\pronostico\insumos

**Comment by Nayita** [comment]
### Bases de datos descargados para el estado de Yucatán

**Agua**
Municipios y delegaciones con servicios de agua potable, alcantarillado y tratamiento de aguas residuales
Agua suministrada al día por habitante para consumo humano
Cobertura de la población con agua potable
Cobertura de población con alcantarillado 
Población con agua potable
Población con alcantarillado
Sitios de monitoreo de calidad del agua superficial que miden DQO, por nivel de calidad del agua 
Sitios de monitoreo de calidad del agua superficial que miden SST, por nivel de calidad del agua
Sitios de monitoreo de calidad del agua superficial que miden DBO5, por nivel de calidad del agua
Municipios y delegaciones por disponibilidad de tratamiento de aguas residuales municipales

**Energía**
Capacidad instalada y generación de electricidad por sector y fuente de energía limpia
Sitios de proyectos con potencial de generación de electricidad por tipo de proyecto y fuente de energía limpia

**Comment by Nayita** [comment]
### Documentos

**Agua**
Escenarios futuros. CONAGUA

**Energía**
Programa del desarrollo eléctrico nacional 2017-2031
Programa sectorial de energía 2020-2024
Prospectiva de energías renovables 2016-2030
Prospectiva del sector eléctrico 2013-2027

Programa Nacional de Desarrollo 2020-2024

**Comment by Nayita** [comment]
### ENERGÍA

Información | Archivo | Ubicación
-- | --
Capacidad instalada y generación de electricidad por sector y fuente de energía limpia  | Nombre de la capa del insumo original
Fuente | Fuente del insumo
Año | Año de publicación

**Comment by Nayita** [comment]
### INFORMACIÓN ACTUALIZADA

### Bases de datos descargados para el estado de Yucatán

**Agua**
Municipios y delegaciones con servicios de agua potable, alcantarillado y tratamiento de aguas residuales
Agua suministrada al día por habitante para consumo humano
Cobertura de la población con agua potable
Cobertura de población con alcantarillado 
Población con agua potable
Población con alcantarillado
Sitios de monitoreo de calidad del agua superficial que miden DQO, por nivel de calidad del agua 
Sitios de monitoreo de calidad del agua superficial que miden SST, por nivel de calidad del agua
Sitios de monitoreo de calidad del agua superficial que miden DBO5, por nivel de calidad del agua
Municipios y delegaciones por disponibilidad de tratamiento de aguas residuales municipales

**Energía**
Capacidad instalada y generación de electricidad por sector y fuente de energía limpia
Sitios de proyectos con potencial de generación de electricidad por tipo de proyecto y fuente de energía limpia

**Capas**
Zonas calificadas de alto potencial de energías limpias
Zonas disponibles con alto potencial

- solar 
  solar FV fijo 
  escenario 1
  escenario 2
  escenario 3
  escenario 4

  solar FV con seguimiento 
  escenario 1
  escenario 2
  escenario 3
  escenario 4

- eólica
  eólica nacional 
  escenario 1
  escenario 2
  escenario 3
  escenario 4

- geotérmica
  escenario 1
  escenario 2
  escenario 3
  escenario 4

- biomasa
  escenario 1
  residuos pecuarios
  residuos industriales
  residuos urbanos
  residuos forestales

  escenario 2
  residuos pecuarios
  residuos industriales
  residuos urbanos
  residuos forestales

  escenario 3
  residuos pecuarios
  residuos industriales
  residuos urbanos
  residuos forestales

**Comment by Nayita** [comment]
### Tabla con la información de los documentos de la carpeta de energía

Información | Documento | Archivo | Ubicación
-- | -- | -- | --
Yutacán   representa el 10% (4,521.3 GWh) de ventas internas de energía eléctrica de la   región sur-sureste (31,123 GWh).     En Mérida se ubica el centro regional peninsular del Sistema Eléctrico   Nacional (SEN).     Datos de la Capacidad de transmisión entre regiones del SEN. Contiene   diferentes tablas con datos de estimaciones prospectivas de consumo eléctrico   bruto, de demanda  a  nivel peninsular. Crecimiento medio anual de   consumo bruto a nivel peninsular será de 5.6% del 2012-2021 y del 5.8% del   2012-2027. Escenarios de expansión del sistema eléctrico; Datos de capacidad   adicional futura y evolución esperada del consumo de combustibles fósiles y   la red de transmisión; y Requerimientos de capacidad. | Prospectiva del sector eléctrico   2013-2027 | prospectiva_sector_electrico_2013-2027.pdf | FOMIX\fmx_estudio_tecnico\pronostico\insumos\energia
  | Evaluación rápida del uso de la   energía. Mérida, Yucatán México | evaluac_uso_energia_yucatan.pdf | \FOMIX\fmx_estudio_tecnico\pronostico\insumos\energia
Capacidad   instalada y generación de electricidad por sector y fuente de energía   limpia | Capacidad instalada y generación   de electricidad por sector y fuente de energía limpia | capacidad_electrica_energia_limpia.xlsx | \FOMIX\fmx_estudio_tecnico\pronostico\insumos\energia
Contiene información estatal y regional   del sistema eléctrico del 2013 al 2027. En particular, en infraestructura del   SEN, consumo y demanda de energía eléctrica, programa indicativo para la   instalación y retiro de centrales eléctricas, programa de ampliación y   modernización de la red nacional de transmisión, programa de ampliación y   modernización de las redes generales de distribución y el resumen de   inversiones 2017-2031 | Programa de Desarrollo del   Sistema Eléctrico Nacional 2017-2031 PRODESEN | prodesen_2017_2031.pdf | \FOMIX\fmx_estudio_tecnico\pronostico\insumos\energia
Programa   sectorial derivado del Plan Nacional de Desarrollo 2019-2024. Metas para el   bienestar y Parámetros (métodos de cálculo e indicadores) | Programa Sectorial de Energía   2020-2034 | programa_sectorial_energia_2020-2024.pdf | \FOMIX\fmx_estudio_tecnico\pronostico\insumos\energia
Sitios   de proyectos con potencial de generación de electricidad por tipo de proyecto   y fuente de energía limpia | Sitios de proyectos con   potencial de generación de electricidad por tipo de proyecto y fuente de   energía limpia | sitios_potencial_energia.xlsx | \FOMIX\fmx_estudio_tecnico\pronostico\insumos\energia
Explicación   en qué consisten los escenarios en AZEL. Escenarios nacionales de las   diferentes energías renovables (limpias). Tabla de disponibilidad potencial   de biomasa de esquilmos en la que aparecen datos para Yucatán. Tablas de   superficie aprovechable de bosques y selvas nativas para potencial de biomasa   forestal leñosa y energética (dato para Yucatán). | Prospectiva de Energías   Renovables 2016-2030 | prospectiva_energias_renovables_2016-2030.pdf | \FOMIX\fmx_estudio_tecnico\pronostico\insumos\energia

**Comment by Nayita** [comment]
### Tabla con la información de los archivos de la carpeta de agua


Información | Documento | Archivo | Ubicación
-- | -- | -- | --
Información   regional de tendencias de agua renovable (Península de Yucatán)   2010-2030 | Escenarios futuros | escenarios_futuros.pdf | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Agua suministrada al día por   habitante para consumo humano | agua_dia_habitantes.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Sitios de monitoreo de calidad   del agua superficial que miden DBO5, por nivel de calidad del agua | calidad_agua_dbo5.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Sitios de monitoreo de calidad   del agua superficial que miden DQO, por nivel de calidad del agua | calidad_agua_dqo.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Sitios de monitoreo de calidad   del agua superficial que miden SST, por nivel de calidad del agua | calidad_agua_sst.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Cobertura de la población con   agua potable | cobertura_agua_potable.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Cobertura de población con   alcantarillado | cobertura_alcantarillado.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Población con agua potable | poblacion_agua_potable.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Población con alcantarillado | poblacion_alcantarillado.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Municipios y delegaciones con   servicios de agua potable, alcantarillado y tratamiento de aguas | servicios_agua.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua
Información para Yucatán | Municipios y delegaciones por   disponibilidad de tratamiento de aguas residuales municipales | tratamiento aguaresidual_municipal.xlsx | FOMIX\fmx_estudio_tecnico\pronostico\insumos\agua

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
