### ISSUE TITLE
Integrar informe del análisis de aptitud del sector silvopastoril #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#54]
### [TALLER GANADERÍA SILVOPASTORIL](https://lancis-apc.github.io/fomix/ga_silvopastoril_pr.html)
 

- **Ubicación de insumos para informe:** FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\silvopastoril

- **Ubicación de productos del taller:**
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\silvopastoril

**Comment by CorinaCantero** [comment]
Capa | Nombre del insumo | Escala | Fuente | Año | Notas | Ubicación en Dropbox
-- | -- | -- | -- | -- | -- | --
Modelo   digital de terreno |   |   |   |   | Hay modelo digital de elevación   tipo terreno:   https://www.inegi.org.mx/temas/relieve/continental/default.html#Descargas |  
Pendiente |   |   |   |   |   |  
Vegetación | Conjunto de datos vectoriales de   la carta de Uso del suelo y vegetación. Escala 1:250 000. Serie VI. Conjunto   Nacional | 1:250,000 | INEGI | 2017 |   | SIG\desarrollo\sig_fomix\entregables\sub_natural\usv_serie6\usv_serie6.shp
Agrícola   - cultivos pastos y praderas | Uso de suelo y vegetación para   el estado de Yucatán serie VI | 1:250,000 |   | 2017 | Clasificación de las categorías:   agropecuario, asentamientos humanos, natural. La categoría agropecuario   contiene: pastizal cultivado, pastizal inducido, pastizal halófilo,   agricultura, palmar inducido, acuícola y bosque cultivado | SIG\desarrollo\sig_fomix\entregables\sub_natural\usv_serie6\usv_serie6
Estado   de la vegetación |   |   |   |   | Hay capa de índice de calidad de   los recursos naturales  (suelo,   vegetación y agua superficial) |  
Infraestructura   de riego |   |   |   |   |   |  
Tipo de   suelo | Conjunto de datos vectoriales   edafológico, Serie II (Continuo Nacional) | 1:250,000 | INEGI | 2014 | Campo: Clave_WRB | \SIG\desarrollo\sig_fomix\insumos\geocientifica\semarnat\edafologia_sii\edafologia_sii
Textura   del suelo | Conjunto de datos vectoriales   edafológico, Serie II (Continuo Nacional) | 1:250,000 | INEGI | 2014 | Campo: Clase_tex | \SIG\desarrollo\sig_fomix\insumos\geocientifica\semarnat\edafologia_sii\edafologia_sii
Humedales | Sitios RAMSAR de México |   |   |   |   | SIG\desarrollo\sig_fomix\entregables\sub_natural\ramsar\ramsar
Cenotes | Red hidrográfica | 1:50,000 | INEGI | 2010 |   | SIG\desarrollo\sig_fomix\insumos\agua\inegi\red_hidrografica\rh_yuc\cenotes_yuc
Cuerpos   de agua | Red hidrográfica | 1:50,000 | INEGI | 2010 | Contiene: esteros, lagunas,   salina, manantial, río |  
Acuíferos | Datos vectoriales de la   disponibilidad de los acuíferos | 1:250,000 | CONAGUA | 2018 |   | SIG\desarrollo\sig_fomix\insumos\agua\conagua\dispon_acuiferos
Pozos | Red piezométrica mapas |   | CONAGUA | 2016 | https://datos.gob.mx/busca/dataset/red-piezometrica-mapas | SIG\desarrollo\sig_fomix\insumos\agua\conagua\pozos_agua\pozos_agua
Profundidad   del manto freático |   |   |   |   |   |  
Precipitación | Precipitación media anual (mm) |   | UNAM | 2001 | ¿Utilizar información de   precipitación media anual, precipitación total anual…? |  
Morfoedafología |   |   |   |   | Hay una capa del POETCY,   metadato:   https://bitacoraordenamiento.yucatan.gob.mx/archivos/200707260875.htm |  
Climas | Climas | 1:1,000,000 | García, E. - Comisión Nacional   para el Conocimiento y Uso de la Biodiversidad (CONABIO) | 1998 |   | \SIG\desarrollo\sig_fomix\entregables\sub_natural\clima\clima.shp
Rellenos   sanitarios |   |   |   |   |   |  
Basurero   municipal (distancia menor a 5 km, mayor a 5 km) |   |   |   |   |   |  
Rastros   / Centros De Sacrificio |   |   |   |   | SIAP Infraestructura del Sector   Agroalimentario https://cmgs.gob.mx:31/infraestructuras/. La información  fue solicitada en el portal de   transparencia, fecha para respuesta 19/10/2020 |  
Distancia   a carreteras | Red nacional de caminos |   | INEGI | 2019 | Contiene: ampliación, avenida,   boulevard, calle, calzada, camino, carretera, circuito, eje vial, enlace,   glorieta, periférico, prolongación, retorno, vereda y viaducto | SIG\desarrollo\sig_fomix\insumos\transporte\inegi\red_vial
Distancia   a caminos | Red nacional de caminos |   | INEGI | 2019 |   |  
Instalación   industrial | Conjuntos de datos vectoriales   de información topográfica escala  por   Entidad Federativa serie VI. | 1:250 000 | INEGI | 2019 |   |  
Líneas   eléctricas | Conjuntos de datos vectoriales   de información topográfica escala  por   Entidad Federativa serie VI. | 1:250 000 | INEGI | 2019 | Subestación eléctrica, líneas de   transmisión de energía eléctica, planta de generación de energía eléctrica | \SIG\desarrollo\sig_fomix\insumos\geocientifica\inegi\topografia_svi\conjunto_de_datos\linea_transm250.shp
Distancia   a red eléctrica | Conjuntos de datos vectoriales   de información topográfica escala  por   Entidad Federativa serie VI. | 1:250 000 | INEGI | 2019 | Subestación eléctrica, líneas de   transmisión de energía eléctica |  
Plantas   de tratamiento de aguas residuales | Plantas de Tratamiento de Aguas   Residuales |   | CONAGUA | 2017 |   | SIG\desarrollo\sig_fomix\insumos\agua\conagua\planta_agua_residual\pl_agua_residual_2017_wgs84
Zonas   urbanas | Conjuntos de datos vectoriales   de información topográfica escala  por   Entidad Federativa serie VI. | 1:250 000 | INEGI | 2019 |   | \SIG\desarrollo\sig_fomix\insumos\geocientifica\inegi\topografia_svi\conjunto_de_datos\localidad250_a.shp

**Comment by paola-gp** [comment]
Preparación de tabla @CorinaCantero 


Columna | Descripción
-- | --
Insumo | Nombre de la capa del insumo original
Fuente | Fuente del insumo
Año | Año de publicación
Ubicación insumo | Ruta del insumo original
Ubicación salida | Ruta del conjunto de datos de salida
Nombre salida (raster) | Nombre de la capa de salida
Modificación | Reclasificación, buffer (km), ninguna, etc.
Archivos de procesamiento | reclass.txt
Tipo de datos | Nominal, cociente
Presencia de NO DATA | Si, No
Número de categorías (nominal) | Número
Notas |

**Comment by vichdzgeo** [comment]
@CorinaCantero @serranoycandela 

El archivo de requerimientos para las capas geográficas se encuentra en SIG\desarrollo\sig_fomix\procesamiento\taller_aptitud_ganadera\requerimientos_capas_geograficas.docx

El archivo con las funciones para los insumos se encuentra en:
SIG\desarrollo\sig_fomix\procesamiento\taller_aptitud_ganadera\funciones_insumos.py

**Comment by paola-gp** [comment]
@CorinaCantero: favor de publicar la ubicación de los insumos de los talleres

**Comment by paola-gp** [comment]
@Nayita

**Comment by CorinaCantero** [comment]
### AVISO
Ubicación para productos del taller del sector ganadero: 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\ganaderia

Se crearon tres carpetas: 
- Modelo
- Funciones de valor
- Presentaciones

@paola-gp @dpedroza74

**Comment by CorinaCantero** [comment]
### Información cargada a la plataforma SIGplanning para el taller 23/10/2020

Insumo | Nombre | Fuente | Año | Tipo de datos
-- | -- | -- | -- | --
Conjunto de datos vectoriales de la carta   de Uso del suelo y vegetación. Escala 1:250 000. Serie VI. | Cobertura con categorías de INEGI | INEGI | 2017 | Nominal
Conjunto de datos vectoriales de la carta   de Uso del suelo y vegetación. Escala 1:250 000. Serie VI. | Cobertura con 16 categorías | INEGI | 2017 | Nominal
Conjunto de datos vectoriales de la carta   de Uso del suelo y vegetación. Escala 1:250 000. Serie VI. | Cobertura con 2 categorías (natural, no natural) | INEGI | 2017 | Nominal
Conjunto de datos vectoriales de la carta   de Uso del suelo y vegetación. Escala 1:250 000. Serie VI. | Cobertura con 3 categorías (natural, agropecuario y asentamientos   humanos) | INEGI | 2017 | Nominal
Conjunto de datos vectoriales   edafológico, Serie II (Continuo Nacional) | Tipo de suelo | INEGI | 2014 | Nominal
Modelo Cartográfico de Humedales | Humedales (distancia) | INEGI | 2014 | Distancia
Modelo Cartográfico de Humedales | Humedales (presencia) | INEGI | 2014 | Binario
Red Hidrográfica Edición 2 | Cuerpos de agua (distancia) | INEGI | 2010 | Binario
Red Hidrográfica Edición 2 | Cuerpos de agua (presencia) | INEGI | 2010 | Distancia
Red Piezométrica mapas | Pozos (presencia) | CONAGUA | 2016 | Binario
Red Piezométrica mapas | Pozos (distancia) | CONAGUA | 2016 | Distancia
Precipitación total anual | Precipitación | García, E. - CONABIO | 1998 | Nominal
Sitios de disposición final | Basureros (distancia) | SEMARNAT | 2017 | Distancia
Plantas de tratamiento de aguas   residuales | Plantas de tratamiento de agua residual (distancia) | CONAGUA | 2017 | Distancia
Isotermas Medias Anuales | Isotermas medias anuales | García, E. - CONABIO | 1998 | Nominal
Temperatura mínima promedio | Temperatura mínima | García, E. - CONABIO | 1998 | Nominal
Temperatura máxima promedio | Temperatura máxima | García, E. - CONABIO | 1998 | Nominal
Insumo de capa vulnerabilidad intrínseca   del acuífero - Nivel freático | Nivel freático | Batllori Sampedro, E. y Canto Mendiburu, S | 2019 | Continua
Población ocupada por sector de actividad   económica para el estado de Yucatán | Disponibilidad mano de obra | INEGI | 2015 | Continua
Población ocupada por sector de actividad   económica para el estado de Yucatán | Población femenina | INEGI | 2015 | Continua
Conjuntos de datos vectoriales de   información topográfica escala  por   Entidad Federativa serie VI. Zonas urbanas | Localidades | INEGI | 2019 | Distancia
Conjuntos de datos vectoriales de   información topográfica escala  por   Entidad Federativa serie VI. Zonas urbanas | Localidades (más de 2,500 hab) | INEGI | 2019 | Distancia
Conjuntos de datos vectoriales de   información topográfica escala  por   Entidad Federativa serie VI. Zonas urbanas | Localidades (más de 15,000 hab) | INEGI | 2019 | Distancia
Conjuntos de datos vectoriales de   información topográfica escala  por   Entidad Federativa serie VI. Zonas urbanas | Localidades (más de 50,000 hab) | INEGI | 2019 | Distancia
Conjuntos de datos vectoriales de   información topográfica escala  por   Entidad Federativa serie VI. Zonas urbanas | Localidades urbanas* | INEGI | 2019 | Distancia

*Nota: De acuerdo con INEGI las localidades se clasifican en:
- Rurales: con menos de 2,500 habitantes y que no son cabecera municipal
- Urbanas: con 2,500 habitantes o más o que son cabecera municipal.

**Comment by CorinaCantero** [comment]
### AVISO
@vichdzgeo 

Lista la capa de caminos reclasificada: 
0 Peatonal
1 Tránsito urbano rápido
2 Tránsito urbano lento
3 Tránsito rural
4 Carretera o autopista
5 Vereda o terracería

Ubicación: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\sector_ganadero\insumos\caminos\dist_caminos.shp

**Comment by Nayita** [comment]
### AVISO

Ruta de los audios (taller 6/11/2020): FOMIX\fmx_estudio_tecnico\diagnostico\talleres\ganaderia\audios
Archivos: taller_ganaderia_1_6nov2020.m4a 
               taller_ganaderia_2_6nov2020.m4a

Ruta de los videos (taller 6/11/2020):FOMIX\fmx_estudio_tecnico\diagnostico\talleres\ganaderia\imagenes
Proyectos: taller_ganaderia_1_6nov2020.tscproj
                 taller_ganaderia_2_6nov2020.tscproj

Ruta de figuras de funciones de valor: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\ganaderia\funciones_valor
Archivos: fi_fv_disponibilidad_agua.png
               fi_fv_dist_mercados_foraneos.png               
               fi_fv_dist_mercados_loc.png
               fi_fv_precipitacion.png
               fi_fv_sec_primario.png
               fi_fv_temperatura.png

**Comment by paola-gp** [comment]
@vichdzgeo: preparar lizmap con insumos y resultados de silvicultura
@Nayita @vichdzgeo: actualizar diagrama y preparar insumos para Sphinx
@CorinaCantero, actualizar cobertura y tipo de suelo con base en clasificación wf 1.6 del archivo: \talleres\insumos/rank_order.xlsx

**Comment by paola-gp** [comment]
@vichdzgeo 

Llevar a ideal las funciones de valor:
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\ganaderia\funciones_valor

fv_gbe_sil_bio_temp_max
fv_gbe_sil_socio_d_mercados_for

**Comment by paola-gp** [comment]
Nombramiento de archivos con base en **prefijos_ganaderia_bovina.xlsx**:

**fi_nombre** para las gràficas de funciones continuas
**mapa_nombre** para los mapas
**tabla_nombre** para las funciones de valor discretas

**Comment by paola-gp** [comment]
Estructura

- Modelo (ahp) con pesos

- Definiciones

- Funciones de valor: gráfica o tabla y mapa

- Mapa resultado de silvicultura

**Comment by vichdzgeo** [comment]
@Nayita @CorinaCantero 
Ruta de Sphinx:

vhernandez\aptitud_fomix_docs\docs\source\

**Comment by vichdzgeo** [comment]
> @vichdzgeo
> 
> Llevar a ideal las funciones de valor:
> FOMIX\fmx_estudio_tecnico\diagnostico\talleres\ganaderia\funciones_valor
> 
> fv_gbe_sil_bio_temp_max
> fv_gbe_sil_socio_d_mercados_for

@paola-gp  las capas ya han sido actualizadas, se rescribieron en la misma carpeta.

**Comment by vichdzgeo** [comment]
## liga de documentación en Sphinx

https://lancis-apc.github.io/fomix/

**Comment by vichdzgeo** [comment]
## Estilos para mapas

Ruta: C:\Dropbox (LANCIS)\SIG\desarrollo\sig_fomix\paletas

### Aptitud con 6 categorias

- paleta_aptitud_6_categorias_semaforo.qml

**Comment by vichdzgeo** [comment]
## Recursos documentación 
@Nayita ya están los recursos faltantes para la documentación

**Gráfica del análisis de sensibilidad del mapa de aptitud silvopastoril** 
-fi_analisis_sensibilidad_silvopastoril.png 

**Tabla de áreas en km² por categorías**
- tabla_areaskm2_porcentaje_aptitud_equidistante.csv

**Comment by CorinaCantero** [comment]
### AVISO

@Nayita listos los mapas actualizados con la plantilla. CARPETAS_TRABAJO\vhernandez\aptitud_fomix_docs\docs\source\recursos

**Comment by Nayita** [comment]
### AVISO

@vichdzgeo 

Listo el md con las tablas. Ruta: C:\Dropbox (LANCIS)\CARPETAS_TRABAJO\vhernandez\aptitud_fomix_docs\docs\source. 

Revisar la tabla de Área por categoría de actitud.

**Comment by vichdzgeo** [comment]
# AVISO

@paola-gp 

La documentación ha sido actualizada

https://lancis-apc.github.io/fomix/

NOTAS:
-  Se cambia la forma de generar la documentación para tener más control respecto a la alineación de tablas, ahora se genera en archivos  MD (markdown)

**Comment by vichdzgeo** [comment]
## Aviso

@CorinaCantero Actualizar las imágenes de los mapas corregidos y sustituirlas en la documentación.

ruta = o\sig_fomix\procesamiento\analisis_aptitud\sector_ganadero\procesamiento\aptitud
Se corrigieron dos mapas:
 

- **gbe_sivopastoril_exclusion.tif** Se agregaron dos categorías más al mapa de exclusión: Pastizal halófilo y Vegetación secundaría Arbustiva de Manglar
- **gbe_silvopastoril.tif** Se aplico de nuevo la máscara al mapa de aptitud

**Comment by CorinaCantero** [comment]
### AVISO
@vichdzgeo Listas las correcciones

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de hacer las siguientes correcciones en el informe:

- [ ] Sección 1.2.1.1 tabla de insumos de cobertura cambiar el año de 2014 a 2017
- [ ] Sección 1.2.2.1.1 tabla de insumos accesibilidad a mercados locales cambiar unidades de "Adimensional" a "Kilómetros"
- [ ] Sección 1.2.2.1.2 tabla de insumos accesibilidad a mercados foráneos cambiar unidades de "Adimensional" a "Kilómetros"
- [ ] Agregar la tabla de insumos en la sección 1.3.1 Capa de exclusión 

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Aviso

Ruta: talleres\sectores\silvopastoril\funciones_valor

Se actualizaron y corrigieron las funciones de valor de silvopastoril, las versiones anteriores se movieron a la carpeta auxiliares. quedan en su lugar las capas actualizadas.

Actualizar figuras de mapas de las funciones de valor @CorinaCantero 

- fv_gbe_sil_bio_usv_inegi.tif
- fv_gbe_sil_bio_temp_max.tif
- fv_gbe_sil_bio_precipitacion.tif

**Comment by vichdzgeo** [comment]
## Tabla de área por categoría de silvopastoril 
@Nayita  actualizar tabla en el informe

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 19591.3 | 50
Alta | 11542.5 | 29
Moderada | 4286.5 | 11
Baja | 543.7 | 1
Muy baja | 714 | 2
Nula | 2858.6 | 7

**Comment by vichdzgeo** [comment]
## Actualizar 

- [ ] fi_analisis_sensibilidad_silvopastoril.png Figura de sensibilidad @Nayita 
- [ ] gbe_silvopastoril.tif figura de mapa categorizado para aptitud silvopastoril.  @CorinaCantero 
- [ ] gbe_silvopastoril_exclusion. figura de mapa de exclusión @CorinaCantero

**Comment by CorinaCantero** [comment]
### CORRECCIONES
@Nayita 

- [ ] Por favor incluir en el modelo de decisión de silvopastoril en el atributo socioeconómico accesibilidad a mercados los criterios: accesibilidad a mercados locales y accesibilidad a mercados foráneos

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
