### ISSUE TITLE
Atender observaciones SDS informe etapa 1 #FOMIX

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#55]
Andrés Sierra nos envío el día 12 de octubre las observaciones que resultaron de la revisión por parte de los funcionarios de la SDS del informe de la etapa 1 del proyecto. 
A continuación se enlistan las observaciones y se señalan los responsables de atenderlas

**1. DIANGÓSTICO**
@dpedroza74 
1.2.1.1 Entrevistas. Manejo de información
- [ ] Para las opiniones técnicas se están integrando capas de información de los trámites (FUAS, MIAS) en formato shapefile para su análisis.

1.2.1.2 Encuestas
- [ ] Ya se respondieron las 3 encuestas faltantes.

1.2.1.3 Revisión de programas de gobierno		
- [ ] Incorporar el Programa Sectorial de Cambio Climático 2019 - 2024  #46 

- [ ] Programa Especial de Acción ante el CC del Estado de Yucatán (PEACC)	Considerar los estudios previos a la elaboración del PEACC, así como las estrategias y líneas de acción vinculadas a la gestión del territorio http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php

1.5 Conclusiones

- [ ] Uso del POETY para orientar programas de gobierno.	Se realiza el análisis de la compatibilidad de las actividades y usos del suelo del territorio y se generan mapas para orientar el desarrollo de proyectos.
- [ ] Actualización del POETY.	Las actividades para el proceso de gestión del comité se realiza de manera coordinada entre el personal de las direcciones Jurídica y de Planeación y Cambio Climático

**2. ESTRATEGIA**
@dpedroza74 
2.4 Módulos de gestión a incorporar en el sistema de conocimiento		
- [ ] En la región VII  también es prioritario el tema de Agua Limpia y Saneamiento, en  Tabla 2.22 Resultados del modelo de optimización para el diseño de módulos de gestión de políticas públicas en las siete regiones de Yucatán (NS).

**3.1 SUBSISTEMA NATURAL**
@CorinaCantero 
- [x] Actualizar capa de cenotes

3.1.1.2 Geología		
- [x] Revisar información del proyecto Ecoregional de Selva Maya

3.1.1.3 Fisiografía y geomorfología		
- [x] Revisar información del proyecto Ecoregional de Selva Maya. 
- [ ] Faltó el texto relacionado al  Mapa 3.1.5 Unidades de paisaje.

3.1.1.4 Edafología		
- [x] Revisar información del proyecto Ecoregional de Selva Maya.

3.1.1.5 Clima	
3.1.1.5.1 Tipos de clima
3.1.1.5.3 Temperatura media anual
3.1.1.5.4 Temperatura máxima promedio
3.1.1.5.5 Temperatura mínima promedio
3.1.1.5.6 Precipitación media anual
3.1.1.5.7 Evapotranspiración	
- [ ] Revisar mapa de climas http://www.ccpy.gob.mx/agenda-regional/escenarios-cambio-climatico/atlas/

3.1.1.6 Hidrología	
3.1.1.6.1 Regiones hidrológicas
3.1.1.6.2 Cuerpos de agua
Lagunas costeras y esteros
Cenotes
3.1.1.6.3 Hidrología subterránea
3.1.1.6.4 Aprovechamiento del agua subterránea
Zonas de veda
3.1.1.6.5 Calidad del agua
Calidad del agua superficial
Calidad del agua subterránea
- [x] Actualizar capa de cenotes.
- [x] Considerar el mapa de profundidad al nivel estático del agua subterránea.

3.1.2.2 Áreas Naturales Protegidas		
- [x] La leyenda del mapa dice federales. Confirmar si X-la´kaj en Valladolid es ANP municipal.

3.1.2.8 Uso del suelo y vegetación	3.1.2.8.1 Vegetación terrestre	
- [ ] No se mencionan todos los tipos de selvas y otras coberturas presentes.
- [ ] Se tienen mapas de MAD-MEX  CONABIO, Mapas de EOSS (MAD-MEX automatizado) de 2016, 2019 y producto de cambio de cobertura, y se está trabajando un mapa de 2016 con CONAFOR. Se cuentan con mapas de cambios de 2000 al 2016 de CONAFOR (MAD-MEXV1.2).
- [ ] Se tienen datos actualizados de la tasa de deforestación elaborados por Pronatura Sur  y validados por la CONAFOR.

3.1.3.1 Riesgo a eventos naturales		

- [ ] Revisar el Atlas de Peligros por Fenómenos Naturales.
- [ ] Considerar los estudios previos a la elaboración del PEACC, así como las estrategias y líneas de acción vinculadas a la gestión del territorio http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php

3.1.3.2 Vulnerabilidad costera a ciclones tropicales e inundaciones		

- [ ] Revisar el Atlas de Peligros por Fenómenos Naturales, ya que hay sitios al sur del estado con áreas de inundación importantes.
- [ ] Considerar los estudios previos a la elaboración del PEACC, así como las estrategias y líneas de acción vinculadas a la gestión del territorio http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php

3.1.3.3 Vulnerabilidad por efectos climáticos	3.1.3.3.1 Vulnerabilidad a inundaciones 3.1.3.3.2 Vulnerabilidad al incremento en la distribución del dengue	
- [x] Considerar información sobre Zika y Chikungunya

**3.2 SUBSISTEMA SOCIOECONÓMICO**
@dpedroza74 
3.2.5.2 Sector ganadería		
- [ ] Revisar decreto de zonificación apícola: http://sistemaseder.yucatan.gob.mx:4000/transparencia/storage/data/2/2017-10-31_Decreto_537-2017_por_el_que_se_establecen_las_zonas_apicolas_del_estado_de_Yucatan_para_el_fomento_de_su_aprovechamiento_racional.pdf
3.2.5.5 Sector forestal		
- [ ] Detección de puntos de calor e incendios
3.2.5.7 Sector energía		
- [ ] Atlas Nacional de Zonas con Alto Potencial de Energías Limpias https://dgel.energia.gob.mx/azel/
- [ ] Mapas de radiación solar generados con datos de CONAGUA.

**4.1 SISTEMA NECESIDADES USUARIO**.
@serranoycandela @aaron-ts  @milocortes 

4.1 Identificación de necesidades del usuario y otros beneficiarios 
4.1.1.2 Sistema de información y comunicación interna	
- [ ] Revisar  si se describen los casos de uso de este sistema.

**4.1 PROYECTO DE SISTEMA**
@serranoycandela @aaron-ts  @milocortes 

4.2.1 Especificación de requerimientos		
- [ ] Falta incluir la descripción de la infraestructura tecnológica de hardware mínima requerida para la instalación y operación del sistema. Se describe el requerimiento del funcionamiento del sistema pero no su operación. Es decir, características de los equipos de cómputo (procesador, memoria, pantalla), velocidad de internet, etc. para visualizar las capas de información y consultas.

4.2.1.3 Requerimientos	
- [ ] Entendiendo que  las actividades compatibles y no compatibles están incluidas en los “Criterios de Regulación” (Figura 4.2.1 Capacidades del sistema por usuario).
- [ ] Especificar que incluyen los términos “Recursos de monitoreo” y “Proyectos”
- [ ] En “Proyectos” es deseable la posibilidad de consultar los proyectos en trámite y aprobados en el área de influencia., así como los impactos acumulativos relacionados a la UGA.

4.2.1.6 Casos de uso	
- [ ] Incluir la consulta por polígono, o mascara (shapefile o kmz)  en Figura 4.2.2 Diagrama de administración de recursos y Figura 4.2.3 Diagrama de consumo de recursos,  como se menciona en la Figura 4.2.1 Capacidades del sistema por usuario. 
- [ ] Una vez generada la consulta a través de un polígono, se crea un historial?
- [ ] Considerar la  generación de un reporte general de seguimiento del sistema de indicadores semestral o anual.
- [ ] En la Tabla 4.2.2 Módulos y Casos de Uso, no se distingue la diferencia entre el usuario interno, externo. Entiendo que para el apartado de Consultas y Descargas es tanto para el Usuario Interno y Externo.
Por lo tanto estoy suponiendo que el apartado de Actualización de recursos, Automatización de reportes y Modulo de Administración le corresponde al Administrador, que sería adicional al Usuario Interno.  Si entiendo bien, en la Tabla 4.2.2 Módulos y Casos de Uso viene el Módulo de Consultas y descargas que están relacionados a los diagramas de administración de recursos (Figura 4.2.2) y consumo de recursos (Figura 4.2.3).
- [ ] Lo que faltó son los diagramas del Administrador relacionados a los módulos de Actualización de recursos, Automatización de reportes y Módulo de administración. Es correcto?

**7.1 VISUALIZADOR DE MAPAS.**
@paola-gp @CorinaCantero @vichdzgeo 

http://sig.apps.lancis.ecologia.unam.mx/index.php/view/map/

- [ ] Se hizo una revisión del contenido del visualizador de mapas. La siguiente lista de mapas que no se encontraron en el geoportal:
•	Población indígena económicamente activa (número dehabitantes)
•	Población indígena por nivel de ingresos (número de habitantes
•	Número de viviendas indígenas sin drenaje o electricidad
•	Población indígena mayor de 15 años alfabeta
•	Distribución de los pueblos indígenas.
•	Distribución de la población total de Yucatpan (2015)
•	Número de hijos promedio de hjos nacidos vivos en municipios de Yucatán
•	Tasa media anual de crecimiento poblacional
•	Migración reciente interestatal
•	Índice de intensidad migratoria
•	Flujos migratorios en Yucatán
•	Porcentaje de la población económicamente activa ocupada
•	Nivel de ingresos PEA ocupada
•	Grado de marginación por región 
•	Áreas de concentración poblacional en Yucatán 
•	Localidades débilmente integradas*
•	Porcentaje de población afiliada a servicios de salud
•	Porcentaje de viviendas sin drenaje
•	Tipología de municipios según su población indígena
•	Población indígema económicamente activa (número de habitantes)
•	Población indígena monolingüe
•	Población indígena mayor de 15 años alfabeta

- [ ] Hay algún manual para el uso del geoportal?

**Comment by CorinaCantero** [comment]
### AVISO

Se crearon dos carpetas en: 
**FOMIX\fmx_procesamiento\obs_sds**

- word: en esta carpeta se encuentran las últimas versiones de los archivos word para los cuales se solicitaron correcciones 
- documentos_corregidos: en esta carpeta se guardaran los archivos ya corregidos

**Comment by Nayita** [comment]
### Aviso

Poner: 
a) insumos con los que ya se cuentan para resolver las observaciones
b) comentarios o dudas respecto a las observaciones para la reunión del miércoles con la SDS en la siguiente tabla.

**Apartado** | **Subtema** | **Observaciones** | **Insumos** | **Comentarios**
-- | -- | -- | -- | --
**DIAGNÓSTICO** |   |   |   |  
1.2.1.1   Entrevistas | Manejo de información | Para las opiniones técnicas se   están integrando capas de información de los trámites (FUAS, MIAS) en formato   shapefile para su análisis. |   |  
1.2.1.2   Encuestas |   | Ya se respondieron las 3   encuestas faltantes. |   |  
1.2.1.3 Revisión de programas de gobierno |   | Incorporar el Programa Sectorial   de Cambio Climático 2019 - 2024 |   |  
Programa   Especial de Acción ante el CC del Estado de Yucatán (PEACC) | Considerar los estudios previos   a la elaboración del PEACC, así como las estrategias y líneas de acción   vinculadas a la gestión del territorio   http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php |   |  
1.5 Conclusiones | Uso del POETY para orientar   programas de gobierno | Se realiza el análisis de la   compatibilidad de las actividades y usos del suelo del territorio y se   generan mapas para orientar el desarrollo de proyectos. |   |  
Actualización   del POETY | Las actividades para el proceso   de gestión del comité se realiza de manera coordinada entre el personal de   las direcciones Jurídica y de Planeación y Cambio Climático |   |  
**ESTRATEGIA** |   |   |   |  
2.4   Módulos de gestión a incorporar en el sistema de conocimiento |   | En la región VII  también   es prioritario el tema de Agua Limpia y Saneamiento, en  Tabla 2.22 Resultados   del modelo de optimización para el diseño de   módulos de gestión de políticas públicas en las siete regiones de Yucatán   (NS). |   |  
**3.1   SUBSISTEMA NATURAL** |   |   |   |  
3.1.1.1   Delimitación del área de estudio |   | Actualizar capa de cenotes |   |  
3.1.1.2   Geología |   | Revisar información del proyecto   Ecoregional de Selva Maya |   |  
3.1.1.3   Fisiografía y geomorfología |   | Revisar información del proyecto   Ecoregional de Selva Maya. Faltó el texto relacionado al  Mapa 3.1.5 Unidades de paisaje. |   |  
3.1.1.4   Edafología |   | Revisar información del proyecto   Ecoregional de Selva Maya. |   |  
3.1.1.5   Clima | 3.1.1.5.1 Tipos de clima     3.1.1.5.3 Temperatura media anual     3.1.1.5.4 Temperatura máxima promedio     3.1.1.5.5 Temperatura mínima promedio     3.1.1.5.6 Precipitación media anual     3.1.1.5.7 Evapotranspiración | Revisar mapa de climas   http://www.ccpy.gob.mx/agenda-regional/escenarios-cambio-climatico/atlas/ |   |  
3.1.1.6   Hidrología | 3.1.1.6.1 Regiones   hidrológicas     3.1.1.6.2 Cuerpos de agua     Lagunas costeras y esteros     Cenotes     3.1.1.6.3 Hidrología subterránea     3.1.1.6.4 Aprovechamiento del agua subterránea     Zonas de veda     3.1.1.6.5 Calidad del agua     Calidad del agua superficial     Calidad del agua subterránea | Actualizar capa de   cenotes.     Considerar el mapa de profundidad al nivel estático del agua subterránea. |   |  
3.1.2.2   Áreas Naturales Protegidas |   | La leyenda del mapa dice   federales. Confirmar si X-la´kaj en Valladolid es ANP municipal. |   |  
3.1.2.8   Uso del suelo y vegetación | 3.1.2.8.1 Vegetación terrestre | No se mencionan todos los tipos   de selvas y otras coberturas presentes.     Se tienen mapas de MAD-MEX  CONABIO,   Mapas de EOSS (MAD-MEX automatizado) de 2016, 2019 y producto de cambio de   cobertura, y se está trabajando un mapa de 2016 con CONAFOR. Se cuentan con   mapas de cambios de 2000 al 2016 de CONAFOR (MAD-MEXV1.2).     Se tienen datos actualizados de la tasa de deforestación elaborados por   Pronatura Sur  y validados por la   CONAFOR. |   |  
3.1.3.1   Riesgo a eventos naturales |   | Revisar el Atlas de Peligros por   Fenómenos Naturales.     Considerar los estudios previos a la elaboración del PEACC, así como las   estrategias y líneas de acción vinculadas a la gestión del territorio   http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php |   |  
3.1.3.2   Vulnerabilidad costera a ciclones tropicales e inundaciones |   | Revisar el Atlas de Peligros por   Fenómenos Naturales, ya que hay sitios al sur del estado con áreas de   inundación importantes.     Considerar los estudios previos a la elaboración del PEACC, así como las   estrategias y líneas de acción vinculadas a la gestión del territorio   http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php |   |  
3.1.3.3   Vulnerabilidad por efectos climáticos | 3.1.3.3.1 Vulnerabilidad a   inundaciones     3.1.3.3.2 Vulnerabilidad al incremento en la distribución del dengue | Considerar información sobre   Zika y Chikungunya |   |  
**3.2   SUBSISTEMA SOCIOECONÓMICO** |   |   |   |  
3.2.5.2   Sector ganadería |   | Revisar decreto de zonificación   apícola:   http://sistemaseder.yucatan.gob.mx:4000/transparencia/storage/data/2/2017-10-31_Decreto_537-2017_por_el_que_se_establecen_las_zonas_apicolas_del_estado_de_Yucatan_para_el_fomento_de_su_aprovechamiento_racional.pdf |   |  
3.2.5.5   Sector forestal |   | Detección de puntos de calor e   incendios |   |  
3.2.5.7   Sector energía |   | Atlas Nacional de Zonas con Alto   Potencial de Energías Limpias.     https://dgel.energia.gob.mx/azel/     Mapas de radiación solar generados con datos de CONAGUA. |   |  
**4.1   SISTEMA NECESIDADES USUARIO** |   |   |   |  
4.1   Identificación de necesidades del usuario y otros beneficiarios | 4.1.1.2 Sistema de información y   comunicación interna | Revisar  si se describen los casos de uso de este   sistema. |   |  
**4.2   PROYECTO DE SISTEMA** |   |   |   |  
4.2.1 Especificación de requerimientos |   | Falta incluir la descripción de   la infraestructura tecnológica de hardware mínima requerida para la   instalación y operación del sistema. Se describe el requerimiento del   funcionamiento del sistema pero no su operación. Es decir, características de   los equipos de cómputo (procesador, memoria, pantalla), velocidad de   internet, etc. para visualizar las capas de información y consultas. |   |  
  | 4.2.1.3 Requerimientos | Entendiendo que  las actividades compatibles y no   compatibles están incluidas en los “Criterios de Regulación” (Figura 4.2.1   Capacidades del sistema por usuario).     Especificar que incluyen los términos “Recursos de monitoreo” y   “Proyectos”     En “Proyectos” es deseable la posibilidad de consultar los proyectos en   trámite y aprobados en el área de influencia., así como los impactos   acumulativos relacionados a la UGA. |   |  
  | 4.2.1.6 Casos de uso | Incluir la consulta por   polígono, o mascara (shapefile o kmz)    en Figura 4.2.2 Diagrama de administración de recursos y Figura 4.2.3   Diagrama de consumo de recursos,  como   se menciona en la Figura 4.2.1 Capacidades del sistema por usuario.      Una vez generada la consulta a través de un polígono, se crea un   historial?     Considerar la  generación de un   reporte general de seguimiento del sistema de indicadores semestral o   anual.     En la Tabla 4.2.2 Módulos y Casos de Uso, no se distingue la diferencia   entre el usuario interno, externo. Entiendo que para el apartado de Consultas   y Descargas es tanto para el Usuario Interno y Externo.     Por lo tanto estoy suponiendo que el apartado de Actualización de recursos,   Automatización de reportes y Modulo de Administración le corresponde al   Administrador, que sería adicional al Usuario Interno.  Si entiendo bien, en la Tabla 4.2.2 Módulos   y Casos de Uso viene el Módulo de Consultas y descargas que están   relacionados a los diagramas de administración de recursos (Figura 4.2.2) y   consumo de recursos (Figura 4.2.3).     Lo que faltó son los diagramas del Administrador relacionados a los módulos   de Actualización de recursos, Automatización de reportes y Módulo de   administración. Es correcto? |   |

**Comment by CorinaCantero** [comment]
### Actividades para atender observaciones del Subsistema Natural actualizado al 18/05/2021

- [x] **1. Actualizar mapa 3.1.2 de cenotes con información proporcionada por Andrés**
_Se actualizará utilizando la última capa de cenotes 2021 entregada por SDS_
- [x] **2. Incluir un texto relacionado al mapa 3.1.5 Unidades de paisaje @Nayita** 
- [x] **3.Actualizar mapa de Edafología**
_Se actualizó con el conjunto de datos edafológicos serie II 1:250,000 INEGI 2014_ Falta actualizar tabla "Tipos de suelo en el estado de Yucatán"
- [x] **4. Mapas geología y fisiografía - geomorfología:** revisar fechas y escalas del proyecto Ecoregional de Selva Maya y actualizar información en caso de que sea más reciente o que tenga **mayor escala** Ubicación: ENTREGAS\fomix\Selva_Maya
- `Nota: Se entregó información geográfica del proyecto selva maya, sin embargo, los metadatos están en un formato que no se puede consultar y no se sabe la fecha ni la escala de las capas. `
**Por su poca contribución al resto de los insumos necesarios para la conformación del modelo de ordenamiento se decidió no actualizar con otra información.** 
- _Se puede actualizar utilizando: 
ATLAS DE PELIGRO POR FENÓMENOS NATURALES DEL ESTADO DE YUCATÁN (2013)_ 
_Cartografía   Geológica de la República Mexicana escala 1:250,000 (2017)_

- [x] **5. Clima:** actualizar información con los mapas del Atlas de Escenarios de Cambio Climático. 
- _Se descargó de la página información sobre: temperatura media anual, precipitación pluvial anual, P/T o índice de humedad de Lang, porcentaje de lluvia invernal, sequía intraestival o canícula y tipos de clima, para 10 modelos de cambio climático:_ http://www.ccpy.gob.mx/agenda-regional/escenarios-cambio-climatico/atlas/
Ubicación: SIG\desarrollo\sig_fomix\insumos\amc\estrat_cc_py 
 - _SDS entregó lo siguiente: 
Sistema de climas modificado: contiene el libro digital de Modificaciones al sistema de clasificación climática de Koppen de Enriqueta García y el software de la Dra. Celene Espadas.
Ruta: FOMIX\fmx_insumos\clima_sist_mod_
Estaciones climatológicas, 2019 CONAGUA para acceder a base de datos histórica
Ruta: SIG\desarrollo\sig_fomix\insumos\amc\imta\estaciones_clim\estclim_wgs84.shp

**Por su poca contribución al resto de los insumos necesarios para la conformación del modelo de ordenamiento se decidió no reportar la información ya publicada en la página de http://www.ccpy.gob.mx/agenda-regional/escenarios-cambio-climatico/atlas/  
Se atenderán los escenario de los modelos actualizados de cc en la etapa de pronóstico @vichdzgeo** 
- Se pueden actualizar las capas:
 Evapotranspiración (2011) Gottwein-Bauer 
Precipitación media anual (2006) INEGI. Escala:	1:1 000 000 https://www.inegi.org.mx/app/biblioteca/ficha.html?upc=702825267544
-  Faltaría actualizar mapas: climas, temperatura media anual, temperatura máxima promedio, temperatura mínima promedio

- [x] **6. Hidrología:** incorporar mapa de nivel estático del agua subterránea (Dr. Batllori) 1.19a
- [x] **7. Actualizar mapa 3.1.15 Cuerpos de agua**
- [x] **8. Áreas Naturales Protegidas:** corregir leyenda de mapa de ANPs estatales (dice federales), revisar si X-la'kaj en Valladolid es una ANP municipal.
_*Respuesta: Se hace la corrección ya que el Bioparque Xla´kaj es una zona de preservación ecológica de los centros de población http://www.yucatan.gob.mx/docs/diario_oficial/diarios/2004/2004-07-01.pdf, p.60_ 

**Sigue pendiente corrección de ANP que coincidan entre CONANP, CONABIO y SDS**
- [x] **Vegetación terrestre:** mencionar todos los tipos de selvas y coberturas presentes (Sección 3.1.2.8.1) @Nayita 

- [x] 9. **Actualizar mapas de uso de suelo y vegetación y cambio de cobertura** - utilizar los de CONAFOR 
Información disponible de CONAFOR: 
- Mapa de cambio de cobertura 2000-2003
- Mapa de cambio de cobertura 2003-2011
- Mapa de cambio de cobertura 2011-2014
- Mapa de cambio de cobertura 2014-2016
** **No hay metadatos**
**Las capas que entregaron no sirven de insumos para hacer el análisis de cambio de cobertura. Se integrará en diagnóstico la nueva versión de este análisis con capas de INEGI-CONABIO.** 
- [ ] 10. **3.1.3.1 Revisar el Atlas de Peligros por Fenómenos Naturales.** Considerar los estudios previos a la elaboración del PEACC, así como las estrategias y líneas de acción vinculadas a la gestión del territorio http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php
- PROGRAMA ESPECIAL DE ACCIÓN ANTE EL CAMBIO CLIMÁTICO (PEACC) 
- Se acordó incorporar información adicional disponible en el Atlas de Peligros por Fenómenos Naturales, las capas geográficas entregadas por Andrés se pueden consultar en el issue #1 
Se va agregar un 

- [ ] 11. **3.1.3.2 Revisar el Atlas de Peligros por Fenómenos Naturales,** ya que hay sitios al sur del estado con áreas de inundación importantes. Considerar los estudios previos a la elaboración del PEACC, así como las estrategias y líneas de acción vinculadas a la gestión del territorio http://www.ccpy.gob.mx/agenda-yucatan/programa-estatal-estudios-peacc.php
![image](https://user-images.githubusercontent.com/44783182/118851376-49a42a00-b897-11eb-881c-c04ab6f27aaf.png)
** Note: Esa capa del SGM no la tenemos 

- [x] Cambiar el nombre de riesgo a eventos naturales a: **Riesgo a eventos hidrometeorológicos**, cambiar figura, mapa y textos. @Nayita @CorinaCantero 
- [x] Generar un índice a **Riesgo de eventos geológicos**

- [x]  **12. Considerar información sobre Zika y Chikungunya.** 
_El mosquito que es vector del dengue también lo es de Zika y Chinkunguya, por lo que el mapa  de Vulnerabilidad al incremento en la distribución del dengue puede utilizarse en los tres casos._
**El área de vulnerabilidad de la población a las enfermedades Zika y Chikunguya es la misma al compartir el mismo vector de transmisión.**

**Comment by vichdzgeo** [comment]
##  Actualizar mapas de uso de suelo y vegetación y cambio de cobertura - utilizar los de CONAFOR

### Datos proporcionados 

ruta: ENTREGAS\fomix\CONAFOR\MapasDeCambios_2000al2016_YUCATAN_15Nov2019
Periodos

- 2000 - 2003
- 2003 - 2011
- 2011 - 2014
- 2014 - 2016

Para cada periodo existe un archivo shapefile que contienen tres campos

- ID
- C_FL_NFL
- IPCC

dada la ausencia del metadato asociado a la información geográfica no se sabe con certeza lo que significa el contenido de los datos

- Faltan las capas de cobertura de CONAFOR para los diferentes pedidos de tiempo (2000,2003,2011,2014,2016)
## capa de cambio de cobertura EOSS - MADMEX

ruta: ENTREGAS\fomix\CONABIO EOSS MADMEX

la información recibida contiene:

-  archivo shapefile que representa los cambios de cobertura entre 2016 y 2019, dentro de la tabla de atributos se encuentran el nombre de las clases de vegetación. La capa no esta codificada en UTF-8 lo que ocasiona que en las clases que contienen acentos se muestren con símbolos extraños, esto se soluciona con saber la codificación correcta de la capa.
- un archivo tiff que puede corresponder al campo **code_t0_t1** del archivo shapefile (falta verificarlo con los metadatos) 
- un arhivo tiff eoss4tnc_landcoverchanges_landsat8_2016-2019_20200313_madmexplus_YUC_cloud que se desconoce el significado de lo que representa.

- Faltan las capas de cobertura del 2016 y 2019 
- Dada la ausencia del metadato asociado a la información geográfica no se sabe con certeza lo que significa el contenido de los datos

**Comment by dpedroza74** [comment]
subí grabación y minuta de reunión con Celene Espadas del CICY sobre cambio climático el día 12 de noviembre en dropbox:
/work/FOMIX/fmx_reuniones_sds

**Comment by CorinaCantero** [comment]
### **AVISO**
@dpedroza74 @ofegarcia 

Ruta para guardar los últimos archivos de la caracterización:
FOMIX\fmx_procesamiento\obs_sds\documentos_corregidos

En esta carpeta pueden encontrar los archivos ya corregidos con las peticiones de CONACYT:
FOMIX\fmx_procesamiento\obs_sds\word

**Comment by dpedroza74** [comment]
Listo, ya subí a la carpeta de documentos corregidos la caracterización del subsistema productivo
subsistema_productivo_3_2_bit

@Nayita porfa cuando cambies la numeración, checa lo de las figuras/tablas/mapas, porque en la sección de caracterización sectorial no se actualizaron de manera automática las numeraciones de figuras y tablas y su respectivo hipervínculo en la referencia en el texto.

**Comment by paola-gp** [comment]
Este informe se entregó el 8 julio del 2020 y contiene la última información oficial disponible solicitada en  la demanda específica YUC-2018-04-01-88958: "Requerimientos del usuario con respecto al estudio técnico para la actualización del programa de ordenamiento ecológico del territorio del estado de Yucatán (POETY)".

**Comment by paola-gp** [comment]
@CorinaCantero 
- [ ] Diagnóstico de lo que falta en lizmap 
- [ ] Actualizar lizmap de lo que se entregó en caracterización

**Comment by paola-gp** [comment]
La nueva sección se llamará:
Peligros geológico-geomorfológicos

Ver issue #88

**Comment by Nayita** [comment]
@CorinaCantero 

Lista la figura en la ruta:
FOMIX/fmx_estudio_tecnico/caracterizacion_subs/figuras
Archivo: indice_r_eventos_hidro.png

**Comment by CorinaCantero** [comment]
### AVISO
Listas las correcciones al documento de la caracterización natural. **Ubicación:** 
FOMIX\fmx_procesamiento\obs_sds\documentos_corregidos\subsistema_natural_3_1_nrn

**Comment by CorinaCantero** [comment]
### **AVISO**

Para atender la observación de la SDS sobre el punto 7.1 VISUALIZADOR DE MAPAS, se agregaron los mapas faltantes  presentes en los documentos de la caracterización.
@vichdzgeo por favor actualizar el Lizmap. 

**Ubicaciones:**

- Carpeta con las capas faltantes: SIG\desarrollo\sig_fomix\entregables\lizmap_caracterizacion_entrega
- Proyecto Qgis: SIG\desarrollo\sig_fomix\mapas\sub_natural\subsistemas_fomix
