### ISSUE TITLE
Generar procedimiento para la digitalización de minas y banco de materiales 

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#57]
Ruta:

SIG\desarrollo\sig_fomix\procesamiento\minas

Se descargaron las cartas topográficas 1:250,000.
![image](https://user-images.githubusercontent.com/38017509/97211774-2859e000-1785-11eb-862e-220f7bd146b6.png)

El formato de estas cartas es en PDF.

## Preparación de los insumos:

-  se transforman los archivos PDF en formato TIFF
- Se recortan las imágenes para obtener unicamente el área del mapa 
- Las imágenes son georreferenciadas con 4 puntos de control ubicados en los extremos del mapa y utilizando las coordenadas UTM de la retícula.
- Se genera un proyecto en qgis 3 **minas.qgis** el cual contiene las cartas geo referenciadas.

## Procedimiento 

- Editar el archivo shapefile del proyecto minas_banco_material. 
- agregar un nuevo punto 
- hacer clic sobre  la ubicación de la mina o banco de material a digitalizar
- rellenar los datos de la siguiente tabla que se muestra

![image](https://user-images.githubusercontent.com/38017509/97213091-d44ffb00-1786-11eb-85de-181c0e3d02c4.png)

### Campo Tipo 

- MINA 
- BANCO DE MATERIAL

### Campo estado

Si el tipo es MINA 

los estados pueden ser  
- MANIFESTACION DE MINERAL IN SITU
- EN PRODUCCION
- ABANDONADA

si el tipo  es BANCO DE MATERIAL

- EN PRODUCCION 
- INACTIVO
- PROSPECTO

### Campo material 

El material se específica en el símbolo del mapa de la mina o banco de material en el mapa ( por lo general esta entre paréntesis) , agregar el material especificado en mayúsculas

## Simbología de guía 

![image](https://user-images.githubusercontent.com/38017509/97213738-a323fa80-1787-11eb-9072-911dc2206b5a.png)
Prospecto
![image](https://user-images.githubusercontent.com/44783182/99867123-506a1280-2b7c-11eb-9156-d88a38ad9cfc.png)

Fuente: https://www.sgm.gob.mx/GeoInfoMexGobMx/

**Comment by CorinaCantero** [comment]
### AVISO

Se terminaron de marcar los puntos de bancos de materiales de las cartas, la capa final se mueve a entregables:
SIG\desarrollo\sig_fomix\entregables\minas\minas.shp

**Comment by vichdzgeo** [comment]
@dpedroza74 @CorinaCantero 


De la información comentada en el correo solo se procesaron los bancos de materiales. la  capa disponible cuenta con la siguiente información: 

En el proceso de restitución se capturó el estado del banco de material (En producción, inactivo, prospecto) así como el material (area, bloque, grava , grava gravillas y arena, grava gravilla y gravon, grava-arcilla, grava-arena, material de relleno)

- Yacimientos minerales -minas (Banco de materiales)
![image](https://user-images.githubusercontent.com/38017509/108914691-57784500-75f1-11eb-93ed-1a2702097bb6.png)

En octubre no se solicito procesar la información disponible de  los criterios de Rocas dimensionables y Empresas mineras. por lo cual no se cuenta con capas disponibles de dicha información.

Como propuesta para empresas mineras el DENUE cuenta con 39 registros relacionados con  (212) Minería de minerales metálicos y no metálicos, excepto petróleo y gas



La información de CartoMinMex es únicamente de consulta y no se puede descargar 

Se muestra en el mapa para *Concesiones mineras*
- Valladolid, Cementos Apasco
- Rio lagartos, Industria salinera de Yucatán
- - Tizimín , Industria salinera de Yucatán
- Yobain, Comercial salinera de Yucatán, Salinas de Mayab 

para **Propuestas en trámite**

- Chapab, fecha de solicitud 25 abril, 2018
- Valladolid, 30 marzo, 2015 y 24 octubre, 2013 ambas de Cementos Apasco
- Tizimín, 15 octubre 2015, Industria salinera de Yucatán 
```
CartoMinMex
https://portalags1.economia.gob.mx/arcgis/apps/webappviewer/index.html?id=1f22ba130b0e40d888bfc3b7fb5d3b1b
Concesiones mineras 
Propuestas en trámite

GeoInfoMex SGM
https://www.sgm.gob.mx/GeoInfoMexGobMx/
Yacimientos minerales -minas
Rocas dimensionables
Empresas mineras
```

**Comment by CorinaCantero** [comment]
### PRODUCTOS ENTREGABLES

Ubicación de productos entregables con metadatos:

- **Yacimientos minerales:**
SIG\desarrollo\sig_fomix\entregables\bancos_materiales\banco_material.shp
- **Rocas dimensionables:**
SIG\desarrollo\sig_fomix\entregables\lizmap_segunda_entrega\insumos\rocas_dimensionables.shp
