### ISSUE TITLE
Integrar procedimiento para el desarrollo y presentación de análisis de aptitud

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#59]

**Comment by Nayita** [comment]
# PROCEDIMIENTO PARA EL DESARROLLO Y PRESENTACIÓN DEL ANÁLISIS DE APTITUD

## PREPARACIÓN DEL TALLER DE ANÁLISIS DE APTITUD

### Preparación de insumos geográficos
**Actividades**
1. Buscar  información geográfica acorde con el sector (@CorinaCantero) con el que se trabajará: 
- En el catálogo de información geográfica del SIG de FOMIX (Ubicación: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\catalogo_fomix) o en fuentes oficiales de información.
`NOTA:` En el issue #65 están las ligas a los Lizmaps por categoría temática

2. Rasterizar  archivos vectoriales (@vichdzgeo) 
- Las capas vectoriales se rasterizan de acuerdo con las instrucciones ubicadas en: sig_fomix\procesamiento\analisis_aptitud\insumos\requerimientos_capas_geograficas.docx y utilizando los códigos de Phyton ubicados en: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\insumos\funciones_insumos.py
- Los raster finales y los insumos para el procesamiento se guardarán en: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\sectores, en la carpeta que corresponda (finales, fv, insumos o procesamiento).
- Los archivos raster finales deben ser guardados con nombres cortos y de ser el caso utilizando las siguientes claves: 
 
Abreviatura | Información que contiene la capa
-- | --
d_ | Distancia a
t_ | Tipo
disp_ | Disponibilidad
n_ | Número de

3. Preparar las tablas con datos de las capas insumo (.csv utf 8). (@CorinaCantero) Deben contener los siguientes campos: 

Campo | Titulo de la capa insumo
-- | --
Fuente | Adaptado de…. (cuando la capa no es exactamente como el insumo base)
Año |  
Campo | Solo agregar si es relevante
Escala | Resolución o escala
Unidades | Poner si es adimensional

Ejemplo:

Capa | Uso de suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación. Serie VI. Conjunto Nacional INEGI
Año | 2014
Escala | 1:250,000
Campo | descripcio (el campo de la fuente original usado)
Unidades | Adimensional

Ubicación: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\insumos\tablas_metadatos

4. Preparar tablas para las funciones de valor categóricas, usando la plantilla (@CorinaCantero) (plantilla_fv_discretas; FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\plantillas_prefijos). 
 
5. Cargar las capas raster en la plataforma (SIGfunction o SIGfunctionD) (@CorinaCantero)  http://pruebas.sigplanning.com.mx/ , entrando con el usuario de fomix. 
- Título: se coloca un título corto/abreviado de la capa raster, entre paréntesis se puede colocar información adicional, por ejemplo: Humedales (distancia), Pozos (presencia).
- Descripción: se coloca el nombre del sector, p.ej. Ganadería
- Nombre de salida: este nombre se modificará más adelante cuando se haya construido en el taller el modelo de aptitud, utilizando como plantilla el archivo  prefijos_sectores (p.ej. fv_gbe_sil_bio_usv_inegi).(Ubicación: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\plantillas_prefijos).
- Modificar las paletas de colores, la paleta para la capa resultado siempre debe ser "userColor2".

## DESARROLLO DEL TALLER

**Actividades**

- Facilitar el desarrollo del taller. @paola-gp @dpedroza74 

- Asignar coanfitriones. @paola-gp @dpedroza74 

- Operar el programa Superdecisions y los módulos SIGfunction, SIGfunction D (@ofegarcia @TatianaMerino)  y SIGindex (@vichdzgeo @paola-gp)

- Grabar el taller con el programa Camtasia. @Nayita @CorinaCantero 

- Tomar fotos de las funciones de valor finales. @CorinaCantero 

- Tomar notas de la información relevante de los participantes @ofegarcia @TatianaMerino  

- Apoyar al facilitador(a) en actividades como: @Nayita @CorinaCantero @ofegarcia @TatianaMerino 

1. permitir el ingreso a la sesión una vez iniciado el taller, 
2. registrar asistencia, 
2. controlar y notificar el tiempo del desarrollo del taller, 
3. silenciar micrófonos ruidosos que interrumpan la sesión,
4. bloquear la posibilidad que los participantes quieran compartir pantalla,
5. comunicar el número de participantes al facilitador(a) antes del resumen de cada sesión,
6. Invitar a que los participantes anónimos pongan su nombre y procedencia. A la tercera invitación, sacarlos de la sesión,
7. Solicitar y contestar en los chats dirigidos cualquier información relevante para el buen desempeño del taller y,
8. Monitorear y ceder la palabra a los participantes que lo soliciten.


## ACTIVIDADES POSTERIORES AL TALLER

**Actividades**

1. Guardar la carpeta de grabación de 10 minutos de zoom en las subcarpeta **imagenes** (contiene chat, audio y vídeo), renombrar de acuerdo a protocolo (@TatianaMerino @ofegarcia)

- Guardar el video de Camtasia separando audio (subcarpeta audio) y video (subcarpeta imagenes).

2. Hacer los esquemas del modelo AHP hecho en el taller con los criterios y pesos correspondientes (@Nayita). Guardar la figura y la plantilla en la subcarpeta informes/insumos y la figura con extensión .png en la ruta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos, en la subcarpeta del sector correspondiente.


3. Depurar los archivos de los modelos AHP obsoletos y ponerlos en una subcarpeta de **auxiliares** (@TatianaMerino @ofegarcia).

4. Hacer la tabla de las definiciones del sector y los criterios biofísicos y socioeconómicos que se hayan obtenido en el taller a partir del html generado por el programa _Superdecisions_, al imprimir los resultados de la evaluación multicriterio. Guardar el archivo de la tabla en la ruta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos, en la subcarpeta del sector correspondiente. Ver características del archivo de la tabla en la sección **Características de edición**.
@ofegarcia @TatianaMerino 

5. Generar las imágenes (fv continuas) (@CorinaCantero) :

- Instalar la fuente de OpenSans-Regular.ttf ubicada en FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos
- Hacer recortes de las gráficas de las funciones de valor desde la plataforma de SIGfunction: en una pantalla de resolución 1366 x 768 con zoom 100% hacer el corte por el siguiente borde: 
![Captura2](https://user-images.githubusercontent.com/44783182/108422017-9ece9200-71fb-11eb-9a64-ce8861560ea4.PNG)

- Agregar las etiquetas de mejor condición y peor condición según corresponda. (para este punto existe la plantilla en power point plantillas_figuras_fv_continuas.pptx ubicada en FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\plantillas_prefijos, si existen dudas pueden visualizar el **tutorial_figuras_fv_continuas.mp4** ubicado en la misma carpeta
![image](https://user-images.githubusercontent.com/44783182/108402604-60c57400-71e3-11eb-99f7-4fcd781f64d8.png)

6. Hacer la tabla(s) de la(s) capa(s) de exclusión (@ofegarcia @TatianaMerino). 
Se debe generar una tabla por cada capa de exclusión que contenga ID y Categoría, por ejemplo:  
_Coberturas no aptas de la capa de uso del suelo y vegetación serie VI INEGI usadas como zonas de exclusión (Aptitud nula)_

ID | Categoría
-- | --
01 | Acuícola
11 | Cuerpo de agua
13 | Manglar
14 | Palmar inducido

7. Hacer los mapas producto de las funciones de valor (@CorinaCantero). Utilizar el proyecto mp_talleres_aptitud ubicado en: SIG\desarrollo\sig_fomix\mapas para generar los mapas, en el proyecto hay tres composiciones: 

a) aptitud: para elaborar el mapa de aptitud del sector
![mapa_apt_gbe_silvopastoril](https://user-images.githubusercontent.com/44783182/100134870-79c1c180-2e4e-11eb-8e8b-98ec29b7abe5.png)

b) exclusión: para elaborar el mapa de exclusión
![mapa_gbe_silvopastoril_exclusion](https://user-images.githubusercontent.com/44783182/100134887-7fb7a280-2e4e-11eb-8984-596ef8e0ce93.png)

c) funcion_valor: para elaborar mapas de las funciones de valor
![mapa_fv_gbe_sil_bio_d_acuifero](https://user-images.githubusercontent.com/44783182/100130524-6ad81080-2e48-11eb-8c2a-4115c91535be.PNG)

8. Hacer tablas de los pesos globales (@CorinaCantero) y área por categoría de aptitud (@vichdzgeo). Ejemplos: 

**Pesos globales**
![image](https://user-images.githubusercontent.com/44783182/105206133-a40cc400-5b0b-11eb-9080-b464f3cac401.png)

**Área por categoría de aptitud**
Categoria | km² | Porcentaje del estado
-- | -- | --
Nula | 2538.1 | 6
Muy baja | 702.2 | 2
Baja | 397.2 | 1
Moderada | 4300.0 | 11
Alta | 11956.0 | 30
Muy alta | 19486.6 | 49

9. Hacer análisis y gráfica de sensibilidad de atributos (@vichdzgeo) . Ejemplo: 
![image](https://user-images.githubusercontent.com/44783182/105206252-c43c8300-5b0b-11eb-872d-0f682664cf0f.png)


## PRESENTACIÓN DEL ANÁLISIS DE APTITUD

Los análisis de aptitud se generarán en formato _markdown_  (@Nayita) para presentación en la página: 

https://lancis-apc.github.io/fomix/

Los archivos _markdown_ se encontrarán en la siguiente ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source

**Contenido de los archivos _markdown**_

- Título del elemento (sector o subsector al que se el hizo el análisis de aptitud)

- Ruta de la documentación comentada

- Definición del elemento (sector o subsector)

- Definición de la meta

- Modelo AHP (figura)

- Criterios y sus definiciones (biofísicos y socioeconómicos) 
   - Resumen (tabla)

- Descripción de cada uno de los criterios
  - Definición
  - Insumos (tabla)
  - Parámetros de las función de valor (tabla o figura)
  - Función de valor del criterio (mapa)

- Pesos globales del modelo de aptitud (tabla)

- Capa de exclusión (tabla, mapa)

- Mapa de aptitud (mapa)

- Área por categoría de aptitud (tabla)

- Sensibilidad de atributos (mapa)

**Características de edición**

- Títulos
   Título del elemento, título principal (#)
   Título de segundo nivel (##)
   Título de tercer nivel (###)
   Título de cuarto nivel (####)
   Negritas 

- Tablas
   Los archivos de todas las tablas deben ser guardados como archivos **UTF8-CSV**.
   Para elaborar la tabla de definiciones del sector y criterios, usar la plantilla de la ruta 
   \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\plantillas_prefijos\tabla_definiciones.xlsx.
   La información y valores de las tablas deben estar alineadas. Los valores con punto decimal deben 
   alinearse con respecto a éste. 
   Las tablas con valores numéricos como las tablas de fv discretas o nominales o de pesos globales deben ordenarse de mayor a 
   menor peso o importancia. 
   Ejemplo de tabla alineada y ordenada de mayor a menor. 
   
Tabla de pesos globales:

Criterio | Peso
-- | --
Disponibilidad de agua | 0.38
Cobertura | 0.20
Disponibilidad de mano de obra | 0.15
Accesibilidad a mercados locales | 0.09
Precipitación | 0.08
Tipo de suelo | 0.08
temperatura | 0.02
Accesibilidad a mercados foráneos | 0.01

La ruta y nombre de la tabla  se debe poner y comentar en el markdown. Ejem.:

"<!-- .. csv-table:: Cobertura
   :file: recursos/gbe_sil/tabla_fv_gbe_sil_bio_usv_inegi.csv"

- Títulos de tablas, figuras y mapas
   Para nombrar estos archivos consultar los archivos de prefijos correspondientes, según sea el caso, en la ruta FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\plantillas_prefijos.

**Comment by Nayita** [comment]
@dpedroza74  @ofegarcia  

Para que vean el procedimiento.

**Comment by ofegarcia** [comment]
Muchas gracias¡  Enviado desde Correo para Windows 10 De: nadiaruizEnviado: viernes, 8 de enero de 2021 06:24 p. m.Para: lancis-apc/fomixCC: ofegarcia; MentionAsunto: Re: [lancis-apc/fomix] Integrar procedimiento para el desarrollo y presentación de análisis de aptitud (#59) @dpedroza74 @ofegarciaPara que vean el procedimiento.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Nayita** [comment]
@TatianaMerino 
Para tu conocimiento.

**Comment by Nayita** [comment]
### Aviso
@TatianaMerino @dpedroza74 @ofegarcia 

Liga para consultar los manuales de SIGfunction y SIGfunction D

https://lancis-apc.github.io/SVACC/

**Comment by CorinaCantero** [comment]
### AVISO: Organización de la carpeta "talleres"

Los archivos referentes a los talleres de aptitud para la actualización del POETY se guardarán en la siguiente ubicación: 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres

A continuación se explica la organización de la carpeta:

* **ganaderia:** contiene archivos referentes al taller de ganadería bovina silvopastoril

* **insumos:** en esta carpeta se encuentran los insumos generales para los talleres de aptitud 
        ** pagina_web: insumos utilizados para la generación de la página web
	** plantillas_prefijos: contiene la plantilla y un tutorial para generar la gráfica de funciones de valor;
           el machote y los prefijos para el nombrado de las funciones de valor; y un ejemplo de archivo con categorías
           con id, jerarquías y función de valor.
                
* **sectores:** hay una carpeta para cada taller sectorial, a su vez cada una deberá contener al terminar los talleres:
        ** aptitud: los archivos raster de exclusión y de aptitud (finales).
        ** audios: audios de los talleres
        ** funciones_valor: los archivos raster de las funciones de valores (finales), las tablas ID para funciones 
           de valor categóricas, las tablas de insumos para el informe, el archivo final de prefijos para nombrado de 
           archivos.
        ** imagenes: imagenes y videos de los talleres.
	** informe: documento donde se describe la meta y la definición de los criterios.
        ** modelo: modelos de super decisions.
        ** notas: notas de las presentaciones.
        ** presentaciones: presentaciones utilizadas durante los talleres.

Los siguientes archivos fueron renombrados de acuerdo al protocolo:
Actualización del Programa de Ordenamiento Ecológico del Territorio de Yucatán (1) -> invitacion_poety_pecuario
Actualización del Programa de Ordenamiento Ecológico del Territorio de Yucatán pesca y acuacultura -> invitacion_poety_pesca

**NOTA:**
- Presentación de Paola para la preparación de talleres: 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\preparacion_talleres

**Comment by CorinaCantero** [comment]
## TAREAS


Producto | Responsable | Carpeta | Nombrado | Ej. Nombrado
-- | -- | -- | -- | --
**Diagrama del modelo AHP** | @Nayita   | talleres\sphinx\docs\source\recursos | modelo_"prefijo sector" | modelo_gbe
**Gráficas FV SIGfunction** | @CorinaCantero  | talleres\sphinx\docs\source\recursos | fi_"nombre FV" | fi_fv_gbe_sil_bio_precipitacion
**Mapas** |  @CorinaCantero  | talleres\sphinx\docs\source\recursos | mapa_"nombre FV" | mapa_fv_gbe_sil_bio_precipitacion
**Tablas   con datos de capas insumos** | @CorinaCantero   | talleres\sphinx\docs\source\recursos | tabla_insumos_"nombre   FV" | tabla_insumos_fv_gbe_sil_bio_precipitacion
**Tablas   con parámetros de funciones de valor categóricas** | @ofegarcia @TatianaMerino   | talleres\sectores\x\funciones_valor | tabla_cat_"nombre FV" | tabla_cat_fv_gbe_sil_bio_t_suelo
**Tablas de definiciones de criterios** | @ofegarcia @TatianaMerino  | talleres\sectores\x\informe | tabla_c_"prefijo   sector"_"criterio" | tabla_c_gbe_socioeconomico_mercados
**Tabla   de pesos globales** | @CorinaCantero   | talleres\sphinx\docs\source\recursos | tabla_"prefijo_sector"_pesos_globales | tabla_gbe_pesos_globales
**Tabla   área por categoría de aptitud** | @vichdzgeo  | talleres\sphinx\docs\source\recursos | tabla_"prefijo_sector"_aptitud | tabla_gbe_aptitud
**Gráfica   sensibilidad de atributos** | @vichdzgeo   | talleres\sphinx\docs\source\recursos | fi_"prefijo   sector"_sensibilidad | fi_gbe_sensibilidad

**Comment by TatianaMerino** [comment]
AVISO
@ofegarcia 

Los videos de los últimos 10 min de los talleres se suben a FOMIX\fmx_estudio_tecnico\diagnostico\talleres\x\imagenes
(donde x= sector correspondiente) en formato mp4 (con audio y video).

**Comment by CorinaCantero** [comment]
### AVISO

Las carpetas "imagenes" y "audio" se cambiaron a la siguiente ubicación: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\imagenes

Se acordó que los responsables en grabar los audios y/o vídeos con Zoom o Camtasia guarden los archivos en sus equipos y posterior a los talleres los suban a Dropbox para evitar problemas de sincronización.

**Comment by paola-gp** [comment]
#### Acuerdos del 5/02/2021 @dpedroza74 @TatianaMerino 
1. @vichdzgeo  Bajar página hasta que estén resultados finales para consulta de estos 4 sectores, fecha programada, miércoles 10 de febrero. 
2. @Nayita Cambiar a modelo de decisión. 
3. @Nayita Verificar espacios y tamaños de subtítulos, ver propuesta. 
4. *nuevo para* @Nayita: Cuando haya subsectores diferenciar en el título con numeración (en el siguiente comentario pongo ejemplo). 
5. No modificar FV para que sea equidistante en estos cuatro primeros sectores, pero modificar machote en sectores subsecuentes @CorinaCantero 
6. Actualizar gráficas y mapas para que quede "peor condición" y "mejor condición", @CorinaCantero 
7. Subir listas de participantes en PDF debajo del nombre del sector @ofegarcia y @Nayita  
8. @Víctor  Incluir análisis de sensibilidad

**Comment by paola-gp** [comment]
#### Estructura en Sphinx

Ver código fuente e ir por rama

# Sector 
## Meta
**Lista de participantes**
## 1. Subsector A _(Si no hay subsectores, saltarse el nivel)_
### Criterio 1.1  o el nombre que le pongan los participantes
#### Subcriterios 1.1.1  o el nombre que le pongan los participantes _(si no hay subcriterios, saltarse en nivel)_
##### Atributo A
###### Insumo A
###### Párámetros de funciones de valor A_
###### Función de valor A
##### Atributo B
###### Insumo B
###### Párámetros de funciones de valor B
###### Función de valor B
#### Subcriterios 1.1.2  o el nombre que le pongan los participantes _(si no hay subcriterios, saltarse en nivel) 
##### Atributo C
###### Insumo C
###### Párámetros de funciones de valor C
###### Función de valor C
##### Atributo D
###### Insumo D
###### Párámetros de funciones de valor D
###### Función de valor D
### Criterio 1.2 
etc...
#### Mapa parcial del criterio o subcriterio X (o como le hayan llamado en el sector y solo si lo solicitan como en energía)


##### Aprovechamiento actual 
Atributos que reflejan las zonas de aprovechamiento actual de las actividades del sector. 
##### Zonas de exclusión
Atributos que por sus características imposibilitan, sin lugar a duda, el desarrollo de una actividad del sector. Puesto que se busca la identificación de los conflictos ambientales actuales o potenciales que resultan de la sobreposición de mapas de aptitud de distintos sectores, es importante señalar que en la etapa de diagnóstico del POETY no se agregan a las zonas de exclusión, preferencias asociadas a conflictos ambientales. 
### Mapa de aptitud del subsector A _(solo como título)_
#### Pesos globales de los atributos ambientalesdel subsector A
#### Mapa de aptitud del subsector A_(la imagen del mapa)_

## 2. Subsector B

**Comment by paola-gp** [comment]
@CorinaCantero: Se acordó hoy en una reunión con la SDS que se incluiría (solo para el mapa de aptitud final) los límites municipales en el informe.

**Comment by paola-gp** [comment]
@CorinaCantero: Se actualizó machote de funciones de valor para que incluya el mismo número de categorías que el mapa. 

fv_machote.csv

Importancia | Categoría mapa | Equidistante
-- | -- | --
Muy alta | Mejor condición | 1.00
Alta |   | 0.75
Moderada |   | 0.50
Baja |   | 0.25
Nula | Peor condición | 0.00

**Comment by paola-gp** [comment]
@dpedroza74 @TatianaMerino @ofegarcia @Nayita @CorinaCantero @vichdzgeo 

### Pasos para subir las grabaciones de camtasia a dropbox

1. Abrir archivo .tscproj en camtasia
2. En el menú **share** seleccionar **local file** 
3. Seleccionar **Custom production settings** >> siguiente
4. Seleccionar MP4 Smart Player (html5) >> siguiente
5. En la pestaña de **video settings** seleccionar en el slider una calidad (quality) del 50% dejar todo lo demás como está.
6. En **Audio settings** seleccionar **encode audio** a **96 kbps**.
7. Dejar todo lo demás con los parámetros predeterminados.
8. Seleccionar **next** >> **next** >> indicar donde debe poner la carpeta en su equipo de computo
9. Seleccionar **finish**
10. Se va tardar mucho en y les va a ocupar todo el RAM de sus equipos, así que sugiero hacer esto en las noches (cuando ya no usen el equipo) 
11. Les va a guardar varios archivos, solo neceitan el .mp4, el cual ya podrán ver desde dropbox sin tener que descargarlo (dependiendo de su conexión a internet)
12. Subir mp4 en la carpeta correspondiente a /imagenes de preferencia por las noches para que no dejen a toda su casa sin internet
13. Recordar que solo se tiene una licencia por lo que no podrán usarlo simultáneamente mas de dos personas.

**Comment by CorinaCantero** [comment]
### Procedimiento para la generación de imágenes de gráficas de FV

5. Generar las imágenes (fv continuas):

- Instalar la fuente de OpenSans-Regular.ttf ubicada en FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos
- Hacer recortes de las gráficas de las funciones de valor desde la plataforma de SIGfunction: en una pantalla de resolución 1366 x 768 con zoom 100% hacer el corte por el siguiente borde: 
![image](https://user-images.githubusercontent.com/44783182/103711490-2d08f480-4f7d-11eb-930f-012bc1e32247.png)

- Agregar las etiquetas de mejor condición y peor condición según corresponda. (para este punto existe la plantilla en power point plantillas_figuras_fv_continuas.pptx ubicada en FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\plantillas_prefijos, si existen dudas pueden visualizar el **tutorial_figuras_fv_continuas.mp4** ubicado en la misma carpeta
![image](https://user-images.githubusercontent.com/44783182/108402604-60c57400-71e3-11eb-99f7-4fcd781f64d8.png)

Archivos de nombrado para cada sector: 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores en la carpeta "funciones_valor"

- Silvopastoril: prefijos_ganaderia_bovina
- Energía: prefijos_sector_ene_v6
- Forestal: prefijos_sector_for_v2
- Urbano: prefijos_sector_urb_v2
- Industrial:  prefijos_sector_ind
- Agricultura: prefijos_sector_agr -----> hasta el momento solo están hechas las imágenes para agricultura de riego
- Pecuario bovino, pecuario porcino y milpa maya (no se ha hecho ninguna imagen de gráfica FV para estos sectores)

Ubicación de las imágenes para los informes:
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos

**Comment by paola-gp** [comment]
### para actualización de gráficas este es el acuerdo:

1. Usar una capa genérica en la cuenta de paolagp para no modificar funciones de valor vigentes. 
2. La distribución de sectores quedó:
- Industrial - @vichdzgeo 
- Forestal - @paola-gp 
- Urbano - @ofegarcia 
- Energía - @Nayita 
- Silvopastoril y todos los nuevos @CorinaCantero

**Comment by paola-gp** [comment]
@Nayita:

Agregar la siguiente leyenda, en la sección de **mapa de aptitud integrado**, aquellos sectores que fueron integrados y que no se hizo la ponderación explícita en los talleres:

_El mapa de aptitud se integró considerando que los subsectores son igualmente importantes y, por lo tanto, tienen el mismo peso._

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
