### ISSUE TITLE
Generar gráficas y bases de datos para el estado de Yucatán #fomix

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#6]
Área de estudio: Estado de Yucatán

Actividades:
Revisar el Anexo de la Demanda Específica YUC-2018-04-01, subsistemas natural, productivo y socioeconómico y hacer una lista de los insumos necesario para la generación de gráficas y bases de datos solicitados

Ruta documento: CARPETAS_TRABAJO\ccantero\fomix_yucatan_demanda_especifica

**Comment by CorinaCantero** [comment]
## Insumos disponibles 

![image](https://user-images.githubusercontent.com/44783182/67226431-8299c580-f3fa-11e9-9419-119167409694.png)

**Comment by CorinaCantero** [comment]
@aleestrada en el comentario "Gráficos y bases de datos solicitados en el Anexo de FOMIX" se indican los matrices y gráficas que se deben hacer y en el comentario anterior puse que insumos  ya están descargados. 
¿Me puedes decir que otra información se necesitaría para calcular las matrices y tasas?

**Comment by aleestrada** [comment]
Tengo algunas dudas:

- ¿Cuál es el periodo de análisis del proyecto?
- ¿Cuál es la escala temporal del proyecto?

**Comment by aleestrada** [comment]
@CorinaCantero 
Te pido que por el momento descargues información sobre:

- PIB a nivel estatal para los últimos 10 años, a precios constantes del 2013, divididos por actividad económica (primaria, secundaria y terciaria). Esto lo encuentras en el BIE del INEGI, si se te complica encontrarlos me dices. (si quieres deja esto al final)
- Tasas de crecimiento de la población y proyecciones de crecimiento (tasas).  CONAPO
- Población por localidad CONAPO de los últimos años (para el periodo más largo que encuentres, pero que sea el mismo que el número de localidades, mayor a 10 años)
- Número de localidades de los últimos años (para el periodo más largo que encuentres)
- Tasa de mortalidad por sexo y fecundidad para los últimos 10 años. CONAPO
- Verificar los datos de población, si se tienen los de INEGI es preferente usar los de CONAPO.
- Población por sexo y grupos quinquenales para 2010 por municipio (supongo que tienes las del 2019) CONAPO

** Tener presentes las ligas de dónde se descarga la información por si se requiere incrementar el periodo de análisis.

**Comment by CorinaCantero** [comment]
- Se solicitó por medio de INFOMEX a CONAPO bases de datos de la población por localidad en los últimos diez años y bases de datos de la tasa global de fecundidad y de mortalidad por municipio, pues solo encontré disponible esa información por entidad.

**Ubicación:** FOMIX\fmx_insumos\fmx_estadisticas
Se descargaron las siguientes bases de datos:

Nombre | Fuente | Año
-- | -- | --
Proyecciones de la Población de los   Municipios de México, 2015-2030 (base 2) | CONAPO | 2015-2030
Tasa global de fecundidad por   entidad federativa, México, 1990-2018. | Secretaria de Salud | 1990-2018
Mortalidad general por   entidad federativa, por sexo. 1990-2018 | INEGI | 1990-2018
Defunciones y mortalidad   general (cruda y estandarizada por edad) por sexo, según entidad federativa   de residencia habitual | Secretaria de Salud | 2000-2008
Listado de localidades de   Yucatán | SEDESOL | 2010
XII Censo General de   Población y Vivienda 2000. Principales resultados por localidad (ITER) | INEGI | 2000, 2010

**Comment by CorinaCantero** [comment]
Se ha recibido respuesta de la solicitud de información solicitada a CONAPO:

**a. SOLICITUD** : “Base de datos de tasa global de fecundidad por municipio para el estado de Yucatán.  Base de datos de mortalidad por municipio para el estado de Yucatán.  De ser posible que la información sea de los últimos 10 años.”

**a. RESPUESTA**:  _El Consejo Nacional de Población tiene estimaciones de defunciones y de Tasa Global de Fecundidad a partir de las Proyecciones de Población de México y de las Entidades Federativas, 2016-2050 pero sólo a nivel estatal, la razón de ello es que entre más desagregada se la estimación a realizar, ésta es menos precisa. Puede consultar defunciones y nacimientos a partir de los registros administrativos, teniendo en consideración que al tratarse de un registro, existen casos de registro tardío o sub-registro:_

https://www.inegi.org.mx/sistemas/olap/Proyectos/bd/continuas/mortalidad/MortalidadGeneral.asp
https://www.inegi.org.mx/sistemas/olap/Proyectos/bd/continuas/natalidad/nacimientos.asp

**b. SOLICITUD**: “Base de datos de la población por localidad de los últimos 10 años para el estado de Yucatán.”

**b. RESPUESTA**: _En estos momentos el Consejo Nacional de Población cuenta con proyecciones de población para las entidades federativas y los municipios del país, sin embargo, para este ejercicio no se generarán proyecciones a nivel localidad a partir del nuevo ejercicio de proyecciones, debido a que la principal fuente para generar las actuales proyecciones fue una encuesta probabilística, cuyas estimaciones a ese nivel geográfico no son posibles. Nuevas estimaciones de proyecciones a nivel localidad se realizarán a partir del Censo 2020, por el momento se puede consultar el Censo 2010 del INEGI para tener estimaciones a nivel localidad para el año 2010:_

https://www.inegi.org.mx/programas/ccpv/2010/default.html#Tabulados

Se guarda el documento completo de las respuestas en: 
FOMIX\fmx_insumos\fmx_estadisticas\resp_solicitud_conapo1
FOMIX\fmx_insumos\fmx_estadisticas\resp_solicitud_conapo2

**Comment by CorinaCantero** [comment]
@aleestrada En este issue puedes encontrar información acerca de las bases de datos y gráficas solicitadas para el proyecto FOMIX. También puedes consultar los siguientes archivos:

- **Catálogo de las bases de datos que se han descargado:** FOMIX\fmx_insumos\fmx_estadisticas\fmx_bd_catalogo
- **Propuesta del proyecto presentada por LANCIS:** \FOMIX\propuesta_lancis_12oct18
-  **Demanda Específica YUC-2018-04-01 (revisar ANEXO subsistema productivo) :** \FOMIX\fmx_demanda_especifica_abr18 

Las bases de datos se ubican en: FOMIX\fmx_insumos\fmx_estadisticas, las carpetas están organizadas por proveedor del recurso, ahí mismo puedes ir guardando las nuevas bases de datos que descargues.

**Comment by CorinaCantero** [comment]
### Aviso

Ubicación: (FOMIX\fmx_insumos\fmx_estadisticas) 

Se organizó la información de acuerdo a la fuente oficial de donde se obtuvo, quedando hasta el momento las siguientes carpetas: 

* coespo: Consejo Estatal de Población
* conabio: Comisión Nacional para el Conocimiento y Uso de la Biodiversidad
* conapo: Consejo Nacional de Población
* coneval: Consejo Nacional de Evaluación de la Política de Desarrollo Social
* inegi: Instituto Nacional de Estadística y Geografía	
* inpi: Instituto Nacional de los Pueblos Indígenas		
* sedesol: Secretaría de Desarrollo Social    
* siegy: Sistema de Información Estadística y Geográfica del Estado de Yucatán

A su vez, cada carpeta está organizada en las siguientes subcarpetas:
- **insumos**: Contiene las bases de datos como fueron proporcionados por las instituciones, en caso de contener metadatos también se deberán guardar aquí.
- **procesamiento**: en esta carpeta se encuentran las bases de datos que tengan algún tipo de procesamiento. 

El catálogo que contiene todas las bases de datos aún no se concluye, pero se ubica en: FOMIX\fmx_insumos\fmx_estadisticas\fmx_bd_catalogo

Favor de avisar por este Issue si se agrega alguna base de datos para poder mantener actualizado el catálogo.

**Comment by CorinaCantero** [comment]
### Aviso

@ofegarcia @aleestrada 

Dentro de la carpeta FOMIX\fmx_insumos\fmx_estadisticas se creó la carpeta "banco_datos", la cual a su vez contiene las carpetas:

- insumos: en estas carpetas se colocarán los bancos de datos finales, según el subsistema que corresponda, los cuales deben cumplir con los protocolos de bases de datos y que servirán como insumos para @aaron-ts. 
1. sub_socioeconomico
2. sub_productivo
3. sub_natural

- procesamiento: en esta carpeta @aaron-ts colocará los productos que genere respecto a los bancos de datos.

**Comment by ofegarcia** [comment]
Guardé archivo de Excel que corresponde a base de datos municipal en la carpeta 
fmxinsumos/fmx_estadisticas/banco_datos/procesamiento/sub_socioeconomico
Nombre del archivo: bd_munic_1abr

Queda pendiente subir archivos de población quinquenal, crecimiento poblacional, población indígena.

Los archivos que procese Aarón quedarán en la carpeta    .... /finales

**Comment by aaron-ts** [comment]
Muchas gracias @ofegarcia. Además, agradecería que en el nombre de las tablas originales que usaron de INEGI agregaran el nombre de la dependencia (_tabla1_inegi.csv_ por ejemplo), y en caso de que utilicen información de otra dependencia, también agreguen el nombre de la dependencia al final (_tabla2_dependencia.csv_ por ejemplo). (@aleestrada, @CorinaCantero)
