### ISSUE TITLE
Generar video y presentación de análisis de aptitud

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#62]

**Comment by Nayita** [comment]
@CorinaCantero Indicar ubicación de insumos

**Comment by CorinaCantero** [comment]
### AVISO
Ubicación para insumos:
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\analisis_aptitud

**Comment by Nayita** [comment]
@paola-gp 
Listas figuras para revisión.
Ruta: 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\analisis_aptitud\imagenes

![fi_distancia_fv](https://user-images.githubusercontent.com/25210323/103688779-f5d41c80-4f57-11eb-92a9-f81d3fd0c73a.png)

![fi_fv_ecosistemas](https://user-images.githubusercontent.com/25210323/103688801-fff61b00-4f57-11eb-8092-b41058ad3e64.png)

**Comment by paola-gp** [comment]
@Nayita : 

- [ ] Alinear el menos deseable con el 0 y el más deseable con el 1. 

- [ ] Unificar el tipo de letra en las dos figuras. 
- [ ] Sustituir las figuras en el mismo comentario

**Comment by paola-gp** [comment]
@dpedroza74 

Figuras para video. Hay dos versiones de la integración para que elijas la que te guste mas.

![fig_ecosistemas](https://user-images.githubusercontent.com/25205806/103849963-bb5ba400-506b-11eb-9758-18ba4dc5d7e1.JPG)
![fig_carreteras](https://user-images.githubusercontent.com/25205806/103849964-bbf43a80-506b-11eb-9801-375613696567.JPG)
![fig_aptitud2](https://user-images.githubusercontent.com/25205806/103849966-bbf43a80-506b-11eb-84fb-16c0fded782b.JPG)
![fig_aptitud1](https://user-images.githubusercontent.com/25205806/103849967-bbf43a80-506b-11eb-89b5-a28ecba191a7.JPG)
![fig_localidades](https://user-images.githubusercontent.com/25205806/103849968-bc8cd100-506b-11eb-8102-50f756211188.JPG)

**Comment by dpedroza74** [comment]
@paola-gp 
envié por correo y subí propuesta de guion para videos en esta carpeta
FOMIX/fmx_estudio_tecnico/diagnostico/talleres/insumos/analisis_aptitud/guion%20video

Perdón, pero todavía usé las imágenes originales del curso. Aumenté una imagen de un diagrama que ilustra la revisión/validación de los mapas de aptitud  que integré en la carpeta de imágenes

**Comment by Nayita** [comment]
### AVISO

El nombre de las carpetas de los insumos cambió. La nueva ruta es: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\insumos\pagina_web\herramientas_taller

**Comment by Nayita** [comment]
### AVISO

Revisar el tamaño de la tipografía de la figura

![fi_sector1](https://user-images.githubusercontent.com/25210323/104754891-5cf38d00-571f-11eb-92b7-f9e476783bad.png)

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
