### ISSUE TITLE
Preparar capas para talleres de aptitud sectoriales

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#63]
### INSUMOS GENERALES 

Ruta: Las capas raster deben colocarse en: 

SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\insumos\generales

### Preparar capas
- [x] Distancia a carreteras -  insumo: sig_fomix\insumos\transporte\inegi\red_vial_19\carreteras_penyuc.shp
- [x] Distancias a todos los caminos -insumo: sig_fomix\insumos\transporte\inegi\red_vial_19\red_vial_penyuc.shp
- [x] Distancia localidades - insumo: sig_fomix\insumos\geocientifica\inegi\topografia_svi\localidades_a_penyuc.shp
- [x] Cobertura (CONAFOR) - insumo: sig_fomix\insumos\cobertura\conafor\cobertura_16
- [x] Cobertura INEGI serie VI - insumo: sig_fomix\entregables\sub_natural\usv_serie6
- [x] Cobertura INEGI serie VI - insumo: sig_fomix\entregables\sub_natural\usv_serie6 16 categorías 
- [ ] Distancias a cobertura
- [ ] Presencia de solo un tipo (o unos cuantos)
- [x] Distancia a la costa - insumo: sig_fomix\entregables\limites\linea_costa
- [x] Cuerpos de agua costeros - insumo: sig_fomix\insumos\biota\inegi\humedales\conjunto_de_datos\humedales_utm16.shp (cuerpos de agua a 10 km de la costa)
- [x] Cuerpos de agua totales - insumo: sig_fomix\insumos\biota\inegi\humedales\conjunto_de_datos\humedales_utm16.shp
- [ ] Distancias a cuerpos de agua
- [x] Precipitación - insumo: sig_fomix\procesamiento\analisis_aptitud\sector_ganadero\insumos\precipitacion
- [x] Temperatura máxima promedio - insumo: sig_fomix\procesamiento\analisis_aptitud\sector_ganadero\insumos\temperatura
- [x] Temperatura media anual: sig_fomix\insumos\amc\conabio\isoter_med_anual\temp_maisolineas_yuc.shp
- [x] Temperatura mínima promedio - insumo: sig_fomix\insumos\amc\conabio\temp_min_promedio\temp_minp_yuc_clip.shp
- [x] Edafología - insumo: sig_fomix\procesamiento\analisis_aptitud\sector_ganadero\insumos\edafologia_sii
- [ ] Edafología (solo un tipo) 
- [x] Presencia y distancia a ANP - insumo: sig_fomix\entregables\anp\anp_yuc.shp
- [x] Profundidad del acuífero - insumo: sig_fomix\procesamiento\analisis_aptitud\sector_ganadero\insumos\nivel_piezom
- [x] Elevación - insumo: sig_fomix\procesamiento\analisis_aptitud\sector_ganadero\insumos\cem
- [x] Distancia a puertos - insumo: sig_fomix\insumos\poety\puertos 
- [x] Presencia de puertos
- [x] Distancia a aeropuertos (Mérida) otro con Mérida y Cancún -insumos: sig_fomix\entregables\aeropuertos

Ubicación de rasters insumos generales: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\insumos\generales

### Preparar tablas insumo para informes
Ubicación: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\insumos\tablas_metadatos

**Comment by vichdzgeo** [comment]
## Códigos 

### Librería de funciones 
Ruta: CARPETAS_TRABAJO\vhernandez\geo_lancis\codigos
apcsig.py 

### Códigos generales para la creación de capas
ruta: \SIG\desarrollo\sig_fomix\códigos

**Comment by CorinaCantero** [comment]
### Capas sector energía
@vichdzgeo 

- [ ] Distancia a líneas de transmisión - insumo
- [x] Distancia a carreteras
- [ ] Uso de suelo (terrenos ya impactados)
- [x] Distancia a poblaciones 

 **Capas de exclusión:**
- [ ] Hábitat de fauna en peligro de extinción (ANP) - insumo
- [ ] Cenotes - insumo
- [ ] Zonas arqueológicas - insumo

**Potencial Eólico**

- Velocidad del viento 
Insumos: sig_fomix\insumos\redes_sum\inel\potencial_eolico\velocidad_viento\velocidad_viento_yuc
- [ ] Velocidad del viento 30 m (anual) -insumo: 
- [ ] Velocidad del viento 50 m (anual)
- [ ] Velocidad del viento 80 m (anual)
- [ ] Velocidad del viento 120 m (anual)

- Densidad potencial del viento
Insumos: sig_fomix\insumos\redes_sum\inel\potencial_eolico\densidad_viento\densidad_yuc
- [ ] Densidad potencial del viento 30 m (anual)
- [ ] Densidad potencial del viento 50 m (anual)
- [ ] Densidad potencial del viento 80 m (anual)
- [ ] Densidad potencial del viento 120 m (anual)

** Potencial solar**
- [ ] Irradiación global anual 
- [ ] Irradiación directa anual

**Potencial biomasa**

**Comment by vichdzgeo** [comment]
## Avisos

- para las capas de **Velocidad del viento** se realizaron continuas, extrayendo el valor del intervalo inferior del campo "Velocidad"

- para las capas de **Densidad potencial del viento** se realizaron categóricas

- La capa de **Residuos industriales, Residuos pecuarios, ** una constante en el estado,

**Comment by paola-gp** [comment]
### Sector Urbano
Capas de polígonos de localidades (con los siguientes atributos): 

#### Atributos urbanos (funcionales)
- [ ] Equipamiento
- [ ] Infraestructura
- [ ] Fuentes de empleo
- [ ] Conectividad (índice grado de aislamiento de la población)

#### Atributos demográficos
- [ ] Densidad (habitantes/ha)
- [ ] Tamaño poblacional (número de habitantes 2015)
- [ ] Inmigración (municipio??) - (Número de habitantes que llegaron a la "localidad" en 2015??)
- [ ] Población indígena (% de la población indígena en la localidad o municipio)
- [ ] Tasa de crecimiento (**localidad** o municipío) 

-

**Comment by CorinaCantero** [comment]
### SECTOR INDUSTRIAL

**Biofísicos**

- [ ] Cobertura (zonas urbanas, asentamientos humanos)
- [ ] Dispersión de emisiones 
- [ ] Disponibilidad de agua 

**Socioeconómicos**

- [ ] Localidades
- [ ] Industria instalada
- [ ] Tenencia de la tierra

**Infraestructura**

- [ ] Manejo de residuos
- [ ] Conectividad
- [ ] Agua
- [ ] Electricidad
- [ ] Telecomunicaciones

**Capas exclusión**

- [ ] Hidrología: cenotes, vulnerabilidad de contaminación de acuíferos
- [ ] Cobertura: agrícola, forestales
- [ ] ANP
- [ ] Programas de desarrollo urbano
- [ ] Derechos de vía y zonas federales ZOFEMAT, aeropuertos, torres de transmisión, gasoductos

**Comment by CorinaCantero** [comment]
### SECTOR FORESTAL

Atributos:

**Biofísicos**

- [ ] Cobertura 
- [ ] Tipo de suelo
- [ ] Clima
- [ ] Riesgos para la actividad forestal (plagas, incendios)

**Socioeconómicos**

- [ ] Autorizaciones de aprovechamiento forestal vigentes
- [ ] Tenencia de la tierra
- [ ] Cercanía a mercados

**Infraestructura**

- [ ] Distancia a redes de comunicación: red de caminos primarios y secundarios
- [ ] Localidades
- [ ] Centros de acopio y transformación

**Comment by vichdzgeo** [comment]
## Aviso  en procesamiento

### Localidades con acceso a agua potable y Viviendas particulares habitadas que disponen de internet

Se ocuparon los datos del censo 2020, La localidad **Leona Vicario**  con Clave 310500408, no tiene datos en los campos requeridos para el procesamiento, por lo cual se colocan los campos de la localidad Vecina Kanasín
@CorinaCantero @TatianaMerino

**Comment by CorinaCantero** [comment]
### **AVISO**
@vichdzgeo 

Capas de ANP: 

- **SDS ANP** (última versión entregada, faltan Ría Lagartos, Ría Celestún y Bala'an K'aax): SIG\desarrollo\sig_fomix\insumos\ambiente\sds\anps_2020\anps2.shp
- **SDS ANP** (versión anterior completa): SIG\desarrollo\sig_fomix\insumos\ambiente\sds\anps_sds\ANPs.shp
- **CONANP:** SIG\desarrollo\sig_fomix\insumos\ambiente\conanp\anp_federal\anp_federal_yuc.shp
- **CONABIO:**
SIG\desarrollo\sig_fomix\insumos\ambiente\conabio\anp_estatal_muni\anp_est_mun_priv.shp

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
