### ISSUE TITLE
Integrar informe del análisis de aptitud del sector industrial #FOMIX

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/fomix#67]
### **[TALLER DE APTITUD SECTOR INDUSTRIAL](https://lancis-apc.github.io/fomix/industrial_pr.html)** 

Ruta para insumos: \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\industrial

Ruta para informe.md: \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source

**Comment by TatianaMerino** [comment]
# Insumos sesión 1 y 2

El sector se dividió en dos subsectores: (1) Ligera y (2) Pesada y mediana

El modelo multicriterio se trabajó en subredes. Archivo: industrial_red_21ene2021_v2.sdmod
Copia de los avances en una sola jerarquía: industrial_simple_21ene2021.sdmod

Los criterios son los mismos para ambos subsectores. Archivo: tabla_def_ind.xlsx (en las pestañas del documento están las definiciones de los criterios de cada subsector)

**Comment by Nayita** [comment]
@TatianaMerino 

Convertir tabla de definiciones a CSV

**Comment by CorinaCantero** [comment]
## SIG - Preparación de insumos geográficos

**Biofísicos**

- Cobertura (zonas urbanas, asentamientos humanos)
 _**Opción 1. Polígonos de zonas urbanas y rurales INEGI 2019**
Opción 2. Polígonos de uso de suelo y vegetación (urbano construido) INEGI 2016
Opción 3. Polígonos de uso de suelo y vegetación (urbano y construido) CONAFOR 2016_
- Dispersión de emisiones 
**_No hay info disponible_**
- Disponibilidad de agua - distancia a manto freático y calidad
_**Nivel piezométrico (m) POETY**
Calidad del agua -Pozos de monitoreo CONAGUA 20_

**Socioeconómicos**

- Localidades
_**Número de habitantes
% población con agua, luz y drenaje**_
-  Industria instalada
_**Capa de unidades económicas industriales en localidades**_ 
Alguna categoría específica del DENUE? 
- Tenencia de la tierra
_**Capa ejidal/no ejidal**_

**Infraestructura**

- Manejo de residuos: sitios de disposición final (basureros, rellenos sanitarios, disposición de residuos peligrosos)
_**Sitios de disposición final de residuos INEGI-SEMARNAT 2017 (basurero, relleno sanitario, sitio de disposición final de residuos, tiraderos)**_
-  Conectividad
**_Distancia a carreteras
Distancia a puertos pesqueros y comerciales
Distancia a infraestructura ferroviaria_**
- Agua
_**Acceso a red de agua potable (no disponible)
Plantas potabilizadoras (no disponible)
Plantas de tratamiento **_ 
- Electricidad
**_CENACE capacidad de carga en nodos (no disponible)_** 
- Telecomunicaciones: cobertura de red IFETEL
**_No hay info disponible_**

### **Capas exclusión**
-  Hidrología: cenotes, vulnerabilidad de contaminación de acuíferos
-  Cobertura: agrícola, forestales
-  ANP
-  Programas de desarrollo urbano
- Derechos de vía y zonas federales ZOFEMAT, aeropuertos, torres de transmisión, gasoductos

**Comment by Nayita** [comment]
@dpedroza74 

Para Vo. Bo.

![industrial](https://user-images.githubusercontent.com/25210323/105781117-8f7b6200-5f37-11eb-9cbd-4357214596ac.png)

**Comment by CorinaCantero** [comment]
## Tablas metadatos

### Infraestructura

Capa | Distancia a carreteras
-- | --
Fuente | [1] Conjunto de datos vectoriales de información topográfica por Entidad   Federativa Serie VI. (localidad_250a) INEGI y [2] Red nacional de caminos   INEGI
Año | 2019
Escala | [1] 1:250,000; [2]Sin dato
Unidades | Kilómetros


Capa | Distancia a puertos
-- | --
Fuente | [1] Conjunto de datos vectoriales   de información topográfica por Entidad     Federativa Serie VI. (localidad_250a) INEGI y [2] Ubicación de los   principales puertos de el estado de Yucatán POETY
Año | [1]2019 y [2] 2002
Escala | Sin dato
Unidades | Kilómetros


Capa | Distancia a red ferroviaria
-- | --
Fuente | Red ferroviaria INEGI
Año | 2012
Escala | 1:50,000
Unidades | Kilómetros


Capa | Distancia a agua
-- | --
Fuente | Censo de Población y Vivienda 2010. Principales resultados por localidad   (ITER) INEGI
Año | 2010
Campo | VPH_AGUADV
Escala | Localidad
Unidades | Kilómetros


Capa | Distancia líneas de transmisión de energía   eléctrica
-- | --
Fuente | Líneas de transmisión INEGI
Año | 2012
Escala | 1:50,000
Unidades | Kilómetros



Capa | Distancia a plantas de tratamiento de agua   residual
-- | --
Fuente | Datos vectoriales de las plantas municipales de tratamiento de aguas   residuales en operación registradas en el inventario nacional CONAGUA
Año | 2017
Escala | 1:250,000
Unidades | Kilómetros


Capa | Distancia a residuos
-- | --
Fuente | Sitios de disposición final de residuos INEGI-SEMARNAT
Año | 2017
Escala | Sin dato
Unidades | Kilómetros

**Comment by TatianaMerino** [comment]
# Actualización de insumos (sesión 3)

_Industria pesada y mediana_
**Modelo multicriterio**: industrial_red_26ene2021_v4.sdmod 
**Definiciones:** tabla_def_ind_pesm_v2.csv

**Comment by Nayita** [comment]
### AVISO

Listas actualizaciones indicadas.

@vichdzgeo 

Favor de publicar el informe.

**Comment by TatianaMerino** [comment]
## Actualizaciones 

Se agregó plantas de tratamiento de aguas residuales como subcriterio de Manejo de Residuos. 

Insumos
Modelo: **industrial_red_27ene2021.sdmod** e industrial_pesm_27ene2021.sdmod

Definiciones: **tabla_def_ind_pesm_v4.csv**

**Comment by Nayita** [comment]
@vichdzgeo 

Diagrama actualizado para guía de capas.

**Comment by Nayita** [comment]
### AVISO

Listos avances actualizados del informe.

@vichdzgeo  

Favor de publicar actualización.

**Comment by Nayita** [comment]
@vichdzgeo 

Favor de hacer una nueva publicación. Se hizo una corrección de último momento.

**Comment by dpedroza74** [comment]
@Nayita @TatianaMerino 

En la página de avances incluir todos los puntos de la meta

- Incrementar la productividad y diversificar las actividades en sector industrial, considerando las actividades e infraestructura de: (1) producción, (2) almacenamiento y centros de distribución y de logística, y (3) comercialización de insumos y productos terminados
- Disminuir el impacto ambiental, en cuanto al consumo de recursos y suelo y generación de residuos
- Promover la producción en el sector industrial mediante el favorecimiento de economía circular
- Promover la descentralización de la actividad industrial hacia la zona sur y oriente

**Comment by TatianaMerino** [comment]
## Insumos sesión 4 

**Modelos**

- Red con ambos subsectores: industrial_red_28ene2021_v3.sdmod 
- AHP de industria ligera: industrial_lig_28ene2021_v3.sdmod
- AHP de industria mediana y peada: industrial_pesm_28ene2021.sdmod

**Actualización de definiciones**

- tabla_def_ind_lig.csv
- tabla_def_ind_pesm_v5.csv 
 
Se pusieron en auxiliares las versiones caducadas:
tabla_def_ind_pesm_v2.csv 
tabla_def_ind_pesm_v3.csv
tabla_def_ind_pesm_v4.csv

**Funciones de valor categóricas**
Tenencia: tabla_cat_fv_ind_pesm_socio_tenencia_tierra
Cobertura: tabla_cat_fv_ind_pesm_socio_tenencia_tierra.csv

**Comment by Nayita** [comment]
### AVISO

Diagrama del modelo del subsector de industria ligera

![industria_ligera](https://user-images.githubusercontent.com/25210323/106341361-9faa7e80-6262-11eb-9f9e-458f03f8f683.png)

**Comment by TatianaMerino** [comment]
@Nayita 
## Actualizaciones de definiciones 
tabla_def_ind_lig_v2.csv
tabla_def_ind_pesm_v7.csv

## Actualizaciones de diagrama
Al diagrama de **Industria ligera** modificar la conexión del clúster **Manejo de residuos**.
Y modificar los nombres de los criterios conforme a las tablas de definiciones actualizadas, por favor.

**Comment by CorinaCantero** [comment]
## SIG - actualizaciones

**Industria pesada y mediana**

- [ ] Energía: distancia a gasoductos y líneas de transmisión eléctrica (solo líneas de 230kV o más)
- [ ] Acceso a agua?
- [ ] Industria instalada: industria con más de 50 trabajadores (DENUE) + parques industriales (presencia) 

**Industria ligera**

- [ ] Industria instalada: industria ligera y almacenamiento (almacenamiento/ industria-fabricación de equipo de computo) + polígono del parque científico tecnológico de Yucatán (242)
- [ ] Localidades: asignar un peso de 1 a las localidades que tengan universidades tecnológicas y 0.25 al resto. El producto final es distancia a localidades

**Comment by Nayita** [comment]
### AVISO

@TatianaMerino 

Listas actualizaciones. 

Falta actualizar tabla de fv categóricas de cobertura con las correcciones solicitadas. @TatianaMerino favor de notificar en cuanto esté para incluirla en el informe.

**Comment by TatianaMerino** [comment]
@Nayita 
Listas las actualizaciones. 

Recordatorio: Las funciones de valor son las mismas para Industria Ligera e Industria Pesada y mediana. Lo único que cambia son los pesos y los subcriterios Biofísicos.

**Comment by Nayita** [comment]
### AVISO

Se incorporaron las tablas de fv categóricas para ambos subsectores.

@vichdzgeo 

Favor de publicar las actualizaciones del informe.

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 
Se modificaron las siguientes tablas de insumos:

**Para industria ligera:**
- Distancia a carreteras (hay una tabla para carreteras de un carril y para carreteras de dos o más carriles)
- Red ferroviaria: por favor cambiar en el apartado Capa "distancia a red ferroviaria" por "distancia a vías ferroviarias"
- Aeropuertos:  tabla_insumos_fv_lig_infra_d_aeropuertos
- Acceso a agua: fv_lig_infra_loc_acceso_agua
- Comunicación: tabla_insumos_fv_lig_infra_loc_internet
- Rellenos sanitarios: fv_lig_infra_d_relleno_sanitario
- Basureros: fv_lig_infra_d_basureros
- Industria instalada: fv_lig_socio_ind_instalada
- Localidades:  fv_lig_socio_d_localidades
- Tenencia de la tierra: fv_lig_socio_tenencia_tierra

**Para industria pesada y mediana:** 
- Energía: tabla_insumos_fv_ind_pesm_infra_d_linea_electrica
- Acceso a agua: tabla_insumos_fv_ind_pesm_infra_d_agua
- Carreteras: mismo caso que para industria ligera, hay dos tablas para carreteras de un carril y para carreteras de dos o más carriles (utilizar las mismas tablas que para industria ligera: tabla_insumos_fv_lig_infra_d_carreteras_1carril y ...._2mcarril)
- Red ferroviaria: por favor cambiar en el apartado capa "distancia a red ferroviaria" por "distancia a vías ferroviarias"
-  Aeropuertos: ya está la tabla (utilizar la misma que en industria ligera) tabla_insumos_fv_lig_infra_d_aeropuertos
- Rellenos sanitarios: fv_lig_infra_d_relleno_sanitario
- Basureros: fv_lig_infra_d_basureros
- Comunicación: tabla_insumos_fv_lig_infra_loc_internet
- Industria instalada: tabla_insumos_fv_ind_pesm_socio_ind_pesm
- Localidades:  fv_lig_socio_d_localidades
- Tenencia de la tierra: fv_lig_socio_tenencia_tierra
- Cobertura: en el apartado Capa borrar lo que está entre paréntesis (zonas urbanas)

**Comment by Nayita** [comment]
### AVISO

@CorinaCantero 

Agregadas las tablas de insumos solicitadas.

Avances de informe con numeración solicitada.

@vichdzgeo 

- [ ] Favor de publicar avances del informe.

**Comment by Nayita** [comment]
@ofegarcia

Falta lista de asistencia en el informe. Indicar ruta.

**Comment by ofegarcia** [comment]
@Nayita
La lista de asistencia del sector está disponible en fmx_estudio técnico/ diagnostico/talleres/sectores/industrial
Archivo: lista_asistencia_industrial.pdf

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de incorporar lo siguiente al informe: 

### **Industria ligera:**

**Parámetros FV**
- [ ] fi_fv_lig_infra_loc_internet
- [ ] fi_fv_lig_infra_d_carreteras_1carril
- [ ] fi_fv_lig_infra_d_carreteras_2mcarril
- [ ] fi_fv_lig_infra_d_aeropuertos
- [ ] fi_fv_lig_infra_d_puertos
- [ ] fi_fv_lig_infra_d_red_ferroviaria
- [ ] fi_fv_lig_infra_d_lineas_electricas
- [ ] fi_fv_lig_infra_loc_acceso_agua
- [ ] fi_fv_lig_infra_d_plantas_agua_residual
- [ ] fi_fv_lig_infra_d_relleno_sanitario
- [ ] fi_fv_lig_infra_d_basureros
- [ ] fi_fv_lig_socio_d_localidades

**Mapas**

- [ ] mapa_fv_lig_infra_loc_internet
- [ ] mapa_fv_lig_infra_d_carreteras_1carril
- [ ] mapa_fv_lig_infra_d_carreteras_2mcarril
- [ ] mapa_fv_lig_infra_d_aeropuertos
- [ ] mapa_fv_lig_infra_d_puertos
- [ ] mapa_fv_lig_infra_d_red_ferroviaria
- [ ] mapa_fv_lig_infra_d_lineas_electricas
- [ ] mapa_fv_lig_infra_loc_acceso_agua
- [ ] mapa_fv_lig_infra_d_plantas_agua_residual
- [ ] mapa_fv_lig_infra_d_relleno_sanitario
- [ ] mapa_fv_lig_infra_d_basureros
- [ ] mapa_fv_lig_socio_ind_instalada
- [ ] mapa_fv_lig_socio_d_localidades
- [ ] mapa_fv_lig_socio_tenencia_tierra
- [ ] mapa_fv_lig_bio_usv_16cats


### **Industria pesada**
Las gráficas de FV y mapas son las mismas que para industria ligera excepto:

- [ ] Industria instalada: 
- [ ] Energía: 
- [ ] Disponibilidad de agua:
- [ ] Dispersión de emisiones:
- [ ] Cobertura:

**Comment by TatianaMerino** [comment]
@Nayita, favor de agregar al informe de **industria pesada y mediana**

- [ ] Tabla de función categórica de **dispersión de emisiones** en factores biofísicos (tabla_cat_fv_ind_pesm_vulnerabilidad_acuidero.xlsx)

- [ ] Tabla de función categórica de **disponibilidad de agua** en factores biofísicos (tabla_cat_fv_ind_pesm_d_manto_acuifero.xlsx)

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

@vichdzgeo 

- [ ] Favor de publicar.

**Comment by vichdzgeo** [comment]
## Áreas por categoría de aptitud para industria ligera 


Categoría | Km² | Porcentaje del   estado
-- | -- | --:
Muy alta | 517 | 1
Alta | 1415.7 | 4
Moderada | 6897.1 | 17
Baja | 25415.6 | 64
Muy baja | 2874.9 | 7
Nula | 2416.2 | 6

## Áreas por categoría de aptitud para industria pesada

Categoría | Km² | Porcentaje del   estado
-- | -- | --:
Muy alta | 1529.5 | 4
Alta | 2570.8 | 7
Moderada | 10017.6 | 25
Baja | 17272.4 | 44
Muy baja | 5730.1 | 14
Nula | 2416.2 | 6

@Nayita

**Comment by vichdzgeo** [comment]
## Mapas de aptitud

ruta: talleres\sectores\industrial\aptitud
### mapa de aptitud
- ind_industria_ligera.tif
- - ind_industria_pesada.tif
### mapa de exclusión para el mapa de aptitud 
- ind_industria_ligera_capa_exclusion.tif
- - ind_industria_pesada_capa_exclusion.tif
@CorinaCantero 

## Figuras de análisis de sensibilidad
@Nayita  estas figuras fueron copiadas en el directorio de:
alleres\sphinx\docs\source\recursos\industrial

- fi_analisis_sensibilidad_industria_ligera.png
- - fi_analisis_sensibilidad_industria_pesada.png

**Comment by CorinaCantero** [comment]
AVISO
@Nayita 

Favor de incluir lo siguiente en el informe: 
- [ ] mapa_aptitud_lig
- [ ] mapa_aptitud_pesm
- [ ] mapa_exclusion_pesm
- [ ] mapa_exclusion_lig

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@CorinaCantero @TatianaMerino @vichdzgeo 

Faltan insumos de aprovechamiento actual de ambos subsectores, tabla de pesos globales de ambos subsectores e insumos de las capas de exclusión de ambos subsectores.

**Comment by CorinaCantero** [comment]
### CAPAS DE EXCLUSIÓN
@Nayita 

La siguiente información aplica tanto para industria pesada como para industria ligera, por favor agregar al informe:

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional


ID | Categoría
-- | --
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

**Comment by dpedroza74** [comment]
@Nayita @TatianaMerino 
Revisando el informe de industria ligera, considero que sería necesario integrar esto en la definición del atributo _Localidades_ en el cluster de socioeconómicos para que quede claro por qué algunas localidades quedan en morado

Distancia a localidades donde se tiene acceso a capital social, servicios y mercado. **Se asigna un mayor peso de importancia a las localidades donde hay universidades e instituciones de educación superior con carreras en el campo de informática, computación, sistemas o afines.**

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Favor de hacer las siguientes correcciones en el informe: 

- [ ] Tabla de insumos de la sección 1.2.1.1 cambiar en Unidades de **Adimensional** a **Porcentaje**
- [ ] Tabla de insumos de la sección 1.2.1.4 cambiar en Unidades de **Adimensional** a **Porcentaje**
- [ ] Tabla de insumos de la sección 1.2.2.2 cambiar en Unidades de **Kilómetros** a **Adimensional**
- [ ] Quitar la gráfica de FV de la sección 1.2.2.2 
- [ ] Tabla de insumos de la sección 2.2.1.1 agregar en Fuente: [2] Gasoductos GeoComunes con datos de CRE, SEMARNAT, ASEA y CFE
- [ ] Tabla de insumos de la sección 2.2.1.2 cambiar en Unidades de **Adimensional** a **Porcentaje**
- [ ] Tabla de insumos de la sección 2.2.1.5 cambiar en Unidades de **Adimensional** a **Porcentaje**
- [ ] Quitar el acento a sabana para el criterio de cobertura

**Comment by vichdzgeo** [comment]
## Tabla del atributo de Localidades de industria ligera 


Categoría | Importancia | FV
-- | -- | --:
Distancia de 5 kms a localidades que   cuentan con universidades con carreras de computación o afines | Muy alta | 1.00
Distancia de 5 kms a localidades | Baja | 0.25

@Nayita

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe.

**Comment by dpedroza74** [comment]
@Nayita 
Favor de hacer las siguientes correcciones en el informe

Cambiar definiciones tanto en la tabla de definiciones como en la descripción del insumo 

**Industria ligera**
1.2.1.1 Comunicación
Distancia de 5 km a localidades que se evaluaron con base en el porcentaje de viviendas con internet.
1.2.1.4 Acceso a agua
Distancia de 5 km a localidades que se evaluaron con base en el porcentaje de viviendas con acceso a agua potable.
1.2.2.1 Industria instalada
Distancia de 5 km a localidades con unidades económicas registradas en el Directorio Estadístico Nacional de Unidades Económicas del INEGI en las categorías (334) Fabricación de equipo de computación, comunicación, medición y de otros equipos, componentes y accesorios electrónicos y (493) Servicios de almacenamiento, así como el Parque Científico Tecnológico de Yucatán.
1.2.2.2 Localidades
Distancia de 5 km a localidades donde se tiene acceso a capital social, servicios y mercado. Se asigna un mayor peso de importancia a las localidades donde hay universidades e instituciones de educación superior con carreras en el campo de informática, computación, sistemas o afines.

**Industria mediana y pesada**
2.2.1.5 Comunicación
Distancia de 5 km a localidades que se evaluaron con base en el porcentaje de viviendas con internet.
2.2.1.2 Acceso a agua
Distancia de 5 km a localidades que se evaluaron con base en el porcentaje de viviendas con acceso a agua potable.
2.2.2.1 Industria instalada
Distancia de 5 km a parques industriales y localidades con unidades económicas registradas en el Directorio Estadístico Nacional de Unidades Económicas del INEGI en la categoría (31-33). Industrias manufactureras excepto la categoría (334).

**Comment by dpedroza74** [comment]
OJO @vichdzgeo  @Nayita 
 En la tabla del atributo de Localidades de industria ligera  quitar la "**s**" a 5 kms debe decir **5 km**

**Comment by ofegarcia** [comment]
@Nayita 

Sa actualizó la lista de asistencia del sector industrial, disponible en fmx_estudio técnico/ diagnostico/talleres/sectores/industrial
Archivo: lista_asistencia_industrial.pdf

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor corregir lo siguiente en el informe: 

- [ ] Tabla de insumos de las secciones 1.2.1.4 y 2.2.1.2  Acceso a agua 

Capa | Viviendas que disponen de agua entubada por   localidad
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Campo | [2] VIVTOT y VPH_AEASP
Unidades | Adimensional

- [ ] Quitar los apartados de aprovechamiento actual, porque en este caso se incluyeron en el modelo
- [ ] La imagen del mapa de aptitud de industria mediana y pesada me sale rota

**Comment by CorinaCantero** [comment]
### **TABLAS DE PESOS GLOBALES**
@Nayita 

Favor de agregar al informe:

- [ ] Industria pesada y mediana

Criterio | Peso
-- | --
Energía | 0.246
Industria instalada | 0.228
Acceso a agua | 0.146
Localidades | 0.081
Disponibilidad de agua | 0.056
Carreteras de varios carriles | 0.052
Tenencia | 0.042
Puertos | 0.031
Cobertura | 0.025
Comunicación | 0.022
Rellenos sanitarios | 0.016
Plantas de agua residual | 0.016
Red ferroviaria | 0.012
Dispersión de emisiones | 0.008
Basureros | 0.008
Aeropuertos | 0.006
Carreteras de un carril | 0.006

- [ ] Industria ligera 


Criterio | Peso
-- | --
Comunicación | 0.162
Carreteras de un carril | 0.009
Carreteras de varios carriles | 0.082
Aeropuertos | 0.041
Puertos | 0.019
Red ferroviaria | 0.006
Energía | 0.140
Acceso a agua | 0.073
Rellenos sanitarios | 0.011
Basureros | 0.006
Plantas de aguas residuales | 0.011
Industria instalada | 0.228
Localidades | 0.081
Tenencia | 0.042
Cobertura | 0.090

**Comment by Nayita** [comment]
### AVISO

Informe concluido.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita

Por favor hacer las siguientes modificaciones en la parte de **exclusión** para industria ligera y pesada:

- [ ] Cambiar tabla de insumos para exclusión: 

Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Polígonos de localidades.   Marco Geoestadístico. Censo de Población y Vivienda INEGI
Año | [1] 2017; [2] 2020
Campo | [1] descripcio
Escala | [1] 1:250,000; [2] Sin dato
Unidades | Adimensional

- [ ] Agregar números entre corchetes y el enunciado después del número [2]
- [ ] Cambiar la tabla de ID y categoría por la siguiente:

[1]


[2] Se utilizaron todas las localidades (urbanas y rurales)

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

- [ ] Por favor corregir las tablas de exclusión para industria ligera y mediana-pesada para incluir el campo ND 17:

ID | Categoría
-- | --
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila
17 | ND

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

**Comment by paola-gp** [comment]
@CorinaCantero 

- [ ] Se actualiza capa de cobertura de las dos industrias, subir capa actualizada a SIGfunctionD

**Comment by CorinaCantero** [comment]
### **AVISO**
@vichdzgeo

Listas las capas evaluadas y exportadas de cobertura (corregida con capa de manglares) para industria ligera y pesada
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\industrial\funciones_valor

- fv_pesm_bio_cobertura_usv_svi_16cats_costa_manglar
- fv_lig_bio_cobertura_usv_svi_16cats_costa_manglar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor hacer las siguientes actualizaciones a las tablas de insumos en el informe:

- [ ] Cobertura para industria mediana-pesada y ligera


Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Exclusión 

Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo   de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000;[2] 1:50,000; [3] Sin dato
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Actualizaciones 

Listas las actualizaciones para este sector 

- [ ] Actualizar figuras de mapas de aptitud @CorinaCantero 
- [ ] Actualizar figuras de mapas de exclusión @CorinaCantero 
- [ ] Actualizar las tablas de categorías de aptitud en Sphinx @Nayita

**Comment by vichdzgeo** [comment]
## Producto final

### Mapa integrado

### Insumos

- ind_industria_ligera_sigindex.tif w = 0.5
- ind_industria_pesada_sigindex.tif w = 0.5
- ind_industria_ligera_exclusion.tif
- ind_industria_pesada_exclusion.tif

### Productos

- industrial.tif (mapa categorizado con zonas de exclusión)
- indutrial_integrado.tif (mapa normalizado entre 0 y 1 )
- industrial_exclusion.tif

### Tabla de área por categoría de aptitud

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 662.7 | 2
Alta | 2551.4 | 6
Moderada | 9717.4 | 25
Baja | 21178.7 | 54
Muy baja | 2709.8 | 7
Nula | 2716.5 | 7

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Listo mapa de aptitud integrada y mapa de exclusión para el sector industrial: 
- [ ] mapa_aptitud_industrial
- [ ] mapa_exclusion_industrial

**Comment by CorinaCantero** [comment]
### PESOS GLOBALES DEL MAPA DE APTITUD INTEGRADO DEL SECTOR INDUSTRIAL

Criterio | Peso
-- | --
Basureros - Ligera | 0.200
Energía - Pesada | 0.123
Industria instalada - Ligera | 0.114
Industria instalada - Pesada | 0.114
Comunicación - Ligera | 0.081
Acceso a agua - Pesada | 0.073
Energía - Ligera | 0.070
Cobertura - Ligera | 0.045
Localidades - Ligera | 0.041
Localidades - Pesada | 0.041
Carreteras - varios carriles - Ligera | 0.041
Acceso a agua - Ligera | 0.037
Disponibilidad de agua - Pesada | 0.028
Carreteras-varios carriles - Pesada | 0.026
Tenencia - Ligera | 0.021
Tenencia - Pesada | 0.021
Aeropuertos - Ligera | 0.020
Puertos - Pesada | 0.016
Cobertura - Pesada | 0.013
Comunicación - Pesada | 0.011
Puertos - Ligera | 0.010
Rellenos sanitarios - Pesada | 0.008
Plantas de aguas residual - Pesada | 0.008
Plantas de aguas residuales - Ligera | 0.006
Red ferroviaria - Pesada | 0.006
Rellenos sanitarios - Ligera | 0.005
Carreteras - un carril - Ligera | 0.005
Basureros - Pesada | 0.004
Dispersión de emisiones - Pesada | 0.004
Red ferroviaria | 0.003
Carreteras -un carril - Pesada | 0.003
Aeropuertos - Pesada | 0.003

**Comment by CorinaCantero** [comment]
### CORRECCIONES
@Nayita 

Por favor hacer las siguientes correcciones: 

- Actualizar las siguientes tablas de insumos:

- [ ] Industria ligera 1.2.1.4 Acceso a agua e Industria mediana y pesada 2.2.1.2 Acceso a agua

Capa | Viviendas que disponen de agua entubada por   localidad
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Escala | Localidad
Campo | [2] VIVTOT y VPH_AEASP
Unidades | Adimensional

- [ ]  Industria ligera 1.2.2.1 Industria instalada

Capa | Industria ligera instalada por localidad
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI, [2] Datos de indicador. Directorio Estadístico Nacional de   Unidades Económicas (DENUE) INEGI y [3] Polígono del Parque Científico   Tecnológico de Yucatán. Parques industriales en la Península de Yucatán   Ayuntamiento de Mérida
Año | [1][2] 2020; [3] 2016
Escala | [1][2] Localidad; [3] 1:65,000
Unidades | Adimensional

- [ ] Industria ligera 1.2.2.2 Localidades e Industria pesada y mediana 2.2.2.2 Localidades

Capa | Distancia a localidades
-- | --
Fuente | Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI
Año | 2020
Escala | Localidad
Unidades | Kilómetros

- [ ] Industria mediana y pesada 2.2.1.5 Comunicación

Capa | Viviendas con internet por localidad
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Escala | Localidad
Campo | [2] VIVTOT y VPH_INTER
Unidades | Porcentaje

- [ ] Industria mediana y pesada 2.2.2.1 Industria instalada

Capa | Industria mediana y pesada instalada
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI, [2] Datos de indicador. Directorio Estadístico Nacional de   Unidades Económicas (DENUE) INEGI y [3] Parques industriales en la Península   de Yucatán Ayuntamiento de Mérida
Año | [1][2] 2020; [3] 2016
Escala | [1][2] Localidad; [3] 1:65,000
Unidades | Adimensional

- [ ] En la tabla de insumos 2.2.3.1 Disponibilidad de agua cambiar el Año de Sin dato a **2007**

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

- [ ] Favor de agregar al informe lo siguiente:

**Zona de exclusión del mapa integrado**

Tabla de insumos: 

Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y vegetación de la zona costera asociada a los manglares, Región Península de Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000;[2] 1:50,000; [3] Sin dato
Unidades | Adimensional

[1] y [2]

ID | Categoría
-- | --
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila
17 | ND

[3] Se seleccionaron las localidades urbanas y Sisal

**Comment by Nayita** [comment]
### Diagrama del modelo de decisión del mapa integrado

![fi_industrial_integrado](https://user-images.githubusercontent.com/25210323/120404656-741ccb00-c30c-11eb-9d1c-e861e692ce9d.png)

**Comment by Nayita** [comment]
### AVISO

Durante el proceso de revisión de capas de WMS se detectaron diferencias de color en los mapas de la función de valor de tenencia en el sector industria ligera y mediana y pesada y las capas entregadas.

Ver figuras

Mapa del informe de industria ligera

![image](https://user-images.githubusercontent.com/25210323/161829716-be2df1eb-b97a-4c62-aeb9-935fda669437.png)


Mapa del informe de industria mediana y pesada

![image](https://user-images.githubusercontent.com/25210323/161829688-e77db903-978f-41fb-b514-cccab42bda01.png)


Capa entregada

![image](https://user-images.githubusercontent.com/25210323/161830138-7de87cc9-662b-4716-b5c9-418e5b5fd42e.png)

**Importante revisar la capa porque en la función de valor se tienen tres categorías máxima, alta y muy baja. El color de la capa de muy baja no corresponde al color de la categoría en la capa entregada.**

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
