### ISSUE TITLE
Integrar informe del análisis de aptitud del sector urbano #FOMIX

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/fomix#68]
### [TALLER DE APTITUD SECTOR URBANO](https://lancis-apc.github.io/fomix/urbano_pr.html)

- **Ubicación de insumos para el informe** FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\urbano

- **Ubicación de productos del taller** FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\urbano

**Comment by ofegarcia** [comment]
### Insumos sesiones 1 y 2 ### 
La tabla de definiciones de criterios está disponible en \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\urbano
Nombre del archivo: tabla_def_urb.xls

La estructura jerárquica está disponible en:
\FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\urbano\modelo
Nombre del archivo: urbano_21_ene_2021_v5.sdmod

**Comment by Nayita** [comment]
@ofegarcia 

Convertir tabla de definiciones a CSV

**Comment by CorinaCantero** [comment]
## SIG

Para integrar las capas geográficas solicitadas en el issue #63 se descargaron los principales resultados por localidad (ITER) de los Censos y Conteos de Población y Vivienda 2000 y 2010:

Campos a extraer para cada banco de datos: 

**CENSO 2000**

RUTA:
SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\sectores\urbano\insumos\censos\iter_yuc_2000

Campos:

Campo | Descripción
-- | --
ENTIDAD | Clave entidad
NOM_ENT | Nombre de la entidad
MUN | Clave del municipio
NOM_MUN | Nombre del municipio
LOC | Clave de la localidad
NOM_LOC | Nombre de la localidad
POBTOT | Población total

**CENSO 2010**

RUTA:
SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\sectores\urbano\insumos\censos\iter_yuc_2010

Campos:

Campo | Descripción
-- | --
ENTIDAD | Clave entidad
NOM_ENT | Nombre de la entidad
MUN | Clave del municipio
NOM_MUN | Nombre del municipio
LOC | Clave de la localidad
NOM_LOC | Nombre de la localidad
POBTOT | Población total
PDER_SS | Población     derechohabiente a      servicio de salud
VPH_C_SERV | Viviendas particulares habitadas     que disponen de luz eléctrica,     agua entubada de la red pública     y drenaje
VIVTOT | Total de viviendas
POCUPADA | Población ocupada
PNACOE | Personas nacidas en otra entidad federativa
P3YM_HLI | Población de 3 años y más que     habla alguna lengua indígena

**Comment by Nayita** [comment]
### AVISO

@paola-gp 

Dar vo. bo. de figura.

![urbano](https://user-images.githubusercontent.com/25210323/105745550-0434a900-5f04-11eb-8645-e3745409373f.png)

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 
Listas las tablas de insumos. Ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\urbano

**Comment by ofegarcia** [comment]
@Nayita 
### Sesión 3 ###
Para incluir los resultados de la sesión 3, se actualizaron los siguientes archivos: 
**Tabla de definiciones**
Archivo: tabla_def_urb_26ene21.csv
Ubicación: f\FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\urbano
Cambios:
1)	Meta del sector redactada en un solo enunciado.
2)	Cambio de “Criterio” por “Atributo” en todos los niveles.
3)	Definición de Tasa de crecimiento: cambio de 2005-2015 por 2000-2010.
4)	Definición de Equipamiento: se incluyeron “transportes, correo y almacenamiento”.
5)	Adición de elementos y definiciones para Equipamiento (escuelas, centros de salud y edificios administrativos).
6)	Se eliminaron los “Polos de desarrollo”

**Modelo**
Archivo:  urbano_26_ene_2021_v3
Ubicación:  \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\urbano\modelo
Cambios:
1)	Se modificó la definición de la meta, para dejar un solo enunciado.
2)	Se cambiaron los años en la definición de Tasa de crecimiento, para dejar 2000-2010
3)	Se modificó la definición de Equipamiento para incluir “transportes, correo y almacenamiento”.
4)	Se agregó clúster de Equipamiento_1.2.1, con tres nodos, sus definiciones y comparaciones pareadas.
5)	Se eliminó clúster de “Polos de desarrollo”

**Comment by Nayita** [comment]
### AVISO

@ofegarcia 
Listas las actualizaciones.

**Comment by vichdzgeo** [comment]
## Polos de crecimiento 

el archivo se encuentra en 

\talleres\sectores\urbano\funciones_valor\auxiliares\polos_de_crecimiento_loc.xlsx

@paola-gp

**Comment by Nayita** [comment]
@vichdzgeo 

Favor de actualizar avances del informe de urbano.

**Comment by paola-gp** [comment]
#### Actualización del mapa de aptitud sectorial urbano con base en acuerdos del 28 de enero
1. Agregar a la capa de localidades a Sisal (aunque sea un punto) - @vichdzgeo 
2. Actualizar la base de datos del Censo 2020 si hay información para localidades @ofegarcia 
3. Verificar tasa de crecimiento @ofegarcia. 
3. Actualizar capas para subir mapa de aptitud  @Victor
4. Actualizar tablas de informe para reemplazar censo 2000 por 2020 @CorinaCantero 
4. Agregar en la sección de mapa de aptitud leyenda que diga: **Este mapa se actualizará para incluir como aptitud muy alta los póligonos de reserva territorial incluidos den los programas de desarrollo urbano y vivienda del estado.** 
5. Incluir resumen de método de análisis de dispersión @paola-gp 

Fecha de publicación final sugerida miércoles 3 de febrero

**Comment by paola-gp** [comment]
#### 5. Incluir resumen de método de análisis de dispersión #70 
@Nayita: Ya está la síntesis del atributo ambiental  **Conectividad** para que sea agregado (en cuanto nos avise @vichdzgeo de su actualización) al informe en Sphinx

ubicación: talleres\sectores\urbano\informe\insumos/metodo_indice_dispersion_sintesis.docx

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Se hicieron correcciones a todas las tablas de insumos del sector, mapas y gráficas. Favor de actualizar en el informe.

**Comment by Nayita** [comment]
### AVISO

Listas las correcciones solicitadas incluyendo la síntesis del atributo Conectividad.

En espera de la capa de exclusión y el mapa de aptitud; tabla de áreas por categoría de aptitud y sensibilidad de atributos, si es el caso.

**Comment by vichdzgeo** [comment]
## Capa de exclusión 
@paola-gp  
¿Se definió alguna capa o atributos para la generación de capa de exclusión?

**Comment by CorinaCantero** [comment]
### AVISO

@Nayita 
Favor de agregar la siguiente tabla de insumos al informe: 

- Edificios administrativos: tabla_insumos_fv_urb_urb_equi_equipamiento_admin

**Comment by paola-gp** [comment]
8/02/2021

@CorinaCantero:

El mapa de la fv de población indígena está mal. Pedir a @vichdzgeo que dé la última versión para subirla al informe.

**Comment by vichdzgeo** [comment]
@CorinaCantero 
Ruta: diagnostico\talleres\sectores\urbano\funciones_valor

- [ ] mapa correcto de población indígena  : fv_urb_dem_indi_por_pob_indigena.tif
- [ ] mapa de polos de crecimiento: polos_de_crecimiento.tif
- [ ] mapa de aptitud urbano: apt_urbano_sigindex_equidistante.tif
- [ ] mapa de crecimiento orgánico : fv_urbano_crecimiento.tif

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Se agregaron los siguientes mapas para el informe del sector urbano:
- mapa_aptitud_urb
- mapa_fv_urbano_crecimiento
- mapa_polos_crecimiento

**Comment by paola-gp** [comment]
@Nayita 

### Sección 1.3 Mapa de aptitud

1.3.1 Priorización de polos de crecimiento
1.3.2 Crecimiento urbano orgánico
Agregar insumo y función de valor
1.3.3 Zonas de exclusión 
Agregar leyenda:  **Este mapa se actualizará para incluir como aptitud muy alta los póligonos de reserva territorial incluidos en los programas de desarrollo urbano y vivienda del estado.**
1.3.4 Reservas territoriales urbanas 
1.3.5 Mapa de aptitud urbano
1.3.6 Sensibilidad de atributos ambientales

**Comment by Nayita** [comment]
@CorinaCantero 

Falta insumo y función de valor del mapa de crecimiento urbano orgánico (mapa_fv_urbano_crecimiento)

**Comment by Nayita** [comment]
### AVISO

Listas actualizaciones del informe

@vichdzgeo 

- [ ] Favor de publicar actualizaciones del informe

**Comment by Nayita** [comment]
@ofegarcia 

Falta lista de asistencia en el informe. Indicar ruta

**Comment by ofegarcia** [comment]
La lista de asistencia del sector urbano está disponible en fmx_estudio técnico/ diagnostico/talleres/sectores/urbano
Archivo: lista_asistencia_urbano.pdf

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de agregar lo siguiente al informe del sector urbano:

- [ ] Edificios administrativos: tabla_insumos_fv_urb_urb_equi_equipamiento_admin
- [ ] fi_fv_crecimiento_urbano_organico
- [ ] tabla_insumo_crecimiento_urbano

**Comment by Nayita** [comment]
### AVISO

Listas actualizaciones del informe.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### AVISO

@Nayita 

Las siguientes tablas de insumos no se copiaron con el formato correcto, por favor hacer una revisión: 

- [ ] 1.2.2.2 Población
- [ ] 1.2.2.3 Densidad

**Comment by paola-gp** [comment]
@Nayita:

Falta leyenda en la sección 1.3.4 
Está pendiente la recepción de la capa geográfica con los póligonos de reserva territorial incluidos en los programas de desarrollo urbano y vivienda del estado.

**Comment by paola-gp** [comment]
@Nayita y @CorinaCantero 

Está mal puesta la leyenda y faltan las zonas de exclusión.

**Comment by paola-gp** [comment]
@CorinaCantero @vichdzgeo @ofegarcia 

Zonas de exclusión: cuerpos de agua (incluyendo cenotes)

**Comment by Nayita** [comment]
### AVISO

Lista actualización del informe.

@vichdzgeo 

- [ ] Favor de publicar.

**Comment by paola-gp** [comment]
@vichdzgeo 
Aprovechamiento actual (aptitud muy alta)

- [ ] 1. Categoría urbano de USV 16 categorías
- [ ] 2. Polígonos de INEGI urbanos y rurales
- [ ] 3. Reservas territoriales (pendientes de entrega por parte de SDS)

**Comment by paola-gp** [comment]
@Nayita y @CorinaCantero 
modificar en Fuente de empleo que la capa diga únicamente Unidades económicas totales (eliminar excepto agricultura y minería)

**Comment by vichdzgeo** [comment]
## Mapa de aptitud Urbano

ruta: talleres\sectores\urbano\aptitud

**urb_urbano.tif** Mapa final con exclusión y aprovechemiento
**urb_urbano_exclusion.tif** mapa de exclusión
**urb_urbano_aprovechamiento**.tif mapa de aprovechamiento actual  
**tabla_urb_urbano_areas_categorias.xlsx** area por categorias de aptitud

**Comment by vichdzgeo** [comment]
## Área por categoria de aptitud


Categoría | Km² | Porcentaje del   estado
-- | -- | --
Muy alta | 1060.3 | 3
Alta | 0.0 | 0
Moderada | 192.4 | 0
Baja | 2230.0 | 6
Muy baja | 34032.4 | 86
Nula | 2021.5 | 5


@Nayita

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de agregar los siguientes mapas al informe: 
- [ ] Mapa aprovechamiento actual sector urbano ----> mapa_aprov_urbano
- [ ] Mapa exclusión ----> mapa_exclusion_urb

**Comment by Nayita** [comment]
### AVISO

Listas actualizaciones del informe

**Comment by Nayita** [comment]
### AVISO

Figura de sensibilidad incluida en el informe.

**Comment by CorinaCantero** [comment]
### **Tablas exclusión**
@Nayita 

ID | Categoría
-- | --
1 | Cenote
2 | Charca
3 | Depresión húmeda
4 | Estanque artificial
5 | Estanque de acuicultura
6 | Estero
7 | Excavación
8 | Lago
9 | Laguna costera
10 | Laguna húmeda
11 | Llanura inundada
12 | Marisma

**Comment by CorinaCantero** [comment]
CAPA DE EXCLUSIÓN
@vichdzgeo 

- [ ] Capa de cenotes SDS: sig_fomix\insumos\agua\sds\cenotes_union.shp
- [ ] Capa de humedales: \sig_fomix\insumos\biota\inegi\humedales\conjunto_de_datos\humedales_utm16.shp
- [ ] Capa USV SVI INEGI: SIG\desarrollo\sig_fomix\entregables\sub_natural\usv_serie6; Utilizar el atributo "id_clase1" = 6 o 
"clase1" = Cuerpo de agua

**Comment by Nayita** [comment]
### AVISO

@CorinaCantero @vichdzgeo 
Falta el mapa de reservas territoriales urbanas para concluir el informe.

**Comment by CorinaCantero** [comment]
### **Observaciones 23/02/21**

- [ ] Verificar pesos @ofegarcia 
- [ ] 1.2.2.1 Tasa de crecimiento: actualizar en definiciones de demográfico 2010-2020
- [ ] Agregar tabla "polos_de_crecimiento_2020" después del mapa en la sección 1.3.1 Priorización de polos de crecimiento (con vínculo)
Ruta: 
- [ ] Para mapa de exclusión. Quedan: estero, laguna costera y marisma ----> se quita lo de cenotes (pendiente a SDS diga que es de jurisdicción federal y que no) @CorinaCantero

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

**Comment by ofegarcia** [comment]
@Nayita 

Sa actualizó la lista de asistencia del sector urbano, disponible en fmx_estudio técnico/ diagnostico/talleres/sectores/urbano
Archivo: lista_asistencia_urbano.pdf

**Comment by Nayita** [comment]
### AVISO

Listo el vínculo de la lista de asistencia.

@vichdzgeo 

- [x] Favor de publicar

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.

**Comment by victor** [comment]
Pues yo no he actualizado ninguna capa
