### ISSUE TITLE
Integrar informe y análisis de la caracterización del Subsistema Natural #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#7]
### ACTIVIDAD
Escribir el texto solicitado en el documento "Demanda específica Yuc-2018-04-01" 

- Ubicación:  FOMIX/fmx_demanda_especifica_2018-04.pdf 

En donde se indica que debe tener las siguientes características: "texto que contenga la caracterización y análisis del Subsistema Natural, incluyendo los siguientes aspectos: tipo, cantidad y ubicación y cartografía de los temas: geología, relieve, climatología y efectos climáticos, suelo, agua, biota (vegetación y fauna silvestre); se presentarán las unidades de paisaje o zonificación ecológica; presencia de fenómenos geomorfohidrológicos (ciclones, huracanes, inundaciones, heladas, sequías, granizadas y otros); mapa de aptitud del territorio, mapa de potencialidad del territorio y mapa de habitabilidad."

"**Subsistema natural**: _El análisis de este subsistema, será establecido en el contexto de las características básicas de geología, climatología y las formas de relieve resultantes de su combinación pasada y presente. Los elementos, suelo, agua, vegetación y fauna silvestres, así como el aire, deberán ser tratados de manera particular. En conjunto, se analizarán los elementos del medio físico-biótico en las dos vertientes siguientes: ecosistemas naturales como soporte de los asentamientos humanos y el desarrollo de sus actividades económicas._"

**Comment by CorinaCantero** [comment]
@Nayita 
Aquí puedes por favor poner la ubicación del documento de la caracterización hecha para el proyecto de Pacífico Norte, para tomarla como guía.

**Comment by CorinaCantero** [comment]
Índice propuesto para la caracterización del subsistema natural, basado en la propuesta de FOMIX:

- [ ] Geomorfología 
-Fisiografía (provincias fisiográficas)
- [ ] Geología 
-Sistema de fallas y fracturas
-Relieve
-Modelo digital de elevación*
- [ ] Edafología 
-Tipos de suelo
-Degradación del suelo
- [ ] Climatología
-Tipos de climas
-Temperatura media anual (isotermas)
-Precipitación media anual (isoyectas)
-Estaciones meteorológicas*
-Efectos climáticos (?)
- [ ] Fenómenos naturales 
-Geológicos: hundimientos, procesos de remoción en masa
-Hidrometeorológicos: depresiones, tormentas tropicales, ciclones, huracanes, inundaciones, marea de tormenta, sequías, incendios forestales) Incluyendo registros históricos*
-Riesgo y vulnerabilidad del territorio a eventos naturales
- [ ] Hidrología superficial 
-Regionalización hidrológica (CONAGUA, INEGI, INE-INEGI-CONAGUA)
-Cuencas hidrológicas
-Cuerpos de agua (lagunas costeras, cenotes)
-Calidad del agua superficial
- [ ] Hidrología subterránea
-Acuíferos 
-Disponibilidad del agua (acuíferos explotados, recarga, uso)
-Calidad del agua subterránea
-Balance hídrico*
- [ ] Biota (vegetación y fauna silvestre)
-Tipología y estado de la vegetación, especies de flora y fauna relevantes
-Composición de especies
-Especies en la NOM-059-SEMARNAT-2010 (distribución)
-Composición de especies hábitat de reproducción, alimentación y/o refugio de especies de flora y fauna en algún estatus de riesgo de acuerdo con la NOM-059-SEMARNAT-2001
-Productividad primaria
-Biomasa
-Distribución de especies de importancia para el aprovechamiento o cultivos comerciales
-Vegetación y uso del suelo (vegetación costera*)
-Cambio de uso de suelo
-Grado de fragmentación
-Protección de la Biodiversidad 
- [ ] -Áreas de manejo o protección especial (incluyendo especies con estatus) 
-Regiones prioritarias (CONABIO) 
-Áreas críticas PROFEPA
-Regiones hidrológicas prioritarias
-Regiones terrestres prioritarias
-Áreas Naturales Protegidas
-Áreas de Importancia para la conservación de las aves
-Sitios RAMSAR 
-Unidades para la conservación, manejo y aprovechamiento sustentable de la vida silvestre*
- [ ] Aire
-Calidad del aire … 
- [ ] -Unidades de paisaje o zonificación ecológica
- [ ] -Mapa de aptitud del territorio
- [ ] -Mapa de potencialidad del territorio
- [ ] -Mapa de habitabilidad 
- [ ] -Fragilidad del territorio
- [ ] -Calidad de los recursos (incorporando al menos agua, vegetación y suelo)
- [ ] -Síntesis del diagnóstico

**Comment by Nayita** [comment]
@CorinaCantero 
El manual para informes se encuentra en la siguiente ruta: ORGANIZACION_APC/apc_plantillas/plantillas_informes/manual_informes.pdf

**Comment by CorinaCantero** [comment]
### AVISO
@paola-gp  

En esta ubicación puedes poner los scripts de R para los climogramas:
C:\Dropbox (LANCIS)\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos

**Comment by CorinaCantero** [comment]
### Análisis de vacíos y omisiones
@Nayita 
Redactar la sección de vacíos y omisiones utilizando los mapas 1_29 y 1_30 ubicados en: SIG\desarrollo\sig_fomix\mapas\plantillas\imagenes\sub_natural\texto
Consultar la siguiente información:

- https://www.biodiversidad.gob.mx/pais/vaciosyom.html
- Programa de Ordenamiento Ecológico de Pacífico Norte, pág. 427 ubicado en:
FOMIX\fmx_estudio_tecnico\caracterizacion_subs\insumos\componente_natural_dp

**Comment by CorinaCantero** [comment]
### AIRE

**Insumos:**

- SEDUMA-Gobierno del Estado de Yucatán y SEMARNAT (2017). _Programa de gestión para mejorar la calidad del aire del estado de Yucatán 2018-2027,_ Journal of Chemical Information and Modeling. Disponible en: file:///C:/Users/User/Downloads/fvm939e.pdf. 
Contiene información de:
- Diagnostico de la calidad del aire del 2014 al 2016 
- Evaluación del cumplimiento de las NOM
- Comportamiento mensual, semanal y diario
- Inventario de emisiones
- Impactos a la salud 
- Comunicación y educación ambiental

- Sistema Nacional de Información de la Calidad del Aire, SINAICA
https://sinaica.inecc.gob.mx/
Descarga de datos por día, semana y mes, para los parámetros:
Parámetros contaminantes: dióxido de azufre, dióxido de nitrógeno, monóxido de carbono, óxido nítrico, óxidos de nitrógeno, ozono, ppm menores a 2.5 micras.
Parámetros meteorológicos: dirección del viento, humedad relativa, presión barométrica, precipitación pluvial, radiación solar, temperatura

**Comment by paola-gp** [comment]
### Acuerdos de entregables para informe de caracterización natural 03/jun/2020
#### Bases de datos con metadatos
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Mapas, proyecto QGis, PDF y metadatos
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Informe 
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Anexo metodológico
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Scripts de procedimientos
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico
#### Referencias
- [ ] Subsistema productivo 
- [ ] Subsistema natural
- [ ] Subsistema socioeconómico

**Comment by Nayita** [comment]
@CorinaCantero 

Ruta del informe revisado y corregido para que pueda ser completado.
\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\fmx_caract_natural_22abr20_nr.docx

**Comment by CorinaCantero** [comment]
### Correcciones y actividades pendientes para completar el informe de caracterización natural

- [ ] Teoría sobre evapotranspiración 3.3.5
- [ ] Teoría de flora y fauna 3.6
- [ ] Teoría sobre protección a la biodiversidad 3.7 
- [ ] Redondear las hectáreas a decenas (tablas) 
- [ ] Convertir km2 a hectáreas en las tablas que haga falta
- [ ] Arreglar las numeraciones de los mapas 3.1.
- [ ] Cambiar las numeraciones de las tablas 3.1. y centrar los números
- [ ] Citas faltantes @CorinaCantero 
- [ ] Calcular las áreas de ANPs, AICAS y sitios RAMSAR dentro del estado @CorinaCantero 

Redacción de los textos:

- [ ] Aire
- [ ] Efectos climáticos (pendiente saber a que se refiere)

Mapas: 

- [ ] Mapa de ubicación de Yucatán
- [ ] Mapa base con curvas de nivel, vías de comunicación, rasgos hidrológicos, localidades y toponimia
- [ ] Correcciones a los mapas de cambio de cobertura @CorinaCantero

**Comment by CorinaCantero** [comment]
### Avances y pendientes para el informe de caracterización natural 

## **Análisis** 

- [x] 1. **Análisis del cambio de cobertura** 
- [x] 2. **Calidad de recursos** 
- [x] 3. **Fragilidad del territorio** 
- [x] 4. **Análisis de riesgo a eventos  naturales** 
- [x] 5. **Análisis de vulnerabilidad a eventos naturales**
- [ ] 6. **Habitabilidad** 

 
## **Informes**

- [x] 1. **Caracterización y análisis del subsistema natural** @CorinaCantero  ( %)
 **Pendientes:** Hacer correcciones y terminar los apartados de: aire y efectos   climáticos (cambio climático), potencialidad del territorio (INEGI). Incorporar resultados de los otros informes. 
 **Ubicación:** \FOMIX\fmx_estudio_tecnico\caracterizacion_subs
 
- [x] 2. **Análisis del cambio de cobertura** @CorinaCantero  (75%)
 **Pendientes:** Revisión de la redacción y los resultados del análisis, propuesta de  ecuación para corregir tasa de deforestación.
**Ubicación:** FOMIX\fmx_estudio_tecnico\caracterizacion_subs\procesamiento\sub_natural\cambio_usv

- [x] 3. **Calidad de recursos** 
 **Pendientes:**
 **Ubicación:**  

- [x]  4. **Fragilidad del territorio** 
 **Pendientes:**
**Ubicación:** 

- [x] 5. **Análisis de riesgo a eventos  naturales** 
 **Pendientes:**
 **Ubicación:** 

- [x] 6. **Análisis de vulnerabilidad a eventos  naturales (PAPIIT)** 
 **Pendientes:**
 **Ubicación:** 

- [ ] 7. **Habitabilidad** 
**Pendientes:** 
**Ubicación:** 


## Anexo metodológico
- [x] 1. **Análisis del cambio de cobertura** 
- [ ] **Pendientes:** Revisar la redacción del método, @vichdzgeo terminar de redactar el procesamiento de las capas geográficas.
- [x] 2. **Calidad de recursos**   
- [x] 3. **Fragilidad del territorio** 
- [x] 4. **Análisis de riesgo a eventos  naturales** 
- [x] 5. **Análisis de vulnerabilidad a eventos naturales (PAPIIT)**
- [ ] 6. **Habitabilidad**

## Scripts de procedimientos @vichdzgeo 

- [ ] 1.  Scripts para las cruzas de capas de uso de suelo y vegetación con: degradación del suelo, ANPs, por municipios y regiones. 
- [ ] 2. **Análisis del cambio de cobertura** 
- [ ] 3. **Calidad de recursos**  
- [ ] 4. **Fragilidad del territorio** 
- [ ] 5. **Análisis de riesgo a eventos  naturales** 
- [ ] 6. **Análisis de vulnerabilidad a eventos naturales (PAPIIT)**
- [ ] 7. **Habitabilidad**

## Bases de datos con metadatos 

**Productos:**
- Bases de datos para las tres clasificaciones de uso de suelo y vegetación con diccionarios de datos (Terminado):

- Uso de suelo y   vegetación por municipio
- Uso de suelo y vegetación por región
- ANP por uso de suelo y vegetación por municipio
- ANP por uso de suelo y vegetación por región
- Degradación del suelo por tipo de cobertura por municipio
- Degradación del suelo por tipo de cobertura por región

Ubicación: FOMIX\fmx_insumos\fmx_estadisticas\banco_datos\procesamiento\sub_natural

**Pendientes:**
¿Resultados de acuerdos de la reunión del lunes 08/06/2020 con la SDS ? 

## Mapas (proyecto QGis, PDF y metadatos)
**Pendientes:**
- [x] Ordenar los proyectos para entregarlos a Víctor 
- [ ] Metadatos pendientes

**Mapas:** 
- [x] Potencialidad del territorio (INEGI, 2012) https://www.inegi.org.mx/app/biblioteca/ficha.html?upc=702825293239
- [x] Efectos climáticos (INECC y Centro de Ciencias de la Atmósfera)
- [x] Unidades de paisaje: se solicitó capa a la SDS, se presentará tal y como se usó en el POETY.
- [x] Mapa síntesis del subsistema natural

**Comment by Nayita** [comment]
@CorinaCantero 
Listo informe con los archivos del modelo de vulnerabilidad y los índices incorporados en formatos y con la numeración de tablas, mapas y figuras actualizados.
Ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\fmx_caract_natural_22jun2020_v1


Listo anexo metodológico de vulnerabilidad y tabla de capas utilizadas para el modelo. Ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\anexo_metod_vulnera.docx y tablas_capas.docx

**Comment by Nayita** [comment]
@paola-gp 
Favor de revisar informe en la ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs

Archivo: fmx_caract_natural_22jun2020_v1.docx

Faltan algunas citas que se pondrán después de la revisión.

**Comment by paola-gp** [comment]
@Nayita y @CorinaCantero: ya está la versión revisada del informe integrado. Le hace falta trabajo a la sección de vulnerabilidad costera. 
fmx_caract_natural_25jun2020_v2.docx

**Comment by Nayita** [comment]
@paola-gp 
Listo archivo para tu revisión. Ruta: \FOMIX\fmx_estudio_tecnico\caracterizacion_subs\fmx_caract_natural_25jun2020_v2.docx

**Comment by paola-gp** [comment]
@Nayita y @CorinaCantero: lista última revisión en:
\FOMIX\fmx_estudio_tecnico\caracterizacion_subs\fmx_caract_natural_30jun2020_v1.docx

@Nayita: corregir sección de vulnerabilidad costera
@CorinaCantero: agregar unidades de paisaje después de fisiografía (mismo nivel)

**Comment by Nayita** [comment]
### Aviso
Correcciones terminadas de la sección de vulnerabilidad costera.

**Comment by CorinaCantero** [comment]
### AVISO

- Ultima versión del documento FOMIX\fmx_procesamiento\obs_conacyt\documentos_corregidos\subsistema_natural_3_1
Pendiente actualizar el documento haciendo correcciones solicitadas por la SDS

**Comment by CorinaCantero** [comment]
### ACTUALIZACIÓN

El informe se actualizó para atender las observaciones solicitadas por la SDS, la última versión del documento se encuentra en: 
FOMIX\fmx_estudio_tecnico\bitacora_ambiental\pdf\subsistema_natural_1_1
