### ISSUE TITLE
Integrar informe del análisis de aptitud del sector energía #FOMIX

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/fomix#70]
Ruta para insumos: \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\energia

Ruta para informe.md: \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source

Ruta del informe publicado: https://lancis-apc.github.io/fomix/

**Comment by ofegarcia** [comment]
@Nayita 
### Sesiones 1 y ### 2
La tabla de definiciones de criterios está disponible en \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\energia
Nombre del archivo: tabla_def_ene.csv

La estructura jerárquica está disponible en:
\FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\energia\modelo
Nombre del archivo: energia_22_ene_2021_v7.sdmod

**Comment by Nayita** [comment]
@paola-gp 

Para vo. bo.

![energia](https://user-images.githubusercontent.com/25210323/105891876-bd63b380-5fd6-11eb-92fe-20b89b2c1457.png)

**Comment by Nayita** [comment]
@vichdzgeo 

Listo avance de informe para publicar.

**Comment by CorinaCantero** [comment]
## SIG - Preparación de  insumos geográficos

Ubicación insumos: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\sectores\energia\insumos

- [ ] **Presencia de PARQUES SOLARES EN MÉXICO** (2020) http://132.248.14.102/layers/CapaBase:parque_solar_2020
parque_solar_yuc.shp
- [ ] **Presencia de POLÍGONOS PARQUES EÓLICOS EN MÉXICO** http://132.248.14.102/layers/CapaBase:parques_eolicos_poli_2020
parques_eolicos_yuc.shp
- [ ] **Gasoductos** (ver si se puede diferenciar combustoleo y gas http://132.248.14.102/layers/CapaBase:gasoductos_gc_1
`Nota:` categorías: gas LP, gas natural y poliducto. En Yucatán solo hay una línea de gas natural
gasoducto_yuc.shp
- [ ] **Presencia de AEROGENERADORES PARQUES EÓLICOS** http://132.248.14.102/layers/CapaBase:iii_1_3_aerogeneradores_2020
autogeneradores_yuc.shp
- [ ] **Demanda: CONSUMO DE ELECTRICIDAD POR MUNICIPIO** EN 2018 http://132.248.14.102/layers/CapaBase:usuarios_consumo_mun_2018
consumo_electrico_yuc.shp
- [ ] (no prioritario) CENTRALES TÉRMICAS EN LA PENÍNSULA DE YUCATÁN http://132.248.14.102/layers/CapaBase:_3_1_3_central_termica_peninsula
centrales_termicas_yuc.shp
- [ ] Centrales eléctricas https://base.energia.gob.mx/nacei/mapas_infraestructura_energetica.aspx
centrales_electricas_yuc.shp
- [ ] Centrales de energía renovable https://base.energia.gob.mx/nacei/mapas_infraestructura_energetica.aspx
centrales_erenovable_yuc.shp

**Comment by ofegarcia** [comment]
@Nayita 

Se actualizó la tabla de definiciones. Archivo: tabla_def_ene_27_ene_21
Se actualizó el modelo. Archivo: energia_27_en_2021_v9

**Comment by paola-gp** [comment]
Prioridades para evaluación:


Fuentes o criterios | Atributo |   | Peso global
-- | -- | -- | --
Fuente hidrocarburos líquidos | Distancia a carreteras | 24.0%
Fuente hidrocarburos líquidos | Distancia a poblaciones | 13.4%
Fuente gas natural | Ductos existentes | 12.4%
Fuente gas natural | Zonas industriales | 11.0%
Fuente hidrocarburos líquidos | Ductos existentes | 7.3%
Fuente solar | Distancia a red eléctrica | 6.9%
Fuente hidrocarburos líquidos | Distancia a vías férreas | 4.5%
Fuente hidrocarburos líquidos | Puerto Progreso | 4.1%
Fuente gas natural | Distancia a poblaciones | 2.6%
Fuente solar | Tipo de cobertura | 1.4%
Fuente solar | Tenencia de la tierra | 1.4%

**Comment by Nayita** [comment]
### AVISO

@vichdzgeo 

Favor de de publicar los avances del informe de energía

**Comment by CorinaCantero** [comment]
### Tabla de unidades capas potencial del recurso
Fuente: https://dgel.energia.gob.mx/inel/mapa.html?lang=es


Energía | Capa | Unidades
-- | -- | --
Eólica | Velocidad de viento a x metros de altura (anual) | m/s
Eólica | Densidad de potencia eólica a x metros de altura (anual) | W/m2
Solar | Irradiación Global Horizontal (Anual) | kWh/m2/día
Solar | Irradiación Directa Normal (Anual) | kWh/m2/día
Biomasa | Todas las capas de biomasa | TJ/a

@paola-gp

**Comment by paola-gp** [comment]
### Tareas de actualización del 2/2/21

- [ ] Generar tabla de fv de tenencia @CorinaCantero @ofegarcia 
- [ ] Generar imágenes de mapas para Sphinx @CorinaCantero 
- [ ] Integración de capa de aprovechamiento actual @vichdzgeo 
- [ ] Agregar atributos de eólico y biomasa para industrial en superdecisions @ofegarcia 
- [ ] Generar capa de exclusión con base en usv_svi_16cats.csv @vichdzgeo 
- [ ] actualizar pesos en archivo de prefijos @paola-gp 
- [ ] actualizar nombres de capas en SIGfunction, SIGfunctionD y archivo de prefijos @CorinaCantero 
- [ ] reemplazar capas que se normalizaron manualmente @vichdzgeo

**Comment by Nayita** [comment]
@paola-gp 

Para tu vo. bo. 

![energia_comunitaria](https://user-images.githubusercontent.com/25210323/106657382-902c7d80-6561-11eb-9b93-b6a9a6461fcf.png)

**Comment by paola-gp** [comment]
@Nayita 

### Validación de diagrama 
El diagrama está mal. Veo que @ofegarcia no te pasó la versión actualizada con los pesos actualizados.

#### 1. Atributos hidrocarburos líquidos, solo quedan los siguientes atributos y el resto se elimina:

Distancia   a carreteras | 0.64
-- | --
Distancia a localidades | 0.35

#### 2. Gas natural, solo quedan los siguientes:

Distancia  del gasoducto a las  zonas industriales | 0.81
-- | --
Distancia de localidades al gasoducto | 0.19

#### 3. Se elimina función de valor de tenencia }
#### 4. Se deja pendiente los atributos de eólica y biomasa hasta acordar con participantes

**Comment by Nayita** [comment]
@vichdzgeo 







@vichdzgeo 

Favor de publicar avances de informe de  energía

**Comment by paola-gp** [comment]
Pendientes 3 de febrero 

- [ ] Actualizar meta @ofegarcia 
Garantizar el cuidado y el aprovechamiento sostenible de los recursos energéticos del estado de Yucatán, en un marco de justicia ambiental y energética, a fin de: 1) asegurar el acceso a energía asequible, sostenible, confiable y de calidad a la población y a sectores productivos del Estado; 2) reducir la pobreza energética1 y 3) contribuir a una mayor democracia en la gestión de los recursos energéticos públicos y comunes de la región. 

- [ ] Generar fv de distancias granjas porcinas @vichdzgeo (lineal decreciente mínimo 0 hasta 5 km)
- [ ] Generar fv de sitios de distancia disposición final (lineal decreciente mínimo 500m máximo 20 km)
- [ ] Generar mapas de aptitud de cada fuente @vichdzgeo 
- [ ] Integrar mapas al informe de todas las fv generadas en sesión 5 @CorinaCantero 
- [ ] Arreglar modelo y últimas definiciones @ofegarcia y diagrama @Nayita
- [ ] Agregar el aprovechamiento actual @vichdzgeo 
- [ ] Zonas de exclusión @vichdzgeo @paola-gp

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de agregar las siguientes tablas de insumos:

**Fuente eólica**
- Tipo de cobertura: tabla_insumos_fv_ene_ind_sol_cobertura_usv_svi_16cats
- Distancia a la red eléctrica: tabla_insumos_fv_ene_ind_eol_d_lineas_transmision
- Distancia a asentamientos: tabla_insumos_fv_ene_ind_eol_d_localidades
- Velocidad a 120 m de altura: tabla_insumos_fv_ene_ind_eol_velocidad_viento_120m
- Distancia a carreteras: 

**Fuente biomasa**
- Distancia a granjas porcícolas: tabla_insumos_fv_ene_ind_bio_d_granjas_porcinas
- Distancia a sitios de disposición final: tabla_insumos_fv_ene_ind_bio_d_sitios_disp_residuos
- Residuos agrícolas forestales: tabla_insumos_ene_ind_bio_potencial_biomasa_residuos_agricolas_forestales

**Comment by paola-gp** [comment]
### Capas de exclusión

- Zonas de exclusión para solar (tabla_fv_sol_cobertura_usv_svi.16cats.csv)
- Zonas de exclusión para el resto (tabla_fv_ind_eol_cobertura_usv_svi.16cats.csv)

### Zonas de aprovechamiento

Solar: parques solares
Eólico: parques eólicos
Hidrocarburos líquidos: centrales eléctricas de combustóleo y poliducto
Gas natural: Centrales eléctricas de gas y gasoducto

**Comment by ofegarcia** [comment]
La lista de asistencia del sector está disponible en fmx_estudio técnico/ diagnostico/talleres/sectores/energia
Archivo: lista_asistencia_energia.pdf

**Comment by vichdzgeo** [comment]
Listos los mapas de aptitud por fuente, incluyen zonas de exclusión y zonas de aprovechamiento

- [ ] fv_ene_ind_solar_equidistante.tif
- [ ] fv_ene_ind_hidrocarburos_equidistante.tif 
- [ ] fv_ene_ind_gas_equidistante.tif 
- [ ] fv_ene_ind_eolica_equidistante.tif 
- [ ] fv_ene_ind_biomasa_equidistante.tif

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Agregar los siguientes mapas al informe: 

- [ ] mapa_aptitud_biomasa
- [ ] mapa_aptitud_eolica
- [ ] mapa_aptitud_gas
- [ ] mapa_aptitud_hidrocarburos
- [ ] mapa_aptitud_solar
- [ ] mapa_fv_ene_ind_bio_d_granjas_porcinas
- [ ] mapa_fv_ene_ind_bio_d_sitios_disp_residuos

**Comment by vichdzgeo** [comment]
### Capas de exclusión

Ruta : ..talleres\sectores\energia\funciones_valor\exclusion

para todos los mapas excepto solar 
- fv_ene_ind_eolica_exclusion.tif
para Solar
- fv_ene_ind_solar_exclusion.tif

@CorinaCantero

**Comment by paola-gp** [comment]
@CorinaCantero @Nayita 
### Sección de mapa de aptitud del sector energía industrial
1.3.1 Mapa de aptitud de fuente hidrocarburos líquidos 
1.3.1.1 Zonas de aprovechamiento actual de hidrocarburos líquidos
1.3.1.2 Zonas de exclusión actual de hidrocarburos líquidos
1.3.1.3 Mapa de aptitud de energía de fuente hidrocarburos líquidos

1.3.2 Mapa de aptitud de fuente gas natural
1.3.2.1 Zonas de aprovechamiento actual de gas natural
1.3.2.2 Zonas de exclusión actual de gas natural
1.3.2.3 Mapa de aptitud de energía de fuente gas natural

1.3.3 Mapa de aptitud de energía solar
1.3.3.1 Zonas de aprovechamiento actual de energía solar
1.3.3.2 Zonas de exclusión actual de energía solar
1.3.3.3 Mapa de aptitud de energía solar

 1.3.4 Mapa de aptitud de energía eólica
1.3.4.1 Zonas de aprovechamiento actual de energía eólica
1.3.4.2 Zonas de exclusión actual de energía eólica
1.3.4.3 Mapa de aptitud de energía eólica

1.3.5 Mapa de aptitud de energía de fuente biomasa 
1.3.5.1 Zonas de aprovechamiento actual de energía fuente biomasa
1.3.5.2 Zonas de exclusión actual de energía fuente biomasa
1.3.5.3 Mapa de aptitud de energía de fuente biomasa

**Pesos globales de los atributos del sector energía industrial**
1.3.6 Mapa de aptitud de energía industrial
1.3.7 Sensibilidad de atributos ambientales del sector energía industrial

**Comment by vichdzgeo** [comment]
### Capas de aprovechamiento

Ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\energia\funciones_valor\aprovechamiento

Solar: parques_eolicos_yuc_presencia.tif
Eólico: parques_eolicos_yuc_presencia.tif
Hidrocarburos líquidos: aprovechamiento_hidrocarburos.tif
Gas natural: aprovechamiento_gas_presencia.tif
Biomasa: granjas_porcinas_presencia.tif
@CorinaCantero

**Comment by Nayita** [comment]
###  AVISO

Listas las actualizaciones del informe.

@vichdzgeo 

- [ ] Favor de publicar.

**Comment by paola-gp** [comment]
@vichdzgeo 

Incluir para mapa integrado de energía industrial las siguientes exclusiones generales:

- - [ ] Asentamientos humanos
- - [ ] Manglar
- - [ ] Cuerpos de agua
- - [ ] Vegetación hidrófila
- - [ ] Vegetación de petén
- - [ ] Tular

**Comment by paola-gp** [comment]
@CorinaCantero 

Faltan las tablas de lo que se considera exclusión para cada una de las fuentes y los insumos para el aprovechamiento actual.

**Comment by paola-gp** [comment]
@CorinaCantero @vichdzgeo @Nayita @ofegarcia 

- [ ] El mapa de distancia a localidades para hidrocarburos líquidos está mal (es excluyente).
- [ ] En las funciones de valor discretas no están poniendo las expresiones verbales (y el acuerdo original era si agregarlas). 
- [ ] Las funciones de valor SIEMPRE deben tener un valor de 1 como máximo, la función de valor de tenencia de la tierra para solar está mal

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Por favor actualizar la siguiente tabla en la sección cobertura 1.2.3.2
- [ ] tabla_cat_fv_ene_cobertura_usv_svi_16cats
- [ ] tabla_cat_fv_ene_tenencia_tierra

**Comment by Nayita** [comment]
### AVISO

Lista la actualización del informe.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by vichdzgeo** [comment]
## Tablas de insumos para exclusión

### Mapas por fuente de energía

para solar: tabla_fv_ene_sol_cobertura_usv_svi_16cats.xlsm 
para el resto: tabla_fv_ene_ind_eol_cobertura_usv_svi_16cats.xlsm

### Mapa integrado

tabla_fv_energia_exclusion_general_usv_svi_16cats.xlsm

@ofegarcia

**Comment by paola-gp** [comment]
Agregar en informe la leyenda antes de la sección de Mapa de aptitud (integrado)

REGLAMENTO DE LA LEY GENERAL DEL EQUILIBRIO ECOLÓGICO Y LA PROTECCIÓN
AL AMBIENTE EN MATERIA DE ORDENAMIENTO ECOLÓGICO
_Artículo 37.- Para la suscripción de los convenios de coordinación a que se refiere el artículo 20 BIS 2 de la Ley, la Secretaría deberá observar los criterios contenidos en el presente Reglamento y los instrumentos jurídicos que deriven del mismo. 
Artículo 38.- Los convenios que suscriba la Secretaría con los estados y el Distrito Federal, con la
participación que corresponda a los municipios y delegaciones, respectivamente, para la formulación de
los programas de ordenamiento ecológico a que se refiere el artículo 20 BIS 2 de la Ley, además de los
requisitos señalados en el artículo 8o. de este Reglamento, deberán establecer, entre otros aspectos:
Las materias y actividades que constituyen el objeto del convenio respectivo. **No podrán ser objeto de estos convenios las actividades que permiten el desarrollo de la industria de hidrocarburos, ni las actividades a que se refiere el artículo 3o., fracción XI de la Ley de la Agencia Nacional de Seguridad Industrial y de Protección al Medio Ambiente del Sector Hidrocarburos, conforme lo previsto en el artículo 95 de la Ley de Hidrocarburos.**_

**Comment by ofegarcia** [comment]
@Nayita 
Tablas incorporadas en la carpeta sphinx/docs/source/recursos/energia

### tabla_cat_fv_ene_ind_eol_cobertura_usv_svi_16cats.xls

ID | Cobertura | Importancia | FV
-- | -- | -- | --
2 | Agricultura de riego | Máxima | 1.00
3 | Agricultura de temporal | Máxima | 1.00
5 | Bosque cultivado/Palmar inducido | Máxima | 1.00
8 | Pastizal | Máxima | 1.00
11 | Sin vegetación | Máxima | 1.00
9 | Selva baja | Baja | 0.56
10 | Selva mediana | Baja | 0.56
12 | Sábana | Muy baja | 0.33
15 | Vegetación de petén | Muy baja | 0.33
1 | Acuícola | Nula | 0.00
4 | Asentamiento humano | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
7 | Manglar | Nula | 0.00
13 | Tular | Nula | 0.00
14 | Vegetación de duna costera | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

### tabla_cat_fv_ene_sol_cobertura_usv_svi_16cats.xls
ID | Categoría | Importancia | FV
-- | -- | -- | --
2 | Agricultura de riego | Máxima | 1.00
3 | Agricultura de temporal | Máxima | 1.00
5 | Bosque cultivado/Palmar inducido | Máxima | 1.00
8 | Pastizal | Máxima | 1.00
11 | Sin vegetación | Máxima | 1.00
4 | Asentamiento humano | Moderada | 0.70
9 | Selva baja | Baja | 0.56
10 | Selva mediana | Baja | 0.56
12 | Sábana | Muy baja | 0.33
1 | Acuícola | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
7 | Manglar | Nula | 0.00
13 | Tular | Nula | 0.00
14 | Vegetación de duna costera | Nula | 0.00
15 | Vegetación de petén | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00



### tabla_cat_fv_ene_tenencia_tierra.xls

ID | Categoria | FV
-- | -- | --
3 | No ejidal | 1.00
2 | Zona de tierras parceladas | 0.52
1 | Tierra de uso común | 0.19


### tabla_ex_ene_general_usv_svi_16cats.csv

ID | Cobertura
-- | --
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe. Falta tabla de exclusión para la fuente solar.

**Comment by vichdzgeo** [comment]
## Área por categoría de aptitud


Categoría | Km² | Porcentaje del   estado
-- | -- | --
Muy alta | 617.2 | 2
Alta | 2080.0 | 5
Moderada | 9211.1 | 23
Baja | 17249.7 | 44
Muy baja | 7959.2 | 20
Nula | 2419.4 | 6

@Nayita

**Comment by vichdzgeo** [comment]
## mapa de aptitud
RUTA: talleres\sectores\energia\aptitud
ene_energia.tif

### análisis de sensibilidad

fi_analisis_sensibilidad_energia.png

@Nayita

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de agregar los siguientes mapas al informe:

- [ ] Mapa de aptitud de energía industrial ---->mapa_aptitud_energia
- [ ] Mapa de aprovechamiento actual  ----->mapa_aprov_energia
- [ ] Mapa de exclusión del sector energía industrial ----->mapa_exclusion_energia

**Comment by ofegarcia** [comment]
@Nayita 

Las siguientes tablas de exclusión del sector están disponibles en la carpeta de sphinx/docs/source/recursos/energia

### Tablas de exclusión por fuente de energía
 **Para solar:** tabla_ex_ene_sol_cobertura_usv_svi_16cats.csv

ID | Cobertura
-- | --
1 | Acuícola
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila


**Para el resto:** tabla_ex_ene_ind_eol_cobertura_usv_svi_16cats.csv
ID | Cobertura 
-- | --
1 | Acuícola
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
16 | Vegetación halófila hidrófila

### Tabla de exclusión para mapa integrado:  tabla_ex_ene_general_usv_svi_16cats.csv

ID | Cobertura
-- | --
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

**Comment by Nayita** [comment]
### AVISO

Listas gráficas actualizadas.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### **Observaciones para concluir el informe de aptitud 23/02/2021**

- [ ] Verificar pesos @ofegarcia 
- [ ]  Mapa de aptitud de energía industrial de fuentes renovables, se eliminaria de la integración del mapa de aptitud los hidrocarburos líquidos y gas natural **Pendiente de que se discuta si será así o no**
- [ ] Modificar tablas de insumos de fuente GeoComunes con datos de .... @CorinaCantero

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Favor de hacer las siguientes correcciones en el informe: 
- [ ] Tabla de insumos de la sección 1.2.2.1 agregar en Fuente: [2] Gasoductos GeoComunes **con datos de CRE, SEMARNAT, ASEA y CFE**
- [ ] Tabla de insumos de la sección 1.2.2.2  agregar en Fuente: [2] Gasoductos GeoComunes **con datos de CRE, SEMARNAT, ASEA y CFE**
- [ ] Tabla de insumos de la sección 1.2.5.2 agregar en Fuente: Granjas porcinas y avícolas en la Península de Yucatán GeoComunes **con datos de SAGARPA SIAP

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones

**Comment by ofegarcia** [comment]
@Nayita 

Se actualizó la lista de asistencia del sector energía, disponible en fmx_estudio_técnico/ diagnostico/talleres/sectores/energia
Archivo: lista_asistencia_energia.pdf

**Comment by Nayita** [comment]
### AVISO

Listo el informe final.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by ofegarcia** [comment]
### AVISO

@Nayita 
Se **actualizó la lista de asistencia**, para atender una solicitud de eliminar a Ezequiel Toledo.
Archivo: fmx_estudio_tecnico/diagnostico/talleres/sectores/energia/lista_asistencia_energia.pdf
**Nota**: se conserva el archivo con la lista original (lista_asistencia_energia_orig)

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

- [ ] Por favor corregir las tablas de exclusión (hidrocarburos líquidos, gas natural, energía solar, energía eólica, biomasa y mapa integrado) para agregar la categoría 17 - ND 

ID | Cobertura
-- | --
1 | Acuícola
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila
17 | ND

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

**Comment by paola-gp** [comment]
@CorinaCantero 

- [ ] Se actualiza capa de cobertura de solar y eólica, subir capa actualizada a SIGfunctionD

**Comment by CorinaCantero** [comment]
### **AVISO**
@vichdzgeo 

Listas las capas evaluadas y exportadas de cobertura (corregida con capa de manglares) para energía eólica y solar
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\energia\funciones_valor

- fv_ene_ind_eol_cobertura_usv_svi_16cats_costa_manglar
- fv_ene_ind_sol_cobertura_usv_svi_16cats_costa_manglar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor hacer las siguientes actualizaciones a las tablas de insumos en el informe: 

- [ ] Cobertura para energía solar y energía eólica

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Exclusión hidrocarburos líquidos, gas natural, solar, eólica, biomasa y exclusión general de energía 

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Actualizaciones 
Ruta : \FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\energia\aptitud 
Se actualizaron los mapas de aptitud 

- Energía (integrado) ene_energia.tif
- Energía solar ene_energia_solar.tif
- Energía eólica  ene_energia_eolica.tif
- Exclusión Energía (integrado) ene_energia_exclusion.tif
- Exclusión Energía solar ene_energia_solar_exclusion.tif
- Exclusión  Energía eólica  ene_energia_eolica_exclusion.tif


Actualizar 

- Figuras de mapas de aptitud para los mapas actualizados @CorinaCantero 
- Figuras de mapas de exclusión para los mapas actualizados @CorinaCantero 
- Tabla de categorías de aptitud  @Nayita

**Comment by vichdzgeo** [comment]
## Actualizaciones

- [ ] Actualizar figuras de los mapas de aptitud @CorinaCantero 
 - biomasa
 - gas
 - hidrocarburos

**Comment by vichdzgeo** [comment]
## Producto final 
### Mapa integrado 

Insumos

- ene_energia_biomasa_sigindex.tif w = 0.08875
- ene_energia_solar_sigindex.tif w= 0.55906
- ene_energia_eolica_sigindex.tif w = 0.35219


# Productos

- energia_integrado.tif (mapa normalizado entre 0 y 1)
- energia.tif (mapa captegorizado con zonas de exclusión y aprovechamiento actual

### Tabla de áreas por categoria de aptitud 

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 1786.4 | 5
Alta | 10186.2 | 26
Moderada | 13293.6 | 34
Baja | 9922.8 | 25
Muy baja | 2476.1 | 6
Nula | 1871.4 | 5

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Se generó la figura del mapa de aptitud de energía renovable, favor de agregar al informe:

- [ ] mapa_aptitud_energia_renovable

**Comment by CorinaCantero** [comment]
### PESOS GLOBALES MAPA DE APTITUD ENERGÍA RENOVABLE
@Nayita 

- [ ] Favor de agregar al informe

Fuente de energía | Criterio | Peso
-- | -- | --
Eólica | Cobertura | 0.046
Eólica | Distancia a la red eléctrica | 0.074
Eólica | Distancia a localidades | 0.014
Eólica | Velocidad a 120 m de altura | 0.204
Eólica | Distancia a carreteras | 0.014
Solar | Distancia a red eléctrica | 0.399
Solar | Cobertura | 0.080
Solar | Tenencia de la tierra | 0.080
Biomasa | Residuos urbanos | 0.060
Biomasa | Distancia a granjas porcícolas | 0.024
Biomasa | Residuos vegetales | 0.005

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por entrega de metadatos favor de hacer las siguientes correcciones a las tablas de insumos:

- [ ] 1.2.2.1 Distancia del gasoducto a zonas industriales - Hidrocarburos líquidos 

Capa | Distancia del gasoducto a los parques   industriales
-- | --
Fuente | [1] Parques industriales Ayuntamiento de Mérida con datos del PMDU; [2]   Gasoductos GeoComunes con datos de CRE, SEMARNAT, ASEA y CFE
Año | [1] 2017; [2] 2020
Escala | [1] 1:65,000; [2] Sin dato
Unidades | Kilómetros

**Comment by Nayita** [comment]
Diagrama de energías renovables

![energia_renovable](https://user-images.githubusercontent.com/25210323/120362636-e374c980-c2d0-11eb-9b43-5b9027841658.png)

**Comment by paola-gp** [comment]
### Últimas observaciones

- [ ] Eliminar lo industrial del nombre de Energía 
- [ ] Agregar la leyenda como introducción de la sección 1: 

Si bien durante los talleres se evaluó la aptitud de cinco tipos de fuentes que incluyen hidrocarburos líquidos, gas natural, solar, eólica y biomasa, con base en los Art. 37 y 38 del Reglamento de la Ley General del Equilibrio Ecológico y la Protección al Ambiente en Materia de Ordenamiento Ecológico el mapa de aptitud que se utilizará como insumo para la actualización del POETY es el de energías renovables que se muestra en la sección 2. 

- [ ] Integrar una versión completa del sector Energías renovables y solo dejar leyenda de la sección 2 y ponerla como introducción.

**Comment by vichdzgeo** [comment]
## Aviso

Durante el proceso de revisión de capas de WMS se detecto un error en la función de valor de velocidad del viento.
Ver figura

![image](https://user-images.githubusercontent.com/38017509/156077165-6b530207-d9b9-499a-893a-11fc4946c7d6.png)

**Comment by Nayita** [comment]
### AVISO

Durante el proceso de revisión de capas de WMS se detectó un error en el mapa de la función de valor de tenencia de energía solar.

Ver figura

Mapa del informe

![image](https://user-images.githubusercontent.com/25210323/157958518-6666b9b7-d8de-4bca-8481-2c2c3a885ce9.png)

Problema: Presenta la coloración de la peor condición que es igual a 0.
Sin embargo, los parámetros de la función de valor son los siguientes:

ID | Categoria | FV
-- | -- | --
3 | No ejidal | 1.00
2 | Zona de tierras parceladas | 0.52
1 | Tierra de uso común | 0.19

La importancia más baja es 0.19 como está en el mapa que se utilizó para hacer el mapa de actitud. Por lo que se concluye que al modificarse la capa, la imagen del mapa no fue actualizada en el informe.

Mapa actualizado en el WMS y que fue utilizado en el mapa de aptitud.

![image](https://user-images.githubusercontent.com/25210323/157958942-93c40de3-a9b5-4837-8bb0-a9c821a6f23b.png)

Este mapa ya fue actualizado en el informe en línea.

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
