### ISSUE TITLE
 Integrar informe del análisis de aptitud del sector agricultura tecnificada #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#74]
### [TALLER AGRICULTURA TECNIFICADA](https://lancis-apc.github.io/fomix/agricultura_pr.html)

- Ubicación de insumos para informe: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\agricultura

- Ubicación de productos del taller: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\agricultura

**Comment by CorinaCantero** [comment]
### POSIBLES INSUMOS GEOGRÁFICOS PARA EL TALLER

- [ ] Modelo digital de terreno --- elevación
- [ ] Uso de suelo y vegetación
- [ ] Edafología
- [ ] Precipitación (puede ser promedio, mínima o máxima?)

CONAGUA https://smn.conagua.gob.mx/es/climatologia/informacion-climatologica/mapas-de-climatologia-1981-2010

- [ ] Agua – pozos / nivel piezométrico acuíferos
- [ ] agua calidad - la del artículo de Batllori (voy a insistir en conseguirla esta semana)

- [ ] Infraestructura de riego
- [ ] Unidades de riego CONAGUA
- [ ] Distrito de riego Ticul CONAGUA http://sina.conagua.gob.mx/sina/tema.php?tema=distritosriego&ver=mapa&o=1&n=nacional
- [ ] Almacenes localidades con almacenes SIAP_ infraestructura del sector Agroalimentario SADER https://cmgs.gob.mx:31/infraestructuras/
- [ ] Localidades
- [ ] Carreteras y vialidades
- [ ] Líneas eléctricas

**Comment by CorinaCantero** [comment]
### DEFINICIONES
@dpedroza74 @TatianaMerino 

**Unidades de riego:** Las unidades de riego son áreas agrícolas con infraestructura y sistemas de riego distintas de los distritos de riego y por lo general de menos superficie. Pueden integrarse por asociaciones de usuarios u otras figuras de productores organizados, que se asocian entre sí para prestar el servicio de riego con sistemas de gestión autónoma y operar las obras de infraestructura hidráulica para la captación, derivación, conducción, regulación y distribución y desalojo de las aguas nacionales destinadas al riego agrícola.

**Distrito de riego:** es establecido mediante Decreto Presidencial, está conformado por una o varias superficies previamente delimitadas y dentro de cuyo perímetro se ubica la zona de riego, el cual cuenta con las obras de infraestructura hidráulica, aguas superficiales y del subsuelo, así como con sus vasos de almacenamiento, su zona federal, de protección y demás bienes y obras conexas, pudiendo establecerse también con una o varias unidades de riego (L.A.N).

**Comment by TatianaMerino** [comment]
@Nayita 
Listas las primeras definiciones de agricultura. 
Se planteó dividir en Agricultura de riego y Agricultura de temporal 

Modelo multicriterio: 
agr_riego_11feb2021.sdmod

@vichdzgeo @CorinaCantero 
La tabla de prefijos de agricultura de riego ya se comenzó con las ponderaciones de los criterios (nivel 1).

**Comment by Nayita** [comment]
### Modelo de decisión

@dpedroza74 @TatianaMerino 

![a_riego](https://user-images.githubusercontent.com/25210323/107810035-a391d280-6d31-11eb-93a7-175a09dd4ce0.png)

**Comment by CorinaCantero** [comment]
## SIG- Preparación de insumos geográficos
@vichdzgeo 

### Infraestructura

- [ ] Vías de comunicación ----> Distancia a la red vial INEGI (d_carreteras_caminos)
- [ ] Hidroagrícola (categórica) ------>  insumo: 
- [ ] Energía------> Distancia a líneas eléctricas INEGI (

### Biofísicos

- [ ] Tipo de cobertura ------> USV SVI INEGI 16 cats
- [ ] Tipo de suelo --------> Edafología INEGI
- [ ] Pendiente ------->
- [ ] Disponibilidad de agua
_Opción 1._ Nivel freático POETY
_Opción 2._ Pozos de agua REPDA
- [ ] Precipitación ------> Precipitación anual en México (1910-2009)

### Socioeconómicos

- [ ] Distancia a mercados ----->
- [ ] Disponibilidad de mano de obra ------>
- [ ] Tenencia -------> RAN 2020

**Comment by CorinaCantero** [comment]
### TABLAS INSUMOS AGRICULTURA DE RIEGO
@Nayita 

### **Infraestructura**

**Vías de comunicación**

Capa | Distancia a la red vial
-- | --
Fuente | Red Nacional de Caminos (RNC) Red vial - INEGI
Año | 2019
Escala | Sin dato
Unidades | Kilómetros

**Hidroagrícola**

Capa | Unidades y distritos de riego
-- | --
Fuente | [1] Datos vectoriales de los distritos de riego a nivel nacional CONAGUA   y [2] Unidades de riego agrupadas por Región Hidrológico-Administrativa   CONAGUA
Año | [1] 2018-2019; [2] 2017-2018
Escala | [1] 1:250,000; [2] Sin dato
Unidades | Adimensional

**Energía** 

Capa | Distancia líneas de transmisión de energía   eléctrica
-- | --
Fuente | Líneas de transmisión INEGI
Año | 2012
Escala | 1:50,000
Unidades | Kilómetros

### Biofísicos

**Cobertura**

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

**Edafología**


Capa | Edafología
-- | --
Fuente | Conjunto de datos vectoriales edafológico. Serie II (Continuo Nacional)   INEGI
Año | 2014
Campo | tipo_suelo
Escala | 1:250,000
Unidades | Adimensional

**Pendiente**

Capa | Pendiente
-- | --
Fuente | Adaptado de: Continuo de Elevaciones Mexicano (CEM) INEGI
Año | 2013
Resolución | 15 m x 15 m
Unidades | Grados

**Disponibilidad de agua**

Capa | Nivel freático
-- | --
Fuente | Nivel freático POETY
Año | Sin dato
Campo | n_freat_m
Escala | Estatal
Unidades | Metros


Capa | Distancia a pozos
-- | --
Fuente | Registro Público de Derechos de Agua (REPDA) CONAGUA
Año | 2018
Escala | Sin dato
Unidades | Kilómetros

**Precipitación** 

Capa | Precipitación
-- | --
Fuente | Adaptado de: Precipitación acumulada anual SGM
Año | 1960-2000
Escala | Sin dato
Unidades | mm

**Mano de obra**

Capa | Población económicamente activa en el sector primario
-- | --
Fuente | Adaptado de: [1] Encuesta Intercensal INEGI y [2] División política municipal INEGI
Año | [1] 2015; [2] 2018
Campo | [1] Sector de actividad económica primario
Escala | [2] 1:250,000
Unidades | Porcentaje

**Tenencia**

Capa | Tenencia de la tierra
-- | --
Fuente | [1] Zonas de Tierras Parceladas RAN y [2] Tierra de uso común RAN
Año | 2020
Escala | Sin dato
Unidades | Adimensional

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe

**Comment by TatianaMerino** [comment]
## Actualización de insumos
@Nayita 

## Pesos
Modelo: agr_riego_16feb2021_v3.sdmod

## Definiciones

**Infraestructura**

Criterio|Definición
-- | -- |
Hidroagrícola | Distrito de riego y unidades de riego. 
Energía | Distancia a red de transmisión eléctrica. 
Vías de comunicación | Distancia a caminos, brechas y carreteras para el   transporte de insumos y productos. 

**Biofísicos**

Criterio|Definición|
 -- | -- |
Disponibilidad de agua | Posibilidad de extraer agua subterránea considerando el nivel piezométrico. 
Pendiente| Elevación del terreno. 
Tipo de suelo | Edafología.
Tipo de cobertura | Tipos de vegetación y usos de suelo. 

**Socioeconómicos**

Criterio|Definición|
-- | -- |
Mercados | Distancia a las localidades en las que se ubican centros de almacenamiento y centrales de abasto.
Mano de obra | Distancia a   localidades/municipios  donde existe un   mayor porcentaje de población económicamente activa ocupada en el sector primario. 
Tenencia | Tenencia de la tierra.

**Comment by TatianaMerino** [comment]
@vichdzgeo @CorinaCantero 
Listas las funciones de valor (a excepción de mercados) y el machote de agricultura de riego.

**Comment by TatianaMerino** [comment]
## Funciones de valor categóricas de Agricultura de riego
@Nayita 
### Infraestructura

**Hidroagrícola**

ID | Categoría | Importancia | FV
-- | -- | -- | --
1 | Distrito de riego | Muy alta | 1.00
2 | Unidad de riego | Muy alta | 1.00
3 | NA | Nula | 0.00

### Biofísicos

**Tipo de suelo**

ID | Categoría | Importancia | FV
-- | -- | -- | --
7 | Luvisol | Muy alta | 1.00
8 | Nitosol | Muy alta | 1.00
2 | Cambisol | Alta | 0.75
3 | Chernozem | Alta | 0.75
5 | Histosol | Alta | 0.75
4 | Gleysol | Moderada | 0.50
9 | Phaeozem | Moderada | 0.50
12 | Vertisol | Moderada | 0.50
1 | Arenosol | Baja | 0.25
6 | Leptosol | Baja | 0.25
10 | Regosol | Baja | 0.25
11 | Solonchak | Nula | 0.00
13 | No aplica | Nula | 0.00

**Tipo de cobertura**

ID | Categoría | Importancia | FV
-- | -- | -- | --
2 | Agricultura de riego | Muy alta | 1.00
3 | Agricultura de temporal | Alta | 0.75
8 | Pastizal | Moderada | 0.50
9 | Selva baja | Moderada | 0.50
10 | Selva mediana | Baja | 0.25
11 | Sin vegetación | Baja | 0.25
12 | Sábana | Baja | 0.25
1 | Acuícola | Nula | 0.00
4 | Asentamiento humano | Nula | 0.00
5 | Bosque cultivado/Palmar inducido | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
7 | Manglar | Nula | 0.00
13 | Tular | Nula | 0.00
14 | Vegetación de duna costera | Nula | 0.00
15 | Vegetación de petén | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

### Socioeconómicos

**Tenencia**

ID | Categoría | Importancia | FV
-- | -- | -- | --
1 | Tierra de uso común | Baja | 0.25
2 | Zona de tierras parceladas | Alta | 0.75
3 | No ejidal | Muy alta | 1.00

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Listas gráficas y mapas de criterios evaluados hasta el momento para agricultura de riego.

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe

@vichdzgeo 

- [ ] Favor de publicar

**Comment by TatianaMerino** [comment]
# Agricultura tecnificada de temporal 
@Nayita 
(Favor de poner "Agricultura tecnificada de riego" en el informe correspondiente a agricultura de riego)

## Modelo 
agr_temp_18feb2021_v2.sdmod

## Funciones de valor categóricas de Agricultura de temporal
### Biofísicos

**Precipitación**

ID | Categoría | Importancia | FV
-- | -- | -- | --
5 | e) 1081-1233 mm | Muy alta | 1.00
4 | d) 930-1081 mm | Alta | 0.75
3 | c) 778-930 mm | Moderada | 0.50
1 | a) 551-626 mm | Baja | 0.25
2 | b) 626-778 mm | Baja | 0.25

**Tipo de suelo**

ID | Categoría | Importancia | FV
-- | -- | -- | --
7 | Luvisol | Muy alta | 1.00
8 | Nitosol | Muy alta | 1.00
2 | Cambisol | Alta | 0.75
3 | Chernozem | Alta | 0.75
5 | Histosol | Alta | 0.75
4 | Gleysol | Moderada | 0.50
9 | Phaeozem | Moderada | 0.50
12 | Vertisol | Moderada | 0.50
1 | Arenosol | Baja | 0.25
6 | Leptosol | Baja | 0.25
10 | Regosol | Baja | 0.25
11 | Solonchak | Nula | 0.00
13 | No aplica | Nula | 0.00

**Tipo de cobertura**

ID | Categoría | Importancia | FV
-- | -- | -- | --
3 | Agricultura de temporal | Muy alta | 1.00
2 | Agricultura de riego | Alta | 0.75
8 | Pastizal | Moderada | 0.50
9 | Selva baja | Moderada | 0.50
10 | Selva mediana | Moderada | 0.50
11 | Sin vegetación | Baja | 0.25
12 | Sábana | Baja | 0.25
1 | Acuícola | Nula | 0.00
4 | Asentamiento humano | Nula | 0.00
5 | Bosque cultivado/Palmar inducido | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
7 | Manglar | Nula | 0.00
13 | Tular | Nula | 0.00
14 | Vegetación de duna costera | Nula | 0.00
15 | Vegetación de petén | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

### Socioeconómicos

**Tenencia**

ID | Categoría | Importancia | FV
-- | -- | -- | --
3 | No ejidal | Muy alta | 1.00
2 | Zona de tierras parceladas | Alta | 0.75
1 | Tierra de uso común | Baja | 0.25

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de agregar las siguientes  gráficas al informe:

- [ ] fi_fv_agrie_socio_merca_almacen_central_abasto_agricola
- [ ] fi_fv_agtem_socio_merca_almacen_central_abasto_agricola
- [ ] fi_fv_agtem_infra_com_d_carreteras_caminos
- [ ] fi_fv_agtem_bio_pend_pendiente_grados
- [ ] fi_fv_agtem_infra_ene_gasolina
- [ ] fi_fv_agtem_socio_pea_pea_sector_primario

**Comment by TatianaMerino** [comment]
# Definiciones de Agricultura tecnificada de riego 
- [ ] @dpedroza74 favor de agregar definición de Agricultura tecnificada de riego

Tipo | Definición
-- | --
Agricultura tecnificada de riego |  


**Infraestructura**

Criterio | Definición
-- | --
Hidroagrícola | Distrito de riego y unidades de riego.
Energía | Distancia a red de transmisión eléctrica.
Vías de comunicación | Distancia a caminos, brechas y carreteras para el transporte de insumos y productos.

**Biofísicos**

Criterio | Definición
-- | --
Disponibilidad de agua | Posibilidad de extraer agua subterránea, considerando el nivel   piezométrico.
Pendiente | Elevación del terreno.
Tipo de suelo | Edafología.
Tipo de cobertura | Tipos de vegetación y usos de suelo.

**Socioeconómicos**

Criterio | Definición
-- | --
Mercados | Distancia a las principales localidades en las que se venden los   productos agrícolas.
Mano de obra | Distancia a localidades/municipios    donde existe un mayor porcentaje de población económicamente activa   ocupada en el sector primario.
Tenencia | Tenencia de la tierra.

**Comment by CorinaCantero** [comment]
### TABLAS DE INSUMOS - Agricultura de temporal
@Nayita 

### **Infraestructura**

- [ ] **Gasolina**


- [ ] **Vías de comunicación**

Capa | Distancia a la red vial
-- | --
Fuente | Red Nacional de Caminos (RNC) Red vial - INEGI
Año | 2019
Escala | Sin dato
Unidades | Kilómetros

### **Biofísicos**

- [ ] **Precipitación**

Capa | Precipitación
-- | --
Fuente | Adaptado de: Precipitación acumulada anual SGM
Año | 1960-2000
Escala | Sin dato
Unidades | mm

- [ ] **Pendiente**

Capa | Pendiente
-- | --
Fuente | Adaptado de: Continuo de Elevaciones Mexicano (CEM) INEGI
Año | 2013
Resolución | 15 m x 15 m
Unidades | Grados

- [ ] **Cobertura**

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

- [ ] **Tipo de suelo**

Capa | Edafología
-- | --
Fuente | Conjunto de datos vectoriales edafológico. Serie II (Continuo Nacional)   INEGI
Año | 2014
Campo | tipo_suelo
Escala | 1:250,000
Unidades | Adimensional

### **Socioeconómicos**

- [ ] **Personal**

- [ ] **Mercados**

- [ ] **Tenencia**

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

- [ ] Por favor corregir la tabla de insumos para agricultura de riego y agricultura de temporal para el criterio distancia a mercados, con la siguiente información:

Capa | Distancia a localidades con centrales de   abasto y almacenes agrícolas
-- | --
Fuente | Adaptado de: [1] Polígonos de localidades. Marco Geoestadístico. Censo de   Población y Vivienda INEGI y [2] Infraestructura del Sector Agroalimentario   almacenes y centrales de abasto SIAP
Año | [1] 2020; [2] Sin dato
Escala | Localidad
Unidades | Kilómetros

**Comment by dpedroza74** [comment]
@Nayita 
Favor de corregir definición en agricultura tecnificada de riego

1.2.3.2 Mano de obra
Municipios con mayor porcentaje de población económicamente activa ocupada en el sector primario.

**Comment by vichdzgeo** [comment]
## Mapas de aptitud
Ruta: talleres\sectores\agricultura\aptitud

- agrie_agricultura_riego.tif
- agrie_agricultura_temporal.tif

#Mapas de exclusión 
**insumos:**

1. categorías clasificadas con importancia *Nula* en el atributo de cobertura excepto la categoría *asentamiento humano*
2. Polígonos de todas las localidades, tanto urbanas como rurales. 

- agrie_agricultura_riego_exclusion.tif
- agrie_agricultura_temporal_exclusion.tif

## Áreas por categorías de aptitud para agricultura de riego 


Categoría | Km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 502.5 | 1
Alta | 19395.3 | 49
Moderada | 14850.5 | 38
Baja | 1785.1 | 5
Muy baja | 297.2 | 1
Nula | 2594.7 | 7

## Áreas por categorías de aptitud para agricultura de temporal
Categoría | Km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 6373.8 | 16
Alta | 17818.7 | 45
Moderada | 12031.5 | 31
Baja | 605.7 | 2
Muy baja | 0.9 | 0
Nula | 2594.7 | 7

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Favor de agregar lo siguiente al informe:

- [ ] mapa_agrie_aptitud
- [ ] mapa_agtem_aptitud
- [ ] mapa_agtem_exclusion
- [ ] mapa_agrie_exclusion

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

**Comment by Nayita** [comment]
### AVISO

Falta los siguientes insumos para terminar el informe:

- [ ] Tablas de pesos globales @TatianaMerino 
- [ ]  Figuras de sensibilidad @vichdzgeo 
- [ ]  Lista de asistencia @ofegarcia @Nayita

**Comment by CorinaCantero** [comment]
### **TABLA PESOS GLOBALES**
@Nayita 

- [ ] Agricultura de riego 

Criterio | Peso
-- | --
Hidroagrícola | 0.270
Energía | 0.252
Disponibilidad de agua | 0.171
Vías de comunicación | 0.078
Pendiente | 0.066
Mano de obra | 0.043
Mercados | 0.043
Tipo de suelo | 0.042
Tipo de cobertura | 0.021
Tenencia | 0.014

- [ ] Agricultura de temporal 

Criterio | Peso
-- | --
Precipitación | 0.314
Tipo de suelo | 0.207
Pendiente | 0.150
Vías de comunicación | 0.108
Mano de obra | 0.061
Mercados | 0.061
Tipo de cobertura | 0.043
Combustible | 0.036
Tenencia | 0.020

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@TatianaMerino @dpedroza74 

- [ ] Falta la meta

**Comment by dpedroza74** [comment]
- Fomentar la producción incorporando tecnologías, insumos, equipos y maquinaria avanzada, optimizando al máximo los procesos de manera eficiente y amigable con el medio ambiente, que permitan un mayor rendimiento por unidad de superficie.
- Aumentar en las zonas sur y oriente la producción tecnificada de pasto, maíz amarillo, sorgo y soya para cubrir la demanda del sector ganadero y reducir importaciones.
- •	Incrementar rendimientos, a través de la recuperación de áreas agrícolas degradadas o abandonadas, mediante la agricultura de conservación (rotación de cultivos, manejo de rastrojo y cero labranza) y la restauración de suelos (uso de coberturas vegetales).
- Diversificar tecnologías apropiadas para las condiciones del suelo y productos para promover la competitividad, la integración de pequeños productores y mujeres y la coexistencia con otros sistemas de producción como la milpa maya.
- Reducir el impacto sobre los ecosistemas naturales.
-

**Comment by Nayita** [comment]
### AVISO

Informe concluido.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita

Por favor hacer las siguientes modificaciones en la parte de exclusión para agricultura de riego y agricultura de temporal:

- [ ] Agregar los números entre corchetes y el enunciado después del número [2]
- [ ] Cambiar la tabla de exclusión por la siguiente:

[1]

ID | Categoría
-- | --
1 | Acuícola
5 | Bosque cultivado/Palmar inducido
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

[2] Se utilizaron todas las localidades (urbanas y rurales)

Otras correcciones: 
- [ ]  En la tabla de insumos de la sección 2.2.1.1 poner en Año 2013, ya que este se refiere al año de publicación.

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@vichdzgeo 

- [ ]  Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Se corrigió la tabla de exclusión (ID, Categoría) del comentario AVISO: MAPAS DE APTITUD Y TABLAS DE EXCLUSIÓN para agregar la categoría ND (le quité la palomita)

**Comment by Nayita** [comment]
### AVISO

Lista la actualización del informe

**Comment by paola-gp** [comment]
@CorinaCantero 

- [ ] Se actualiza capa de cobertura de ambas agriculturas, subir capa actualizada a SIGfunctionD

**Comment by CorinaCantero** [comment]
### **AVISO**
@vichdzgeo 

Listas las capas evaluadas y exportadas de cobertura (corregida con capa de manglares) para agricultura de riego y agricultura de temporal 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\agricultura\funciones_valor
- fv_agtem_bio_cober_cobertura_usv_svi_16cats_costa_manglar
- fv_agrie_bio_cober_cobertura_usv_svi_16cats_costa_manglar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor hacer actualizar las siguientes tablas de insumos en el informe: 

- [ ] Cobertura para agricultura de riego y de temporal

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Exclusión de agricultura de riego y de temporal


Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo   de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000;[2] 1:50,000; [3] Sin dato
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Actualizaciones

Listas las actualizaciones para este sector

- [ ] Actualizar las figuras de mapas de aptitud @CorinaCantero 
- [ ] Actualizar las figuras de mapas de exclusión @CorinaCantero 
- [ ] Actualizar las tablas de categorías de aptitud en sphinx @Nayita

**Comment by vichdzgeo** [comment]
## Integración de los mapas de aptitud



### Insumos
- capa de aptitud de agricultura de riego (capa resultante de la clp y normalizada. resultado de sigindex)
- capa de aptitud de agricultura de temporal (capa resultante de la clp y normalizada. resultado de sigindex)
- capa de exclusión para agricultura de riego
- capa de exclusión para agricultura de temporal 

### Procedimiento

- se integran las capas mediante clp con pesos iguales (0.5,0.5). el resultado se normaliza
- se genera la capa de exclusión para la capa integrada,  la exclusión integrada solo es válida si existe concurrencia espacial, es decir, es necesario que exista exclusión en todas las capas para que sea válida.
- se aplica la capa de exclusión integrada al la de aptitud  integrado, si hay exclusión la capa resultante tendra valor de 0, en caso de que no exista exclusión, el valor es el de la capa de  aptitud integrada.

### Productos 

- agricultura_integrado.tif (capa normalizada entre 0 y 1 con exclusión con valor en 0)
- agricultura.tif (capa categorizada de la capa integrada que representa las categorías de aptitud, Nula =0, Muy baja = 1 ... Muy alta = 5)

**Comment by vichdzgeo** [comment]
## Área por categoria de aptitud del mapa integrado de Agricultura 


Categoría | km² | Porcentaje del estado
-- | --: | --:
Muy alta | 1461.4 | 4
Alta | 23470.1 | 59
Moderada | 11295.6 | 29
Baja | 431.5 | 1
Muy baja | 1.8 | 0
Nula | 2876.3 | 7

Ruta de los mapas : FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\agricultura\aptitud

agricultura.tif (capa categorizada) 
agricultura_exclusion.tif(capa de exclusión)

- [ ] Generar figuras de mapa de aptitud integrado, exclusion de agricultura @CorinaCantero 
- [ ] Integrar la tabla de áreas a sphinx @Nayita 
- [ ]

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Listos mapas integrados para el informe: 

- [ ]  Mapa integrado aptitud -----> mapa_agricultura_aptitud
- [ ] Mapa integrado exclusión ------> mapa_agricultura_exclusion

**Comment by CorinaCantero** [comment]
### TABLA PESOS GLOBALES DEL MAPA DE APTITUD INTEGRADO 
@Nayita 

- [ ] Favor de agregar al informe

Criterio | Peso
-- | --
Hidroagrícola - Riego | 0.135
Energía - Riego | 0.126
Disponibilidad de agua - Riego | 0.086
Vías de comunicación - Riego | 0.039
Pendiente - Riego | 0.033
Mano de obra - Riego | 0.022
Mercados - Riego | 0.022
Tipo de suelo - Riego | 0.021
Tipo de cobertura - Riego | 0.011
Tenencia - Riego | 0.007
Precipitación - Temporal | 0.157
Tipo de suelo - Temporal | 0.103
Pendiente - Temporal | 0.075
Vías de comunicación -Temporal | 0.054
Mano de obra - Temporal | 0.031
Mercados - Temporal | 0.031
Tipo de cobertura - Temporal | 0.021
Combustible -Temporal | 0.018
Tenencia - Temporal | 0.010

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Por entrega de metadatos, favor de hacer las siguientes actualizaciones a las tablas de insumos: 

- [ ] Disponibilidad de agua - Agricultura tecnificada de riego 

Capa | Nivel freático
-- | --
Fuente | Nivel freático POETY
Año | 2007
Campo | n_freat_m
Escala | Estatal
Unidades | Metros

**Comment by Nayita** [comment]
**Diagrama de modelo de decisión del mapa de aptitud integrado**

![agricultura_integrado](https://user-images.githubusercontent.com/25210323/120397982-f1414380-c2fe-11eb-9449-c823e145b2fe.png)

**Comment by CorinaCantero** [comment]
**AVISO**
@Nayita 

Favor de agregar lo siguiente al informe:

Mapa integrado de agricultura tecnificada ---> Exclusión

- [ ] Tabla de insumos: 

Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y vegetación de la zona costera asociada a los manglares, Región Península de Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000;[2] 1:50,000; [3] Sin dato
Unidades | Adimensional

- [ ] Tabla ID/categoría

[1] y [2] 

ID | Categoría
-- | --
1 | Acuícola
5 | Bosque cultivado/Palmar inducido
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila
17 | ND

[3] Se utilizaron todas las localidades (urbanas y rurales).

**Comment by TatianaMerino** [comment]
@Nayita favor de hacer las siguientes correcciones: 

## INFORME DE AGRICULTURA DE RIEGO 

1.2.3.3 Tenencia

Parámetros de la función de valor

ID | Categoría | Importancia | FV
-- | -- | -- | --
3 | No ejidal | Muy alta | 1.00
2 | Zona de tierras parceladas | Alta | 0.75
1 | Tierra de uso común | Baja | 0.25


## INFORME AGRICULTURA DE TEMPORAL

2.2.1.1 Precipitación

Parámetros de la función de valor

ID | Categoría (mm)| Importancia |FV
-- | -- | -- | --
5 | 1081-1233| Muy alta | 1.00
4 | 930-1081| Alta | 0.75
3 | 778-930 | Moderada | 0.50
2 | 626-778 | Baja | 0.25
1 | 551-626 | Baja | 0.25

**Comment by Nayita** [comment]
### AVISO

Durante el proceso de revisión de capas de WMS se detectó un error en el mapa de la función de valor de tenencia de agricultura de riego.

Ver figura

Mapa del informe

![image](https://user-images.githubusercontent.com/25210323/157743621-87c36c89-1035-4962-b94e-e6e72c37a2cd.png)

Problema: Presenta la coloración de la peor condición que es igual a 0.
Sin embargo, los parámetros de la función de valor son los siguientes:

ID | Categoría | Importancia | FV
-- | -- | -- | --
3 | No ejidal | Muy alta | 1.00
2 | Zona de tierras parceladas | Alta | 0.75
1 | Tierra de uso común | Baja | 0.25

La importancia más baja es 0.25 como está en el mapa que se utilizó para hacer el mapa de actitud. Por lo que se concluye que al modificarse la capa, la imagen del mapa no fue actualizada en el informe.

Mapa actualizado en el WMS y que fue utilizado en el mapa de aptitud.

![image](https://user-images.githubusercontent.com/25210323/157743045-829eaa7d-f58b-4044-ba4f-e06d6f7d58b4.png)

Este mapa ya fue actualizado en el informe en línea.

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
