### ISSUE TITLE
Integrar informe del análisis de aptitud del sector milpa maya y apicultura #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#75]
### [TALLER DE APTITUD MILPA MAYA Y APICULTURA](https://lancis-apc.github.io/fomix/milpa_apic_pr.html)

**Ubicación de insumos para el informe:** FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\milpa_apic

**Ubicación de productos del taller:**
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\milpa_apic

**Comment by paola-gp** [comment]
### Lista (preliminar) de atributos ambientales para milpa maya y apicultura

@CorinaCantero 
- [ ] Precipitación (promedio y mínima promedio)
- [ ] Suelo (edafología)
- [ ] Cobertura (uso de suelo y vegetación) 16 categorías
- [ ] Tenencia de la tierra (3 categorías)
- [ ] Población indígena (%)
- [ ] Disponibilidad del agua (nivel piezométrico)

**Comment by ofegarcia** [comment]
@Nayita 
La tabla de definiciones está en la carpeta de fmx_estudio_tecnico_diagnostico_talleres_sphinx_docs_source_recursos_milpa_apic

**Comment by Nayita** [comment]
### AVISO

Para vo. bo

![fi_milpa](https://user-images.githubusercontent.com/25210323/107977234-640cf580-6f80-11eb-9221-93e0002c7bf5.png)

**Comment by CorinaCantero** [comment]
### AVISO
@paola-gp 
[Lizmap agricultura](http://sig.apps.lancis.ecologia.unam.mx/index.php/view/map/?repository=insumosfmx&project=agricultura) para mostrar capas de regionalización apícola y milpera

**Comment by CorinaCantero** [comment]
### TABLAS DE INSUMOS
@Nayita 

### **Biofísicos**
**Cobertura**

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

**Disponibilidad de agua**
**Cenotes y aguadas**
Pendiente
**Precipitación** 
Pendiente
**Profundidad del acuífero**

Capa | Nivel freático
-- | --
Fuente | Nivel freático POETY
Año | Sin dato
Campo | n_freat_m
Escala | Estatal
Unidades | Metros

**Tipo de suelo**

Capa | Edafología
-- | --
Fuente | Conjunto de datos vectoriales edafológico. Serie II (Continuo Nacional)   INEGI
Año | 2014
Campo | tipo_suelo
Escala | 1:250,000
Unidades | Adimensional

### **Socioeconómicos**
**Población milpera y apícola**
Pendiente
**Población indígena**

**Tenencia de la tierra**

Capa | Tenencia de la tierra
-- | --
Fuente | [1] Zonas de Tierras Parceladas RAN y [2] Tierra de uso común RAN
Año | 2020
Escala | Sin dato
Unidades | Adimensional


### **Infraestructura**

**Distancia a caminos**

**Distancia a centros de acopio**

**Comment by paola-gp** [comment]
@CorinaCantero @vichdzgeo 

1. Revisar entrada de la actualización de atributos 
2. Ver áreas de aprovechamientos actual en

http://sig.apps.lancis.ecologia.unam.mx/index.php/view/map/?repository=insumosfmx&project=agricultura&bbox=95244.85974402598,2165557.3439121637,529290.9091292621,2378821.226518567

### Aprovechamiento actual milpa maya
- [ ] Capa milpa_subsistencia

### Aprovechamiento actual apicultura 
- [ ] APIARIOS_2005_PROD_MIEL - tal cual los puntos

**Comment by ofegarcia** [comment]
@Nayita 
Se actualizó la tabla de definiciones para milpa, subsector milpa: tabla_def_mil_mil_17feb21


Tipo | Definición |  
-- | -- | --
Milpa maya y apicultura | Sistema alimentario agroforestal   dinámico, integrado por diversas actividades productivas a pequeña escala   (solar, apicultura, otras actividades en el monte), asociadas a la seguridad   alimentaria por ser principalmente para autoconsumo. Sus principales componentes   son: semillas nativas, agro diversidad, cultivo de temporal, vegetación más o   menos conservada, extensión menor a 1-3 ha. |  
  |   |  
Meta | Definición |  
  | Promover el fortalecimiento del   sistema milpa maya tradicional y de la apicultura del Estado de Yucatán, para   que la producción se realice de manera sustentable, promueva la conservación   de la biodiversidad y del patrimonio biocultural y permita la innovación en   la milpa maya, sin perder su esencia tradicional. |  
  |   |  
Atributos | Definición | Peso
Biofísicos | Atributos asociados a las   propiedades biológicas, físicas del suelo y del ambiente. | 0.635
Sociales | Atributos que describen las   características sociales del territorio. | 0.259
Infraestructura | Atributos asociados a la   distribución de productos y centros de acopio y accesibilidad. | 0.106
  |   |  
Biofísicos |   |  
Atributo | Definición | Peso
Cobertura | Vegetación o uso de suelo actual | 0.467
Tipo de   suelo | Tipo de suelo (Edafología) | 0.407
Disponibilidad   de agua | Fuentes de acceso al agua | 0.125
  |   |  
Infraestructura |   |  
Atributo | Definición |  
Distancia   a caminos | Distancia a caminos principales,   brechas, terracerías |  
Distancia   a centros de acopio | Distancia a poblaciones   principales. Existencia de grupos organizados de mercado. |  
  |   |  
Sociales |   |  
Atributo | Definición |  
Población   indígena | Porcentaje de la población que   habla una lengua indígena en el municipio. |  
Tenencia   de la tierra | Zonas de área común, parcelas y   áreas no ejidales. |  
  |   |  
Disponibilidad   agua |   |  
Atributo | Definición |  
Precipitación | Precipitación promedio de mayo,   junio y julio |  
  |   |  
Caminos |   |  
Carreteras | Distancia a carreteras y   prolongación |  
Veredas | Distancia a caminos y veredas. |  
  |   |  
Centros   de acopio |   |  
Atributo | Definición |  
Distancia   a localidades rurales | Distancia localidades rurales   < 2,500 habitantes. |  
Distancia   a localidades rurales-urbanas | Distancia a localidades   rurales-urbanas => 2500 y <15,000 habitantes. |  
Distancia   a localidades urbanas | Distancia a localidades urbanas   >= 15,000 habitantes. |

**Comment by ofegarcia** [comment]
@Nayita 
Se incluyó en carpeta sphinx la tabla de categorías de cobertura para milpa, subsector milpa



tabla_cat_mil_mil_bio_usv_cobertura_usv_svi_16cats
ID | Categoria | Importancia | FV
-- | -- | -- | --
3 | Agricultura de temporal | Muy alta | 1.00
9 | Selva baja | Muy alta | 1.00
10 | Selva mediana | Muy alta | 1.00
2 | Agricultura de riego | Baja | 0.25
8 | Pastizal | Baja | 0.25
11 | Sin vegetación | Baja | 0.25
1 | Acuícola | Nula | 0.00
4 | Asentamiento humano | Nula | 0.00
5 | Bosque cultivado/Palmar inducido | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
7 | Manglar | Nula | 0.00
12 | Sábana | Nula | 0.00
13 | Tular | Nula | 0.00
14 | Vegetación de duna costera | Nula | 0.00
15 | Vegetación de petén | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe

@vichdzgeo 

- [ ] Favor de publicar

**Comment by ofegarcia** [comment]
@Nayita
Se incluyó en carpeta sphinx la tabla de categorías de suelo para milpa, subsector milpa

tabla_cat_mil_mil_bio_suelo_tipo_suelo


ID | Categoría | Importancia | FV
-- | -- | -- | --
2 | Cambisol | Muy alta | 1.00
3 | Chernozem | Muy alta | 1.00
7 | Luvisol | Muy alta | 1.00
8 | Nitosol | Muy alta | 1.00
9 | Phaeozem | Muy alta | 1.00
6 | Leptosol | Alta | 0.75
12 | Vertisol | Moderada | 0.50
4 | Gleysol | Baja | 0.25
5 | Histosol | Baja | 0.25
10 | Regosol | Baja | 0.25
1 | Arenosol | Nula | 0.00
11 | Solonchak | Nula | 0.00
13 | No aplica | Nula | 0.00

**Comment by ofegarcia** [comment]
@Nayita 
Subsector apícola

Cambios en el modelo, tomando como base el de milpa

Biofísicos
Atributo | Definición
Cobertura | Vegetación o uso de suelo actual
Disponibilidad de agua | Fuentes de acceso al agua


Disponibilidad de agua

Atributo | Definición
-- | --
Precipitación | Precipitación promedio de mayo,   junio y julio
Distancia a asentamientos | Fuentes de suministro de agua


Distancia a asentamientos

Atributo | Definición
-- | --
Rural | Distancia localidades rurales < 2,500 habitantes.
Rural-urbana | Distancia a localidades rurales-urbanas => 2500 y <15,000   habitantes.
Urbano | Distancia a localidades urbanas >= 15,000 habitantes.

**Comment by paola-gp** [comment]
### Revisión y finalización de capas de funciones de valor e integración final
El orden es importante 
- [ ] 1. Actualizar capa de distancia a asentamientos urbanos para apicultura para que sea incluyente @vichdzgeo 
- [ ] 2. Actualizar los nombres de las capas en el archivo de prefijos y las funciones de valor con base en prefijos_sector_mil_v4 para milpa maya y prefijos_api_v2 para apicultura @CorinaCantero 
- [ ] 3. Actualizar y verificar todas las funciones de valor para los dos sectores en SIGplanning @ofegarcia 
- [ ] 4. Integrar mapas de aptitud para informe @vichdzgeo

**Comment by CorinaCantero** [comment]
### TABLAS INSUMOS APICULTURA

### **Biofísicos**

- [ ] **Cobertura**

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

- [ ] **Disponibilidad de agua**

Capa | Precipitación promedio de marzo
-- | --
Fuente | Precipitación mensual, periodo: 2000 (1980-2009) Instituto de Biología,   UNAM
Año | 2019
Resolución | 1000 m x 1000 m
Unidades | Adimensional

### **Sociales**

- [ ] **Tenencia de la tierra**

Capa | Tenencia de la tierra
-- | --
Fuente | [1] Zonas de Tierras Parceladas RAN y [2] Tierra de uso común RAN
Año | 2020
Escala | Sin dato
Unidades | Adimensional

- [ ] **Población indígena**

Capa | Población indígena
-- | --
Fuente | [1] Polígonos de municipios.División política municipal INEGI y [2] Datos   de indicador. Censo de Población y Vivienda INEGI
Año | [1] 2018 y [2] 2020
Campo | [2] POBTOT y P3YM_HLI
Escala | Municipal
Unidades | Porcentaje

### **Infraestructura**

- [ ] **Distancia a caminos**

Capa | Distancia a veredas y caminos
-- | --
Fuente | Red Nacional de Caminos (RNC) Red vial - INEGI
Año | 2019
Campo | TIPO_VIAL
Escala | Sin dato
Unidades | Kilómetros

Capa | Distancia a carreteras y prolongaciones
-- | --
Fuente | Red Nacional de Caminos (RNC) Red vial - INEGI
Año | 2019
Campo | TIPO_VIAL
Escala | Sin dato

- [ ] **Distancia a centros de acopio**

Capa | Distancia a localidades urbanas (mayor o   igual a 15,000 habitantes)
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Campo | [2] POBTOT
Escala | Localidad
Unidades | Kilómetros


Capa | Distancia a localidades rurales (menos de   2,500 habitantes)
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Campo | [2] POBTOT
Escala | Localidad
Unidades | Kilómetros


Capa | Distancia a localidades rurales - urbanas   (entre 2,500 y 15,000 habitantes)
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Campo | [2] POBTOT
Escala | Localidad
Unidades | Kilómetros

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Por favor agregar lo siguiente al informe: 

**Mapas apicultura**
- [ ] mapa_fv_api_soc_indi_porpob_indigena_municipal
- [ ] mapa_fv_api_soc_ejido_tenencia_tierra
- [ ] mapa_fv_api_infra_merc_d_localidades_2500_15k
- [ ] mapa_fv_api_infra_merc_d_localidades_2500
- [ ] mapa_fv_api_infra_merc_d_localidades_15k
- [ ] mapa_fv_api_infra_cam_d_carretera_prolongacion
- [ ] mapa_fv_api_infra_cam_d_caminos_veredas
- [ ] mapa_fv_api_bio_usv_cobertura_usv_svi_16cats
- [ ] mapa_fv_api_bio_agua_precipitacion_marzo

Gráficas apicultura:

- [ ] fi_fv_api_infra_merc_d_localidades_2500
- [ ] fi_fv_api_bio_agua_precipitacion_marzo
- [ ] fi_fv_api_infra_cam_d_carretera_prolongacion
- [ ] fi_fv_api_infra_merc_d_localidades_2500_15k
- [ ] fi_fv_api_infra_cam_d_caminos_veredas

**Comment by ofegarcia** [comment]
@Nayita
Se incluyó en carpeta sphinx la tabla de categorías de cobertura para apicultura

Archivo: tabla_cat_api_bio_usv_cobertura_usv_svi_16cats


ID | Categoría | Importancia | FV
-- | -- | -- | --
3 | Agricultura de temporal | Muy alta | 1.00
9 | Selva baja | Muy alta | 1.00
10 | Selva mediana | Muy alta | 1.00
13 | Tular | Alta | 0.75
5 | Bosque cultivado/Palmar inducido | Moderada | 0.50
12 | Sábana | Moderada | 0.50
14 | Vegetación de duna costera | Moderada | 0.50
15 | Vegetación de petén | Moderada | 0.50
2 | Agricultura de riego | Baja | 0.25
7 | Manglar | Baja | 0.25
8 | Pastizal | Baja | 0.25
11 | Sin vegetación | Baja | 0.25
1 | Acuícola | Nula | 0.00
4 | Asentamiento humano | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

**Comment by ofegarcia** [comment]
@Nayita
Se incluyó en carpeta sphinx la tabla de categorías de tenencia de la tierra para apicultura

Archivo: tabla_cat_api_soc_ejido_tenencia_tierra


ID | Categoría | Importancia | FV
-- | -- | -- | --
1 | Tierra de uso común | Muy alta | 1.00
2 | Zona de tierras parceladas | Moderada | 0.50
3 | No ejidal | Baja | 0.25

**Comment by ofegarcia** [comment]
@Nayita 
### Aviso
**Actualización de definiciones y pesos de Apicultura**
Archivo de definiciones: sphinx/docs/source/recursos/milpa_apic/tabla_def_api_22feb21.csv

Archivo del modelo: sectores/milpa_apic/modelo/milpa_api_18_feb_2021_v3


Atributos | Definición | Peso
-- | -- | --
Biofísicos | Atributos asociados a las   propiedades biológicas, físicas del suelo y del ambiente. | 0.68
Infraestructura | Atributos asociados a la   distribución de productos y centros de acopio y accesibilidad. | 0.24
Sociales | Atributos que describen las   características sociales del territorio. | 0.08

Biofísicos

Atributo | Definición | Peso
-- | -- | --
Cobertura | Vegetación o uso de suelo actual | 0.80
Precipitación | Precipitación de marzo (estiaje) | 0.20


Infraestructura

Atributo | Definición | Peso
-- | -- | --
Distancia   a caminos | Distancia a caminos principales, brechas, terracerías | 0.50
Distancia   a localidades | Distancia a poblaciones principales donde se ubican los centros de   acopio. Existencia de grupos organizados de mercado. | 0.50


Sociales

Atributo | Definición | Peso
-- | -- | --
Tenencia   de la tierra | Zonas de área común, parcelas y áreas no ejidales. | 0.75
Población   indígena | Porcentaje de la población de 3 años y más que habla una lengua indígena   en el municipio. | 0.25


Caminos

Atributo | Definición | Peso
-- | -- | --
Carreteras | Distancia a carreteras y   prolongación | 0.50
Veredas | Distancia a caminos y veredas. | 0.50

Distancia a localidades

Atributo | Definición | Peso
-- | -- | --
Distancia   a localidades rurales | Distancia localidades rurales < 2,500 habitantes. | 0.46
Distancia   a localidades rurales-urbanas | Distancia a localidades rurales-urbanas => 2500 y   <15,000 habitantes. | 0.44
Distancia   a localidades urbanas | Distancia a localidades urbanas >= 15,000 habitantes. | 0.10

**Comment by vichdzgeo** [comment]
## Mapas de aptitud 
Ruta: talleres\sectores\milpa_apic\aptitud

- mil_milpa_maya.tif
- api_apicultura.tif

## Mapas de aprovechamiento actual y exclusión
### Aprovechamiento

- mil_milpa_maya_aprovechamiento_actual.tif
- api_apicultura_aprovechamiento_actual.tif

### Exclusión 
**Insumos**: 
- localidades rurales -urbanas (población entre 2500 y 15000) localidades urbanas (población de 15000 o más) 
- csv de exclusión a partir de ../funciones_valor/tabla_fv_api_bio_usv_cobertura_usv_svi_16cats_exclusion.csv y tabla_fv_mil_bio_usv_cobertura_usv_svi_16cats_exclusion.csv (son los mismos criterios ifentificados con importancia *Nula* de las funciones de cobertura de cada subsector, sin considerar la categoría de *Asentamiento humano*
- mil_milpa_maya_exclusion.tif
- api_apicultura_exclusion.tif

## Áreas por categorías de aptitud para milpa maya


Categoría | Km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 16624.6 | 42
Alta | 12812.6 | 32
Moderada | 6700.0 | 17
Baja | 841.6 | 2
Muy baja | 144.4 | 0
Nula | 2413.4 | 6

## Áreas por categorías de aptitud para apicultura

Categoría | Km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 22439.4 | 57
Alta | 5488.2 | 14
Moderada | 4453.8 | 11
Baja | 5645.0 | 14
Muy baja | 524.2 | 1
Nula | 985.9 | 2

@Nayita @CorinaCantero

**Comment by vichdzgeo** [comment]
## Análisis de sensibilidad
@Nayita  listas las imágenes del análisis de sensibilidad, las imágenes ya se encuentran en la ruta de sphinx correspondiente 

- fi_analisis_sensibilidad_milpa_maya.png
- fi_analisis_sensibilidad_apicultura.png

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Favor de agregar lo siguiente al informe: 

- [ ] mapa_mil_aptitud
- [ ] mapa_api_aptitud
- [ ] mapa_api_aprov_actual
- [ ] mapa_mil_aprov_actual
- [ ] mapa_api_exclusion
- [ ] mapa_mil_exclusion

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

**Comment by ofegarcia** [comment]
@Nayita 

### AVISO
**Se actualizó el modelo del sector milpa.** 
Archivo: milpa_mil_23-feb-2021_v2  

- En el clúster de atributos biofísicos, “disponibilidad de agua” cambia a “precipitación”, con el correspondiente cambio en la definición.
- En el clúster de Infraestructura, el nodo “Distancia a centros de acopio” cambia a “Distancia a localidades rurales”, con el correspondiente cambio en la definición.
- Se eliminan los clústeres: Disponibilidad de agua y Distancia a centros de acopio

**Definiciones y pesos:**
Archivo: tabla_def_mil_25feb21

**Atributos**

Atributos | Definición | Peso
-- | -- | --
Biofísicos | Atributos asociados a las   propiedades biológicas, físicas del suelo y del ambiente. | 0.635
Sociales | Atributos que describen las   características sociales del territorio. | 0.259
Infraestructura | Atributos asociados a la   distribución de productos, disponibilidad de insumos, centros de acopio y   accesibilidad. | 0.106

**Biofísicos**

Atributo | Definición | Peso
-- | -- | --
Cobertura | Vegetación o uso de suelo actual | 0.467
Tipo de   suelo | Tipo de suelo (Edafología) | 0.407
Precipitación | Precipitación promedio de mayo, junio y julio. | 0.125

**Sociales**

Atributo | Definición | Peso
-- | -- | --
Población   indígena | Porcentaje de la población de 3 años y más que habla una lengua indígena   en el municipio. | 0.500
Tenencia   de la tierra | Zonas de área común, parcelas y áreas no ejidales. | 0.500


**Infraestructura**

Atributo | Definición | Peso
-- | -- | --
Distancia   a caminos | Distancia a caminos principales, brechas, terracerías | 0.833
d_localidades   rurales | Distancia a localidades rurales   (<2,500 habitantes) como centros de vivienda, fuentes de acceso a insumos,   a centros de acopio y comercio. | 0.167

**Distancia a caminos**

Atributo | Definición | Peso
-- | -- | --
Veredas | Distancia a caminos y veredas. | 0.834
Carreteras | Distancia a carreteras y   prolongación | 0.166

**Comment by ofegarcia** [comment]
@Nayita

### AVISO
**Se actualizó el modelo del sector apícola.**
Archivo: milpa_api_18-feb-2021_v3

- En el clúster de Infraestructura, el nodo “Distancia a centros de acopio” cambia a “Distancia a localidades”, con el correspondiente cambio en la definición.


**Definiciones que cambian:** 
Archivo: tabla_def_api_25feb21

**Atributos**
Atributos | Definición | Peso
-- | -- | --
Biofísicos | Atributos asociados a las propiedades biológicas y del ambiente. | 0.68
Infraestructura | Atributos asociados al acceso de   insumos, distribución de productos y centros de acopio. | 0.24

**Infraestructura**


Atributo | Definición | Peso
-- | -- | --
Distancia   a localidades | Distancia a poblaciones para el acceso a insumos, recursos, herramientas y centros de acopio. Existencia de grupos organizados de mercado. | 0.5

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe.

- [ ] Falta la tabla de pesos globales y lista de asistencia para concluirlo @ofegarcia @Nayita

**Comment by CorinaCantero** [comment]
### **TABLA DE PESOS GLOBALES**
@Nayita 

- [ ] Apicultura


Criterio | Peso
-- | --
Cobertura | 0.544
Precipitación | 0.136
Tenencia de la tierra | 0.062
Carreteras | 0.059
Veredas | 0.059
Distancia a localidades rurales | 0.055
Distancia a localidades rurales-urbanas | 0.052
Población indígena | 0.021
Distancia a localidades urbanas | 0.012



- [ ] Milpa maya

Criterio | Peso
-- | --
Cobertura | 0.297
Tipo de suelo | 0.258
Tenencia de la tierra | 0.130
Población indígena | 0.130
Precipitación | 0.079
Veredas | 0.073
Distancia a localidades rurales | 0.018
Carreteras | 0.015

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

**Comment by Nayita** [comment]
### AVISO

Informe concluido.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by ofegarcia** [comment]
@Nayita 
### AVISO
### Cambios realizados en sector Milpa

1. Se actualizó la definición de precipitación. Archivo: tabla_def_mil_23feb21

Atributo | Definición
-- | --
Precipitación | Precipitación promedio de los   meses de mayo, junio y julio (meses de inicio de siembra de la milpa).

2. Se incluyó en la carpeta de sphinx la tabla de categorías de tenencia de la tierra. Archivo: tabla_cat_mil_soc_ejido_tenencia


ID | Categoría | Importancia | FV
-- | -- | -- | --
1 | Tierra de uso común | Muy alta | 1.00
2 | Zona de tierras parceladas | Moderada | 0.50
3 | No ejidal | Baja | 0.25

**Comment by ofegarcia** [comment]
@Nayita 
### AVISO

### Cambios realizados en el sector Apícola

Atributo | Definición
-- | --
Precipitación | Precipitación promedio del mes de marzo (temporada de estiaje)



Se actualizó la definición de precipitación. Archivo: tabla_def_api:25feb21

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita

Por favor hacer las siguientes modificaciones en la parte de exclusión para milpa maya: 

- [ ] agregar números entre corchetes y el enunciado después del número [2]
- [ ] poner acento en el encabezado de tabla a **categoría** (el contenido de la tabla no se modificó)

**Tabla de exclusión de milpa maya**

**[1]**

ID | Categoría
-- | --
1 | Acuícola
5 | Bosque cultivado/Palmar inducido
6 | Cuerpo de agua
7 | Manglar
12 | Sabana
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

[2] Se seleccionaron las localidades con 2,500 habitantes o más

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones al informe.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Se corrigieron las tablas de exclusión (ID, Categoría) del comentario AVISO. TABLAS EXCLUSIÓN para agregar la categoría ND (les quité la palomita)

**Comment by Nayita** [comment]
### AVISO

Lista la actualización del informe

**Comment by paola-gp** [comment]
@CorinaCantero 

- [ ] Se actualiza capa de cobertura en milpa maya y apicultura, subir capas actualizadas a SIGfunctionD

**Comment by CorinaCantero** [comment]
### **AVISO**
@paola-gp 

Listas las capas de cobertura (corregida con capa de manglares) para evaluarlas

**Comment by CorinaCantero** [comment]
### **AVISO**
@vichdzgeo

Listas las capas evaluadas y exportadas de cobertura (corregida con capa de manglares) para milpa maya y apicultura
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\milpa_apic\funciones_valor

- fv_api_bio_usv_cobertura_usv_svi_16cats_costa_manglar
- fv_mil_bio_usv_cobertura_usv_svi_16cats_costa_manglar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor hacer las siguientes actualizaciones de las tablas de insumos en el informe:

- [ ] Milpa maya cobertura

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Apicultura cobertura 

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Milpa exclusión

Capa | Uso de suelo y vegetación y localidades con   2,500 habitantes o más
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo   de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000; [3] Sin dato
Unidades | Adimensional

- [ ] Apicultura exclusión

Capa | Uso de suelo y vegetación y localidades con   2,500 habitantes o más
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo   de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000; [3] Sin dato
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Actualizaciones
ya se encuentran corregidas y actualizados los mapas y las tablas de categorías de aptitud para este sector. La capa de aprovechamiento igual no cambia. 

- [ ] Actualizar figuras  mapas de aptitud para milpa maya y apicultura @CorinaCantero 
- [ ] Actualizar figuras mapas de exclusión para milpa maya y apicultura @CorinaCantero 
- [ ] Actualizar tablas de categorías de aptitud en sphinx  @Nayita

**Comment by vichdzgeo** [comment]
## Mapa integrado 
### Productos finales

- apicultura.tif ( mapa categorizado con exclusión  y aprovechamiento actual) (equidistante)
- apicultura_integrado (mapa normailizado, valores entre 0 y 1, con exclusión [valor = 0] y aprovechamiento actual [valor = 1]
- milpa_maya.tif ( mapa categorizado con exclusión  y aprovechamiento actual) (equidistante)
- milpa_maya_integrado.tif (mapa normailizado, valores entre 0 y 1, con exclusión [valor = 0] y aprovechamiento actual [valor = 1]

- [ ] actualizar la tabla de apicultura @Nayita 
- [ ] actualizar la tabla de milpa maya @Nayita 
- [ ] actualizar figuras de mapas de aptitud @CorinaCantero

**Comment by paola-gp** [comment]
@vichdzgeo 

Calcular el área y porcentaje de las zonas de aprovechamiento actual de milpa maya con respecto al área y porcentaje de la aptitud del sector milpa maya. 

Aptitud | km² | Porcentaje del estado | km² de aprovechamiento actual | Porcentaje del aprovechamiento actual
-- | --: | --: | --: | --:
Nula | 2652.6 | 7 | 1.6 | 0
Muy baja | 59.0 | 0 | 0.0 | 0
Baja | 785.3 | 2 | 0.3 | 0
Media | 6678.9 | 17 | 42.2 | 4
Alta | 12993.7 | 33 | 177.3 | 17
Muy alta | 16367.2 | 41 | 829.3 | 79
  | 39536.6 |   | 1050.8 |

**Comment by Nayita** [comment]
### AVISO

Durante el proceso de revisión de capas de WMS se detectó un error en el mapa de la función de valor de cobertura del sector milpa maya.

Ver figura

Mapa del informe

![image](https://user-images.githubusercontent.com/25210323/158438498-cfb1e1af-252a-41a3-b02f-149cecffd548.png)

Problema: Se hizo una actualización de la capa de cobertura vegetal y no se actualizó la imagen del mapa en el informe.

Mapa actualizado en el WMS y que fue utilizado en el mapa de aptitud.

![image](https://user-images.githubusercontent.com/25210323/158439620-bdc859c5-551b-4d29-b661-46c1f9f789a0.png)

Este mapa ya fue actualizado en el informe en línea.

**Comment by Nayita** [comment]
### AVISO

Durante el proceso de revisión de capas de WMS se detectó un error en el mapa de la función de valor de cobertura del sector apicultura.

Ver figura

Mapa del informe

![image](https://user-images.githubusercontent.com/25210323/158441084-f88036e9-9c61-4a2b-9ddb-bf5917ed9fb4.png)

Problema: Se hizo una actualización de la capa de cobertura vegetal y no se actualizó la imagen del mapa en el informe.

Mapa actualizado en el WMS y que fue utilizado en el mapa de aptitud.

![image](https://user-images.githubusercontent.com/25210323/158441217-42a831d4-449f-479e-aa77-e88840afd09d.png)

Este mapa ya fue actualizado en el informe en línea.

**Comment by Nayita** [comment]
AVISO
Durante el proceso de revisión de capas de WMS se detectó una diferencia en el mapa de la función de valor de cobertura del sector apicultura.

Ver figura

Mapa del informe

![image](https://user-images.githubusercontent.com/25210323/162031873-2561b4c8-1296-46e0-8497-ed548cfd63c5.png)

Problema: Se hizo una actualización en la capa de cobertura y no se actualizó la imagen del mapa en el informe.

Mapa actualizado en el WMS y que fue utilizado en el mapa de aptitud.

![mapa_fv_api_bio_usv_cobertura_usv_svi_16cats](https://user-images.githubusercontent.com/25210323/162033224-abd484a1-05d8-43bd-90be-244b25db3405.png)

Este mapa ya fue actualizado en el informe en línea.

**Comment by Nayita** [comment]
### AVISO

Revisar la siguiente capa porque en el proceso de revisión de capas de WMS se detectó un error en el mapa de la función de valor de distancia a localidades urbanas del sector apicultura.

Figura del informe

![image](https://user-images.githubusercontent.com/25210323/163041163-75ae50d7-c4b7-4d5c-afef-03746429c4a8.png)

En el mapa del informe, las zonas urbanas son la peor condición y en la liga aparecen como la mejor.

Figura del wms

![image](https://user-images.githubusercontent.com/25210323/163047020-015cb155-b99e-4d63-9f61-e55e74b32d2c.png)

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
