### ISSUE TITLE
Integrar informe del análisis de aptitud del sector pecuario bovino #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#76]
### [TALLER DE APTITUD SECTOR PECUARIO BOVINO](https://lancis-apc.github.io/fomix/pec_bovino_pr.html) 

- **Ubicación de insumos para el informe:** FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sphinx\docs\source\recursos\pec_bovino

- **Ubicación de productos del taller:** FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\pec_bovino

**Comment by TatianaMerino** [comment]
## Insumos 12 feb 2021
Modelo: bov_12feb2021_v2.sdmod

Definiciones: tabla_def_bov.xlsx

**Biofísicos**
Criterio|Definición|Capa
-- | -- | --
Tipo de cobertura | Tipos de vegetación y usos de suelo. | Conjunto de datos vectoriales de la carta de Uso del   suelo y vegetación. Serie VI. Conjunto Nacional INEGI   2014
Tipo de suelo | Edafología. | Conjunto de datos vectoriales edafológico. Serie II   (Continuo Nacional) INEGI   2014
Disponibilidad de agua | Posibilidad de extraer agua subterránea,   considerando el nivel piezométrico. | Nivel freático POETY
Precipitación | lluvia anual | Lluvia   Acumulada Promedio anual   El mapa de   lluvia anual muestra la distribución del promedio anual de lluvia en el   periodo de 1981 a 2010.   CONAGUA https://smn.conagua.gob.mx/es/climatologia/informacion-climatologica/mapas-de-climatologia-1981-2010           Precipitación   total anual   Adaptado de:   Precipitación total anual García, E. – CONABIO 1998       CONABIO MÁS RECIENTE   1910-2009

**Infraestructura**

Criterio|Definición|Capa
-- | -- | --
Vías de comunicación | Distancia a caminos, brechas y carreteras para el   transporte de insumos y productos. | Red Nacional de Caminos   (RNC) Red vial – INEGI   2019
Centros de acopio | Distancia a localidades con centros de acopio y de   comercialización de ganado (subastas) | Falta la   información de la unión y asociaciones ganaderas
Rastros | Distancia a localidades con rastros o centros de   sacrificio | SIAP de la SADER    Plataforma de Infraestructura del Sector   Agroalimentario    Centros de sacrificio    https://cmgs.gob.mx:31/infraestructuras/       +       DENUE   3116   Matanza, empacado y procesamiento de procesamiento   de ganado   Rastros   https://www.inegi.org.mx/app/mapa/denue/default.aspx
Energía | Distancia a red de transmisión eléctrica. | Líneas de transmisión INEGI   2012

**Comment by Nayita** [comment]
### AVISO

Para vo. bo.

![fi_bovino](https://user-images.githubusercontent.com/25210323/108005528-90dffd80-6fbe-11eb-9344-799a0931482e.png)

**Comment by CorinaCantero** [comment]
## SIG- Preparación de insumos geográficos
@vichdzgeo 

### **Biofísicos**

- [ ] Tipo de cobertura  INEGI 2017
- [ ] Tipo de suelo INEGI 2014
- [ ] Disponibilidad de agua  Nivel freático POETY
- [ ] Precipitación 

### **Infraestructura**

- [ ] Vías de comunicación  INEGI 2019
- [ ] Centros de acopio Distancia a localidades con centros de acopio y de comercialización de ganado (subastas) 
- [ ] Rastros  SIAP de la SADER Plataforma de Infraestructura del Sector Agroalimentario Centros de sacrificio  (Bases de datos rastros: SIG\desarrollo\sig_fomix\insumos\agricultura\siap: centros_sacrificio_pec.csv y centros_tif.csv +   DENUE 3116 Matanza, empacado y procesamiento de procesamiento de ganado Rastros)
- [ ] Distancia a red de transmisión eléctrica. INEGI 2012

**Comment by CorinaCantero** [comment]
## TABLAS DE INSUMOS
@Nayita 

### **Biofísicos**

**Cobertura**

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

**Tipo de suelo**

Capa | Edafología
-- | --
Fuente | Conjunto de datos vectoriales edafológico. Serie II (Continuo Nacional)   INEGI
Año | 2014
Campo | tipo_suelo
Escala | 1:250,000
Unidades | Adimensional

**Disponibilidad de agua**

Capa | Nivel freático
-- | --
Fuente | Nivel freático POETY
Año | Sin dato
Campo | n_freat_m
Escala | Estatal
Unidades | Metros

**Precipitación**

Capa | Precipitación
-- | --
Fuente | Adaptado de: Precipitación acumulada anual SGM
Año | 2013
Escala | Sin dato
Unidades | mm

### Infraestructura

**Vías de comunicación**

Capa | Distancia a la red vial
-- | --
Fuente | Red Nacional de Caminos (RNC) Red vial - INEGI
Año | 2019
Escala | Sin dato
Unidades | Kilómetros

**Centros de acopio**

**Rastros**

Capa | Distancia a rastros, sitios de empacado y   procesamiento de ganado
-- | --
Fuente | [1] Infraestructura del sector Agroalimentario centros de sacrificio y   TIF; [2] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [3] Datos de indicador. Directorio Estadístico Nacional de   Unidades Económicas (DENUE) INEGI
Año | [1] Sin dato; [2] [3] 2020
Escala | Localidad
Unidades | Distancia

**Energía**

Capa | Distancia líneas de transmisión de energía   eléctrica
-- | --
Fuente | Líneas de transmisión INEGI
Año | 2012
Escala | 1:50,000
Unidades | Kilómetros

**Comment by Nayita** [comment]
### AVISO

Listas actualizaciones del informe.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by TatianaMerino** [comment]
# Actualización de insumos 17 febrero 2021

## Modelo 
bov_17feb2021_v2.sdmod

## Capas
@vichdzgeo  @CorinaCantero  

- [ ] Actualizar la capa de Rastros agregando las siguientes localidades: 

- Izamal
- Tzucacab
- Tuncas
- Motul

## Funciones de valor categóricas
@Nayita 

### Biofísicos

**Precipitación**

ID | Categoría | Importancia | FV
-- | -- | -- | --
5 | e) 1081-1233 mm | Muy alta | 1.00
4 | d) 930-1081 mm | Alta | 0.75
3 | c) 778-930 mm | Moderada | 0.50
1 | a) 551-626 mm | Baja | 0.25
2 | b) 626-778 mm | Baja | 0.25

**Tipo de suelo**

ID|Categoría|Importancia|FV
--|--|--|--|
7|Luvisol|Muy alta|1.00
8|Nitosol|Muy alta|1.00
2|Cambisol|Alta|0.75
3|Chernozem|Alta|0.75
5|Histosol|Alta|0.75
12|Vertisol|Alta|0.75
4|Gleysol|Moderada|0.50
6|Leptosol|Moderada|0.50
9|Phaeozem|Moderada|0.50
10|Regosol|Baja|0.25
1|Arenosol|Nula|0.00
11|Solonchak|Nula|0.00
13|No aplica|Nula|0.00

**Cobertura**

ID | Categoría | Importancia | FV
-- | -- | -- | --
2 | Agricultura de riego | Muy alta | 1.00
8 | Pastizal | Muy alta | 1.00
3 | Agricultura de temporal | Alta | 0.75
9 | Selva baja | Alta | 0.75
10 | Selva mediana | Moderada | 0.50
5 | Bosque cultivado/Palmar inducido | Baja | 0.25
11 | Sin vegetación | Baja | 0.25
12 | Sábana | Baja | 0.25
1 | Acuícola | Nula | 0.00
4 | Asentamiento humano | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
7 | Manglar | Nula | 0.00
13 | Tular | Nula | 0.00
14 | Vegetación de duna costera | Nula | 0.00
15 | Vegetación de petén | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Favor de agregar los siguientes mapas al informe

- [ ] mapa_fv_bov_bio_d_manto_freatico
- [ ] mapa_fv_bov_bio_precipitacion
- [ ] mapa_fv_bov_bio_cobertura_usv_svi_16cats
- [ ] mapa_fv_bov_bio_tipo_suelo
- [ ] mapa_fv_bov_infra_d_carreteras_caminos
- [ ] mapa_fv_bov_infra_d_centros_acopio_bov
- [ ] mapa_fv_bov_infra_d_lineas_electricas
- [ ] mapa_fv_bov_infra_d_rastros_bov

**Comment by TatianaMerino** [comment]
## Actualización de definiciones 


Sector | Definición
-- | --
Pecuario bovino |  

**Meta**  
-- |
 Aumentar la capacidad de producción bovina a largo plazo,   minimizando el crecimiento de la superficie destinada a esta actividad y   haciendo más eficiente el uso del área actual.
 Incrementar sustentablemente la eficiencia y resiliencia de la   actividad, a través de la restauración de paisajes y la protección de la   biodiversidad, así como la implementación de innovaciones en el sistema de   producción.
 Mantener y restaurar la fertilidad de suelo para obtener suficiente   cantidad de biomasa que permita hacer más eficiente la actividad para que la   producción por superficie sea rentable en el largo plazo, así como la   diversificación de la actividad a sistemas agroforestales u otras   actividades.

**Biofísicos**

Criterio | Definición
-- | --
Disponibilidad de agua | Posibilidad de extraer agua subterránea, considerando el nivel   piezométrico.
Precipitación | Lluvia anual promedio.
Tipo de suelo | Edafología.
Tipo de cobertura | Tipos de vegetación y usos de suelo.

**Infraestructura**

Criterio | Definición
-- | --
Energía | Distancia a red de transmisión eléctrica.
Vías de comunicación | Distancia a caminos, brechas y carreteras para el transporte de insumos y   productos.
Centros de acopio | Distancia a localidades con centros de acopio y de comercialización de   ganado (subastas).
Rastros | Distancia a localidades con rastros o centros de sacrificio.

**Comment by dpedroza74** [comment]
@Nayita 
@CorinaCantero 

En la descripción del insumo del atributo de precipitación, ¿podrían cambiar en la descripción de la fuente para que quede así por favor?

Adaptado de: Precipitación acumulada anual. Atlas de Peligros por Fenómenos Naturales del Estado de Yucatán. Servicio Geológico Mexicano

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by dpedroza74** [comment]
@Nayita 

Favor de poner bullets en la meta

**Comment by vichdzgeo** [comment]
## Áreas por categoría de aptitud


Categoría | Km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 3679.0 | 9
Alta | 21901.9 | 55
Moderada | 10084.4 | 26
Baja | 258.8 | 1
Muy baja | 804.5 | 2
Nula | 2808.0 | 7

@Nayita 

## Mapa de aptitud
Ruta: talleres\sectores\pec_bovino\aptitud

- bov_bovino.tif

## Mapa de exclusión 
Insumos:

1 - Categorías nulas en el atributo de cobertura,  tabla_fv_bov_cobertura_usv_svi_16cats.csv
2 - Polígonos de todas las localidades de urbanas y rurales 2020

- bov_bovino_exclusion.tif

@CorinaCantero 

## Mapa de aprovechamiento actual 
No aplica

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor agregar lo siguiente al informe:

- [ ] mapa_bov_exclusion
- [ ] mapa_bov_aptitud

- [ ] Tabla insumos exclusión:

Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Polígonos de localidades.   Marco Geoestadístico. Censo de Población y Vivienda INEGI
Año | [1] 2017; [2] 2020
Campo | [1] descripcio
Escala | [1] 1:250,000; [2] Sin dato
Unidades | Adimensional

- [ ] Tabla de ID y categorías para exclusión

ID | Categoría
-- | --
1 | Acuícola
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

- [ ] Quitar acentos de sabana para criterios de cobertura

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

Falta:
@TatianaMerino @Nayita @vichdzgeo @CorinaCantero @ofegarcia 
- [ ]  Tabla de pesos globales
- [ ]  Figura de sensibilidad
- [ ]  Lista de asistencia

**Comment by CorinaCantero** [comment]
### **TABLA DE PESOS GLOBALES**
@Nayita 

Por favor agregar al informe:

- [ ] Pecuario bovino

Criterio | Peso
-- | --
Disponibilidad de agua | 0.405
Precipitación | 0.210
Energía | 0.158
Tipo de suelo | 0.083
Tipo de cobertura | 0.053
Vías de comunicación | 0.040
Centros de acopio | 0.040
Rastros | 0.010

**Comment by Nayita** [comment]
### AVISO

Lista la actualización del informe.

@TatianaMerino @dpedroza74 

- [ ] Falta definición de pecuario bovino en vista de que se convirtió en subsector junto al pecuario silvopastoril.

**Comment by dpedroza74** [comment]
Sistema de producción de ganado bovino extensivo o estabulado, en el que la alimentación se basa principalmente en pastizales de monocultivo de gramíneas forrajeras y el uso de granos (raciones balanceadas)

**Comment by Nayita** [comment]
### AVISO

Informe concluido.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita

Por favor hacer las siguientes modificaciones en la parte de exclusión para **pecuario bovino**:

- [ ] Agregar los números entre corchetes y el enunciado después del número [2]
- [ ] Cambiar la tabla de exclusión por la siguiente:

[1]

ID | Categoría
-- | --
1 | Acuícola
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

[2] Se utilizaron todas las localidades (urbanas y rurales)

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@vichdzgeo 

- [ ]  Favor de publicar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Se corrigió la tabla de exclusión (ID, Categoría) del comentario AVISO. MAPAS APTITUD Y EXCLUSIÓN para agregar la categoría ND (le quité la palomita)

**Comment by Nayita** [comment]
### AVISO

Lista la actualización del informe

**Comment by paola-gp** [comment]
@CorinaCantero 

- [ ] Se actualiza capa de cobertura, subir capa actualizada a SIGfunctionD

**Comment by CorinaCantero** [comment]
### **AVISO**
@vichdzgeo 

Lista la capa evaluada y exportada de cobertura (corregida con capa de manglares) 
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\pec_bovino\funciones_valor\fv_bov_bio_cobertura_usv_svi_16cats_costa_manglar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor actualizar en el informe las tablas de insumos de cobertura de: servicios ambientales de soporte, regulación, provisión y  la tabla de insumos de la capa de exclusión por la siguiente:

Capa | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor actualizar las tablas de insumos: 

- [ ] Tipo de cobertura 

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Tabla de insumos exclusión 


Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo   de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000;[2] 1:50,000; [3] Sin dato
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Actualizaciones

- [ ] Actualizar figura de mapa de aptitud @CorinaCantero 
- [ ] Actualizar figura de mapa de exclusión @CorinaCantero 
- [ ] Actualizar tabla de áreas por categoría de aptitud @Nayita

**Comment by vichdzgeo** [comment]
## Producto final 

- bov_bovino.tif (mapa categorizado)
- bov_bovino_integrado.tif (mapa normalizado entre o y 1, incluye exclusión con valor 0.0)

**Comment by CorinaCantero** [comment]
### PESOS GLOBALES PARA EL MAPA DE APTITUD INTEGRADO DEL SECTOR PECUARIO BOVINO: PECUARIO BOVINO Y PECUARIO SILVOPASTORIL #54 
@Nayita 

- [ ] Favor de agregar al informe

Criterio | Peso
-- | --
Disponibilidad de agua - Bovino | 0.203
Disponibilidad de agua - Silvopastoril | 0.190
Precipitación - Bovino | 0.105
Cobertura - Silvopastoril | 0.100
Energía - Bovino | 0.079
Disponibilidad de mano de obra -   Silvopastoril | 0.075
Accesibilidad a mercados locales -   Silvopastoril | 0.045
Tipo de suelo - Bovino | 0.041
Precipitación - Silvopastoril | 0.040
Tipo de suelo - Silvopastoril | 0.040
Tipo de cobertura - Bovino | 0.026
Vías de comunicación - Bovino | 0.020
Centros de acopio - Bovino | 0.020
Temperatura - Silvopastoril | 0.010
Rastros - Bovino | 0.005
Accesibilidad a mercados foráneos -   Silvopastoril | 0.005

**Comment by vichdzgeo** [comment]
## Integración de los subsectores bovino - Silvopastoril

bovino w = 0.5 , silvopastoril = 0.5

## tabla de área por categoría de aptitud del mapa integrado 

Categoría | km² | Porcentaje del estado
-- | --: | --:
Muy alta | 8378.1 | 21
Alta | 22575.8 | 57
Moderada | 4686.9 | 12
Baja | 147.6 | 0
Muy baja | 820.9 | 2
Nula | 2927.2 | 7

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Mapas de aptitud y exclusión integrado del sector bovino: 

- [ ] mapa_bov_integrado_aptitud
- [ ] mapa_bov_integrado_exclusion

**Comment by CorinaCantero** [comment]
### CORRECCIONES
@Nayita 

Por recepción de metadatos favor de hacer la siguiente corrección: 

- [ ] En la tabla de insumos de la sección 1.2.1.1 Disponibilidad de agua cambiar el año de "Sin dato" a **2007**

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de agregar lo siguiente al informe- Mapa de aptitud integrado zonas de exclusión

- [ ] Tabla de insumos

Capa | Uso del suelo y vegetación y localidades
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación. Serie VI. Conjunto Nacional INEGI, [2] Mapa de uso del suelo y vegetación de la zona costera asociada a los manglares, Región Península de Yucatán CONABIO y [3] Polígonos de localidades. Marco Geoestadístico. Censo de Población y Vivienda INEGI
Año | [1] 2017; [2] 2021; [3] 2020
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000;[2] 1:50,000; [3] Sin dato
Unidades | Adimensional

- [ ] Tabla ID/categoría

ID | Categoría
-- | --
1 | Acuícola
6 | Cuerpo de agua
7 | Manglar
13 | Tular
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila

**Comment by Nayita** [comment]
### Diagrama del modelo de decisión del mapa de aptitud integrado

![fi_bov_integrado](https://user-images.githubusercontent.com/25210323/120407389-ad583980-c312-11eb-9e27-52db299c0c7f.png)

**Comment by TatianaMerino** [comment]
@Nayita  favor de hacer la modificación de la tabla de FV

## INFORME PECUARIO BOVINO EXTENSIVO O ESTABULADO
1.2.1.2 Precipitación

ID | Categoría (mm) | Importancia | FV
-- | -- | -- | --
5 | 1081-1233 | Muy alta | 1.00
4 | 930-1081 | Alta | 0.75
3 | 778-930 | Moderada | 0.50
2 | 626-778 | Baja | 0.25
1 | 551-626 | Baja | 0.25

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
