### ISSUE TITLE
Generar el modelo de cambio de cobertura

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#79]
## Objetivos:

- Explorar Idrisi y dinámica EGO  para seleccionar el que facilite la tarea del desarrollo del autómata celular para cambio de cobertura
- Desarrollar el modelo de cambio de cobertura considerando la aptitud de los sectores
- Generar el informe asociado

## Carpeta de trabajo:

/SIG/desarrollo/sig_fomix/procesamiento/cambio_cobertura_ca

**Comment by iaga** [comment]
## Tareas:

- [ ] Apoyo en la instalación de Idrisi en las computadoras del grupo de trabajo (Lunes 15 de Febrero). Responsable: @vichdzgeo 
- [ ] Ubicar insumos en la carpeta correspondiente (insumos). Responsable: @aaron-ts 
- [ ] Explorar Dinamica Ego. Responsable: @serranoycandela 
- [ ] Explorar Idrisi. Responsable: @aaron-ts

**Comment by iaga** [comment]
@vichdzgeo Luis comentó que existen ya algunos mapas de aptitud generados. ¿Podrías indicarnos cuáles son y su ubicación?

**Comment by vichdzgeo** [comment]
## Instalador de Idrisi

CARPETAS_TRABAJO\vhernandez\software
- Idrisi Selva (17.00).zip (instalador) **antes de descomprimir leer realizar los primeros dos pasos del archivo txt de instrucciones**
- Instrucciones_Idrisi.txt
@aaron-ts

**Comment by vichdzgeo** [comment]
## Mapas de aptitud

Ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores

Encontrarás un directorio por cada sector, en la subcarpeta **aptitud** encontraras los mapas de aptitud

Los mapas que terminan en:
**sigindex**: son los mapas exportados de la plataforma normalizados
**sigindex_equidistante**: son los mapas exportados de la plataforma con clasificación equidistante (progresiva con fp=1 y 5 categorias)

Los mapas que **no** tienen en su nombre nada relacionado con sigindex, Por ejemplo:

- urb_urbano.tif
- ene_energia.tif
Son los mapas finales  de aptitud por sector, los cuales incluyen zonas de exclusión y zonas de aprovechamiento actual. Estos mapas estas clasificados de 0 a 5, donde 0 representa una aptitud Nula; 1 una aptitud muy baja hasta 5 una Muy alta aptitud

@serranoycandela  @aaron-ts

**Comment by iaga** [comment]
@vichdzgeo Indicar la ruta de las reclasificaciones de las series de uso de suelo y vegetación de inegi que se reclasificaron en menos categorias y notificar a @serranoycandela

**Comment by iaga** [comment]
@aaron-ts Notificar si lograste la instalación de Idrisi satisfactoriamente en tu equipo de trabajo

**Comment by vichdzgeo** [comment]
### Capas raster de cobertura con 16 categorías 

mapas de las 6 series de uso de suelo y vegetación 

NOTAS: 
- las capas contienen una categoría (17) que representa los huecos de información de las capas originales y que caen dentro del límite estatal de Yucatán.
- las capas de la serie 1 y 2 no cuentan con la categoría 1 (Acuícola)


Ruta de los productos solicitados:
SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\usv_16cats\
cada capa cuenta con su archivo xml que contiene el nombre de la categoría según su valor en la capa 

## Insumos de origen capas vectoriales
ruta: SIG\desarrollo\sig_fomix\entregables\sub_natural\usv_serie#

Se pueden consultar los archivos shape como alternativa para saber la categoria asociada a el valor de pixel
los campos son **clase1** el cual contiene el nombre de la categoría de cobertura; **id_clase1** el cual representa el valor numérico asociado al mapa raster.

@serranoycandela

**Comment by iaga** [comment]
# Actividades:

@serranoycandela 
- [ ] Investigar qué software se puede instalar en el cluster
- [ ] Verificar tiempo de cómputo IDRISI y Dinámica EGO
- [ ] Ensamblar ejemplo en Dinámica EGO con datos de Yucatán
- [ ] Revisar workstation en windows para correr IDRISI

@aaron-ts 
- [ ] Ensamblar ejemplo en IDRISI con datos de Yucatán
- [ ] Instalar IDRISI en Linux con la máquina virtual

@iaga y Luis
- [ ] Clasificar municipios de Yucatán para dividir los ráster

**Comment by iaga** [comment]
# Tutorial de Idrisi

**Ruta:** insumos/bibliografia/IDRISI Tutorial.pdf
**Instrucciones para correr el CA en Idrisi:** Exercise 3-6 Using Markov Cellular Automata for Landuse Change Modelling

## Nota:
El archivo TRANSSUIT está roto. Es necesario generar un grupo de rásters nuevo con los mapas de aptitud para correr el ejemplo.

**Comment by iaga** [comment]
@vichdzgeo reportar la ubicación de la clasificación de Yucatán por regiones y municipios

**Comment by vichdzgeo** [comment]
@serranoycandela 

Ruta: \SIG\desarrollo\sig_fomix\procesamiento\frag_series\insumos\municipios_frags

- serie_1.shp
- serie_2.shp
- serie_3.shp
- serie_4.shp
- serie_5.shp
- serie_6.shp

cada capa contiene el campo **cvegeo** que indica el id por municipio y **id_region**  Que indica el número de región a la que pertenece, el campo **region** contiene el nombre de la región

**Comment by vichdzgeo** [comment]
### Capa de distancia a localidades urbanas 

- Capa de distancia a localidades urbanas
sig_fomix/procesamiento/analisis_aptitud/sectores/urbano/procesamiento/d_localidades_excluyente_con_carreteras.tif

- Función de valor de distancia a localidades urbanas para el sector urbano [ver 1.3.2 Crecimiento urbano orgánico](https://lancis-apc.github.io/fomix/urbano_pr.html)
-FOMIX/fmx_estudio_tecnico/diagnostico/talleres/sectores/urbano/funciones_valor/fv_urbano_crecimiento.tif
@serranoycandela

**Comment by vichdzgeo** [comment]
## Coberturas corregidas 

Ruta:
insumos\series_corregidas

Series corregidas : 

- usv_serie1_100m_v4_corregida.tif
- usv_serie3_100m_v4_corregida.tif
- usv_serie5_100m_v4_corregida.tif
- usv_serie6_100m_v4_corregida.tif


## Categorías de las capas
id | Clase_v4
-- | --
1 | Acuícola
2 | Agricultura
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar, petén, tular e hidrófila
9 | Selva
11 | Sin vegetación
14 | Duna costera
17 | ND

@serranoycandela  @aaron-ts

**Comment by iaga** [comment]
## Relacionar aptitud con cobertura

**Objetivo**: Cruzar y sacar valores promedio de aptitud por tipo de vegetación, llevar a ideales
Responsable: @vichdzgeo

**Comment by iaga** [comment]
serie|año
--|--
1|1985
3|2002
5|2011
6|2014

**Comment by vichdzgeo** [comment]
## Mapas de aptitud integrados

Ruta: 

SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\mapas_aptitud

## Mapas cruzados entre cobertura y aptitud por sector

Ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\\aptitud_cobertura

- archivos con terminación "_i.tif" son archivos llevado a ideales 
ejemplo: 

apt_acuacultura_cobertura.tif mapa con el valor promedio de aptitud por tipo de cobertura de la serie 6 Clase_v4
apt_acuacultura_cobertura_i.tif mapa con el valor promedio de aptitud idealizada (dividida entre el valor promedio máximo)  por tipo de cobertura de la serie 6 Clase_v4

@serranoycandela

**Comment by iaga** [comment]
# Actividades:

- [ ] @serranoycandela y @vichdzgeo, documentar la versión actual del modelo en dinamica EGO
- [ ] @TatianaMerino, @aaron-ts, @iaga, correr la última versión del modelo y anotar dudas para realizar el procedimiento (para el martes 04/05/2021)

**Comment by serranoycandela** [comment]
Corrió el modelo con aptitud como probabilidad. Para este primer ejemplo se compilaron únicamente las probabilidades de transición hacia urbano y agropecuario, para la probabilidad hacia urbano se usó el máximo por pixel de las aptitudes (industrial, turístico, y urbano) y para la probabilidad hacia agropecuario se usó el máximo por pixel del las aptitudes (milpa maya, agricultura, pec_bovino, pec_porcino_v2)

El código para correr el modelo está en la carpeta cambio_cobertura_ca\v4_aptitud

![primer_modelo](https://user-images.githubusercontent.com/12860576/117183364-147ae080-ad9d-11eb-9851-f53186b1a44a.PNG)

primer corrida de 10 steps:
![primer_corrida](https://user-images.githubusercontent.com/12860576/117183458-31afaf00-ad9d-11eb-8dc8-fbf3f16ef5b4.PNG)

**Comment by iaga** [comment]
# Actividades:

- [ ] Revisar y entender los módulos: PATCHER y EXPANDER @serranoycandela, @aaron-ts, @TatianaMerino, @iaga 
- [ ] Calcular la estadística necesaria para correr el modelo: tamaño promedio de parche, varianza, isometria @vichdzgeo

**Comment by iaga** [comment]
Videos tutoriales del programa DINAMICA EGO (https://csr.ufmg.br/dinamica/)

Introducción a DINAMICA EGO https://www.youtube.com/watch?v=SLzu21E_9so

Reclasificación de mapas raster con DINAMICA EGO https://www.youtube.com/watch?v=1rwLsgq2qm0

Algebra de mapa con DINAMICA EGO https://www.youtube.com/watch?v=mIqs3wKkDXw

Operaciones zonales con DINAMICA EGO https://www.youtube.com/watch?v=6G9OylPEsCs

Loops e iteraciones con DINAMICA EGO https://www.youtube.com/watch?v=LdQS7ZPXLLI

**Comment by iaga** [comment]
https://www.ciga.unam.mx/wrappers/proyectoActual/modelacione/files/curso_dinamica_abril2017.pdf

**Comment by TatianaMerino** [comment]
para revisar lo de curvas ROC
https://lukeoakdenrayner.wordpress.com/2017/12/06/do-machines-actually-beat-doctors-roc-curves-and-performance-metrics/
https://lukeoakdenrayner.wordpress.com/2018/01/07/the-philosophical-argument-for-using-roc-curves/

**Comment by iaga** [comment]
@TatianaMerino @serranoycandela 

La presentación se encuentra en la ruta: 

\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\presentaciones\ca_markov_resultados.pptx

**Comment by TatianaMerino** [comment]
## Diagrama del modelo de cambio de cobertura DINAMICA 
Ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\diagramas\fi_diagrama_cobertura.png

![fi_diagrama_cobertura](https://user-images.githubusercontent.com/57197109/118848481-6723c480-b894-11eb-91bc-d53d40e27671.png)

**Comment by iaga** [comment]
## Análisis de redes

El análisis de redes para las matrices de transición se ubica en la ruta:
CARPETAS_TRABAJO\igrave\avance_personal\markov\red

Los resultados se encuentran en el ppt: .\resultados_analisis_redes_cc.pptx
El modelo de cytoscape que contiene las redes para las tres series: .\insumos\series_v2.cys

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
