### ISSUE TITLE
Preparar el informe de resultados de la revisión de las capas de información geográfica #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#8]
**Objetivo:** Preparar el informe de resultados de la revisión de las capas de información geográfica para incluirlo en la sección del informe de Análisis de activos de información que forma parte del diagnóstico institucional.

### Revisión de capas de la bitácora ambiental

Se evaluarán las capas disponibles en la página web de la bitácora ambiental del estado de Yucatán,  POETY y POETCY.

Se generará una base de datos con los siguientes campos: 

Tema | Nombre del   producto | Autor | Escala | Año | Fuente | Shape | Metadato
-- | -- | -- | -- | -- | -- | -- | --

INSUMOS

- Ubicación de la base de datos: SIG\desarrollo\sig_fomix\insumos
- Página web de la bitácora ambiental: http://bitacoraordenamiento.yucatan.gob.mx/galeria/index.php

### Revisión de capas de insumos generales para el proyecto FOMIX

Se realizará un banco de datos con el registro de los activos de información geográficos disponibles que han sido recopilados de fuentes oficiales, con la finalidad de compartirlo con académicos e instituciones interesadas en participar en la actualización del POETY para que puedan, si así lo desean, contribuir a ampliar el catálogo de información geográfica disponible. 

INSUMOS
- Ubicación de la base de datos (momentánea): \CARPETAS_TRABAJO\ccantero\catalogos

Para la revisión de la calidad de capas geográficas se incluirá en la base de datos una verificación por parte de @vichdzgeo que incluye una calificación de los parámetros:

Proyección | Geometría | Sobrelapado | Sin atributos | Nulos | Codificado
-- | -- | -- | -- | -- | --

**Comment by CorinaCantero** [comment]
@Nayita 
Descargar los shapefiles disponibles en la página de la bitácora ambiental del Programa de Ordenamiento Ecológico del Territorio Costero del Estado de Yucatán (POETCY), hacer una carpeta para cada subsistema y dentro de esas carpetas ir guardando los archivos en subcarpetas.

Ubicación en Dropbox:
SIG\desarrollo\sig_fomix\insumos\poetcy

**Comment by Nayita** [comment]
### Aviso
Se han terminado de descargar las capas del POETCY 

- Mapa base

- Subsistema social

**Comment by Nayita** [comment]
### Aviso
@CorinaCantero 
Se ha concluido con las descargas de capas del POETCY

- Subsistema natural

- Subsistema económico

- Subsistema territorio

No se pudieron descargar las capas en las siguientes carpetas:

- Destino producción agrícola

- Instituciones de apoyo

- Actividad enzimática CAT (metadatos en lugar de shape)

Hay capas que están tanto en el Subsistema Natural como en el Subsistema Territorio. Ejem. Ancho playa Terr, Aptitud agropecuaria

**Comment by CorinaCantero** [comment]
@vichdzgeo 

Ya terminó Nadia de descargar las capas del POETCY, para que las puedas revisar con tu código para calificar su calidad. 

Ubicación: SIG\desarrollo\sig_fomix\insumos\poetcy

**Comment by vichdzgeo** [comment]
@CorinaCantero 

Se terminó de revisar las capas:

las bitácoras se encuentran en : 

- \SIG\desarrollo\sig_fomix\insumos\poetcy\faltantes\bitacora_poetcy_faltantes.csv
- \SIG\desarrollo\sig_fomix\insumos\poetcy\bitacora_poetcy.csv

**Comment by CorinaCantero** [comment]
@paola-gp 

La versión final del catálogo de capas geográficas de POETY/POETCY y de otras fuentes de información oficiales está ubicada en:

-  SIG\desarrollo\sig_fomix\insumos\catalogo_fomix_final.xlsx

**Comment by CorinaCantero** [comment]
### AVISO

@dpedroza74 

El catálogo final de capas de información geográfica disponibles ha sido terminado y está listo para ser enviado a quien corresponda. 

**Ubicación:** FOMIX\fmx_insumos\bd_informacion_geografica.xlsx

- La hoja "_poety-poetcy_" contiene la información descargada de la página web de la bitácora ambiental, para los programas: Ordenamiento Ecológico Territorial del estado de Yucatán y el Ordenamiento Costero; los productos fueron agrupados de acuerdo a los temas que se manejan en la misma página eléctronica, correspondiente a subsistemas (económico, territorio, social, natural) 

- La hoja "_general_" contiene la base de datos de la información geográfica obtenida de diversas fuentes de información oficial (INEGI, SEMARNAT, CONAGUA, etc). Los productos se agruparon de acuerdo a la clasificación de la temática establecida en el protocolo para el manejo de la información geográfica del  APC.

**Comment by CorinaCantero** [comment]
### AVISO

Se actualizó la base de datos, pues SEMARNAT proporcionó los metadatos que se le solicitaron. Dichos metadatos se agregaron a Dropbox.

**Comment by CorinaCantero** [comment]
@dpedroza74

**Comment by CorinaCantero** [comment]
### AVISO 
@dpedroza74 

En los comentarios anteriores está la explicación de lo que contiene la base de datos 
Ubicación: FOMIX\fmx_insumos\bd_catalogo_informacion_geografica.xlsx
