### ISSUE TITLE
Integrar informe del análisis de aptitud del sector pesca y acuacultura #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#82]
### Capas acuacultura:

- [ ] Restricciones por inocuidad: lejos de áreas industriales, áreas agrícolas con uso de agroquímicos, sitios de disposición de residuos
   - [ ] Opción 1: Distancia a parques industriales incluyentes (ya que la mejor condición será lo más lejano)
   - [ ] Opción 2: Distancia a polígonos identificados como agricultura de riego y/o agricultura de temporal incluyentes
   - [ ] Opción 3: Distancia a todos los sitios de disposición de residuos
----------------------------------------------------------------------------------------------------------------------------------------------
### **Biofísicos**
**Acceso a agua**
- [x] opción 2: distancia de manto freático  "continua"
- [x] Nivel estático
**Salinidad**
- [x] Espesor de agua dulce (m)

**Vegetación** 
- [x] Uso de suelo y vegetación INEGI

### **Infraestructura**
**Carreteras**
- [x] Distancia a carreteras y caminos
**Electricidad**
- [x] opción 1: capa de INEGI (contiene más elementos) 
**Localidades**
- [x]  Distancia a localidades con 2,500 hab o más (incluyente?)

### **Infraestructura**
**Agua potable**
- [x] Distancia a localidades con agua entubada (%)
**Comunicaciones**
 - [x] Distancia a localidades con internet (%)
 - [x] Distancia a localidades con celular (%) `Nota: el campo es VPH_CEL`
**Carreteras** 
- [x] Opción 2: Distancia a todo tipo de caminos (carreteras, caminos y veredas)
**Electricidad**
- [x] opción 1: capa de INEGI (contiene más elementos) 

### **Socioeconómicos**
**Centros de distribución**
 - [x] Distancia a los puntos de distribución de productos: Progreso, Mérida, Valladolid, Tizimín, Hunucmá y Motul 
sig_fomix\procesamiento\analisis_aptitud\sectores\pesca\insumos\centros_distribucion_pesca.shp
**Localidades**
- [x] Distancia a localidades de comunidades pesqueras: Celestún, Sisal, Chuburná, Yucalpetén, Progreso, Telchac, Chabihau, Dzilam de Bravo, San Felipe, Río Lagartos, Las Coloradas, El Cuyo, Chelem, Chicxulub, Santa Clara y San Crisanto.
sig_fomix\procesamiento\analisis_aptitud\sectores\pesca\insumos\localidades_pesca.shp

**Comment by TatianaMerino** [comment]
# Insumos sesión 2 (4 de marzo, 2021)

## Modelos

Se contemplarán dos sectores: (1) Sector pesca y (2) sector acuacultura
con metas y modelos independientes.

Archivos: **acua_04mar2021_v2.sdmod** y **pes_04mar2021_v2.sdmod**

## Acuacultura

Meta
--|
Promover el crecimiento de la producción acuícola de agua marina en la zona costera y de agua dulce al interior del estado, a partir de la capacitación del personal técnico, la construcción de granjas y la integración de la infraestructura ya existente a un estándar de sustentabilidad.
Implementar en la granjas acuícolas infraestructura y tecnología para la mejora de los procesos de producción, como el uso de sistemas de recirculación del agua, sistemas acuapónicos y de generación de energía solar.
Establecer y habilitar centros de acopio, laboratorios de producción de semilla, unidades de bioseguridad y centros de capacitación para la producción acuícola (proyecto de parque acuícola).

**Biofísicos**

Criterio|Definición
--|--|
Acceso a agua| Posibilidad de extraer agua subterránea, considerando el nivel piezométrico.
Salinidad| Interfase salina
Vegetación| Tipos de vegetación y usos de suelo.

**Infraestructura**
Criterio|Definición
--|--|
Carreteras| Distancia a caminos, brechas y carreteras para el transporte de insumos y productos.
Electricidad| Distancia a red de transmisión eléctrica.
Localidades| Distancia a localidades de 2,500 habitantes o más, para mano de obra en las granjas acuícolas.

## Pesca

Meta
--|
Fortalecer el sector pesquero para que desarrolle actividades pesqueras viables y sostenibles.
Fortalecer la infraestructura de procesamiento actual en la zona costera y áreas circundantes, así como buscar espacios para el desarrollo de centros de acopio y plantas de procesamiento de subproductos de la pesca, que cumplan con la normatividad nacional e internacional.
Asegurar espacios de refugio para embarcaciones pesqueras y definir espacios diferenciados para las embarcaciones de desarrollo turístico y pesca comercial.

**Infraestructura**

Criterio|Definición
--|--|
Agua potable| Distancia a localidades que se evaluaron con base en el porcentaje de viviendas que disponen de agua entubada.
Internet| Distancia a localidades que se evaluaron con base en el porcentaje de viviendas con internet.
Carreteras| Distancia a caminos, brechas y carreteras para el transporte de insumos y productos.
Electricidad| Distancia a red de transmisión eléctrica.

**Socioeconómicos**

Criterio|Definición
--|--|
Centros de distribución| Distancia a los puntos de distribución de productos: Progreso, Mérida, Valladolid, Tizimín, Hunucmá y Motul 
Localidades| Distancia a localidades de comunidades pesqueras (cuentan con pescadores, embarcaciones y puertos de abrigo).

- [ ] @dpedroza74 favor de revisar.

**Comment by dpedroza74** [comment]
Áreas de restricción
Buffer de 2km alrededor de las ANP, incluyendo cenotes

**Comment by CorinaCantero** [comment]
### AVISO

Información entregada por la Secretaría de Pesca y Acuacultura Sustentables (SEPASY): 

**1. Unidades   acuícolas**
``En la información de cada una tenemos dos variables particulares: Activa/Inactiva y Operando/Sin Operar. Esto debido a que algunas unidades se encuentran en buen estado pero por diversos motivos no estén produciendo, siendo entonces Activas Sin Operar. Pero una vez que se capitalizan o solventan el problema que tengan, comienzan de nuevo a producir. Las granjas Inactivas son aquellas que se encuentran generalmente en abandono y que requieren mucha inversión para volverse a activar.``

**2. Diagnóstico de los sectores de Pesca y Acuacultura del Estado de Yucatán**
``Respaldo de la base de datos que trabajó Andrés Maldonado con el Dr. Jorge Euan del Cinvestav Mérida.
Sin embargo, las capas finales publicadas en el Diagnóstico como las de Profundidad de Interfase Salina, la de Aptitud Acuícola para especies de agua salobre y marina no se encuentran. La información colectada sirvió para hacer esos análisis multivariados y debe ser posible replicarlos.``

**Comment by Nayita** [comment]
### AVISO

@dpedroza74 

![fi_acuacultura](https://user-images.githubusercontent.com/25210323/110520748-82c06100-80d4-11eb-97da-6bd632dd556b.png)

![fi_pesca](https://user-images.githubusercontent.com/25210323/110520774-88b64200-80d4-11eb-8f78-6bc3d941d00e.png)

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

@vichdzgeo 

- [ ] Favor de publicar

**Comment by TatianaMerino** [comment]
Modificación del modelo de Acuacultura
![fi_acua_09mar2021](https://user-images.githubusercontent.com/57197109/110527031-1ba6aa80-80dc-11eb-9f1b-8d2c4932a527.png)

**Comment by dpedroza74** [comment]
@Nayita 
Un favor, en la tabla de deficiones cambié el nombre del atributo "Carreteras" a "Vía de comunicación", podrías cambiar eso en el diagrama de pesca, porfa?

**Comment by TatianaMerino** [comment]
# Acuacultura

**Modelo**: acua_09mar2021_v3.sdmod

**AVISO**
Serán dos mapas de aptitud: (1) Acuacultura de agua salada y (2) Acuacultura de agua dulce. Con los mismos criterios, los mismos pesos  y las mismas funciones de valor, a excepción de la fv de **Salinidad** (Espesor de agua salada//Espesor de agua dulce)


## Definiciones

**Meta**
--|

- Promover el crecimiento de la producción acuícola de agua marina en la zona costera y de agua dulce al interior del estado, a partir de la capacitación del personal técnico, la construcción de granjas y la integración de la infraestructura ya existente a un estándar de sustentabilidad.
- Implementar en la granjas acuícolas infraestructura y tecnología para la mejora de los procesos de producción, como el uso de sistemas de recirculación del agua, sistemas acuapónicos y de generación de energía solar.
- Establecer y habilitar centros de acopio, laboratorios de producción de semilla, unidades de bioseguridad y centros de capacitación para la producción acuícola (proyecto de parque acuícola).

**Biofísicos**

Criterio|Definición
--|--|
Acceso a agua| Posibilidad de extraer agua subterránea, considerando la Profundidad en metros, a partir de la superficie del terreno, a la cual se encuentra el espejo de agua (acuífero).
Salinidad| Ancho en metros de la columna de agua dulce, a partir del cual se puede encontrar agua salada.
Vegetación| Tipos de vegetación y usos de suelo.

**Infraestructura**
Criterio|Definición
--|--|
Electricidad| Distancia a red de transmisión eléctrica.
Vías de comunicación| Distancia a caminos y carreteras para el transporte de insumos y productos.

**Socioeconómicos**
Criterio|Definición
--|--
Tenencia| Tenencia de la tierra. 

## Funciones de valor categóricas

**Vegetación**

ID | Categoría | Importancia | FV
-- | -- | -- | --
1 | Acuícola | Muy alta | 1.00
11 | Sin vegetación | Muy alta | 1.00
3 | Agricultura de temporal | Alta | 0.75
8 | Pastizal | Alta | 0.75
2 | Agricultura de riego | Moderada | 0.50
5 | Bosque cultivado/Palmar inducido | Moderada | 0.50
9 | Selva baja | Moderada | 0.50
12 | Sábana | Moderada | 0.50
7 | Manglar | Baja | 0.25
10 | Selva mediana | Baja | 0.25
13 | Tular | Baja | 0.25
4 | Asentamiento humano | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
14 | Vegetación de duna costera | Nula | 0.00
15 | Vegetación de petén | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

**Tenencia**
ID | Categoría | Importancia | FV
-- | -- | -- | --
3 | No ejidal | Muy alta | 1.00
2 | Zona de tierras parceladas | Alta | 0.75
1 | Tierra de uso común | Baja | 0.25

# Pesca

**Modelo:** pes_09mae2021_v2.sdmod

## Definiciones

Meta
--|

- Fortalecer el sector pesquero para que desarrolle actividades pesqueras viables y sostenibles.
- Fortalecer la infraestructura de procesamiento actual en la zona costera y áreas circundantes, así como buscar espacios para el desarrollo de centros de acopio y plantas de procesamiento de subproductos de la pesca, que cumplan con la normatividad nacional e internacional.
- Asegurar espacios de refugio para embarcaciones pesqueras y definir espacios diferenciados para las embarcaciones de desarrollo turístico y pesca comercial.

**Infraestructura**

Criterio|Definición
--|--|
Agua potable| Requerimiento de agua potable para la producción de hielo. El atributo se representa con la distancia a localidades que se evaluaron con base en el porcentaje de viviendas que disponen de agua entubada.
Electricidad| Distancia a red de transmisión eléctrica.
Vías de comunicación| Distancia a caminos y carreteras para el transporte de insumos y productos.
Comunicaciones| Acceso a  comunicación a través de internet y telefonía. El atributo se representa con la distancia a localidades que se evaluaron con base en el porcentaje de viviendas con internet, celular y teléfono.

**Socioeconómicos**

Criterio|Definición
--|--|
Localidades| Distancia a localidades con comunidades pesqueras: Celestún, Sisal, Chuburná, Yucalpetén, Progreso, Telchac, Chabihau, Dzilam de Bravo, San Felipe, Río Lagartos, Las Coloradas, El Cuyo, Chelem, Chicxulub, Santa Clara y San Crisanto.
Centros de distribución| Distancia a los puntos de distribución de productos pesqueros: Progreso, Mérida, Valladolid, Tizimín, Hunucmá y Motul.

**Comment by CorinaCantero** [comment]
TABLAS DE INSUMOS
@Nayita 

Favor de agregar al informe: 

## **PESCA**

### **Socioeconómicos**

- [ ] Centros de distribución

Capa | Distancia a localidades con centros de   distribución pesquera
-- | --
Fuente | Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI
Año | 2020
Escala | Sin dato
Unidades | Kilómetros

- [ ] Localidades

Capa | Distancia a localidades pesqueras
-- | --
Fuente | Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI
Año | 2020
Escala | Sin dato
Unidades | Kilómetros


### **Infraestructura**

- [ ] Agua potable

Capa | Viviendas que disponen de agua entubada por   localidad
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Campo | [2] VIVTOT y VPH_AEASP
Unidades | Porcentaje

- [ ] Comunicaciones

Capa | Viviendas con internet por localidad
-- | --
Fuente | [1] Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI y [2] Datos de indicador. Censo de Población y Vivienda.   Principales resultados por localidad (ITER) INEGI
Año | 2020
Campo | [2] VIVTOT y VPH_INTER
Unidades | Porcentaje

- [ ] Vías de comunicación

Capa | Distancia a la red vial
-- | --
Fuente | Red Nacional de Caminos (RNC) Red vial - INEGI
Año | 2019
Escala | Sin dato
Unidades | Kilómetros

- [ ] Electricidad

Capa | Distancia líneas de transmisión de energía   eléctrica
-- | --
Fuente | Líneas de transmisión INEGI
Año | 2012
Escala | 1:50,000
Unidades | Kilómetros

**Comment by CorinaCantero** [comment]
### **INSUMOS PARA EL INFORME**
@Nayita 

Por favor agregar lo siguiente al informe: 
**Acuacultura de agua salada**

- [ ] mapa_fv_acuasal_bio_nivel_estatico
- [ ] mapa_fv_acuasal_bio_espesor_agua_salada
- [ ] mapa_fv_acuasal_bio_cobertura_usv_svi_16cats
- [ ] mapa_fv_acuasal_infra_d_carreteras_caminos
- [ ] mapa_fv_acuasal_infra_d_lineas_electricas
- [ ] mapa_fv_acuasal_socio_tenencia_tierra

**Acuacultura agua dulce**

- [ ] mapa_fv_acuadul_bio_nivel_estatico
- [ ] mapa_fv_acuadul_bio_espesor_agua_dulce
- [ ] mapa_fv_acuadul_bio_cobertura_usv_svi_16cats
- [ ] mapa_fv_acuadul_infra_d_carreteras_caminos
- [ ] mapa_fv_acuadul_infra_d_lineas_electricas
- [ ] mapa_fv_acuadul_socio_tenencia_tierra

**Comment by TatianaMerino** [comment]
@Nayita 
Favor de cambiar los diagramas de Acuacultura con lo siguiente
- [ ] Nombres de los subsectores: "Acuacultura de especies de agua dulce" y "Acuacultura de especies de agua salobre y marina"
- [ ] Cambiar el criterio socioeconómico "Localidades" por "Tenencia"

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by TatianaMerino** [comment]
@Nayita  favor de hacer las siguientes actualizaciones de 
- [ ] definiciones de los criterios de infraestructura y socioeconómicos
- [ ] cambiar el diagrama para que diga "Localidades pesqueras" en socioeconómicos

# Pesca
**Infraestructura**
Criterio|Definición
--|--|
Agua potable| Requerimiento de agua potable para la producción de hielo. El atributo se representa con la distancia a localidades que se evaluaron con base en el porcentaje de viviendas que disponen de agua entubada.
Electricidad| Distancia a red de transmisión eléctrica.
Vías de comunicación| Distancia a caminos y carreteras para el transporte de insumos y productos.
Comunicaciones| Acceso a comunicaciones en localidades urbanas y pesqueras evaluadas con base en el porcentaje de viviendas con internet y celular.

**Socioeconómicos**

Criterio|Definición
--|--|
Localidades pesqueras| Distancia a localidades con comunidades pesqueras: Celestún, Sisal, Chuburná, Yucalpetén, Progreso, Telchac, Chabihau, Dzilam de Bravo, San Felipe, Río Lagartos, Las Coloradas, El Cuyo, Chelem, Chicxulub, Santa Clara y San Crisanto.
Centros de distribución| Distancia a los puntos de distribución de productos pesqueros: Progreso, Mérida, Valladolid, Tizimín, Hunucmá y Motul.

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@vichdzgeo 

- [ ] Favor de publicar

**Comment by CorinaCantero** [comment]
AVISO
@Nayita 

Por favor modificar lo siguiente en el informe:

- Se modificaron las tablas de insumos de: pesca/infraestructura/ **agua potable**, **internet** y se adicionó la de **celular**. 
- En el comentario de tablas de insumos ya agregaron las dos tablas de insumos que estaban pendientes: nivel estático (acceso a agua) y salinidad

**Comment by TatianaMerino** [comment]
# Actualizaciones de Acuacultura y Pesca

## Acuacultura

**Modelo:** acua_11mar2021.sdmod

### Definiciones

**Meta**
--|
- Promover el crecimiento de la producción acuícola de agua marina en la zona costera y de agua dulce al interior del estado, a partir de la capacitación del personal técnico, la construcción de granjas y la integración de la infraestructura ya existente a un estándar de sustentabilidad.
- Implementar en la granjas acuícolas infraestructura y tecnología para la mejora de los procesos de producción, como el uso de sistemas de recirculación del agua, sistemas acuapónicos y de generación de energía solar.
- Establecer y habilitar centros de acopio, laboratorios de producción de semilla, unidades de bioseguridad y centros de capacitación para la producción acuícola (proyecto de parque acuícola).

**Biofísicos**

Criterio|Definición
--|--|
Acceso a agua| Posibilidad de extraer agua subterránea, considerando la profundidad en metros, a partir de la superficie del terreno, a la cual se encuentra el espejo de agua (acuífero).
Salinidad| Profundidad a partir de la cual se puede encontrar agua salobre o salada, considerando el ancho en metros de la columna de agua dulce.
Vegetación| Tipos de vegetación y usos de suelo.

**Infraestructura**
Criterio|Definición
--|--|
Electricidad| Distancia a red de transmisión eléctrica.
Vías de comunicación| Distancia a caminos y carreteras para el transporte de insumos y productos.

**Socioeconómicos**
Criterio|Definición
--|--
Tenencia| Tenencia de la tierra. 

### Funciones de valor

@CorinaCantero  cambió la función contínua de Nivel estático para Acuacultura salobre (ya está exportada y actualizada)

## Pesca

**Modelo:** pes_11mar2021_v2.sdmod

AGREGAR LA SIGUIENTE NOTA DESPUÉS DEL DIAGRAMA

Debido a que la actividad pesquera en el estado es marina, el análisis se aplicó en la zona de 100 km de distancia a la costa.


## Definiciones

Meta
--|
- Fortalecer el sector pesquero para que desarrolle actividades pesqueras viables y sostenibles.
- Fortalecer la infraestructura de procesamiento actual en la zona costera y áreas circundantes, así como buscar espacios para el desarrollo de centros de acopio y plantas de procesamiento de subproductos de la pesca, que cumplan con la normatividad nacional e internacional.
- Asegurar espacios de refugio para embarcaciones pesqueras y definir espacios diferenciados para las embarcaciones de desarrollo turístico y pesca comercial.

**Infraestructura**
Criterio|Definición
--|--|
Agua potable| Acceso a agua potable para la producción de hielo como distancia de 5 Km a localidades urbanas y pesqueras evaluadas con base en el porcentaje de viviendas que disponen de agua entubada.
Electricidad| Distancia a red de transmisión eléctrica.
Vías de comunicación| Distancia a caminos y carreteras para el transporte de insumos y productos.
Comunicaciones| Acceso a comunicación a través de internet y telefonía.

**Comunicaciones**
Criterio|Definición
--|--
Internet| Distancia de 5 Km a localidades urbanas y pesqueras evaluadas con base en el porcentaje de viviendas con internet.
Telefonía| Distancia de 5 Km a localidades urbanas y pesqueras evaluadas con base en el porcentaje de viviendas con celular.

**Socioeconómicos**

Criterio|Definición
--|--|
Localidades pesqueras| Distancia a localidades con comunidades pesqueras: Celestún, Sisal, Chuburná, Yucalpetén, Progreso, Telchac, Chabihau, Dzilam de Bravo, San Felipe, Río Lagartos, Las Coloradas, El Cuyo, Chelem, Chicxulub, Santa Clara y San Crisanto.
Centros de distribución| Distancia a localidades consideradas como puntos de distribución de productos pesqueros: Progreso, Mérida, Valladolid, Tizimín, Hunucmá, Motul y Dzilam González.

**Comment by TatianaMerino** [comment]
@vichdzgeo 
Tablas para análisis de sensibilidad:

- sensibilidad_ acuacultura_salada.csv
- sensibilidad_ acuacultura_dulce.csv
- sensibilidad_ pesca.csv

**Comment by CorinaCantero** [comment]
AVISO
@Nayita 

Por favor agregar lo siguiente al informe: 

- [ ] mapa_fv_pes_infra_d_loc_urb_pes_acceso_agua
- [ ] mapa_fv_pes_infra_loc_urb_pes_internet
- [ ] mapa_fv_pes_infra_loc_urb_pes_celular
- [ ] mapa_fv_pes_infra_d_carreteras_caminos
- [ ] mapa_fv_pes_infra_d_lineas_electricas
- [ ] mapa_fv_pes_socio_d_centros_distribucion_pesca
- [ ] mapa_fv_pes_socio_d_localidades_pesca
- [ ] fi_fv_pes_infra_d_carreteras_caminos
- [ ] fi_fv_pes_infra_d_loc_urb_pes_acceso_agua
- [ ] fi_fv_pes_infra_loc_urb_pes_celular
- [ ] fi_fv_pes_infra_loc_urb_pes_internet
- [ ] fi_fv_pes_infra_d_lineas_electricas
- [ ] fi_fv_pes_socio_d_centros_distribucion_pesca
- [ ] fi_fv_pes_socio_d_localidades_pesca

**Comment by CorinaCantero** [comment]
### **TABLAS DE PESOS GLOBALES**
@Nayita 

**Acuacultura salobre**
Criterio | Peso
-- | --
Electricidad | 0.394
Acceso a agua | 0.320
Salinidad | 0.104
Tenencia | 0.100
Vías de comunicación | 0.056
Vegetación | 0.027

**Acuacultura dulce**

Criterio | Peso
-- | --
Electricidad | 0.394
Acceso a agua | 0.320
Salinidad | 0.104
Tenencia | 0.100
Vías de comunicación | 0.056
Vegetación | 0.027

**Pesca**

Criterio | Peso
-- | --
Agua potable | 0.344
Electricidad | 0.241
Vías de comunicación | 0.155
Centros de distribución | 0.096
Internet | 0.088
Telefonía | 0.046
Localidades pesqueras | 0.024

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@TatianaMerino @CorinaCantero @vichdzgeo 

Favor de revisar el informe en html o en la página una vez que se actualice para verificar lo que falta

@vichdzgeo 

- [ ] Favor de publicar

**Comment by vichdzgeo** [comment]
## Áreas por categorías de aptitud para acuacultura de agua dulce 


Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 12799.3 | 32
Alta | 10082.1 | 26
Moderada | 9986.9 | 25
Baja | 3798.8 | 10
Muy baja | 1513.2 | 4
Nula | 1356.4 | 3

## Mapa de aptitud y exclusión para acuacultura dulce 
ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\pesca\aptitud

> El mapa de aptitud es equidistante

- **aptitud**: acuadul_acuacultura_dulce.tif
- **exclusion**: acuadul_acuacultura_dulce_exclusion.tif

### Exclusión 

Categorías clasificadas como nulas en la capa de uso de suelo y vegetación del mapa de aptitud. 
ruta: talleres/sectores/pesca/funciones_valor/tabla_fv_acuadul_bio_cobertura_usv_svi_16cats.csv'
@CorinaCantero  @Nayita

**Comment by vichdzgeo** [comment]
## Áreas por categorías de aptitud para acuacultura de agua salobre

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 5862.3 | 15
Alta | 15606.0 | 39
Moderada | 12540.4 | 32
Baja | 3369.2 | 9
Muy baja | 802.3 | 2
Nula | 1356.4 | 3

### Mapa de aptitud y exclusión para acuacultura dulce
ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\pesca\aptitud

El mapa de aptitud es equidistante

**aptitud**: acuasal_acuacultura_salobre.tif

**exclusion**: acuasal_acuacultura_salobre_exclusion.tif

Figura de sensibilidad: fi_analisis_sensibilidad_acuacultura_salobre.png

Exclusión
Categorías clasificadas como nulas en la capa de uso de suelo y vegetación del mapa de aptitud.
ruta: talleres/sectores/pesca/funciones_valor/tabla_fv_acuasal_bio_cobertura_usv_svi_16cats.csv

@Nayita @CorinaCantero

**Comment by vichdzgeo** [comment]
## Áreas por categorías de aptitud para pesca


Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 6053.6 | 15
Alta | 3647.7 | 9
Moderada | 2897.9 | 7
Baja | 12808.6 | 32
Muy baja | 3390.7 | 9
Nula | 10738.1 | 27



### Mapa de aptitud y exclusión para pesca
ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\pesca\aptitud

El mapa de aptitud es equidistante

**aptitud**: pes_pesca.tif

**exclusion**: pes_pesca_exclusion.tif

Figura de sensibilidad: fi_analisis_sensibilidad_pesca.png

Exclusión
distancia mayor a 100 km a partir de la línea de costa se considera como zona de exclusión.
@Nayita @CorinaCantero

**Comment by CorinaCantero** [comment]
AVISO
@Nayita 

Por favor agregar lo siguiente al informe:

- [ ] mapa_aptitud_acuadul
- [ ] mapa_aptitud_acuasal
- [ ] mapa_aptitud_pes
- [ ] mapa_ex_acuadul
- [ ] mapa_ex_acuasal
- [ ] mapa_ex_pes
- [ ] Tabla de insumos para mapa de exclusión de acuacultura salobre y dulce: 

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

- [ ] Para exclusión de pesca poner lo siguiente: 
Se considera como exclusión la distancia mayor a 100 km a partir de la línea de costa

Capa | Distancia a la línea de costa
-- | --
Fuente | Adaptado de: División política municipal INEGI
Año | 2018
Escala | 1:250,000
Unidades | Kilómetros


- [ ] Tabla ID y categorías de exclusión para acuacultura dulce y salobre: 

ID | Categoría
-- | --
4 | Asentamiento humano
6 | Cuerpo de agua
14 | Vegetación de duna costera
15 | Vegetación de petén
16 | Vegetación halófila hidrófila
17 | ND

**Comment by ofegarcia** [comment]
### AVISO
@Nayita

Se incluyó la **lista de asistencia** a los talleres de aptitud.
Archivo: fmx_estudio_tecnico/diagnostico/talleres/sectores/pesca/lista_asistencia_pesca.pdf

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones

@vichdzgeo 

- [ ] Favor de publicar

@TatianaMerino @dpedroza74 

- [ ] Favor de revisar para vo. bo.

**Comment by dpedroza74** [comment]
@TatianaMerino ver con @Nayita y @vichdzgeo correcciones en el mapa de aptitud de pesca y subir el  de acuacultura de agua salobre 

@Nayita las correcciones de forma que veo en el informe de pesca son estas:

Cambiar **Km** por **km** en todas las definiciones de Agua potable, Internet, Telefonía

Dice: Función de valor de centros de localidades pesqueras
Debe decir: Función de valor de localidades pesqueras

1.2.2.2 Centros de distribución
En la tabla el nombre de la capa 
Dice: Distancia a localidades con centros de distribución pesquera
Debe decir: Distancia a localidades con centros de distribución de productos pesqueros

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

- [ ] Atendiendo las correcciones, favor de cambiar la tabla de insumos de pesca 1.2.2.2 Centros de distribución por la siguiente: 

Capa | Distancia a localidades con centros de   distribución de productos pesqueros
-- | --
Fuente | Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI
Año | 2020
Escala | Sin dato
Unidades | Kilómetros

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe.

@vichdzgeo 

- [ ] Favor de publicar

@dpedroza74 

- [ ]  Favor de dar vo. bo

**Comment by paola-gp** [comment]
@CorinaCantero 

- [ ] Se actualiza capa de cobertura de acuaculturas, subir capa actualizada a SIGfunctionD

**Comment by CorinaCantero** [comment]
### **AVISO**
@vichdzgeo 

Listas las capas evaluadas y exportadas de cobertura (corregida con capa de manglares) para acuacultura de agua dulce y de agua salada
FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\pesca\funciones_valor

- fv_acuasal_bio_cobertura_usv_svi_16cats_costa_manglar
- fv_acuadul_bio_cobertura_usv_svi_16cats_costa_manglar

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor actualizar las siguientes tablas de insumos del informe: 

- [ ] Cobertura de acuacultura de agua dulce y salada

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Tabla de exclusión para acuacultura dulce y salada

Campo | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Factores de progresión para los mapas de aptitud

> Modo de clasificación **Progresiva**

- Acuacultura de agua dulce  FP= 1.30
- Acuacultura de agua salobre  FP = 1.30
- Pesca FP = 1.80

**Comment by vichdzgeo** [comment]
## Actualizaciones 

Listas las actualizaciones para los mapas de aptitud y tablas de categorías de aptitud

- [ ] Actualizar las figuras de los mapas de aptitud para las dos Acuaculturas @CorinaCantero 
- [ ] Actualizar las figuras de los mapas de exclusión para las dos Acuaculturas @CorinaCantero 
- [ ] Actualizar las tablas de categorías de aptitud para las dos acuaculturas en Sphinx  @Nayita

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Haciendo los metadatos se detectaron los siguientes errores, favor de corregir en el informe:

- [ ] Agregar la figura de la gráfica 1.2.1.2 Salinidad del subsector acuacultura salobre "fi_fv_acuasal_bio_espesor_agua_salada"
- [ ] La figura de la gráfica en la sección 1.2.2.2 Vías de comunicación del subsector acuacultura salobre, está mal (se puso la de distancia a líneas eléctricas en lugar de distancia a carreteras y caminos), la correcta es: fi_fv_acuasal_infra_d_carreteras_caminos
- [ ] En la sección 2.2.1.2 Salinidad de acuacultura dulce, dice "FV de acceso a agua" pero debe decir "FV de salinidad"

**Comment by vichdzgeo** [comment]
## Corrección

### Reescalar los mapas normalizados (integrados) para poderlos comparar respecto al factor de progresión seleccionado en los talleres

### Acuacultura Dulce y Acuacultura salada

#### Procedimiento

Para un factor de progresión de 1.3 en clasificación progresiva el corte detectado es en el valor c = 0.684
la ecuación utilizada es 
`"(A>0.684)*1+(A<=0.684)*(A/0.684)"`

- Se aplica de nuevo la capa de exclusión
- Se reemplaza el mapa en entregables

### pesca

#### Procedimiento

Para un factor de progresión de 1.8 en clasificación progresiva el corte detectado es en el valor c = 0.531
la ecuación utilizada es 
`"(A>0.531)*1+(A<=0.531)*(A/0.531)"`

- Se aplica de nuevo la capa de exclusión
- Se reemplaza el mapa en entregables

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
