### ISSUE TITLE
Integrar informe del análisis de aptitud del sector minería #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#83]
## **[SECTOR MINERO ](https://lancis-apc.github.io/fomix/mineria_pr.html)**

[Lizmap del sector Minería](http://sig.apps.lancis.ecologia.unam.mx/index.php/view/map/?repository=mineria&project=mineria)

**Comment by vichdzgeo** [comment]
```
CartoMinMex
https://portalags1.economia.gob.mx/arcgis/apps/webappviewer/index.html?id=1f22ba130b0e40d888bfc3b7fb5d3b1b
Concesiones mineras 
Propuestas en trámite

GeoInfoMex SGM
https://www.sgm.gob.mx/GeoInfoMexGobMx/
Yacimientos minerales -minas
Rocas dimensionables
Empresas mineras
```

**Comment by TatianaMerino** [comment]
#  Insumos de sesión 2

## Modelo terminado

Archivo: **min_05mar2021.sdmod**

## Definiciones en orden de pesos

Meta
--|
Aumentar la apertura de bancos de materiales para cumplir con la demanda de productos químicos, alimentación, así como de insumos en la construcción, en particular de desarrollos inmobiliarios, caminos y carreteras, que están en aumento por el crecimiento poblacional y la llegada de proyectos como el Tren Maya. 

**Biofísicos**

Criterio|Definición
--|--|
Nivel freático| Distancia al manto acuífero medido por el nivel piezométrico.
Tipo de cobertura| Tipos de vegetación y usos de suelo.
Tipo de suelo| Edafología. 

**Infraestructura**

Criterio|Definición
--|--|
Caminos| Distancia a caminos, senderos y carreteras.
Electricidad| Distancia a red eléctrica.
Minas| Distancia a sitios de explotación de minerales y salinos.

**Socioeconómicos**

Criterio|Definición
--|--|
Localidades| Distancia a localidades donde existe mayor demanda de materiales: Mérida y zonas conurbadas, Tizimín, Progreso, Valladolid e Izamal.
Oportunidades| Caminos-trazos planeados a construir y ampliar (por ejemplo: Carretera Mérida-Chetumal).

## Asistencia
@Nayita 
Entraron Lorena Pat y  Francisco Gordillo Triturados Sarzo S A

**Comment by CorinaCantero** [comment]
### Preparación de insumos geográficos -SIG

**Biofísicos**

- [ ] Nivel freático 
- [ ] Tipo de cobertura 
- [ ] Tipo de suelo 

**Infraestructura**

- [ ] Distancia a caminos y carreteras
- [ ] Distancia a red de transmisión eléctrica
Opción 1: capa de INEGI (contiene más elementos)
Opción 2: capa de Geocomunes (se puede diferenciar por tipo de voltaje)
- [ ] Distancia a minas
Opciones: Banco de materiales, rocas dimensionables, concesiones mineras

**Socioeconómicos**

- [ ] Distancia a localidades: Mérida y zona conurbada, Tizimín, Progreso, Valladolid e Izamal ---->
- [ ] Oportunidades

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

@vichdzgeo 

- [ ] Favor de publicar

**Comment by TatianaMerino** [comment]
Como resultado de la 3ra sesión del taller de minería, saldrán 4 mapas de aptitud:

1. Minería de arcillas
2. Minería de arenas
3. Minería de rocas con extracción en seco
4. Minería de rocas con extracción en húmedo

## Definiciones

Meta
--|
Aumentar la apertura de bancos de materiales para cumplir con la demanda de productos químicos, de alimentación, así como de insumos en la construcción, en particular de desarrollos inmobiliarios, caminos y carreteras, que están en aumento por el crecimiento poblacional y la llegada de proyectos como el Tren Maya. 

**Biofísicos**
Criterio|Definición
--|--|
Nivel freático| Distancia al manto acuífero medido por el nivel piezométrico.
Tipo de cobertura| Tipos de vegetación y usos de suelo.
Tipo de suelo| Edafología. 

**Infraestructura**
Criterio|Definición
--|--|
Caminos| Distancia a caminos y carreteras para transporte de los productos.
Electricidad| Distancia a red de transmisión eléctrica. Requerimiento de electricidad para la operación de trituradoras. 
Minas| Distancia a sitios de explotación de yacimientos minerales

**Socioeconómicos**
Criterio|Definición
--|--|
Localidades| Distancia a localidades donde existe mayor demanda de materiales: Mérida y zona conurbada, Tizimín, Progreso, Valladolid e Izamal.
Oportunidades| Proyectos de construcción y ampliación de vías de comunicación.

## Funciones de valor categóricas

ARCILLA**Tipo de suelo**
ID | Categoría | Importancia | FV
-- | -- | -- | --
7 | Luvisol | Muy alta | 1.00
8 | Nitosol | Muy alta | 1.00
2 | Cambisol | Baja | 0.25
6 | Leptosol | Baja | 0.25
10 | Regosol | Baja | 0.25
12 | Vertisol | Baja | 0.25
1 | Arenosol | Nula | 0.00
3 | Chernozem | Nula | 0.00
4 | Gleysol | Nula | 0.00
5 | Histosol | Nula | 0.00
9 | Phaeozem | Nula | 0.00
11 | Solonchak | Nula | 0.00
13 | No aplica | Nula | 0.00

ARENA**Tipo de suelo**
ID | Categoría | Importancia | FV
-- | -- | -- | --
1 | Arenosol | Muy alta | 1.00
10 | Regosol | Moderada | 0.50
11 | Solonchak | Baja | 0.25
2 | Cambisol | Nula | 0.00
3 | Chernozem | Nula | 0.00
4 | Gleysol | Nula | 0.00
5 | Histosol | Nula | 0.00
6 | Leptosol | Nula | 0.00
7 | Luvisol | Nula | 0.00
8 | Nitosol | Nula | 0.00
9 | Phaeozem | Nula | 0.00
12 | Vertisol | Nula | 0.00
13 | No aplica | Nula | 0.00

ROCA**Tipo de suelo**
ID | Categoría | Importancia | FV
-- | -- | -- | --
6 | Leptosol | Muy alta | 1.00
2 | Cambisol | Alta | 0.75
10 | Regosol | Moderada | 0.50
1 | Arenosol | Baja | 0.25
3 | Chernozem | Baja | 0.25
7 | Luvisol | Baja | 0.25
8 | Nitosol | Baja | 0.25
9 | Phaeozem | Baja | 0.25
12 | Vertisol | Baja | 0.25
4 | Gleysol | Nula | 0.00
5 | Histosol | Nula | 0.00
11 | Solonchak | Nula | 0.00
13 | No aplica | Nula | 0.00

**Tipo de cobertura** (para todos los mapas es la misma fv)
ID | Categoría | Importancia | FV
-- | -- | -- | --
11 | Sin vegetación | Muy alta | 1.00
2 | Agricultura de riego | Alta | 0.75
3 | Agricultura de temporal | Alta | 0.75
8 | Pastizal | Alta | 0.75
9 | Selva baja | Alta | 0.75
14 | Vegetación de duna costera | Alta | 0.75
5 | Bosque cultivado/Palmar inducido | Moderada | 0.50
10 | Selva mediana | Moderada | 0.50
12 | Sabana | Baja | 0.25
1 | Acuícola | Nula | 0.00
4 | Asentamiento humano | Nula | 0.00
6 | Cuerpo de agua | Nula | 0.00
7 | Manglar | Nula | 0.00
13 | Tular | Nula | 0.00
15 | Vegetación de petén | Nula | 0.00
16 | Vegetación halófila hidrófila | Nula | 0.00
17 | ND | Nula | 0.00

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 
Por favor agregar lo siguiente al informe: 

**Minería de arcillas**
- [ ] mapa_fv_min_arci_socio_d_localidades_min
- [ ] fi_fv_min_arci_socio_d_localidades_min
- [ ] fi_fv_min_arci_infra_rocas_banco_materiales
- [ ] mapa_fv_min_arci_infra_rocas_banco_materiales
- [ ] fi_fv_min_arci_infra_d_lineas_electricas
- [ ] mapa_fv_min_arci_infra_d_lineas_electricas
- [ ] mapa_fv_min_arci_infra_d_carreteras_caminos
- [ ] fi_fv_min_arci_infra_d_carreteras_caminos
- [ ] mapa_fv_min_arci_bio_tipo_suelo
- [ ] mapa_fv_min_arci_bio_d_manto_freatico
- [ ] fi_fv_min_arci_bio_d_manto_freatico
- [ ] mapa_fv_min_arci_bio_cobertura_usv_svi_16cats

**Minería de arena**

- [ ] mapa_fv_min_arena_bio_cobertura_usv_svi_16cats
- [ ] mapa_fv_min_arena_bio_tipo_suelo
- [ ] mapa_fv_min_arena_bio_d_manto_freatico
- [ ] mapa_fv_min__arena_infra_d_carreteras_caminos
- [ ] mapa_fv_min_arena_infra_d_lineas_electricas
- [ ] mapa_fv_min_arena_infra_rocas_banco_materiales
- [ ] mapa_fv_min_arena_socio_d_localidades_min
- [ ] fi_fv_min_arena_bio_d_manto_freatico 
- [ ] fi_fv_min_arena_infra_d_carreteras_caminos
- [ ] fi_fv_min_arena_infra_d_lineas_electricas
- [ ] fi_fv_min_arena_infra_rocas_banco_materiales
- [ ] fi_fv_min_arena_socio_d_localidades_min

**Minería roca seca**

**Comment by CorinaCantero** [comment]
### **TABLAS DE INSUMOS**
@Nayita 

Por favor agregar al informe (los insumos son los mismos para todos los mapas de mineria (arcillas, arena, roca seca y roca húmeda):

**Biofísicos**

- [ ] Nivel freático

Capa | Nivel freático
-- | --
Fuente | Nivel freático POETY
Año | Sin dato
Campo | n_freat_m
Escala | Estatal
Unidades | Metros

- [ ] Cobertura

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

- [ ] Suelo

Capa | Edafología
-- | --
Fuente | Conjunto de datos vectoriales edafológico. Serie II (Continuo Nacional)   INEGI
Año | 2014
Campo | tipo_suelo
Escala | 1:250,000
Unidades | Adimensional


**Infraestructura**

- [ ] Distancia a caminos 

Capa | Distancia a la red vial
-- | --
Fuente | Red Nacional de Caminos (RNC) Red vial - INEGI
Año | 2019
Escala | Sin dato
Unidades | Kilómetros

- [ ] Distancia a sitios   de extracción de minerales y salinos
- [ ] Distancia a red eléctrica

Capa | Distancia líneas de transmisión de energía   eléctrica
-- | --
Fuente | Líneas de transmisión INEGI
Año | 2012
Escala | 1:50,000
Unidades | Kilómetros

**Socioeconómicos**

- [ ] Distancia localidades con centros de   distribución

Capa | Distancia a localidades de mayor demanda de   material minero
-- | --
Fuente | Polígonos de localidades. Marco Geoestadístico. Censo de Población y   Vivienda INEGI
Año | 2020
Escala | Sin dato
Unidades | Kilómetros


- [ ] Oportunidades de proyectos y   carreteras nuevas
**Pendiente**

**Comment by Nayita** [comment]
### AVISO

Listas las actualizaciones del informe

@vichdzgeo 

- [ ] Favor de publicar

**Comment by TatianaMerino** [comment]
AVISO
@CorinaCantero @vichdzgeo 
- El archivo prefijos_sector_mineria.xlsx tiene en las pestañas (hojas) los 4 mapas correspondientes a los 4 tipos de minería. 

- Temporalmente se eliminó el criterio "Oportunidades" hasta que se tena la capa correspondiente. 
El archivo para generar los mapas de aptitud sin este criterio es **prefijos_sector_mineria_v2.xlsx**

**Comment by TatianaMerino** [comment]
# Actualizaciones de insumos
Se hizo un modelo con mismos criterios pero diferentes pesos para arcilla y arena. 

## Arcilla y Arena
Modelo: min_arci_arena_12mar2021.sdmod

## Definiciones
**Biofísicos**
Criterio|Definición
--|--|
Tipo de suelo| Edafología. 
Nivel freático| Distancia al manto acuífero medido por el nivel piezométrico.
Tipo de cobertura| Tipos de vegetación y usos de suelo.

**Infraestructura**
Criterio|Definición
--|--|
Caminos| Distancia a caminos y carreteras para transporte de los productos.
Electricidad| Distancia a red de transmisión eléctrica. Requerimiento de electricidad para la operación de trituradoras. 
Minas| Distancia a sitios de explotación de yacimientos minerales

**Socioeconómicos**
Criterio|Definición
--|--|
Localidades| Distancia a localidades donde existe mayor demanda de materiales: Mérida y zona conurbada, Tizimín, Progreso, Valladolid e Izamal.
Oportunidades| Proyectos de construcción y ampliación de vías de comunicación.

## Roca con extracción en seco y en húmedo
Modelo: min_rohum_rosec_12mar2021.sdmod
(no hay cambios)

## Prefijos
prefijos_mineria_v3.xlsx (sin capa de Oportunidades)

## Mapas de aptitud
Factor de progresión elegido: 

- roca extr en seco: 1.3
- roca extr en húmedo: equidistante
- arcillas:1.2
- arena:1.5

**Comment by TatianaMerino** [comment]
@vichdzgeo
Tablas para análisis de sensibilidad:

- sensibilidad_mineria_roca_hum.csv
- sensibilidad_mineria_roca_seca.csv
- sensibilidad_mineria_arcilla.csv
- sensibilidad_mineria_arena.csv

Nota: se construyeron con la normalización sin la capa de Oportunidades.

**Comment by vichdzgeo** [comment]
## fp para cada mapa de aptitud

roca extr en seco: 1.3
roca extr en humedo: equidistante
arcillas:1.2
arena:1.5

**Comment by TatianaMerino** [comment]
## Acuerdos para informe

- Permanecen como "tipos" las clasificaciones en las que se dividió el sector minería
- Un sólo diagrama será utilizado para todos los tipos, únicamente se hará diferencia de pesos correspondientes de arcilla/arena y roca húmeda/seca
- Las definiciones de los tipo de minería resultan innecesarias debido a que se tiene una única meta y sector
- El atributo Oportunidades no se consideró por falta de la capa correspondiente. Además, el hecho de que tanto Oportunidades como Localidades tengan el mismo peso de importancia relativa (0.5) significa que no se puede distinguir entre estos dos atributos. Por lo tanto, Localidades es suficiente para representar los atributos socioeconómicos.

**Comment by ofegarcia** [comment]
### AVISO
@Nayita 

Se incluyó la **lista de asistencia** a los talleres de aptitud.
Archivo:  fmx_estudio_tecnico/diagnostico/talleres/sectores/mineria/lista_asistencia_mineria.pdf

**Comment by vichdzgeo** [comment]
## Áreas por categoría de aptitud Arcilla

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 2003.2 | 5
Alta | 14019.6 | 35
Moderada | 15223.6 | 39
Baja | 5674.9 | 14
Muy baja | 189.3 | 0
Nula | 2426.0 | 6

## Áreas por categoría de aptitud Arenas

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 2208.4 | 6
Alta | 18923.7 | 48
Moderada | 13549.8 | 34
Baja | 2411.8 | 6
Muy baja | 16.9 | 0
Nula | 2426.0 | 6



## Áreas por categoría de aptitud Rocas húmedas

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 13851.9 | 35
Alta | 12137.3 | 31
Moderada | 1897.6 | 5
Baja | 5476.0 | 14
Muy baja | 3747.8 | 9
Nula | 2426.0 | 6

## Áreas por categoría de aptitud Rocas secas

Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 5777.1 | 15
Alta | 14206.0 | 36
Moderada | 13048.0 | 33
Baja | 4038.6 | 10
Muy baja | 40.9 | 0
Nula | 2426.0 | 6

## Mapas de aptitud
Ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\mineria\aptitud

- **Arcillas** : min_arcilla.tif
- **Arena**: min_arena.tif
- - **Rocas extracción húmeda**: min_rocas_humedas.tif
- **Rocas extracción en seco**: min_rocas_secas.tif

## Mapas de exclusión

- **Arcillas** : min_arcilla_exclusion.tif
- **Arena**: min_arena_exclusion.tif
- - **Rocas extracción húmeda**: min_rocas_humedas_exclusion.tif
- **Rocas extracción en seco**: min_rocas_secas_exclusion.tif

## Figuras de sensibilidad 
- fi_analisis_sensibilidad_mineria_arcilla.png
- fi_analisis_sensibilidad_mineria_arena.png
- fi_analisis_sensibilidad_mineria_rocas_humedas.png
- fi_analisis_sensibilidad_mineria_rocas_secas.png

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor agregar lo siguiente al informe: 

- [ ] Tabla de insumos para mapa de exclusión (para todos los tipos de minería)

Capa | Uso del suelo y vegetación
-- | --
Fuente | Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación.   Serie VI. Conjunto Nacional INEGI
Año | 2017
Campo | descripcio
Escala | 1:250,000
Unidades | Adimensional

- [ ] Tabla ID, categoría para exclusión (para todos los tipos de minería)

ID | Categoría
-- | --
1 | Acuícola
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
15 | Vegetación de petén
16 | Vegetación halófila hidrófila
17 | ND

- [ ] mapa_exclusion (este mapa es para los cuatro tipos de minería) 
- [ ] mapa_aptitud_min_arcilla
- [ ] mapa_aptitud_min_arena
- [ ] mapa_aptitud_min_rohum
- [ ] mapa_aptitud_min_rosec

**Comment by CorinaCantero** [comment]
### **TABLAS DE PESOS GLOBALES**
@Nayita 

- [ ] **Minería de arcilla**

Criterio | Peso
-- | --
Tipo de suelo | 0.335
Nivel freático | 0.223
Localidades | 0.140
Caminos | 0.107
Electricidad | 0.092
Tipo de cobertura | 0.062
Minas | 0.040

- [ ] **Minería de arena**

Criterio | Peso
-- | --
Tipo de suelo | 0.335
Nivel freático | 0.223
Localidades | 0.140
Caminos | 0.107
Electricidad | 0.092
Tipo de cobertura | 0.062
Minas | 0.040

- [ ] **Minería de rocas húmedas** 

Criterio | Peso
-- | --
Nivel freático | 0.387
Tipo de suelo | 0.174
Localidades | 0.140
Caminos | 0.107
Electricidad | 0.092
Tipo de cobertura | 0.058
Minas | 0.040

- [ ] **Minería de rocas secas**

Criterio | Peso
-- | --
Nivel freático | 0.387
Tipo de suelo | 0.174
Localidades | 0.140
Caminos | 0.107
Electricidad | 0.092
Tipo de cobertura | 0.058
Minas | 0.040

**Comment by Nayita** [comment]
### AVISO 

Listas las actualizaciones del informe

@vichdzgeo 

- [ ] Favor de publicar

@dpedroza74 @TatianaMerino 

- [ ] Favor de revisar html o publicación en la página para vo. bo.

**Comment by paola-gp** [comment]
@CorinaCantero 

- [ ] Se actualiza capa de cobertura, subir capa actualizada a SIGfunctionD

**Comment by CorinaCantero** [comment]
@vichdzgeo 

Listas las capas evaluadas y exportadas de cobertura (corregida con capa de manglares) para los cuatro tipos de minería. 
 FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\mineria\funciones_valor

**Comment by vichdzgeo** [comment]
## Actualizaciones 

- [ ] Mapas de aptitud actualizados con la capa de cobertura corregida @CorinaCantero  
- [ ] Mapas de exclusión actualizados @CorinaCantero  
- [ ] Tablas de áreas de categorías por aptitud actualizadas @Nayita

**Comment by vichdzgeo** [comment]
> ## Áreas por categoría de aptitud Arcilla
> Categoría	km²	Porcentaje del estado
> Muy alta	2003.2	5
> Alta	14016.7	35
> Moderada	15176.6	38
> Baja	5498.1	14
> Muy baja	167.0	0
> Nula	2675.1	7
> ## Áreas por categoría de aptitud Arenas
> Categoría	km²	Porcentaje del estado
> Muy alta	2187.8	6
> Alta	18839.3	48
> Moderada	13463.7	34
> Baja	2354.2	6
> Muy baja	16.5	0
> Nula	2675.1	7
> ## Áreas por categoría de aptitud Rocas húmedas
> Categoría	km²	Porcentaje del estado
> Muy alta	13845.2	35
> Alta	12028.8	30
> Moderada	1763.9	4
> Baja	5475.8	14
> Muy baja	3747.8	9
> Nula	2675.1	7
> ## Áreas por categoría de aptitud Rocas secas
> Categoría	km²	Porcentaje del estado
> Muy alta	5777.1	15
> Alta	14199.3	36
> Moderada	12942.3	33
> Baja	3915.3	10
> Muy baja	27.6	0
> Nula	2675.1	7
> ## Mapas de aptitud
> Ruta: FOMIX\fmx_estudio_tecnico\diagnostico\talleres\sectores\mineria\aptitud
> 
> * **Arcillas** : min_arcilla.tif
> * **Arena**: min_arena.tif
> * * **Rocas extracción húmeda**: min_rocas_humedas.tif
> * **Rocas extracción en seco**: min_rocas_secas.tif
> 
> ## Mapas de exclusión
> * **Arcillas** : min_arcilla_exclusion.tif
> * **Arena**: min_arena_exclusion.tif
> * * **Rocas extracción húmeda**: min_rocas_humedas_exclusion.tif
> * **Rocas extracción en seco**: min_rocas_secas_exclusion.tif
> 
> tabla de categorías de exclusión de USV serie VI
> 
> id	categoria
> 1	Acuícola
> 4	Asentamiento humano
> 6	Cuerpo de agua
> 7	Manglar
> 13	Tular
> 15	Vegetación de petén
> 16	Vegetación halófila hidrófila
> 17	ND
> ## Figuras de sensibilidad
> * fi_analisis_sensibilidad_mineria_arcilla.png
> * fi_analisis_sensibilidad_mineria_arena.png
> * fi_analisis_sensibilidad_mineria_rocas_humedas.png
> * fi_analisis_sensibilidad_mineria_rocas_secas.png
>   @CorinaCantero @Nayita

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Por favor hacer las siguientes actualizaciones a las tablas de insumos del informe: 

- [ ] Cobertura para minería de arcillas, arenas, rocas secas y rocas húmedas


Capa | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Exclusión para los 4 tipos de minería

Capa | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y   vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y   vegetación de la zona costera asociada a los manglares, Región Península de   Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

**Comment by vichdzgeo** [comment]
## Integración de mapas y Producto final

## Insumos
- min_roca_seca_sigindex.tif w= 0.25
- min_roca_humeda_sigindex.tif w= 0.25
- min_arena_sigindex.tif w= 0.25
- min_arcilla_sigindex.tif w= 0.25
- min_rocas_secas_exclusion.tif
- min_rocas_humedas_exclusion.tif
- min_arena_exclusion.tif
- min_arcilla_exclusion.tif

#### productos

- mineria.tif (capa categorizada)
- mineria_integrado.tif (capa normalizada entre 0 y 1, resultado de la integración y agregando las zonas de exclusión con 0.0)
- minera_exclusion.tif 



Categoría | km² | Porcentaje del   estado
-- | --: | --:
Muy alta | 2001.0 | 5
Alta | 15047.7 | 38
Moderada | 10426.0 | 26
Baja | 9088.6 | 23
Muy baja | 297.5 | 1
Nula | 2675.8 | 7

- [ ] integrar tabla de categorias al informe @Nayita 
- [ ] generar las figuras de los mapas @CorinaCantero

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Listo el mapa de aptitud integrado y el mapa de exclusión para el sector minería: 

- [ ] mapa_aptitud_mineria
- [ ] mapa_exclusion_mineria

**Comment by CorinaCantero** [comment]
### PESOS GLOBALES DEL MAPA DE APTITUD INTEGRADO DEL SECTOR MINERÍA
@Nayita 

- [ ] Favor de agregar en el informe


Tipo de minería | Criterio | Peso
-- | -- | --
Arcillas | Minas | 0.010
Arcillas | Tipo de cobertura | 0.015
Arcillas | Electricidad | 0.023
Arcillas | Caminos | 0.027
Arcillas | Localidades | 0.035
Arcillas | Nivel freático | 0.058
Arcillas | Tipo de suelo | 0.084
Arenas | Tipo de cobertura | 0.016
Arenas | Tipo de cobertura | 0.016
Arenas | Electricidad | 0.023
Arenas | Caminos | 0.027
Arenas | Localidades | 0.035
Arenas | Nivel freático | 0.056
Arenas | Tipo de suelo | 0.084
Rocas con extracción en húmedo | Tipo de cobertura | 0.015
Rocas con extracción en húmedo | Electricidad | 0.023
Rocas con extracción en húmedo | Caminos | 0.027
Rocas con extracción en húmedo | Localidades | 0.035
Rocas con extracción en húmedo | Tipo de suelo | 0.044
Rocas con extracción en húmedo | Nivel freático | 0.097
Rocas con extracción en húmedo | Minas | 0.020
Rocas con extracción en seco | Electricidad | 0.023
Rocas con extracción en seco | Caminos | 0.027
Rocas con extracción en seco | Localidades | 0.035
Rocas con extracción en seco | Tipo de suelo | 0.044
Rocas con extracción en seco | Nivel freático | 0.097
Rocas con extracción en seco | Tipo de cobertura | 0.029
Rocas con extracción en seco | Minas | 0.020

**Comment by CorinaCantero** [comment]
### Correcciones
@Nayita 

- [ ] En las secciones 1.2.1.1.2, 1.2.2.1.2, 1.2.3.1.1 y 1.2.4.1.1 Nivel freático,  cambiar el Año de "sin dato" a **2007**
- [ ] En la sección 1.2.3.3 y 1.2.4.3 Socioeconómicos quitar de la tabla de criterios "Oportunidades", solo se queda Localidades

**Comment by CorinaCantero** [comment]
### AVISO
@Nayita 

Favor de agregar lo siguiente al informe. 
**Mapa de aptitud integrado - Zonas de exclusión**

- [ ] Tabla de insumos

Capa | Uso del suelo y vegetación
-- | --
Fuente | [1] Conjunto de datos vectoriales de la carta de Uso del suelo y vegetación. Serie VI. Conjunto Nacional INEGI y [2] Mapa de uso del suelo y vegetación de la zona costera asociada a los manglares, Región Península de Yucatán CONABIO
Año | [1] 2017; [2] 2021
Campo | [1] descripcio; [2] Descrip
Escala | [1] 1:250,000; [2] 1:50,000
Unidades | Adimensional

- [ ] Tabla ID/categoría

ID | Categoría
-- | --
1 | Acuícola
4 | Asentamiento humano
6 | Cuerpo de agua
7 | Manglar
13 | Tular
15 | Vegetación de petén
16 | Vegetación halófila hidrófila
17 | ND

**Comment by Nayita** [comment]
Diagrama de modelo de decisión del mapa de aptitud integrado

![fi_mineria_integrado](https://user-images.githubusercontent.com/25210323/120392257-da4a2380-c2f5-11eb-9b4a-5f9209cde9d9.png)

**Comment by Nayita** [comment]
@CorinaCantero 

Favor de sustituir el diagrama integrado, una vez que esté publicado, en el metadato correspondiente.

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
