### ISSUE TITLE
Hacer metadatos de insumos e información geográfica generada en los talleres sectoriales #FOMIX

### ISSUE THREAD

**Issue by CorinaCantero** [lancis-apc/fomix#86]
### Insumos y plantillas para generar los metadatos de los insumos e información geográfica generada en los talleres sectoriales FOMIX:
@Nayita 

Para crear los metadatos de las FV se utilizan los siguientes archivos (Descargarlos) : 

Ubicación: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\metadatos

- plantilla_fv: plantilla para llenar según el tipo de función de valor continua y sus parámetros
- machote_medatados: textos para editar según el tipo de metadato a generar

Liga Geonetwork en donde se crearán los metadatos: http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search;jsessionid=12E80C565C17BA2584FC289F57D5EC27?node=srv#/home

### **Tareas**

- [ ] Metadato máscara municipios utilizada para rasterizar SIG\desarrollo\sig_fomix\entregables\mascara_municipios_2018

**Comment by CorinaCantero** [comment]
### **Tareas**

- [ ] Metadato máscara municipios utilizada para rasterizar SIG\desarrollo\sig_fomix\entregables\mascara_municipios_2018

**Comment by CorinaCantero** [comment]
### **Tareas**

- [ ] Metadato máscara municipios utilizada para rasterizar SIG\desarrollo\sig_fomix\entregables\mascara_municipios_2018

**Comment by CorinaCantero** [comment]
### **MAPAS DE APTITUD**

Sector | Mapa de aptitud
-- | --
Acuacultura | Acuacultura salobre
Acuacultura | Acuacultura dulce
Agricultura | Agricultura tecnificada de riego
Agricultura | Agricultura tecnificada de temporal
Conservación | Servicios ambientales de soporte
Conservación | Servicios ambientales de regulación
Conservación | Servicios ambientales de provisión
Conservación | Servicios ambientales culturales
Conservación | Funcionalidad ecosistémica
Conservación | Conservación - integrado
Energía | Fuente hidrocarburos líquidos
Energía | Fuente gas natural
Energía | Energía solar
Energía | Energía eólica
Energía | Energía de fuente biomasa
Energía | Energía industrial - integrado
Forestal | Forestal maderable
Forestal | Forestal no maderable
Industrial | Industria ligera
Industrial | Industria mediana y pesada
Milpa maya y apicultura | Milpa maya
Milpa maya y apicultura | Apicultura
Minería | Minería de arcillas
Minería | Minería de arenas
Minería | Mineria de rocas con extracción en seco
Minería | Minería de rocas con extracción en húmedo
Pecuario bovino | Pecuario bovino
Pecuario bovino | Pecuario silvopastoril
Pecuario porcino y   avícola | Pecuario porcino y avícola
Pesca | Pesca
Turismo | Turismo cultural
Turismo | Turismo de naturaleza
Turismo | Turismo de sol y playa
Turismo | Turismo urbano
Turismo | Turismo de cruceros
Turismo | Turismo - integrado
Urbano | Urbano

**Comment by CorinaCantero** [comment]
### **MAPAS DE APTITUD (37)**

- [ ] Acuacultura | Acuacultura salobre
- [ ] Acuacultura | Acuacultura dulce
- [ ] Agricultura | Agricultura tecnificada de riego
- [ ] Agricultura | Agricultura tecnificada de temporal
- [ ] Conservación | Servicios ambientales de soporte
- [ ] Conservación | Servicios ambientales de regulación
- [ ] Conservación | Servicios ambientales de provisión
- [ ] Conservación | Servicios ambientales culturales
- [ ] Conservación | Funcionalidad ecosistémica
- [ ] Conservación | Conservación - integrado
- [ ] Energía | Fuente hidrocarburos líquidos
- [ ] Energía | Fuente gas natural
- [ ] Energía | Energía solar
- [ ] Energía | Energía eólica
- [ ] Energía | Energía de fuente biomasa
- [ ] Energía | Energía industrial - integrado
- [ ] Forestal | Forestal maderable
- [ ] Forestal | Forestal no maderable
- [ ] Industrial | Industria ligera
- [ ] Industrial | Industria mediana y pesada
- [ ] Milpa maya y apicultura | Milpa maya
- [ ] Milpa maya y apicultura | Apicultura
- [ ] Minería | Minería de arcillas
- [ ] Minería | Minería de arenas
- [ ] Minería | Mineria de rocas con extracción en seco
- [ ] Minería | Minería de rocas con extracción en húmedo
- [ ] Pecuario bovino | Pecuario bovino
- [ ] Pecuario bovino | Pecuario silvopastoril
- [ ] Pecuario porcino y   avícola | Pecuario porcino y avícola
- [ ] Pesca | Pesca
- [ ] Turismo | Turismo cultural
- [ ] Turismo | Turismo de naturaleza
- [ ] Turismo | Turismo de sol y playa
- [ ] Turismo | Turismo urbano
- [ ] Turismo | Turismo de cruceros
- [ ] Turismo | Turismo - integrado
- [ ] Urbano | Urbano

**Comment by vichdzgeo** [comment]
## Tablas de sensibilidad para los mapas de aptitud 

Ruta: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\sensibilidad @CorinaCantero

**Comment by CorinaCantero** [comment]
### **ACUERDOS REUNIÓN 12/04/2021**

Prioridades de metadatos: 
1. Mapas de aptitud
2. Función de valor 
3. Insumo raster para la FV
4. Insumos (pendiente si se harán o no) 

- Por el momento no se harán los metadatos de las funciones de valor con una sensibilidad menor a 0.005 (0.5%)

**Comment by CorinaCantero** [comment]
### **FUNCIONES DE VALOR**

**Acuacultura salobre**

- [ ] Acceso a agua
- [ ] Salinidad
- [ ] Vegetación
- [ ] Electricidad 
- [ ] Vías de comunicación
- [ ] Tenencia

**Acuacultura dulce**

- [ ] Acceso a agua
- [ ] Salinidad
- [ ] Vegetación
- [ ] Electricidad 
- [ ] Vías de comunicación
- [ ] Tenencia

**Agricultura de riego**

- [ ] Hidroagrícola
- [ ] Energía
- [ ] Vías de comunicación
- [ ] Disponibilidad de agua
- [ ] Pendiente 
- [ ] Tipo de suelo
- [ ] Tipo de cobertura
- [ ] Mercados 
- [ ] Mano de obra
- [ ] Tenencia

**Agricultura de temporal**

- [ ] Precipitación
- [ ] Tipo de suelo
- [ ] Pendiente
- [ ] Tipo de cobertura
- [ ] Socioeconómicos
- [ ] Mercados 
- [ ] Mano de obra
- [ ] Tenencia
- [ ] Vías de comunicación 
- [ ] Combustible

**Conservación**

- [ ] Soporte-Zonas de recarga
- [ ] Soporte-Cobertura forestal
- [ ] Soporte-Riqueza forestal
- [ ] Soporte-Biomasa aérea
- [ ] Regulación-Cobertura forestal
- [ ] Regulación-Captura de carbono
- [ ] Regulación-Especies melíferas
- [ ] Provisión-Cobertura
- [ ] Provisión-Cuerpos de agua
- [ ] Provisión-Parientes silvestres de cultivo
- [ ] Culturales-Cenotes y grutas
- [ ] Culturales-Población indígena
- [ ] Culturales-Zonas arqueológicas
- [ ] Culturales-ANP bioculturales
- [ ] Culturales-ADVC
- [ ] Culturales-Áreas de uso común
- [ ] Culturales-UMA
- [ ] Culturales-PSA
- [ ] Fragilidad eco-Integridad ecológica
- [ ] Fragilidad eco-Distancia a ANP y sitios RAMSAR
- [ ] Fragilidad eco-AICAS
- [ ] Fragilidad k-Densidad de dolinas
- [ ] Fragilidad k-Cenotes
- [ ] Vulnerabilidad hídrica-Vulnerabilidad intrínseca
- [ ] Vulnerabilidad hídrica-Zonas de recarga
- [ ] Vulnerabilidad hídrica-Humedales
- [ ] Vulnerabilidad hídrica-Cenotes
- [ ] Vulnerabilidad hídrica-Reforestación

**Energía industrial**

- [ ] Hidrocarburos-Carreteras
- [ ] Hidrocarburos-Localidades
- [ ] Gas-Distancia del gasoducto a zonas industriales
- [ ] Gas-Distancia del gasoducto a localidades
- [ ] Solar-Distancia a red eléctrica
- [ ] Solar-Cobertura
- [ ] Solar-Tenencia de la tierra
- [ ] Eólica-Velocidad
- [ ] Eólica-Distancia a red eléctrica
- [ ] Eólica-Cobertura
- [ ] Eólica-Distancia a caminos
- [ ] Eólica-Distancia a localidades
- [ ] Biomasa-Residuos urbanos
- [ ] Biomasa-Distancia a granjas porcícolas
- [ ] Biomasa-Residuos vegetales

**Comment by CorinaCantero** [comment]
### **AVISO**
@Nayita 

Para los metadatos de FV categóricas de silvopastoril poner la siguiente escala de transformación: 

Importancia | Valor
-- | --
Máxima | 1.00
Muy alta | 0.87
Alta | 0.80
Moderada | 0.70
Baja | 0.56
Muy baja | 0.33
Nula | 0.00

**Comment by Nayita** [comment]
### Metadatos modificados 

@CorinaCantero 

**Forestal maderable** 

- [x] Aprovechamiento
- [x] Tenencia
- [x] _Mercados_
- [x] Comunicación
- [x] Abastecimiento
- [x] Centro de almacenamiento

**Forestal no maderable** 

- [x] Aprovechamiento
- [x] Tenencia
- [x] Mercados
- [x] Comunicación
- [x] Abastecimiento
- [x] Centro de almacenamiento

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
