### ISSUE TITLE
Generar índice de peligros geológico-geomorfológicos 

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#88]
Peligros geológico-geomorfológicos

- Se descartaron capas que no tienen geometría o tabla de atributos
- Se buscó información descargable en: http://www.atlasnacionalderiesgos.gob.mx/portal/fenomenos/

- 1.  Vulnerabilidad por remoción de masa `SIG/desarrollo/sig_fomix/insumos/geocientifica/sgm/atlas_riesgos/Peligros/Geologicos/Remocion en Masa/Peligro/Vulnerabilidad_PRM.shp`
- 2. Modelo de hundimiento `SIG/desarrollo/sig_fomix/insumos/geocientifica/sgm/atlas_riesgos/Peligros/Geologicos/Hundimientos/Peligro/MODELO DE HUNDIMIENTO.shp`
- 3. Grado de fracturamiento `SIG/desarrollo/sig_fomix/insumos/geocientifica/sgm/atlas_riesgos/Peligros/Geologicos/Fallas y fracturas/Peligro/GRADO_DE_FRACTURAMIENTO.shp`
 
RUTA: SIG\desarrollo\sig_fomix\procesamiento\indice_peligro_geologico\

**Comment by paola-gp** [comment]
@Nayita 

### Figura

![image](https://user-images.githubusercontent.com/25205806/119404881-118d5480-bca6-11eb-9c7e-3fe022946e28.png)

**Comment by paola-gp** [comment]
### FV

![image](https://user-images.githubusercontent.com/25205806/119405580-156da680-bca7-11eb-9c81-cb02ef163281.png)

**Comment by paola-gp** [comment]
Definiciones: @CorinaCantero 

Vulnerabilidad por remoción de masa:
Susceptibilidad a deslizamiento o movimiento de una masa de roca, escombros o tierra a lo largo de una ladera.

Modelo de hundimiento:
Susceptibilidad al hundimiento de la superficie del suelo por actividades de minería o por la acción erosiva de las aguas subterráneas.

Grado de fracturamiento:
Susceptibilidad a la pérdida de continuidad entre bloques de roca con desplazamiento perpendicular al plano de ruptura.

**Comment by vichdzgeo** [comment]
## Procesamiento

- Se genera una copia de los insumos en la carpeta insumos
- se toma el campo de cada capa para categorizar las capas
- se arregla la capa modelo hundimiento ya que presenta huecos en zonas contiguas e intrínsecas de los polígonos
- se generan los insumos de las funciones de valor con las condiciones técnicas requeridas 
- se genera el índice mediante las funciones de valor y pesos iguales. El resultado se normaliza 
- el resultado es clasificado en 5 categorías con wf ,fp = 1.9.
- Se calculan áreas por categoría
- Se calculan áreas por categoría por región
-

Códigos  `SIG\desarrollo\sig_fomix\procesamiento\indice_peligro_geologico\codigos`



## Producto
ruta: SIG/desarrollo/sig_fomix/procesamiento/indice_peligro_geologico/procesamiento/

- [ ] indice_peligros_geomorfolicos_n_wf_1_90_5cats.tif Capa con 5 categorias clasificada con weber - Fechner, fp = 1.9
- [ ] fv_modelo_hundimiento.tif función de valor 
- [ ] fv_grado_fracturamiento.tif función de valor
- [ ] fv_vulnerabilidad_prm.tif función de valor
- [ ] indice_peligros_geomorfolicos_n.tif mapa normalizado resultado de la integración de los criterios con sus respectivos pesos (0.333 ) para cada uno. 
- [ ] 

## Áreas por categoría 
Categoría | km² | Porcentaje del   estado
-- | --:| --:
Muy alta | 3,944.8 | 10
Alta | 5,365.2 | 14
Moderada | 8,376.9 | 21
Baja | 10,801.0 | 27
Muy baja | 11,048.7 | 28

Ruta del archivo xlsx: `SIG/desarrollo/sig_fomix/procesamiento/indice_peligro_geologico/procesamiento/areas_categorias_peligros_geo.xlsx`



## Área por categoría por región 

Región | Categoría | km²
:--: | :-- | --:
I | Muy alta | 265.3
I | Alta | 728.4
I | Media | 766.6
I | Baja | 1,403.1
I | Muy baja | 1,341.2
II | Alta | 17.8
II | Media | 141.2
II | Baja | 1,236.2
II | Muy baja | 2,409.6
III | Muy alta | 44.2
III | Alta | 273.5
III | Media | 569.1
III | Baja | 887.8
III | Muy baja | 828.8
IV | Muy alta | 20.1
IV | Alta | 3.4
IV | Media | 154.8
IV | Baja | 1,099.2
IV | Muy baja | 1,685.6
V | Muy alta | 518.1
V | Alta | 1,139.5
V | Media | 3,946.8
V | Baja | 2,050.1
V | Muy baja | 212.5
VI | Muy alta | 672.9
VI | Alta | 636.4
VI | Media | 2,438.6
VI | Baja | 3,685.6
VI | Muy baja | 3,041.9
VII | Muy alta | 2,424.3
VII | Alta | 2,566.2
VII | Media | 359.8
VII | Baja | 439.0
VII | Muy baja | 1,529.2

ruta: `SIG\desarrollo\sig_fomix\procesamiento\indice_peligro_geologico\procesamiento\areas_categorias_peligros_geo_regiones.xlsx`


@CorinaCantero

**Comment by Nayita** [comment]
@CorinaCantero 

Lista figura en la siguiente ruta:
FOMIX/fmx_estudio_tecnico/caracterizacion_subs/figuras
Archivo: indice_p_geologico_morfologicos.png



![indice_r_geologicos_morfologicos](https://user-images.githubusercontent.com/25210323/119580753-a5cee880-bd86-11eb-9025-521680504a7e.png)

**Comment by CorinaCantero** [comment]
### AVISO

Después de hacer una revisión en el portal de Atlas de Riesgos de CENAPRED tanto estatal como nacional, se encontraron dos capas potenciales a ser utilizadas para complementar el análisis de peligros geológico-geomorfológico:

1.- SGM (2013) **'Mapa de susceptibilidad a hundimiento del terreno en el estado de Yucatán.'** Escala: sin dato. Servicio Geológico Mexicano. Proveedor de la información: Portal del Atlas Estatal de Riesgos del estado de Yucatán CENAPRED http://www.atlasnacionalderiesgos.gob.mx/AtlasEstatales/?&NOM_ENT=Yucat%C3%A1n&CVE_ENT=31

**Ubicación:** SIG\desarrollo\sig_fomix\insumos\geocientifica\sgm\atlas_riesgos_portal_cenapred\hundimientos\susceptibilidad_hundimientos.shp

![image](https://user-images.githubusercontent.com/44783182/135186993-dc263178-b73f-48cb-8e14-2f85df52881d.png)

`NOTA: La capa no se había utilizado porque no fue entregada cuando se recibió la información geográfica del Atlas de peligros por fenómenos naturales del SGM 2013' por parte de la SDS y en su momento no se encontraba disponible en el portal de CENAPRED`

2.- CENAPRED (2020) **'Mapa Nacional de Susceptibilidad por Inestabilidad de Laderas.'** Escala: sin dato. Centro Nacional de Prevención de Desastres. Proveedor de la información: Portal del Atlas Nacional de Riesgos CENAPRED http://www.atlasnacionalderiesgos.gob.mx/portal/fenomenos/

![image](https://user-images.githubusercontent.com/44783182/135187459-11e4cf40-7933-4801-a0dd-f5a2feab7ed3.png)

`Nota: las capas se pueden descargar en formato .kmz, sin embargo, no se pudieron utilizar porque al convertirlas en formato .kml para poder trabajar con ellas en Qgis solo se muestra un polígono de la extensión de la República Mexicana. Se solicitará la información a Andrés SDS o por el portal de transparencia`
![image](https://user-images.githubusercontent.com/44783182/135187604-6a537d8b-aa0c-4339-b150-74fec3734dc7.png)

[Aquí se pueden consultar los metadatos del mapa de susceptibilidad por inestabilidad de laderas](http://www.atlasnacionalderiesgos.gob.mx/descargas/Metodologias/SusceptibilidadLaderas.pdf)

En el portal de datos abiertos se encuentra la capa anunciada pero al descargarla arroja error.
![image](https://user-images.githubusercontent.com/44783182/135188314-70bc697c-36c2-4d31-9ed3-0d0f03500429.png)

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
