### ISSUE TITLE
Generar análisis BOCR #FOMIX

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/fomix#9]
Objetivo: Concluir el análisis y preparar informe de BOCR, con base en los criterios definidos por la SDS en el taller de diciembre. Se utilizará la técnica de PIVOT para priorizar las 11 estrategias definidas por la SDS en el taller de FODA.

**Ubicación:  FOMIX\fmx_diagnostico_institucional\bocr**

**Comment by dpedroza74** [comment]
@ofegarcia preparar el archivo excel con las estrategias ordenadas de acuerdo a su importancia para cada criterio de los cuatro elementos BOCR, para utilizar la técnica de rank order centroid. Subirlo al dropbox

**Comment by ofegarcia** [comment]
Buenas tardes.
El archivo *pesos_estrateg_orden* ya está la tabla de Excel en el dropbox,
ubicada en: FOMIX\fmx_diag_insti\bocr

Saludos

**Comment by dpedroza74** [comment]
Envié a Luis mi evaluación de las estrategias utilizando los pesos derivados del rank order centroid y la técnica pivot (hoja Pivot 2 cluster). Todos los pesos se llevaron a ideales (hoja Orden Lancis pesos ideales). Para cada elemento BOCR se calculó la combinación lineal ponderada (hoja PESOS FINALES).
El archivo excel fomix_pesos_estrateg_pivot_dpp 
está en la carpeta /FOMIX/fmx_diag_insti/bocr
