### ISSUE TITLE
Incorporar escenarios de vulnerabilidad al pronóstico #fomix

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#91]
https://atlasvulnerabilidad.inecc.gob.mx/page/index.html#zoom=undefined&lat=23.5000&lon=-101.9000&layers=1

- Se puede descargar la ficha técnica de cada base de datos para que vean como se construyó. 

- Si quieren ver lo que ya está en el informe de caracterización:
http://sig.apps.lancis.ecologia.unam.mx/

- Si quieren saber más detalles de los índices que incluimos en caracterización ver #90

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
