### ISSUE TITLE
Generar escenarios de cambio de cobertura

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#92]
## Procedimiento:

- [ ] Definir los escenarios de cambio de cobertura
- [ ] Generar los insumos
- [ ] Integrar los escenarios al modelo de cambio de cobertura

**Comment by iaga** [comment]
## Actividades:

- @iaga, @TatianaMerino revisar la documentación
- @iaga, @TatianaMerino cruzar los cambios de cobertura con las políticas
- @vichdzgeo obtener la información del índice de presión económica a la deforestación 
- @vichdzgeo generar los escenarios de OWA

**Comment by vichdzgeo** [comment]
## Extraer, reclasificar y calcular  áreas por región y por municipios del índice de Presión Económica de la Deforestación (IRDef) para Yucatán

[Fuente](https://datos.gob.mx/busca/dataset/economia-sectorial-ambiental-y-de-recursos-naturales/resource/af1251e1-f2d1-417e-a612-a3e302b89a47)

## Productos

ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\indices\irdef_mejora

Unidades 
- regiones_riesgo_cats.xlsx  (áreas por categoría de riesgo por región)
- municipio_riesgo_cats.xlsx (áreas por categoría de riesgo por municipio)
- area_categorias_riesgo_irdef.xlsx (áreas por categoria de riesgo) 

## Calcular áreas por categoría de cobertura por región para las series de uso de suelo y vegetación corregidas

### Producto
ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\cobertura_regiones

- regiones_usv_s1_cats.xlsx
- regiones_usv_s3_cats.xlsx
- regiones_usv_s5_cats.xlsx
- regiones_usv_s6_cats.xlsx

@iaga @TatianaMerino

**Comment by TatianaMerino** [comment]
## Definición de escenarios 
@ofegarcia @dpedroza74 @iaga 

### Tendencial 
Gráficas de tendencias de áreas por categoría de cobertura por región para las series de uso de suelo y vegetación corregidas: CARPETAS_TRABAJO\tmerino\cobertura\tableau\regiones_cobertura.twb
- Identificar programas de gobierno relacionados con los grandes cambios de cobertura

### Contextual y estratégico
- Definir factores forzantes biofísicos, económicos, sociales y vulnerabilidades (e.g. contaminación) por sectores
- Base de datos INEGI 2020
- Base de datos de programas de gobierno 
- Análisis de componentes principales
- Unión de aptitud sectorial con bases de datos

**Comment by TatianaMerino** [comment]
##  Insumo
Datos de cobertura por región para las series de uso de suelo y vegetación corregidas en un sólo archivo

Ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\cobertura_regiones\

Archivo: bd_cobertura_regiones.csv
Insumo: archivos de @vichdzgeo 10 junio 2021
Elaboración: @TatianaMerino 
Unidades en hectáreas

Campos:
serie|num_reg|	region|categoria|ha|year
--|--|--|--|--|--|
Número de serie de cobertura|Número de región|Nombre de la región|Tipo de cobertura|Número de hectáreas de cobertura|Año de la serie

- Gráficas en tableau, escenario tendencial @TatianaMerino 

## Pendientes: 

- [ ] Base de datos de cobertura corregidos por municipio @vichdzgeo @CorinaCantero 
- [ ] Clusters (tableau) de políticas regionales, estatales e infraestructura, con residuales @iaga 
- [ ] Base de datos y cruza (tableau) de cambio de cobertura, políticas, rezago social y población total @TatianaMerino

**Comment by vichdzgeo** [comment]
## Generar cruzas de series de uso de suelo y vegetación con municipios

## Producto
Ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\cobertura_municipios

Unidades en hectáreas

- bd_municipios_usv_s1_cats.xlsx
- bd_municipios_usv_s3_cats.xlsx
- bd_municipios_usv_s5_cats.xlsx
- bd_municipios_usv_s6_cats.xlsx

campos
cvegeo: Clave geográfica (ID) del municipio 
municipio: Nombre del municipio
clase:  clase de cobertura 
ha: hectáreas de la clase de cobertura por municipio

**Comment by vichdzgeo** [comment]
## Escenarios de aptitud con OWA

ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\owa_aptitud

archivos tif para los 16 sectores de aptitud, 3 escenarios por sector
ejemplo de nombrado 

- acuacultura_dulce_a_few.tif ( alpha = 0.5)
- acuacultura_dulce_half.tif (alpha = 1.0)
- acuacultura_dulce_most.tif (alpha = 2.0)


en la carpeta de **imagenes**

se encuentran las figuras de los mapas por cada escenario
- acuacultura_dulce_a_few_fig_sc_0_1.png ( los cortes para la escala de color se mantienen en 0 y 1 de forma equidistante)
- acuacultura_dulce_a_few_fig_sc_min_max.png ( los cortes para la escala de color son a partir del valor mínimo y máximo de la capa de forma equidistante) 

### Power points 

se encuentran dentro de la carpeta de **imágenes** es uno por sector
ejemplo: 
owa_acuacultura_dulce.pptx 
el orden del contenido  es el siguiente 

1. a_few_sc_0_1
2. half_sc_0_1
3. most_sc_0_1
4. a_few_sc_min_max
5. half_sc_min_max
6. most_sc_min_max

@iaga @TatianaMerino

**Comment by iaga** [comment]
## Transformar la cobertura a nivel municipal de hectáreas a porcentaje de área

- [ ] Cambiar el formato del banco de datos a wide
- [ ] Generar archivos con el porcentaje de área

**Comment by TatianaMerino** [comment]
## Índice de riesgo por presión económica de deforestación
SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\indices\irdef_mejora\

- municipio_riesgo_cats_wide.xlsx
- bd_municipio_riesgo_cats_wide.csv

Nota: falta poner los datos en % de área 

## Índice de rezago y pea
SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\indices\poblacion_rezago

- bd_poblacion_2020.xlsx: pea y población total en 2020 (INEGI)
- bd_rezago_2000_2020 .xlsx: irs (índice de rezago social), pobt (poblacion total) en 2000, 2010 y 2020

SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\tableau_luis
- Gráficas de población y rezago 
- Se actualizaron los bancos de datos con los correspondientes a 2020

**Comment by TatianaMerino** [comment]
## Análisis de correlaciones y PCA de programas federales
SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios\pca

- Análisis de correlaciones

Código: pca_cluster_corr.Rmd
Análisis: clusters_pca_corr_federales.xlsx

- PCA y residuales de programas federales 

Código:  pca_cluster_v2.Rmd
Archivo: prog_federales.xlsx

- Clusters

en \cambio_cobertura_ca\procesamiento\escenarios\tableau
Mapas: clusters_federal_instalado.twb
Gráficas: correlaciones.twb

Nota: se actualizó el irs_20 de las bases de datos.

**Comment by TatianaMerino** [comment]
# Cruzas de OWA con programas estatales, federales e infraestructura instalada

## Tableau
SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios\tableau\cruzas_prog_owa.twb

- Se realizaron cruzas de escenarios owa (a few, half, most) de porcentaje de territorio de aptitud "Muy alta".
- Se calcularon campos de capacidad instalada en metros cuadrados (m2) a hectáreas (ha)
- Se exportó la base de datos para las coordenadas paralelas. Archivos: bd_owa_prog.csv y bd_owa_prog_mod.csv (sin y con dummy, respectivamente)

### Insumos
- Bases de datos de escenarios owa: bd_a_few_muy_alta_por_wide.csv; bd_half_muy_alta_por_wide.csv; bd_most_muy_alta_por_wide.csv
- Base de datos de programas: bd_programas_ha.csv

Abreviatura|Programa federal|Unidades 
-- | -- | --
psa18 | CONAFOR_Pago por servicios   ambientales | superficie (ha)
psa19 | CONAFOR_Pago por servicios   ambientales | superficie (ha)
sv | SADER_Programa Sembrando Vida | superficie (ha)
gan | SADER_Programa Fomento Ganadero | importe (pesos)
ppb_mgt | SADER_Progrma Producción para el   Bienestar_maíz grano temporal | superficie (ha)
ppb_mgr | SADER_Progrma Producción para el   Bienestar_maíz grano riego | superficie (ha)
ppb_mil | SADER_Progrma Producción para el   Bienestar_milpa | superficie (ha)
ppb_mr | SADER_Progrma Producción para el   Bienestar_maíz riego | superficie (ha)
ppb_mt | SADER_Progrma Producción para el   Bienestar_maíz temporal | superficie (ha)
sagrfo | CONAFOR_Programa apoyos para el   desarrollo forestal sustentable_Sistemas agroforestales | superficie (ha)

Abreviatura|Capacidad instalada|Unidades 
-- | -- | --
granj_porci | SADER_SIAP_Infraestructura del sector agroalimentario_granjas porcinos | superficie del total de las   granjas del municipio (ha)
granj_avi | SADER_SIAP_Infraestructura del sector agroalimentario_granjas aves | superficie del total de las   granjas del municipio (ha)
apiario | SADER_SIAP_Infraestructura del sector agroalimentario_apiarios | número de apiarios
estab_lech | SADER_SIAP_Infraestructura del sector agroalimentario_cuencas y establos lecheros | superficie del total de establos del municipio (ha)
corr_engo | SADER_SIAP_Infraestructura del sector agroalimentario_corrales de engorda|superficie del total de corrales del municipio (ha)
tur_cuart | INEGI_Cuartos y unidades de hospedaje registrados por municipio según categoría turística del establecimiento | número de cuartos y unidades de hospedaje
tur_estab | INEGI_ Establecimientos de hospedaje registrados por municipio según tipo de alojamiento| número de establecimientos
ene_lim | Banco Nacional de Obras y Servicios Públicos, S.N.C., Proyectos México, Oportunidades de Inversión | presencia de proyectos de energía limpia (eólica o solar)
parq_ind | Sistema Mexicano de Promoción de Parques Industriales (SIMPPI) y Asociación Mexicana de Parques Industriales Privados (AMPIP)|presencia de parques industriales
sem_mgt | SADER_Estadística de Producción Agrícola_maíz de grano temporal | superficie sembrada (ha)
sem_mgr | SADER_Estadística de Producción Agrícola_maíz de grano riego | superficie sembrada (ha)

Abreviatura|Gobierno Yucatán_Programas regionales|Binario
-- | -- | --
Ind | política desarrollo industrial | presencia
Tur | política impulso al turismo | presencia
Tur_luj | política impulso al turismo_lujo | presencia
Tur_cul | política impulso al turismo_cultural | presencia
Tur_nat | política impulso al turismo_de naturaleza | presencia
Agrpec_inf | política desarrollo agropecuario_infraestructura movimiento | presencia
Agrpec_api | política desarrollo agropecuario_fomento apicultura | presencia
Agrpec_cit | política desarrollo agropecuario_fomento cítricos | presencia
Agrpec_pec | política desarrollo agropecuario__fomento pecuario | presencia
Pes_infr | política desarrollo pesquero_infraestructura | presencia
Acua | política desarrollo granjas acuícolas | presencia
Viv | política acceso a la vivienda | presencia
Ene | política energía asequible y no contaminante | presencia
Tran_tren | política conectividad y transporte_ferrovario | presencia
Tran_carr | política conectividad y transporte_carretero | presencia
Almacen | política conectividad y transporte_almacentamiento y movimiento   logístico mercancías | presencia
Urb | desarrollo urbano sustentable | presencia


## Coordenadas paralelas
Ruta de insumos: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios\coordenadas_par\insumos

Se utilizó una capa de municipios (municipios_cruzas_owa.shp) con un rectángulo dummie de cvegeo "31000" para ajustar la escala de la plataforma SIgNature al máximo 100% en los tres escenarios owa y al mínimo 0 en los programas y la capacidad instalada. 

- Las cruzas de cada sector están en una carpeta con el nombre del sector. La capa correspondiente se subió a la plataforma SigNature. 

Escenario owa|Traducción
A few | Expansivo
Half | Actual o Tendencial
Most | Restringido 

A continuación se ve el ejemplo del sector Acuacultura salobre:
![image](https://user-images.githubusercontent.com/57197109/127401860-f1fc6bdd-26fa-43fd-8e84-17d7ace18450.png)

- Datos estadísticos por sector para cada escenario

**Acuacultura salobre**
Estadístico | Expansivo | Tendencial | Restringido
--|--|--|--
Mínimo | 7 | 0 | 0
1er. Cuartil | 56 | 9 | 0
Mediana | 79 | 38 | 3
3er. Cuartil | 92 | 75 | 32
Máximo | 100 | 100 | 98

- Gráficos de cajas por sector para cada escenario
**Acuacultura salobre**
![image](https://user-images.githubusercontent.com/57197109/127403003-df7e5694-6c89-47c7-bff8-a0a96f800dbe.png)

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
