### ISSUE TITLE
Calcular los grupos para identificar las áreas a proteger, restaurar, conservar 

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/fomix#95]
ver #84 

- [x] subir los indicadores a la plataforma y crear un proyecto en SIGzoning 
- [x] Crear un proyecto en qgis para visualizar el resultado de grupos que contenga ANPS, USV serie VI, los indicadores, un mapa base de google. 

- [x] Calcular área en km² de los grupos

## Proyecto en SIGZoning 

[link del proyecto](http://pruebas.sigplanning.com.mx/sigzoning/detail/19/)
cuenta: fomix
Titulo: Áreas a proteger, conservar, restaurar
Descripción:  v3

## Proyecto en QGIS

directorio del proyecto: SIG\desarrollo\sig_fomix\procesamiento\areas_conservacion\grupos_indicadores

nombre del proyecto: mp_grupos_indicadores.qgs
@paola-gp 

## Área en km² por grupo
directorio del proyecto: SIG\desarrollo\sig_fomix\procesamiento\areas_conservacion\grupos_indicadores\bd_areas_grupos_km2.xlsx

**Comment by paola-gp** [comment]
- [ ] Humedales terrestres = 1
- [ ] Humedales costeros = 1
- [ ] ANP = 1
**Combinación lineal ponderada** 
- [ ] Calidad de parche peso = 0.20
- [ ] Biomasa, peso = 0.20
- [ ] Spp mielíferas, peso = 0.20 
- [ ] Vulnerabilidad, peso = 0.20
- [ ] Recarga al acuífero = 0.20

**Comment by paola-gp** [comment]
1. Generar escenario para SIGzoning:

- [ ] Calidad de parche
- [ ] Biomasa
- [ ] Spp mielíferas
- [ ] Vulnerabilidad del acuífero
- [ ] Recarga
- [ ] Generar máscara de humedales costeros, terrestres y zonas urbanas 2020
- [ ] Normalizar los indicadores después de aplicar la máscara

2. Generar promedio _400 m²_ de indicadores para SIGnature

**Comment by paola-gp** [comment]
### Modelo multicriterio 
Versión 6 de julio del 2021
/insumos/multicriterio
fv	w
biomasa	0.25181
recarga	0.1259
vul_acuifero	0.1479
riqueza_m	0.25181
cal_parche	0.22257
FP=1.3 Progresiva

### Generar mapa integrado, tabla y procedimiento:
Criterio | Indicadores | Área
-- | -- | --
ANP | Proteger |  
Humedales costeros y terrestres (fuera de   ANP) | Preservar o conservar nivel 1 |  
Categoría 5 multicriterio | Preservar o conservar nivel 1 |  
Categoría 4 multicriterio | Preservar o conservar nivel 2 |  
Categoría 3 multicriterio | Preservar o conservar nivel 3 |  
Categoría 4 multicriterio | Sin importancia relativa |  
Categoría 5 multicriterio | Sin importancia relativa |

**Comment by vichdzgeo** [comment]
continua en issue #84
