### ISSUE TITLE
Construir mapa de UGA a partir de grupos de aptitud - Propuesta - ET # fomix

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/fomix#96]
Ubicación: 
/FOMIX/fmx_estudio_tecnico/diagnostico/grupos_aptitud

## Última versión de UGAS

NOTA: en  el campo titulo_uga  se pueden diferenciar las UGAs que son ANP ya que traen el nombre de ANP que le corresponde.

[poety_uga_11mar2022.zip](https://github.com/lancis-apc/fomix/files/8277362/poety_uga_11mar2022.zip)

@serranoycandela @dpedroza74

**Comment by vichdzgeo** [comment]
## Versión sin restricciones 30 de junio
## OBSOLETO
cuenta: paolagp 
Titulo del proyecto: POETY V2	
Descripción:  POETY YUCATAN JUNIO 2021
 [liga](http://pruebas.sigplanning.com.mx/sigzoning/detail/13/)

## Versión sin anps federales ni estatales con tamaño de pixel a 10m  1 de julio
cuenta: fomix
Titulo del proyecto: Grupos de aptitud	
Descripción: 1 de julio 2021
[liga](http://pruebas.sigplanning.com.mx/sigzoning/detail/20/)

## Versión sin anps federales ni estatales con tamaño de pixel a 100m 2 de julio
cuenta: fomix
Titulo del proyecto: Grupos de aptitud 100m
Descripción: 2 de julio 2021 100x100	
[liga](http://pruebas.sigplanning.com.mx/sigzoning/detail/21/)

## Versión sin anps federales ni estatales con tamaño de pixel a 100m 8 de julio 

**NOTA: Esta versión se corre sin los sectores: pesca, acuacultura salobre, acuacultura dulce**

cuenta: fomix
Titulo del proyecto: Grupos de aptitud 100m
Descripción: 8 jul 2021 (exc p y ac)	
[liga](http://pruebas.sigplanning.com.mx/sigzoning/detail/23/)

**Comment by vichdzgeo** [comment]
## Procedimiento general 

Ruta de trabajo: CARPETAS_TRABAJO\apc_temeraria\politetico_divisivo
Maquina de trabajo: TEMERARIA

1. Verificación de insumos (qué mapas de aptitud se integran)
2. -  Creación de .csv  5 minutos
3. Verificación de exclusiones (ANP y sectores) (10 minutos – dependiendo de las exclusiones)
4. Nombre del escenario
5. Número de cortes iniciales (default = 15)  15 minutos
6. Revisión de mapa con agregados por cada corte
7. Revisión de promedios de aptitud y residuales de Gower
8. Revisión de histogramas y punto de corte 
9. Confirmación de grupos 
10. Reagrupación de agregados  10 minutos
11. Corte adicional de agregados  5 minutos (por corte)
12. Reglas heurísticas para la generación de UGA con base en grupos
13. ANP
14. Zonas urbanas?
15. Agregación por unidad mínima cartografiable (filtro de paso alto)

`ver a detalle procedimiento_uga.pptx`

### Reunión del 25 de septiembre:

- 1. Mapas de aptitud normalizados a 100 metros sin ANP `CARPETAS_TRABAJO\apc_temeraria\politetico_divisivo\insumos_aptitud\mapas_sin_anp_100m`
- 2. archivo csv: mapas_aptitud_sin_acu_pesca_100m.csv
- 3. Mapas sin ANP (Estatales, Federales, Municipales y privadas), No se incluyen los sectores: Pesca, Acuacultura de agua salobre, Acuacultura de agua dulce
- 4. Nombre del escenario: sin_acu_pesca_100m
- 5. ruta de productos:  ..\sin_acu_pesca_100m
- pasos de 6 a 8 se llevaron conforme en la reunión
- 9. Mapa de grupos final: grupos_v10.tif total de grupos: 13 

id | corte | Descripción
-- | -- | --
1 | grupo__1 | zonas urbanas, con algunos atributos costeros como dunas
2 | grupo__2_1_1_1 |  
3 | grupo__2_1_1_2 |  
4 | grupo__2_1_2_1 |  
5 | grupo__2_1_2_2 |  
6 | grupo__2_2_1_1_1 |  
7 | grupo__2_2_1_1_2 |  
8 | grupo__2_2_1_2_1 |  
9 | grupo__2_2_1_2_2 |  
10 | grupo__2_2_2_1_1 |  
11 | grupo__2_2_2_1_2 |  
12 | grupo__2_2_2_2_1 |  
13 | grupo__2_2_2_2_2 |  

`código en python para generar el análisis, el mapa de grupos y los residuales: politetico_divisivo_grass_aptitud_sin_acu_pesca_100m.py`
## Productos solicitados:
- Generación de bases de datos por grupo por pixel de los valores de los mapas de aptitud. (Insumo para el análisis de UGAs) ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\analisis_grupos\insumos
`Codigo en python: por_pixel_ugas.py`
- Matriz de residuales: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\insumos_sig\bd_residuales_grupos_v10.xlsx

**Comment by vichdzgeo** [comment]
Nombre del escenario | Versión de mapa de grupos | Descripción
-- | -- | --
e01 | grupos_v13 | Incluye 13 sectores   (sin pesca, ni acuacultura) y   excluye   ANP federales y estatales.
e02 | grupos_v6 | Incluye 13 sectores   (sin pesca, ni acuacultura) y   excluye   ANP federales y estatales.   Agricultura, bovino, forestal y   porcino con OWA mínimo.
e04|  grupos_v2 | Incluye 13 sectores   (sin pesca ni acuacultura) y   excluye   ANP federales y estatales. 12   sectores   con OWA mínimo   y urbano   con aptitud   original.
e05 | grupos_v3 |Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales.
e06 | grupos_v4 |  Incluye 13 sectores (sin pesca ni acuacultura) y excluye ANP federales y estatales. 10 sectores con OWA mínimo. Turismo de naturaleza, turismo de sol y playa, urbano  con aptitud original. 
e07 | grupos_v1 | Mapas   de aptitud Mapas incluye ANP Federales y Estatales. Mapa de aptitud de   conservación sin incluir el ANP como aprovechamiento actual (tal cual sale de   la plataforma) sin los sectores: pesca, acuacultura de agua salobre, acuacultura de agua dulce
**e07_b** | grupos_v4 | Incluye ANP Federales y Estatales. Mapa de aptitud de conservación sin incluir el ANP como aprovechamiento actual (tal cual sale de la plataforma) y el mapa de aptitud de urbano representado únicamente con la función de valor de crecimiento orgánico, reescalado.
e08 | grupos_v1 | Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 12 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. 1 sector con OWA mínimo: Bovino
e09 | grupos_V1 | Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 11 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. 2 sectores con OWA mínimo: Bovino, Porcino avícola
e10 |grupos_v1| Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 12 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. 1 sector con OWA mínimo: Forestal
e11 |grupos_v1| Incluye   13 sectores   (sin   pesca   ni   acuacultura),   incluye   ANP federales y estatales. 12 sectores con CLP, el mapa de aptitud de conservación sin incluir ANP como aprovechamiento actual. **1 sector con OWA mínimo: Porcino avícola**


## Productos solicitados

### Residuales 

ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_ugas\insumos_sig

- bd_residuales_grupos_v13_e01.xlsx
- bd_residuales_grupos_v6_e02.xlsx
- bd_residuales_grupos_v2_e04.xlsx

### Valores de aptitud por grupo 

ruta: CARPETAS_TRABAJO\apc_temeraria\analisis_grupos\insumos\grupos\escenarios

Se encuentran organizados por carpetas con el nombre del escenario:
- e01
- e02
- e04
- e05
- e06
- e07
- e08
- e09
- e10

> NOTA: Estos datos contienen una columna llamada id que corresponde al id del pixel

> NOTA 2: Se ha realizado la unión de dos grupos en la capa "grupos_v3" del escenario e06, el mapa actual ahora es "grupos_v4" , se agregan los archivos  bd_grupo_n_e06_grupos_v4_valor_aptitud.csv en la carpeta e06

### Base de datos  de los diferentes escenarios de grupos de aptitud.

ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_grupos

- bd_grupos_v13_e01_18_oct2021.xlsx
- bd_grupos_v6_e02_18_oct2021.xlsx
- bd_grupos_v2_e04_18_oct2021.xlsx
- bd_grupos_v3_e05_19_oct2021.xlsx
- bd_grupos_v3_e06_19_oct2021.xlsx
- bd_grupos_v4_e06_23_oct2021.xlsx
- bd_grupos_v1_e08_22_oct2021.xlsx
- bd_grupos_v1_e09_22_oct2021.xlsx
- bd_grupos_v1_e10_22_oct2021.xlsx

en las diferentes hojas del libro se encuentra:

1. Diagrama y mapa de grupos de aptitud analizados (diagrama&mapa)
2. Nombres de los campos de la hoja de síntesis de grupos (diccionario_datos)
3. Claves para identificar los nombres de los sectores (id_sectores)
4. Indicadores de síntesis de grupos que incluye promedios por sector, residuales de Gower, tipos de cobertura, presencia y tipo de humedales, cercanía a ANP, distribución en regiones, 5 municipios representativos, sectores prioritarios como resultado de inspección de gráfica de residuales  (sintesis_grupos) 
5. en adelante, los residuales de dos agregados (agregado&agregado)

### Visualizador de capas

Se ha creado un proyecto en Lizmap para ver a mayor detalle el mapa de grupos, los agregados por escenario y los mapas de aptitud para cada escenario:

El proyecto tiene:

indicadores
- limite_municipal sin nombres: solo se muestra el limite municipal
- limite_municipal : límite municipal y etiquetas con el nombre del municipio
- appcr_parches: muestra los parches con Biomasa mayor al 0.8 y Especies melíferas mayor al 0.8
- usv_serie6_100m_v4_corregida: Coberturas
- anp_femp: ANP Estatales, Federales, Municipales y privadas.
- localidades_yuc_mg2020_rubanas_sisal: Polígonos de las localidades clasificadas como urbanas en el marco geoestádistico 2020, se incluye el polígono de Sisal
- humedales_terrestres
- humedales_costeros
- regiones

Mapas de grupos por escenario:
- e01 : grupos_v13
- e02 : grupos_v6
- e04 : grupos_v2
- e05 : grupos_v3
- e06 : grupos_v3

Aptitud:e0x Mapas de aptitud para el escenario e0X
Agregados:e0x mapas de agregados por nivel del escenario e0X

Ingresar con la cuenta de owa, desplazarse entre los diferentes proyectos hasta encontrar  **Escenarios mapa de grupos**
@iaga @TatianaMerino

**Comment by vichdzgeo** [comment]
## Aviso
21 de octubre.

- Ya se encuentran disponibles los datos de la corrida e07v1
- Se corrige el error de la etiqueta en todos los archivos de excel de id_sectores de los archivos de  base de datos de los diferentes escenarios de grupos de aptitud. 
@iaga @TatianaMerino

**Comment by vichdzgeo** [comment]
## Aviso 
25 octubre

- ya se encuentran los datos disponibles de las corridas e08,e09 y e10
- Se agregan datos para el e06, como resultado de la unión de dos grupos. En este momento la última versión de grupos es: grupos_v4 para e06

@TatianaMerino @iaga

**Comment by vichdzgeo** [comment]
## Aviso

Los residuales  se encuentran en la hoja "sintesis_grupos"  de los archivos de las bases de datos de los diferentes escenarios de grupos de aptitud.

ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_grupos

También se ha creado una aplicación sencilla para visualizarlos todos en una sola página web

https://residuales.herokuapp.com/

En esta aplicación se puede:
- activar / desactivar algún sector en la gráfica, por ejemplo: Urbano, haciendo clic sobre el color en la leyenda: 
![image](https://user-images.githubusercontent.com/38017509/139332049-c9c78788-538e-41d6-b774-72bbd853e428.png)

- Hacer zoom a un determinado grupo o grupos de la gráfica, para ello sobre la gráfica se dibuja un rectángulo al mantener y presionar clic izquierdo sobre los grupos de interés.
![image](https://user-images.githubusercontent.com/38017509/139332482-2d7f7ae1-36bc-414e-9fee-59a4b9743f13.png)

Al soltar, la gráfica solo mostrará los grupos seleccionados

![image](https://user-images.githubusercontent.com/38017509/139332566-15c19ae6-e522-4726-8cdd-08f9deece084.png)

Para deshacer la selección, hacer doble clic en la gráfica.

- Cada escenario tiene su descripción y un enlace para ver su respectivo esquema, la figura se abre en una ventana nueva del explorador.

- El proyecto en lizmap ya se encuentra actualizado.

@TatianaMerino @iaga

**Comment by vichdzgeo** [comment]
# Aviso
4 de noviembre

Ya se encuentran disponibles los datos de la corrida e11v1

@iaga @TatianaMerino

**Comment by vichdzgeo** [comment]
# Escenario para construir las UGA a partir de los grupos de aptitud

## Escenario  e07b


Ruta de trabajo: CARPETAS_TRABAJO\apc_temeraria\politetico_divisivo


### Insumos: 
archivo CSV : mapas_aptitud_e07_b.csv

### Procesamiento

**Código en python - GRASS GIS 7.8.5**

archivo python: politetico_divisivo_grass_aptitud_e07_b.py

**Nombre del repositorio y directorio de mapas**
sin_restricciones_100m > e07_b

**Carpeta de salida**

e07_b/

**Diagrama de agregados**

![image](https://user-images.githubusercontent.com/38017509/145868856-693e7021-a6c0-4fbc-ae29-fdc79ee2353d.png)


**Síntesis de grupos y residuales por corte**
ruta: FOMIX\fmx_estudio_tecnico\propuesta\analisis_grupos\bd_grupos_v6_e07_b_6_dic_2021.xlsx

**Comment by paola-gp** [comment]
### Insumos para la generación del mapa de UGA en formato vectorial


1. grupos_v6_e07_b_6_dic_2021 a 100 m 

- r.clump a 100 m por grupo de aptitud y calcular áreas de cada id final por grupo 

### Integrar proyecto para análisis y desagregación de grupos que incluya: 
- Índicadores de la síntesis de grupos
- Zonas urbanas -INEGI 2020
- Zonas de aprovechamiento actual de los sectores

### Intersección vectorial
- Carreteras
-Límite oficial estatal
-Municipios
- Áreas naturales protegidas federales
- Áreas naturales protegidas estatales 
- Áreas naturales protegidas municipales

**Comment by paola-gp** [comment]
### Procedimiento de construcción de UGA 17-dic-21
### Segunda parte 

- [x] r.clump `('r.clump',
        input=r_input,
        output=r_output,
        threshold=0.01,
        minsize=100,
        overwrite=True)` `clump('grupos_v6','grupos_v6_clump_100m',path_salida,minimo=100)
`
- [x] Documentar el efecto de aumentar el threshold. La documentación de Grass indica lo sensible que es a este parámetro e iniciar con 0.01. 
![image](https://user-images.githubusercontent.com/38017509/146621430-d44553c1-bd2a-4ecd-8e4a-a3a16e6a4563.png)


- [ ] Cambiar tamaño de pixel a 1 m (nueva región) y vectorizar
- [x] Agregar polígonos menores a 100 ha al grupo más afín
- [ ] Documentar los nombres de campos y evitar **id_uga** cuando pueda confundirse con las UGA del modelo final, usar **id_pol**. 
- [x] Verificar topología de insumos antes de iniciar una intersección 

### Tercera parte
- [x] Al tp_xx modificarle límites estatales 
- [x] Al tp_xx2 agregar y cortar polígonos para construir una UGA única de ANP 
- [x] Al tp_xx3 agregar y cortar polígonos para construir una UGA única de áreas urbanas

**Comment by vichdzgeo** [comment]
## Cuarta parte

- [x] Cortar polígonos por límite municipal
- [x] Limpiar polígonos y verificar topología
- [ ] Buscar y aplicar  herramienta o método de suavizado de borde
- [ ] calcular áreas
- [ ] generar residuales por polígono
- [ ] zonas costeras dividirlas con base en el POETCY

**Comment by vichdzgeo** [comment]
## Generación del mapa de UGA 
Reunión: 7-enero-2022
Ruta de productos:

SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\grupos_a_ugas
Ruta de trabajo: CARPETAS_TRABAJO\apc_temeraria\grupos_a_ugas


- Generar r.clump a 1,000m 2,500m y 5,000m
- Se selecciona r.clumo a 2,500m para trabajar

### Tareas:

- [x] Generar base de datos con, id_pol,id_grupo,id_region, y ha

- [x] Trabajar la capa de carreteras para generar polígonos cerrados, insumo que será ocupado para refinar algunas UGA

## Productos

En ruta de productos: bd_clump_por_grupos_v6_2500m_regiones.xlsx

**Comment by paola-gp** [comment]
26-ene-22
### Procedimiento de selección de UGA

Insumo: grupos_v6_clump_2500m_v4_con_anp

Integrar polígonos prioritarios en o inmersos en parches mayores a 1000 km²
1. Disolver con carreteras 
2. Disolver con áreas prioritarias

**Comment by vichdzgeo** [comment]
## Residuales con de UGAS que incluyen los sectores de acuacultura y pesca

NOTAS: 
- Se calcularon con las UGAs que no tienen zonificación dentro de ANP.
- Total de UGAs: 176.
- La UGA 163 no aparece por cuestiones de escala. representa un problema topológico de la ANP de Ría Lagartos (UGA 162) 

[bd_residuales_ugas_yucatan_anp.xlsx](https://github.com/lancis-apc/fomix/files/8043984/bd_residuales_ugas_yucatan_anp.xlsx)

@iaga @TatianaMerino

**Comment by vichdzgeo** [comment]
## Actualización 

## Base de datos de residuales por UGA con los siguientes cambios:
- mapa de aptitud restrictivo (most) de  Acuacultura dulce
- mapa de aptitud restrictivo (most) de  Acuacultura salobre
- mapa de aptitud restrictivo (most) de  Pesca con **datos únicamente en la zona ocupada por las UGAs del POETCY** 

[bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most.xlsx](https://github.com/lancis-apc/fomix/files/8050601/bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most.xlsx)

@iaga @TatianaMerino

**Comment by vichdzgeo** [comment]
## aviso
[bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most_v3.xlsx](https://github.com/lancis-apc/fomix/files/8051369/bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most_v3.xlsx)
@iaga

**Comment by vichdzgeo** [comment]
## aviso 
[bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most_v4.xlsx](https://github.com/lancis-apc/fomix/files/8051444/bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most_v4.xlsx)
@iaga

**Comment by vichdzgeo** [comment]
aviso
mapa de aptitud restrictivo (most) de Acuacultura dulce
mapa de aptitud restrictivo (most) de Acuacultura salobre
mapa de aptitud restrictivo (most) de Pesca con datos únicamente en la zona ocupada por las UGAs del POETCY

notas: 
acuaculturas solo con valores >= a 0.8
pesca con valores >= 0.6


[bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most_v5.xlsx](https://github.com/lancis-apc/fomix/files/8051605/bd_residuales_ugas_yucatan_anp_sin_acu_pesca_most_v5.xlsx)

@iaga

**Comment by vichdzgeo** [comment]
## Procedimiento técnico en la edición de polígonos.

Proceso | Minutos
-- | --:
Cargar versión de capa a editar | 1
Filtrar polígonos a editar | 1
Activar Capas guía para edición de   linderos | 1
Edición de geometría interior | 5
Edición de geometría sobrante | 3
Unión a polígonos colindantes / Edición   de tabla de atributos | 2
Salvar edición y/o exportar versión de capa | 1
Revisión visual de edición | 1

Tiempo promedio en edición de Polígonos = 15 minutos +- 5 (Dependiendo lo complejo de la sinuosidad  y extensión del polígono) 

@paola-gp

**Comment by vichdzgeo** [comment]
## Actualización 

11 de marzo

**No actualizar archivos con DASS hasta recibir confirmación**

Para corregir la ausencia de una UGA con id=5 se renumeran las UGAS.
0 >1
1 >2
2 > 3
3 >4
4 >5


Renumeración de UGAS

- [ ] Capa vectorial de UGAS
- [ ] Capa raster de UGAS
- [ ] Figuras General y Zoom de las UGAS que cambian 
- [ ] Generar indicadores básicos
- [ ] Bases de datos para el sistema

**Comment by vichdzgeo** [comment]
## Generar figuras de UGA 

ruta de trabajo: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\ugas

rutas para almacenar figuras: ruta de trabajo + /figuras/

### Proyecto para figuras generales
proyecto: automatizacion_ugas.qgs

### Proyecto para figuras de acercamiento

probar con diferentes etiquetas por tamaño de población

proyecto: automatizacion_ugas_zoom_1abril.qgs

Favor de colocar muestra de figuras  de acercamiento y general
@Nayita

**Comment by Nayita** [comment]
### AVISO

Figura de UGA general

![image](https://user-images.githubusercontent.com/25210323/162803793-babae134-f9cf-47fa-9eab-9d4fcb8bf78e.png)

**Comment by Nayita** [comment]
### AVISO

Relación de figuras de UGAs que no tienen ninguna población cercana en cualquier escala:

- 16
- 153
- 169
- 174
- 175

Relación de figuras de UGAs que no parecen tener zoom en cualquier escala:

- 95
- 109

Relación de figuras de UGAs que tienen muchas poblaciones cercanas en cualquier escala:

- 72
- 77
- 82
- 93
- 95
- 111
- 112
- 119
- 134
- 137
- 140
- 146
- 164
- 167
- 171

Figura de UGA que no se ve: 160

**Comment by vichdzgeo** [comment]
# Actualización - versiones finales de las figuras

## Figura del mapa de grupos

![fig_grupos_aptitud](https://user-images.githubusercontent.com/38017509/165426425-5b430f8b-65bc-4b27-91f7-43dd0fc513e3.png)


## Figura del mapa de UGA

![fig_ugas](https://user-images.githubusercontent.com/38017509/165426442-4befb294-36a6-486d-beac-7201e29fd450.png)



@dpedroza74

**Comment by vichdzgeo** [comment]
## Área por grupo de aptitud 


Grupo | superficie (km²)
-- | --:
1 | 1,870.2
2 | 2,231.9
3 | 633.2
4 | 1,858.3
5 | 4,850.7
6 | 4,428.0
7 | 3,054.3
8 | 2,446.7
9 | 6,727.1
10 | 3,369.5
11 | 8,066.7

**Comment by vichdzgeo** [comment]
## Actualización de figuras

@Nayita de favor podrías actualizar las figuras generales y de zoom para las UGA:

- 95
- 158 hasta la 164 

ya he colocado la nueva versión de la capa de UGA en ambos proyectos. solo falta sacar las figuras individuales para las UGAs mencionadas.

**Comment by Nayita** [comment]
### AVISO

Lista la actualización de figuras.
Ruta: SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\ugas\figuras\zoom\finales y
SIG\desarrollo\sig_fomix\procesamiento\analisis_aptitud\ugas\figuras\generales

**Importante**

La figura de la UGA 164 presenta muchos sitios en la versión que tenía menor número de localidades. Favor de revisar

@vichdzgeo

**Comment by paola-gp** [comment]
- [ ] Las figuras de algunas UGA no se ven. Hay que editarlas manualmente para que se resalten. @Nayita  
- [x] Las figuras tienen que ser de menor resolución a manera de que el conjunto completo no rebase 50 Mb y se siga viendo bien @vichdzgeo

**Comment by vichdzgeo** [comment]
@paola-gp se ha modificado la resolución de las figuras y se ha generado de nuevo el archivo zip.

En lo que vemos detalles de las UGA que no se ven, ya se podría hacer una prueba para definir la resolución

**Comment by vichdzgeo** [comment]
## UGAS con problemas de visualización en figuras

- 161 Zoom y General
- 95 Zoom y General
- 7 General

@Nayita 

- importante: generar una nueva copia de los proyectos de qgis para la generación de las figuras

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
