### ISSUE TITLE
Definir escenarios pronóstico OWA

### ISSUE THREAD

**Issue by iaga** [lancis-apc/fomix#98]
## Objetivo
A partir de los distintos escenarios de owa, definir los escenarios para pronóstico.

## Carpeta de trabajo:
\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa

**Comment by TatianaMerino** [comment]
# Cruzas de OWA con programas estatales, federales e infraestructura instalada

## Tableau
SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios\tableau\cruzas_prog_owa.twb

- Se realizaron cruzas de escenarios owa (a few, half, most) de porcentaje de territorio de aptitud "Muy alta".
- Se calcularon campos de capacidad instalada en metros cuadrados (m2) a hectáreas (ha)
- Se exportó la base de datos para las coordenadas paralelas. Archivos: bd_owa_prog.csv y bd_owa_prog_mod.csv (sin y con dummy, respectivamente)

### Insumos
- Bases de datos de escenarios owa: bd_a_few_muy_alta_por_wide.csv; bd_half_muy_alta_por_wide.csv; bd_most_muy_alta_por_wide.csv
- Base de datos de programas: bd_programas_ha.csv

Abreviatura|Programa federal|Unidades 
-- | -- | --
psa18 | CONAFOR Pago por servicios ambientales | superficie (ha)
psa19 | CONAFOR Pago por servicios ambientales | superficie (ha)
sv | SADER Programa Sembrando Vida | superficie (ha)
gan | SADER Programa Fomento Ganadero | importe (pesos)
ppb_mgt | SADER Programa Producción para el Bienestar maíz grano temporal | superficie (ha)
ppb_mgr | SADER Programa Producción para el Bienestar maíz grano riego | superficie (ha)
ppb_mil | SADER Programa Producción para el Bienestar milpa | superficie (ha)
ppb_mr | SADER Programa Producción para el Bienestar maíz riego | superficie (ha)
ppb_mt | SADER Programa Producción para el Bienestar maíz temporal | superficie (ha)
sagrfo | CONAFOR Programa apoyos para el desarrollo forestal sustentable sistemas agroforestales | superficie (ha)

Abreviatura|Capacidad instalada|Unidades 
-- | -- | --
granj_porci | SADER SIAP Infraestructura del sector agroalimentario granjas porcinos | superficie del total de las   granjas del municipio (ha)
granj_avi | SADER SIAP Infraestructura del sector agroalimentario granjas aves | superficie del total de las   granjas del municipio (ha)
apiario | SADER SIAP Infraestructura del sector agroalimentario apiarios | número de apiarios
estab_lech | SADER SIAP Infraestructura del sector agroalimentario cuencas y establos lecheros | superficie del total de establos del municipio (ha)
corr_engo | SADER SIAP Infraestructura del sector agroalimentario_corrales de engorda|superficie del total de corrales del municipio (ha)
tur_cuart | INEGI Cuartos y unidades de hospedaje registrados por municipio según categoría turística del establecimiento | número de cuartos y unidades de hospedaje
tur_estab | INEGI Establecimientos de hospedaje registrados por municipio según tipo de alojamiento| número de establecimientos
ene_lim | Banco Nacional de Obras y Servicios Públicos, S.N.C., Proyectos México, Oportunidades de Inversión | presencia de proyectos de energía limpia (eólica o solar)
parq_ind | Sistema Mexicano de Promoción de Parques Industriales (SIMPPI) y Asociación Mexicana de Parques Industriales Privados (AMPIP)|presencia de parques industriales
sem_mgt | SADER Estadística de Producción Agrícola maíz de grano temporal | superficie sembrada (ha)
sem_mgr | SADER Estadística de Producción Agrícola maíz de grano riego | superficie sembrada (ha)

Abreviatura|Programas regionales del Gobierno Yucatán (presencia)
-- | -- 
Ind | política desarrollo industrial 
Tur | política impulso al turismo
Tur_luj | política impulso al turismo lujo
Tur_cul | política impulso al turismo cultural
Tur_nat | política impulso al turismo de naturaleza
Agrpec_inf | política desarrollo agropecuario infraestructura movimiento
Agrpec_api | política desarrollo agropecuario fomento apicultura
Agrpec_cit | política desarrollo agropecuario fomento cítricos
Agrpec_pec | política desarrollo agropecuario fomento pecuario
Pes_infr | política desarrollo pesquero infraestructura
Acua | política desarrollo granjas acuícolas
Viv | política acceso a la vivienda
Ene | política energía asequible y no contaminante
Tran_tren | política conectividad y transporte ferrovario
Tran_carr | política conectividad y transporte carretero
Almacen | política conectividad y transporte almacenamiento y movimiento logístico mercancías
Urb | desarrollo urbano sustentable


## Coordenadas paralelas
Ruta:SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios\coordenadas_par

### Insumos:
Se utilizó una capa de municipios (municipios_cruzas_owa.shp) con un rectángulo dummy de cvegeo "31000" para ajustar la escala de la plataforma SIgNature al máximo 100% en los tres escenarios owa y al mínimo 0 en los programas y la capacidad instalada. 

- Las cruzas de cada sector están en una carpeta con el nombre del sector. La capa correspondiente se subió a la plataforma SigNature. 

Escenario owa|Traducción
--|--
A few | Expansivo
Half | Actual o Tendencial
Most | Restringido 

### Análisis:
A continuación se ve el ejemplo del sector Acuacultura salobre:
![image](https://user-images.githubusercontent.com/57197109/127401860-f1fc6bdd-26fa-43fd-8e84-17d7ace18450.png)

- Datos estadísticos por sector para cada escenario

**Acuacultura salobre**
Estadístico | Expansivo | Tendencial | Restringido
--|--|--|--
Mínimo|7|0|0
1er. Cuartil|56|9|0
Mediana|79|38|3
3er. Cuartil|92|75|32
Máximo|100|100|98

- Gráficos de cajas por sector para cada escenario
**Acuacultura salobre**
![acua_sal_box](https://user-images.githubusercontent.com/57197109/127414706-64cde280-646b-498c-bcd3-aa7eec576ab5.png)

- Cruzas de aptitud sectorial con programas y capacidad instalada: 

Sector | Programa federal | Capacidad instalada | Programa regional
-- | -- | -- | --
Acuacultura salobre |   |   | Acua
Agricultura de riego | ppb_mgr; ppb_mr | sem_mgr | Agrpec_inf; Agrpec_cit
Agricultura de temporal | ppb_mgt; ppb_mt | sem_mgt | Agrpec_inf; Agrpec_cit
Apicultura |   | apiario | Agrpec_api
Bovino | gan | corr_engor; estab_lech | Agrpec_pec
Conservación | sv; psa19; psa18 |   |  
Energía |   | ene_lim | Ene
Forestal | sv; sagrfo; psa19; psa18 |  
Industrial |   | parq_ind | Ind; Tran_tren; Tran_carr; Almacen
Milpa | ppb_mil; sagrfo |   |  
Minería |   |   | Tran_tren; Tran_carr; Almacen
Pesca |   |   | Pes_inf
Porcino avícola |   | granj_porci; granj_avi
Turismo de naturaleza |   | tur_cuart; tur_estab | Tur; Tur_nat
Turismo de sol y playa |   | tur_cuart; tur_estab | Tur; Tur_luj
Urbano |   |   | Urb; Viv

**Comment by iaga** [comment]
# Exploración de escenarios owa

**Descripción:** Algoritmo para generar los escenarios del pronóstico y definición de escenarios.

## Axiomas
A1. Los inversionistas tienen aversión al riesgo por lo que prefieren las zonas que mantienen la  mayor aptitud, aún en el escenario pesimista para realizar sus actividades.
A2. Los conservacionistas buscan maximizar la protección de las áreas más valiosas para la biodiversidad y la integridad funcional de los ecosistemas.
A3. La severidad de los conflictos está relacionada con el grado de aptitud para los dos sectores.

## Sectores "inversionista" a cruzar con Conservación:
- Turismo
- Urbano
- Porcino-Avícola
- Energía
- Minería

## Etapa 1. Cruza restrictivo <inversionista> - restrictivo <conservación> (most-most).
@vichdzgeo 

![imagen](https://user-images.githubusercontent.com/41757755/128072635-11fa475e-82f9-4642-8825-ff70f35aff6f.png)

- [ ] Mapa con las cruzas

Calcular a partir de los bancos de datos\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\owa_aptitud\evolucion\matrices\unidos
- [ ] Área total de MA/MA en ha. 
- [ ] Porcentaje de MA/MA con respecto al área total de MA (inversionista)
- [ ] Porcentaje del municipio libre para porcino y para conservación
- [ ] Generar banco de datos con los municipios más importantes: MA/MA diferente de 0

cvegeo | municipio | porcino_MA | conservacion_MA | p_MA_c_MA | ha_mun|area_libre_p|porc_libre_p|area_libre_con|porc_libre_con
-- | -- | -- | -- | -- | -- | -- | -- | --| -- 

- [ ] Generar banco con los datos a nivel estatal

inversionista | area_libre_inv | porc_libre_inv | area_libre_con | porc_libre_con
-- | -- | -- | -- | --
Turismo |   |   |   |  
Urbano |   |   |   |  
Porcino-Avícola |   |   |  
Energía |   |   |   |  
Minería |   |   |   |  

## Etapa 2. Cruza restrictivo <inversionista> - base <conservación> (most-half)
@vichdzgeo 

- [ ] Mapa con las cruzas
- [ ] Área total de MA/MA, MA/A, MA/Mod en ha
- [ ] Porcentaje de MA/MA, MA/A, MA/Mod con respecto al área total de MA (inversionista)
- [ ] Porcentaje del municipio libre para porcino y para conservación
- [ ] Generar banco de datos con los municipios más importantes: MA/MA diferente de 0

cvegeo | municipio | porcino_MA | conservacion_M | conservacion_A | conservacion_MA | p_MA_c_M | p_MA_c_A | p_MA_c_MA | ha_mun|area_libre_p|porc_libre_p|area_libre_con|porc_libre_con
-- | -- | -- | -- | -- | -- | -- | -- | --| -- | --| -- | --| --

- [ ] Generar banco con los datos a nivel estatal

inversionista | area_libre_inv | porc_libre_inv | area_libre_con | porc_libre_con
-- | -- | -- | -- | --
Turismo |   |   |   |  
Urbano |   |   |   |  
Porcino-Avícola |   |   |  
Energía |   |   |   |  
Minería |   |   |   |  


**Ojo:** dejar fuera el área nula

## Etapa 3. Seleccionar los municipios más relevantes
@TatianaMerino 
- [ ] A partir de los bancos de datos clasificar los municipios (PCA, cuartiles)

**Comment by vichdzgeo** [comment]
## Mapas de aptitud categorizados Escenarios Half, Most y A few
Ruta: SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\owa_aptitud\categorizados

Diccionario

 valor del pixel | Aptitud|
 -- | -- |
0 | Nula (Zona de exclusión) |
1 | Muy baja |
2 | Baja |
3 | Moderada |
4 | Alta |
5 | Muy alta |

@TatianaMerino @iaga 

## Generar cruzas y visualizador de mapas 

Generar un proyecto por conflicto entre sectores:
Ejemplo : Porcino y avícola vs Conservación

Capas que debe contener 
 nombre capa | Descripción | NOTAS | 
 -- | -- | -- |
Límites municipales | | |
Conflicto: porcino avícola (MIN) - conservación (MIN) | (Cruza entre el mapa de aptitud de porcino avícola (Escenario most) y el mapa de aptitud de conservación (Escenario most)|  poder visualizar todas e individualmente las categorías|
Conflicto: porcino avícola (MIN) - conservación (CLP) | (Cruza entre el mapa de aptitud de porcino avícola (Escenario most) y el mapa de aptitud de conservación (Escenario half)| ppoder visualizar todas e individualmente las categorías |
Conflicto: porcino avícola (MIN) - conservación (MAX) | (Cruza entre el mapa de aptitud de porcino avícola (Escenario most) y el mapa de aptitud de conservación (Escenario a few)| poder visualizar todas e individualmente las categorías |
Aptitud: porcino avícola (MIN) | categoría Muy Alta de aptitud porcino avícola del escenario (most) | 
Aptitud: conservación  (MIN) | categoría Moderada, Alta y  Muy Alta de aptitud porcino avícola del escenario (most) | 
Aptitud: conservación  (CLP) | categoría Moderada, Alta y  Muy Alta de aptitud porcino avícola del escenario (half) | 
Aptitud: conservación  (MAX) | categoría Moderada, Alta y  Muy Alta de aptitud porcino avícola del escenario (a few) | 

![image](https://user-images.githubusercontent.com/38017509/128264983-654b4f61-baca-4363-9590-7ff970daefa5.png)

**Comment by TatianaMerino** [comment]
## Otros insumos a considerar: 

- [ ] Matriz de conflictos que lleve al visualizador correspondiente
- [ ] Tablas dinámicas de los bancos de datos
- [ ] Presentación ppt de mapa con tabla

**Comment by iaga** [comment]
# Cruzas grass

## Insumos
- Escenarios de OWA. \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\owa_aptitud\categorizados
- Capa de municipios. \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\municipios_yuc.tif
- Cruzas obtenidas en grass. \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\bancos_cruzas\insumos

## Salidas
\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\bancos_cruzas\salidas
- Bancos de datos con los campos requeridos para el análisis de PCA. bd_pca_xx_conservacion_mun_most_yy.csv (https://github.com/lancis-apc/fomix/issues/98#issuecomment-895605273)
- Bancos a nivel municipal completos con todas las cruzas y los cálculos. bd_xx_conservacion_mun_most_yy_full.csv
- Bancos a nivel estatal completos. bd_estatal_inv_con_most_xx_full.csv

donde **xx** representa al sector inversionista y **yy** al escenario con el que se realiza la cruza

## Scripts

\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\bancos_cruzas
- **pca_bancos.Rmd.** Bancos de datos con los campos requeridos para el análisis de PCA.
- **unmelt_raster_mun_v2.Rmd.** Bancos a nivel municipal completos con todas las cruzas y los cálculos. 
- **estatales.Rmd.** Bancos a nivel estatal completos. 

## Descripción banco de datos

### Municipal

Campo | Descripción
-- | --
cvegeo | Clave geográfica
municipio | Número de municipio
0_0 | Área de cruza entre las categorías X y Y, donde X es la categoría del   sector inversionista (NULA) y Y la del sector conservación
0_1 | Área de cruza entre las categorías X y Y, donde X es la categoría del   sector inversionista (NULA) y Y la del sector conservación
0_2 | Área de cruza entre las categorías X y Y, donde X es la categoría del   sector inversionista (NULA) y Y la del sector conservación
. | .
. | .
. | .
5_3 | Área de cruza entre las categorías X y Y, donde X es la categoría del   sector inversionista (Muy Alta) y Y la del sector conservación
5_4 | Área de cruza entre las categorías X y Y, donde X es la categoría del   sector inversionista (Muy Alta) y Y la del sector conservación
5_5 | Área de cruza entre las categorías X y Y, donde X es la categoría del   sector inversionista (Muy Alta) y Y la del sector conservación
area_total_mun | Área total del municipio: Suma de todas las cruzas
area_exc_inv | Área de exclusión para el sector inversionista: Suma de todas las cruzas   en categoría NULA (0) para el sector X
area_exc_con | Área de exclusión para el sector conservación: Suma de todas las cruzas   en categoría NULA (0) para del sector Y
area_total_inv_MA | Área total con aptitud MA para el sector inversionista: Suma de todas las   cruzas en categoría MA (5) para el sector X, sin la zona de exclusión
area_total_con_MA | Área total con aptitud MA para el sector conservación: Suma de todas las   cruzas en categoría MA (5) para el sector Y, sin la zona de exclusión
area_total_inv_A | Área total con aptitud A para el sector inversionista: Suma de todas las   cruzas en categoría A (4) para el sector X, sin la zona de exclusión
area_total_con_A | Área total con aptitud A para el sector conservación: Suma de todas las   cruzas en categoría A (4) para el sector Y, sin la zona de exclusión
area_total_inv_Mod | Área total con aptitud Mod para el sector inversionista: Suma de todas   las cruzas en categoría Mod (3) para el sector X, sin la zona de exclusión
area_total_con_Mod | Área total con aptitud Mod para el sector conservación: Suma de todas las   cruzas en categoría Mod (3) para el sector Y, sin la zona de exclusión
area_total_inv_B | Área total con aptitud B para el sector inversionista: Suma de todas las   cruzas en categoría B (2) para el sector X, sin la zona de exclusión
area_total_con_B | Área total con aptitud B para el sector conservación: Suma de todas las   cruzas en categoría B (2) para el sector Y, sin la zona de exclusión
area_total_inv_MB | Área total con aptitud MB para el sector inversionista: Suma de todas las   cruzas en categoría MB (1) para el sector X, sin la zona de exclusión
area_total_con_MB | Área total con aptitud MB para el sector conservación: Suma de todas las   cruzas en categoría MB (1) para el sector Y, sin la zona de exclusión
area_total | Área total del municipio, sin zona de exclusión: Suma de todas las cruzas   excepto las que inician o terminan con cero
por_area_total_inv_MA | Porcentaje de área con aptitud MA para el sector inversionista:   area_total_inv_MA/area_total
por_area_total_inv_A | Porcentaje de área con aptitud A para el sector inversionista:   area_total_inv_A/area_total
por_area_total_inv_Mod | Porcentaje de área con aptitud Mod para el sector inversionista:   area_total_inv_Mod/area_total
por_area_total_inv_MB | Porcentaje de área con aptitud MB para el sector inversionista:   area_total_inv_MB/area_total
por_area_total_inv_B | Porcentaje de área con aptitud B para el sector inversionista:   area_total_inv_B/area_total
sum_por_inv | Suma de los porcentajes de todas las aptitudes para el sector   inversionista: Campo de verificación
area_total_con | Área total del municipio, sin zona de exclusión: Suma de todas las áreas   totales para conservación, campo de verificación, debe ser igual a area_total
por_con_MA | Porcentaje de área con aptitud MA para el sector conservación:   area_total_con_MA/area_total
por_con_A | Porcentaje de área con aptitud A para el sector conservación:   area_total_con_A/area_total
por_con_Mod | Porcentaje de área con aptitud Mod para el sector conservación:   area_total_con_Mod/area_total
por_con_MB | Porcentaje de área con aptitud MB para el sector conservación:   area_total_con_MB/area_total
por_con_B | Porcentaje de área con aptitud B para el sector conservación:   area_total_con_B/area_total
sum_por_con | Suma de los porcentajes de todas las aptitudes para el sector   conservación: Campo de verificación
por_1_1 | Porcentaje de área de cruza X_Y del sector inversionista con respecto al área total MB 
por_1_2 | Porcentaje de área de cruza X_Y del sector inversionista con respecto al área total MB 
por_1_3 | Porcentaje de área de cruza X_Y del sector inversionista con respecto al área total MB 
. | .
. | .
. | .
por_5_3 | Porcentaje de área de cruza X_Y del sector inversionista con respecto al   área total MA
por_5_4 | Porcentaje de área de cruza X_Y del sector inversionista con respecto al   área total MA
por_5_5 | Porcentaje de área de cruza X_Y del sector inversionista con respecto al   área total MA
por_con_0_1 | Porcentaje de área de cruza X_Y del sector conservación con respecto al   área total MB
por_con_1_1 | Porcentaje de área de cruza X_Y del sector conservación con respecto al   área total MB
por_con_2_1 | Porcentaje de área de cruza X_Y del sector conservación con respecto al   área total MB
. | .
. | .
. | .
por_con_3_5 | Porcentaje de área de cruza X_Y del sector conservación con respecto al   área total MA
por_con_4_5 | Porcentaje de área de cruza X_Y del sector conservación con respecto al   área total MA
por_con_5_5 | Porcentaje de área de cruza X_Y del sector conservación con respecto al   área total MA
area_libre_inv_MA_umb_MA | Área libre inversionista: inversionista MA-conservación MA
area_libre_inv_MA_umb_A | Área libre inversionista: inversionista MA - suma conservación MA y A
area_libre_inv_MA_umb_Mod | Área libre inversionista: inversionista - suma conservación MA, A y Mod
por_area_libre_inv_MA_umb_MA | Porcentaje de área libre inversionista:   area_libre_inv_MA_umb_MA/area_total
por_area_libre_inv_MA_umb_A | Porcentaje de área libre inversionista:   area_libre_inv_MA_umb_A/area_total
por_area_libre_inv_MA_umb_Mod | Porcentaje de área libre inversionista:   area_libre_inv_MA_umb_Mod/area_total

**Comment by iaga** [comment]
# Verificar áreas totales

@vichdzgeo 

En reunión con Luis, se observó que las áreas totales son distintas entre escenarios de owa. Como ejemplo: porcino_avicola_conservacion_most_a_few.csv. ¿Podrías validar que esto es correcto? 

![imagen](https://user-images.githubusercontent.com/41757755/128735648-184cd5d8-577d-4b2d-8384-eb091dfa0337.png)

**Comment by iaga** [comment]
@vichdzgeo Indicar la ruta del proyecto en GIS utilizado como ejemplo para el visualizador de mapas (https://github.com/lancis-apc/fomix/issues/98#issuecomment-893023174)

**Comment by TatianaMerino** [comment]
## Insumos PCA
@iaga 
- Ejemplo de los insumos a extraer de los bancos de datos de las cruzas:

cvegeo | municipio | porcino_MA | conservacion_M | conservacion_A | conservacion_MA | p_MA_c_M | p_MA_c_A | p_MA_c_MA | ha_mun|area_libre_p|porc_libre_p
-- | -- | -- | -- | -- | -- | -- | -- | --| -- | --| -- |

**Comment by iaga** [comment]
# Visualizador de mapas: Turismo sol y playa

@vichdzgeo 
![imagen](https://user-images.githubusercontent.com/41757755/129406226-588c8ac4-d2d3-42f1-aba7-8c9b70f7d7b8.png)

Categorías para la paleta de colores

MA-MA
.
.
.
Mod-Mod

**Comment by iaga** [comment]
# Análisis conflictos

Se realizaron las cruzas para todos los conflictos considerando las definiciones de la matriz de conflictos: **sector_a** afecta a **sector_b**

## Cruzas en grass

### Insumos
- Escenarios de OWA. \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\owa_aptitud\categorizados
- Capa de municipios. \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\insumos\municipios_yuc.tif

### Salidas
\CARPETAS_TRABAJO\igrave\avance_personal\grass\prueba1\salida_cruzas

### Script
Código en python para realizar las cruzas de todos los conflictos \CARPETAS_TRABAJO\igrave\avance_personal\grass\prueba1\insumos\estadisticas_con_grass.py. **Nota:** por simplicidad del script, es necesario renombrar las capas que tienen factor de progresión distinto, se realizó una copia de las mismas y se ubicaron en la ruta insumos

## Bancos de datos  

### Insumos
- Cruzas en grass. \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\bancos_cruzas\insumos

### Salidas
\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\bancos_cruzas\salidas
- Bancos de datos con los campos requeridos para el análisis de **PCA** .\pca\bd_pca_xx_yy_mun_owa_xx_owa_yy.csv (https://github.com/lancis-apc/fomix/issues/98#issuecomment-895605273)
- Bancos a nivel **municipal** completos con todas las cruzas y los cálculos. \municipal\bd_xx_yy_mun_owa_xx_owa_yy_full.csv
donde **xx** representa al sector a , **yy** al escenario con el que se realiza la cruza (sector b), **owa_xx** el escenario de owa asociado al sector xx y **owa_yy** el escenario asociado al sector yy.
- Banco a nivel **estatal**, con todos los conflictos para todos los escenarios \estatal\bd_estatal_conflictos.csv


### Scripts

\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\bancos_cruzas
- **unmelt_raster_mun_sector_a_b.Rmd.** Bancos a nivel **municipal** completos con todas las cruzas y los cálculos. 
- **estatal_sector_a_b.Rmd.** Bancos a nivel **estatal** completos. 
- **pca_bancos_sector_a_b.Rmd** Bancos a nivel municipal para el análisis de **PCA**.

## Análisis de componentes principales

### Insumos
- Bancos de datos con los campos requeridos para el análisis de **PCA** \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\bancos_cruzas\salidas\pca\bd_pca_xx_yy_mun_owa_xx_owa_yy.csv (https://github.com/lancis-apc/fomix/issues/98#issuecomment-895605273)

### Salidas
\SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\pca\salidas
- html
- pdf
**pca_sector_a_sector_b_mun_owa_a_owa_b.zzzz** Resultados del PCA para cada conflicto, donde **xx** representa al sector a , **yy** al escenario con el que se realiza la cruza (sector b), **owa_xx** el escenario de owa asociado al sector xx y **owa_yy** el escenario asociado al sector yy.


### Scripts
- **pca_cruzas_sector_a_b.Rmd.** R markdown para generar el análisis de PCA para un par de sectores.
- **generar_markdowns.R** Permite correr el archivo **pca_cruzas_sector_a_b.Rmd.** para todos los sectores.

**Comment by iaga** [comment]
@TatianaMerino 
- [x] Verificar la descripción de los campos del banco de datos https://github.com/lancis-apc/fomix/issues/98#issuecomment-893552803
- [x] Revisar la salida de los markdown de los PCA. Ruta: \SIG\desarrollo\sig_fomix\procesamiento\cambio_cobertura_ca\procesamiento\escenarios_pronostico_owa\pca\salidas\html
- [x] Revisar con Luis los proyectos cargados en el visualizador
- [ ] Indicar las correcciones necesarias para cada caso (banco de datos, pca, visualizador)

**Comment by iaga** [comment]
@vichdzgeo 
Documentar en este issue el visualizador de mapas

**Comment by iaga** [comment]
# Equivalencia escenarios owa

Escenario | Plataforma
-- | --
most | MIN
half | CLP
a few | MAX

**Comment by Nayita** [comment]
Actividad concluida. Se cierra el issue.
